### PR TITLE
[SYCL] Add atomic64 aspect decoration to atomic_ref<T *>

### PR DESCRIPTION
**Pull request by maksimsab**
atomic_ref<T *> uses 64-bit atomics and it should be decorated with the corresponding aspect.

fixes: https://github.com/intel/llvm/issues/12743

### CODE REVIEW

**Review by Alcpz — CHANGES_REQUESTED** [review]
`syclcompat/math_ops.cpp` and `syclcompat/atomic_comp_exchange.cpp` also mention this fix. The changes to `atomic_arith.cpp` have to be applied there as well.

**Comment by maksimsab** [comment]
@Alcpz Thank you for pointing out. I changed them accordingly.

**Review by Alcpz — APPROVED** [review]
Looks good! Thanks! :smile:

**Comment by maksimsab** [comment]
@intel/llvm-gatekeepers Can we merge it?

**Comment by steffenlarsen** [comment]
Re-triggering stalled CUDA workflow.

**Comment by maksimsab** [comment]
strange error in lit configuration:
```
lit.py: /__w/llvm/llvm/llvm/sycl/test-e2e/lit.cfg.py:665: error: Cannot detect device aspect for cuda:gpu
```

I will try to sync `sycl` branch.

**Review by mdtoguchi — COMMENTED** [review]
Inadvertent add for driver review?  I see nothing from our team that requires approval.

**Comment by maksimsab** [comment]
@mdtoguchi Yes, sorry for inconvenience.

**Comment by maksimsab** [comment]
@intel/llvm-gatekeepers Can we merge it?

**Pull request merged**
