### PR TITLE
[CI] Switch labels for OCL x64 job

### PR DESCRIPTION
**Pull request by alexbatashev**
Use any x64 machine

### CODE REVIEW

**Comment by bader** [comment]
@alexbatashev, any clues why `SYCL / Default Linux / HIP AMD GPU Test Suite` fails?

**Review by bader — APPROVED** [review]
LGTM, but I like to see green pre-commit checks.

**Comment by alexbatashev** [comment]
> LGTM, but I like to see green pre-commit checks.

I think this test is flaky. I'll open a tracker and disable it.

**Comment by alexbatashev** [comment]
Created https://github.com/intel/llvm-test-suite/issues/661 and https://github.com/intel/llvm-test-suite/pull/662

**Comment by bader** [comment]
Thanks!

**Pull request merged**
