### PR TITLE
[SYCL] Move on-device tests to intel/llvm-test-suite#243

### PR DESCRIPTION
**Pull request by vladimirlaz**

### CODE REVIEW

**Review by dm-vodopyanov — APPROVED** [review]
LGTM, something is wrong with clang-format check, it shouldn't be caused by the changes in this patch.

**Comment by vladimirlaz** [comment]
> g with clang-format check, it shouldn't be caused by t

It  looks like clang-format check failed if patch contains only removed files.

**Comment by bader** [comment]
> > g with clang-format check, it shouldn't be caused by t
> 
> It looks like clang-format check failed if patch contains only removed files.

Could someone point the logs for the failed check, please? I see that chang-format-check has passed.

**Comment by vladimirlaz** [comment]
> > > g with clang-format check, it shouldn't be caused by t
> > 
> > 
> > It looks like clang-format check failed if patch contains only removed files.
> 
> Could someone point the logs for the failed check, please? I see that chang-format-check has passed.

I restarted the job and it passed. Initially it failed without any log. It looks like it was action automation failure.

**Pull request merged**
