### PR TITLE
[NFC][Opaque Pointer][clang] Remove code within ifndef INTEL_SYCL_OPAQUEPOINTER_READY

### PR DESCRIPTION
**Pull request by jsji**
- Remove code in INTEL_SYCL_OPAQUEPOINTER_READY==0
- clang-format

This should be NFC, as INTEL_SYCL_OPAQUEPOINTER_READY is always 1 since #10888 .

### CODE REVIEW

**Comment by jsji** [comment]
Ping @intel/dpcpp-clang-driver-reviewers @intel/dpcpp-cfe-reviewers . Thanks.

**Review by mdtoguchi — APPROVED** [review]
OK for driver

**Review by elizabethandrews — APPROVED** [review]

**Review by smanna12 — APPROVED** [review]
FE changes LGTM

**Comment by jsji** [comment]
@intel/llvm-gatekeepers Can we get this merged? Thanks!

**Pull request merged**
