### PR TITLE
[CI] Move CUDA AWS job to nightly

### PR DESCRIPTION
**Pull request by sarnex**
There have been no issues with the self-hosted runners over the last 1+ week since we enabled them (July 19), and the only test failures on them have been actual product issues. Removing this job saves resources and developer time waiting for CI (self-hosted runners are faster).

### CODE REVIEW

**Comment by aelovikov-intel** [comment]
I would prefer to move this to Nightly instead, so that we can keep the AWS setup maintained in case we'd suddenly need it in future.

**Comment by sarnex** [comment]
@aelovikov-intel Do you mean we use AWS only in the Nightly and don't use the self-hosted runners there?

**Comment by aelovikov-intel** [comment]
> @aelovikov-intel Do you mean we use AWS only in the Nightly and don't use the self-hosted CUDA runners there?

Yes for the first part, doesn't matter for the second :)

**Comment by sarnex** [comment]
Ok, let me try.

**Comment by sarnex** [comment]
I don't think I can fully test this in a PR because AWS is still running here even though I changed the trigger workflow, so let me make the change and watch the nightly. I will work to get it running in the nightly in a follow-up PR if this doesn't end up working.

**Comment by sarnex** [comment]
Draft again, addressing feedback from Andrei

**Comment by sarnex** [comment]
@aelovikov-intel Feedback should be addressed and we can see it works in this manual nightly run:

https://github.com/intel/llvm/actions/runs/10252343290/job/28363118249

I canceled the other jobs after CUDA finished as to not waste resources

**Review by aelovikov-intel — APPROVED** [review]

**Pull request merged**
