### PR TITLE
Disabling mem2reg by default

### PR DESCRIPTION
**Pull request by AlexeySotkin**
Translator is not supposed to optimize code.
Also mem2reg complicates debugger's work.

Signed-off-by: Alexey Sotkin <alexey.sotkin@intel.com>

### CODE REVIEW

**Comment by bader** [comment]
Note: I've asked @AGindinson to pull all patches from the translator repo here: #347.
Please, sync with him and decide if this PR still needed.

**Comment by AGindinson** [comment]
> Note: I've asked @AGindinson to pull all patches from the translator repo here: #347.
> Please, sync with him and decide if this PR still needed.

@bader, this PR and #347 are the only commits that were made to Translator since the last pulldown. Maybe proceeding with both could be faster?

**Comment by bader** [comment]
> > Note: I've asked @AGindinson to pull all patches from the translator repo here: #347.
> > Please, sync with him and decide if this PR still needed.
> 
> @bader, this PR and #347 are the only commits that were made to Translator since the last pulldown. Maybe proceeding with both could be faster?

There should be no difference then and I prefer to stick with the regular process.
Please, make sure that there is no patches committed to SPIR-V translator in SYCL repo, which are not committed to Khronos repository yet.

**Comment by AGindinson** [comment]
@AlexeySotkin I've created #351 that combines our PR's so that the usual procedure is carried out. I believe this PR may be closed

**Pull request closed without merging**
