### PR TITLE
[SYCL][libdevice] add fmaf and fmaf with rounding mode support in imf libdevice

### PR DESCRIPTION
**Pull request by jinge90**

### CODE REVIEW

**Review by maksimsab — APPROVED** [review]
sycl-post-link part LGTM.

**Comment by jinge90** [comment]
Hi, @zettai-reido and @akolesov-intel
Could you help review __imf_fma/fmaf_r* functions?
Thanks very much.

**Review by akolesov-intel — APPROVED** [review]
Looks good to me, thank you for taking care, Jin Ge!

Just one general question: as far as I understand we need to implement basic operation with direct rounding emulations because neither LLVM nor IGC do not provide rounding control built-ins, is this correct? Is this rounding control going to be implemented later by compiler/run-time? I am asking because current emulations doesn't make much sense for customers since they are extremely slow in comparison to HW operations, it makes them unusable. Do we plan to replace these emulations by HW operations with direct rounding control when implemented? Thanks!

**Comment by jinge90** [comment]
> Looks good to me, thank you for taking care, Jin Ge!
> 
> Just one general question: as far as I understand we need to implement basic operation with direct rounding emulations because neither LLVM nor IGC do not provide rounding control built-ins, is this correct? Is this rounding control going to be implemented later by compiler/run-time? I am asking because current emulations doesn't make much sense for customers since they are extremely slow in comparison to HW operations, it makes them unusable. Do we plan to replace these emulations by HW operations with direct rounding control when implemented? Thanks!

Hi, @akolesov-intel 
Yes, we have such plan.
Thanks very much.

**Comment by jinge90** [comment]
Hi, @againull 
Could you help review this patch?
Thanks very much.

**Review by againull — APPROVED** [review]

**Pull request merged**
