### PR TITLE
[SYCL][Test E2E] Change 'CHECK-NEXT' to 'CHECK' of abort_internalization.cpp

### PR DESCRIPTION
**Pull request by myler**
To make the test more robust with ZE_DEBUG environment.

### CODE REVIEW

**Comment by myler** [comment]
Unrelated failure:
`TEST 'SYCL :: Basic/handler/handler_mem_op.cpp' FAILED`

**Review by victor-eds — CHANGES_REQUESTED** [review]
Can we get a rationale of this change and an actual description? I understand why the change is needed, but I'd argue that should be part of the description

**Comment by victor-eds** [comment]
I'd move the "because the output break continuous checking with "// CHECK-NEXT" directives." part from the commit title to the body, similar to: "Do not run this test as L0 debug output breaks `CHECK-NEXT` directives in test"

**Comment by myler** [comment]
@victor-eds please check again, I moved reason to description.

**Comment by jandres742** [comment]
> Do not run this test as L0 debug output breaks `CHECK-NEXT` directives in test.

shouldn't we try to fix the test or the way we are running, instead of not running it?

**Comment by myler** [comment]
> > Do not run this test as L0 debug output breaks `CHECK-NEXT` directives in test.
> 
> shouldn't we try to fix the test or the way we are running, instead of not running it?

Hi @sommerlukas, 
I checked the commit history, seems you are this test owner, could you help to check this issue? Is it possible to fix the test with `ZE_DEBUG` environment?

**Comment by Naghasan** [comment]
> I checked the commit history, seems you are this test owner, could you help to check this issue? Is it possible to fix the test with ZE_DEBUG environment?

We are no level 0 expert and we do not use it beyond what the CI requires us to do. We are happy to assist you in making the test more resilient, but when it comes to the actual test failures / testing environment, you have the data.

IIRC from similar failure with debug level 0, the issue is simply that you have a debug dump that is interleaved with the sycl log we are checking. In this test the `CHECK-NEXT` is probably overkill (it is checking for a sequence so it makes sense, but if that sequence goes out of sync the test will fail anyway), so I would be happy to merge a patch changing this to `CHECK`.

**Comment by victor-eds** [comment]
Changing to `CHECK` LGTM. Better than not running the test.

**Comment by myler** [comment]
> > I checked the commit history, seems you are this test owner, could you help to check this issue? Is it possible to fix the test with ZE_DEBUG environment?
> 
> We are no level 0 expert and we do not use it beyond what the CI requires us to do. We are happy to assist you in making the test more resilient, but when it comes to the actual test failures / testing environment, you have the data.
> 
> IIRC from similar failure with debug level 0, the issue is simply that you have a debug dump that is interleaved with the sycl log we are checking. In this test the `CHECK-NEXT` is probably overkill (it is checking for a sequence so it makes sense, but if that sequence goes out of sync the test will fail anyway), so I would be happy to merge a patch changing this to `CHECK`.

Have you done the change or do I need to make this change in current PR?

**Comment by sommerlukas** [comment]
> > > I checked the commit history, seems you are this test owner, could you help to check this issue? Is it possible to fix the test with ZE_DEBUG environment?
> > 
> > 
> > We are no level 0 expert and we do not use it beyond what the CI requires us to do. We are happy to assist you in making the test more resilient, but when it comes to the actual test failures / testing environment, you have the data.
> > IIRC from similar failure with debug level 0, the issue is simply that you have a debug dump that is interleaved with the sycl log we are checking. In this test the `CHECK-NEXT` is probably overkill (it is checking for a sequence so it makes sense, but if that sequence goes out of sync the test will fail anyway), so I would be happy to merge a patch changing this to `CHECK`.
> 
> Have you done the change or do I need to make this change in current PR?

We don't have an active PR to incorporate this change, so you can do it as part of this PR.

**Review by sommerlukas — APPROVED** [review]

**Review by victor-eds — APPROVED** [review]

**Comment by myler** [comment]
Unrelated failures:
```
Failed Tests (10):
  SYCL :: Basic/context-with-multiple-devices.cpp
  SYCL :: Basic/fpga_tests/fpga_aocx.cpp
  SYCL :: Basic/fpga_tests/fpga_dsp_control.cpp
  SYCL :: Basic/fpga_tests/fpga_latency_control_lsu.cpp
  SYCL :: Basic/fpga_tests/fpga_latency_control_pipe.cpp
  SYCL :: Basic/fpga_tests/fpga_lsu.cpp
  SYCL :: Basic/fpga_tests/global_fpga_device_selector.cpp
  SYCL :: DeviceLib/complex-fpga.cpp
  SYCL :: OnlineCompiler/online_compiler_OpenCL.cpp
  SYCL :: Scheduler/DISABLED_DataMovement.cpp
```

**Comment by myler** [comment]
Ping @intel/llvm-gatekeepers this PR is ready to merge.

**Comment by sommerlukas** [comment]
@myler Can you please update the PR description (which will become the commit message) to match the changes made in the PR?

**Comment by myler** [comment]
> @myler Can you please update the PR description (which will become the commit message) to match the changes made in the PR?

Thanks for the reminder, I updated the title and removed unused description.

**Comment by myler** [comment]
Ping @intel/llvm-gatekeepers this PR is ready to merge.

**Pull request merged**
