### PR TITLE
[UR] Update tag to get the fix for urProgramGetGlobalVariablePointer

### PR DESCRIPTION
**Pull request by againull**
UR PR: https://github.com/oneapi-src/unified-runtime/pull/2370

### CODE REVIEW

**Comment by againull** [comment]
********************
Failed Tests (1):
  SYCL :: Graph/Update/dyn_cgf_different_arg_nums.cpp

is probably caused  by this UR change: https://github.com/oneapi-src/unified-runtime/pull/1975
because it seems to be the only command-buffer change in the range. Haven't verified it though.

Same failure is observed in another UR tag update: https://github.com/intel/llvm/pull/16154

**Comment by againull** [comment]
> CUDA backend failure:
> 
> Failed Tests (1): SYCL :: Graph/Update/dyn_cgf_different_arg_nums.cpp
> 
> is probably caused by this UR change: [oneapi-src/unified-runtime#1975](https://github.com/oneapi-src/unified-runtime/pull/1975) because it seems to be the only command-buffer change in the range. Haven't verified it though.
> 
> Same failure is observed in another UR tag update: #16154

Actually, I am not sure about this as that PR affects L0 only. And I don't see any cuda related changes in the range of commits.

**Comment by againull** [comment]
Graph/Update/dyn_cgf_different_arg_nums.cpp  requires an update because of this change https://github.com/oneapi-src/unified-runtime/pull/2240/files#diff-281e113df062b6fd2da62d677a876ace550500168f5716d84a6f54e176703843L16142-L16151   by @pbalcer  in https://github.com/oneapi-src/unified-runtime/pull/2240

**Comment by pbalcer** [comment]
> I believe Graph/Update/dyn_cgf_different_arg_nums.cpp requires an update because of this change https://github.com/oneapi-src/unified-runtime/pull/2240/files#diff-281e113df062b6fd2da62d677a876ace550500168f5716d84a6f54e176703843L16142-L16151 by @pbalcer in [oneapi-src/unified-runtime#2240](https://github.com/oneapi-src/unified-runtime/pull/2240)

Thanks for spotting this. Evan created a PR with a fix here: https://github.com/intel/llvm/pull/16157

**Comment by callumfare** [comment]
@againull The UR PR has merged so I've bumped the tag here

**Review by kbenzie — APPROVED** [review]

**Pull request merged**
