### PR TITLE
[SYCL] Fix a few warnings during build scripts configuration

### PR DESCRIPTION
**Pull request by denis-kabanov**

### CODE REVIEW

**Review by vladimirlaz — APPROVED** [review]

**Review by bader — COMMENTED** [review]
Is the goal of this patch to make CMake configuration step free from warnings?
If so, we need to fix this warning:
```
CMake Warning (dev) in /localdisk2/sycl_ci/buildbot/worker/Lit_With_Cuda/llvm.src/libclc/CMakeLists.txt:
  A logical block opening on the line
    /localdisk2/sycl_ci/buildbot/worker/Lit_With_Cuda/llvm.src/libclc/CMakeLists.txt:86 (if)
  closes on the line
    /localdisk2/sycl_ci/buildbot/worker/Lit_With_Cuda/llvm.src/libclc/CMakeLists.txt:88 (endif)
```
Tagging code author for awareness - @Naghasan.

@AlexeySotkin, @AlexeySachkov, please, help with disabling SPIR-V translator project related warnings:
```
CMake Warning at /localdisk2/sycl_ci/buildbot/worker/Lit_With_Cuda/llvm.src/llvm-spirv/test/CMakeLists.txt:32 (message):
  spirv-as not found! SPIR-V assembly tests will not be run.
CMake Warning at /localdisk2/sycl_ci/buildbot/worker/Lit_With_Cuda/llvm.src/llvm-spirv/test/CMakeLists.txt:37 (message):
  spirv-link not found! SPIR-V test involving the linker will not be run.
CMake Warning at /localdisk2/sycl_ci/buildbot/worker/Lit_With_Cuda/llvm.src/llvm-spirv/test/CMakeLists.txt:42 (message):
  spirv-val not found! SPIR-V generated for test suite will not be validated.
```

**Review by bader — COMMENTED** [review]
I found one more warning on Windows:
```
-- Performing Test HAVE_POSIX_REGEX -- failed to compile
CMake Warning at utils/benchmark/CMakeLists.txt:248 (message):
  Using std::regex with exceptions disabled is not fully supported
```

**Comment by denis-kabanov** [comment]
> I found one more warning on Windows:
> 
> ```
> -- Performing Test HAVE_POSIX_REGEX -- failed to compile
> CMake Warning at utils/benchmark/CMakeLists.txt:248 (message):
>   Using std::regex with exceptions disabled is not fully supported
> ```

This warning is related to benchmark tests, so we need to turn on BENCHMARK_ENABLE_EXCEPTIONS to fix it, but how does this affect the performance of such tests? 
OR I can just suppress it. 
@bader what do you think will be better?

**Comment by bader** [comment]
From the offline discussion, I got an impression that your goal is not fix all the warnings. AFAIK, DPC++ doesn't use "benchmark test", so I don't think we should fix this warning.

**Comment by Naghasan** [comment]
```
If so, we need to fix this warning:

CMake Warning (dev) in /localdisk2/sycl_ci/buildbot/worker/Lit_With_Cuda/llvm.src/libclc/CMakeLists.txt:
  A logical block opening on the line
    /localdisk2/sycl_ci/buildbot/worker/Lit_With_Cuda/llvm.src/libclc/CMakeLists.txt:86 (if)
  closes on the line
    /localdisk2/sycl_ci/buildbot/worker/Lit_With_Cuda/llvm.src/libclc/CMakeLists.txt:88 (endif)
Tagging code author for awareness - @Naghasan.
```

Thanks for the fix :)

**Comment by denis-kabanov** [comment]
I think that warnings about spirv is quite important, so they should remain.

**Review by bader — APPROVED** [review]

**Comment by bader** [comment]
> I think that warnings about spirv is quite important, so they should remain.

I don't think emitting warnings is a good choice for missing tools notification, I think `STATUS` fits better, but translator issues shouldn't be fixed in this repository anyway.

**Review by vladimirlaz — APPROVED** [review]

**Comment by Naghasan** [comment]
> I don't think emitting warnings is a good choice for missing tools notification

my 2 cents: part of the testing depends on these tools, so I think warning is the appropriate choice.

**Pull request merged**
