### PR TITLE
[DeviceSanitizer] Fix invalid-argument lit tests failure

### PR DESCRIPTION
**Pull request by AllanZyne**
UR: https://github.com/oneapi-src/unified-runtime/pull/2114

fix: https://github.com/intel/llvm/issues/15449

### CODE REVIEW

**Comment by yingcong-wu** [comment]
Why is this problem only with DG2? It is because we only have DG2 env for testing?

**Comment by AllanZyne** [comment]
> Why is this problem only with DG2? It is because we only have DG2 env for testing?

yep

**Comment by AllanZyne** [comment]
Kindly ping @intel/unified-runtime-reviewers @intel/dpcpp-sanitizers-review, please review

**Comment by AllanZyne** [comment]
Kindly ping @intel/unified-runtime-reviewers

**Review by pbalcer — APPROVED** [review]

**Comment by pbalcer** [comment]
@intel/llvm-gatekeepers please merge

**Pull request merged**
