### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW33)

### PR DESCRIPTION
**Pull request by dbudanov-cmplr**
LLVM:  llvm/llvm-project@ec7f4a7
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@a827fb0

### CODE REVIEW

**Comment by pvchupin** [comment]
@dbudanov-cmplr, please update PR title and description similar to https://github.com/intel/llvm/pull/6358

**Comment by pvchupin** [comment]
\merge

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Thu 11 Aug 2022 09:04:36 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Thu 11 Aug 2022 09:08:31 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Comment by bader** [comment]
I think some translator patches a lost.
For instance, I don't see this patch - https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/c5b29f292bf06bd59982f629068dee2320196114.

**Pull request merged**
