### PR TITLE
[SYCL][Matrix] Make joint_matrix_mad return A*B+C's result instead of…

### PR DESCRIPTION
**Pull request by yubingex007-a11y**
… C=A*B+C

### CODE REVIEW

**Comment by yubingex007-a11y** [comment]
@dkhaldi , I should have noticed joint_matrix_mad is not aligned with your doc. I hope it is not too late.

**Review by alexbatashev — APPROVED** [review]
LGTM

**Comment by yubingex007-a11y** [comment]
I guess we should wait for Dounia's response before we merge this patch.
Besides, we'd better merge it after https://github.com/intel/llvm/pull/3584 is merged but currently this PR is under review.

**Review by alexbatashev — CHANGES_REQUESTED** [review]
Put on hold to let Dounia review.

**Comment by yubingex007-a11y** [comment]
ping @dkhaldi

**Review by dkhaldi — DISMISSED** [review]
LGTM

**Comment by alexbatashev** [comment]
@yubingex007-a11y please, resolve merge conflicts

**Review by alexbatashev — APPROVED** [review]

**Pull request merged**
