### PR TITLE
[SYCL][E2E] Disable in_order_profiling_queue.cpp on more devices

### PR DESCRIPTION
**Pull request by sarnex**
https://github.com/intel/llvm/issues/14315

### CODE REVIEW

**Review by aelovikov-intel — APPROVED** [review]
Meh, but ok...

* turning my eyes out of this and hitting the green button blindly... *

**Comment by sarnex** [comment]
@aelovikov-intel lol sorry

**Comment by steffenlarsen** [comment]
@sarnex - https://github.com/intel/llvm/issues/14315 only shows OpenCL FPGA failing, which I am not surprised by. Have we seen L0 fail in a separate run?

**Comment by sarnex** [comment]
@steffenlarsen Isn't this part from the upper part of the comment in the issue showing a L0 failure? 

```
env ONEAPI_DEVICE_SELECTOR=level_zero:gpu  /__w/llvm/llvm/build-e2e/ProfilingTag/Output/in_order_profiling_queue.cpp.tmp.out
# executed command: env ONEAPI_DEVICE_SELECTOR=level_zero:gpu /__w/llvm/llvm/build-e2e/ProfilingTag/Output/in_order_profiling_queue.cpp.tmp.out
# .---command stdout------------
# | StartTagSubmit: 163045595492
# | StartTagStart: 163046086944
# | StartTagEnd: 163046086944
# | EndTagSubmit: 163046406848
# | EndTagStart: 163046840320
# | EndTagEnd: 163046840320
# | E1Start: 163046303056
# | E1End: 163046377832
# | E2Start: 163046387296
# | E2End: 163046463320
# `-----------------------------
```

**Comment by steffenlarsen** [comment]
It will always print the times, though we only see them in the output if one of the associated runs fail, which in this case seems to be OCL FPGA. Like for the FPGA case, we would see something like "E2End <= EndTagEnd Failed!" if there was something wrong.

**Comment by sarnex** [comment]
@steffenlarsen Oh my bad, I assume that there being any output at all meant the test failed, I was too lazy to actually look at the output. I'll update the issue to show it's FPGA only, thanks for reenabling the test.

**Comment by steffenlarsen** [comment]
Thanks, @sarnex! I have a strong suspicion that it relates to the failure previously observed in it's sister test, sycl/test-e2e/ProfilingTag/profiling_queue.cpp, so I added a note about it in the issue and added the link to the issue in the other test. See https://github.com/intel/llvm/pull/14328.

**Comment by sarnex** [comment]
Thanks!

**Pull request merged**
