### PR TITLE
[SYCL] Mark parallel_for_work_item even when called indirectly

### PR DESCRIPTION
**Pull request by premanandrao**
Previously, we would mark parallel_for_work_item FunctionDecl only
when called directly from a parallel_for_work_group region.  This
change marks it when called even indirectly.

### CODE REVIEW

**Comment by premanandrao** [comment]
> I'm not a fan of the functionality we are adding here but I guess the code is fine if we need this functionality. I had a question though. In the PR description you mention -
> 
> `Previously, we would mark parallel_for_work_item FunctionDecl only when called directly from a parallel_for_work_group region.`
> 
> Where/how is this marked?

There is a top-down walk in SemaSYCL which starts from a parallel_work_group call that marks it.  But that only works for direct calls.  See here: https://github.com/intel/llvm/blob/6b496e3e6ea35197a44d230f6a8d81c1af04a46f/clang/lib/Sema/SemaSYCL.cpp#L3016

**Comment by elizabethandrews** [comment]
> > I'm not a fan of the functionality we are adding here but I guess the code is fine if we need this functionality. I had a question though. In the PR description you mention -
> > `Previously, we would mark parallel_for_work_item FunctionDecl only when called directly from a parallel_for_work_group region.`
> > Where/how is this marked?
> 
> There is a top-down walk in SemaSYCL which starts from a parallel_work_group call that marks it. But that only works for direct calls. See here:
> 
> https://github.com/intel/llvm/blob/6b496e3e6ea35197a44d230f6a8d81c1af04a46f/clang/lib/Sema/SemaSYCL.cpp#L3016

Can we not update the MarkWIScopeFnVisitor  visitor to handle this case then?

**Comment by premanandrao** [comment]
> > > I'm not a fan of the functionality we are adding here but I guess the code is fine if we need this functionality. I had a question though. In the PR description you mention -
> > > `Previously, we would mark parallel_for_work_item FunctionDecl only when called directly from a parallel_for_work_group region.`
> > > Where/how is this marked?
> > 
> > 
> > There is a top-down walk in SemaSYCL which starts from a parallel_work_group call that marks it. But that only works for direct calls. See here:
> > https://github.com/intel/llvm/blob/6b496e3e6ea35197a44d230f6a8d81c1af04a46f/clang/lib/Sema/SemaSYCL.cpp#L3016
> 
> Can we not update the MarkWIScopeFnVisitor visitor to handle this case then?

I couldn't figure out how without causing an unbounded descent from there.
Today, it looks something like:
p_f_w_g() {
  ...
  p_f_w_i();
  ...
}

So all we have to traverse is the body of p_f_w_g to mark the work_item call.   But with a need to mark indirectly called p_f_w_i calls as well, we will need to traverse the body of each of the routines called from p_f_w_g.

So rather do this potentially expensive walk, this change just marks from bottom-up; i.e. when a call node to p_f_w_i is seen, it gets marked.

**Comment by elizabethandrews** [comment]
> MarkWIScopeFnVisitor

Do we need the MarkWIScopeFnVisitor then? Won't your PR mark direct calls as well if you remove the existing attribute check?

**Comment by premanandrao** [comment]
> > MarkWIScopeFnVisitor
> 
> Do we need the MarkWIScopeFnVisitor then? Won't your PR mark direct calls as well if you remove the existing attribute check?

Yes.  MarkWIScopeFnVisitor is redundant now.  I will update the patch with that removed.

**Comment by premanandrao** [comment]
> > MarkWIScopeFnVisitor
> 
> Do we need the MarkWIScopeFnVisitor then? Won't your PR mark direct calls as well if you remove the existing attribute check?

I remembered why I hadn't removed MarkWIScopeFnVisitor before.   It marks another entry point ``wait_for`` in it.   I have left that in place in the new changes.

Alternately, I could also mark ``wait_for`` in the new way and remove the visitor entirely.   Please let me know what you prefer.

**Comment by elizabethandrews** [comment]
> > > MarkWIScopeFnVisitor
> > 
> > 
> > Do we need the MarkWIScopeFnVisitor then? Won't your PR mark direct calls as well if you remove the existing attribute check?
> 
> I remembered why I hadn't removed MarkWIScopeFnVisitor before. It marks another entry point `wait_for` in it. I have left that in place in the new changes.
> 
> Alternately, I could also mark `wait_for` in the new way and remove the visitor entirely. Please let me know what you prefer.

I think it makes sense to remove the visitor? It 'feels' wrong having 2 different areas basically doing the same thing. I do not know whether wait_for functionality is similar though - as in should indirect calls be marked the same way? Because I guess the current code does not. Not sure if that is a bug or intentional

**Comment by premanandrao** [comment]
> I think it makes sense to remove the visitor? It 'feels' wrong having 2 different areas basically doing the same thing. I do not know whether wait_for functionality is similar though - as in should indirect calls be marked the same way? Because I guess the current code does not. Not sure if that is a bug or intentional

It is not a bug, but a restriction imposed - that it must be called directly.   The ask was to relax it for ``parallel_for_wait_item``; but I can also do it for ``wait_for``.

**Comment by elizabethandrews** [comment]
> > I think it makes sense to remove the visitor? It 'feels' wrong having 2 different areas basically doing the same thing. I do not know whether wait_for functionality is similar though - as in should indirect calls be marked the same way? Because I guess the current code does not. Not sure if that is a bug or intentional
> 
> It is not a bug, but a restriction imposed - that it must be called directly. The ask was to relax it for `parallel_for_wait_item`; but I can also do it for `wait_for`.

If it is not incorrect to remove the restriction for wait_for, I think it makes sense handling it similar to parallel_for_wait_item. I'm not insisting it needs to be done in this PR though. It is up to you

**Comment by premanandrao** [comment]
@asudarsa, does the current patch fix your reported test case?   Do you have an opinion on whether I could handle ``wait_for`` the same way?

**Comment by premanandrao** [comment]
> If it is not incorrect to remove the restriction for wait_for, I think it makes sense handling it similar to parallel_for_wait_item. I'm not insisting it needs to be done in this PR though. It is up to you

I would like to leave it as is, unless you object or have further comments.   I can always incorporate further changes or comments in a future patch.

**Review by elizabethandrews — APPROVED** [review]

**Comment by premanandrao** [comment]
Thank you @elizabethandrews!   @intel/llvm-gatekeepers, this is ready for merge.

**Pull request merged**
