### PR TITLE
[SYCL] Revert support for templated call operators

### PR DESCRIPTION
**Pull request by srividya-sundaram**
This PR reverts the support for templated call operators in functors and functors without call operators which were introduced in #7104 and #7970

We found a regression internally with https://github.com/intel/llvm/pull/7104 that https://github.com/intel/llvm/pull/7970 attempted to fix. A subsequent review of https://github.com/intel/llvm/pull/7970 internally, lead to identifying some pre-existing caveats with regards to supporting templated call operators in functor,  supporting cases where there are multiple call operators in functor and making sure the right instantiated version is selected etc. 

In order to better address the pre-existing issues as well as gaps in #7970 , it was decided to revert the above two 
PRs.

### CODE REVIEW

**Comment by smanna12** [comment]
LGTM. Can you please add some description why you are reverting the patch for future reference?

**Review by smanna12 — APPROVED** [review]

**Comment by premanandrao** [comment]
> LGTM. Can you please add some description why you are reverting the patch for future reference?

We found a regression internally with #7104 that #7970 attempted to fix.   A subsequent review of #7970 internally, found some deficiencies with the patch (with templated call operators).  Rather than rush a fix for that, @srividya-sundaram is backing out both PRs and intends to architect a solution that addresses the concerns raised.  She may be able to provide a better message to add in the description.

**Review by premanandrao — APPROVED** [review]

**Comment by smanna12** [comment]
> > LGTM. Can you please add some description why you are reverting the patch for future reference?
> 
> We found a regression internally with #7104 that #7970 attempted to fix. A subsequent review of #7970 internally, found some deficiencies with the patch (with templated call operators). Rather than rush a fix for that, @srividya-sundaram is backing out both PRs and intends to architect a solution that addresses the concerns raised. She may be able to provide a better message to add in the description.

Thanks @premanandrao for the explanation!

**Comment by srividya-sundaram** [comment]
> LGTM. Can you please add some description why you are reverting the patch for future reference?

Updated the PR description with details.

**Pull request merged**
