### PR TITLE
[SYCL_MLIR][FIX] Fix address space mismatch between caller and callee by adding address space cast.

### PR DESCRIPTION
**Pull request by arnamoy10**

### CODE REVIEW

**Comment by whitneywhtsang** [comment]
Do you know why the address spaces are different in the first place?

**Comment by arnamoy10** [comment]
> Do you know why the address spaces are different in the first place?

In my examples, mainly due to one having no address space and the other one (the callee argument) having address space of 4 (The callee arg requiring it to be in addrspace 4)

**Comment by arnamoy10** [comment]
Instead of a mismatch, I guess in this scenario it will make sense to check if the srcTy does not have an addressspace and the destination type has an addressspace of 4, then do the cast.

**Comment by whitneywhtsang** [comment]
We probably want to check why the source type doesn't have address space first. e.g., it could be the AST cast not respected.

**Comment by arnamoy10** [comment]
> We probably want to check why the source type doesn't have address space first. e.g., it could be the AST cast not respected.

Should the source type always have an address space?  Also, is having no address space equivalent to having an address space 4 in our case?

**Comment by Naghasan** [comment]
> > Do you know why the address spaces are different in the first place?
> 
> In my examples, mainly due to one having no address space and the other one (the callee argument) having address space of 4 (The callee arg requiring it to be in addrspace 4)

That's odd, you should have a cast in the AST you are processing.

**Comment by arnamoy10** [comment]
> > > Do you know why the address spaces are different in the first place?
> > 
> > 
> > In my examples, mainly due to one having no address space and the other one (the callee argument) having address space of 4 (The callee arg requiring it to be in addrspace 4)
> 
> That's odd, you should have a cast in the AST you are processing.

Thanks, probably there is a bug somewhere.  Let me reinvestigate

**Comment by whitneywhtsang** [comment]
> > We probably want to check why the source type doesn't have address space first. e.g., it could be the AST cast not respected.
> 
> Should the source type always have an address space? Also, is having no address space equivalent to having an address space 4 in our case?

It is true that our default address space is 4, but no address space and address space 4 are not the same in our case. 
The source type doesn't always have an address space, but source and destination address space should match at least from the AST.

**Comment by Naghasan** [comment]
This could happen when dealing with GV

```
int foo = 42;
void call(int*);

void bar() {
 call(&foo);
}
```

`&foo` lowers to a pointer to global. but the AST will not have a cast as they are both to `Default`

**Comment by arnamoy10** [comment]
> This could happen when dealing with GV
> 
> ```
> int foo = 42;
> void call(int*);
> 
> void bar() {
>  call(&foo);
> }
> ```
> 
> `&foo` lowers to a pointer to global. but the AST will not have a cast as they are both to `Default`

Thanks for the example.  Please let me know whether I should update my heuristic from a generic mismatch to one having no address space and the other having address space 4.

**Comment by Naghasan** [comment]
I think this is fine, FE checks should only hand over an AST where this kind of things are fine. And TBH, this is the only example I can come up with that could trigger this.

Although, It would be nice to have a test derived from the code that triggered your bug just to make sure this is not something missed from processing the AST.

**Pull request closed without merging**
