### PR TITLE
[SYCL] Allow max-concurrency attribute on lambdas.

### PR DESCRIPTION
**Pull request by zahiraam**
Signed-off-by: Zahira Ammarguellat <zahira.ammarguellat@intel.com>

### CODE REVIEW

**Review by AaronBallman — APPROVED** [review]
LGTM, thank you!

**Review by smanna12 — COMMENTED** [review]
Should we remove the comments since we are removing the error here?

    // Applying attributes to lambdas is a nonconforming extension. This will
    // remain an an error until the SYCL specifications allow it or until
    // users require it. Refer to comments about
    // SupportsNonconformingLambdaSyntax bit in Attr.td.

**Comment by AaronBallman** [comment]
> Should we remove the comments since we are removing the error here?
> 
> ```
> // Applying attributes to lambdas is a nonconforming extension. This will
> // remain an an error until the SYCL specifications allow it or until
> // users require it. Refer to comments about
> // SupportsNonconformingLambdaSyntax bit in Attr.td.
> ```

Ooh, good catch on the leading comment! Yeah, that should be removed.

**Review by AaronBallman — APPROVED** [review]
LGTM!

**Review by premanandrao — APPROVED** [review]
Changes LGTM.   Please fix the typo in the title "Allow" and add a [SYCL] prefix.

**Pull request merged**
