### PR TITLE
[SYCL][HIP] Fix hip prefetch/mem_advise (noop) for rocm < 5.0

### PR DESCRIPTION
**Pull request by JackAKirk**
The main fix here is to enable prefetch functionality when the HIP backend is built with rocm versions < 5.
The change to the prefix/mem_advise UR hip adapter APIs fixes four e2e-tests that fail test-e2e only for HIP 4.x versions (These failures don't come up in the CI since it tests using rocm 5.x).

The change to Tracing/image_printers.cpp is effectively re-XFailing this test for rocm 4 only. rocm 4 doesn't support `hipCreateSurfaceObject` which is called by this test. I'm not sure this legacy image functionality (Which as I understand it will be replaced by bindless images) is really working for rocm 5 in a meaningful way, since most other legacy image e2e tests are XFAIL for hip. But this test can still be useful for us for ROCM 5 compatibility testing. The XFAIL was recently removed here https://github.com/intel/llvm/commit/745febe51b68b2a7cc0ed021e6ebb863af48c4fa which led to us finding the rocm 4 fail. I guess that the CI at some point switched from testing rocm 4 to testing rocm 5, which meant this test stopped failing in CI.

### CODE REVIEW

**Review by npmiller — APPROVED** [review]
LGTM

**Comment by GeorgeWeb** [comment]
LGTM!

Good spot wrt `hipPointerGetAttribute`. It's unfortunate that this cannot be queried from `hipPointerAttribute_t` attribs via `hipPointerGetAttributes` instead, but suppose it's okay for **4.5.x** - only difference is gonna be just that the hip implementation will return a `hipErrorInvalidValue`, so while the user may not get the most meaningful error message I don't see an alternative.

**Review by steffenlarsen — APPROVED** [review]
Sorry for missing this. LGTM!

**Comment by steffenlarsen** [comment]
@JackAKirk - Could you please resolve the merge conflicts?

**Comment by JackAKirk** [comment]
> @JackAKirk - Could you please resolve the merge conflicts?

Done!

**Comment by JackAKirk** [comment]
@intel/llvm-gatekeepers  Windows CI is having issues. I think this is safe to merge.

**Comment by steffenlarsen** [comment]
> @intel/llvm-gatekeepers Windows CI is having issues. I think this is safe to merge.

Since it only seems to touch HIP-specific paths, I agree and will proceed with a merge without a Windows pass.

**Pull request merged**
