### PR TITLE
[GHA] Uplift Linux GPU RT version to 22.43.24595.30

### PR DESCRIPTION
**Pull request by bb-sycl**
Scheduled drivers uplift

### CODE REVIEW

**Comment by cperkinsintel** [comment]
@smaslov-intel  - this PR to uplift the GPU drivers has two L0 failures (  SYCL :: Plugin/level_zero_queue_priority.cpp and 
  SYCL :: Plugin/level_zero_queue_profiling.cpp ).   Is this something known or is it a problem in the driver update?

**Review by bader — CHANGES_REQUESTED** [review]
There must be no regressions.
I see two tests fail: https://github.com/intel/llvm/actions/runs/4050380459/jobs/6967995225.

**Comment by smaslov-intel** [comment]
> @smaslov-intel - this PR to uplift the GPU drivers has two L0 failures ( SYCL :: Plugin/level_zero_queue_priority.cpp and SYCL :: Plugin/level_zero_queue_profiling.cpp ). Is this something known or is it a problem in the driver update?

@cperkinsintel : these fails are not known. Both have the same unexpected symptom:

> what(): No device of requested type 'info::device_type::gpu' available. -1 (PI_ERROR_DEVICE_NOT_FOUND)

**Comment by bader** [comment]
Replaced by https://github.com/intel/llvm/pull/8485.

**Comment by bader** [comment]
> > @smaslov-intel - this PR to uplift the GPU drivers has two L0 failures ( SYCL :: Plugin/level_zero_queue_priority.cpp and SYCL :: Plugin/level_zero_queue_profiling.cpp ). Is this something known or is it a problem in the driver update?
> 
> @cperkinsintel : these fails are not known. Both have the same unexpected symptom:
> 
> > what(): No device of requested type 'info::device_type::gpu' available. -1 (PI_ERROR_DEVICE_NOT_FOUND)

@cperkinsintel, @smaslov-intel, @intel/dpcpp-l0-pi-reviewers, any updates on this issue? I see that it's still present in 22.53.* drivers - https://github.com/intel/llvm/pull/8550.

In addition to that, there is one more regression on L0 and OpenCL. First time seen in 22.49.* driver https://github.com/intel/llvm/pull/8485. Please, investigate this one too.

> Failed Tests (1):
>  SYCL :: Printf/char.cpp

**Pull request closed without merging**
