### PR TITLE
[GHA] Uplift Linux IGC Dev RT version to igc-dev-6ba42ba

### PR DESCRIPTION
**Pull request by bb-sycl**
Scheduled igc dev drivers uplift

### CODE REVIEW

**Comment by sarnex** [comment]
Test failure should be fixed in https://github.com/intel/llvm/pull/16039#issuecomment-2476481630 so I guess we just wait for that to be merged and then rebase

**Comment by YuriPlyakhin** [comment]
> Test failure should be fixed in [#16039 (comment)](https://github.com/intel/llvm/pull/16039#issuecomment-2476481630) so I guess we just wait for that to be merged and then rebase

@sarnex , @YixingZhang007 , if you are waiting for this fix: https://github.com/intel/intel-graphics-compiler/commit/bdce5e87ab841f2da0847c1923092061f982d457 in IGC, then it was merged. Maybe no need to XFAIL anything. Just wait for new auto-PR with IGC update?

**Comment by sarnex** [comment]
I have no idea what if any IGC change will fix that test failure :)

**Review by sarnex — APPROVED** [review]

**Comment by sarnex** [comment]
@YuriPlyakhin Passing after rebase, can you review pls? Thx

**Review by YuriPlyakhin — APPROVED** [review]
sure, LGTM! :)

**Pull request merged**
