### PR TITLE
[SYCL][Scheduler] Refactor data transfer scheduler commands

### PR DESCRIPTION
**Pull request by romanovvlad**
Refactored update requirment, map and unmap commands to enable future optimizations of host memory allocations.

Signed-off-by: Vlad Romanov <vlad.romanov@intel.com>

### CODE REVIEW

**Comment by bader** [comment]
Typo in the commit message: requirment -> requirement.
Could you also provide more context of the problem you are trying to solve, please?

**Comment by romanovvlad** [comment]
> 
> 
> Refactored update requirment, map and unmap commands to take host
> pointer instead of requirement.
> 
> Signed-off-by: Vlad Romanov [vlad.romanov@intel.com](mailto:vlad.romanov@intel.com)

I'm planning

> you also provide more context

The change makes map,  unmap and other commands more flexible so they can be used not only for situations when we have host accessor which we need to initialize with host ptr, but for doing map/unmap in cases when we can/must avoid copying which would require additional memory allocation on the host.
Yes this is a change extracted from this https://github.com/intel/llvm/pull/724 PR.

**Comment by bader** [comment]
> > you also provide more context
> 
> The change makes map, unmap and other commands more flexible so they can be used not only for situations when we have host accessor which we need to initialize with host ptr, but for doing map/unmap in cases when we can/must avoid copying which would require additional memory allocation on the host.
> Yes this is a change extracted from this #724 PR.

Thanks.
I've updated PR title and description based on your clarification. It would be great if commit message provides more details too.

**Comment by romanovvlad** [comment]
refactored MemCpyCommandHost in the same way

**Pull request merged**
