### PR TITLE
[SYCL] Treat profiling as not supported if submit timestamps are not

### PR DESCRIPTION
**Pull request by sergey-semenov**
With the recent fix to command_submit profiling information query it now requires that the plugin supports piGetDeviceAndHostTimer API. Because of that, we should not report queue profiling as a supported aspect unless both the underlying pi_queue supports profiling and piGetDeviceAndHostTimer is available.

In addition, add a feature_not_supported exception when a queue is constructed with enable_profiling property and a device that does not support profiling.

### CODE REVIEW

**Comment by sergey-semenov** [comment]
Note that the spec does not currently state that the exception must be thrown in the case described in the commit message, but I don't expect it to be a controversial change (https://github.com/KhronosGroup/SYCL-Docs/pull/359)

**Comment by sergey-semenov** [comment]
Looks like ESIMD tests assume that queue profiling is supported despite that not actually being the case with ESIMD emulator (it's just actually checked with this patch). I think the tests should be modified so that profiling is optional there.

I noticed, however, that several profiling related functions from the ESIMD emulator backend (`piGetDeviceAndHostTime`, `piEventGetProfilingInfo`) return `PI_SUCCESS` instead of an error despite not being able to do anything meaningful. @dongkyunahn-intel Is that intentional?

**Comment by dongkyunahn-intel** [comment]
@sergey-semenov , as far as I remember, when I brought up ESIMD_EMULATOR backend, `piEventGetProfilingInfo` had to return `PI_SUCCESS` for the backend to pass some tests even if the implementation does nothing meaningful while profiling under emulation is not critical. That was the reason why warning message was added in the function. I was not aware that `piGetDeviceAndHostTime` was added.

**Comment by sergey-semenov** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1604

**Comment by sergey-semenov** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1604

**Comment by sergey-semenov** [comment]
@dm-vodopyanov @intel/llvm-reviewers-runtime Could you please take a look?

**Review by dm-vodopyanov — APPROVED** [review]

**Pull request merged**
