### PR TITLE
[SYCL] Fix self build on windows.

### PR DESCRIPTION
**Pull request by zahiraam**
Fix to avoid error "default label in switch which covers all enumeration values" on windows self-build.

### CODE REVIEW

**Review by bader — CHANGES_REQUESTED** [review]
Please, commit `llvm/utils/benchmark/include/benchmark/benchmark.h` to https://github.com/llvm/llvm-project. These changes are not specific to SYCL.

Post-commit validates self-build on Linux. Any idea why these issues are not reproducible there?

**Comment by zahiraam** [comment]
> Please, commit `llvm/utils/benchmark/include/benchmark/benchmark.h` to https://github.com/llvm/llvm-project. These changes are not specific to SYCL.
> 
> Post-commit validates self-build on Linux. Any idea why these issues are not reproducible there?

benchmark.h on github.com/llvm/llvm-project is correct, meaning the functions that need to be marked override, are already. I am proposing this change here to reflect what is **already** in github.com/llvm/llvm-project. But I understand it is not sycl code. 

Pre-post commit run debug build on Windows but not on Linux. This is a debug build fail on Windows.

**Comment by erichkeane** [comment]
I don't believe that LLORG wants this, and I'm quite sure that _WE_ don't want this either.  The google-test infrastructure gets updated in the community via a copy/paste from its upstream which ends up destroying any modifications that we make.  I'd suggest we instead just change our cmakelist file to omit the warning that gets caught by this.

**Comment by bader** [comment]
> > Please, commit `llvm/utils/benchmark/include/benchmark/benchmark.h` to https://github.com/llvm/llvm-project. These changes are not specific to SYCL.
> > Post-commit validates self-build on Linux. Any idea why these issues are not reproducible there?
> 
> benchmark.h on github.com/llvm/llvm-project is correct, meaning the functions that need to be marked override, are already. I am proposing this change here to reflect what is **already** in github.com/llvm/llvm-project. But I understand it is not sycl code.

If so, I suggest wait for pulldown instead, if it's not urgent. https://github.com/intel/llvm/pull/3852 or the next one should pull the fix to the `sycl` branch.

> 
> Pre-post commit run debug build on Windows but not on Linux. This is a debug build fail on Windows.

I suppose self build you are using enables `LLVM_ENABLE_WERROR` cmake variable, whereas we enable only `SYCL_ENABLE_WERROR`, which fails only on SYCL project warnings.

**Comment by zahiraam** [comment]
> > > Please, commit `llvm/utils/benchmark/include/benchmark/benchmark.h` to https://github.com/llvm/llvm-project. These changes are not specific to SYCL.
> > > Post-commit validates self-build on Linux. Any idea why these issues are not reproducible there?
> > 
> > 
> > benchmark.h on github.com/llvm/llvm-project is correct, meaning the functions that need to be marked override, are already. I am proposing this change here to reflect what is **already** in github.com/llvm/llvm-project. But I understand it is not sycl code.
> 
> If so, I suggest wait for pulldown instead, if it's not urgent. #3852 or the next one should pull the fix to the `sycl` branch.
> 
> > Pre-post commit run debug build on Windows but not on Linux. This is a debug build fail on Windows.
> 
> I suppose self build you are using enables `LLVM_ENABLE_WERROR` cmake variable, whereas we enable only `SYCL_ENABLE_WERROR`, which fails only on SYCL project warnings.

Yes debug build on Windows is using LLVM_ENABLE_WERROR.

**Review by bader — APPROVED** [review]

**Review by smaslov-intel — APPROVED** [review]
LGTM

**Pull request merged**
