### PR TITLE
[SYCL] Remove device_global_static.cpp test 

### PR DESCRIPTION
**Pull request by sarnex**
We don't think it provides value.

### CODE REVIEW

**Comment by aelovikov-intel** [comment]
In https://github.com/intel/llvm/pull/15224#issuecomment-2333564820:

> Thanks @aelovikov-intel I'd like to keep it in if possible. I can remove at any point in time if it becomes a problem.

I'd rather remove the test :)

**Comment by hdelan** [comment]
> @hdelan Can I remove the test?

Sure go for it

**Comment by sarnex** [comment]
@aelovikov-intel Updated PR to remove test, thx

**Review by aelovikov-intel — APPROVED** [review]

**Comment by sarnex** [comment]
No need for CI on this, it's just removing a file.

**Pull request merged**
