### PR TITLE
[Matrix][AMX] remove REQUIRES gpu for element_wise_all_ops_half.cpp since AMX now support half

### PR DESCRIPTION
**Pull request by yubingex007-a11y**

### CODE REVIEW

**Review by YuriPlyakhin — APPROVED** [review]

**Comment by yubingex007-a11y** [comment]
ping? @aelovikov-intel

**Comment by aelovikov-intel** [comment]
> ping? @aelovikov-intel

What do you expect from me in this PR? If you want this PR merged then follow the instructions at https://github.com/intel/llvm/blob/sycl/CONTRIBUTING.md.

**Comment by yubingex007-a11y** [comment]
i saw the FAIL is ipldt but obviously the pr has no ipldt issue

**Comment by steffenlarsen** [comment]
Precommit timeout is an infrastructure issue. Merging this.

**Pull request merged**
