### PR TITLE
[UR] Remove unused function prototypes

### PR DESCRIPTION
**Pull request by hdelan**
https://github.com/oneapi-src/unified-runtime/pull/1460

### CODE REVIEW

**Comment by aarongreig** [comment]
https://github.com/oneapi-src/unified-runtime/pull/1460 has merged

**Comment by hdelan** [comment]
@aarongreig have rebased

**Comment by hdelan** [comment]
@aarongreig CI has passed so I think this should be OK to merge

**Review by aarongreig — APPROVED** [review]

**Comment by aarongreig** [comment]
@intel/llvm-gatekeepers please merge

**Pull request merged**
