### PR TITLE
[SYCL][Driver] Remove -fsycl-esimd-build-host-code

### PR DESCRIPTION
**Pull request by sarnex**
Remove the positive option and keep only the negative option. The option was added only a couple of days ago and nobody should be using it. It is a hidden option as well.

Based on feedback from https://github.com/intel/llvm/pull/11037#discussion_r1328955361

### CODE REVIEW

**Comment by sarnex** [comment]
Ignore Windows CI failure, it's currently disabled overall because it's not working.

**Review by mdtoguchi — APPROVED** [review]

**Comment by sarnex** [comment]
@intel/llvm-gatekeepers This one should be good to go, the other reviewers are already on board with this change. Thanks

**Comment by aelovikov-intel** [comment]
> Ignore Windows CI failure, it's currently disabled overall because it's not working.

Please merge `origin/sycl`.

**Review by v-klochkov — APPROVED** [review]

**Comment by sarnex** [comment]
@intel/llvm-gatekeepers Should be ready now, CI passed :)

**Pull request merged**
