### PR TITLE
[SYCL][CUDA][libclc] Add remaining atomics

### PR DESCRIPTION
**Pull request by t4c1**
Adds implementations for atomic operations that do not have direct PTX equivalents. Sub is implemented by using add. Floating point min and max use compare exchange loops.

I pushed the tests for this into: https://github.com/intel/llvm-test-suite/pull/534

This blocks: https://github.com/intel/llvm/pull/4853

### CODE REVIEW

**Comment by bader** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/534

**Review by bader — DISMISSED** [review]

**Comment by bader** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/534

**Comment by t4c1** [comment]
@bader I think this one can be merged as well. It should pass the test suite on `intel` branch, while intel/llvm-test-suite#534 will require https://github.com/intel/llvm/pull/4853 merged before.

**Comment by bader** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/697

**Review by bader — APPROVED** [review]

**Comment by t4c1** [comment]
I think the failures are unrelated to the changes in this PR.

**Pull request merged**
