### PR TITLE
[SYCL][E2E][Bindless] Increase image size for interop tests

### PR DESCRIPTION
**Pull request by wenju-he**
Align with real world cases and enable debugging of failures in large image-size cases.
Other changes to dx12 read_write_unsampled tests:
* Init sycl::queue and dx12 device/queue/cmdlist once to reduce run time
* read_write_unsampled_semaphore.cpp fails with large image size.
   Define TEST_SMALL_IMAGE_SIZE for the semaphore test as a w/a.
* Add `m_sharedFenceValue++` after waitDX12Fence() at the end of callSYCLKernel
* Fix readbackBufferRange in validateOutput
* Fix unorm_int8 input/output value out-of-range.
* Fix fp16 input value out-of-range.

Other changes to vulkan sampled_images.cpp test:
* Fix fp16 input value out-of-range.
* Set linearTiling to true at vkutil::createImage call for L0. It is
  disabled for CUDA due to failure "Could not create image!".

Co-authored-by: Ashwin Kumar Kulkarni <ashwin.kumar.kulkarni@intel.com>

### CODE REVIEW

**Comment by DBDuncan** [comment]
Hey Wenju. We are trying to address the problem with slow running tests. If you have any ideas and can apply them now then that would be great. Otherwise we are fine merging this and will improve test performance later.

**Review by DBDuncan — APPROVED** [review]

**Comment by jbrodman** [comment]
You may want to consider refactoring this test so the queue creation happens outside the core test loop.

**Comment by wenju-he** [comment]
> We are trying to address the problem with slow running tests. If you have any ideas and can apply them now then that would be great. Otherwise we are fine merging this and will improve test performance later.

You're right that this change will increase test run time. 
For CUDA this PR only changes dx12 test time. Dx12 read_write_unsampled.cpp run time is increased from 12s to 17s on GTX 1060 Windows.
For L0, vulkan test time increases from 1~2s to 24s on DG2 windows.

> You may want to consider refactoring this test so the queue creation happens outside the core test loop.

If we initialization sycl queue and dx12 device/command queue/command list once, dx12 read_write_unsampled.cpp run time is reduced from 17s to 11s on GTX 1060 Windows.

**Comment by wenju-he** [comment]
@DBDuncan I just find that dx12_interop/read_write_unsampled_semaphore.cpp fails at https://github.com/intel/llvm/blob/2f3919ee3239de7069f3973953f51d0865889815/sycl/test-e2e/bindless_images/dx12_interop/read_write_unsampled.cpp#L576 after this PR change.
The root cause isn't clear to to me. It looks like a synchronization issue. 
I think `m_sharedFenceValue++` might be missing right after https://github.com/intel/llvm/blob/2f3919ee3239de7069f3973953f51d0865889815/sycl/test-e2e/bindless_images/dx12_interop/read_write_unsampled.cpp#L380, but it doesn't help.
Could you please also take a look?

**Comment by DBDuncan** [comment]
I am working on speeding up the tests and not had much luck moving the sycl queue and device out of the core test loop. Performance improvements have been very minor. Like 23.95s to 22.47s. Though now the worst test takes less then 33 seconds which is a decent improvement from about 67 on my system previously.

**Comment by DBDuncan** [comment]
Hey Wenju. We have discussed the issue and some workarounds you could do for now is either add a macro that switches between small and large image sizes and have the large image sizes turned off for now. Or, you could try to use full synchronization instead of semaphores. Not just sycl queue wait but also DX12 sycl?

We have a ticket to look into this to put in a proper fix but likely it will be a little while till it is picked up.

**Comment by aravindksg** [comment]
> A lot of the time the size of the images being tested are way bigger then they need to be.

Hi @DBDuncan could you provide guidance on what images sizes we need to test and also would those be representative of the size we expect to be used in real-world apps?

**Comment by wenju-he** [comment]
> Other changes to dx12 tests
> 
> * Init sycl::queue and dx12 device/queue/cmdlist once to reduce run time
> * read_write_unsampled_semaphore.cpp fails with large image size.
>   Define TEST_SMALL_IMAGE_SIZE for the semaphore test as a w/a.
> * Add `m_sharedFenceValue++` after waitDX12Fence() at the end of callSYCLKernel
> * Fix readbackBufferRange in validateOutput

@DBDuncan I've added a new commit that change dx12 tests:
* Init sycl::queue and dx12 device/queue/cmdlist once to reduce run time
* read_write_unsampled_semaphore.cpp fails with large image size.
  Define TEST_SMALL_IMAGE_SIZE for the semaphore test as a w/a.
* Add m_sharedFenceValue++ after waitDX12Fence() at the end of callSYCLKernel
* Fix readbackBufferRange in validateOutput

**Comment by DBDuncan** [comment]
> > A lot of the time the size of the images being tested are way bigger then they need to be.
> 
> Hi @DBDuncan could you provide guidance on what images sizes we need to test and also would those be representative of the size we expect to be used in real-world apps?

The sizes that Wenju has provided here are reasonable. Note that we also need a way to reduce testing time as quite a few of our tests are the slowest in DPC++. The switch Wenju has added to use either real world or small test sizes helps with this.

**Comment by DBDuncan** [comment]
> You may want to consider refactoring this test so the queue creation happens outside the core test loop.

I have experimented with this and it did not help as much as I would had hoped. TBH prob because tests like `read_sampled.cpp` compiling takes a while as there is a lot of templates and at runtime it is running sampling operations manually on the host to verify the device results.

**Comment by wenju-he** [comment]
> > You may want to consider refactoring this test so the queue creation happens outside the core test loop.
> 
> I have experimented with this and it did not help as much as I would had hoped.

I only observed a less than 1s time reduction when initializing SYCL queue once. In general it is a good idea to reuse a SYCL queue. The SYCL queue initialization time could vary from device to device.
Initializing DX12 device/queue/cmdlist reduces run time by 5~6s on a Windows machine with CPU 8700K and GPU GTX 1060:

**Comment by wenju-he** [comment]
@DBDuncan I've pushed a new commit to fix dx12 input value out-of-range for unorm_int8 type.
For the input value, conversion out-of-range value to uchar type is implementation defined behavior.
In addition, the SYCL kernel multiplies the input value by 2.

**Comment by wenju-he** [comment]
Commit https://github.com/intel/llvm/pull/15129/commits/c9455a7f722734b64e8f39541710a778fa129adc fixes 2D&3D vulkan tests on DG2 per suggestion from Ashwin Kumar Kulkarni

**Review by DBDuncan — APPROVED** [review]

**Comment by aravindksg** [comment]
@wenju-he  we also need option for "ENABLE_LINEAR_TILING" for VK unsampled test as well?

**Comment by aravindksg** [comment]
> @wenju-he we also need option for "ENABLE_LINEAR_TILING" for VK unsampled test as well?


answering myself - looks like unsampled case does not need it as it works fine without forcing linear images. however - do we need the unorm fixes?

**Review by nrspruit — APPROVED** [review]
LGTM

**Comment by wenju-he** [comment]
> > @wenju-he we also need option for "ENABLE_LINEAR_TILING" for VK unsampled test as well?
> 
> answering myself - looks like unsampled case does not need it as it works fine without forcing linear images. however - do we need the unorm fixes?

@aravindksg unorm_int8 fail in vulkan/dx12 unsampled image tests isn't root caused yet, so it isn't clear if it is also a test issue.

**Comment by wenju-he** [comment]
@intel/llvm-gatekeepers please merge, thank you

**Pull request merged**
