### PR TITLE
Correct some cuda/sycl accuracy from 0.0 to 0.5 and add relate handling.

### PR DESCRIPTION
**Pull request by FreddyLeaf**
Several functions for "sycl" and "cuda" requires "0.5" accuracy levels, which means correctly rounded results. For now x86 host AltMathLibrary doesn't have such ability. For such accuracy level, the fpbuiltins should be replaced by equivalent IR operation or llvmbuiltins.

### CODE REVIEW

**Comment by FreddyLeaf** [comment]
ping for review

**Review by premanandrao — APPROVED** [review]
FE changes look okay to me, but someone else will need to check/verify the IR in the tests.

**Review by andykaylor — APPROVED** [review]
lgtm

**Review by smanna12 — APPROVED** [review]

**Comment by FreddyLeaf** [comment]
Thanks for review @premanandrao @andykaylor 
ping @intel/dpcpp-tools-reviewers

**Comment by FreddyLeaf** [comment]
ping for review

**Comment by FreddyLeaf** [comment]
ping for review @intel/dpcpp-tools-reviewers

**Review by AlexeySachkov — APPROVED** [review]

**Comment by bader** [comment]
@intel/llvm-gatekeepers, this seems to be ready to land. Any objections to merge?

**Review by asudarsa — APPROVED** [review]
Sorry for late review. LGTM.

**Pull request merged**
