### PR TITLE
[SYCL][CUDA][NFC] Check alignment of USM allocations

### PR DESCRIPTION
**Pull request by bader**

### CODE REVIEW

**Review by smaslov-intel — APPROVED** [review]
LGTM, but why don't you do the same check for other plugins?

**Comment by bader** [comment]
This patch intended to address this particular comment: https://github.com/intel/llvm/pull/2557#discussion_r530906007.

> LGTM, but why don't you do the same check for other plugins?

Probably it would be better add validation of `piext*` results in `sycl/source/detail/usm/usm_impl.cpp` - the check implementation is not specific to PI implementation.

**Comment by smaslov-intel** [comment]
> This patch intended to address this particular comment: [#2557 (comment)](https://github.com/intel/llvm/pull/2557#discussion_r530906007).
> 
> > LGTM, but why don't you do the same check for other plugins?
> 
> Probably it would be better add validation of `piext*` results in `sycl/source/detail/usm/usm_impl.cpp` - the check implementation is not specific to PI implementation.

Actually, I think plugins should better themselves verify their output (similar how they tend to verify inputs).

**Comment by bader** [comment]
@smaslov-intel, ping.

**Review by smaslov-intel — APPROVED** [review]

**Pull request merged**
