### PR TITLE
Update SVML altmath library high accuracy entries

### PR DESCRIPTION
**Pull request by andykaylor**
This changes the accuracy declared for 'ha' SVML functions to 1.0, reflecting the actual standard used by the library team for these functions.

### CODE REVIEW

**Review by FreddyLeaf — APPROVED** [review]
LGTM

**Comment by andykaylor** [comment]
@intel/dpcpp-tools-reviewers I don't understand how my change could be causing the failure reported in the Windows Build + LIT testing. Is this a know issue?

**Comment by AlexeySachkov** [comment]
> @intel/dpcpp-tools-reviewers I don't understand how my change could be causing the failure reported in the Windows Build + LIT testing. Is this a know issue?

Better to ask gatekeepers, but If I understand correctly, we have a general problem with Windows machines where some tests never exit and lock some directories so that the next job coming to a machine fails while trying to re-create them.

**Review by AlexeySachkov — APPROVED** [review]

**Comment by asudarsa** [comment]
> > @intel/dpcpp-tools-reviewers I don't understand how my change could be causing the failure reported in the Windows Build + LIT testing. Is this a know issue?
> 
> Better to ask gatekeepers, but If I understand correctly, we have a general problem with Windows machines where some tests never exit and lock some directories so that the next job coming to a machine fails while trying to re-create them.

It is a known issue in CI reported here. https://github.com/intel/llvm/issues/14248
Restarting sometimes helps (I have restarted the failing tests).

Thanks

**Comment by andykaylor** [comment]
@intel/dpcpp-tools-reviewers Can you merge this change? Thanks.

**Pull request merged**
