### PR TITLE
[SYCL][Bindless] Create mapping of host and device handle

### PR DESCRIPTION
**Pull request by DBDuncan**
Updates L0 UR commit. Creates a mapping between the host and device handle in the L0 backend to be able to retrieve the host handle when destroying the image.

### CODE REVIEW

**Comment by DBDuncan** [comment]
Corresponding UR PR: https://github.com/oneapi-src/unified-runtime/pull/1790

**Comment by DBDuncan** [comment]
Friendly ping @intel/unified-runtime-reviewers

**Comment by kbenzie** [comment]
> Friendly ping @intel/unified-runtime-reviewers

The UR PR needs to be approved and merged before we'll approve this PR.

**Comment by DBDuncan** [comment]
> > Friendly ping @intel/unified-runtime-reviewers
> 
> The UR PR needs to be approved and merged before we'll approve this PR.

No problem. I have a few other PRs up which I wanted to get reviews started on the DPC++ side. Got a bit ahead of myself with all the `@'s` lol.

**Comment by omarahmed1111** [comment]
This will be included in this [PR](https://github.com/intel/llvm/pull/14848)

**Comment by omarahmed1111** [comment]
The bump for this PR will be included as part of this [PR](https://github.com/intel/llvm/pull/14701), so I think we could close this PR.

**Pull request closed without merging**
