### PR TITLE
[SYCL] sycl/test should not be repeated for different triples

### PR DESCRIPTION
**Pull request by DYNIO-INTEL**
This change modifies sycl/test/CMakeLists.txt because tests should set the right triple explicitly to removes need to repeat every other test for a different triple.

Fixes https://github.com/intel/llvm/issues/14671

### CODE REVIEW

**Comment by steffenlarsen** [comment]
@npmiller - Are you aware of any sycl/test tests that make assumptions and or have requirements based on the triples? I suspect this is just legacy, but it would be good to make sure no tests are silently ignored as a result of this.

**Comment by npmiller** [comment]
I think all the CUDA/AMD specific tests already set the triples directly.

Just to make sure I understand we're moving to just using `check-sycl-combined-triples` that builds the tests for all targets at once?

Should this also remove `check-sycl-spirv` above then?

**Review by steffenlarsen — APPROVED** [review]
LGTM! @npmiller - Can you confirm that there are no concerns about removing these from your side?

**Review by npmiller — APPROVED** [review]
Changes for CUDA and HIP LGTM!

**Pull request merged**
