### PR TITLE
[SYCL][E2E] add the FP16 tests in marray_geometric

### PR DESCRIPTION
**Pull request by jinz2014**
Thank you for your review.

### CODE REVIEW

**Review by cperkinsintel — APPROVED** [review]
I haven't seen the test results complete yet, but this looks good.

**Comment by jinz2014** [comment]
> I haven't seen the test results complete yet, but this looks good.

could you please explain "test results not complete yet" ?

**Comment by KseniyaTikhomirova** [comment]
@jinz2014 hi, tests are failing for all platforms even with -fpreview-breaking-changes flag. Could you please take a look?

**Comment by KseniyaTikhomirova** [comment]
> @KseniyaTikhomirova Could you please point out where the flag is added for the AMD HIP build ?
> 
> Reference #11929

@jinz2014 hi, I would start from test run on OCL/L0 on our HW. It is also failing. I guess the problem could be that your have lines 1-2 not removed/unchanged, with no any flags, and sycl::cross for sycl::half is still involved in compilation.

**Comment by jinz2014** [comment]
> > @KseniyaTikhomirova Could you please point out where the flag is added for the AMD HIP build ?
> > Reference #11929
> 
> @jinz2014 hi, I would start from test run on OCL/L0 on our HW. It is also failing. I guess the problem could be that your have lines 1-2 not removed/unchanged, with no any flags, and sycl::cross for sycl::half is still involved in compilation.

I deleted the first two lines. Thanks.

**Comment by KseniyaTikhomirova** [comment]
> > > @KseniyaTikhomirova Could you please point out where the flag is added for the AMD HIP build ?
> > > Reference #11929
> > 
> > 
> > @jinz2014 hi, I would start from test run on OCL/L0 on our HW. It is also failing. I guess the problem could be that your have lines 1-2 not removed/unchanged, with no any flags, and sycl::cross for sycl::half is still involved in compilation.
> 
> I deleted the first two lines. Thanks.

I clarified more details about that.
I would suggest to keep that lines to not reduce coverage. You can use __INTEL_PREVIEW_BREAKING_CHANGES define to wrap the code you added, the code that needs -fpreview-breaking-changes to be enabled to fix complication failures for initial scenario and properly add yours.

**Comment by jinz2014** [comment]
> > > > @KseniyaTikhomirova Could you please point out where the flag is added for the AMD HIP build ?
> > > > Reference #11929
> > > 
> > > 
> > > @jinz2014 hi, I would start from test run on OCL/L0 on our HW. It is also failing. I guess the problem could be that your have lines 1-2 not removed/unchanged, with no any flags, and sycl::cross for sycl::half is still involved in compilation.
> > 
> > 
> > I deleted the first two lines. Thanks.
> 
> I clarified more details about that. I would suggest to keep that lines to not reduce coverage. You can use __INTEL_PREVIEW_BREAKING_CHANGES define to wrap the code you added, the code that needs -fpreview-breaking-changes to be enabled to fix complication failures for initial scenario and properly add yours.

Thanks for the suggestions.

**Pull request merged**
