### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW29)

### PR DESCRIPTION
**Pull request by sys-ce-bb**
LLVM: llvm/llvm-project@1aecb0e
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@8dcd16c

### CODE REVIEW

**Comment by jsji** [comment]
@intel/llvm-gatekeepers OK to merge?

**Comment by bader** [comment]
@jsji, there are no pre-commit results. I'd like to test the changes before the merge.
@aelovikov-intel, how we can run pre-commit tests for this PR?

**Comment by jsji** [comment]
@intel/dpcpp-devops-reviewers Looks like CI bug? Quite some checks are skipped?

**Comment by jsji** [comment]
> @jsji, there are no pre-commit results. I'd like to test the changes before the merge. @aelovikov-intel, how we can run pre-commit tests for this PR?

Yes, I just realized it -- is it a bug or new change that we don't run Pre-commit CI test automatically now?

**Comment by aelovikov-intel** [comment]
> Yes, I just realized it -- is it a bug or new change that we don't run Pre-commit CI test automatically now?

Security feature - we don't allow running tasks for arbitrary PRs that modify files affecting CI. We will need to allow such pulldown PRs to go by somehow, but that hasn't been worked on yet.

**Comment by jsji** [comment]
> > Yes, I just realized it -- is it a bug or new change that we don't run Pre-commit CI test automatically now?
> 
> Security feature - we don't allow running tasks for arbitrary PRs that modify files affecting CI. We will need to allow such pulldown PRs to go by somehow, but that hasn't been worked on yet.

Got.  Thanks!

**Comment by jsji** [comment]
> Security feature - we don't allow running tasks for arbitrary PRs that modify files affecting CI.

But in that case, shouldn't we return False for checks by default instead? Or else,  arbitrary PRs might be merged accidently?

**Comment by aelovikov-intel** [comment]
> But in that case, shouldn't we return False for checks by default instead? Or else, arbitrary PRs might be merged accidently without running CI?

I don't understand the question.

PS Running pre-commit testing in https://github.com/intel/llvm/pull/10435/checks via some manual workarounds.

**Comment by jsji** [comment]
> PS Running pre-commit testing in https://github.com/intel/llvm/pull/10435/checks via some manual workarounds.

Thank you!

> I don't understand the question.

This PR shows Green and "All check passed" , in that case, approves might merge it if they don't check the CI status carefully.
I meant should we default to return "Some checks were not successful" if we did not run the required `Pre-commit` CI tests?

**Comment by bader** [comment]
> > Yes, I just realized it -- is it a bug or new change that we don't run Pre-commit CI test automatically now?
> 
> Security feature - we don't allow running tasks for arbitrary PRs that modify files affecting CI. We will need to allow such pulldown PRs to go by somehow, but that hasn't been worked on yet.

Technically, DPC++ project CI files are separate from LLVM project CI, so we can filter DPC++ CI files more precise than "any files in .github directory".

**Comment by bader** [comment]
> > PS Running pre-commit testing in https://github.com/intel/llvm/pull/10435/checks via some manual workarounds.
> 
> Thank you!
> 
> > I don't understand the question.
> 
> This PR showed Green and "All check passed" around 1 hour ago, in that case, approvers might merge it if they don't check the CI status carefully. I meant should we default to return "Some checks were not successful" if we did not run the required `Pre-commit` CI tests?

+1 for changing the logic from "skip" to "fail".

**Comment by bader** [comment]
@jsji, build on windows failed.

> D:\github\_work\llvm\llvm\src\lld\ELF\Arch\ARM.cpp(974): error C2027: use of undefined type 'lld::elf::ELFFileBase'

Full log - https://github.com/intel/llvm/pull/10435/checks

**Comment by jsji** [comment]
> @jsji, build on windows failed.
> 
> > D:\github_work\llvm\llvm\src\lld\ELF\Arch\ARM.cpp(974): error C2027: use of undefined type 'lld:🧝:ELFFileBase'
> 
> Full log - https://github.com/intel/llvm/pull/10435/checks

Thanks, yes, @Chenyang-L will follow up further.

**Comment by Chenyang-L** [comment]
@bader I think this is ready to merge. The cmath*.ll tests are flaky from what I've seen and everything else is passing.

**Comment by bader** [comment]
> The cmath*.ll tests are flaky from what I've seen and everything else is passing.

Do you mean sycl/test-e2e/DeviceLib/cmath*.cpp test? AFAIK, these are quite stable in the sycl branch, so I suppose failures are caused by the PR changes.

I see you did changes on top of what we pull from the community. I'd like code owners to approve them before merging.

@intel/dpcpp-spirv-reviewers, @intel/dpcpp-tools-reviewers, @intel/llvm-reviewers-runtime, @intel/dpcpp-esimd-reviewers, please, take a look at changes and let me if it's okay to merge. Here is the link with the diff for the latest 10 commits in this PR: https://github.com/intel/llvm/pull/10427/files/bbd88b0a0acc0c946f59e3a50c3788408e890dfc..b2c98d5d27e70a6f817b34fd15553154198026ad. Please, review everything except lld changes.

E.g. https://github.com/intel/llvm/pull/10427/commits/b2c98d5d27e70a6f817b34fd15553154198026ad - the test passes on Windows (see latest pre-commit results). We need to figure out why it doesn't work on Linux. 

@Chenyang-L, did you open a tracker for all the tests disabled in this PR?

**Comment by Chenyang-L** [comment]
> > The cmath*.ll tests are flaky from what I've seen and everything else is passing.
> 
> Do you mean sycl/test-e2e/DeviceLib/cmath*.cpp test? AFAIK, these are quite stable in the sycl branch, so I suppose failures are caused by the PR changes.
> 
> I see you did changes on top of what we pull from the community. I'd like code owners to approve them before merging.
> 
> @intel/dpcpp-spirv-reviewers, @intel/dpcpp-tools-reviewers, @intel/llvm-reviewers-runtime, @intel/dpcpp-esimd-reviewers, please, take a look at changes and let me if it's okay to merge. Here is the link with the diff for the latest 10 commits in this PR: https://github.com/intel/llvm/pull/10427/files/bbd88b0a0acc0c946f59e3a50c3788408e890dfc..b2c98d5d27e70a6f817b34fd15553154198026ad. Please, review everything except lld changes.
> 
> E.g. [b2c98d5](https://github.com/intel/llvm/commit/b2c98d5d27e70a6f817b34fd15553154198026ad) - the test passes on Windows (see latest pre-commit results). We need to figure out why it doesn't work on Linux.
> 
> @Chenyang-L, did you open a tracker for all the tests disabled in this PR?

I opened up https://jira.devtools.intel.com/browse/CMPLRTST-21914 for the lit tests disabled in this PR. I just noticed I included some Intel related changes that preserved some of the previous typed pointer code. If needed, those can be removed.

**Comment by sarnex** [comment]
For ESIMD, I have no idea why `sycl/test-e2e/ESIMD/private_memory.cpp` is failing, IMO it's okay to merge this but please open a tracker and assign it to me to investigate.

**Comment by bader** [comment]
> For ESIMD, I have no idea why `sycl/test-e2e/ESIMD/private_memory.cpp` is failing, IMO it's okay to merge this but please open a tracker and assign it to me to investigate.

@sarnex, thanks for confirming.

@intel/dpcpp-spirv-reviewers, @intel/dpcpp-tools-reviewers, @intel/llvm-reviewers-runtime, we need your confirmation too. Please, take a look at changes and let me if it's okay to merge. Details are in my previous comment - https://github.com/intel/llvm/pull/10427#issuecomment-1666253507.

**Comment by jsji** [comment]
@intel/dpcpp-spirv-doc-reviewers @intel/dpcpp-tools-reviewers @intel/llvm-reviewers-runtime Can you please have a look? We need to get this merged ASAP, as we have HUGE backlog (sycl branch is 1.5 months behind main now), we need to start another pulldown soon. Thanks.

**Comment by bader** [comment]
> E.g. [b2c98d5](https://github.com/intel/llvm/commit/b2c98d5d27e70a6f817b34fd15553154198026ad) - the test passes on Windows (see latest pre-commit results).

Maybe it wasn't clear from the previous message, but we need to fix the status of test on Windows. CI checks results are "fail" on Windows. @Chenyang-L, @jsji, please, make sure there are no regressions in CI checks except clang-format check.

**Comment by jsji** [comment]
> > E.g. [b2c98d5](https://github.com/intel/llvm/commit/b2c98d5d27e70a6f817b34fd15553154198026ad) - the test passes on Windows (see latest pre-commit results).
> 
> Maybe it wasn't clear from the previous message, but we need to fix the status of the test on Windows. CI checks results are "fail" on Windows. @Chenyang-L, @jsji, please, make sure there are no regressions in CI checks except clang-format check.

Did I interpret the result correctly? It is a unexpected pass? @Chenyang-L @bader ?
FYI. @tylanphear @wwXing0 Let us take over this to get this merged. Thanks.

Unexpectedly Passed Tests (1):
  SYCL :: DeviceLib/cmath_test.cpp

**Comment by jsji** [comment]
> Did I interpret the result correctly? It is a unexpected pass? @Chenyang-L @bader ? FYI. @tylanphear @wwXing0 Let us take over this to get this merged. Thanks.
> 
> Unexpectedly Passed Tests (1): SYCL :: DeviceLib/cmath_test.cpp

I force-pushed to XFAIL this on Linux only. Let us see the test result.

**Comment by jsji** [comment]
Hmm.. Looks like we have some sort of CI env differences?
There is NO source code change, I only changed the XFAIL in in the test file ESIMD/private_memory.cpp.

2 hours ago, CI is telling me, this test is XPASS:
https://github.com/intel/llvm/actions/runs/5813164854/job/15762998873

So I reverted it back to original state.
Then the CI 24 minutes ago is telling me , this test is now XFAIL!
https://github.com/intel/llvm/actions/runs/5815260358/job/15767274830



Looking at the log:

XPASS one is with only L0 runtime:
"::group::sycl-ls --verbose"
[ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Iris(R) Xe Graphics 1.3 [1.3.26370]

: 'RUN: at line 13';    D:/github/**actions-runner**/_work/llvm/llvm/install/bin/clang++.exe   -fsycl -fsycl-targets=spir64 D:\github\actions-runner\_work\llvm\llvm\llvm\sycl\test-e2e\ESIMD\private_memory.cpp -fsycl-device-code-split=per_kernel -o D:\github\actions-runner\_work\llvm\llvm\build-e2e\ESIMD\Output\private_memory.cpp.tmp.out
: 'RUN: at line 14';   env ONEAPI_DEVICE_SELECTOR=ext_oneapi_level_zero:gpu  D:\github\actions-runner\_work\llvm\llvm\build-e2e\ESIMD\Output\private_memory.cpp.tmp.out

XFAILED one is with both OCL and L0 runtime:
[opencl:gpu:0] Intel(R) OpenCL Graphics, Intel(R) Iris(R) Xe Graphics OpenCL 3.0 NEO  [31.0.101.4502]
[ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Iris(R) Xe Graphics 1.3 [1.3.26370]

: 'RUN: at line 13';    D:/github/_work/llvm/llvm/install/bin/clang++.exe   -fsycl -fsycl-targets=spir64 D:\github\_work\llvm\llvm\llvm\sycl\test-e2e\ESIMD\private_memory.cpp -fsycl-device-code-split=per_kernel -o D:\github\_work\llvm\llvm\build-e2e\ESIMD\Output\private_memory.cpp.tmp.out
: 'RUN: at line 14';   env ONEAPI_DEVICE_SELECTOR=ext_oneapi_level_zero:gpu  D:\github\_work\llvm\llvm\build-e2e\ESIMD\Output\private_memory.cpp.tmp.out
--

But both are testing L0 runtime.
So looks like we have different build env here? I suspect that we did not clobber build in the 2nd run in Machine name: 'JFEW-TL-119893'

**Comment by jsji** [comment]
Hmm, I am really confused by the CI here. I need some help to investigate what is really wrong here. @aelovikov-intel @bader Can either of you help here? Thanks.

**Comment by bader** [comment]
> @intel/dpcpp-spirv-reviewers, @intel/dpcpp-tools-reviewers, @intel/llvm-reviewers-runtime, we need your confirmation too. Please, take a look at changes and let me if it's okay to merge. Details are in my previous comment - [#10427 (comment)](https://github.com/intel/llvm/pull/10427#issuecomment-1666253507).

Ping.

**Comment by bader** [comment]
I think we can drop this commit - https://github.com/intel/llvm/pull/10427/commits/fb840cd274828d47c292f4c3c590b69194dba19c. It's not needed as we switched to opaque pointers by default.

**Comment by jsji** [comment]
> I think we can drop this commit - [fb840cd](https://github.com/intel/llvm/commit/fb840cd274828d47c292f4c3c590b69194dba19c). It's not needed as we switched to opaque pointers by default.

If we are going to do this, then we need to get rid of more:

* | 34b54f44b162 - (2023-07-31) Revert "Use -emit-opaque-pointers for SPIR-V-friendly IR." - Chenyang Liu
* | 6a06f3e93a03 - (2023-07-31) Revert "Convert tests to use -emit-opaque-pointers (#2084)" - Chenyang Liu

Let me try to reorg the commit a little bit, but it might cause additional efforts to clean up these tests due to the outdated code.

**Comment by jsji** [comment]
> 23 successful, 4 failing, and 1 skipped checks

Mark the current status -- the 4 failure are known failures -- 2 clang-format failures, 2 MacOS failures also seen in sycl.

**Comment by jsji** [comment]
Force pushed to include only necessary changes -- discard all other opaque pointer lit changes first for now. Will cherry-pick some of them if we see failures in CI.

**Comment by jsji** [comment]
> Hmm, I am really confused by the CI here. I need some help to investigate what is really wrong here. @aelovikov-intel @bader Can either of you help here? Thanks.
> 
> eg: I pushed a commit, and there are two `Post-commit` CI triggered, one for the commit and passed, the other for the PR it failed. What are the difference of these two `Post-commit` CI? Why we need to run two times?
> 
> [LLVM and SPIRV-LLVM-Translator pulldown (WW29)](https://github.com/intel/llvm/actions/runs/5813164854) SYCL Post Commit #4171: Pull request #10427 synchronize by [jsji](https://github.com/jsji) [llvmspirv_pulldown](https://github.com/intel/llvm/tree/llvmspirv_pulldown) 6 hours ago 3h 41m 51s [mark 2 sycl tests XFAIL](https://github.com/intel/llvm/actions/runs/5813145030) SYCL Post Commit #4170: Commit [3cdff00](https://github.com/intel/llvm/commit/3cdff000d2bb06c8230e0b1bf37a492caba7a49a) pushed by [jsji](https://github.com/jsji) [llvmspirv_pulldown](https://github.com/intel/llvm/tree/llvmspirv_pulldown) 6 hours ago 3h 22m 20s
> 
> The PR run was successful: https://github.com/intel/llvm/actions/runs/5815261173 But the commit itself is failing: https://github.com/intel/llvm/actions/runs/5815260358

For completeness,  the two CI run is somehow a *bug* or *know limitation* in CI, one (push) is running against branch itself, the other one (PR) is running against sycl branch ,  and since we switched the opaque pointer in sycl branch, we end up getting opposite result here.
That is why I *HAVE* to merge sycl branch into this PR again.

Thanks @aelovikov-intel  for helping to sorting out this, and follow up to get rid of duplicate post-commit CI run.

**Comment by jsji** [comment]
> > I think we can drop this commit - [fb840cd](https://github.com/intel/llvm/commit/fb840cd274828d47c292f4c3c590b69194dba19c). It's not needed as we switched to opaque pointers by default.
> 
> If we are going to do this, then we need to get rid of more:
> 
> * | [34b54f4](https://github.com/intel/llvm/commit/34b54f44b162ac4fafc67c7a672ea19fb150958b) - (2023-07-31) Revert "Use -emit-opaque-pointers for SPIR-V-friendly IR." - Chenyang Liu
> * | [6a06f3e](https://github.com/intel/llvm/commit/6a06f3e93a031b594572a022d49464a82ad2edfc) - (2023-07-31) Revert "Convert tests to use -emit-opaque-pointers ([Adding buffer_location SPIR-V spec as an extension #2084](https://github.com/intel/llvm/pull/2084))" - Chenyang Liu
> 
> Let me try to reorg the commit a little bit, but it might cause additional efforts to clean up these tests due to the outdated code.

So, looks like we DO need those commits like - [fb840cd](https://github.com/intel/llvm/commit/fb840cd274828d47c292f4c3c590b69194dba19c). [34b54f4](https://github.com/intel/llvm/commit/34b54f44b162ac4fafc67c7a672ea19fb150958b) [6a06f3e](https://github.com/intel/llvm/commit/6a06f3e93a031b594572a022d49464a82ad2edfc) for the current stage of pulldown.

We have two choice:
1. Merge this PR and keep those commits for now. Fixing them in next pulldown.
2. Abandon this PR, doing a pulldown to get latest state of sycl-web and llvm-spirv code.

#2 will be better as it will get rid of these middle states of lit changes etc, 
but apparently we will need more time to stabilize it.

**Comment by jsji** [comment]
Close this first, try to do a new pulldown PR with latest state instead.

**Comment by bader** [comment]
> We have two choice:
> 
> 1. Merge this PR and keep those commits for now. Fixing them in next pulldown.
> 2. Abandon this PR, doing a pulldown to get latest state of sycl-web and llvm-spirv code.

@jsji, I'm okay with option 1, if option 2 takes a lot of time.

**Comment by jsji** [comment]
> > We have two choice:
> > 
> > 1. Merge this PR and keep those commits for now. Fixing them in next pulldown.
> > 2. Abandon this PR, doing a pulldown to get latest state of sycl-web and llvm-spirv code.
> 
> @jsji, I'm okay with option 1, if option 2 takes a lot of time.

Thanks. Trying #2 in https://github.com/intel/llvm/pull/10783 first. If we end up getting complications, then we can fall back to option 1 here.

**Pull request closed without merging**
