### PR TITLE
[SYCL] Disable clang pedantic diagnostics in header/footer

### PR DESCRIPTION
**Pull request by premanandrao**
When -Wreserved-identifer or -Wold-style-cast is enabled, some of the constructs used in
integration headers and footers for device_globals and host_pipes trigger a diagnostic.
This change adds a pragma to the generated files that suppress the diagnostic prior to
the construct and reenabled the diagnostic after.

### CODE REVIEW

**Review by maarquitos14 — APPROVED** [review]
LGTM.

**Review by elizabethandrews — APPROVED** [review]

**Comment by premanandrao** [comment]
@intel/llvm-gatekeepers, this is ready for merge.   The test failures seem unrelated to my changes.

**Review by smanna12 — APPROVED** [review]

**Comment by aelovikov-intel** [comment]
> @intel/llvm-gatekeepers, this is ready for merge. The test failures seem unrelated to my changes.

This looks weird and I'm not aware of any issues with gen12 runners. I'm re-running the failed job.

**Comment by premanandrao** [comment]
> > @intel/llvm-gatekeepers, this is ready for merge. The test failures seem unrelated to my changes.
> 
> This looks weird and I'm not aware of any issues with gen12 runners. I'm re-running the failed job.

Thanks!  Looks finished?

**Pull request merged**
