### PR TITLE
[SYCL][NFC] Update status of SYCL_INTEL_local_memory extension

### PR DESCRIPTION
**Pull request by sergey-semenov**

### CODE REVIEW

**Comment by Pennycook** [comment]
I just took a look at the [documentation](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/LocalMemory/SYCL_INTEL_local_memory.asciidoc) and the [implementation](https://github.com/intel/llvm/blob/54ede407edeb93b7e9334d1e725f48bf981b2965/sycl/include/CL/sycl/group_local_memory.hpp) and noticed that:

1. The extension is written against SYCL 1.2.1, not SYCL 2020
2. The extension and implementation both use the wrong namespace (`cl::sycl::` instead of `sycl::ext::oneapi`)

Can we fix these issues before marking the extension as "implemented"?  I'm worried that once we mark things as "implemented" developers will start to use the extension, and then these issues will be harder to fix.

I can handle the rewrite of the extension, if somebody else (maybe you, Sergey) can handle the namespace changes and move the header files to the correct place.

**Comment by sergey-semenov** [comment]
@Pennycook Yeah, that makes sense. I'll handle the namespace change then.

**Comment by Pennycook** [comment]
@sergey-semenov Great, thanks!  Should I push the fixed spec onto the branch associated with this PR?

**Comment by sergey-semenov** [comment]
> @sergey-semenov Great, thanks! Should I push the fixed spec onto the branch associated with this PR?

Let's just handle the changes separately and hold off on merging this PR until both are done.

**Comment by sergey-semenov** [comment]
https://github.com/intel/llvm/pull/4326 and https://github.com/intel/llvm/pull/4346 have been merged. @Pennycook I think we can proceed with this.

**Review by Pennycook — APPROVED** [review]
LGTM.  Thanks again, @sergey-semenov!

**Pull request merged**
