### PR TITLE
[SYCL] Disable RTTI for SYCL device compilation

### PR DESCRIPTION
**Pull request by elizabethandrews**
We do not support RTTI in kernel code. Do not emit type info during SYCL device compilation.
This aligns SYCL with other offloading targets like CUDA.

### CODE REVIEW

**Comment by elizabethandrews** [comment]
ping @premanandrao @smanna12

**Review by premanandrao — APPROVED** [review]
LGTM.

For my own curiosity, what was the removed test testing for?  Couldn't tell if that was just basic functionality test.

**Comment by elizabethandrews** [comment]
> LGTM.
> 
> For my own curiosity, what was the removed test testing for? Couldn't tell if that was just basic functionality test.

It just checked IR for vtable and typeinfo. We've removed type info and since we already have another test checking vtable IR, I removed this test since it was superflous.

**Review by smanna12 — APPROVED** [review]
LGTM

**Pull request merged**
