### PR TITLE
[SYCL] Remove all uses of `_be` suffix in testing

### PR DESCRIPTION
**Pull request by hdelan**
The `_be` suffix was used in sycl/test to identify support for lots of
different backends. For instance: `hip_be`, `cuda_be` etc.

sycl/test-e2e used the same backend identifiers but without the `_be`
suffix. This has caused some confusion, allowing tests to be added to
sycl/test that do not use the `_be` suffix, meaning they are considered
UNSUPPORTED for all backends.

This patch removes all uses of the `_be` suffix in sycl/test, so that
the backend support is aligned with the keywords used in sycl/test-e2e.
Some tests that were not running for any backends now fail, so they are
marked XFAIL.

### CODE REVIEW

**Review by frasercrmck — APPROVED** [review]
LGTM

**Review by jchlanda — APPROVED** [review]
The patch looks OK, but we are in a bit of a `REQUIRES` mess already, perhaps you'd consider unifying it across the entire testing. We seem to be using all different flavours now:
* [hip](https://github.com/intel/llvm/blob/sycl/sycl/test/check_device_code/hip/matrix/matrix-hip-double-double-test.cpp#L1)
* [hip_be](https://github.com/intel/llvm/blob/sycl/sycl/test/extensions/macro_hip.cpp#L3)
* [cuda](https://github.com/intel/llvm/blob/sycl/sycl/test/check_device_code/math-builtins/native-math-cuda.cpp#L1)
* [cuda_be](https://github.com/intel/llvm/blob/sycl/sycl/test/basic_tests/interop-backend-traits-cuda.cpp#L1)

Feel free to ignore it, in which case: LGTM.

**Comment by hdelan** [comment]
> The patch looks OK, but we are in a bit of a `REQUIRES` mess already, perhaps you'd consider unifying it across the entire testing. We seem to be using all different flavours now:

Good shout. Have changed so all uses of `_be` are removed. Will be interesting to see if more tests fail

**Review by cperkinsintel — APPROVED** [review]

**Comment by hdelan** [comment]
Ping @intel/dpcpp-nativecpu-pi-reviewers

**Review by PietroGhg — APPROVED** [review]
Native CPU lgtm, sorry for the late review

**Pull request merged**
