### PR TITLE
Cast Integer to enumeration type using static_cast for KernelNameType

### PR DESCRIPTION
**Pull request by srividya-sundaram**
For specializations of KernelInfo for kernel function types, cast Integer to Enumeration type using static_cast. 
Eg: `template <> struct KernelInfo<::dummy_functor_1<(no_namespace_int)0>>` to
`template <> struct KernelInfo<::dummy_functor_1<static_cast<no_namespace_int>(0)>>`
Issue# : https://github.com/intel/llvm/issues/1784

### CODE REVIEW

**Comment by elizabethandrews** [comment]
Error does not seem related to patch.

       [19/33] Performing update step for 'l0-loader'
        FAILED: tools/sycl/plugins/level_zero/l0-loader-prefix/src/l0-loader-stamp/l0-loader-update 
        cd /localdisk2/sycl_ci/buildbot/worker/sycl-ubu-x64- 
        pr/llvm.obj/tools/sycl/plugins/level_zero/Level0/l0_loader && /usr/local/bin/cmake -P 
        /localdisk2/sycl_ci/buildbot/worker/sycl-ubu-x64-pr/llvm.obj/tools/sycl/plugins/level_zero/l0- 
        loader-prefix/tmp/l0-loader-gitupdate.cmake
        fatal: unable to access 'https://github.com/oneapi-src/level-zero.git/': Couldn't connect to 
        server
        CMake Error at /localdisk2/sycl_ci/buildbot/worker/sycl-ubu-x64- 
        pr/llvm.obj/tools/sycl/plugins/level_zero/l0-loader-prefix/tmp/l0-loader-gitupdate.cmake:55 
        (message):
        Failed to fetch repository 'https://github.com/oneapi-src/level-zero.git'

@bader is this a known issue?

**Comment by bader** [comment]
+@againull

**Comment by Fznamznon** [comment]
Could you please follow these guidelines when writing commit message in the future?  https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

**Comment by srividya-sundaram** [comment]
Tried rebuilding the failed check and got : `Cannot rebuild: you need to have role 'llvm-write'`
Can someone add me to that role?

**Comment by elizabethandrews** [comment]
Oh strange. I don't think I have write access too but I am able to rebuild. Can you make sure you are signed in? Top right corner will say 'Anonymous' if you are not signed in. Maybe that is issue?

**Comment by srividya-sundaram** [comment]
Thanks. I had to authorize bb-sycl to access my github account.

**Comment by againull** [comment]
> +@againull

This looks like CI issue to me:
fatal: unable to access 'https://github.com/oneapi-src/level-zero.git/': Couldn't connect to 
    server
Please report to CI team.

**Pull request merged**
