### PR TITLE
[SYCL] Fix race condition in EnqueueNativeCommand

### PR DESCRIPTION
**Pull request by hdelan**
Wrong command type was being used for enqueue native command, causing a race condition as the host task codepath was being taken, where another path should have been taken. This fixes https://github.com/intel/llvm/issues/14715

@sarnex

### CODE REVIEW

**Review by sarnex — APPROVED** [review]
lgtm in terms of i think it should fix the nightly failure. we should have a seperate tracker to fix the root cause and reenable this case

**Comment by hdelan** [comment]
> lgtm in terms of i think it should fix the nightly failure. we should have a seperate tracker to fix the root cause and reenable this case

Yep I'm investigating as we speak

**Comment by sarnex** [comment]
thx

**Comment by hdelan** [comment]
@sarnex bug found. See update

**Comment by sarnex** [comment]
thanks! im not qualified to review this fix but i really appreciate the quick investigation and root cause fix!

**Review by cperkinsintel — APPROVED** [review]

**Review by bso-intel — APPROVED** [review]

**Pull request merged**
