### PR TITLE
[X86] Create all-one vector(v8i32) for TESTC(X,~X) == TESTC(X,-1) if …

### PR DESCRIPTION
**Pull request by yubingex007-a11y**
…X is v8f32

### CODE REVIEW

**Comment by AlexeySachkov** [comment]
Is there any reason this is not pushed to the upstream `llvm/llvm-project` repo?

**Comment by yubingex007-a11y** [comment]
> Is there any reason this is not pushed to the upstream `llvm/llvm-project` repo?
some customer would like to fix a bug ASAP.

**Comment by yubingex007-a11y** [comment]
i encounter a issue that i can't cherry-pick  https://reviews.llvm.org/D148608 to intel/llvm since the testcase doesn't match. i guess there is some commits in llorg change the testcase and these commits are not in intel/llvm .

**Comment by yubingex007-a11y** [comment]
i saw there commit modified llvm/llvm/test/CodeGen/X86/combine-testpd.ll in llorg but these commits are not in intel/llvm.
so it is brutal to cherry-pick all of them. Thus, i remove the testcase changes.
when pulldown coordinator see the commit land on xmain-web it lead to conflict and he will add back the testcases.
@AlexeySachkov

**Comment by yubingex007-a11y** [comment]
@AlexeySachkov ping?

**Comment by yubingex007-a11y** [comment]
ping? @AlexeySachkov

**Review by AlexeySachkov — APPROVED** [review]
I'm ok with cherry-picking this earlier to unblock a customer.

@againull, @FreddyLeaf: FYI. This is a _partial_ cherry-pick of [D148608](https://reviews.llvm.org/D148608), because we had to adjust tests to avoid cherry-picking more commits. If you encounter conflicts with this patch, they should be resolved by picking community version of the code

**Comment by againull** [comment]
USM/usm_pooling.cpp reported here: https://github.com/intel/llvm/issues/9148

**Pull request merged**
