### PR TITLE
[SYCL][E2E] Fix sycl-ls discovery

### PR DESCRIPTION
**Pull request by npmiller**
We should also look for `sycl-ls` in the `PATH` and not just in the llvm tools dir.

### CODE REVIEW

**Comment by aelovikov-intel** [comment]
\+ @frasercrmck

**Comment by npmiller** [comment]
> Why is that so? Are you trying to use `sycl-ls` outside of the build?

Specifically, I'm running E2E tests standalone against the release package's `clang++`, it's located in `bin/compiler` rather than `bin`, so the current lit setup isn't able to find `sycl-ls`.

But more broadly this seems to be the only restrictions to using a compiler and a runtime installed in different locations when running the tests.

**Comment by aelovikov-intel** [comment]
We have some tight coupling between `sycl-ls` output format and the E2E infrastructure, so I wouldn't want to pick some random version of it from the `PATH`...

Can we make it more explicit for the user, maybe by asking to provide the path to `sycl-ls` explicitly? WDYT?

**Comment by npmiller** [comment]
Closing this.

We've ended up deciding it didn't make that much sense to run tests against the `clang++` binary from the release package so we don't need this anymore.

If we do end up revisiting it at some point I do agree that a flag to point to a specific `sycl-ls` binary would make sense.

**Pull request closed without merging**
