### PR TITLE
[SYCL][Driver] Enable SPV_INTEL_memory_access_aliasing extension

### PR DESCRIPTION
**Pull request by MrSidims**
Signed-off-by: Dmitry Sidorov <dmitry.sidorov@intel.com>

### CODE REVIEW

**Comment by MrSidims** [comment]
>> InvalidModule: Invalid SPIR-V module: input SPIR-V module uses unknown extension 'SPV_INTEL_memory_access_aliasing'

Moved to draft.

**Review by vzakhari — APPROVED** [review]
LGTM

**Comment by MrSidims** [comment]
I believe with GPU RT update the patch is ready to be tested and reviewed.

**Pull request closed without merging**
