### PR TITLE
[SYCL][NFC] Specify target for XFAIL command

### PR DESCRIPTION
**Pull request by zahiraam**
Making the XFAIL run command line target specific.

### CODE REVIEW

**Review by elizabethandrews — APPROVED** [review]

**Review by smanna12 — APPROVED** [review]

**Comment by bader** [comment]
@zahiraam, what if we change the title to: "[SYCL][NFC] Specify target for XFAIL command"?

**Comment by zahiraam** [comment]
> @zahiraam, what if we change the title to: "[SYCL][NFC] Specify target for XFAIL command"?

@bader this PR is still testing since yesterday! Isn't strange?

**Comment by bader** [comment]
> > @zahiraam, what if we change the title to: "[SYCL][NFC] Specify target for XFAIL command"?
> 
> @bader this PR is still testing since yesterday! Isn't strange?

It's not expected. Pre-commit should be fast.

**Comment by zahiraam** [comment]
> > > @zahiraam, what if we change the title to: "[SYCL][NFC] Specify target for XFAIL command"?
> > 
> > 
> > @bader this PR is still testing since yesterday! Isn't strange?
> 
> It's not expected. Pre-commit should be fast.

That's strange! What can I do about it?

**Comment by bader** [comment]
> > > > @zahiraam, what if we change the title to: "[SYCL][NFC] Specify target for XFAIL command"?
> > > 
> > > 
> > > @bader this PR is still testing since yesterday! Isn't strange?
> > 
> > 
> > It's not expected. Pre-commit should be fast.
> 
> That's strange! What can I do about it?

I think you should talk with QA/Tools team about this.

**Pull request merged**
