### PR TITLE
[SYCL] Widen (u)int8/16 to (u)int32 in group operations

### PR DESCRIPTION
**Pull request by dnmokhov**
CPU device does not yet support the (u)int8/16 versions.

### CODE REVIEW

**Review by v-klochkov — COMMENTED** [review]
Looks good to me. 
@Pennycook would you please take a quick look at this patch.

**Review by Pennycook — COMMENTED** [review]
I just want to check what this means (if anything) for future releases, since there are some tests here checking that everything lowers to i32 in the SPIR-V.  When the CPU device supports the 8-bit and 16-bit group operations natively, how difficult is it going to be to revert this change?  Will it trigger any API/ABI breakage concerns?

**Comment by dnmokhov** [comment]
> I just want to check what this means (if anything) for future releases, since there are some tests here checking that everything lowers to i32 in the SPIR-V. When the CPU device supports the 8-bit and 16-bit group operations natively, how difficult is it going to be to revert this change? Will it trigger any API/ABI breakage concerns?

My understanding is that reverting this change will make newly compiled kernels use the i8/i16 __spirv_GroupXXX API versions. The i32 ones will still be there, so
- kernels compiled with this change will work with old and new CPU drivers;
- kernels compiled after reverting this change will require new CPU drivers.

**Comment by Pennycook** [comment]
> My understanding is that reverting this change will make newly compiled kernels use the i8/i16 __spirv_GroupXXX API versions. The i32 ones will still be there, so
> 
> * kernels compiled with this change will work with old and new CPU drivers;
> * kernels compiled after reverting this change will require new CPU drivers.

Ok, that makes sense.  Thanks for the explanation.

**Review by Pennycook — APPROVED** [review]

**Review by v-klochkov — APPROVED** [review]

**Pull request merged**
