### PR TITLE
[SYCL-MLIR] Merge from intel/llvm sycl branch

### PR DESCRIPTION
**Pull request by whitneywhtsang**
Please only review https://github.com/intel/llvm/pull/8774/commits/dbcd0beda6fe0a7ed70f5947a7a93712d04e3e30, which is similar to https://github.com/intel/llvm/commit/e74334e26dbf337c81ddcbb13ae3ab83e02df81b, `detail::dim_loop<>` cannot be handled correctly by `cgeist`.

Temporally reverted https://github.com/intel/llvm/commit/130466e924c51d408408d2a8b8f774d2a119baf4 to unblock the merge, modified https://github.com/intel/llvm/issues/8616 to investigate and add it back.

Reverted https://github.com/intel/llvm/commit/a0d0942d2b42d937b9ec41e7526d93c608a2beaf due to cmake data race described in https://github.com/intel/llvm/pull/8774#issuecomment-1483724722.

Please do not squash and merge this PR.

### CODE REVIEW

**Comment by bader** [comment]
> I cannot reproduce the error from `Linux / Build + LIT` locally:
> 
> ```
> /__w/llvm/llvm/src/sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero_common.hpp:10:10: fatal error: sycl/detail/pi.h: No such file or directory
>    10 | #include <sycl/detail/pi.h>
>       |          ^~~~~~~~~~~~~~~~~~
> ```
> 
> The change came from #8517, and it could be built successfully. @AlexeySachkov Any idea why we are getting the error here?

@jandres742, I've seen this issue on my system too. It disappears when I do incremental build, so I think there is some missing dependency in cmake files. Do you know anything about this?

**Comment by jandres742** [comment]
> > I cannot reproduce the error from `Linux / Build + LIT` locally:
> > ```
> > /__w/llvm/llvm/src/sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero_common.hpp:10:10: fatal error: sycl/detail/pi.h: No such file or directory
> >    10 | #include <sycl/detail/pi.h>
> >       |          ^~~~~~~~~~~~~~~~~~
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The change came from #8517, and it could be built successfully. @AlexeySachkov Any idea why we are getting the error here?
> 
> @jandres742, I've seen this issue on my system too. It disappears when I do incremental build, so I think there is some missing dependency in cmake files. Do you know anything about this?

@bader , @whitneywhtsang :

I cannot reproduce it locally, but it might be other change https://github.com/intel/llvm/pull/8637. could you try w/o that patch?

**Comment by bader** [comment]
> > > I cannot reproduce the error from `Linux / Build + LIT` locally:
> > > ```
> > > /__w/llvm/llvm/src/sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero_common.hpp:10:10: fatal error: sycl/detail/pi.h: No such file or directory
> > >    10 | #include <sycl/detail/pi.h>
> > >       |          ^~~~~~~~~~~~~~~~~~
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The change came from #8517, and it could be built successfully. @AlexeySachkov Any idea why we are getting the error here?
> > 
> > 
> > @jandres742, I've seen this issue on my system too. It disappears when I do incremental build, so I think there is some missing dependency in cmake files. Do you know anything about this?
> 
> @bader , @whitneywhtsang :
> 
> I cannot reproduce it locally, but it might be other change #8637. could you try w/o that patch?

It's hard to say for sure if reverting this patch removes the data race, but a few tries went okay.

**Comment by whitneywhtsang** [comment]
> > > > I cannot reproduce the error from `Linux / Build + LIT` locally:
> > > > ```
> > > > /__w/llvm/llvm/src/sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero_common.hpp:10:10: fatal error: sycl/detail/pi.h: No such file or directory
> > > >    10 | #include <sycl/detail/pi.h>
> > > >       |          ^~~~~~~~~~~~~~~~~~
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > The change came from #8517, and it could be built successfully. @AlexeySachkov Any idea why we are getting the error here?
> > > 
> > > 
> > > @jandres742, I've seen this issue on my system too. It disappears when I do incremental build, so I think there is some missing dependency in cmake files. Do you know anything about this?
> > 
> > 
> > @bader , @whitneywhtsang :
> > I cannot reproduce it locally, but it might be other change #8637. could you try w/o that patch?
> 
> It's hard to say for sure if reverting this patch removes the data race, but a few tries went okay.

`Linux / Build + LIT` passes with #8637 reverted.

**Comment by jandres742** [comment]
> > > > > I cannot reproduce the error from `Linux / Build + LIT` locally:
> > > > > ```
> > > > > /__w/llvm/llvm/src/sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero_common.hpp:10:10: fatal error: sycl/detail/pi.h: No such file or directory
> > > > >    10 | #include <sycl/detail/pi.h>
> > > > >       |          ^~~~~~~~~~~~~~~~~~
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > The change came from #8517, and it could be built successfully. @AlexeySachkov Any idea why we are getting the error here?
> > > > 
> > > > 
> > > > @jandres742, I've seen this issue on my system too. It disappears when I do incremental build, so I think there is some missing dependency in cmake files. Do you know anything about this?
> > > 
> > > 
> > > @bader , @whitneywhtsang :
> > > I cannot reproduce it locally, but it might be other change #8637. could you try w/o that patch?
> > 
> > 
> > It's hard to say for sure if reverting this patch removes the data race, but a few tries went okay.
> 
> `Linux / Build + LIT` passes with #8637 reverted.



> > > > > I cannot reproduce the error from `Linux / Build + LIT` locally:
> > > > > ```
> > > > > /__w/llvm/llvm/src/sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero_common.hpp:10:10: fatal error: sycl/detail/pi.h: No such file or directory
> > > > >    10 | #include <sycl/detail/pi.h>
> > > > >       |          ^~~~~~~~~~~~~~~~~~
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > The change came from #8517, and it could be built successfully. @AlexeySachkov Any idea why we are getting the error here?
> > > > 
> > > > 
> > > > @jandres742, I've seen this issue on my system too. It disappears when I do incremental build, so I think there is some missing dependency in cmake files. Do you know anything about this?
> > > 
> > > 
> > > @bader , @whitneywhtsang :
> > > I cannot reproduce it locally, but it might be other change #8637. could you try w/o that patch?
> > 
> > 
> > It's hard to say for sure if reverting this patch removes the data race, but a few tries went okay.
> 
> `Linux / Build + LIT` passes with #8637 reverted.

Thanks @whitneywhtsang .

@bader : do we need then to revert https://github.com/intel/llvm/pull/8637 on sycl branch?

**Review by sommerlukas — APPROVED** [review]

**Comment by whitneywhtsang** [comment]
Merged commit https://github.com/intel/llvm/commit/dbcd0beda6fe0a7ed70f5947a7a93712d04e3e30 into https://github.com/intel/llvm/tree/sycl-mlir.

**Pull request closed without merging**
