### PR TITLE
[SYCL] Fix post-commit issue with library dependencies

### PR DESCRIPTION
**Pull request by AlexeySachkov**

### CODE REVIEW

**Review by maksimsab — APPROVED** [review]
Looks much better than my approach.

**Review by sarnex — APPROVED** [review]

**Comment by sarnex** [comment]
Seems this doesn't work @AlexeySachkov 
```
sycl-module-split: /__w/llvm/llvm/src/llvm/include/llvm/IR/PassManager.h:474: typename PassT::Result& llvm::AnalysisManager<IRUnitT, ExtraArgTs>::getResult(IRUnitT&, ExtraArgTs ...) [with PassT = llvm::PassInstrumentationAnalysis; IRUnitT = llvm::Module; ExtraArgTs = {}; typename PassT::Result = llvm::PassInstrumentation]: Assertion `AnalysisPasses.count(PassT::ID()) && "This analysis pass was not registered prior to being queried"' failed.
```

**Comment by AlexeySachkov** [comment]
> Seems this doesn't work @AlexeySachkov
> 
> ```
> sycl-module-split: /__w/llvm/llvm/src/llvm/include/llvm/IR/PassManager.h:474: typename PassT::Result& llvm::AnalysisManager<IRUnitT, ExtraArgTs>::getResult(IRUnitT&, ExtraArgTs ...) [with PassT = llvm::PassInstrumentationAnalysis; IRUnitT = llvm::Module; ExtraArgTs = {}; typename PassT::Result = llvm::PassInstrumentation]: Assertion `AnalysisPasses.count(PassT::ID()) && "This analysis pass was not registered prior to being queried"' failed.
> ```

Yeah, I didn't run tests locally, only build. But I've just pushed another commit which should fix this issue

**Comment by sarnex** [comment]
Cool thx

**Review by asudarsa — APPROVED** [review]
Thanks for taking care of this @AlexeySachkov

**Comment by sarnex** [comment]
CI is broken RN and this fixes build issues, so merging to unbreak build for everyone.

**Pull request merged**
