### PR TITLE
[SYCL][NFC] Simplify working with mock images in unit tests

### PR DESCRIPTION
**Pull request by AlexeySachkov**
Most of our unit-tests only care about getting a device image with certain kernels and certain properties regardless of how other fields are set.

This patch introduces a new constructor to UrImage to simplify unit-tests code. Also it cleans up some includes and uses existing helpers where possible to generate device images for tests.

### CODE REVIEW

**Review by againull — APPROVED** [review]

**Comment by AlexeySachkov** [comment]
Most recent update did not bring any new functionality, it was just a merge with `sycl` branch to adjust the PR to the codebase changes (namely removal of `UrArray`). I previously wanted for another PR to go first, but it was a long time ago and this one should be ready, so let's go with it first.

Once CI passes, I will proceed with commit here, assuming that the previous approval still stands (simply because there were no significant changes made during the merge)

**Comment by sarnex** [comment]
@AlexeySachkov Seeing some werror postcommit fails unfortunately
```
In file included from /__w/llvm/llvm/src/sycl/unittests/helpers/TestKernel.hpp:12:
/__w/llvm/llvm/src/sycl/unittests/helpers/UrImage.hpp:279:25: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
  279 |             "", "", {}, std::move(std::vector<unsigned char>{1, 2, 3, 4, 5}),
      |                         ^
/__w/llvm/llvm/src/sycl/unittests/helpers/UrImage.hpp:279:25: note: remove std::move call here
  279 |             "", "", {}, std::move(std::vector<unsigned char>{1, 2, 3, 4, 5}),
      |                         ^~~~~~~~~~                                         ~
```

**Comment by AlexeySachkov** [comment]
> @AlexeySachkov Seeing some werror postcommit fails unfortunately
> 
> ```
> In file included from /__w/llvm/llvm/src/sycl/unittests/helpers/TestKernel.hpp:12:
> /__w/llvm/llvm/src/sycl/unittests/helpers/UrImage.hpp:279:25: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
>   279 |             "", "", {}, std::move(std::vector<unsigned char>{1, 2, 3, 4, 5}),
>       |                         ^
> /__w/llvm/llvm/src/sycl/unittests/helpers/UrImage.hpp:279:25: note: remove std::move call here
>   279 |             "", "", {}, std::move(std::vector<unsigned char>{1, 2, 3, 4, 5}),
>       |                         ^~~~~~~~~~                                         ~
> ```

Looking into it

**Comment by AlexeySachkov** [comment]
> > @AlexeySachkov Seeing some werror postcommit fails unfortunately
> > ```
> > In file included from /__w/llvm/llvm/src/sycl/unittests/helpers/TestKernel.hpp:12:
> > /__w/llvm/llvm/src/sycl/unittests/helpers/UrImage.hpp:279:25: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
> >   279 |             "", "", {}, std::move(std::vector<unsigned char>{1, 2, 3, 4, 5}),
> >       |                         ^
> > /__w/llvm/llvm/src/sycl/unittests/helpers/UrImage.hpp:279:25: note: remove std::move call here
> >   279 |             "", "", {}, std::move(std::vector<unsigned char>{1, 2, 3, 4, 5}),
> >       |                         ^~~~~~~~~~                                         ~
> > ```
> 
> Looking into it

#15675

I've re-configured my local build to use `clang` in order to see all those warnings. I don't think that passing `-werror` to `configure.py` did anything, because I still don't see any errors, but at least I don't see those warnings anymore with that patch

**Pull request merged**
