### PR TITLE
[SYCL] Enable JIT tests relying on debug output

### PR DESCRIPTION
**Pull request by jchlanda**
Wrap the tests in `REQUIRE: asserts` in order to make sure that the compiler can generate the messages.

Also make sure we don't run the e2e tests on windows, as JIT is not supported there.

### CODE REVIEW

**Comment by jchlanda** [comment]
Fixes #14783

**Review by sommerlukas — APPROVED** [review]

**Comment by jchlanda** [comment]
I had to introduce a dedicated feature `has_ndebug` in order to be able to reliably test the debug output. I decided to remove the debug test form sycl-fusion's directory, as in order to enable a `has_ndebug` feature there we would first need to teach it about the `dpcpp_compiler` and that seemed like too much of a hustle for this purpose.

@ldrumm, you might want to have a quick look at this, thank you!

**Comment by jchlanda** [comment]
Fixes https://github.com/intel/llvm/issues/14989

**Comment by jchlanda** [comment]
Friendly ping @sarnex (and @maarquitos14, somehow your previous 👍 disappeared).

Thank you.

**Review by maarquitos14 — APPROVED** [review]

**Comment by jchlanda** [comment]
@intel/llvm-gatekeepers this should be ready to go, thank you.

**Pull request merged**
