### PR TITLE
[SYCL] Move Driver tests into a model-specific directory

### PR DESCRIPTION
**Pull request by AGindinson**
List of changes (view from `clang/test/Driver/`):
1. Move all SYCL tests into `SYCL/`.
2. Move SYCL inputs from `Inputs/SYCL` into `SYCL/Inputs/`. Adjust
paths in LIT `RUN` lines accordingly.
3. Copy CUDA inputs into `SYCL/Inputs/CUDA/`.
4. Clean up empty lines at EOF.

Signed-off-by: Artem Gindinson <artem.gindinson@intel.com>

### CODE REVIEW

**Comment by AGindinson** [comment]
@bader, the only SYCL test present in LLORG so far is `clang/test/Driver/sycl.c`. Would it be preferable if I moved the test into a similar `SYCL` directory in upstream first? What's your general take on such a reorg in terms of "upstreamability"?

**Comment by bader** [comment]
> Would it be preferable if I moved the test into a similar `SYCL` directory in upstream first?

I think so, because I see that driver tests for other programming models are located in `clang/test/Driver` directory, so you suggestion is not aligned with common community practice and therefore I make sense to discuss it before making the change.
I'm not sure if it solves any practical problem.

**Comment by AGindinson** [comment]
> Your suggestion is not aligned with common community practice and therefore it makes sense to discuss it before making the change.

Fair point; I will bring the proposition to the community before proceeding here.

> I'm not sure if it solves any practical problem.

It's more of a convenience matter; the following is the rationale list from #3817:
1. Easier time launching SYCL-specific tests locally (llvm-lit clang/test/Driver/SYCL/ instead of llvm-lit clang/test/Driver/sycl-* # Let's hope there are no other namings)
2. Less clutter in the base directory
3. Along the way, tests like sycl-offload.c could also be decluttered

**Comment by bader** [comment]
I don't see much difference between these two approaches: put test to "SYCL/" directory or name test with "sycl-" prefix.
I use LIT_FILTER env. variable to launch sycl specific tests.

**Comment by AGindinson** [comment]
Revisiting this now, I feel like revoking the suggestion. The "non-debated" advantage regarding `sycl-offload.c` decluttering has little to do with the topic and deserves a separate issue.

**Pull request closed without merging**
