### PR TITLE
[GHA] Uplift Linux IGC Dev RT version to igc-dev-afcddb0

### PR DESCRIPTION
**Pull request by bb-sycl**
Scheduled igc dev drivers uplift

### CODE REVIEW

**Review by YuriPlyakhin — COMMENTED** [review]
I believe, this one should be closed. It seems all ESIMD and Joint Matrix tests failed.

**Comment by sarnex** [comment]
@YuriPlyakhin As in we should just wait for the next version and hope it's fixed?

**Comment by YuriPlyakhin** [comment]
> @YuriPlyakhin As in we should just wait for the next version and hope it's fixed?

Yep

**Comment by sarnex** [comment]
Sounds good, will close

**Pull request closed without merging**
