### PR TITLE
[SYCL][E2E] Update minimum driver version for get_backend.cpp

### PR DESCRIPTION
**Pull request by sarnex**
I manually tested this on DG2.

### CODE REVIEW

**Review by aelovikov-intel — APPROVED** [review]

**Comment by AlexeySachkov** [comment]
@sarnex, the test still fails in [post-commit](https://github.com/intel/llvm/actions/runs/7693185039/job/20963430826):

```
FAIL: SYCL :: Basic/get_backend.cpp (190 of 1850)
******************** TEST 'SYCL :: Basic/get_backend.cpp' FAILED ********************
Exit Code: -6

Command Output (stdout):
--
# RUN: at line 3
/__w/llvm/llvm/toolchain/bin//clang++   -fsycl -fsycl-targets=spir64 /__w/llvm/llvm/llvm/sycl/test-e2e/Basic/get_backend.cpp -o /__w/llvm/llvm/build-e2e/Basic/Output/get_backend.cpp.tmp.out
# executed command: /__w/llvm/llvm/toolchain/bin//clang++ -fsycl -fsycl-targets=spir64 /__w/llvm/llvm/llvm/sycl/test-e2e/Basic/get_backend.cpp -o /__w/llvm/llvm/build-e2e/Basic/Output/get_backend.cpp.tmp.out
# note: command had no output on stdout or stderr
# RUN: at line 4
/__w/llvm/llvm/build-e2e/Basic/Output/get_backend.cpp.tmp.out
# executed command: /__w/llvm/llvm/build-e2e/Basic/Output/get_backend.cpp.tmp.out
# .---command stderr------------
# | terminate called after throwing an instance of 'sycl::_V1::runtime_error'
# |   what():  Native API failed. Native API returns: -999 (Unknown PI error) -999 (Unknown PI error)
# `-----------------------------
# error: command failed with exit status: -6
```

Is that something this PR should have fixed, or is it something else requiring investigation?

**Comment by sarnex** [comment]
@AlexeySachkov Sorry I'll look at this again, I don't understand what's happening

**Comment by sarnex** [comment]
The driver check was wrong, I'll disable it and make an internal tracker

**Comment by sarnex** [comment]
https://github.com/intel/llvm/pull/12530

**Pull request merged**
