### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW08 2024)

### PR DESCRIPTION
**Pull request by sys-ce-bb**
LLVM: llvm/llvm-project@815644b4dd882ade2e5649d4f97c3dd6f7aea200
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@747ef0f0ec03a25b5fb4edf5f5bf43e794503806

### CODE REVIEW

**Comment by jsji** [comment]
This is ready for review.
- [ ] [Enable support of non-instrinsic debug-info](https://github.com/intel/llvm/pull/12799/commits/a5ef6c4f883e90b763c5601174a0bec1c7778a23) This is to reenable the support that we disabled in last week's pulldown after fixes in spirv translator and sycl-fusion (and community fixes).
- [ ]

**Comment by jsji** [comment]
The failure in Windows and AWS CUDA are unstable CI.

**Comment by AlexeySachkov** [comment]
> @MrSidims @intel/dpcpp-tools-reviewers would you please add explicit comments/approval for [Enable support of non-instrinsic debug-info](https://github.com/intel/llvm/pull/12799/commits/a5ef6c4f883e90b763c5601174a0bec1c7778a23) so that this can be merged? Thanks!

Mechanical nature of the change looks good to me. Whether or not the rest of the stack is ready for this, I think @MrSidims should know better

**Review by AlexeySachkov — APPROVED** [review]

**Comment by jsji** [comment]
Thanks @AlexeySachkov ! @MrSidims  approved my draft PR to enable it here. https://github.com/intel/llvm/pull/12768#pullrequestreview-1893072262. 

The Pre-commit CI are happy with this, so I'd like to at least give it a try. We can always flip back if we find problems after turning it on (sync with community).

**Comment by jsji** [comment]
@bader @intel/llvm-gatekeepers OK to merge? Thanks.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Mon 26 Feb 2024 07:55:37 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Mon 26 Feb 2024 08:03:13 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
