### PR TITLE
[SYCL][Matrix] Correct Prefetch instruction usage

### PR DESCRIPTION
**Pull request by MrSidims**

### CODE REVIEW

**Review by maarquitos14 — APPROVED** [review]
LGTM.

**Review by dkhaldi — APPROVED** [review]
LGTM. 
Can we cherry pick this in xmain?

**Comment by MrSidims** [comment]
@intel/llvm-gatekeepers please help with merge

**Review by MrSidims — COMMENTED** [review]
I haven't pushed another change, sorry, wait a bit

**Comment by sarnex** [comment]
Oh my god that was so close
image

**Comment by steffenlarsen** [comment]
ESIMD/aot_mixed.cpp should have been fixed with https://github.com/intel/llvm/pull/12650. @MrSidims - Is this ready for merging?

**Comment by MrSidims** [comment]
@steffenlarsen yes, thanks for checking!

**Pull request merged**
