### PR TITLE
[SYCL] Add bfloat16 generic implementation for fmax, fmin

### PR DESCRIPTION
**Pull request by jinge90**
Signed:sign-off-by: jinge90 <ge.jin@intel.com>

### CODE REVIEW

**Review by romanovvlad — APPROVED** [review]
LGTM

**Comment by jinge90** [comment]
Hi, @romanovvlad 
I update the PR to fix a return type error of isnan and a conflict with sycl complex headers, could you help review again?
Thanks very much.

**Review by romanovvlad — APPROVED** [review]

**Comment by jinge90** [comment]
Hi, @JackAKirk and @gmlueck 
Kind ping~
Thanks very much.

**Review by xtian-github — APPROVED** [review]
LGTM

**Review by bader — APPROVED** [review]

**Review by xtian-github — APPROVED** [review]
LGTM

**Comment by gmlueck** [comment]
It looks like this PR adds a new public API `sycl::ext::oneapi::experimental::isnan()`.  Was that intentional, or should this be in `detail`?  If it was intentionally added, the extension specification should be updated.

**Comment by jinge90** [comment]
> It looks like this PR adds a new public API `sycl::ext::oneapi::experimental::isnan()`. Was that intentional, or should this be in `detail`? If it was intentionally added, the extension specification should be updated.

Hi, @gmlueck 
I think isnan should be added in spec since all other fp format (fp32, fp64, fp16) supports it, I will create a PR to update the spec doc.
Thanks very much.

**Pull request merged**
