### PR TITLE
[Do Not Merge][CI] Verify CI functions

### PR DESCRIPTION
**Pull request by DoyleLi**
Signed-off-by: Xiaodong Li <xiaodong.li@intel.com>
This PR is for verification use. Please do not merge it. Thanks!

### CODE REVIEW

**Comment by DoyleLi** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/559

**Comment by bader** [comment]
@DoyleLi, can we close this PR?

**Comment by DoyleLi** [comment]
> @DoyleLi, can we close this PR?

Sure, I will close it now.

**Pull request closed without merging**
