### PR TITLE
[DeviceSanitizer] Strip off pointer casts and inbounds GEPs

### PR DESCRIPTION
**Pull request by zhaomaosu**
Disable device sanitizer instrument following case:
%0 = load i64, ptr addrspace(1) getelementptr inbounds (i8,
  ptr addrspace(1) @__spirv_BuiltInGlobalInvocationId, i64 8)

### CODE REVIEW

**Review by wenju-he — COMMENTED** [review]
could you add a example in pr description?

**Comment by zhaomaosu** [comment]
> could you add a example in pr description?

Done, also added a lit test.

**Review by wenju-he — APPROVED** [review]
LGTM

**Comment by AllanZyne** [comment]
Just a side note, I added this in https://github.com/intel/llvm/pull/13247 as well

**Review by AlexeySachkov — APPROVED** [review]

**Comment by zhaomaosu** [comment]
Hi @intel/llvm-gatekeepers, could you please help merge this PR? Thanks.

**Pull request merged**
