### PR TITLE
[SYCL][NATIVECPU] Allow building Native CPU with shared libraries

### PR DESCRIPTION
**Pull request by PietroGhg**
Currently building Native CPU with shared libraries enabled leads to a CMake error when configuring: some components of the oneAPI Construction Kit depend on `LLVMPasses`, and since they are also added as `link_libraries` to `SYCLLowerIR` (which `LLVMPasses` depends on), that creates a circular dependency that is not allowed when building with shared libraries enabled.
This PR addresses this by moving all the Native CPU components to a new folder (`SYCLNativeCPUUtils`), that is not linked to `LLVMPasses`, thus breaking the circular dependencies.

### CODE REVIEW

**Review by AlexeySachkov — APPROVED** [review]

**Review by smanna12 — APPROVED** [review]

**Review by kbenzie — APPROVED** [review]
UR LGTM

**Comment by PietroGhg** [comment]
Hi @intel/dpcpp-esimd-reviewers, could you take a look at this PR? Thanks

**Comment by PietroGhg** [comment]
@intel/dpcpp-esimd-reviewers ping

**Comment by PietroGhg** [comment]
@intel/dpcpp-esimd-reviewers ping

**Review by uwedolinsky — APPROVED** [review]

**Comment by wenju-he** [comment]
kindly ping @intel/dpcpp-esimd-reviewers for review

**Comment by PietroGhg** [comment]
Hi @intel/llvm-gatekeepers, this looks ready to merge, windows failure is infrastructural, see https://github.com/intel/llvm/pull/14370#issuecomment-2203142568

**Pull request merged**
