### PR TITLE
[SYCL][E2E] XFAIL tests failing in new driver

### PR DESCRIPTION
**Pull request by sarnex**
Failing on the new driver [here](https://github.com/intel/llvm/actions/runs/11259739126/job/31309872610?pr=15626).

### CODE REVIEW

**Review by aarongreig — APPROVED** [review]

**Comment by sarnex** [comment]
@intel/llvm-reviewers-runtime Ping on this one, thanks!

**Review by uditagarwal97 — APPROVED** [review]

**Comment by sarnex** [comment]
Thanks!

**Comment by AlexeySachkov** [comment]
@sarnex, those tests seems to have passed in post-commit here: https://github.com/intel/llvm/actions/runs/11289334750/job/31399311520

Do you know what's the reason for that?

**Comment by sarnex** [comment]
@AlexeySachkov We aren't using the new driver where they XFAIL yet, I will merge it in https://github.com/intel/llvm/pull/15626 soon, sorry for the trouble

**Pull request merged**
