### PR TITLE
[GHA] Uplift Linux GPU RT version to 22.39.24347

### PR DESCRIPTION
**Pull request by bb-sycl**
Scheduled drivers uplift

### CODE REVIEW

**Comment by pvchupin** [comment]
@smaslov-intel, @againull , it seems all tests fail in Level Zero mode with the new driver uplift. Could you please help to triage?

**Comment by smaslov-intel** [comment]
> @smaslov-intel, @againull , it seems all tests fail in Level Zero mode with the new driver uplift. Could you please help to triage?

Lots of failures are like this. I am going to try reproduce locally.
Is the new driver installed anywhere?
```
$ "env" "SYCL_DEVICE_FILTER=ext_oneapi_level_zero:gpu" "/__w/llvm/llvm/build/SYCL/Assert/Output/assert_in_kernels.cpp.tmp.out"
# redirected output from '/__w/llvm/llvm/build/SYCL/Assert/Output/assert_in_kernels.cpp.tmp.txt':
terminate called after throwing an instance of 'sycl::_V1::runtime_error'
  what():  Native API failed. Native API returns: -997 (The plugin has emitted a backend specific error) -997 (The plugin has emitted a backend specific error)

note: command had no output on stdout or stderr
error: command failed with exit status: -6
```

**Comment by pvchupin** [comment]
> Lots of failures are like this. I am going to try reproduce locally. Is the new driver installed anywhere?

I don't think so. This PR is first attempt to try that.
We probably should be building container with that at least, not doing that today.
That's this one: https://github.com/intel/compute-runtime/releases/tag/22.39.24347

**Comment by bader** [comment]
> We probably should be building container with that at least, not doing that today.

We were doing this before @pvchupin removed it in https://github.com/intel/llvm/pull/6581. :)
See [this comment](https://github.com/intel/llvm/pull/6581#discussion_r962280324).

**Comment by pvchupin** [comment]
> We were doing this before @pvchupin removed it in #6581. :) See [this comment]

We did it wrong imo. Instead of producing a PR for unstable version uplift simultaneously with stable version uplift, the task which builds unstable containers should just always pickup the latest driver and build the container. No additional PR needed.
I'll submit a new PR if there is a need for such container.

**Comment by pvchupin** [comment]
Closing this PR. Weekly uplift will retrigger this again automatically. Driver is still broken.

**Pull request closed without merging**
