### PR TITLE
[SYCL][Doc] Fix TBB installation instructions

### PR DESCRIPTION
**Pull request by vladimirlaz**
The issues has been reported in https://github.com/intel/llvm/issues/823#issuecomment-567349126

### CODE REVIEW

**Comment by AlexeySachkov** [comment]
@agozillon: FYI

**Comment by agozillon** [comment]
Nice, thanks for the quick fix!

I also forgot to mention in the previous statement I raised that I think the following command may also be a bit outdated for the most recent TBB release:
 
```
mkdir -p /opt/intel/tbb
cd /opt/intel/tbb
tar -zxvf tbb2019_<version>oss_lin.tgz
```
It appears that the newer release I'm using (tbb-2020.0-lin.tgz) will un-package into a tbb and pstl folder, which means you end up with /opt/intel/tbb/tbb (if the intent of the above commands is to tar extract directly into /opt/intel/tbb).
    
I think the command could perhaps be:
```
mkdir -p /opt/intel/
cd /opt/intel/
tar -zxvf tbb2019_<version>oss_lin.tgz
```
That is if the intent was to end up with just an /opt/intel/tbb like the current symbolic link commands seem to expect. Or alternatively I suppose the symbolic link commands could just be updated to be prefixed with /opt/intel/tbb/tbb/ rather than the current /opt/intel/tbb/

**Comment by vladimirlaz** [comment]
@agozillon The file has been adopted for changes in TBB 2020.

**Comment by agozillon** [comment]
> @agozillon The file has been adopted for changes in TBB 2020.

Awesome, LGTM thanks for fixing this and sorry for bothering you with it!

**Pull request merged**
