### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW39)

### PR DESCRIPTION
**Pull request by sys-ce-bb**
LLVM: llvm/llvm-project@c43aa46
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@3d28e52

### CODE REVIEW

**Comment by jsji** [comment]
One fix to be reviewed. 
- [ ] [[LLVM-SPIRV][TEST] Fix debug info order in FortranArray.ll due to](https://github.com/intel/llvm/pull/11347/commits/30e051c2cd78af41d15db9fcfa6a7c8b6aa8db2c) https://github.com/intel/llvm/commit/f8aab289b5549086062588fba627b0e4d3a5ab15 @intel/dpcpp-spirv-reviewers

**Review by MrSidims — APPROVED** [review]

**Comment by jsji** [comment]
@intel/llvm-gatekeepers @bader I think this is ready to be merged. Thanks.

**Comment by jsji** [comment]
Ping https://github.com/orgs/intel/teams/llvm-gatekeepers @bader. Can we get this merged? Thanks!

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Mon 02 Oct 2023 02:49:56 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Mon 02 Oct 2023 02:54:29 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
