### PR TITLE
[SYCL] Honor dependencies of empty command groups

### PR DESCRIPTION
**Pull request by aelovikov-intel**

### CODE REVIEW

**Comment by aelovikov-intel** [comment]
Not very familiar with the scheduler, so this can be totally wrong. And if this is the right direction, then there might be some work left for @intel/sycl-graphs-reviewers to support the same when part of SYCL graph.

**Comment by aelovikov-intel** [comment]
Hm, I wouldn't expect. I'm going to wait till the job finishes and restart the failing task plus see how the next commit's post-commit CI behaves.

**Comment by aelovikov-intel** [comment]
Interesting, 

```
#include <sycl/sycl.hpp>

int main() {
  sycl::queue q;
  sycl::buffer<int, 1> b{1};

  q.submit([&](sycl::handler &cgh) {
    sycl::accessor a{b, cgh, sycl::read_write_host_task};
  });
  return 0;
}
``` 
passes, but 

```
#include <sycl/sycl.hpp>

using namespace sycl::access;

int main() {
  sycl::queue q;

  sycl::unsampled_image<1> UImg(sycl::image_format::r32b32g32a32_uint, 3);

  q.submit([&](sycl::handler &cgh) {
    auto A1 =
        UImg.get_access<sycl::uint4, mode::read, sycl::image_target::host_task>(
            cgh);
  });
  return 0;
}
```
fails:
```
$ clang++ -fsycl a.cpp -O0 -gdwarf-4
$ ./a.out
terminate called after throwing an instance of 'sycl::_V1::exception'
  what():  Enqueue process failed.
Aborted (core dumped)
```

**Comment by sarnex** [comment]
I don't understand why it didn't fail in precommit either. It looks like the failure case is L0 + gen12 + linux, which we definitely have in precommit. Weird.

**Pull request merged**
