### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW01)

### PR DESCRIPTION
**Pull request by sys-ce-bb**
LLVM: llvm/llvm-project@202a4c0dfb19823a0c0fc737e32d205efaffb7ff
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@c0e19d67eccf2f5b93568ff6eb0b9f363590b26d

### CODE REVIEW

**Comment by jsji** [comment]
@bader @intel/llvm-gatekeepers This is ready for merge, no review needed. Thanks.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Fri 05 Jan 2024 04:39:56 AM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Fri 05 Jan 2024 04:44:01 AM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
