### PR TITLE
[SYCL] Adjust local size of ND range for host device

### PR DESCRIPTION
**Pull request by vmaksimo**
If local size is not set explicitly for host, it will be set to 1, so
nd_range_error for zero local size is not thrown.

Signed-off-by: Viktoria Maksimova <viktoria.maksimova@intel.com>

### CODE REVIEW

**Comment by keryell** [comment]
I think that the text describing this PR should appear as a comment in the code.
Otherwise, do you think it makes sense to have the local range to be a multiple of the CPU SIMD lane size to have efficient SIMD execution on CPU?

**Comment by michaelxtian** [comment]
Having local group size being multiple of SIMD width is very important for achieving optimal performance on CPU. E.g. for binomial workload, we want to have 8 * SIMD width to get a good performance as if it were vectorized with SIMD16  with unroll(8).

**Comment by romanovvlad** [comment]
> 
> 
> I think that the text describing this PR should appear as a comment in the code.
> Otherwise, do you think it makes sense to have the local range to be a multiple of the CPU SIMD lane size to have efficient SIMD execution on CPU?

I don't think we should do it. First of all the host kernel is not autovectorized across over workitems, so number of work-items inside work-group makes [almost] no difference. And even if the host kernel was verctorized we would need to know how much work-items can be executed using one SIMD lane to make more or less smart decision here.

> Having local group size being multiple of SIMD width is very important for achieving optimal  performance on CPU. E.g. for binomial workload, we want to have 8 * SIMD width to get a good performance as if it were vectorized with SIMD16 with unroll(8).

If the requirements are so clear why not specify local size explicitly?

**Comment by keryell** [comment]
> First of all the host kernel is not autovectorized across over workitems, so number of work-items inside work-group makes [almost] no difference.

Probably I do not understand how the device host works in your implementation.
But in triSYCL and some other implementation the work-item loop inside a work-group is just a normal loop. So if it is compiled with a normal compiler as any other host code, there is still some hope that the code will be vectorized...

**Pull request merged**
