### PR TITLE
[ESIMD] Fixed a copy-paste bug in simd_view::operator--

### PR DESCRIPTION
**Pull request by DenisBakhvalov**

### CODE REVIEW

**Comment by bader** [comment]
Test?

**Comment by DenisBakhvalov** [comment]
> Test?

Frankly, I don't want to introduce E2E test (~70 LOC) just for this operator. It is an obvious copy-paste bug.

**Comment by DenisBakhvalov** [comment]
> Test?

https://github.com/intel/llvm-test-suite/pull/281

**Comment by DenisBakhvalov** [comment]
@kbobrovs, if no objections, this patch can be merged.

**Review by kbobrovs — APPROVED** [review]

**Pull request merged**
