### PR TITLE
[SYCL] Rename intel_reqd_sub_group_size attribute metadata

### PR DESCRIPTION
**Pull request by smanna12**
This commit renames metadata nodes introduced by the intel_reqd_sub_group_size attribute feature design document from using intel_ prefix to use sycl_ prefix.

Addresses https://github.com/intel/llvm/issues/6824

Signed-off-by: Soumi Manna <soumi.manna@intel.com>

### CODE REVIEW

**Comment by smanna12** [comment]
This is a follow-up comment from https://github.com/intel/llvm/pull/6822#issuecomment-1252444481

**Comment by steffenlarsen** [comment]
I believe we will need the SPIR-V translator to also correctly consume the renamed metadata. @MrSidims - Can you confirm?

**Review by AlexeySachkov — CHANGES_REQUESTED** [review]

**Comment by elizabethandrews** [comment]
IMO what is important right now is to identify all the `intel_` LLVM IR metadata that we generate for SYCL and see if we can/should rename it to `sycl_`.  We already renamed metadata related to optional device features but the answer might not be as straightforward for other cases. If we want consistency and clarity, IMO this should investigation should be done first.

**Comment by MrSidims** [comment]
> I believe we will need the SPIR-V translator to also correctly consume the renamed metadata. @MrSidims - Can you confirm?

Sorry for a long response, don't hesitate to ping me :)

Yes, it would require the appropriate change. But I have the same concern as Alexey.

**Pull request closed without merging**
