### PR TITLE
[CI] Uplift clang 13->15 in post-commit

### PR DESCRIPTION
**Pull request by pvchupin**
Update post-commit task where we build SYCL toolchain with clang instead of GCC

### CODE REVIEW

**Comment by pvchupin** [comment]
> Let's see if focal has clang-15. If not, we can combine this change with #7671.

It has it seems: https://apt.llvm.org/focal/dists/

**Comment by bader** [comment]
@pvchupin, any idea what's going on with pre-commit here? GitHub glitch?

**Comment by pvchupin** [comment]
Had to rebase, because post-commit is not using the current head of the repo.

**Comment by bader** [comment]
> Had to rebase, because post-commit is not using the current head of the repo.

Still fails. Is it due to compiler update or just unfortunate commit? I see that post-commit has been failing recently.

**Comment by pvchupin** [comment]
I think this is real this time, i.e. related to compiler update. I haven't see this issue in other post-commits.

**Comment by pvchupin** [comment]
@zahiraam, can you take a look?

```
/home/runner/work/llvm/llvm/build/include/sycl/stream.hpp:744:21: error: 'sycl_special_class' attribute ignored [-Werror,-Wignored-attributes]
class __SYCL_EXPORT __SYCL_SPECIAL_CLASS __SYCL_TYPE(stream) stream
                    ^
/home/runner/work/llvm/llvm/build/include/sycl/detail/defines.hpp:25:45: note: expanded from macro '__SYCL_SPECIAL_CLASS'
#define __SYCL_SPECIAL_CLASS __attribute__((sycl_special_class))
```
Problem here is that clang-15 recognizes sycl_special_class attribute by __has_attribute(sycl_special_class), but why "attribute ignored" warning is produced?

Related to https://reviews.llvm.org/D114483

**Comment by pvchupin** [comment]
Tagging @intel/dpcpp-cfe-reviewers

**Comment by zahiraam** [comment]
> @zahiraam, can you take a look?
> 
> ```
> /home/runner/work/llvm/llvm/build/include/sycl/stream.hpp:744:21: error: 'sycl_special_class' attribute ignored [-Werror,-Wignored-attributes]
> class __SYCL_EXPORT __SYCL_SPECIAL_CLASS __SYCL_TYPE(stream) stream
>                     ^
> /home/runner/work/llvm/llvm/build/include/sycl/detail/defines.hpp:25:45: note: expanded from macro '__SYCL_SPECIAL_CLASS'
> #define __SYCL_SPECIAL_CLASS __attribute__((sycl_special_class))
> ```
> 
> Problem here is that clang-15 recognizes sycl_special_class attribute by __has_attribute(sycl_special_class), but why "attribute ignored" warning is produced?
> 
> Related to https://reviews.llvm.org/D114483

I didn't get a notice for the ping.
Is it failing only for stream.hpp? The other special (accessor and sampler) classes are defined with the same attribute!

**Comment by zahiraam** [comment]
> @zahiraam, can you take a look?
> 
> ```
> /home/runner/work/llvm/llvm/build/include/sycl/stream.hpp:744:21: error: 'sycl_special_class' attribute ignored [-Werror,-Wignored-attributes]
> class __SYCL_EXPORT __SYCL_SPECIAL_CLASS __SYCL_TYPE(stream) stream
>                     ^
> /home/runner/work/llvm/llvm/build/include/sycl/detail/defines.hpp:25:45: note: expanded from macro '__SYCL_SPECIAL_CLASS'
> #define __SYCL_SPECIAL_CLASS __attribute__((sycl_special_class))
> ```
> 
> Problem here is that clang-15 recognizes sycl_special_class attribute by __has_attribute(sycl_special_class), but why "attribute ignored" warning is produced?
> 
> Related to https://reviews.llvm.org/D114483

This diff should fix the issue:
sh-3.2$ git diff
diff --git a/sycl/include/sycl/detail/defines.hpp b/sycl/include/sycl/detail/defines.hpp
index 23df19ce4b28..3f6c392baf5a 100644
--- a/sycl/include/sycl/detail/defines.hpp
+++ b/sycl/include/sycl/detail/defines.hpp
@@ -21,8 +21,8 @@
 #endif
 #endif

-#if __has_attribute(sycl_special_class)
-#define __SYCL_SPECIAL_CLASS __attribute__((sycl_special_class))
+#if __has_attribute(sycl_special_class) && (defined __SYCL_DEVICE_ONLY__)
+#define __SYCL_SPECIAL_CLASS  __attribute__((sycl_special_class))
 #else
 #define __SYCL_SPECIAL_CLASS
 #endif
sh-3.2$

I am still in the process of testing it. But if you are pressed for time, you might want to cherry pick this and see if that fixes the build issue with clang-15?

**Comment by pvchupin** [comment]
> ) && (defined **SYCL_DEVICE_ONLY**)

I confirm it works. I can submit a PR unless you already did.

**Comment by pvchupin** [comment]
The only task "Linux + Clang + Shared libs (pull_request)" for this change is clean. Merging in.

**Pull request merged**
