### PR TITLE
[SYCL][DOC] Move deprecated extensions

### PR DESCRIPTION
**Pull request by gmlueck**
Move these deprecated extension specifications to the "deprecated"
directory, but add a signpost file in the "supported" directory pointing
at the deprecated extension.

We will follow this convention when a supported extension is deprecated.
The deprecated extension will move to the "deprecated" directory, and
we will change the file in the "supported" directory into a signpost.  Thus,
any external links to the spec will still point to something that leads to the
deprecated extension.

### CODE REVIEW

**Review by Pennycook — APPROVED** [review]

**Comment by pvchupin** [comment]
Is there any way to distinguish supported from supported-but-deprecated?

**Review by bader — DISMISSED** [review]

**Comment by gmlueck** [comment]
> Is there any way to distinguish supported from supported-but-deprecated?

At present you need to open the file and read the content.  A deprecated extension will contain a note near the top saying it is deprecated.  All three of the deprecated extensions in this PR have such a note, though I admit that we should find some better formatting to make this stand out better.

We originally planned to have a "deprecated" directory, and we would move the specification there when it becomes deprecated.  However, @romanovvlad noted that this would cause anyone with an eternal link to the spec to have a broken link.

I see three options:

1. Keep the current POR organization where supported and deprecated extensions are both in the "supported" directory.  People will need to read the file to see whether an extension is deprecated.

2. Go back to our original plan where there is a "deprecated" directory.  If people get a broken link, they will need to learn to look for the extension in the "deprecated" directory.  The directory structure is pretty obvious, so many people will probably figure this out.

3. Create a "deprecated" folder but also keep a "signpost" file in the "supported" folder.  The signpost file will just have some text the says something like:

   > This extension is deprecated.  See "../deprecated/<filename>".

   This is not very much different from option (1) because you still need to open the file to tell whether it is deprecated.

Note that option (2) is the only one that lets you quickly get a list of all the non-deprecated supported extensions (you just look at the list of files in the "supported" directory).  So, if this is important, we should choose that option.

**Comment by pvchupin** [comment]
option (3) looks like the best one.

**Comment by gmlueck** [comment]
> option (3) looks like the best one.

Works for me.  Done in ad0d48bbd4dc26493d72cfbcaa5420419de17f61

**Review by pvchupin — APPROVED** [review]

**Review by Pennycook — APPROVED** [review]

**Pull request merged**
