### PR TITLE
[SYCL][BuildBot] Uplift GPU RT version for Windows to 27.20.100.9030

### PR DESCRIPTION
**Pull request by yanfeng3721**
Windows GFX systems upgrade IGFX driver to 27.20.100.9030

### CODE REVIEW

**Comment by yanfeng3721** [comment]
Hi @yinyangsx , all pre/post commit tests are pass, please prepare the Windows driver uplift.

**Review by yinyangsx — APPROVED** [review]
LGTM, will update for all machines

**Comment by yanfeng3721** [comment]
Hi @romanovvlad  @vladimirlaz , the test machines update is ready. We will switch to 27.20.100.9030 once the PR is merged.

**Review by vladimirlaz — APPROVED** [review]

**Pull request merged**
