### PR TITLE
[SYCL-MLIR] Merge from intel/llvm sycl branch

### PR DESCRIPTION
**Pull request by whitneywhtsang**
Please only review https://github.com/intel/llvm/pull/8849/commits/953eba7c6c617db0078a717f1d63f199b7d2661e and the files with conflict:
```
both modified:   llvm/lib/TargetParser/Triple.cpp
both modified:   mlir/lib/Dialect/Arith/IR/ArithOps.cpp
both modified:   mlir/lib/Dialect/LLVMIR/IR/LLVMDialect.cpp <= SYCL-MLIR change moved to mlir/lib/Dialect/LLVMIR/IR/LLVMInlining.cpp
both modified:   mlir/test/Dialect/LLVMIR/invalid.mlir
```

Temporally reverted https://github.com/intel/llvm/commit/946f8030b58d3d6975369c1b8e047385b86c7ab0, modified https://github.com/intel/llvm/issues/8616 to investigate and add it back.

Please do not squash and merge this PR.

### CODE REVIEW

**Comment by sommerlukas** [comment]
Only reviewed https://github.com/intel/llvm/pull/8849/commits/c4bb8c47cc34014ea9cb6ef025b5f56d22d1579c so far, as accessing the changes to the other four files is a bit too much for my browser. Will need to find a different way to look at those changes. 

For https://github.com/intel/llvm/pull/8849/commits/c4bb8c47cc34014ea9cb6ef025b5f56d22d1579c, I had one question: Why do we need to add two members to `GPUFuncOp`, is that our change to make them work with transformations?

**Comment by victor-eds** [comment]
Changes LGTM apart from comments. I've had to make some changes to merge [this](https://github.com/intel/llvm/commit/af822e25fa82b11470a25eac39ab18364ace3b06) upstream, so I'll apply the changes later today so that we don't have it as a conflict next time.

**Review by sommerlukas — APPROVED** [review]

**Comment by whitneywhtsang** [comment]
Addressed review comment, the commit to fix merge is now https://github.com/intel/llvm/pull/8849/commits/90f7535798cf70ae64b600b5f547496d79e885c3.

**Review by victor-eds — APPROVED** [review]

**Comment by whitneywhtsang** [comment]
Updated the fix merge commit to update the test suite xfail list.

**Comment by whitneywhtsang** [comment]
CI passed in https://github.com/intel/llvm/actions/runs/4555814141/jobs/8037733568.

**Pull request merged**
