### PR TITLE
Revert "[SYCL][FPGA] Restore legacy debug info version for the hardwa…

### PR DESCRIPTION
**Pull request by AGindinson**
…re (#3991)"

The underlying backend is now prepared to accept the `ocl-100` version.

This reverts commit 33bc8adfe4ec60179df8cdae8ed7de00e7e316e0.

### CODE REVIEW

**Review by MrSidims — DISMISSED** [review]

**Review by mdtoguchi — DISMISSED** [review]

**Comment by dm-vodopyanov** [comment]
@AGindinson, should it be moved out from Draft state?

**Comment by AGindinson** [comment]
@dm-vodopyanov, this has a dependence on FPGA BE version. I will launch Summary tests to see if this is compatible with what we have at the moment.

**Review by mdtoguchi — APPROVED** [review]

**Pull request merged**
