### PR TITLE
Undo #2143 to check if problem in issue #645 still actual

### PR DESCRIPTION
**Pull request by KornevNikita**

### CODE REVIEW

**Review by bader — CHANGES_REQUESTED** [review]
Please, "undo" changes with `git revert 2fb2468474af921e8f79a38808096201b391ab99` to revert all the changes.

**Review by bader — CHANGES_REQUESTED** [review]
Please, resolve merge conflicts.

**Comment by KornevNikita** [comment]
Something wrong with reverting, I'll try again

**Comment by bader** [comment]
> /summary:run

Please, do not run summary job. It's not necessary - there should be no difference with previous results because new version is supposed to change only code comments and lit test, which are not validated by this job.

**Comment by bader** [comment]
> Something wrong with reverting, I'll try again

The easiest way to fix it, revert your patch first to recover original `sycl` branch state and apply the command I suggested after that.

**Pull request closed without merging**
