### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW09-10)

### PR DESCRIPTION
**Pull request by vmaksimo**
LLVM: llvm/llvm-project@3fa0e79
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@d46ee75

### CODE REVIEW

**Review by mdtoguchi — DISMISSED** [review]

**Comment by mlychkov** [comment]
+ @erichkeane @sndmitriev @rolandschulz @steffenlarsen @Pennycook 
Could you please review change in https://github.com/intel/llvm/pull/3312/commits/e294673fb7860e89267600a10a037d7bae13f21b for its correctness?

**Comment by erichkeane** [comment]
> 
> 
>     * @erichkeane @sndmitriev @rolandschulz @steffenlarsen @Pennycook
>       Could you please review change in [e294673](https://github.com/intel/llvm/commit/e294673fb7860e89267600a10a037d7bae13f21b) for its correctness?

I don't really have any idea about the CloneFunction pass nor what CloneFunctionChangeType does.

**Comment by mlychkov** [comment]
Precommit LLVM_Test_Suite_Lin with XFAILed FPGA tests (https://github.com/intel/llvm-test-suite/pull/192) is passed: http://icl-jenkins.sc.intel.com:8080/job/SYCL_CI/job/intel/job/Lin/job/LLVM_Test_Suite/2753
Precommit LLVM_Test_Suite_Win with XFAILed FPGA tests (https://github.com/intel/llvm-test-suite/pull/192) is passed: http://icl-jenkins.sc.intel.com:8080/job/SYCL_CI/job/intel/job/Win/job/Test_Suite/1953/

**Comment by vmaksimo** [comment]
These LLVM and SPIRV-LLVM-Translator changes were merged as a part of https://github.com/intel/llvm/pull/3425

**Pull request closed without merging**
