### PR TITLE
[SYCL][COMPAT] Add experimental launch overloads accepting SG size

### PR DESCRIPTION
**Pull request by AD2605**
add experimental launch overloads accepting SG size in SYCL

### CODE REVIEW

**Comment by AD2605** [comment]
@joeatodd @Alcpz Let me know which functions require doxygen here. I compared it with launch.hpp and few have it while other's do not, hence did not document any,
Or is it the readme you are talking about ?

**Comment by joeatodd** [comment]
> @joeatodd @Alcpz Let me know which functions require doxygen here. I compared it with launch.hpp and few have it while other's do not, hence did not document any, Or is it the readme you are talking about ?

Just the README :+1:

**Comment by Alcpz** [comment]
@AD2605 your PRs currently don't automatically trigger the CI. I will try to find a way for your PRs to be able to do so. In the meantime, ping any of us (preferable @intel/syclcompat-lib-reviewers, which pings everyone) to trigger it for you.

**Review by joeatodd — APPROVED** [review]
Looks good @AD2605!

**Comment by joeatodd** [comment]
@intel/llvm-gatekeepers I believe this PR is ready to merge. The `SYCL Pre Commit on Linux` and `SYCL Pre Commit on Windows` pipelines (currently in progress) seem to failing everywhere at present, so I don't think this is a blocker.

**Pull request merged**
