### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW41)

### PR DESCRIPTION
**Pull request by preethi-intel**
LLVM: llvm/llvm-project@9c0314f
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@a3b372c

### CODE REVIEW

**Comment by pvchupin** [comment]
pre-commit testing seems clean, however it doesn't look windows was tested at all. It was triggered by automation before for pulldowns, but I'm not sure why it's not triggered now...
@preethi-intel can you run local windows build + check.py to make sure it's clean?

**Comment by pvchupin** [comment]
Local windows results are good. Merging.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Fri 07 Oct 2022 06:13:25 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Fri 07 Oct 2022 06:17:16 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
