### PR TITLE
[libclc] Move min/max/clamp into the CLC builtins library (#114386)

### PR DESCRIPTION
**Pull request by frasercrmck**
[libclc] Move min/max/clamp into the CLC builtins library (#114386)

These functions are "shared" between integer and floating-point types,
hence the directory name. They are used in several CLC internal
functions such as __clc_ldexp.

Note that clspv and spirv targets don't want to define these functions,
so pre-processor macros replace calls to __clc_min with regular min, for
example. This means they can use as much of the generic CLC source files
as possible, but where CLC functions would usually call out to an
external __clc_min symbol, they call out to an external min symbol. Then
they opt out of defining __clc_min itself in their CLC builtins library.

Preprocessor definitions for these targets have also been changed
somewhat: what used to be CLC_SPIRV (the 32-bit target) is now
CLC_SPIRV32, and CLC_SPIRV now represents either CLC_SPIRV32 or
CLC_SPIRV64. Same goes for CLC_CLSPV.

There are no differences (measured with llvm-diff) in any of the final
builtins libraries for nvptx, amdgpu, or clspv. Neither are there
differences in the SPIR-V targets' LLVM IR before it's actually lowered
to SPIR-V.

----

This is a cherry-pick of 3 upstream commits: fba9f05ff7b36f9cbb5835d79f659290dadecaad, 86974e15f517e8a4ef3bb91125e75cf43d69da6d, and d12a8da1de1ce2c7d8fbf84306a2b6de5c85d707. It starts to move our downstream `libspirv` implementations towards reusing upstream's shared CLC implementations. See the removal of libspirv's `__clc_(clamp|min|max)`.

### CODE REVIEW

**Comment by frasercrmck** [comment]
CC @jsji @maarquitos14. Since this is effectively a mini-pulldown, can we merge it as such, by retaining the original series of commits?

**Comment by jsji** [comment]
> CC @jsji @maarquitos14. Since this is effectively a mini-pulldown, can we merge it as such, by retaining the original series of commits?

OK for me.

**Review by konradkusiak97 — APPROVED** [review]

**Comment by frasercrmck** [comment]
> > CC @jsji @maarquitos14. Since this is effectively a mini-pulldown, can we merge it as such, by retaining the original series of commits?
> 
> OK for me.

Thanks! How would we go about merging this, then?

**Comment by jsji** [comment]
> > > CC @jsji @maarquitos14. Since this is effectively a mini-pulldown, can we merge it as such, by retaining the original series of commits?
> > 
> > 
> > OK for me.
> 
> Thanks! How would we go about merging this, then?

@intel/llvm-gatekeepers Please merge. Thanks.

**Pull request merged**
