### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW07)

### PR DESCRIPTION
**Pull request by vmaksimo**
LLVM: llvm/llvm-project@a5b627a
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@2e3658a

### CODE REVIEW

**Review by DenisBakhvalov — COMMENTED** [review]
Thanks, @AlexeySachkov for doing this. One question: why did you converted ESIMD from `FuncitonPass`'es into `ModulePass`es?

**Comment by AlexeySachkov** [comment]
> Thanks, @AlexeySachkov for doing this. One question: why did you converted ESIMD from `FuncitonPass`'es into `ModulePass`es?

@DenisBakhvalov, some ESIMD `Function` passes did some `Module`-wide stuff in `doInitialization` method - I'm not yet so familiar with new passes infrastructure to see whether there is a proper replacement for such usage model (briefly looking I haven't found anything like that) and so far it was quicker for me to refactor them into `Module` passes

**Comment by DenisBakhvalov** [comment]
> > Thanks, @AlexeySachkov for doing this. One question: why did you converted ESIMD from `FuncitonPass`'es into `ModulePass`es?
> 
> @DenisBakhvalov, some ESIMD `Function` passes did some `Module`-wide stuff in `doInitialization` method - I'm not yet so familiar with new passes infrastructure to see whether there is a proper replacement for such usage model (briefly looking I haven't found anything like that) and so far it was quicker for me to refactor them into `Module` passes

@AlexeySachkov, I see. This could be OK as a temporary solution but I believe we need to refactor it later. Please open an issue and assign it to me.

**Comment by vmaksimo** [comment]
Pulldown was done by another PR #3266

**Pull request closed without merging**
