### PR TITLE
Revert "[SYCL] Add implementation of sycl::intel::barrier"

### PR DESCRIPTION
**Pull request by vladimirlaz**
Reverts intel/llvm#2198

SYCL::barrier.cpp is failing for every run after merging the PR both on Windows and Linux (e.g. http://ci.llvm.intel.com:8010/#/builders/18/builds/3851)

### CODE REVIEW

**Comment by AlexeySachkov** [comment]
Can we just disable failing LIT test instead of reverting the whole patch?

**Comment by vladimirlaz** [comment]
This is good question. It may be caused by interference of different commits. I was not able to get root cause fast enough so I suggest to revert commit to fix constantly failing test in CI.

**Comment by romanovvlad** [comment]
> 
> 
> This is good question. It may be caused by interference of different commits. I was not able to get root cause fast enough so I suggest to revert commit to fix constantly failing test in CI.

+1

**Comment by bader** [comment]
@vladimirlaz, are you going to merge this PR? We need to unblock CI ASAP.

**Comment by Pennycook** [comment]
Which test is failing because of this?

**Comment by AlexeySachkov** [comment]
> Which test is failing because of this?

New test for `barrier` is failing

**Comment by vladimirlaz** [comment]
> Which test is failing because of this?

you can find link: http://ci.llvm.intel.com:8010/#/builders/18/builds/3851

**Comment by Pennycook** [comment]
Ok, thanks.  I can't reproduce this failure locally, but I'll see if I can work out what's going on.

**Comment by bader** [comment]
> Ok, thanks. I can't reproduce this failure locally, but I'll see if I can work out what's going on.

John, please, make sure that your low-level API drivers are up-to-date. There were updated recently.
https://github.com/intel/llvm/blob/sycl/buildbot/dependency.conf

**Comment by Pennycook** [comment]
> John, please, make sure that your low-level API drivers are up-to-date. There were updated recently.
> https://github.com/intel/llvm/blob/sycl/buildbot/dependency.conf

I updated the CPU RT to match the file in dependency.conf, but now nothing works because it doesn't ship with a TBB library.  See https://github.com/intel/llvm/issues/2220.

**Pull request merged**
