### PR TITLE
[SYCL][ESIMD]Fix lsc_slm_block_load test

### PR DESCRIPTION
**Pull request by fineg74**

### CODE REVIEW

**Review by sarnex — APPROVED** [review]

**Review by v-klochkov — COMMENTED** [review]
I don't understand why this change can fix something.
It is even look wrong to me.
The initialization is done in int-type equivalent units - similarly as the verification is done later. That is done intentionally to avoid bits lost or roundings for FP types.
For example, Vals gets different numbers than 1M*GroupID when it is `T` and when it is `Tuint`.

**Comment by sarnex** [comment]
ExpectedVal in the verification is using T but the kernel uses Tint, I assumed that's the problem.

**Comment by v-klochkov** [comment]
> ExpectedVal in the verification for the transpose case is using T but the kernel uses Tuint, I assumed that's the problem.

Ough..., I see now. It seem it is some mess in init/use/verify code here. non-transpose verification has Uint to verify with expected values, but both transposed/non-transposed use the common LSM initialization code.

**Review by v-klochkov — APPROVED** [review]

**Comment by v-klochkov** [comment]
AWS-CUDA fails are unrelated to changes in 2 ESIMD E2E tests. Proceeding to merge now.

**Pull request merged**
