### PR TITLE
Cherry-pick of "Add SPIR-V 1.4 checks"

### PR DESCRIPTION
**Pull request by MrSidims**
One of the patches missing in intel/llvm

Signed-off-by: Sidorov, Dmitry <dmitry.sidorov@intel.com>

Original commit:
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/c5b3c8e3283b

### CODE REVIEW

**Comment by MrSidims** [comment]
Attempt to start resolving https://github.com/intel/llvm/issues/3686

**Review by vmaksimo — APPROVED** [review]

**Comment by MrSidims** [comment]
@bader I believe, this PR can be merged

**Comment by bader** [comment]
@intel/dpcpp-spirv-reviewers, ping.

**Pull request merged**
