### PR TITLE
[CI] Automatically merge HEAD of sycl branch into jobs

### PR DESCRIPTION
**Pull request by alexbatashev**
Try to merge sycl branch into current git state on each test pipeline run. This is done to make sure the latest compiler is always built for testing changes.

### CODE REVIEW

**Review by bader — APPROVED** [review]
Look okay, but I don't see new changes in pre-commit logs. Is that expected?

**Comment by alexbatashev** [comment]
@bader yes, this action will be packed to docker image and delivered to all existing jobs with the new container. You can see the previous commit, where I deliberately get this action from repository and use the version from this PR.

**Comment by bader** [comment]
> You can see the previous commit, where I deliberately get this action from repository and use the version from this PR.

It looks like job the previous commit pull all branches rather than a single target branch. Is it expected?

**Comment by alexbatashev** [comment]
> > You can see the previous commit, where I deliberately get this action from repository and use the version from this PR.
> 
> It looks like job the previous commit pulls all branches rather than a single target branch. Is it expected?

Yes, that’s how github’s checkout action does it. But that’s fine since we keep a full clone locally.

**Review by bader — CHANGES_REQUESTED** [review]
Fix pre-commit.

**Comment by alexbatashev** [comment]
Here's logs with new logic: https://github.com/intel/llvm/runs/5069696547?check_suite_focus=true

**Review by bader — APPROVED** [review]

**Pull request merged**
