### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW47)

### PR DESCRIPTION
**Pull request by Fznamznon**
LLVM: https://github.com/llvm/llvm-project/commit/cbcf123af293ee56876cce16dac83c3008478dae
SPIRV-LLVM-Translator: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/8784853

### CODE REVIEW

**Comment by Fznamznon** [comment]
[b509dba](https://github.com/intel/llvm/pull/7399/commits/b509dba1c3b9c7375cb575d42945b176b886e957) has clean post commit results.
Pre-commit failures seem unrelated.

**Comment by Fznamznon** [comment]
SYCL/Basic/barrier_order.cpp fails in other PRs as well
See for example https://github.com/intel/llvm/actions/runs/3477880483/jobs/5814961418
Also, it passes in [b509dba](https://github.com/intel/llvm/pull/7399/commits/b509dba1c3b9c7375cb575d42945b176b886e957) which is only different by dummy change.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Wed 16 Nov 2022 06:32:45 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Wed 16 Nov 2022 06:37:53 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
