### PR TITLE
 [SYCL] Start running OpenCL through PI

### PR DESCRIPTION
**Pull request by smaslov-intel**
The PI becomes the default ans only way to run a SYCL program.
Underneath OpenCL is still the default plugin of PI.

### CODE REVIEW

**Comment by smaslov-intel** [comment]
The only commit to review is https://github.com/intel/llvm/pull/281/commits/737394f5068306d4ade6c166490bf0da48f5b74b

It is on top of other changes that should be committed with #259.

**Comment by Ruyk** [comment]
737394f  seems empty

**Comment by bader** [comment]
I think @smaslov-intel means https://github.com/intel/llvm/pull/281/commits/81ab1d667a90da010945a7a21d982272e7a840c8. It seems to be the only commit not in #259.

**Comment by smaslov-intel** [comment]
> I think @smaslov-intel means 81ab1d6
That is correct.

**Pull request merged**
