### PR TITLE
[SYCL]Allow parameter pack expansion in device_has attribute

### PR DESCRIPTION
**Pull request by elizabethandrews**

### CODE REVIEW

**Review by premanandrao — APPROVED** [review]
LGTM!

Adding @AaronBallman to check if he can suggest some other variants for testing pack expansion.

**Review by smanna12 — APPROVED** [review]

**Comment by Alexander-Kleymenov** [comment]
Hello, thank you for the update! At what compiler build `device_has` support for variadic args will be available?

**Comment by elizabethandrews** [comment]
> LGTM!
> 
> Adding @AaronBallman to check if he can suggest some other variants for testing pack expansion.

I would be happy to add additional tests if there are any but this patch essentially just uses existing TableGen interface for pack expansion arguments. So most likely whatever currently works for other attributes which accept pack expansions will work here and if something does not work, it probably warrants follow-up work beyond the scope of this PR.

**Comment by elizabethandrews** [comment]
> Hello, thank you for the update! At what compiler build `device_has` support for variadic args will be available?

@Alexander-Kleymenov I will reach out to you via email!

**Review by AaronBallman — APPROVED** [review]
LGTM as well; I don't think there's a need for additional pack expansion testing as part of this patch (I think the coverage is reasonable enough through other attributes, this is just extending the list of attributes using the functionality).

**Comment by elizabethandrews** [comment]
Thanks for the reviews everyone!

@intel/llvm-gatekeepers PR is ready for merge. The failing testing looks infrastructure related.

**Comment by AlexeySachkov** [comment]
```
  Failed Tests (1):
    SYCL :: SubGroup/shuffle_fp64.cpp
```

This is a known issue on CUDA. ESIMD emulator tests passed, but the job reported failure to upload some results somewhere, so it should be ok to merge anyway

**Pull request merged**
