### PR TITLE
[SYCL] Add support for get_native for buffer and fix backend_return_t

### PR DESCRIPTION
**Pull request by maximdimakov**
Add support for sycl::get_native(sycl::buffer) accordingly to the spec. 
Also, fixed backend_return_t for buffer for OpenCL backend.
Signed-off-by: mdimakov [maxim.dimakov@intel.com](mailto:maxim.dimakov@intel.com)

### CODE REVIEW

**Comment by maximdimakov** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/945

**Comment by maximdimakov** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/945

**Review by gmlueck — DISMISSED** [review]
LGTM, but someone else should review

**Comment by maximdimakov** [comment]
@s-kanaev could you please review?

**Comment by maximdimakov** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/945

**Pull request merged**
