### PR TITLE
[SYCL][E2E] Conditionally use `-fsycl-embed-ir` flags in `KernelFusion` e2e tests

### PR DESCRIPTION
**Pull request by ayylol**
`-fsycl-embed-ir` flag is only used when building the `KernelFusion` tests if there is a cuda or hip device. This removes the "argument unused during compilation" warning when running this test on other platforms.

### CODE REVIEW

**Comment by bader** [comment]
@intel/dpcpp-kernel-fusion-reviewers, this change makes me wonder: why do we report a warning in the first place? If I get it right, users have to add `-fsycl-embed-ir` flag when compile for NVIDIA or AMD targets, but it's not required for SPIR targets. 
Can we consider embedding IR by default to make user experience unified across all targets?

@mdtoguchi, FYI.

**Comment by ayylol** [comment]
> @intel/dpcpp-kernel-fusion-reviewers, this change makes me wonder: why do we report a warning in the first place? If I get it right, users have to add `-fsycl-embed-ir` flag when compile for NVIDIA or AMD targets, but it's not required for SPIR targets. Can we consider embedding IR by default to make user experience unified across all targets?
> 
> @mdtoguchi, FYI.

Hey, too add on to this: I did some limited testing on a machine with a CUDA device, and the tests seem to pass with or without the compile flag. I was unsure whether I should have removed it, but I went through with making it optional instead because of [this mention](https://github.com/intel/llvm/blob/sycl/sycl/doc/design/CompilerAndRuntimeDesign.md?plain=1#L784-L791) in the docs.

**Comment by bader** [comment]
> > @intel/dpcpp-kernel-fusion-reviewers, this change makes me wonder: why do we report a warning in the first place? If I get it right, users have to add `-fsycl-embed-ir` flag when compile for NVIDIA or AMD targets, but it's not required for SPIR targets. Can we consider embedding IR by default to make user experience unified across all targets?
> > @mdtoguchi, FYI.
> 
> Hey, too add on to this: I did some limited testing on a machine with a CUDA device, and the tests seem to pass with or without the compile flag. I was unsure whether I should have removed it, but I went through with making it optional instead because of [this mention](https://github.com/intel/llvm/blob/sycl/sycl/doc/design/CompilerAndRuntimeDesign.md?plain=1#L784-L791) in the docs.

I hope @intel/dpcpp-kernel-fusion-reviewers team can say which tests require this option and where we can drop it.

**Review by victor-eds — APPROVED** [review]

**Comment by sommerlukas** [comment]
> @intel/dpcpp-kernel-fusion-reviewers, this change makes me wonder: why do we report a warning in the first place? If I get it right, users have to add `-fsycl-embed-ir` flag when compile for NVIDIA or AMD targets, but it's not required for SPIR targets. Can we consider embedding IR by default to make user experience unified across all targets?

Embedding the IR by default would have a notable impact on binary size, which is particularly relevant for libraries. As the kernel fusion feature is only an experimental feature, we therefore decided against embedding by default.

Generally, I would assume that the tests that specify the flag also need it, but we will investigate the details. 

An alternative approach to this PR would be to make sure that the warning isn't printed in the clang frontend. This would not only result in the tests not printing it anymore, but would fix the warning for all users.

**Comment by sommerlukas** [comment]
> Generally, I would assume that the tests that specify the flag also need it, but we will investigate the details.

I investigated this, on my machine, 25 tests failed for the CUDA backend when the embed IR flag was not correctly defined.

However, I used the opportunity to improve some of the tests and drop the flag from some tests that don't require it: https://github.com/intel/llvm/pull/14366

**Pull request merged**
