### PR TITLE
[NFC] Update driver tests to not require clang-driver

### PR DESCRIPTION
**Pull request by mdtoguchi**
The REQUIRES: clang-driver setting in the SYCL driver tests is
no longer valid.  Remove this check as it was causing these tests
to not be supported and not run.

### CODE REVIEW

**Review by hchilama — APPROVED** [review]

**Comment by mdtoguchi** [comment]
@intel/llvm-gatekeepers, this is ready for merge.

**Comment by pvchupin** [comment]
@mdtoguchi, there is post-commit fail on windows: https://github.com/intel/llvm/actions/runs/2314201910
```
Clang :: Driver/sycl-intelfpga-static-lib-win.cpp
```

Can you take a look?

**Comment by bader** [comment]
> Not sure why pre-commit wouldn't catch this.

AFAIK, pre-commit doesn't run checks on Windows platform.

**Comment by mdtoguchi** [comment]
test update here: https://github.com/intel/llvm/pull/6147

**Comment by pvchupin** [comment]
Thanks Mike for quick turnaround!

**Pull request merged**
