### PR TITLE
[SYCL][libdevice] Provide fadd/fsub/dadd/dsub with rounding mode support

### PR DESCRIPTION
**Pull request by jinge90**

### CODE REVIEW

**Review by akolesov-intel — APPROVED** [review]
Looks good to me, thank you!

**Comment by jinge90** [comment]
Hi, @intel/dpcpp-tools-reviewers and @intel/llvm-reviewers-runtime 
Could you help review this patch?
Thanks very much.

**Review by AlexeySachkov — APPROVED** [review]
`sycl-post-link` changes LGTM

**Comment by jinge90** [comment]
Hi, @intel/llvm-reviewers-runtime 
Kind ping~

**Review by xtian-github — APPROVED** [review]
LGTM

**Review by bso-intel — APPROVED** [review]

**Comment by asudarsa** [comment]
Hi @jinge90 

Can you please comment on the test failures?

Thanks

**Comment by jinge90** [comment]
> Hi @jinge90
> 
> Can you please comment on the test failures?
> 
> Thanks

The error message is: "Err: Build failed with Error: hudson.AbortException: script returned exit code 255"
It looks like to be an infra issue. Let me trigger pre-ci again.

**Comment by steffenlarsen** [comment]
@jinge90 - There are RHEL-related failures that need to be addressed. I will ping you offline with more information.

**Comment by jinge90** [comment]
Hi, @steffenlarsen 
The failure has been fixed, thanks very much.

**Pull request merged**
