### PR TITLE
[SYCL] Use correct macro for `fabs`

### PR DESCRIPTION
**Pull request by JackAKirk**
`fabs` does not have a native math variant, therefore it is currently defined using the wrong macro that attempts to use a native variants in fast-math mode. This PR corrects this.

### CODE REVIEW

**Comment by jinz2014** [comment]
Did you find the issue after some compiler error ?

**Comment by JackAKirk** [comment]
> Did you find the issue after some compiler error ?

This was the reported problem that this PR fixes:

```
clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda Basic/built-ins/marray_math.cpp -o m -ffast-mat
h
clang++: warning: CUDA version is newer than the latest partially supported version 11.8 [-Wunknown-cuda-version]
Basic/built-ins/marray_math.cpp:94:8: error: no matching function for call to 'fabs'
  TEST(sycl::fabs, float, 3, EXPECTED(float, 180, 180, 180), 0, ma5);
       ^~~~~~~~~~
Basic/built-ins/marray_math.cpp:20:55: note: expanded from macro 'TEST'
            sycl::marray<MARRAY_ELEM_TYPE, DIM> res = FUNC(__VA_ARGS__);       \
                                                      ^~~~
/home/nicolas/oneapi/llvm/build/bin/../include/sycl/builtins.hpp:126:34: note: candidate template ignored: requirement 'std::is_same_v<float, double> || std::is_same_v<float, sycl::detail::half_impl::half>' was not satisfied [with T = float, N = 3]
__SYCL_MATH_FUNCTION_OVERLOAD_FM(fabs)
                                 ^
/home/nicolas/oneapi/llvm/build/bin/../include/sycl/builtins.hpp:451:57: note: candidate template ignored: requirement 'detail::is_contained<sycl::marray<float, 3>, sycl::detail::type_list<sycl::detail::type_list<sycl::detail::type_list<float>, sycl::detail::type_list<double>, sycl::detail::type_list<sycl::detail::half_impl::half>>, sycl::detail::type_list<sycl::detail::type_list<sycl::vec<float, 1>, sycl::vec<float, 2>, sycl::vec<float, 3>, sycl::vec<float, 4>, sycl::vec<float, 8>, sycl::vec<float, 16>>, sycl::detail::type_list<sycl::vec<double, 1>, sycl::vec<double, 2>, sycl::vec<double, 3>, sycl::vec<double, 4>, sycl::vec<double, 8>, sycl::vec<double, 16>>, sycl::detail::type_list<sycl::vec<sycl::detail::half_impl::half, 1>, sycl::vec<sycl::detail::half_impl::half, 2>, sycl::vec<sycl::detail::half_impl::half, 3>, sycl::vec<sycl::detail::half_impl::half, 4>, sycl::vec<sycl::detail::half_impl::half, 8>, sycl::vec<sycl::detail::half_impl::half, 16>>>>>::value' was not satisfied [with T = sycl::marray<float, 3>]
detail::enable_if_t<detail::is_svgenfloat<T>::value, T> fabs(T x) __NOEXC {
                                                        ^
1 error generated.

```

**Review by dm-vodopyanov — APPROVED** [review]
@JackAKirk thanks for finding this!

**Comment by dm-vodopyanov** [comment]
```
SYCL Pre Commit / Linux / Stop AWS (pull_request_target)
```
Submitted https://github.com/intel/llvm/issues/9393

**Pull request merged**
