### PR TITLE
[SYCL] Move implementation details under sycl_private namespace

### PR DESCRIPTION
**Pull request by alexbatashev**
ABI tests require a way to differentiate private and publicly accessible
symbols. Wrap symbols that are not be accessible from user application
in sycl_private namespace to exclude them from ABI checks.

Signed-off-by: Alexander Batashev <alexander.batashev@intel.com>

### CODE REVIEW

**Comment by bader** [comment]
What is "private symbol"?
How can I decide which symbol is private?

**Comment by alexbatashev** [comment]
> What is "private symbol"?
> How can I decide which symbol is private?

Does it sound better now?

**Comment by bader** [comment]
We have "detail" namespace for "implementation details".
How can I decide which symbol should be "sycl_private" namespace and which symbol in "detail"?

**Comment by alexbatashev** [comment]
> We have "detail" namespace for "implementation details".
> How can I decide which symbol should be "sycl_private" namespace and which symbol in "detail"?

`detail` is used for many things across the project. It hides both host- and device-side implementation details, and user application still link againts those symbols. `sycl_private` only wraps the contents of `source` directory: those symbols can not be accessed from user applications, because the declarations are unknown.

**Comment by bader** [comment]
What is wrong with anonymous namespace?
Can we use it to hide symbols?

**Comment by bader** [comment]
> `sycl_private` only wraps the contents of `source` directory: those symbols can not be accessed from user applications, because the declarations are unknown.

I see `sycl_private` uses in SYCL headers. Is this intentional?

**Comment by alexbatashev** [comment]
> > `sycl_private` only wraps the contents of `source` directory: those symbols can not be accessed from user applications, because the declarations are unknown.
> 
> I see `sycl_private` uses in SYCL headers. Is this intentional?

Yes, we still need to keep pointers to impl object. To fill in template arguments I needed forward declarations of classes. But pointers and forward declarations are not linkable symbols, so, those are not really "uses". And we still have a differentiation between accessible and inaccessible pieces of code.

**Comment by bader** [comment]
> What is wrong with anonymous namespace?
> Can we use it to hide symbols?

@alexbatashev, could you answer these questions, please?

**Comment by alexbatashev** [comment]
> > What is wrong with anonymous namespace?
> > Can we use it to hide symbols?
> 
> @alexbatashev, could you answer these questions, please?

I doubt I can reliably filter out everything that is inside cl::sycl::detail::(anonymous) namespace, but I’ll experiment a bit more with that.

**Comment by alexbatashev** [comment]
> What is wrong with anonymous namespace?
> Can we use it to hide symbols?

@bader while I can reliably detect anonymous namespaces on Linux, Windows is a bit trickier. But that's not the main problem. The main problem is that anonymous namespace implies internal linkage. And it breaks our tests:
```
In file included from /repos/sycl_private/sycl/unittests/scheduler/MemObjCommandCleanup.cpp:10:
/repos/sycl_private/sycl/unittests/scheduler/SchedulerTestUtils.hpp:76:6: error: function 'addEdge' is used but not defined in this translation unit, and cannot be defined in any other translation unit because its type does not have linkage
```

Can we keep `sycl_private`?

**Pull request closed without merging**
