### PR TITLE
[SYCL][NFC] Add explicit numbers to the architecture targets

### PR DESCRIPTION
**Pull request by dm-vodopyanov**
This is to prevent future possible discrepancies after removing some of the architecture targets from enum.

### CODE REVIEW

**Comment by al42and** [comment]
Will this table soon get messy?

```cpp
  x86_64 = 0,
  aarch64 = 61,
  ...
  intel_gpu_pvc = 21,
  intel_gpu_dg3 = 58,
  // NVIDIA architectures
  nvidia_gpu_sm_50 = 22,
  ....
  nvidia_gpu_sm_90 = 35,
  nvidia_gpu_sm_90a = 59,
  // AMD architectures
  amd_gpu_gfx700 = 36,
  ...
  amd_gpu_gfx1034 = 57,
  amd_gpu_gfx1100 = 60,
```

It's all an implementation detail, but it would not be easy to maintain. Maybe adding a vendor-specific "prefix" would make it more maintainable:


```cpp
  x86_64 = 0,
  //aarch64 = 1,
  intel_gpu_bdw = 10001,
  // NVIDIA architectures
  nvidia_gpu_sm_50 = 20001,
  // AMD architectures
  amd_gpu_gfx700 = 30001,
```

**Comment by dm-vodopyanov** [comment]
@al42and thanks for the suggestion!

**Comment by dm-vodopyanov** [comment]
@bso-intel ping.

Tagging @gmlueck , what do you think about these improvement? I can also update the spec accordingly.

**Comment by gmlueck** [comment]
> Tagging @gmlueck , what do you think about this improvement? I can also update the spec accordingly.

I don't think the spec should list the specific numerical values for the enumerators.  Instead, the spec can say something like:

> The `architecture` enumerators with the prefix `nvidia_gpu` are ordered according to their associated CUDA architecture level.  For example `nvidia_gpu_sm_90` has a numerical value greater than `nvidia_gpu_sm_89`, etc.

I'm not sure yet about the exact wording for the AMD or Intel GPU enums.  Do we have a specific use case for comparing the order of these?

**Comment by dm-vodopyanov** [comment]
Proper solution was already developed, closing

**Pull request closed without merging**
