### PR TITLE
[SYCL][FPGA] Disallow 'force_pow2_depth' attribute argument > 1

### PR DESCRIPTION
**Pull request by smanna12**
[[intel::force_pow2_depth()]] attribute only accepts integer constant value 0 or 1.

This patch uses correct diagnostic to show the memory attribute behavior.

### CODE REVIEW

**Review by elizabethandrews — APPROVED** [review]

**Comment by smanna12** [comment]
Thank you @elizabethandrews for reviews.

**Comment by smanna12** [comment]
The failure is unrelated to my patch.

@intel/llvm-gatekeepers, This PR is ready to be merged. Thank you

**Comment by smanna12** [comment]
@intel/llvm-gatekeepers Can we get this merged? Thanks!

**Comment by aelovikov-intel** [comment]
> @intel/llvm-gatekeepers Can we get this merged? Thanks!

No. AMD HIP testing seems to be broken and someone needs to take care of it.

**Comment by smanna12** [comment]
https://github.com/orgs/intel/teams/llvm-gatekeepers, All Checks have passed. Can we get this merged? Thanks!

**Pull request merged**
