### PR TITLE
[CI] Skip lint job when disable-lint is set 

### PR DESCRIPTION
**Pull request by jsji**
When we add `ignore-lint` label, CI will still run lint and show a failure despite we will ignore it and continue to do further tests.
Since we don't care about lint result, we should ignore running it to avoid wasting machine resource or causing confusion about check results.

### CODE REVIEW

**Review by aelovikov-intel — DISMISSED** [review]

**Comment by aelovikov-intel** [comment]
@bader , FYI.

**Comment by bader** [comment]
"ignore-lint" description says "Ignore linter failures and proceed with build jobs". It was added with intention to run linter checks but don't block other checks if linter job fails.

We must update description. I would also rename the label to "disable-lint" to make it less confusing.

**Comment by jsji** [comment]
Thanks @aelovikov-intel and @bader . :)

**Review by aelovikov-intel — APPROVED** [review]

**Comment by jsji** [comment]
@intel/llvm-gatekeepers Can we get this merged. This only changed CI file, the failure in lit test and e2e test are irrelevant. Thanks.

**Comment by steffenlarsen** [comment]
L0 Arc Timed Out Tests (1):
  SYCL :: Matrix/XMX8/element_wise_all_sizes.cpp - Reported in https://github.com/intel/llvm/issues/11912.

**Pull request merged**
