### PR TITLE
[SYCL] Fix error: too few template arguments for class template 'instance'

### PR DESCRIPTION
**Pull request by denis-kabanov**
Add default argument for class template 'instance' to prevent errors associated with the loss of the arguments at compile time.

### CODE REVIEW

**Comment by denis-kabanov** [comment]
@GarveyJoe Can you please tell what is the minimum acceptable value for sycl::ext::intel::buffer_location<value>?

**Comment by MrSidims** [comment]
According to https://software.intel.com/content/www/us/en/develop/download/oneapi-fpga-optimization-guide.html (section A8, table 37) buffer location index starts at 0 .

**Comment by denis-kabanov** [comment]
@smaslov-intel Can you please review this code?

**Review by mohammadfawaz — APPROVED** [review]
LGTM!

**Comment by denis-kabanov** [comment]
@intel/llvm-reviewers-runtime  Can someone review this code?

**Review by smaslov-intel — APPROVED** [review]
LGTM

**Pull request merged**
