### PR TITLE
[SYCL] Disallow explicit casts between mismatching address spaces

### PR DESCRIPTION
**Pull request by Fznamznon**

### CODE REVIEW

**Comment by bader** [comment]
Can we commit this patch to llorg?

**Comment by Fznamznon** [comment]
> Can we commit this patch to llorg?

Yes, we can. Will do that after tests pass. Thanks for pointing this out.

**Comment by premanandrao** [comment]
> > Can we commit this patch to llorg?
> 
> Yes, we can. Will do that after tests pass. Thanks for pointing this out.

Changes look good to me!

**Comment by Fznamznon** [comment]
Moved to llorg https://reviews.llvm.org/D118935

**Pull request closed without merging**
