### PR TITLE
[WIP][SYCL] Align stream handling with other classes

### PR DESCRIPTION
**Pull request by Fznamznon**
This change simplifies FE handling of stream class and makes it
identical to handling of accessor and sampler classes. Stream class is not
handled as wrapper struct for several accessors anymore and initialized
within __init method instead.

This is part of job about adding an attribute to annotate special sycl types
and unifying handling of sycl classes by FE. See https://github.com/intel/llvm/pull/2091#discussion_r461743627
for the full idea.

### CODE REVIEW

**Comment by bader** [comment]
@Fznamznon, what is plan for this PR? Are you going to commit this change?

**Comment by Fznamznon** [comment]
> @Fznamznon, what is plan for this PR? Are you going to commit this change?

I'm going to finish it once I have a chance to work on it.

**Review by erichkeane — COMMENTED** [review]
This seems about right to me... What is currently not working?

**Comment by Fznamznon** [comment]
> This seems about right to me... What is currently not working?

This one is pretty old and needs rebase. I guess @zahiraam just decided to create a new PR for it.

**Comment by Fznamznon** [comment]
Closing this PR in favor of https://github.com/intel/llvm/pull/3646

**Pull request closed without merging**
