### PR TITLE
[SYCL][E2E] XFAIL launch_policy_lmem.cpp on Arc

### PR DESCRIPTION
**Pull request by sarnex**
It's failing with the new driver (not yet merged, will merge after this PR is merged)

https://github.com/intel/llvm/issues/14974

### CODE REVIEW

**Comment by sarnex** [comment]
@intel/syclcompat-lib-reviewers FYI, thanks :)

**Comment by sarnex** [comment]
@intel/syclcompat-lib-reviewers Ping on this one? Thanks

**Comment by aelovikov-intel** [comment]
@Alcpz @joeatodd @OuadiElfarouki ping X3, this has been ignored by syclcompat team for days!

**Review by aelovikov-intel — APPROVED** [review]

**Review by joeatodd — APPROVED** [review]

**Comment by sarnex** [comment]
@joeatodd Thank you!

**Pull request merged**
