### PR TITLE
[ESIMD] Let ESIMD attributes not depend on -fsycl-explicit-simd

### PR DESCRIPTION
**Pull request by DenisBakhvalov**
This is one of the final patches to support mixing SYCL and ESIMD kernels.
In the end, we want to get rid of `-fsycl-explicit-simd` option and unify the two modes: regular SYCL and ESIMD.
This patch eliminates one of the dependencies on the `-fsycl-explicit-simd` flag, allowing to use ESIMD attributes without it.

### CODE REVIEW

**Comment by AaronBallman** [comment]
I'd appreciate a bit more information about why the change is being made (added to the PR description so it goes into the commit message).

Are no tests impacted by this change? We should add test coverage to show this is explicitly supported.

**Comment by DenisBakhvalov** [comment]
https://github.com/intel/llvm-test-suite/pull/195

> I'd appreciate a bit more information about why the change is being made (added to the PR description so it goes into the commit message).
> 
> Are no tests impacted by this change? We should add test coverage to show this is explicitly supported.

Yes, sorry, will do. I just wanted to check the ESIMD on-GPU tests in the llvm-test-suite. I believe converting to draft will stop the CI, right?

**Comment by AaronBallman** [comment]
> > I'd appreciate a bit more information about why the change is being made (added to the PR description so it goes into the commit message).
> > Are no tests impacted by this change? We should add test coverage to show this is explicitly supported.
> 
> Yes, sorry, will do. I just wanted to check the ESIMD on-GPU tests in the llvm-test-suite. I believe converting to draft will stop the CI, right?

Good question! I *think* converting to a draft still runs the CI pipeline but I'm not 100% sure.

**Comment by DenisBakhvalov** [comment]
> Denis, can you please update the docs too - the ESIMD intro and spec.

I will. Is it OK if I update the docs in a separate patch once all the changes regarding SYCL-ESIMD coexistence will be done?

**Comment by kbobrovs** [comment]
> > Denis, can you please update the docs too - the ESIMD intro and spec.
> 
> I will. Is it OK if I update the docs in a separate patch once all the changes regarding SYCL-ESIMD coexistence will be done?

Yes, that should be Ok

**Review by AaronBallman — APPROVED** [review]
LGTM!

**Pull request merged**
