### PR TITLE
[GHA] Uplift Linux GPU RT version to 23.30.26918.9

### PR DESCRIPTION
**Pull request by bb-sycl**
Scheduled drivers uplift

### CODE REVIEW

**Comment by aelovikov-intel** [comment]
> [cperkinsintel](https://github.com/cperkinsintel) requested a review from [aelovikov-intel](https://github.com/aelovikov-intel) [43 minutes ago](https://github.com/intel/llvm/pull/11302#event-10488758011)

@cperkinsintel , do you know if someone was assigned to look into the failures?

**Comment by sarnex** [comment]
@aelovikov-intel Me, @bader and @AlexeySachkov are looking at them

**Comment by AlexeySachkov** [comment]
After doing first round of fixes for obvious problems, here are some observations about remaining failures:

`assert` does not work in ESIMD. The test was previously skipped, because it checked if driver version is new enough. Now it runs, but `assert` doesn't fire. Not sure how it was tested before that, because expected assertion message does not match what we have in non-ESIMD tests. Since the test was disabled, this is not a regression and should likely be investigated separately. Commit which added the test (545a043ebaf52976b4a3c7bf35e2ea637428c505) is only a month old and it is a commit which claims to add support for `assert` to ESIMD, so that is just a new feature, which haven't yet been properly tested/bugfixed. @sarnex, @v-klochkov: FYI

`assert` doesn't work on OpenCL backend. This is more concerning, because this _is_ a regression. That is more concerning and I don't think that we should merge such a driver update until we understand the root cause at least or submit an IGC/NEO issue. I will spend some more time looking into this, any suggestion are welcome here.

**Review by sarnex — APPROVED** [review]
esimd test change lgtm, please make an internal bug tracker for us too.

let me know if you need any help with investigation

**Comment by AlexeySachkov** [comment]
A new fail here: 
```
FAIL: SYCL :: Graph/Explicit/buffer_ordering.cpp (791 of 1715)
******************** TEST 'SYCL :: Graph/Explicit/buffer_ordering.cpp' FAILED ********************
Exit Code: -6

Command Output (stdout):
--
# RUN: at line 2
/__w/llvm/llvm/toolchain/bin//clang++   -fsycl -fsycl-targets=spir64 /__w/llvm/llvm/llvm/sycl/test-e2e/Graph/Explicit/buffer_ordering.cpp -o /__w/llvm/llvm/build-e2e/Graph/Explicit/Output/buffer_ordering.cpp.tmp.out
# executed command: /__w/llvm/llvm/toolchain/bin//clang++ -fsycl -fsycl-targets=spir64 /__w/llvm/llvm/llvm/sycl/test-e2e/Graph/Explicit/buffer_ordering.cpp -o /__w/llvm/llvm/build-e2e/Graph/Explicit/Output/buffer_ordering.cpp.tmp.out
# note: command had no output on stdout or stderr
# RUN: at line 3
env ONEAPI_DEVICE_SELECTOR=ext_oneapi_level_zero:gpu  /__w/llvm/llvm/build-e2e/Graph/Explicit/Output/buffer_ordering.cpp.tmp.out
# executed command: env ONEAPI_DEVICE_SELECTOR=ext_oneapi_level_zero:gpu /__w/llvm/llvm/build-e2e/Graph/Explicit/Output/buffer_ordering.cpp.tmp.out
# note: command had no output on stdout or stderr
# RUN: at line 5
env ZE_DEBUG=4 env ONEAPI_DEVICE_SELECTOR=ext_oneapi_level_zero:gpu  /__w/llvm/llvm/build-e2e/Graph/Explicit/Output/buffer_ordering.cpp.tmp.out 2>&1 | /__w/llvm/llvm/toolchain/bin/FileCheck /__w/llvm/llvm/llvm/sycl/test-e2e/Graph/Explicit/buffer_ordering.cpp
# executed command: env ZE_DEBUG=4 env ONEAPI_DEVICE_SELECTOR=ext_oneapi_level_zero:gpu /__w/llvm/llvm/build-e2e/Graph/Explicit/Output/buffer_ordering.cpp.tmp.out
# note: command had no output on stdout or stderr
# error: command failed with exit status: -6
# executed command: /__w/llvm/llvm/toolchain/bin/FileCheck /__w/llvm/llvm/llvm/sycl/test-e2e/Graph/Explicit/buffer_ordering.cpp
# note: command had no output on stdout or stderr

--
```

Does it look like something we have seen already? I couldn't find any trackers. Tagging @julianmi for awareness.

Besides this issue I think the PR is almost ready to go. I plan to create a tracker for OpenCL GPU `assert` regression to reference it from tests next to `XFAIL`

**Review by julianmi — APPROVED** [review]
LGTM. We will continue investigating this issue since we see multiple buffer-related sporadic failures.

**Comment by AlexeySachkov** [comment]
@aelovikov-intel, @intel/llvm-reviewers-runtime, @intel/dpcpp-devops-reviewers, could you please take a look?

I've fixed everything I could quickly fix, submitted issues for everything which requires further analysis and disabled corresponding tests. I also expect that assert-related (non-ESIMD) failures will be automatically fixed with the upcoming driver updates.

**Review by aelovikov-intel — APPROVED** [review]

**Comment by aelovikov-intel** [comment]
Post-commit (https://github.com/intel/llvm/actions/runs/6382366634) resulted in a few `XPASS`es (we treat them as `UNSUPPORTED` in pre-commit to save time in running multiple targets at once). @intel/dpcpp-esimd-reviewers , can you follow up please? I'd expect we need to drop the `XFAIL` markup or somehow limit its conditions.

**Comment by AlexeySachkov** [comment]
@aelovikov-intel, it looks like that particular post-commit was still running on an older version of the GPU driver. Looking at a few most recent post-commits, the issue with those two `XFAIL`-ed tests does not reproduce in there.

**Comment by aelovikov-intel** [comment]
> @aelovikov-intel, it looks like that particular post-commit was still running on an older version of the GPU driver. Looking at a few most recent post-commits, the issue with those two `XFAIL`-ed tests does not reproduce in there.

Are you saying that we have a regression in the newer version of the GPU driver? Tagging @intel/dpcpp-esimd-reviewers .

**Comment by AlexeySachkov** [comment]
> > @aelovikov-intel, it looks like that particular post-commit was still running on an older version of the GPU driver. Looking at a few most recent post-commits, the issue with those two `XFAIL`-ed tests does not reproduce in there.
> 
> Are you saying that we have a regression in the newer version of the GPU driver? Tagging @intel/dpcpp-esimd-reviewers .

Hard to say. The thing is that both ESIMD tests were "disabled" by a driver version check inside them and 23.30 is a first public driver which is good enough for them to run on. However, both tests still fail with that driver. Even if it is a regression, it is a regression between whichever internal version was used to locally verify those tests when adding the check and 23.30. Or it is not even a regression at all if no one had verified those tests when inserting those checks.

Those tests `XPASS`-ed in that single post-commit run, because there were effectively skipped due to driver version check, i.e. the post-commit was still using old driver where those tests passed from LIT point of view, but they didn't check anything.

**Pull request merged**
