### PR TITLE
[NFC][SYCL]Remove unused function parameter.

### PR DESCRIPTION
**Pull request by srividya-sundaram**

### CODE REVIEW

**Review by smanna12 — APPROVED** [review]

**Review by premanandrao — APPROVED** [review]
Thanks!

**Comment by srividya-sundaram** [comment]
@intel/llvm-gatekeepers This is ready to be merged. Thanks!

**Comment by pvchupin** [comment]
@srividya-sundaram, please open issue for the unrelated fail.

**Comment by srividya-sundaram** [comment]
> SYCL / Linux / L0 GEN9 LLVM Test Suite (pull_request_target)

I have file https://github.com/intel/llvm/issues/7222 to track this issue.

**Pull request merged**
