### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW10 2024)

### PR DESCRIPTION
**Pull request by sys-ce-bb**
LLVM: llvm/llvm-project@ac74d9ec0f73898713dd6e0d33f148c13a51875d
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@3df5e38250a6d7c50b58fbb0393be81d909487ff

### CODE REVIEW

**Comment by jsji** [comment]
@bader @intel/llvm-gatekeepers This is ready for merge. No review required. Thanks.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Thu 07 Mar 2024 04:50:19 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Thu 07 Mar 2024 04:59:59 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
