### PR TITLE
[libclc] Reorganize libspirv library

### PR DESCRIPTION
**Pull request by frasercrmck**
This moves the libspirv libraries to their own subdirectory of libclc, reflecting how the CLC library is organized, and how the OpenCL library may be reorganized in the future.

The libspirv bindings are organized in a similar way to CLC, with a single root directory and then a 'generic' directory containing the target-agnostic implementations, as well as top-level target-specific subdirectories to override specific builtins.

The libspirv bindings still do a lot of the CLC implementations so the separation isn't as clean as it needs to be, but this patch should help to keep our downstream modifications better separated from upstream changes.

Headers that were previously 'spirv' have now been renamed to 'libspirv' to reflect this, and to better distinguish them from the 'spirv' and 'spirv64' libclc targets. That accounts for a majority of the churn.

Using llvm-diff shows no change to either OpenCL/libspirv bitcode library on nvidia targets.

### CODE REVIEW

**Comment by frasercrmck** [comment]
@sarnex Not sure who to ping, but are you by any chance able to help make sense of what the ProtexIP job is unhappy about?

**Comment by sarnex** [comment]
i think it just sucks, let me restart it

**Comment by frasercrmck** [comment]
> i think it just sucks, let me restart it

Thanks! It still failed though. I wonder if it's got a problem with some license headers in libclc? I haven't added these files, though - just moved them. I'm not sure what I can do about that - the job output isn't very clear.

**Comment by sarnex** [comment]
ok yeah i dont totally understand it either, but if you can say for sure there's no new code in this PR and its just mvoed around, imo we can ignore it

**Comment by frasercrmck** [comment]
> ok yeah i dont totally understand it either, but if you can say for sure there's no new code in this PR and its just mvoed around, imo we can ignore it

Oh, I see - it seems that `git` isn't able to see that I moved [rotate.inc](https://github.com/intel/llvm/blob/sycl/libclc/generic/libspirv/integer/rotate.inc) to [rotate.inc](https://github.com/intel/llvm/pull/16283/files#diff-2f8f86bad36b27bec00ba6c66348e474861f399331d9bbbec0f871225861a02d). It's treating it as a new file, which might be tripping this check.

Same with `gen_core_convert.py` ([here](https://github.com/intel/llvm/blob/sycl/libclc/generic/libspirv/gen_core_convert.py) -> [here](https://github.com/intel/llvm/pull/16283/files#diff-f749bfbd5bc0e7f3856cba28d2ad2770cf5546661da784fba90cc8dc8e76a7c6)).

I think those are the only two it's complaining about?

Speculating, but it could be that the copyright headers are different between our copies of those files, and upstream's. For `rotate.inc` I see we've added an LLVM Apache License header at some point in the past. For `gen_core_convert.py` the best I can assume is that upstream has another contributor listed in the header? But then the comparison seems to be against llvm 8, and that contributor wasn't listed back then. I dunno.

Maybe it's best to ignore it - this PR hasn't added anything new in that regard.

**Comment by sarnex** [comment]
if youre just moving files i would ignore it

**Review by jchlanda — APPROVED** [review]
This is a large diff, so I'm assuming that the bulk of the change is coming from `libclc/generic/libspirv` -> `libclc/libspirv/lib/generic` layout change and the include adjustment. I like that dir reshuffle, it describes the responsibilities of each component better.

**Comment by frasercrmck** [comment]
@intel/llvm-gatekeepers please merge, thank you. The CI failure is to be ignored (see discussion above)

**Comment by steffenlarsen** [comment]
Jenkins/Precommit job looks infrastructural. Merging...

**Pull request merged**
