### PR TITLE
[SYCL] Fix host device local accessor alignment

### PR DESCRIPTION
**Pull request by npmiller**
Local kernel arguments must be aligned to the type size, simply using `std::vector<char>` doesn't always provide the correct alignment. So this patch adds extra padding to the vector and ensures that the pointer returned for the accessor is actually aligned to the type size.

This issue was exposed by: https://github.com/intel/llvm-test-suite/pull/608, which was a follow up to fixing local accessor alignment for the CUDA plugin.

### CODE REVIEW

**Comment by smaslov-intel** [comment]
> However this patch is breaking ABI (and currently fails the ABI tests), so some feedback on whether this is acceptable of it there is another way to approach it which wouldn't break ABI would be appreciated.

I don't see how an alignment could be forced without changing the ABI, and the ABI breaking change is not allowed until major update.  @intel/llvm-reviewers-runtime , any idea?

**Comment by romanovvlad** [comment]
>> I don't see how an alignment could be forced without changing the ABI, and the ABI breaking change is not allowed until major update. https://github.com/orgs/intel/teams/llvm-reviewers-runtime , any idea?

Can we modify `LocalAccessorImplHost:LocalAccessorImplHost` to allocate more memory(`+ElemSize`) and modify `LocalAccessorBaseHost::getPtr` to adjust the pointer so it's aligned enough for `ElemSize`?

**Comment by npmiller** [comment]
Good shout @romanovvlad , updated as suggested, so it should now fix the alignment without breaking the ABI.

Not exactly related to this patch but I'm a little confused about the `void* getPtr() const` overloads, were these meant to be `const void* getPtr()` instead? There are two of them, one that I modified here and one in another class, and both are/were doing a `const_cast<void *>` on `char*` which doesn't change the constness.

**Comment by npmiller** [comment]
ping @smaslov-intel @romanovvlad

**Review by alexbatashev — APPROVED** [review]

**Comment by bader** [comment]
@npmiller, could you update the PR description, so I can use it as a commit message, please?

**Pull request merged**
