### PR TITLE
[SYCL] Improve sycl-post-link performance with -split=kernel

### PR DESCRIPTION
**Pull request by sarnex**
Right now we are computing a new callgraph in every call to extractCallGraph. extractCallGraph is called every time we do a module split, so for -split=kernel, that would be once per kernel. For modules with many kernels, this can take a very long time. We only need to compute this once because the input IR doesn't seem to change between splits.

This improves performance of sycl-post-link from ~45min to ~7min for an example with 13k kernels

Signed-off-by: Sarnie, Nick <nick.sarnie@intel.com>

### CODE REVIEW

**Comment by asudarsa** [comment]
Hi @kbobrovs, can you please take a look? Thanks.

**Comment by asudarsa** [comment]
It will be great if we can add a test here. Not sure if we have any existing test that track 'compile time'.

**Review by AlexeySachkov — APPROVED** [review]

**Comment by AlexeySachkov** [comment]
> It will be great if we can add a test here. Not sure if we have any existing test that track 'compile time'.

I suppose that this is a non-functional change, which shouldn't require a test. I also doubt that we will be able to write proper 'compile time' test, or at least it should go into a separate suite of performance tests. The problem is that such tests can't be launched in a regular environment or they will be prone to fluctuations caused by many factors, like: having more than one test launched in parallel, having a misconfigured machine which uses tubro boost or operates on a non-fixed CPU frequency, etc.

**Comment by sarnex** [comment]
I agree with Alexey, it would be very difficult to write a unit test that isn't super flaky. I'll reach out @asudarsa offline to see if I can connect with some quality engineers to discuss

**Review by kbobrovs — APPROVED** [review]
Thanks, good catch!

**Comment by AlexeySachkov** [comment]
CUDA testing seems to fail due to infra issues, but since this patch is effectively a non-functional change, I will go ahead and merge it

**Comment by sarnex** [comment]
Thanks! @AlexeySachkov

**Pull request merged**
