### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW52)

### PR DESCRIPTION
**Pull request by sys-ce-bb**
LLVM: llvm/llvm-project@bc8c4bbd7973ab9527a78a20000aecde9bed652d
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@e63fdb8

### CODE REVIEW

**Comment by jsji** [comment]
This is ready for review.
- [ ] [[SYCL] Fix maybe-uninitialized warning](https://github.com/intel/llvm/pull/12255/commits/5c5358ffa7bb61241926039d4531e71f97c00a80) A simple fix to avoid maybe-uninitialized warning  @intel/dpcpp-cfe-reviewers

**Comment by bader** [comment]
> This is ready for review.
> 
> * [ ]  [[SYCL] Fix maybe-uninitialized warning](https://github.com/intel/llvm/pull/12255/commits/5c5358ffa7bb61241926039d4531e71f97c00a80) A simple fix to avoid maybe-uninitialized warning  @intel/dpcpp-cfe-reviewers

@jsji, https://github.com/intel/llvm/pull/12255/commits/5c5358ffa7bb61241926039d4531e71f97c00a80 changes SYCL runtime, so you should tag @intel/llvm-reviewers-runtime team.
BTW, SYCL runtime is not upstreamed, so I'm surprised that this issue is exposed by LLVM pulldown. Do you know what's going on?

**Comment by jsji** [comment]
> > This is ready for review.
> > 
> > * [ ]   [[SYCL] Fix maybe-uninitialized warning](https://github.com/intel/llvm/pull/12255/commits/5c5358ffa7bb61241926039d4531e71f97c00a80) A simple fix to avoid maybe-uninitialized warning  @intel/dpcpp-cfe-reviewers
> 
> @jsji, [5c5358f](https://github.com/intel/llvm/commit/5c5358ffa7bb61241926039d4531e71f97c00a80) changes SYCL runtime, so you should tag @intel/llvm-reviewers-runtime team. BTW, SYCL runtime is not upstreamed, so I'm surprised that this issue is exposed by LLVM pulldown. Do you know what's going on?

I don't know either. Note that his is NOT exposed in our GitHub Action CI, it was exposed in the RHEL build. 
There are only 2 sycl commits, not touching this file,  the code itself was there for a long time, but this is a valid warning. 
So what I can guess is this might be exposed due to some build env change, eg: we got dispatched to some server that has slightly different build compiler??

**Comment by bader** [comment]
> > > This is ready for review.
> > > 
> > > * [ ]    [[SYCL] Fix maybe-uninitialized warning](https://github.com/intel/llvm/pull/12255/commits/5c5358ffa7bb61241926039d4531e71f97c00a80) A simple fix to avoid maybe-uninitialized warning  @intel/dpcpp-cfe-reviewers
> > 
> > 
> > @jsji, [5c5358f](https://github.com/intel/llvm/commit/5c5358ffa7bb61241926039d4531e71f97c00a80) changes SYCL runtime, so you should tag @intel/llvm-reviewers-runtime team. BTW, SYCL runtime is not upstreamed, so I'm surprised that this issue is exposed by LLVM pulldown. Do you know what's going on?
> 
> I don't know either. Note that this is NOT exposed in our GitHub Action CI, it was exposed in the RHEL build. There are only 2 sycl commits, not touching this file, the code itself was there for a long time, but this is a valid warning. So what I can guess is this might be exposed due to some build env change, eg: we got dispatched to some server that has slightly different build compiler??

I see. CI behavior is strange, but I suggest we make https://github.com/intel/llvm/commit/5c5358ffa7bb61241926039d4531e71f97c00a80 change in a separate PR. 
The failure is not caused by LLVM pulldown, so we are making unrelated change.

**Comment by jsji** [comment]
> > > > This is ready for review.
> > > > 
> > > > * [ ]     [[SYCL] Fix maybe-uninitialized warning](https://github.com/intel/llvm/pull/12255/commits/5c5358ffa7bb61241926039d4531e71f97c00a80) A simple fix to avoid maybe-uninitialized warning  @intel/dpcpp-cfe-reviewers
> > > 
> > > 
> > > @jsji, [5c5358f](https://github.com/intel/llvm/commit/5c5358ffa7bb61241926039d4531e71f97c00a80) changes SYCL runtime, so you should tag @intel/llvm-reviewers-runtime team. BTW, SYCL runtime is not upstreamed, so I'm surprised that this issue is exposed by LLVM pulldown. Do you know what's going on?
> > 
> > 
> > I don't know either. Note that this is NOT exposed in our GitHub Action CI, it was exposed in the RHEL build. There are only 2 sycl commits, not touching this file, the code itself was there for a long time, but this is a valid warning. So what I can guess is this might be exposed due to some build env change, eg: we got dispatched to some server that has slightly different build compiler??
> 
> I see. CI behavior is strange, but I suggest we make [5c5358f](https://github.com/intel/llvm/commit/5c5358ffa7bb61241926039d4531e71f97c00a80) change in a separate PR. The failure is not caused by LLVM pulldown, so we are making unrelated change.

Oh, had another look. This should be due to https://github.com/llvm/llvm-project/commit/898320d4e52c9110422a31a8afc896b9d211ed9d, so this is exposed by pulldown.

**Comment by jsji** [comment]
https://github.com/intel/llvm/pull/12260 created for [5c5358f](https://github.com/intel/llvm/commit/5c5358ffa7bb61241926039d4531e71f97c00a80).

We can review follow up there, but I will keep it here, or else if we merge this before https://github.com/intel/llvm/pull/12260, our RHEL CI would be broken.

**Comment by jsji** [comment]
@againull approved https://github.com/intel/llvm/pull/12260, so I remove the fix from this pulldown.

@bader @intel/llvm-gatekeepers This does NOT require review anymore, but  we should merge this *AFTER* https://github.com/intel/llvm/pull/12260.

**Comment by bader** [comment]
The build passes even without https://github.com/intel/llvm/commit/5c5358ffa7bb61241926039d4531e71f97c00a80. 😕 
Good to merge anyway.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Fri 29 Dec 2023 02:22:46 AM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Fri 29 Dec 2023 02:27:08 AM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Comment by jsji** [comment]
> The build passes even without [5c5358f](https://github.com/intel/llvm/commit/5c5358ffa7bb61241926039d4531e71f97c00a80). 😕 Good to merge anyway.

The build passed because it already picked up the fix in #12260.

```
19:49:19  [2023-12-29 00:49:19,469] merge INFO: === stage merge start ===
19:49:19  [2023-12-29 00:49:19,469] merge INFO: top_branch_value is 367166cd3a8a315b178a68ba1ac7000de36cde98

$ git show 367166cd3a8a
commit 367166cd3a8a315b178a68ba1ac7000de36cde98
Author: Jinsong Ji [jinsong.ji@intel.com](mailto:jinsong.ji@intel.com)
Date:   Thu Dec 28 16:12:10 2023 -0800

    [SYCL] Fix maybe-uninitialized warning (#12260)
```

**Comment by bader** [comment]
> > The build passes even without [5c5358f](https://github.com/intel/llvm/commit/5c5358ffa7bb61241926039d4531e71f97c00a80). 😕 Good to merge anyway.
> 
> The build passed because it already picked up the fix in #12260.
> 
> ```
> 19:49:19  [2023-12-29 00:49:19,469] merge INFO: === stage merge start ===
> 19:49:19  [2023-12-29 00:49:19,469] merge INFO: top_branch_value is 367166cd3a8a315b178a68ba1ac7000de36cde98
> 
> $ git show 367166cd3a8a
> commit 367166cd3a8a315b178a68ba1ac7000de36cde98
> Author: Jinsong Ji [jinsong.ji@intel.com](mailto:jinsong.ji@intel.com)
> Date:   Thu Dec 28 16:12:10 2023 -0800
> 
>     [SYCL] Fix maybe-uninitialized warning (#12260)
> ```

Pre-commit has started before #12260 was merged. It looks like some build job started after #12260 was merged and it pulled most recent commits from the SYCL branch. I expected pre-commit to use the same SYCL branch commit for all build configuration for consistent results. That's why I was confused. I can imagine a situation when Linux and Windows builds will use different commits from the SYCL branch and generate inconsistent pre-commit reports.
To be honest, I'm not sure if this is a bug or a feature. Sounds like using independent commits for each configuration might be beneficial (like in this case).
@intel/dpcpp-devops-reviewers, FYI.

**Comment by jsji** [comment]
> > > The build passes even without [5c5358f](https://github.com/intel/llvm/commit/5c5358ffa7bb61241926039d4531e71f97c00a80). 😕 Good to merge anyway.
> > 
> > 
> > The build passed because it already picked up the fix in #12260.
> > ```
> > 19:49:19  [2023-12-29 00:49:19,469] merge INFO: === stage merge start ===
> > 19:49:19  [2023-12-29 00:49:19,469] merge INFO: top_branch_value is 367166cd3a8a315b178a68ba1ac7000de36cde98
> > 
> > $ git show 367166cd3a8a
> > commit 367166cd3a8a315b178a68ba1ac7000de36cde98
> > Author: Jinsong Ji [[jinsong.ji@intel.com](mailto:jinsong.ji@intel.com)](mailto:[jinsong.ji@intel.com](mailto:jinsong.ji@intel.com))
> > Date:   Thu Dec 28 16:12:10 2023 -0800
> > 
> >     [SYCL] Fix maybe-uninitialized warning (#12260)
> > ```
> 
> Pre-commit has started before #12260 was merged. It looks like some build job started after #12260 was merged and it pulled most recent commits from the SYCL branch. I expected pre-commit to use the same SYCL branch commit for all build configuration for consistent results. That's why I was confused. I can imagine a situation when Linux and Windows builds will use different commits from the SYCL branch and generate inconsistent pre-commit reports. To be honest, I'm not sure if this is a bug or a feature. Sounds like using independent commits for each configuration might be beneficial (like in this case). @intel/dpcpp-devops-reviewers, FYI.

Yes, it would be great if all the jobs triggered by the same commit/PR use the same `top_branch_value`. 
But since this involve two CI systems, we might need to figure out ways to pass the `top_branch_value`. 
FYI. @DoyleLi

**Pull request merged**
