### PR TITLE
[SYCL][Opaque pointer] Remove no opaque CodeGenSYCL tests

### PR DESCRIPTION
**Pull request by jsji**
We have finally switched the default to opaque pointer for SPIRV , so everything should be opaque pointer now.
Most of these no-opaque* test have corresponding opaque pointer test, so I think we can remove them safely.

### CODE REVIEW

**Review by elizabethandrews — APPROVED** [review]
I think this looks ok but I would like @premanandrao to approve as well. 

Also is the flag -opaque-pointers/-no-opaque-pointer present in community clang? If it's something we added, should we remove it as well?

**Comment by premanandrao** [comment]
> I think this looks ok but I would like @premanandrao to approve as well.
> 
> Also is the flag -opaque-pointers/-no-opaque-pointer present in community clang? If it's something we added, should we remove it as well?

I just want to make sure we have an opaque version of the test for all the non-opaque ones that we are removing.

**Comment by jsji** [comment]
> I just want to make sure we have an opaque version of the test for all the non-opaque ones that we are removing.

Only annotations-field.cpp is missing.

[jinsongj@scsel-clx-20 llvm]$ cat op.list|xargs ls
ls: cannot access 'clang/test/CodeGenSYCL/annotations-field.cpp': No such file or directory
clang/test/CodeGenSYCL/accessor_inheritance.cpp                 clang/test/CodeGenSYCL/image_accessor.cpp                     clang/test/CodeGenSYCL/max-concurrency.cpp
clang/test/CodeGenSYCL/add_ir_annotations_member.cpp            clang/test/CodeGenSYCL/inheritance.cpp                        clang/test/CodeGenSYCL/noexcept.cpp
clang/test/CodeGenSYCL/add_ir_annotations_member_filter.cpp     clang/test/CodeGenSYCL/inline_asm.cpp                         clang/test/CodeGenSYCL/non-standard-layout.cpp
clang/test/CodeGenSYCL/add_ir_annotations_member_reuse.cpp      clang/test/CodeGenSYCL/intel-fpga-ivdep-array.cpp             clang/test/CodeGenSYCL/nontrivial_device_copyable.cpp
clang/test/CodeGenSYCL/add_ir_attributes_kernel_parameter.cpp   clang/test/CodeGenSYCL/intel-fpga-ivdep-embedded-loops.cpp    clang/test/CodeGenSYCL/pointers-in-structs.cpp
clang/test/CodeGenSYCL/address-space-builtin-alloca.cpp         clang/test/CodeGenSYCL/intel-fpga-ivdep-global.cpp            clang/test/CodeGenSYCL/regcall-cc-test.cpp
clang/test/CodeGenSYCL/address-space-cond-op.cpp                clang/test/CodeGenSYCL/intel-fpga-local.cpp                   clang/test/CodeGenSYCL/sampler.cpp
clang/test/CodeGenSYCL/address-space-new.cpp                    clang/test/CodeGenSYCL/intel-fpga-mem-builtin.cpp             clang/test/CodeGenSYCL/spir-calling-conv.cpp
clang/test/CodeGenSYCL/address-space-of-returns.cpp             clang/test/CodeGenSYCL/intel-fpga-mem-builtin.cpp             clang/test/CodeGenSYCL/spir-enum.cpp
clang/test/CodeGenSYCL/address-space-parameter-conversions.cpp  clang/test/CodeGenSYCL/intel-fpga-reg.cpp                     clang/test/CodeGenSYCL/stall_enable_device.cpp
clang/test/CodeGenSYCL/basic-kernel-wrapper.cpp                 clang/test/CodeGenSYCL/intel-restrict.cpp                     clang/test/CodeGenSYCL/stream.cpp
clang/test/CodeGenSYCL/check-direct-attribute-propagation.cpp   clang/test/CodeGenSYCL/intel-sycl-ptr-annotation-builtin.cpp  clang/test/CodeGenSYCL/sycl-device-alias.cpp
clang/test/CodeGenSYCL/const-wg-init.cpp                        clang/test/CodeGenSYCL/invoke-function-addrspace.cpp          clang/test/CodeGenSYCL/sycl-host-intelfpga-bitint.cpp
clang/test/CodeGenSYCL/device-functions.cpp                     clang/test/CodeGenSYCL/kernel-arg-accessor-pointer.cpp        clang/test/CodeGenSYCL/sycl-intelfpga-bitint.cpp
clang/test/CodeGenSYCL/device_global.cpp                        clang/test/CodeGenSYCL/kernel_binding_decls.cpp               clang/test/CodeGenSYCL/sycl-intelfpga-field.cpp
clang/test/CodeGenSYCL/device-variables.cpp                     clang/test/CodeGenSYCL/kernel-device-space-arg.cpp            clang/test/CodeGenSYCL/union-kernel-param.cpp
clang/test/CodeGenSYCL/esimd-accessor-ptr-md.cpp                clang/test/CodeGenSYCL/kernel-handler.cpp                     clang/test/CodeGenSYCL/unique-stable-id.cpp
clang/test/CodeGenSYCL/esimd-private-global.cpp                 clang/test/CodeGenSYCL/kernel-param-acc-array.cpp             clang/test/CodeGenSYCL/virtual-types.cpp
clang/test/CodeGenSYCL/fpga_pipes.cpp                           clang/test/CodeGenSYCL/kernel-param-member-acc-array.cpp      clang/test/CodeGenSYCL/wg_init.cpp
clang/test/CodeGenSYCL/generated-types-initialization.cpp       clang/test/CodeGenSYCL/kernel-param-pod-array.cpp

**Comment by jsji** [comment]
@premanandrao All files removed have corresponding opaque pointer ones. Can you have a look again. Thanks.

**Comment by jsji** [comment]
> Also is the flag -opaque-pointers/-no-opaque-pointer present in community clang? If it's something we added, should we remove it as well?

Community clang has removed these options `-opaque-pointers/-no-opaque-pointer`. We will remove them later after we  Enable INTEL_SYCL_OPAQUEPOINTER_READY , a draft PR contains are here https://github.com/intel/llvm/pull/10888

**Comment by jsji** [comment]
@premanandrao  Ping.. Can you have a quick look again? Thanks.

**Comment by dm-vodopyanov** [comment]
@jsji please follow https://github.com/intel/llvm/blob/sycl/sycl/doc/developer/ContributeToDPCPP.md#commit-message

**Comment by jsji** [comment]
> @jsji please follow https://github.com/intel/llvm/blob/sycl/sycl/doc/developer/ContributeToDPCPP.md#commit-message

Thanks @dm-vodopyanov for reminding. Updated the title, let me know if more changes needed. Thanks.

**Comment by jsji** [comment]
Looks like @premanandrao is Out of office.
I have already addressed his comments.
Are we OK to get this merged? @elizabethandrews  @intel/llvm-gatekeepers

**Review by premanandrao — APPROVED** [review]

**Comment by jsji** [comment]
Thanks @premanandrao ! @intel/llvm-gatekeepers  Can we get this merged? Thanks!

**Pull request merged**
