### PR TITLE
[NFC] Reflow files in buildbot and sycl-fusion dirs

### PR DESCRIPTION
**Pull request by jchlanda**
Run `black` on python files in buildbot and fusion directories. Those files skipped the original formatting effort, so any change to them now would cause a formatting CI job to fail.

### CODE REVIEW

**Comment by jchlanda** [comment]
We've discussed it here: https://github.com/intel/llvm/pull/14762#issuecomment-2250766686

**Review by sommerlukas — APPROVED** [review]
Changes to kernel fusion LIT config LGTM.

**Review by aelovikov-intel — APPROVED** [review]

**Comment by joeatodd** [comment]
I don't think you really need/want syclcompat-lib-reviewers here?

**Comment by jchlanda** [comment]
@intel/llvm-gatekeepers now that the jobs are green I believe this could go in. Thank you.

**Pull request merged**
