### PR TITLE
[UR] Handle INVALID_VALUE in OCL urPlatformGet

### PR DESCRIPTION
**Pull request by RossBrunton**
Pre-commit MR for: https://github.com/oneapi-src/unified-runtime/pull/2227

As there is a spec change in UR, adapter handling code has been updated -
it no longer tries to populate the platform list if it would be empty
(otherwise both "destination" pointers could be null, which is now
illegal).

This fixes a bug Intel tracks internally as URT-831

### CODE REVIEW

**Comment by aarongreig** [comment]
@intel/llvm-reviewers-runtime please take a look when you can

**Review by aarongreig — APPROVED** [review]

**Comment by aarongreig** [comment]
@intel/llvm-reviewers-runtime please review, it's a trivial change which is blocking our merge queue now

**Review by maarquitos14 — APPROVED** [review]
LGTM.

**Comment by aarongreig** [comment]
@intel/llvm-gatekeepers please merge

**Pull request merged**
