### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW40)

### PR DESCRIPTION
**Pull request by vmaksimo**
LLVM: llvm/llvm-project@eb9f7c28e5fe
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@a88d869

### CODE REVIEW

**Comment by vmaksimo** [comment]
Regression_VEC_GPU_WIN was the only failed step in Jenkins/Summary due to some internal Jenkins error related to node creation. I've restarted this step and it has passed: http://icl-jenkins.sc.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FWin%2FVEC_GPU/detail/VEC_GPU/1448/pipeline
PR is ready to be merged then.

**Review by AlexeySotkin — APPROVED** [review]
SPIRV-LLVM-Translator part looks good to me.

**Pull request merged**
