### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW32)

### PR DESCRIPTION
**Pull request by jsji**
LLVM: llvm/llvm-project@920c461
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@bb2196b

### CODE REVIEW

**Comment by jsji** [comment]
https://github.com/intel/llvm/actions/runs/5826836915/job/15801649641?pr=10783 is failing due to node.js issue.

Run actions/checkout@v3
/usr/bin/docker exec  e05ff825a445ab354db6790a985446c70fad1e147532b0abde6ce255093f77[18](https://github.com/intel/llvm/actions/runs/5826836915/job/15801649641?pr=10783#step:4:19) sh -c "cat /etc/*release | grep ^ID"
/__e/node16/bin/node[6]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xb0a860 node::Abort() [/__e/node16/bin/node]
 2: 0xb0a8de  [/__e/node16/bin/node]
 3: 0xb7a11e  [/__e/node16/bin/node]
 4: 0xb7a1e6 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/__e/node16/bin/node]
 5: 0xacd05e node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/__e/node16/bin/node]
 6: 0xace3a9 node::Start(int, char**) [/__e/node16/bin/node]
 7: 0x7f18e1635d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7f18e1635e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0xa4067c  [/__e/node16/bin/node]

**Comment by jsji** [comment]
- [ ] A few more guarding of typed pointer removal code with INTEL_SYCL_OPAQUEPOINTER_READY . These are due to the nature that we haven't enabled INTEL_SYCL_OPAQUEPOINTER_READY yet, we will need to remove them later after we enable INTEL_SYCL_OPAQUEPOINTER_READY or even delete this macro.
- [ ]  [Fix Driver test due to return code change](https://github.com/intel/llvm/pull/10783/commits/aef58ce9ae09fc3a8c20e5409a0b1de3203ca00d) needs review from @intel/dpcpp-clang-driver-reviewers 
- [ ]  [Add -opaque-pointers=1 for failing tests](https://github.com/intel/llvm/pull/10783/commits/c02d2ff101befaf683446d10fd0c98a7f21e9183) and [Fix merge in group-instructions.ll](https://github.com/intel/llvm/pull/10783/commits/6414c5f20806d2d09fc96a93408093bf3da90144) needs review from @intel/dpcpp-spirv-reviewers 
- [ ] [Update spirv-to-ir-wrapper.ll to use opaque pointer](https://github.com/intel/llvm/pull/10783/commits/4ba783b2d5e5f1556bf61641351ebd1c1cc94e26) is a simpler version to get it pass, there will be a updated version by @tylanphear to update whole IR to opaque pointer after merge. 
- [ ] [Update vtable-align-address-space.cpp](https://github.com/intel/llvm/pull/10783/commits/2e69a4076c023134a8bfd128f878f3a5c127271b) needs review from @intel/dpcpp-cfe-reviewers 
- [ ] [XFAIL two SPIRV tests](https://github.com/intel/llvm/pull/10783/commits/32bb25b8849e3fe0c186fa7e03d17892c5db21f5) needs **follow up**.  

1. There is ongoing work for relanding the entry point support for llvm-spirv/test/extensions/INTEL/SPV_INTEL_function_pointers/alias.ll by @Fznamznon  
2. [llvm-spirv/test/image.ll assertion after pulldown](https://github.com/intel/llvm/issues/10817) 

- [ ] [Revert "AMDGPU: Move placement of RemoveIncompatibleFunctions"](https://github.com/intel/llvm/pull/10783/commits/dce52b456701e4fe6ba55c36571c4be34558fd9b) needs **follow up**.
* [SYCL passes depends on AMDGPU Remove Incompatible Functions unexpectedly](https://github.com/intel/llvm/issues/10816)

**Comment by Fznamznon** [comment]
> There is ongoing work for relanding the entry point support for llvm-spirv/test/extensions/INTEL/SPV_INTEL_function_pointers/alias.ll by @Fznamznon

I'm not aware of that, did you mean to ping someone else?

**Comment by jsji** [comment]
> > There is ongoing work for relanding the entry point support for llvm-spirv/test/extensions/INTEL/SPV_INTEL_function_pointers/alias.ll by @Fznamznon
> 
> I'm not aware of that, did you mean to ping someone else?

Oops, sorry, tagged wrong id.  I meant the work @vmaksimo

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Wed 16 Aug 2023 09:52:20 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Wed 16 Aug 2023 09:57:02 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
