### PR TITLE
[SYCL][Bindless] Fix bindless vulkan interop tests selecting wrong vulkan device

### PR DESCRIPTION
**Pull request by DBDuncan**
The incorrect vulkan device can be selected when both Intel and Nvidia devices are available on the same system. Change tests to use the same device as SYCL default to.

### CODE REVIEW

**Comment by DBDuncan** [comment]
@wenju-he Hey Wenju. Added this fix to the vulkan tests to prevent the wrong vulkan device being selected. Can you test this using the Level Zero backend. Want to make sure that there is no weirdness with the sycl and vulkan devices having slightly different naming causing issues when using an Intel device.

**Comment by wenju-he** [comment]
> @wenju-he Hey Wenju. Added this fix to the vulkan tests to prevent the wrong vulkan device being selected. Can you test this using the Level Zero backend.

@DBDuncan the change LGTM. I've tested it on DG2 linux. There is device name mismatch due to lower/upper case difference:
`dev.get_info<sycl::info::device::name>()` returns `Intel(R) Arc(TM) A770 Graphics`, while vkGetPhysicalDeviceProperties props.deviceName are:
`Intel(R) Arc(tm) A770 Graphics (DG2)`
`llvmpipe (LLVM 15.0.7, 256 bits)`
So it is probably necessary to do case insensitive compare. Then 4 subtests in sampled_images.cpp are passing on DG2 linux, same as before this PR.

**Comment by DBDuncan** [comment]
@wenju-he Dang. TBH thought something annoying like that might happen. Thankfully yeah making the comparison case insensitive should fix the issue. Pushed a patch. Please verify that it works.

**Comment by wenju-he** [comment]
@DBDuncan it is working now, following is log of sampled_images.cpp (only 4 subtests are enabled):
```
Found suitable Vulkan device: Intel(R) Arc(tm) A770 Graphics (DG2)
All tests passed!
```

**Review by wenju-he — APPROVED** [review]
LGTM

**Review by isaacault — APPROVED** [review]

**Review by cppchedy — APPROVED** [review]

**Comment by DBDuncan** [comment]
@intel/llvm-gatekeepers Should be ready to merge.

**Comment by ph0b** [comment]
@DBDuncan @wenju-he a mismatch could also happen with two Intel dGPUs.
Implementations should use `ext::intel::info::device::uuid` and `VkPhysicalDeviceIDProperties::deviceUUID` as https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_external_memory_capabilities.html proposes.
(and for DX12, it'd be with LUID)

**Comment by DBDuncan** [comment]
> @DBDuncan @wenju-he a mismatch could also happen with two Intel dGPUs. Implementations should use `ext::intel::info::device::uuid` and `VkPhysicalDeviceIDProperties::deviceUUID` as https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_external_memory_capabilities.html proposes. (and for DX12, it'd be with LUID)

Thanks for letting me know. The test is currently disabled running on intel devices so should not be an issue for now. I don't think CI has the updated drivers yet? I could be wrong. At least should prevent vulkan picking an intel device when sycl is using an nvidia device for now.

**Comment by ph0b** [comment]
Sure it makes the test pass now but it's fundamentally not the correct approach. if one day we add CI instances with 2x nvidia GPUs it could break.
Using UUID is what applications will do so it's also relevant to have this done by the tests, in case UUID comparison would break for any reason.

**Comment by DBDuncan** [comment]
Yeah, you are right. I should had also been a lot more pessimistic about constant naming of devices between vulkan and sycl in the first place. I will look at updating this on Monday. Not working this Friday.

**Comment by wenju-he** [comment]
> > @DBDuncan @wenju-he a mismatch could also happen with two Intel dGPUs. Implementations should use `ext::intel::info::device::uuid` and `VkPhysicalDeviceIDProperties::deviceUUID` as https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_external_memory_capabilities.html proposes. (and for DX12, it'd be with LUID)
> 
> Thanks for letting me know. The test is currently disabled running on intel devices so should not be an issue for now. I don't think CI has the updated drivers yet? I could be wrong. At least should prevent vulkan picking an intel device when sycl is using an nvidia device for now.

@DBDuncan you're right that CI isn't enabled for bindless tests because drivers are not ready. SPIRV-LLVM-Translator commit used in latest IGC release [igc-1.0.16900.23](https://github.com/intel/intel-graphics-compiler/releases/tag/igc-1.0.16900.23) doesn't contains llvm-spirv support for bindless image. Fortunately latest tag [igc-1.0.17193.3](https://github.com/intel/intel-graphics-compiler/releases/tag/igc-1.0.17193.3) has the llvm-spirv commit for bindless image, so we just need to wait for the next IGC release.

@ph0b thanks for the comment. I can test following-up PR from @DBDuncan on DG2.

**Pull request merged**
