### PR TITLE
[SYCL] Diagnose error in L0 for linker options

### PR DESCRIPTION
**Pull request by gmlueck**
The Level Zero driver does not support any way to pass options that
are specific to the online linker, so diagnose an error if the
application attempts to pass any.  Previously, any such options were
silently ignored.

Note that the Level Zero driver does support online _compiler_
options, and the plugin correctly handles these.

There is a test case for this PR in intel/llvm-test-suite#713

### CODE REVIEW

**Comment by gmlueck** [comment]
This PR is retargeted and rebased now that #5267 is merged.

I expect that the following two E2E tests will fail until intel/llvm-test-suite#713 is merged:

* SYCL/DeprecatedFeatures/get-options.cpp
* SYCL/DeprecatedFeatures/program_link.cpp

**Comment by bader** [comment]
> I expect that the following two E2E tests will fail until [intel/llvm-test-suite#713](https://github.com/intel/llvm-test-suite/pull/713) is merged:
> 
> * SYCL/DeprecatedFeatures/get-options.cpp
> * SYCL/DeprecatedFeatures/program_link.cpp

CI system is able to test if you expectation holds.

@gmlueck, you can validate that updated DPC++ runtime passes updated tests by adding following comment `/verify with <link to PR to test with>`.
You can leave such a comment either in this PR (e.g. `/verify with https://github.com/intel/llvm-test-suite/pull/713`) or in https://github.com/intel/llvm-test-suite/pull/713 (e.g. `/verify with https://github.com/intel/llvm/pull/5268`).

**Comment by gmlueck** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/713

**Comment by gmlueck** [comment]
> you can validate that updated DPC++ runtime passes updated tests by adding following comment /verify with <link to PR to test with>.

@bader: thanks for this tip, but I must be doing something wrong.  I added a comment like this, but testing does not seem to be re-triggered.  What did I do wrong?

**Comment by bader** [comment]
> > you can validate that updated DPC++ runtime passes updated tests by adding following comment /verify with .
> 
> @bader: thanks for this tip, but I must be doing something wrong. I added a comment like this, but testing does not seem to be re-triggered. What did I do wrong?

This comment doesn't re-trigger Jenkins/Precommit, it triggers a new job Jenkins/llvm-test-suite. I see that SYCL/DeprecatedFeatures/get-options.cpp and SYCL/DeprecatedFeatures/program_link.cpp pass, but SYCL :: Reduction/reduction_usm.cpp failed. Tagging @v-klochkov for awareness.

**Comment by gmlueck** [comment]
@smaslov-intel : can you review?  I have analyzed the failing CI tests, and I think they should not prevent merge:

The "Jenkins/Pre-ci-logs" and "Jenkins/Precommit" failures are expected:

* DeprecatedFeatures/get-options.cpp
* DeprecatedFeatures/program_link.cpp

Both of these tests were modified in intel/llvm-test-suite#713, and they will pass once that PR is merged.  I verified this with the `/verify` command in this PR, and you can see that the run of "Jenkins/llvm-test-suite" passed.

The failure in "SYCL / Default Linux / HIP AMD GPU Test Suite" is unrelated to this PR:

* SubGroup/broadcast.cpp
* SubGroup/broadcast_fp16.cpp
* SubGroup/broadcast_fp64.cpp

As evidence, you can see that these same three tests also failed in #4937.

**Review by smaslov-intel — APPROVED** [review]

**Comment by gmlueck** [comment]
@againull: Thanks for merging!  Note that intel/llvm-test-suite#713 also needs to be merged, otherwise the E2E test suite will fail.

**Comment by againull** [comment]
> @againull: Thanks for merging! Note that [intel/llvm-test-suite#713](https://github.com/intel/llvm-test-suite/pull/713) also needs to be merged, otherwise the E2E test suite will fail.

Got it, thank you, merged test as well because 2 PRs were successfully tested together here.

**Pull request merged**
