### PR TITLE
[CI] Add IGC dev as new dependency

### PR DESCRIPTION
**Pull request by jsji**
This is the 1st PR in prepare of enabling dev IGC test for some of the
SYCL tests.

Ref: https://github.com/intel/llvm/pull/11552

Tested https://github.com/intel/llvm/actions/runs/8461815185/job/23182202059

### CODE REVIEW

**Review by cperkinsintel — APPROVED** [review]

**Comment by jsji** [comment]
Thanks @cperkinsintel . @intel/llvm-gatekeepers  Can you please merge this? Thanks.

**Comment by aelovikov-intel** [comment]
@jsji , https://github.com/intel/llvm/actions/runs/8485593107 has failed after this. Is that expected?

**Comment by jsji** [comment]
> @jsji , https://github.com/intel/llvm/actions/runs/8485593107 has failed after this. Is that expected?

[Base Ubuntu 22.04 Docker image](https://github.com/intel/llvm/actions/runs/8485593107/job/23250649681#step:3:1574)
buildx failed with: ERROR: denied: installation not allowed to Write organization package

I think it is more related to the permission change , just exposed by this?

**Comment by aelovikov-intel** [comment]
> I think it is more related to the permission change in https://github.com/intel/llvm/pull/13173, just exposed by this? This change hasn't touched any of the docker image build yet.

+ @stdale-intel

**Comment by jsji** [comment]
> * @stdale-intel

@stdale-intel https://github.com/intel/llvm/pull/13173/files#diff-93e4ff9c5dcc4dfae5e351c7217e250a2f31e0622e4ca77f0926eba1dceaaadfR24 I think we should allow write in `sycl-container.yaml` as we are doing `push` after image update.

**Comment by jsji** [comment]
> > * @stdale-intel
> 
> @stdale-intel https://github.com/intel/llvm/pull/13173/files#diff-93e4ff9c5dcc4dfae5e351c7217e250a2f31e0622e4ca77f0926eba1dceaaadfR24 I think we should allow write in `sycl-container.yaml` as we are doing `push` after image update.

https://github.com/intel/llvm/pull/13245 Posted to fix the permission issue.

**Comment by stdale-intel** [comment]
@jsji  thank you, I was working on a PR to fix this and a few other permissions errors that came up after the change. Thanks for doing this one, i'll remove it from my changes.

**Pull request merged**
