### PR TITLE
[SYCL] Add generic impl for bf16 fabs

### PR DESCRIPTION
**Pull request by jinge90**
Signed-off-by: jinge90 <ge.jin@intel.com>

### CODE REVIEW

**Comment by JackAKirk** [comment]
Can you test this with e.g. a llvm-test-suite PR removing the cuda requirement from this test https://github.com/intel/llvm-test-suite/blob/intel/SYCL/BFloat16/bfloat16_builtins.cpp targetting this PR?

**Comment by JackAKirk** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1495

**Comment by jinge90** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1495

**Comment by bader** [comment]
@jinge90, please, merge with the head of the `sycl` branch to pull the fix for CI scripts. There was a bug, which hang the validation on NVIDIA GPU.

**Comment by jinge90** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1495

**Review by JackAKirk — APPROVED** [review]
LGTM

**Comment by jinge90** [comment]
Hi, @intel/llvm-reviewers-runtime and @cperkinsintel 
Could you help review this PR?
Thanks very much.

**Review by steffenlarsen — APPROVED** [review]
LGTM!

**Pull request merged**
