### PR TITLE
[DO NOT MERGE] PR to trigger CI

### PR DESCRIPTION
**Pull request by uditagarwal97**

### CODE REVIEW

**Comment by uditagarwal97** [comment]
@bader I think we need to update windows_test_comment_trigger workflow as well. Currently, I'm getting the following error:
```
Error when evaluating 'strategy' for job 'build'. intel/llvm/.github/workflows/sycl_windows_build_and_test.yml@19d023b1601f115be13dd54b125e9fd473ef21d2 (Line: 28, Col: 9): Matrix must define at least one vector
```
Should we also run the test_matrix job in windows_test_comment_trigger workflow (similar to SYCL postcommit workflow)?

**Comment by bader** [comment]
In my opinion, it would be very useful. We have 4 Windows machines, and they should be able to handle both post-commit and pre-commit by request.

**Comment by bader** [comment]
> Should we also run the test_matrix job in windows_test_comment_trigger workflow (similar to SYCL postcommit workflow)?

/testwin must work anyway regardless of the decision on running e2e tests.

**Pull request closed without merging**
