### PR TITLE
[SYCL] Add `(raw|decorated)_generic_ptr` aliases

### PR DESCRIPTION
**Pull request by victor-eds**
https://github.com/KhronosGroup/SYCL-Docs/pull/598 adds these aliases to the spec. Prepare for spec change by adding them to the implementation beforehand.

Extend tests so all `multi_ptr` aliases are checked.

### CODE REVIEW

**Review by gmlueck — APPROVED** [review]

**Review by aelovikov-intel — APPROVED** [review]

**Comment by aelovikov-intel** [comment]
This will have a minor conflict with https://github.com/intel/llvm/pull/15402 (see FIXME in the test there). I assume we're waiting for the Khronos PR to be merged in before merging this one.

**Comment by victor-eds** [comment]
@intel/llvm-gatekeepers can we get this merged?

**Comment by KornevNikita** [comment]
@victor-eds hi! Do you plan to update SYCL-CTS to turn it on on DPCPP? If so, could you please share a link to PR then?

**Comment by victor-eds** [comment]
> @victor-eds hi! Do you plan to update SYCL-CTS to turn it on on DPCPP? If so, could you please share a link to PR then?

Yes! I have that in my backlog :smile:

**Comment by victor-eds** [comment]
> @victor-eds hi! Do you plan to update SYCL-CTS to turn it on on DPCPP? If so, could you please share a link to PR then?

https://github.com/KhronosGroup/SYCL-CTS/pull/988

**Pull request merged**
