### PR TITLE
[SYCL] WIP On kernel_args_restrict (Sema Changes)

### PR DESCRIPTION
**Pull request by erichkeane**
Sema changes to allow kernel_args_restrict on the lambda kernels.

@asavonic : Please take a look and add the codegen changes that you want out of this.

### CODE REVIEW

**Comment by asavonic** [comment]
That seems a lot easier than I thought it would be. Thanks Erich.
So we attach an attribute to a lambda function declaration instead of a type, right?

**Comment by erichkeane** [comment]
We assign it to the lambda call operator declaration, yes.  The solution is a little hacky and likely not totally standards compliant, but until there is infrastructure to do this correctly in Clang I think this is what we can do.

I'm going to discuss with Aaron Ballman next time I see him to see what we can do to improve this, but at the moment this should be enough to unblock you.

**Comment by keryell** [comment]
We really need to push a correct way to express `restrict`-ions in C++23...

**Comment by neoskypig** [comment]
I saw the attribute name is "intelfpga", do we need to change it to a common name and cover more devices?

**Comment by MrSidims** [comment]
@erichkeane @asavonic I think, the work on this is finished, please correct me otherwise.

**Pull request closed without merging**
