### PR TITLE
[UR] Bump UR tag to f31160d

### PR DESCRIPTION
**Pull request by pbalcer**
Includes a few small fixes:
https://github.com/oneapi-src/unified-runtime/pull/2083
https://github.com/oneapi-src/unified-runtime/pull/2080
https://github.com/oneapi-src/unified-runtime/pull/2072

### CODE REVIEW

**Comment by omarahmed1111** [comment]
@pbalcer This PR was merged: https://github.com/intel/llvm/pull/14954 . Which made a conflict here for UR tag. This PR should be good to go once the UR tag conflict is resolved.

**Comment by pbalcer** [comment]
@omarahmed1111 thanks, updated.

**Comment by pbalcer** [comment]
the only e2e failure is:
```
********************
Unexpectedly Passed Tests (1):
  SYCL :: OneapiDeviceSelector/no_duplicate_devices.cpp
```
which is unrelated and was already fixed in https://github.com/intel/llvm/pull/15337.

@omarahmed1111 can you please review?

**Review by omarahmed1111 — APPROVED** [review]

**Comment by pbalcer** [comment]
@intel/llvm-gatekeepers please merge

**Pull request merged**
