### PR TITLE
[SYCL] Proxy DLL Loader for Windows

### PR DESCRIPTION
**Pull request by cperkinsintel**
DLLs manually loaded by SYCL are not tracked as direct dependencies in the same way that linked DLLs are. This means these DLL may be unloaded before SYCLs shutdown() routine is called, which will lead to problems when that routine tries to call those DLL to release resources.  This PR adds a new proxy DLL that is a linked dependency of SYCL itself. This proxy DLL loads all the SYCL manually loaded DLLs early, before SYCL itself is loaded, and conversely, they are not unloaded until the proxy itself unloads, which is after SYCL unloads. So now the manually loaded plugin DLLs will be resident when shutdown() is called and piTearDown can complete safely and successfully.

Signed-off-by: Chris Perkins <chris.perkins@intel.com>

### CODE REVIEW

**Comment by cperkinsintel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1465

**Comment by cperkinsintel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1465

**Comment by cperkinsintel** [comment]
The fixes that have been merged for the unified runtime now fix the testing problems I was encountering.  test suite is passing on Windows. Ready for review.

**Comment by KseniyaTikhomirova** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1465

**Comment by cperkinsintel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1465

**Comment by cperkinsintel** [comment]
The hip failure is due to a missing aspect::fp16 check. It is being added here: https://github.com/intel/llvm-test-suite/pull/1487

**Comment by romanovvlad** [comment]
It seems that the patch causing HostInteropTask/host-task-failure.cpp to hang.

**Comment by cperkinsintel** [comment]
@romanovvlad  - I can't reproduce the failure for HostInteropTask/host-task-failure.cpp (yet), but I *do* see the XPTI tests all failing.  I've been investigating that, not sure what's going on. It seems the collector.dlls that are output aren't then loading. Not sure if it's a problem in the loading or their production.

**Comment by cperkinsintel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1465

**Comment by cperkinsintel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1465

**Comment by cperkinsintel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1518

**Comment by cperkinsintel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1465

**Comment by cperkinsintel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1465

**Comment by cperkinsintel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1465

**Comment by cperkinsintel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1465

**Comment by cperkinsintel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1465

**Comment by cperkinsintel** [comment]
The basics of this PR were straightforward, but it was encountering a lot of test failures and it turns out the root cause of that is a difference seen on Windows in how threads may be terminated. This is a separate issue that is now better understood and I'm addressing. But this PR got twisted up chasing that problem. Because this PR never really made it out of draft, I'm closing it. The final work is a new PR which is here: https://github.com/intel/llvm/pull/8242

**Pull request closed without merging**
