### PR TITLE
[SYCL-MLIR][NFC] Restructure Polygeist dialect

### PR DESCRIPTION
**Pull request by victor-eds**
Apply following changes to the dialect to follow MLIR dialects conventions:

- Change headers locations:
  - Dialect definition: "mlir/Dialect/Polygeist/IR/"
  - Transform passes: "mlir/Dialect/Polygeist/Transforms/"
  - Conversion passes: "mlir/Conversion/PolygeistTo<dialect>/"
  - Dialect utils: "mlir/Dialect/Polygeist/Utils/<file>.h"
- Create a library for each conversion pass.
- Conversion passes are defined under the `mlir` namespace.

This commit does not intend to be a complete refactoring of the dialect. This is a work in progress, not intending to refactor any code. 

Signed-off-by: Victor Perez <victor.perez@codeplay.com>

### CODE REVIEW

**Comment by whitneywhtsang** [comment]
Nothing changed from my last review, forget to submit the reply or forget to push?

**Comment by victor-eds** [comment]
> Nothing changed from my last review, forget to submit the reply or forget to push?

No, I just wanted to continue the discussion on your prev. comment.

**Comment by whitneywhtsang** [comment]
> > Nothing changed from my last review, forget to submit the reply or forget to push?
> 
> No, I just wanted to continue the discussion on your prev. comment.

Did you reply on my previous comment?

**Comment by victor-eds** [comment]
> Did you reply on my previous comment?

Did now

**Review by whitneywhtsang — APPROVED** [review]

**Comment by etiotto** [comment]
This PR was merged prematurely.  It has only one approval (we agreed that large PRs require 2) and it was also merged before passing the LLVM test suite tests.

**Comment by victor-eds** [comment]
> This PR was merged prematurely. It has only one approval (we agreed that large PRs require 2) and it was also merged before passing the LLVM test suite tests.

LLVM test suite tests were failing because we are missing some changes upstream. I checked the tests that were failing (I added/modified some of them upstream). Build was passing, but it uses static libs.

> Also it turns out (at least in my build) this PR caused a link issue. If I remove commit "5d81e3095c0d" then I can link the `sycl-mlir` branch fine. I configure the compiler to build shared libraries.

Yep, I tried with shared libs and also failed. Pushing a fixed vers.

**Comment by etiotto** [comment]
@victor-eds I reverted this PR to get private builds going.  I suggest we redo this PR and add the fix for shared lib you mentioned.

**Comment by victor-eds** [comment]
> @victor-eds I reverted this PR to get private builds going. I suggest we redo this PR and add the fix for shared lib you mentioned.

It's already up for review #8357

**Pull request merged**
