### PR TITLE
[SYCL] Rename usm_system_allocator to usm_system_allocations

### PR DESCRIPTION
**Pull request by dm-vodopyanov**
This patch renames usm_system_allocator to usm_system_allocations to
conform SYCL 2020 spec.

### CODE REVIEW

**Comment by dm-vodopyanov** [comment]
@rbegam, ping.

**Comment by dm-vodopyanov** [comment]
@sergey-semenov, can you please review?

**Comment by sergey-semenov** [comment]
The change LGTM overall, but I'm a little bit concerned about the existing code that may use the old non-conformant value which was introduced 5 months ago. @romanovvlad Do you think this is something we should worry about in cases like this? Does it make sense to deprecate then remove the incorrect value here?

**Comment by romanovvlad** [comment]
> 
> 
> The change LGTM overall, but I'm a little bit concerned about the existing code that may use the old non-conformant value which was introduced 5 months ago. @romanovvlad Do you think this is something we should worry about in cases like this? Does it make sense to deprecate then remove the incorrect value here?

Yes, I think we should keep old value and mark with a deprecation warning. There might be code using it already.

**Comment by dm-vodopyanov** [comment]
@sergey-semenov, can you please review?

**Review by sergey-semenov — APPROVED** [review]

**Pull request merged**
