### PR TITLE
[SYCL] reenable ann_arg/ptr e2e test on windows

### PR DESCRIPTION
**Pull request by broxigarchen**
reenable ann_arg/ptr e2e test on windows, tagged with unsupported: gpu

issue https://github.com/intel/llvm/issues/11224

### CODE REVIEW

**Comment by aelovikov-intel** [comment]
I suggest we merge this as-is @broxigarchen 's morning with the expectation that he will monitor CI status (for other PRs) for a few hours post-merge.

**Review by steffenlarsen — APPROVED** [review]
LGTM!

**Comment by broxigarchen** [comment]
@intel/llvm-gatekeepers Hi can you help to merge this? Thanks!

**Comment by aelovikov-intel** [comment]
> @intel/llvm-gatekeepers Hi can you help to merge this? Thanks!

Merged, please keep an eye on CI.

**Pull request merged**
