### PR TITLE
Revert "[SYCL] Change the definition of device number to use the 'sycl-ls' tool"

### PR DESCRIPTION
**Pull request by vmaksimo**
Reverts intel/llvm#3095, because SYCL :: regression/device_num.cpp test fails in Post-Commit checks

### CODE REVIEW

**Review by vladimirlaz — APPROVED** [review]

**Review by bso-intel — CHANGES_REQUESTED** [review]
sycl/test/regression/device_num.cpp is the new test I added as a part of PR 3095.
I will check what the problem is.
In the worst case, just reverting the test device_num.cpp is appropriate. Not the entire PR.

**Comment by bso-intel** [comment]
@vmaksimo , I just tested the test device_num.cpp on my machine, and it passed.
Where can I find the post-commit check log?

**Comment by bso-intel** [comment]
I created a PR https://github.com/intel/llvm/pull/3286 to fix the bug in device_num.cpp.
Maybe you can wait until PR-3286 gets merged, then this revert would not be necessary.

**Comment by vladimirlaz** [comment]
The fix for post-commit failure was submitted in scope of #3286. No need to revert the patch

**Pull request closed without merging**
