### PR TITLE
[BuildBot] Uplift GPU RT version for Linux CI Process

### PR DESCRIPTION
**Pull request by bb-sycl**
Uplift GPU RT version for Linux to 22.05.22297

### CODE REVIEW

**Comment by bader** [comment]
@DoyleLi, @yanfeng3721, @yinyangsx, can we increase the driver update cadence? There are two newer versions of GPU RT available after 22.05 - the version bb-sycl is using for the update.

**Comment by DoyleLi** [comment]
> @DoyleLi, @yanfeng3721, @yinyangsx, can we increase the driver update cadence? There are two newer versions of GPU RT available after 22.05 - the version bb-sycl is using for the update.

Hi @bader. We have an automatic process to uplift the driver every week. 
And we kept checking the "latest" release version from compute-runtime repo, instead of "Pre-release" version.
Currenlty the "latest" version is kept as 22.05.22297. Do you think it is resonable to switch to update "Pre-release" version?

**Comment by bader** [comment]
> > @DoyleLi, @yanfeng3721, @yinyangsx, can we increase the driver update cadence? There are two newer versions of GPU RT available after 22.05 - the version bb-sycl is using for the update.
> 
> Hi @bader. We have an automatic process to uplift the driver every week. And we kept checking the "latest" release version from compute-runtime repo, instead of "Pre-release" version. Currenlty the "latest" version is kept as 22.05.22297. Do you think it is resonable to switch to update "Pre-release" version?

I think we should check why `latest` hasn't been promoted before making any changes. @olegmaslovatintel, could you clarify that, please?

**Comment by yanfeng3721** [comment]
> > > @DoyleLi, @yanfeng3721, @yinyangsx, can we increase the driver update cadence? There are two newer versions of GPU RT available after 22.05 - the version bb-sycl is using for the update.
> > 
> > 
> > Hi @bader. We have an automatic process to uplift the driver every week. And we kept checking the "latest" release version from compute-runtime repo, instead of "Pre-release" version. Currenlty the "latest" version is kept as 22.05.22297. Do you think it is resonable to switch to update "Pre-release" version?
> 
> I think we should check why `latest` hasn't been promoted before making any changes. @olegmaslovatintel, could you clarify that, please?

Hi @bader , we will check why gpu driver 22.06.22433 uplift is not triggered last week. 
BTW, do you think we can uplift with current version 22.05.22297? 
```
SYCL :: Basic/image/image_accessor_range.cpp, SYCL :: ESIMD/preemption.cpp, SYCL :: ESIMD/regression/complex-lib-lin.cpp, SYCL :: Regression/static-buffer-dtor.cpp, SYCL :: Sampler/normalized-clamp-nearest.cpp
```
For the 5 regression detected, there are two regression SYCL :: ESIMD/regression/complex-lib-lin.cpp & SYCL :: Regression/static-buffer-dtor.cpp are already on track, three new pass can remove XFAIL after PR merged.

**Comment by bader** [comment]
> Hi @bader , we will check why gpu driver 22.06.22433 uplift is not triggered last week. 

I was told the the reason is stated in [the release notes](https://github.com/intel/compute-runtime/releases/tag/22.06.22433): **Marked as prerelease due to major compiler regression on Apollo Lake and Gemini Lake. Other platforms are unaffected.**

> BTW, do you think we can uplift with current version 22.05.22297?
> 
> ```
> SYCL :: Basic/image/image_accessor_range.cpp, SYCL :: ESIMD/preemption.cpp, SYCL :: ESIMD/regression/complex-lib-lin.cpp, SYCL :: Regression/static-buffer-dtor.cpp, SYCL :: Sampler/normalized-clamp-nearest.cpp
> ```
> 
> For the 5 regression detected, there are two regression SYCL :: ESIMD/regression/complex-lib-lin.cpp & SYCL :: Regression/static-buffer-dtor.cpp are already on track, three new pass can remove XFAIL after PR merged.

My preference is to have 0 regressions if possible. Having said that, the decision depends on many factors (other than llvm-test-suite status). I don't have full information to make a rational trade-off, so I'll leave the final decision for @pvchupin.

**Comment by pvchupin** [comment]
If there are only 5 issues we need issues created per each unique and proceed with uplift.

**Review by bader — APPROVED** [review]

**Comment by bader** [comment]
@yanfeng3721, please, prepare a corresponding patch to llvm-test-suite updating the impacted tests.

**Comment by yanfeng3721** [comment]
> @yanfeng3721, please, prepare a corresponding patch to llvm-test-suite updating the impacted tests.

Sure, the patch(https://github.com/intel/llvm-test-suite/pull/870) is ready for review. The llvm-test-suite PR need to be merged at the same time.

**Comment by bader** [comment]
> If there are only 5 issues we need issues created per each unique and proceed with uplift.

@pvchupin, FYI, we observe sporadic crash of sycl-ls tool, which blocks pre-commit validation in GHA. See https://github.com/intel/llvm/actions/runs/1911961143 as an example.

**Comment by pvchupin** [comment]
> > If there are only 5 issues we need issues created per each unique and proceed with uplift.
> 
> @pvchupin, FYI, we observe sporadic crash of sycl-ls tool, which blocks pre-commit validation in GHA. See https://github.com/intel/llvm/actions/runs/1911961143 as an example.

@bader, do you think it's related to the new driver? we need an issue report on that.

**Pull request merged**
