### PR TITLE
[SYCL-MLIR] Add noundef attribute to non-aggregate types if allowed

### PR DESCRIPTION
**Pull request by victor-eds**
Add this attribute if allowed taking into account the kernel argument kind.

Signed-off-by: Victor Perez <victor.perez@codeplay.com>

### CODE REVIEW

**Comment by etiotto** [comment]
@victor-eds I have a draft PR I posted yesterday that overlaps with this work.  I am in the process of implementing an infrastructure that should cover all cases the default clang LLVM code generator handles.

**Comment by victor-eds** [comment]
> @victor-eds I have a draft PR I posted yesterday that overlaps with this work. I am in the process of implementing an infrastructure that should cover all cases the default clang LLVM code generator handles.

Great, handling it in a generic way would be ideal. I guess we can close this PR in that case.

**Comment by etiotto** [comment]
> > @victor-eds I have a draft PR I posted yesterday that overlaps with this work. I am in the process of implementing an infrastructure that should cover all cases the default clang LLVM code generator handles.
> 
> Great, handling it in a generic way would be ideal. I guess we can close this PR in that case.

Let's keep this one in the back pocket for now. And let's discuss at the next status mtg.

**Comment by victor-eds** [comment]
Functionality implemented in #7263

**Pull request closed without merging**
