### PR TITLE
[SYCL] Fix ASFixer build with cmake -DBUILD_SHARED_LIBS=ON

### PR DESCRIPTION
**Pull request by asavonic**
Signed-off-by: Andrew Savonichev <andrew.savonichev@intel.com>

### CODE REVIEW

**Comment by vladimirlaz** [comment]
Please sign-off the commit.

**Comment by asavonic** [comment]
> Please sign-off the commit.

It is signed off already (or I am not aware of something).

**Comment by bader** [comment]
> > Please sign-off the commit.
> 
> It is signed off already (or I am not aware of something).

From the logs:
FileNotFoundError: [Errno 2] No such file or directory: b'../../tools/wait_pr_branch.sh

Looks like env. issue.

**Comment by vladimirlaz** [comment]
> > > Please sign-off the commit.
> > 
> > 
> > It is signed off already (or I am not aware of something).
> 
> From the logs:
> FileNotFoundError: [Errno 2] No such file or directory: b'../../tools/wait_pr_branch.sh
> 
> Looks like env. issue.

Agree. The problem has been fixed

**Pull request merged**
