### PR TITLE
[Matrix][SYCL] Rename wi_slice with wi_data

### PR DESCRIPTION
**Pull request by yubingex007-a11y**

### CODE REVIEW

**Comment by yubingex007-a11y** [comment]
we can modify [sycl/doc/extensions/experimental/sycl_ext_oneapi_matrix.asciidoc](https://github.com/intel/llvm/pull/5728/files#diff-47966095a6d3bd166ad70246ca951fcb099a0c324fc0e6782b95bd749671e24a) along with code, am i right?

**Comment by dkhaldi** [comment]
> we can modify [sycl/doc/extensions/experimental/sycl_ext_oneapi_matrix.asciidoc](https://github.com/intel/llvm/pull/5728/files#diff-47966095a6d3bd166ad70246ca951fcb099a0c324fc0e6782b95bd749671e24a) along with code, am i right?

Since this is a small change, this should be okay.

**Review by gmlueck — APPROVED** [review]

**Comment by yubingex007-a11y** [comment]
ping?

**Comment by yubingex007-a11y** [comment]
@intel/llvm-reviewers-runtime

**Comment by yubingex007-a11y** [comment]
ping? @bader @vladimirlaz

**Review by vladimirlaz — APPROVED** [review]

**Comment by yubingex007-a11y** [comment]
@vladimirlaz could you please help us merge it? thanks!

**Pull request merged**
