### PR TITLE
Revert "[NFC][SYCL] Switch to std::enable_if (#7628)"

### PR DESCRIPTION
**Pull request by Fznamznon**
This reverts commit 74833b285babb95a839724d55d7b3a45038c8cad. We found issues when trying to build the project on RHEL7 systems that we need in our OS support matrix.

### CODE REVIEW

**Comment by Fznamznon** [comment]
@intel/llvm-reviewers-runtime please review, it blocks pulldown process.

**Review by steffenlarsen — APPROVED** [review]

**Comment by Fznamznon** [comment]
How to handle lint issue?

**Comment by steffenlarsen** [comment]
> How to handle lint issue?

Best option is probably just to address the formatting issues in an additional commit.

**Comment by steffenlarsen** [comment]
CUDA failures are unrelated and have been reported. Since this is a NFC revert we will go ahead with the merge with missing review. @intel/dpcpp-esimd-reviewers for awareness.

**Pull request merged**
