### PR TITLE
[Driver][SYCL] Enable use of response files for sycl link step

### PR DESCRIPTION
**Pull request by mdtoguchi**
It was found that with large command lines, with large numbers of files,
The default response file usage for sycl-link would end up failing at
the llvm-link stage due to the length of the command line.  All of the
tools within the sycl-link step (clang-offload-wrapper, llvm-link,
llvm-spirv, llc) all support full response files.  Go ahead and enable
usage of full response files for sycl-link.

Signed-off-by: Michael D Toguchi <michael.d.toguchi@intel.com>

### CODE REVIEW

**Comment by AGindinson** [comment]
@mdtoguchi, as a second thought, should `RF_Full` also be enabled for partial link? We could run into the same situation, supposing a large enough number of static libraries gets passed.

**Comment by mdtoguchi** [comment]
> @mdtoguchi, as a second thought, should `RF_Full` also be enabled for partial link? We could run into the same situation, supposing a large enough number of static libraries gets passed.

Done - good suggestion!

**Comment by mdtoguchi** [comment]
Looks like the response file usage has been updated.  The setting is now at the addCommand level opposed to the tool level.  Modifications coming soon.

**Comment by AGindinson** [comment]
Whoops, sorry, I've somehow missed out on the latest branch update.

**Pull request merged**
