### PR TITLE
[SYCL] Change alignment to common property

### PR DESCRIPTION
**Pull request by broxigarchen**
Move alignment from annotated_ptr specific property to a common property

### CODE REVIEW

**Review by rolandschulz — APPROVED** [review]

**Review by maarquitos14 — APPROVED** [review]
LGTM.

**Comment by broxigarchen** [comment]
> This change makes the alignment property specific to FPGA because it is now moved to the extension "sycl_ext_intel_fpga_kernel_arg_properties". Is that intentional? Do we want to use this property also for other devices, or is it only useful for FPGA?

I think you are right. I'll update this PR

**Comment by GarveyJoe** [comment]
Looks like alignment is now defined in two places.

**Review by GarveyJoe — COMMENTED** [review]
commented

**Comment by gmlueck** [comment]
> > This change makes the alignment property specific to FPGA because it is now moved to the extension "sycl_ext_intel_fpga_kernel_arg_properties". Is that intentional? Do we want to use this property also for other devices, or is it only useful for FPGA?
> 
> I think you are right. I'll update this PR

Is your intention to move the alignment property to an extension that is not specific to FPGA, or are you arguing that it should be FPGA specific?

**Review by gmlueck — APPROVED** [review]
spec changes LGTM.

**Pull request merged**
