### PR TITLE
[Driver][SYCL] Do not pull in late static device libs for AMD GPU

### PR DESCRIPTION
**Pull request by mdtoguchi**
The addition of the new OpenMP offloading driver path, which unbundles
archives later in the toolchain is interfering with the device linking
behaviors involving AMD GPU targets for SYCL offload compiles.

Disable the inclusion of these unbundled static archives as we do not yet
take advantage of the new offloading paths.

### CODE REVIEW

**Comment by mdtoguchi** [comment]
This is to address: https://github.com/intel/llvm/issues/6089

**Comment by abagusetty** [comment]
@mdtoguchi I see that the linking issue is addressed with the PR in several applications on atleast a couple of different AMD GPU archs.

**Review by qichaogu — APPROVED** [review]

**Comment by zjin-lcf** [comment]
Thanks.

**Comment by mdtoguchi** [comment]
@hchilama, can you take a look?

**Review by hchilama — APPROVED** [review]

**Comment by mdtoguchi** [comment]
@intel/llvm-gatekeepers, this looks ready for merge - thanks!

**Pull request merged**
