### PR TITLE
[SYCL] Remove sycl/examples

### PR DESCRIPTION
**Pull request by aobolensk**
Remove simple-dpcpp-app.cpp example from sycl/examples folder and the folder itself.

### CODE REVIEW

**Review by alexbatashev — CHANGES_REQUESTED** [review]
Please, provide rationale for this change

**Comment by aobolensk** [comment]
> Please, provide rationale for this change

Moved example to check-sycl tests instead of removal.

**Review by alexbatashev — APPROVED** [review]
LGTM, please, update PR description

**Comment by aobolensk** [comment]
> LGTM, please, update PR description

Done

**Review by bader — CHANGES_REQUESTED** [review]
What is the value of this test? Does it improve code coverage of existing tests or just increase `check-sycl` with no additional value?

**Comment by alexbatashev** [comment]
> What is the value of this test? Does it improve code coverage of existing tests or just increase `check-sycl` with no additional value?

It is the same test as we offer in Get Started Guide. The only reason we have it is to make sure our instructions are still working.

**Comment by bader** [comment]
> > What is the value of this test? Does it improve code coverage of existing tests or just increase `check-sycl` with no additional value?
> 
> It is the same test as we offer in Get Started Guide. The only reason we have it is to make sure our instructions are still working.

I don't think it's the valid reason. This test doesn't validate Get Started Guide instructions because it's a copy of the example and I don't see anything that guarantees they are in sync.
I suggest we just remove this example, unless you find a way to integrate exactly this source and build instructions to the documentation.

**Review by bader — APPROVED** [review]

**Review by alexbatashev — APPROVED** [review]

**Comment by keryell** [comment]
> This test doesn't validate Get Started Guide instructions because it's a copy of the example and I don't see anything that guarantees they are in sync.

In the same vein, is there a way to check that the full examples in the SYCL specification work?

**Pull request merged**
