### PR TITLE
[SYCL] Add rcp for fp32 and fp64 with rounding mode supported

### PR DESCRIPTION
**Pull request by jinge90**
This PR adds frcp_rd/n/u/z and drcp_rd/n/u/z to sycl::ext::intel::math which corresponds to CUDA math's __frcp_r* and __drcp_r*

### CODE REVIEW

**Comment by jinge90** [comment]
Hi, @zettai-reido @akolesov-intel @xtian-github 
Could you help review this PR?
Thanks very much.

**Review by akolesov-intel — APPROVED** [review]
Looks reasonable to map rcp to existing div implementations with rounding

**Review by xtian-github — APPROVED** [review]
LGTM

**Review by bso-intel — APPROVED** [review]

**Comment by jinge90** [comment]
Hi, @intel/llvm-gatekeepers 
Could you help merge this patch?
Thanks very much.

**Pull request merged**
