### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW46)

### PR DESCRIPTION
**Pull request by Fznamznon**
LLVM: llvm/llvm-project@9aae3dd94c881a36998ee8027d3e126ff3becf89
SPIRV-LLVM-Translator: [KhronosGroup/SPIRV-LLVM-Translator@bdc5988](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/5ce6a99bb83a510df7d62950a2fecec38c1527bd)

### CODE REVIEW

**Comment by Fznamznon** [comment]
device_num failure is unrelated.

**Comment by Fznamznon** [comment]
Unrelated failure SYCL :: Basic/barrier_order.cpp - Reported in https://github.com/intel/llvm/issues/7330. Temporarily disabled in https://github.com/intel/llvm-test-suite/pull/1376.

**Comment by Fznamznon** [comment]
Jenkins/Precommit seems to be failing for infrastructural reason. I reported it.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Thu 10 Nov 2022 08:12:04 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Thu 10 Nov 2022 08:16:23 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
