### PR TITLE
[SYCL][FPGA] Allow tablegen handle mutually exclusive decl attrs (SYCLIntelRegister and SYCLIntelMemory)

### PR DESCRIPTION
**Pull request by smanna12**
This patch uses MutualExclusions tablegen support to allow us to remove a custom diagnostic checking codes with FPGA attributes: [[intel:fpga_register]] and [[intel::fpga_memory]].

### CODE REVIEW

**Review by premanandrao — APPROVED** [review]
LGTM

**Comment by smanna12** [comment]
Thanks @premanandrao for reviews

**Comment by smanna12** [comment]
The failing is unrelated to my patch.

@intel/llvm-gatekeepers , could you please merge this PR? Thanks

**Comment by smanna12** [comment]
Ping @intel/llvm-gatekeepers, please merge. Thanks

**Pull request merged**
