### PR TITLE
[SYCL][UR] Replace definition of PI mutexes with UR mutexes

### PR DESCRIPTION
**Pull request by jandres742**

### CODE REVIEW

**Comment by jandres742** [comment]
ESIMD tests failing with:
```
$ "env" "ONEAPI_DEVICE_SELECTOR=ext_intel_esimd_emulator:gpu" "CM_RT_PLATFORM=skl" "/__w/llvm/llvm/build-e2e/ESIMD/InlineAsm/Output/asm_glb.cpp.tmp.out"
# command output:
SYCL exception caught: No device of requested type available. -1 (PI_ERROR_DEVICE_NOT_FOUND)
```

changes on this PR are not ESIMD related, so that should be an error in infra.

**Comment by jandres742** [comment]
@bader  , @smaslov-intel 

L0 Gen9 is failing on memory_consumption, is that a real failure? seeing it also in https://github.com/intel/llvm/pull/9013

ESIMD failures are unrelated.

**Comment by jandres742** [comment]
@smaslov-intel please review.

**Comment by smaslov-intel** [comment]
> @bader , @smaslov-intel
> L0 Gen9 is failing on memory_consumption, is that a real failure? seeing it also in #9013

Known and is tracked in https://github.com/intel/llvm/issues/9008

**Review by smaslov-intel — APPROVED** [review]

**Pull request merged**
