### PR TITLE
[SYCL] Fix accessor::swap() method

### PR DESCRIPTION
**Pull request by KornevNikita**
Need to swap new member MAccData (added in 01e60f76b3484913fad27d8b0e5fe627d9151689) in addition to Impl.

### CODE REVIEW

**Comment by KornevNikita** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1265

**Review by romanovvlad — APPROVED** [review]

**Review by dm-vodopyanov — APPROVED** [review]

**Comment by KornevNikita** [comment]
I believe this failure is unrelated, but I don't see any failures in another PRs

**Comment by KornevNikita** [comment]
Hello @aelovikov-intel, could you take a look please?

**Review by aelovikov-intel — APPROVED** [review]
I thought two other approvals is enough...

I wonder why MAccData couldn't live in the `impl` though.

**Pull request merged**
