### PR TITLE
[SYCL] Move definitions to the reserved name space.

### PR DESCRIPTION
**Pull request by bader**
To avoid conflicts with user definitions we use underscore prefix
reserved for compiler needs.

### CODE REVIEW

**Review by premanandrao — APPROVED** [review]
FE changes look good to me.

**Review by elizabethandrews — COMMENTED** [review]
Just for my curiosity, is there a reason you prefixed with SYCL instead of DPCPP as mentioned issue #2665

**Comment by bader** [comment]
> Just for my curiosity, is there a reason you prefixed with SYCL instead of DPCPP as mentioned issue #2665

The first reason is consistency - so far we've been using SYCL.
The second reason - to save work on renaming for upstreaming. Although we haven't established naming convention SYCL runtime in llorg, but SYCL seems to be less controversial than DPCPP.

**Review by smaslov-intel — APPROVED** [review]
pi* changes look good.

**Review by AlexeySachkov — DISMISSED** [review]
`half_type.hpp` changes LGTM

**Review by romanovvlad — APPROVED** [review]

**Review by turinevgeny — DISMISSED** [review]
types.hpp looks fine.

**Comment by bader** [comment]
@kbobrovs, could you take a look, please?

**Review by elizabethandrews — APPROVED** [review]
FE changes LGTM

**Review by kbobrovs — DISMISSED** [review]
sycl/source/detail/device_binary_image.cpp
sycl/source/detail/program_manager/program_manager.cpp

LGTM

**Review by Fznamznon — APPROVED** [review]

**Comment by bader** [comment]
Thanks for review! I had to push one more commit to resolve merge conflicts. There were two places where I had to do additional changes one changed code block was removed and another one was moved to another file. I don't expect another round of reviews for merge commit. I'll merge after pre-commit testing passes.

**Review by turinevgeny — APPROVED** [review]

**Comment by keryell** [comment]
> The second reason - to save work on renaming for upstreaming. Although we haven't established naming convention SYCL runtime in llorg, but SYCL seems to be less controversial than DPCPP.

Quite sensible!

**Pull request merged**
