### PR TITLE
[mlir][llvm] Define annotation intrinsics

### PR DESCRIPTION
**Pull request by victor-eds**
Define `llvm.intr.var.annotation`, `llvm.intr.ptr.annotation` and `llvm.intr.annotation` in the `llvm` dialect as `llvm.var.annotation`, `llvm.ptr.annotation` and  `llvm.annotation` counterparts.

### CODE REVIEW

**Comment by victor-eds** [comment]
This is needed to raise https://github.com/intel/llvm/pull/10251

**Review by sommerlukas — APPROVED** [review]
Changes LGTM. 

Do you know why `llvm.var.annotation` and `llvm.ptr.annotation` have an additional argument (the last pointer argument) not documented in the LLVM language reference manual?

**Review by jopperm — APPROVED** [review]

**Comment by victor-eds** [comment]
> Do you know why `llvm.var.annotation` and `llvm.ptr.annotation` have an additional argument (the last pointer argument) not documented in the LLVM language reference manual?

Apparently it's an `AnnotateAttr`. Not documented anywhere that I've seen. I'll rename the operand to better fit this.

**Review by etiotto — APPROVED** [review]

**Review by whitneywhtsang — APPROVED** [review]

**Comment by victor-eds** [comment]
Merging this before being merged upstream due to time constraints

**Pull request merged**
