### PR TITLE
[SYCL] Don't launch test if there's no device available

### PR DESCRIPTION
**Pull request by s-kanaev**

### CODE REVIEW

**Comment by bader** [comment]
@s-kanaev, I think we should apply similar fix to sycl/unittests/program/KernelRelease.cpp as well.
@sergey-semenov, am I right?

I see that it fails in post-commit: https://github.com/intel/llvm/runs/747446124.

**Comment by sergey-semenov** [comment]
@bader, I don't think so, it seems that there's no need for this change in `CommandsWaitForEvents` in the first place. Host device should always be available via default selector according to the spec.

**Comment by bader** [comment]
There is no problem statement in the PR description, but I guess the missing piece is that failure happens when default_selector behavior is overwritten with env. variables.
@s-kanaev, am I right? Could you describe the problem in the code comments and PR description, please?

**Comment by s-kanaev** [comment]
No, there is no real issue here.
Closing the PR.

**Pull request closed without merging**
