### PR TITLE
[SYCL] [DOC] Group sorting algorithm design review

### PR DESCRIPTION
**Pull request by andreyfe1**
Implementation of the corresponding [Spec extension](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/GroupAlgorithms/SYCL_INTEL_group_sort.asciidoc).

Signed-off-by: Fedorov, Andrey <andrey.fedorov@intel.com>

### CODE REVIEW

**Comment by capatober** [comment]
The only problem I see is how to get temporary memory we need for implementation if we are in a kernel?

After discussion with @Pennycook we found 2 possible ways to address it:

1. Create any "SPIRV" intrinsic that can help us allocate dynamic memory within the kernel. Inviting @AlexeySachkov, @AlexeySotkin, @bashbaug to discuss is it implementable or not.
2. Modify first parameter of `joint_sort` and `sort_over_group` algorithms (possible for other group algorithms as well) to let it be not just a `sycl::group` or `sycl::sub_group`, but a wrapper (kind of C++ execution policy) that accepts `sycl::group` or `sycl::sub_group` and a temporary memory, e.g.
```cpp
    q.submit([&](sycl::handler& h) {
        ...
        sycl::accessor<uint8_t, 1, read_write, local> scratch(temp_local_memory_size, h);
        h.parallel_for(..., [=](sycl::nd_item<1> id) {
            ...
            joint_sort(sycl::exec(id.get_group(), scratch), first, last, compare);
        });
    });
```
However, here we may need to provide a function (e.g. `get_local_memory_size`) that can help to calculate the `temp_local_memory_size` value because users don't know how much temporary memory we need.
@gmlueck, @rolandschulz, @Pennycook, what do you think about this approach?

**Comment by gmlueck** [comment]
> Create any "SPIRV" intrinsic or built-in function that can help us allocate dynamic memory within the kernel. Inviting @AlexeySachkov, @AlexeySotkin, @bashbaug to discuss is it implementable or not.

Do we really need a way to *dynamically* allocate memory, or is it sufficient to allocate a fixed amount of memory, where the amount is determined at the point when the kernel is submitted / JIT compiled?  For example, is there a way in SPIR-V to allocate an array in local memory, where the array's extent is determined by a specialization constant?

**Comment by capatober** [comment]
Let me provide an example.
```cpp
joint_sort(id.get_group(), first, last, compare);
```
Here we need `(last - first) * sizeof(std::iterator_traits<Iter>::value_type)` additional memory. `last` and `first` are runtime information.

Another example:
```cpp
sort_over_group(id.get_group(), value, compare);
```
Here we need `group.get_local_range(0) * sizeof(T)` additional memory. Is local range size determined at the point when the kernel is submitted / JIT compiled?

**Comment by Pennycook** [comment]
> Here we need (last - first) * sizeof(std::iterator_traits<Iter>::value_type) additional memory. last and first are runtime information.

This didn't occur to me yesterday, but do we really *need* the additional memory, or is that an optimization?  Can we sort in-place?  That would allow us to make passing this new temporary space argument optional, which would be nice.

> Here we need id.get_group().get_local_range(0) * sizeof(T) additional memory. Is local range size determined at the point when the kernel is submitted / JIT compiled?

Local range size is determined when the kernel is submitted.  Several backends (including OpenCL) allow for the size of a local memory allocation to be provided at kernel launch time (e.g. see https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clSetKernelArg.html).  I think if there was a way to communicate to the host that this kernel wanted `sizeof(T)` bytes of local memory per work-item, we could have the host create the local memory allocation upon kernel launch.  There's no way to do that today, though, so we'd need some new metadata.

Assuming we could make this work, it has an advantage over specialization constants in that the kernel wouldn't need to be recompiled for different work-group sizes.

**Comment by capatober** [comment]
> do we really _need_ the additional memory, or is that an optimization? Can we sort in-place? That would allow us to make passing this new temporary space argument optional, which would be nice.

The thing is if default sorting algorithm is the merge sort algorithm, we need an additional memory to merge 2 sequences into 3rd. Without additional memory we will have data races. Example:
Source sequence: `1 0`
1st work-item should place `1` at the place where `0` is located (the same is for the 2nd work-item that should place `0` where `1` is located) and we have a data race.

**Comment by Pennycook** [comment]
> The thing is if default sorting algorithm is the merge sort algorithm, we need an additional memory to merge 2 sequences into 3rd.

I see two ways around this, but I'm not sure if they're good ideas.

1. Change `default_sorter` into a template class.  That would allow `default_sorter<int>` and `default_sorter<user-defined-type>` to be different, and would highlight to users that they should expect different implementations/performance for user-defined and primitive types.

2. Implement some sort of hierarchical merge sort.  Can't you avoid races by chunking the data into N/P chunks and sorting those, using P/2 hardware threads to combine pairs of chunks, then repeat with bigger and bigger chunks?  It would mean that the final step (combining two N/2 sized chunks) would run on a single hardware thread, but I think it would be functionally correct.

**Comment by capatober** [comment]
1. Not sure I understand how it can help us. We can highlight that when users call `joint_sort` or `sort_over_group` with `Compare` they can expect different implementations/performance for user-defined and primitive types.
2. However, it would run on a single hardware thread. I think that's not we expect for performance, e.g. if we have 1 000 000 000 elements, single work item will process all elements on the final step. It looks like execution time consuming.

**Comment by akukanov** [comment]
Let me remind that we do not have to use the merge sort by default; any comparison-based sorting algorithm with the complexity of O(n lg n) will be good enough. And for sort_over_group, the asymptotic complexity is irrelevant as the number of items is known and small, so for example some sorting network can be used.

**Comment by AlexeySotkin** [comment]
> Create any "SPIRV" intrinsic or built-in function that can help us allocate dynamic memory within the kernel. Inviting @AlexeySachkov, @AlexeySotkin, @bashbaug to discuss is it implementable or not.

Yes, it is possible to create a SPIR-V instruction(in scope of a SPIR-V extension) for this purpose. But we should consider how device BE compilers will support this instruction/extension. I guess it should not be a problem on CPU. Need to clarify with IGC if it is possible on GPU.

As alternative and more flexible option, maybe(I'm not sure) we could add _allocator_ function to the API. It might be a pointer to a host function which allocates local memory and returns pointer back to the kernel. @AlexeySachkov any comments?

**Comment by bashbaug** [comment]
> Need to clarify with IGC if it is possible on GPU.

It's possible - we have a similar intrinsic we use internally for the work-group collective functions:

https://github.com/intel/intel-graphics-compiler/blob/master/IGC/BiFModule/Implementation/IBiF_Macros.cl#L14

```c
// Use this to grab a pointer to local memory whenever you
// are treating the local memory as automatic storage.
#define GET_MEMPOOL_PTR(_ptr, _type, _allocAllWorkgroups, _additionalElems) \
  __local _type* _ptr =                                                     \
    (__local _type*)__builtin_IB_AllocLocalMemPool(                         \
        _allocAllWorkgroups,                                                \
        _additionalElems,                                                   \
        sizeof(_type));
```

There are some limitations and restrictions on the use of this intrinsic that will either need to be relaxed or documented - it's currently not quite as flexible as a local memory `alloca`.

**Comment by capatober** [comment]
@bashbaug, could you please clarify what are limitations and restrictions? I'm trying to realize whether we can live with them or not.

**Comment by PawelJurek** [comment]
> @bashbaug, could you please clarify what are limitations and restrictions? I'm trying to realize whether we can live with them or not.

One of the restrictions is that all arguments to this function should be compile-time constants, so you will not be able to allocate the memory dynamically like in the case you mentioned:
`(last - first) * sizeof(std::iterator_traits<Iter>::value_type)`

**Comment by capatober** [comment]
@PawelJurek, thanks for the clarification. Seems, we couldn't follow the way with dynamic local memory allocation SPIR-V/built-in function.
So, to support custom types and comparators I see 2 ways:
1. Try default sorter implementation that doesn't require additional local memory (I'm working on it).
2. Modify first parameter of `joint_sort` and `sort_over_group` (possible for other group algorithms as well) to allow not `sycl::group` or `sycl::sub_group`, but a wrapper (close to C++ execution policy) that accepts `sycl::group` or `sycl::sub_group` and a temporary memory. It requires users to allocate a temporary local memory on their side.

**Comment by capatober** [comment]
The only question is radix sort. It still requires additional dynamic local memory.

**Comment by Pennycook** [comment]
> The only question is the radix sort implementation. It still requires additional dynamic local memory.
> So, I tend to think that it's better to extend `radix_sorter` interface to allow passing local memory to the constructor.
> What do you think about that?

I think if dynamic local memory were only ever going to be required for `radix_sorter`, this would be the way to go.  But I think we've already seen some use-cases for passing memory into other types of sorter (e.g. you could pick a different merge sort implementation if temporary memory is available), and we've discussed passing memory into other algorithms (e.g. reductions for user-defined types).

Moving towards defining a policy for group algorithms seems to be the most flexible thing here:

```c++
auto grp = item_id.get_group();

// Default sort
ext::oneapi::sort_over_group(grp, x);

// User has provided some scratch space -- library may choose a different default sort
ext::oneapi::sort_over_group(ext::oneapi::policy_tbd{grp, tmp}, x);

// Radix sort requires temporary memory...
auto rsorter = ext::oneapi::radix_sorter<int, ext::oneapi::radix_order::descending>());
ext::oneapi::sort_over_group(ext::oneapi::policy_tbd{grp, tmp}, x, sorter);

// ... and so this would be an error
ext::oneapi::sort_over_group(grp, x, rsorter);

// Other algorithms can benefit too
auto sum = sycl::reduce_over_group(ext::oneapi::policy_tbd{grp, tmp}, x, std::plus<>());
```

**Comment by capatober** [comment]
@Pennycook, do we expect that the approach with the "policy-like" object can go to the SYCL Spec?
If yes, we can go this way. If no, we are doomed to have it as a SYCL extension for a long time. I think, we don't want this scenario, correct?

**Comment by Pennycook** [comment]
> @Pennycook, do we expect that the approach with the "policy-like" object can go to the SYCL Spec?
If yes, we can go this way. If no, we are doomed to have it as a SYCL extension for a long time. I think, we don't want this scenario, correct?

I see no reason that we couldn't propose the policy-like object for inclusion in a future version of the SYCL specification.  Whether it is would be accepted or would require changes depends on Khronos.  I suspect we could make a strong case for it, especially if it helps to enable user-defined type support for other algorithms.

Michael Wong [has said](https://www.hpcwire.com/2021/02/09/sycl-2020-launches-new-name-new-features/) that he anticipates the next version of the SYCL specification will be released in 2023.  Whether we go with the "policy-like" object or not, I don't think that group sorting algorithms could be part of a SYCL specification until then at the earliest.  If there is cross-vendor interest in supporting group sorting algorithms there could be a cross-vendor or Khronos extension to SYCL 2020, but it would still be an extension.

**Comment by akukanov** [comment]
> One of the restrictions is that all arguments to this function should be compile-time constants, so you will not be able to allocate the memory dynamically

What about something like this pseudocode - would it work, and could it be completely hidden by the device compiler?

```
auto n = last - first; // the number of elements
if (n<=64)
    use a buffer of size 64
else if (n<=256)
    use a buffer of size 256
else if (n<=1024)
// etc
else // too big to fit local memory
    use global memory or return an error
```

**Comment by capatober** [comment]
> Shell sort is not a O(n log n) sort, as far as I know. Should we relax the requirements then?

It has already been relaxed since parallel merge sort implementation complexity is `O(N*log_2(N))`. See [Spec extension](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/GroupAlgorithms/SYCL_INTEL_group_sort.asciidoc).

> What about something like this pseudocode - would it work, and could it be completely hidden by the device compiler?

+@PawelJurek, @jinge90

**Comment by jinge90** [comment]
> > Shell sort is not a O(n log n) sort, as far as I know. Should we relax the requirements then?
> 
> It has already been relaxed since parallel merge sort implementation complexity is `O(N*log_2(N))`. See [Spec extension](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/GroupAlgorithms/SYCL_INTEL_group_sort.asciidoc).
> 
> > What about something like this pseudocode - would it work, and could it be completely hidden by the device compiler?
> 
> +@PawelJurek, @jinge90



> > Shell sort is not a O(n log n) sort, as far as I know. Should we relax the requirements then?
> 
> It has already been relaxed since parallel merge sort implementation complexity is `O(N*log_2(N))`. See [Spec extension](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/GroupAlgorithms/SYCL_INTEL_group_sort.asciidoc).
> 
> > What about something like this pseudocode - would it work, and could it be completely hidden by the device compiler?
> 
> +@PawelJurek, @jinge90

I am afraid we can't allocate global or local memory space in device code, if we need to access such memory, it should be allocated before entering device function.
Thanks very much.

**Comment by akukanov** [comment]
> It has already been relaxed since parallel merge sort implementation complexity is O(N*log_2(N)). See Spec extension.

I thought log_2 means binary logarithm, not squared logarithm. If we mean squared logarithm, it needs to be written more clearly. Meanwhile, the worst case complexity of Shell sort depends on the chosen gap sequence (https://en.wikipedia.org/wiki/Shellsort#Gap_sequences).

**Comment by capatober** [comment]
> I am afraid we can't allocate global or local memory space in device code, if we need to access such memory, it should be allocated before entering device function.

I believe we can allocate static (not dynamic) local memory in device code (See [here](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/LocalMemory/SYCL_INTEL_local_memory.asciidoc#include-paragraphs)). 

> I thought log_2 means binary logarithm, not squared logarithm

I see. It was discussed [here](https://github.com/intel/llvm/pull/3514#discussion_r618996558). Maybe it's also not the best way.

> Meanwhile, the worst case complexity of Shell sort depends on the chosen gap sequence

Correct. As we can see by the link from your comment, we can choose gaps where complexity is N * squared logarithm. So, I think it's implementation details.

**Pull request closed without merging**
