### PR TITLE
[UR][CUDA] Ifdef remaining CUDA 11 datatypes

### PR DESCRIPTION
**Pull request by hdelan**
https://github.com/intel/llvm/pull/10691 missed these extra cases. This PR adds the needed ifdefs

### CODE REVIEW

**Comment by hdelan** [comment]
Ping @intel/llvm-gatekeepers this can be merged

**Comment by hdelan** [comment]
Ping @intel/llvm-gatekeepers can we merge this please?

**Comment by dm-vodopyanov** [comment]
> Ping @intel/llvm-gatekeepers can we merge this please?

Not yet:

image

@hdelan please get the approval from the remaining group, it was recently added to the codeowners file.

**Comment by hdelan** [comment]
Aha I didn't realise. Thanks @dm-vodopyanov

**Comment by dm-vodopyanov** [comment]
@intel/bindless-images-reviewers friendly ping

**Comment by hdelan** [comment]
Thanks @ProGTX . @dm-vodopyanov this can be merged now. Thanks for patience

**Pull request merged**
