### PR TITLE
[SYCL][HIP] Adds support for PCI device id and UUID

### PR DESCRIPTION
**Pull request by abagusetty**
Completes the extensions for HIP.

### CODE REVIEW

**Comment by abagusetty** [comment]
@npmiller If you can also comment. Wasn't able to choose additional reviewers

**Comment by zjin-lcf** [comment]
I have a question for @abagusetty . Are these HIP macros related to the issue https://github.com/RadeonOpenCompute/ROCm/issues/1907 ?

**Comment by abagusetty** [comment]
It looks the macro are related to the compute capability and the ones used for the PR were related to the driver-version
________________________________

**Review by npmiller — APPROVED** [review]

**Comment by abagusetty** [comment]
@llvm-reviewers-runtime  can I get help with review and merge

**Comment by abagusetty** [comment]
pinging @llvm-reviewers-runtime

**Comment by abagusetty** [comment]
@intel/llvm-reviewers-runtime Friendly ping

**Review by bso-intel — APPROVED** [review]
LGTM

**Pull request merged**
