### PR TITLE
[ESIMD] Do not use ReadNone attribute for GenX intrinsics

### PR DESCRIPTION
**Pull request by v-klochkov**
The attribute is suggested by GenX Intrinsics component for call declarations. Such attribute on calls causes verification since LLVM 16, and needs to be replaced with setMemoryEffects(MemoryEffects::none()).

Signed-off-by: Vyacheslav N Klochkov <vyacheslav.n.klochkov@intel.com>

### CODE REVIEW

**Comment by v-klochkov** [comment]
The existing LIT test "SYCLLowerIR/ESIMD/lower_spirv_intrins.ll" started failing after the recent pulldown from llvm.org and it was the main motivation to make this fix/PR.
The fail without this PR is not visible yet because pulldown from llvm.org is still in process (and is blocked by the issue being fixed here).

**Comment by sarnex** [comment]
> The existing LIT test "SYCLLowerIR/ESIMD/lower_spirv_intrins.ll" started failing after the recent pulldown from llvm.org 

Ah ok so we think some upstream change started adding llvm::Attribute::ReadNone to stuff but we shouldn't have that added for genx instincts?

**Comment by sarnex** [comment]
> > stuff but we shouldn't have that added for
> 
> ESIMD/sycl-post-link uses external component 'vc-intrinsics' which passes us GenX intrinsic declaration and that declaration always had 'readnone' attribute. It is needed for older versions of LLVM (let's say LLVM 9). For LLVM 16 the attribute is not correct on CI and the test stops passing verification.
> 
> I will update the test within an hour to verify 'readnone' does not show up in the generated LLVM IR after sycl-post-link.

Thanks, this is exactly the explanation I was looking for

**Review by sarnex — APPROVED** [review]

**Comment by v-klochkov** [comment]
CUDA CI is still in process (seems to hang). 
I am merging the fix now because this minor fix in ESIMD/LowewrESIMD cannot interfere with CUDA. Also, the issue being fixed here is blocking pulldown process.

**Pull request merged**
