### PR TITLE
[SYCL][ESIMD] Remove test_proxy class

### PR DESCRIPTION
**Pull request by turinevgeny**

### CODE REVIEW

**Review by sarnex — APPROVED** [review]
We also have the `operator_assignment_move_and_copy_core.cpp`, `ctor_move_fp_extra.cpp`, `ctor_move_core.cpp` tests which are currently `XFAIL: *` and use this test proxy, so we can probably remove those. Also the header they use `ctor_move.hpp`

**Comment by turinevgeny** [comment]
> We also have the `operator_assignment_move_and_copy_core.cpp`, `ctor_move_fp_extra.cpp`, `ctor_move_core.cpp` tests which are currently `XFAIL: *` and use this test proxy, so we can probably remove those. Also the header they use `ctor_move.hpp`

Thanks for the hint, done.

**Comment by turinevgeny** [comment]
@intel/llvm-gatekeepers this PR is ready, CUDA fails are unrelated.

**Comment by sarnex** [comment]
Love to see code cleanup like this, nice!

**Review by v-klochkov — CHANGES_REQUESTED** [review]
Temporarily blocking this PR before another planned discussion.

**Pull request closed without merging**
