### PR TITLE
[SYCL][ABI-Break][PI] Remove deprecated piEnqueueNativeKernel

### PR DESCRIPTION
**Pull request by kbenzie**
This patch removes the deprecated entry-point `piEnqueueNativeKernel`.
This change is being made in preparation for porting the OpenCL plugin
to Unified Runtime which does not intend to support enqueuing native
kernels since it has already being deprecated.

### CODE REVIEW

**Review by jandres742 — APPROVED** [review]

**Review by jchlanda — APPROVED** [review]
CUDA/HIP 👍

**Review by EwanC — APPROVED** [review]
Graphs LGTM

**Review by sergey-semenov — APPROVED** [review]

**Comment by kbenzie** [comment]
@intel/dpcpp-esimd-reviewers a review would be much appriciated, thanks.

**Comment by kbenzie** [comment]
@intel/dpcpp-esimd-reviewers ping to review this please.

The relevant changes are very small, removal of an unimplemented function in [sycl/plugins/esimd_emulator/pi_esimd_emulator.cpp](https://github.com/intel/llvm/pull/10008/files#diff-ed69083c592e41858914daf14bcbf59030c1533c179f1688f90710573ce2e5d4). This is also pretty urgent since this PR contains ABI breaking changes and the merge deadline is looming.

**Review by turinevgeny — APPROVED** [review]
ESIMD changes LGTM.

**Comment by kbenzie** [comment]
@intel/llvm-gatekeepers this is now ready to merge

**Pull request merged**
