### PR TITLE
[SYCL-MLIR] Add PointerElementTypeInterface trait to Group type

### PR DESCRIPTION
**Pull request by victor-eds**

### CODE REVIEW

**Review by whitneywhtsang — APPROVED** [review]

**Comment by whitneywhtsang** [comment]
@victor-eds `lint` is failing. We should merge after the tests all pass.

**Comment by etiotto** [comment]
@victor-eds loks like the `lint` test failed and therefore the lit tests were not run on this PR.  Can you revert it and resubmit?

**Comment by victor-eds** [comment]
> @victor-eds looks like the `lint` test failed and therefore the lit tests were not run on this PR. Can you revert it and resubmit?

It's in a new PR. You can accept it right away.

**Comment by pvchupin** [comment]
@etiotto, you can talk to @tfzhu about Jenkins configuration and I recommend to fix this job, rather than remove it. We can talk offline what this job is supposed to be doing and why we may want it to pass.
This needs to be sorted out first before updating sycl-mlir config I suppose.

**Pull request merged**
