### PR TITLE
[OpenCL] Update Interpreter to support OpenCL CPU test

### PR DESCRIPTION
**Pull request by cdai2**
We will revert this change once we resolve the dependency on NEAT.

### CODE REVIEW

**Comment by asudarsa** [comment]
Hi @cdai2 

Not sure if dpcpp-tools can review this. Sorry. Adding @andykaylor and @stdale-intel for any inputs here.

Thanks

**Review by bader — APPROVED** [review]
Please, create an issue to revert these changes in the future.

**Comment by cdai2** [comment]
@bader  I created https://github.com/intel/llvm/issues/7988.  Please help to assign it to me.  
It seems I and some of our team members cannot add reviewer for PR and I cannot set assignee of issues for intel/llvm .  Do know know whether we need to apply for some access privileges?

**Comment by bader** [comment]
> Do know know whether we need to apply for some access privileges?

I can help you with that. Please, send me the list of github ids who need access.

**Pull request merged**
