### PR TITLE
[SYCL][Bindless] Fix incorrect mangling of bindless images builtin functions

### LINKED ISSUE #15727: CoordT type deduction issue in __invoke__ImageReadSampler
### Describe the bug

Somehow we are generating _Z30__spirv_ImageSampleExplicitLodImDv4_DF16_Dv3_fET0_T_T1_iS4_S4_ with <4 x float> instead of <3 x float> .

This can be reproduced with sycl code, exposed by pulldown in https://github.com/intel/llvm/actions/runs/11357226781/job/31590025233
```

# bin//clang++ -Werror -fsycl -fsycl-targets=nvptx64-nvidia-cuda /localdisk2/jinsongj/llvmspirpd/llvm/sycl/test-e2e/bindless_images/mipmap/mipmap_read_3D.cpp -nocudalib -save-temps -v
# bin/llvm-dis mipmap_read_3D-sycl-nvptx64-nvidia-cuda-sm_50-cd6dcf_0.bc

# grep _Z30__spirv_ImageSampleExplicitLodImDv4_DF16_Dv3_fET0_T_T1_iS4_S4_ mipmap_read_3D-sycl-nvptx64-nvidia-cuda-sm_50-cd6dcf_0.ll
  %call10.i.i = tail call noundef <4 x half> @_Z30__spirv_ImageSampleExplicitLodImDv4_DF16_Dv3_fET0_T_T1_iS4_S4_(i64 noundef %0, <3 x float> noundef %extractVec.i.i.i.i, i32 noundef 4, **<3 x float> noundef zeroinitializer, <3 x float> noundef zeroinitializer**) #2
define internal <4 x half> @_Z30__spirv_ImageSampleExplicitLodImDv4_DF16_Dv3_fET0_T_T1_iS4_S4_(i64 noundef %imageHandle, <3 x float> noundef %coord, i32 %type, **<4 x float> noundef %dX, <4 x float> noundef %dY**) unnamed_addr #4 {


```

### To reproduce

```
FAIL: SYCL :: bindless_images/mipmap/mipmap_read_3D.cpp (2109 of 2212)
******************** TEST 'SYCL :: bindless_images/mipmap/mipmap_read_3D.cpp' FAILED ********************
Exit Code: 1

Command Output (stdout):
--
# RUN: at line 3
/__w/llvm/llvm/toolchain/bin//clang++  -Werror  -fsycl -fsycl-targets=nvptx64-nvidia-cuda  /__w/llvm/llvm/llvm/sycl/test-e2e/bindless_images/mipmap/mipmap_read_3D.cpp -o /__w/llvm/llvm/build-e2e/bindless_images/mipmap/Output/mipmap_read_3D.cpp.tmp.out
# executed command: /__w/llvm/llvm/toolchain/bin//clang++ -Werror -fsycl -fsycl-targets=nvptx64-nvidia-cuda /__w/llvm/llvm/llvm/sycl/test-e2e/bindless_images/mipmap/mipmap_read_3D.cpp -o /__w/llvm/llvm/build-e2e/bindless_images/mipmap/Output/mipmap_read_3D.cpp.tmp.out
# .---command stderr------------
# | clang-20: /__w/llvm/llvm/src/llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp:1484: std::string llvm::NVPTXTargetLowering::getPrototype(const llvm::DataLayout&, llvm::Type*, const ArgListTy&, const llvm::SmallVectorImpl<llvm::ISD::OutputArg>&, llvm::MaybeAlign, std::optional<std::pair<unsigned int, const llvm::APInt&> >, const llvm::CallBase&, unsigned int) const: Assertion `(getValueType(DL, Ty) == Outs[OIdx].VT || (getValueType(DL, Ty) == MVT::i8 && Outs[OIdx].VT == MVT::i16)) && "type mismatch between callee prototype and arguments"' failed.
# | PLEASE submit a bug report to https://github.com/intel/llvm/issues and include the crash backtrace, preprocessed source, and associated run script.
# | Stack dump:
# | 0.	Program arguments: /__w/llvm/llvm/toolchain/bin/clang-20 -cc1 -triple nvptx64-nvidia-cuda -aux-triple x86_64-unknown-linux-gnu -fsycl-is-device -fdeclare-spirv-builtins -fenable-sycl-dae -Wno-sycl-strict -O2 -fsycl-int-header=/tmp/lit-tmp-s_c_xo31/mipmap_read_3D-header-668b69.h -fsycl-int-footer=/tmp/lit-tmp-s_c_xo31/mipmap_read_3D-footer-569101.h -sycl-std=2020 -fsycl-unique-prefix=uid1cf3f836aa84c2f5 -D__SYCL_TARGET_NVIDIA_GPU_SM_50__ -D__SYCL_ANY_DEVICE_HAS_ANY_ASPECT__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_intel_device_id__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_intel_device_info_uuid__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_intel_free_memory__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_intel_max_mem_bandwidth__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_intel_memory_bus_width__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_intel_memory_clock_rate__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_intel_pci_address__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_ballot_group__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_bindless_images__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_bindless_images_1d_usm__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_bindless_images_2d_usm__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_bindless_images_shared_usm__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_cubemap__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_cubemap_seamless_filtering__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_external_memory_import__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_external_semaphore_import__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_fixed_size_group__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_graph__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_image_array__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_limited_graph__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_mipmap__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_mipmap_anisotropy__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_mipmap_level_reference__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_native_assert__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_opportunistic_group__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_unique_addressing_per_dim__=1 -D__SYCL_ALL_DEVICES_HAVE_fp64__=1 -D__SYCL_ALL_DEVICES_HAVE_gpu__=1 -D__SYCL_ALL_DEVICES_HAVE_online_compiler__=1 -D__SYCL_ALL_DEVICES_HAVE_online_linker__=1 -D__SYCL_ALL_DEVICES_HAVE_queue_profiling__=1 -D__SYCL_ALL_DEVICES_HAVE_usm_atomic_host_allocations__=1 -D__SYCL_ALL_DEVICES_HAVE_usm_atomic_shared_allocations__=1 -D__SYCL_ALL_DEVICES_HAVE_usm_device_allocations__=1 -D__SYCL_ALL_DEVICES_HAVE_usm_host_allocations__=1 -D__SYCL_ALL_DEVICES_HAVE_usm_shared_allocations__=1 -D__SYCL_ALL_DEVICES_HAVE_usm_system_allocations__=1 -S -dumpdir /__w/llvm/llvm/build-e2e/bindless_images/mipmap/Output/mipmap_read_3D.cpp.tmp.out- -disable-free -clear-ast-before-backend -main-file-name mipmap_read_3D.cpp -mrelocation-model static -mframe-pointer=all -ffp-contract=on -fno-rounding-math -no-integrated-as -aux-target-cpu x86-64 -internal-isystem /__w/llvm/llvm/toolchain/bin/../include/sycl/stl_wrappers -internal-isystem /__w/llvm/llvm/toolchain/bin/../include -mlink-builtin-bitcode /__w/llvm/llvm/toolchain/lib/clang/20/../../clc/remangled-l64-signed_char.libspirv-nvptx64-nvidia-cuda.bc -mlink-builtin-bitcode /usr/local/cuda-12.1/nvvm/libdevice/libdevice.10.bc -target-sdk-version=12.1 -target-cpu sm_50 -target-feature +ptx81 -debugger-tuning=gdb -fno-dwarf-directory-asm -fdebug-compilation-dir=/__w/llvm/llvm/build-e2e/bindless_images/mipmap -resource-dir /__w/llvm/llvm/toolchain/lib/clang/20 -Werror -ferror-limit 19 -fgpu-rdc -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -o /tmp/lit-tmp-s_c_xo31/mipmap_read_3D-sm_50-bb2bf1-4b514a.s -x ir /tmp/lit-tmp-s_c_xo31/mipmap_read_3D-sm_50-100a11_0.bc
# | 1.	Code generation
# | 2.	Running pass 'Function Pass Manager' on module '/tmp/lit-tmp-s_c_xo31/mipmap_read_3D-sm_50-100a11_0.bc'.
# | 3.	Running pass 'NVPTX DAG->DAG Pattern Instruction Selection' on function '@_ZTS6kernelIN4sycl3_V16detail9half_impl4halfELNS1_18image_channel_typeE13EE'
# | Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
# | 0  clang-20  0x00005602840cd3a0 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + [24](https://github.com/intel/llvm/actions/runs/11357226781/job/31590025233#step:22:25)0
# | 1  clang-20  0x00005602840ca7af llvm::sys::RunSignalHandlers() + 47
# | 2  clang-20  0x00005602840ca905
# | 3  libc.so.6 0x00007efd8c2c9520
# | 4  libc.so.6 0x00007efd8c31d9fc pthread_kill + 300
# | 5  libc.so.6 0x00007efd8c2c9476 raise + 22
# | 6  libc.so.6 0x00007efd8c2af7f3 abort + 211
# | 7  libc.so.6 0x00007efd8c2af71b
# | 8  libc.so.6 0x00007efd8c2c0e96
# | 9  clang-20  0x00005602822ba07f
# | 10 clang-20  0x00005602822c3714
# | 11 clang-20  0x0000560285381e79 llvm::TargetLowering::LowerCallTo(llvm::TargetLowering::CallLoweringInfo&) const + 9577
# | 12 clang-20  0x000056028538c737 llvm::SelectionDAGBuilder::lowerInvokable(llvm::TargetLowering::CallLoweringInfo&, llvm::BasicBlock const*) + 247
# | 13 clang-20  0x00005602853a5acc llvm::SelectionDAGBuilder::LowerCallTo(llvm::CallBase const&, llvm::SDValue, bool, bool, llvm::BasicBlock const*, llvm::TargetLowering::PtrAuthInfo const*) + 2668
# | 14 clang-20  0x00005602853d2cd0 llvm::SelectionDAGBuilder::visitCall(llvm::CallInst const&) + 1200
# | 15 clang-20  0x00005602853d319f llvm::SelectionDAGBuilder::visit(llvm::Instruction const&) + 175
# | 16 clang-20  0x00005602854651a1 llvm::SelectionDAGISel::SelectBasicBlock(llvm::ilist_iterator_w_bits<llvm::ilist_detail::node_options<llvm::Instruction, true, false, void, true, llvm::BasicBlock>, false, true>, llvm::ilist_iterator_w_bits<llvm::ilist_detail::node_options<llvm::Instruction, true, false, void, true, llvm::BasicBlock>, false, true>, bool&) + 161
# | 17 clang-20  0x0000560285466[25](https://github.com/intel/llvm/actions/runs/11357226781/job/31590025233#step:22:26)b llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) + 3755
# | 18 clang-20  0x0000560285467917 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) + 231
# | 19 clang-20  0x00005602854582a9 llvm::SelectionDAGISelLegacy::runOnMachineFunction(llvm::MachineFunction&) + 185
# | 20 clang-20  0x00005602833cb887
# | 21 clang-20  0x0000560283a00d47 llvm::FPPassManager::runOnFunction(llvm::Function&) + 1111
# | 22 clang-20  0x0000560283a01199 llvm::FPPassManager::runOnModule(llvm::Module&) + 57
# | 23 clang-20  0x0000560283a01b51 llvm::legacy::PassManagerImpl::run(llvm::Module&) + 1201
# | 24 clang-20  0x0000560284377ac8 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>, clang::BackendConsumer*) + 5416
# | 25 clang-20  0x0000560284a4b234 clang::CodeGenAction::ExecuteAction() + 3684
# | [26](https://github.com/intel/llvm/actions/runs/11357226781/job/31590025233#step:22:27) clang-20  0x0000560284d7ed99 clang::FrontendAction::Execute() + 201
# | [27](https://github.com/intel/llvm/actions/runs/11357226781/job/31590025233#step:22:28) clang-20  0x0000560284cf4015 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 1189
# | [28](https://github.com/intel/llvm/actions/runs/11357226781/job/31590025233#step:22:29) clang-20  0x0000560284e607b3 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 611
# | [29](https://github.com/intel/llvm/actions/runs/11357226781/job/31590025233#step:22:30) clang-20  0x0000560282285767 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 6967
# | [30](https://github.com/intel/llvm/actions/runs/11357226781/job/31590025233#step:22:31) clang-20  0x000056028227cb7a
# | 31 clang-20  0x000056028228102b clang_main(int, char**, llvm::ToolContext const&) + 4715
# | 32 clang-20  0x0000560282198fbb main + 107
# | 33 libc.so.6 0x00007efd8c2b0d90
# | 34 libc.so.6 0x00007efd8c2b0e40 __libc_start_main + 128
# | 35 clang-20  0x000056028227c2a5 _start + 37
# | llvm-foreach: Aborted (core dumped)
# | clang-20: /__w/llvm/llvm/src/llvm/lib/Target/NVPTX/NVPTXISelLowering.cpp:1484: std::string llvm::NVPTXTargetLowering::getPrototype(const llvm::DataLayout&, llvm::Type*, const ArgListTy&, const llvm::SmallVectorImpl<llvm::ISD::OutputArg>&, llvm::MaybeAlign, std::optional<std::pair<unsigned int, const llvm::APInt&> >, const llvm::CallBase&, unsigned int) const: Assertion `(getValueType(DL, Ty) == Outs[OIdx].VT || (getValueType(DL, Ty) == MVT::i8 && Outs[OIdx].VT == MVT::i16)) && "type mismatch between callee prototype and arguments"' failed.
# | PLEASE submit a bug report to https://github.com/intel/llvm/issues and include the crash backtrace, preprocessed source, and associated run script.
# | Stack dump:
# | 0.	Program arguments: /__w/llvm/llvm/toolchain/bin/clang-20 -cc1 -triple nvptx64-nvidia-cuda -aux-triple x86_64-unknown-linux-gnu -fsycl-is-device -fdeclare-spirv-builtins -fenable-sycl-dae -Wno-sycl-strict -O2 -fsycl-int-header=/tmp/lit-tmp-s_c_xo[31](https://github.com/intel/llvm/actions/runs/11357226781/job/31590025233#step:22:32)/mipmap_read_3D-header-668b69.h -fsycl-int-footer=/tmp/lit-tmp-s_c_xo31/mipmap_read_3D-footer-569101.h -sycl-std=2020 -fsycl-unique-prefix=uid1cf3f836aa84c2f5 -D__SYCL_TARGET_NVIDIA_GPU_SM_50__ -D__SYCL_ANY_DEVICE_HAS_ANY_ASPECT__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_intel_device_id__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_intel_device_info_uuid__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_intel_free_memory__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_intel_max_mem_bandwidth__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_intel_memory_bus_width__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_intel_memory_clock_rate__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_intel_pci_address__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_ballot_group__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_bindless_images__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_bindless_images_1d_usm__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_bindless_images_2d_usm__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_bindless_images_shared_usm__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_cubemap__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_cubemap_seamless_filtering__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_external_memory_import__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_external_semaphore_import__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_fixed_size_group__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_graph__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_image_array__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_limited_graph__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_mipmap__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_mipmap_anisotropy__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_mipmap_level_reference__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_native_assert__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_opportunistic_group__=1 -D__SYCL_ALL_DEVICES_HAVE_ext_oneapi_unique_addressing_per_dim__=1 -D__SYCL_ALL_DEVICES_HAVE_fp64__=1 -D__SYCL_ALL_DEVICES_HAVE_gpu__=1 -D__SYCL_ALL_DEVICES_HAVE_online_compiler__=1 -D__SYCL_ALL_DEVICES_HAVE_online_linker__=1 -D__SYCL_ALL_DEVICES_HAVE_queue_profiling__=1 -D__SYCL_ALL_DEVICES_HAVE_usm_atomic_host_allocations__=1 -D__SYCL_ALL_DEVICES_HAVE_usm_atomic_shared_allocations__=1 -D__SYCL_ALL_DEVICES_HAVE_usm_device_allocations__=1 -D__SYCL_ALL_DEVICES_HAVE_usm_host_allocations__=1 -D__SYCL_ALL_DEVICES_HAVE_usm_shared_allocations__=1 -D__SYCL_ALL_DEVICES_HAVE_usm_system_allocations__=1 -S -dumpdir /__w/llvm/llvm/build-e2e/bindless_images/mipmap/Output/mipmap_read_3D.cpp.tmp.out- -disable-free -clear-ast-before-backend -main-file-name mipmap_read_3D.cpp -mrelocation-model static -mframe-pointer=all -ffp-contract=on -fno-rounding-math -no-integrated-as -aux-target-cpu x86-64 -internal-isystem /__w/llvm/llvm/toolchain/bin/../include/sycl/stl_wrappers -internal-isystem /__w/llvm/llvm/toolchain/bin/../include -mlink-builtin-bitcode /__w/llvm/llvm/toolchain/lib/clang/20/../../clc/remangled-l64-signed_char.libspirv-nvptx64-nvidia-cuda.bc -mlink-builtin-bitcode /usr/local/cuda-12.1/nvvm/libdevice/libdevice.10.bc -target-sdk-version=12.1 -target-cpu sm_50 -target-feature +ptx81 -debugger-tuning=gdb -fno-dwarf-directory-asm -fdebug-compilation-dir=/__w/llvm/llvm/build-e2e/bindless_images/mipmap -resource-dir /__w/llvm/llvm/toolchain/lib/clang/20 -Werror -ferror-limit 19 -fgpu-rdc -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -o /tmp/lit-tmp-s_c_xo31/mipmap_read_3D-sm_50-bb2bf1-146402.s -x ir /tmp/lit-tmp-s_c_xo31/mipmap_read_3D-sm_50-100a11_1.bc
# | 1.	Code generation
# | 2.	Running pass 'Function Pass Manager' on module '/tmp/lit-tmp-s_c_xo31/mipmap_read_3D-sm_50-100a11_1.bc'.
# | 3.	Running pass 'NVPTX DAG->DAG Pattern Instruction Selection' on function '@_ZTS6kernelIiLN4sycl3_V118image_channel_typeE9EE'
# | Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
# | 0  clang-20  0x0000564d197da3a0 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 240
# | 1  clang-20  0x0000564d197d77af llvm::sys::RunSignalHandlers() + 47
# | 2  clang-20  0x0000564d197d7905
# | 3  libc.so.6 0x00007f16ba56a520
# | 4  libc.so.6 0x00007f16ba5be9fc pthread_kill + 300
# | 5  libc.so.6 0x00007f16ba56a476 raise + 22
# | 6  libc.so.6 0x00007f16ba5507f3 abort + 211
# | 7  libc.so.6 0x00007f16ba55071b
# | 8  libc.so.6 0x00007f16ba561e96
# | 9  clang-20  0x0000564d179c707f
# | 10 clang-20  0x0000564d179d0714
# | 11 clang-20  0x0000564d1aa8ee79 llvm::TargetLowering::LowerCallTo(llvm::TargetLowering::CallLoweringInfo&) const + 9577
# | 12 clang-20  0x0000564d1aa99737 llvm::SelectionDAGBuilder::lowerInvokable(llvm::TargetLowering::CallLoweringInfo&, llvm::BasicBlock const*) + 247
# | 13 clang-20  0x0000564d1aab2acc llvm::SelectionDAGBuilder::LowerCallTo(llvm::CallBase const&, llvm::SDValue, bool, bool, llvm::BasicBlock const*, llvm::TargetLowering::PtrAuthInfo const*) + 2668
# | 14 clang-20  0x0000564d1aadfcd0 llvm::SelectionDAGBuilder::visitCall(llvm::CallInst const&) + 1200
# | 15 clang-20  0x0000564d1aae019f llvm::SelectionDAGBuilder::visit(llvm::Instruction const&) + 175
# | 16 clang-20  0x0000564d1ab721a1 llvm::SelectionDAGISel::SelectBasicBlock(llvm::ilist_iterator_w_bits<llvm::ilist_detail::node_options<llvm::Instruction, true, false, void, true, llvm::BasicBlock>, false, true>, llvm::ilist_iterator_w_bits<llvm::ilist_detail::node_options<llvm::Instruction, true, false, void, true, llvm::BasicBlock>, false, true>, bool&) + 161
# | 17 clang-20  0x0000564d1ab7[32](https://github.com/intel/llvm/actions/runs/11357226781/job/31590025233#step:22:33)5b llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) + 3755
# | 18 clang-20  0x0000564d1ab74917 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) + 231
# | 19 clang-20  0x0000564d1ab652a9 llvm::SelectionDAGISelLegacy::runOnMachineFunction(llvm::MachineFunction&) + 185
# | 20 clang-20  0x0000564d18ad8887
# | 21 clang-20  0x0000564d1910dd47 llvm::FPPassManager::runOnFunction(llvm::Function&) + 1111
# | 22 clang-20  0x0000564d1910e199 llvm::FPPassManager::runOnModule(llvm::Module&) + 57
# | 23 clang-20  0x0000564d1910eb51 llvm::legacy::PassManagerImpl::run(llvm::Module&) + 1201
# | 24 clang-20  0x0000564d19a84ac8 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>, clang::BackendConsumer*) + 5416
# | 25 clang-20  0x0000564d1a158234 clang::CodeGenAction::ExecuteAction() + 3684
# | 26 clang-20  0x0000564d1a48bd99 clang::FrontendAction::Execute() + 201
# | 27 clang-20  0x0000564d1a401015 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 1189
# | 28 clang-20  0x0000564d1a56d7b3 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 611
# | 29 clang-20  0x0000564d17992767 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 6967
# | 30 clang-20  0x0000564d17989b7a
# | 31 clang-20  0x0000564d1798e02b clang_main(int, char**, llvm::ToolContext const&) + 4715
# | 32 clang-20  0x0000564d178a5fbb main + 107
# | [33](https://github.com/intel/llvm/actions/runs/11357226781/job/31590025233#step:22:34) libc.so.6 0x00007f16ba551d90
# | 34 libc.so.6 0x00007f16ba551e40 __libc_start_main + 128
# | 35 clang-20  0x0000564d179892a5 _start + 37
# | llvm-foreach: Aborted (core dumped)
# | clang++: error: clang frontend command failed with exit code 254 (use -v to see invocation)
# | clang version 20.0.0git (https://github.com/intel/llvm 488dab14e2064953dba634418dc4463a55d57ea5)
# | Target: x86_64-unknown-linux-gnu
# | Thread model: posix
# | InstalledDir: /__w/llvm/llvm/toolchain/bin
# | Build config: +assertions
# | clang++: note: diagnostic msg: Error generating preprocessed source(s).
# `-----------------------------
# error: command failed with exit status: 1

--

********************
```

### Environment

- OS: [e.g Windows/Linux]
- Target device and vendor: [e.g. Intel GPU]
- DPC++ version: [e.g. commit hash or output of `clang++ --version`]
- Dependencies version: [e.g. the output of `sycl-ls --verbose`]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DBDuncan**
The mipmap builtin functions were incorrectly defined in the CUDA backend as having dX and dY argument of 4 elements when 3 is expected. This flew under the radar until a recent pull from upstream LLVM. In addition, an incorrect 'fetch_vec_size' type had been fixed when generating thunk mipmap builtins. 'mipmap_read_3D.cpp' test re-enable.

Fixes #15727

### CODE REVIEW

**Comment by frasercrmck** [comment]
Could you explain the problem in more detail? I assume that it's a problem with the `__spirv_ImageSampleExplicitLod*` builtin declarations? I was checking these against the SPIR-V specification, but I found that `OpImageSampleExplicitLod` says that the coordinate operands can be of a larger vector type:

``` quote
Coordinate must be a scalar or vector of floating-point typeor integer type.
It contains (u[, v] …​ [, array layer]) as needed by the definition of Sampled Image.
Unless the Kernel capability is declared, it must be floating point. It may be a vector
larger than needed, but all unused components appear after all used components.
```

So it doesn't sound like invalid SPIR-V, per se. So it's more that it's a breach of contract between two parts of the code base - libclc and something else?

The PR description should also say that it fixes #15727.

**Comment by DBDuncan** [comment]
Hey. Sorry. My explanation was not clear enough. There was a change a while ago to update the type used to pass coords for 3d images from a vec of size 4 to a vec of size 3. (I can't remember why it was 4 in the first place. The last element was never used.) Problem is that the templating in `sample_mipmap` itself uses `CoordT` for dX and dY. Which is fine but the mipmap builtins expected dx and dy to be vecs of 4 elements and not 3 for 3D mipmap images.

This mismatch did not cause any problems until a pull down from upstream llvm a while ago. So this updates the builtin mangling to fix this. Also, the changes here only relate the CUDA backend. Intel devices which do use SPIR-V and L0 do not support mipmaps currently as they are not supported in L0. 

There is a funny dichotomy going on with libspirv being used to generate ptx. So I think it would be strange for the SPIR-V spec to matter here? I am not sure about how exactly the ptx instruction pipeline works here.

Oh and good shout to link to the issue this fixes!

**Review by frasercrmck — APPROVED** [review]

**Review by ProGTX — APPROVED** [review]

**Comment by DBDuncan** [comment]
@omarahmed1111 Friendly ping

**Comment by DBDuncan** [comment]
@intel/llvm-gatekeepers Please merge

**Pull request merged**
