### PR TITLE
[SYCL] Enable inline asm tests in check-sycl

### PR DESCRIPTION
**Pull request by AlexeySachkov**

### CODE REVIEW

**Comment by olegmaslovatintel** [comment]
@AlexeySachkov what's the plan to commit? When is it planned?

**Comment by AlexeySachkov** [comment]
> @AlexeySachkov what's the plan to commit? When is it planned?

I cannot commit until NEO/IGC is fixed. The last good known is 20.19, all newer versions (up to the latest 20.26) doesn't work with inline asm anymore

**Comment by AlexeySachkov** [comment]
`clang-format` suggest breaking inline-asm string into two and I would like to avoid that for the sake of readability

`Lit_With_Cuda` fails because of infra issue: the machine it is launched on has outdated version of cmake installed
`sycl-win-x64-pr` doesn't seem to be related to this PR: there are several LLVM LIT tests failed

**Comment by bader** [comment]
> `Lit_With_Cuda` fails because of infra issue: the machine it is launched on has outdated version of cmake installed
> `sycl-win-x64-pr` doesn't seem to be related to this PR: there are several LLVM LIT tests failed

@tfzhu, @yinyangsx, we need to fix these issues to avoid unrelated failures. Could you help with that, please?

**Comment by yinyangsx** [comment]
> fix

**Comment by yinyangsx** [comment]
Sorry, my bad, I closed this PR by mistake.
>> Lit_With_Cuda fails because of infra issue: the machine it is launched on has outdated version of cmake installed
Cmake version issue already fixed.

**Pull request merged**
