### PR TITLE
[NFC][SYCL] Remove XFAIL: gpu from SPVCooperativeMatrix tests

### PR DESCRIPTION
**Pull request by MrSidims**
8730002 adds W/A fixing them.

### CODE REVIEW

**Review by YuriPlyakhin — APPROVED** [review]

**Comment by MrSidims** [comment]
Actually, need to un-xfail more tests

**Comment by MrSidims** [comment]
@intel/llvm-gatekeepers please help with the merge

**Comment by MrSidims** [comment]
XFAILed 2 tests back. Ideally I need to add REQUIRES: *intel-driver-version* for for these 2 tests, but right now I'm having troubles with mapping of my IGC patch to neo driver version. So leaving as is no unblocking post-commit, will put REQUIRES string in a separate PR.

**Comment by sarnex** [comment]
@MrSidims Are we confident the current version of the change will pass in postcommit?

(Ideally we should have run postcommit in precommit, but since CI is already broken IMO we can merge with a precommit pass and monitor it)

**Review by asudarsa — COMMENTED** [review]
Just curious. Do these tests not run during the pre-commit testing? Sorry for ignorant question. Thanks

**Comment by MrSidims** [comment]
@sarnex I don't mind to run post-commit if it's possible

@asudarsa TBH I have hard times understanding difference between pre-commit and post-commit, but these tests are being run, see https://github.com/intel/llvm/actions/runs/10701548352/job/29678052739?pr=15272

**Comment by sarnex** [comment]
We run limited testing in precommit on DG2, my understanding is it's due to resource limitations.

**Comment by MrSidims** [comment]
@sarnex post commit has passed on Arc platform. GEN12 has failed, but I doubt it's related to the patch

**Comment by sarnex** [comment]
@MrSidims Ok I'll merge this and watch postcommit. Thanks

**Pull request merged**
