### PR TITLE
[SYCL][CUDA] Fix a test which assumed build on Linux machines.

### PR DESCRIPTION
**Pull request by mmoadeli**
Fix a test which assumed build on Linux machines.

### CODE REVIEW

**Comment by mmoadeli** [comment]
@pvchupin would you please be able to run tests on this PR.

**Comment by mmoadeli** [comment]
@pvchupin, 
would you please be able to run CI on a Windows machine for this PR.

**Review by mdtoguchi — APPROVED** [review]
LGTM

**Comment by mmoadeli** [comment]
This PR fixes the issue seen in 
https://github.com/intel/llvm/pull/7348

**Comment by pvchupin** [comment]
@mmoadeli, there are still problems. Can you take a look?
https://github.com/intel/llvm/actions/runs/3678070586/jobs/6220866632

**Comment by mmoadeli** [comment]
> @mmoadeli, there are still problems. Can you take a look? https://github.com/intel/llvm/actions/runs/3678070586/jobs/6220866632

@pvchupin Sorry, was that it would be possible to run this PR on CI machine without the need for merge.
The tested PR is  https://github.com/intel/llvm/pull/7753

**Comment by pvchupin** [comment]
@mmoadeli, windows testing is in post-commit, if you are checking change locally usually it's enough, otherwise (if you don't have a local windows box) there is a trick is to add a dummy change to post-commit job so that post-commit is triggered in pre-commit, then revert it back before merge.

**Pull request merged**
