### PR TITLE
[SYCL][libdevice] Move fabs, fabs to imf_fp32/64_dl.cpp and add llabs

### PR DESCRIPTION
**Pull request by jinge90**
fabsf, fabs and llabs are required by deep learning frameworks, so we move fabsf and fabs to separate file imf_fp32/64_dl.cpp and add llabs to imf_fp32_dl.cpp as well.

### CODE REVIEW

**Comment by jinge90** [comment]
Hi, @akolesov-intel, @zettai-reido and @xtian-github 
fabs, fabsf and llabs are required by deep learning framework, please help review this PR.
Thanks very much.

**Review by xtian-github — APPROVED** [review]
LGTM. .Thanks.

**Comment by jinge90** [comment]
Hi, @intel/llvm-reviewers-runtime and @intel/dpcpp-tools-reviewers 
Could you help review this patch?
Thanks very much.

**Review by steffenlarsen — APPROVED** [review]
SYCL runtime changes LGTM.

**Comment by jinge90** [comment]
Hi, @intel/llvm-gatekeepers 
Could you help review and merge this patch?
Thanks very much.

**Pull request merged**
