### PR TITLE
[SYCL][CUDA] Bug fix: non-uniform work-groups error on CUDA

### PR DESCRIPTION
**Pull request by huanghua1994**
Bug fix for issue https://github.com/intel/llvm/issues/2821

### CODE REVIEW

**Review by alexbatashev — COMMENTED** [review]
LGTM, but I'd like @v-klochkov to review

**Comment by bader** [comment]
@huanghua1994, could add a regression test following [this guide](https://intel.github.io/llvm-docs/GetStartedGuide.html#test-dpc-toolchain), please?

**Comment by huanghua1994** [comment]
@bader  Sure, will do

**Comment by huanghua1994** [comment]
Tested on vs-sycl-2.hd.intel.com.
Configuration: `python3 buildbot/configure.py --cuda`
Compiling: `python3 buildbot/compile.py`
Testing: `python3 buildbot/check.py`

Test results:
  Unsupported      : 17902
  Passed           : 51284
  Expectedly Failed:    86

**Comment by bader** [comment]
Sorry for confusion. What I meant is that we should add a new regression test to validate that issue #2821 is fixed.
We have CI system, which runs existing regression tests to verify that new patches do not break existing functionality.
I'd like to have a similar test covering non-uniform work-groups on CUDA.

**Comment by v-klochkov** [comment]
Hi, I am in process of debugging a bit bigger and more complete patch for exactly same issue. The intention was to upload it for review yesterday, but the new LIT test added by me there showed some new unexpected issues with work-group size for Aux kernels with reductions. I'll take some more time to analyze it.

**Comment by v-klochkov** [comment]
I uploaded a fix that includes similar code as this patch, but is a bit bigger patch and includes a LIT test: https://github.com/intel/llvm/pull/2859

**Comment by huanghua1994** [comment]
@v-klochkov Thanks! That's a better fix and should be merged. @Pennycook please review Vyecheslav's PR first, and close my PR after passing his PR.

**Comment by bader** [comment]
The bug is fixed by https://github.com/intel/llvm/pull/2859.

**Pull request closed without merging**
