### PR TITLE
[SYCL][NewPM] Add SYCLLowerWGLocalMemory pass into optimization

### PR DESCRIPTION
**Pull request by mlychkov**
Add SYCLLowerWGLocalMemory pass into clang optimizations pipeline when using
new Pass Manager.

Signed-off-by: Mikhail Lychkov <mikhail.lychkov@intel.com>

### CODE REVIEW

**Review by smanna12 — DISMISSED** [review]

**Review by smanna12 — APPROVED** [review]

**Review by AlexeySachkov — APPROVED** [review]

**Comment by AlexeySachkov** [comment]
@intel/llvm-reviewers-runtime, could you please take a look at this PR? The only runtime change here is a small adjustment to a LIT test

**Review by steffenlarsen — APPROVED** [review]
Runtime changes LGTM!

**Comment by bader** [comment]
@mlychkov, this change broke (already broken ;)) build of shared libraries with clang. 

/usr/bin/ld: lib/Target/NVPTX/CMakeFiles/LLVMNVPTXCodeGen.dir/NVPTXTargetMachine.cpp.o: in function `LLVMInitializeNVPTXTarget':
NVPTXTargetMachine.cpp:(.text.LLVMInitializeNVPTXTarget+0x86): undefined reference to `llvm::initializeLocalAccessorToSharedMemoryPass(llvm::PassRegistry&)'

Looks like a missing dependency in cmake files.

**Comment by bader** [comment]
@mlychkov corrected me this issue appeared after https://github.com/intel/llvm/commit/58508ba3158ab83e8c277677f8613f76344f67a6.
@jchlanda, could you take a look, please?

**Comment by jchlanda** [comment]
> @mlychkov corrected me this issue appeared after [58508ba](https://github.com/intel/llvm/commit/58508ba3158ab83e8c277677f8613f76344f67a6). @jchlanda, could you take a look, please?

@bader I might not get to it, as it's my last day before holiday, please feel free to revert [58508ba](https://github.com/intel/llvm/commit/58508ba3158ab83e8c277677f8613f76344f67a6 if it's to blame and I'll look into it in a week's time, sorry.

**Comment by bader** [comment]
Okay. I think it's the issue as reported here - https://github.com/intel/llvm/commit/58508ba3158ab83e8c277677f8613f76344f67a6#commitcomment-64254777.
I'll try to look into it myself and if I'm unable to figure it out, I'll revert the commit.

**Comment by jchlanda** [comment]
> @mlychkov corrected me this issue appeared after [58508ba](https://github.com/intel/llvm/commit/58508ba3158ab83e8c277677f8613f76344f67a6). @jchlanda, could you take a look, please?

Should be fixed in: https://github.com/intel/llvm/pull/5357

**Pull request merged**
