### PR TITLE
[SYCL][ESIMD] Remove tests migrated to llvm-test-suite

### PR DESCRIPTION
**Pull request by vladimirlaz**
The tests have been submitted in scope of https://github.com/intel/llvm-test-suite/pull/29

### CODE REVIEW

**Review by bader — APPROVED** [review]
LGTM, although I'm not sure if we should leave a README file or remove it together with the tests.

**Comment by kbobrovs** [comment]
@vladimirlaz, @bader - will ESIMD tests in the new place still be run as part of CI testing (buildbot/sycl-*-64-pr)?

**Comment by vladimirlaz** [comment]
> @vladimirlaz, @bader - will ESIMD tests in the new place still be run as part of CI testing (buildbot/sycl-*-64-pr)?

They are run as part of post-commit and Jenkins/Summary (when /summary:run comment is added). Potentially we can request executing them for every pre-commit testing. But it may be too expensive once more heavy tests will be added to llvm-test-suite.

**Comment by kbobrovs** [comment]
We really need ESIMD tests to run as a part of pre-commit CI, at least several of them.

**Comment by vladimirlaz** [comment]
https://github.com/intel/llvm/tree/sycl/sycl/test/esimd are still preserved in pre-checkin.

**Review by kbobrovs — APPROVED** [review]

**Review by againull — APPROVED** [review]

**Pull request merged**
