### PR TITLE
[SYCL][L0] Force push of driver update in case there is a stale branch

### PR DESCRIPTION
**Pull request by smaslov-intel**

### CODE REVIEW

**Review by bader — CHANGES_REQUESTED** [review]
I don't think this is a good idea.
If branch exists already, it means that PR is already created.
Doing force-push doesn't fix pre-commit checks. Usually new driver does i.e. another PR.
In case when the problem is with DPC++, it's better to do manual update than wait for another week for action to force-push the same patch to re-trigger testing with the tip of the `sycl` branch.

**Comment by smaslov-intel** [comment]
> Doing force-push doesn't fix pre-commit checks.

The force-push is 1 week later, so it is very likely that the testing is fixed with the changes during this week.

**Comment by bader** [comment]
> > Doing force-push doesn't fix pre-commit checks.
> 
> The force-push is 1 week later, so it is very likely that the testing is fixed with the changes during this week.

Based on previous experience, it's very unlikely. The GPU driver has not been updated since September of 2022 due to regressions in CI. It's more than 1 week.

**Comment by smaslov-intel** [comment]
> > > Doing force-push doesn't fix pre-commit checks.
> > 
> > 
> > The force-push is 1 week later, so it is very likely that the testing is fixed with the changes during this week.
> 
> Based on previous experience, it's very unlikely. The GPU driver has not been updated since September of 2022 due to regressions in CI. It's more than 1 week.

Can we then remove the branch created from an attempt that failed? It really is a stale one, no?

**Comment by bader** [comment]
CI creates a new branch for a new driver, so if branch is already created, it's created for the latest available version.

**Comment by smaslov-intel** [comment]
> CI creates a new branch for a new driver, so if branch is already created, it's created for the latest available version.

That I understand. But why keep a branch that failed to get integrated (for whatever reason)?

**Comment by bader** [comment]
> > CI creates a new branch for a new driver, so if branch is already created, it's created for the latest available version.
> 
> That I understand. But why keep a branch that failed to get integrated (for whatever reason)?

For someone who wants to fix failures.

**Pull request closed without merging**
