### PR TITLE
[SYCL] Add DPAS of PVC query and other improvements:

### PR DESCRIPTION
**Pull request by dkhaldi**
- Remove dynamic_p from the query since dynamic extent of the sizes is not supported
- Add xmx16 to the list of TPUs. This is the PVC TPU 
- Change float19 to tf32 
- Extend scope to return more than one value

### CODE REVIEW

**Comment by dkhaldi** [comment]
These changes are part of the doc PR https://github.com/intel/llvm/pull/7307

**Review by mbelicki — APPROVED** [review]
Looks good to me.

**Comment by dkhaldi** [comment]
@intel/llvm-reviewers-runtime, please help approve/merge this.

**Comment by dkhaldi** [comment]
https://github.com/orgs/intel/teams/llvm-reviewers-runtime, please help approve/merge this.

**Comment by dkhaldi** [comment]
@bso-intel, can you please help review/merge this?

**Review by bso-intel — APPROVED** [review]
LGTM
Unfortunately, I don't have merge permission. Sorry.

**Pull request merged**
