### PR TITLE
[BuildBot] Uplift Win GPU driver version to 27.20.100.8935

### PR DESCRIPTION
**Pull request by yinyangsx**
Signed-off-by: yinyangsx <yin.yang@intel.com>

### CODE REVIEW

**Review by vladimirlaz — DISMISSED** [review]
LGTM
But still need to wait until all test passed

**Comment by yinyangsx** [comment]
Hi @yanfeng3721 , a new regression happen on Windows GPU CTS test, could you please have a look? 
http://icl-jenkins.sc.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FWin%2FCTS_GPU/detail/CTS_GPU/1701/pipeline

**Comment by yanfeng3721** [comment]
@yinyangsx @DoyleLi , the regression looks like a flaky issue and I could not reproduce it on nnlocl160. 
image
I would like to rerun the tests. Please help to assign the tests to test machine 160.

**Comment by vladimirlaz** [comment]
@yanfeng3721, @yinyangsx  It looks like the flacky issue introduced by new driver. Please file a ticket.

**Review by vladimirlaz — APPROVED** [review]

**Comment by yanfeng3721** [comment]
@yinyangsx , I checked the post commit test, the Windows test pass, please prepare Windows test driver 27.20.100.8935 update.

**Review by yanfeng3721 — APPROVED** [review]

**Pull request merged**
