### PR TITLE
[Matrix] fix a typo in joint_matrix_tf32.cpp

### PR DESCRIPTION
**Pull request by yubingex007-a11y**

### CODE REVIEW

**Comment by yubingex007-a11y** [comment]
thanks for finding it. @Nuullll

**Review by Nuullll — COMMENTED** [review]
Do you mind also fixing the other two typos?

https://github.com/intel/llvm/blob/3d6917f0b36f8a90c7eec46a72786559d78c8d43/sycl/test-e2e/Matrix/element_wise_all_ops_tf32.cpp#L10

https://github.com/intel/llvm/blob/3d6917f0b36f8a90c7eec46a72786559d78c8d43/sycl/test-e2e/Matrix/XMX8/element_wise_all_ops_tf32.cpp#L10

**Comment by yubingex007-a11y** [comment]
> Do you mind also fixing the other two typos?
> 
> https://github.com/intel/llvm/blob/3d6917f0b36f8a90c7eec46a72786559d78c8d43/sycl/test-e2e/Matrix/element_wise_all_ops_tf32.cpp#L10
> 
> https://github.com/intel/llvm/blob/3d6917f0b36f8a90c7eec46a72786559d78c8d43/sycl/test-e2e/Matrix/XMX8/element_wise_all_ops_tf32.cpp#L10

done

**Review by Nuullll — APPROVED** [review]
LGTM. Thank you.

**Comment by yubingex007-a11y** [comment]
@steffenlarsen can you help us merge it?

**Review by dkhaldi — APPROVED** [review]
LGTM

**Comment by yubingex007-a11y** [comment]
@steffenlarsen can you help us merge it?

**Comment by yubingex007-a11y** [comment]
@cperkinsintel could you help us merge it?

**Comment by steffenlarsen** [comment]
L0 Failed Tests (1):
  SYCL :: Basic/memory-consumption.cpp - Reported in https://github.com/intel/llvm/issues/9008.

ESIMD Emu CI failures are being investigated separately.

**Pull request merged**
