### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW07)

### PR DESCRIPTION
**Pull request by vmaksimo**
LLVM: llvm/llvm-project@1cee9608982a866688434223bee44c878ea489b1
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@a836197d52aced43f49b7f9a2386424ce734acba

### CODE REVIEW

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Fri 11 Feb 2022 01:25:37 PM UTC --- Merge failed with error: PR is not clean for merge. Please examine ci check status before merge.

**Review by bb-sycl — APPROVED** [review]

**Comment by bader** [comment]
> Fri 11 Feb 2022 02:21:36 PM UTC --- Merge failed with error: PR is not clean for merge. Please examine ci check status before merge.

@vmaksimo, you need to merge sycl branch to the pulldown branch and resolve conflicts (if any) before asking for merge.

**Comment by vmaksimo** [comment]
> > Fri 11 Feb 2022 02:21:36 PM UTC --- Merge failed with error: PR is not clean for merge. Please examine ci check status before merge.
> 
> @vmaksimo, you need to merge sycl branch to the pulldown branch and resolve conflicts (if any) before asking for merge.

There is no conflict with the sycl branch, the problem is in the spontaneously restarted CI job.

I wait for all the jobs to be passed and then trigger the automation for merge, but somehow it causes restarting of windows buildbot job - and that fails the merge ability. Seems to be a bug in CI or automation.

**Comment by bader** [comment]
@tfzhu, could you clarify why bb-sycl can't merge this PR, please?

**Comment by bader** [comment]
@vmaksimo, pointed that that buildbot/sycl-ubu-x64-pr must return "success" status to unblock merge.
@alexbatashev, I think we removed this job and replaced it with GHA jobs. Right?

I think the merge script must be updated to comply with new CI checks.

**Comment by alexbatashev** [comment]
> I think we removed this job and replaced it with GHA jobs. Right?

Right

**Pull request merged**
