### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW03)

### PR DESCRIPTION
**Pull request by sys-ce-bb**
LLVM: llvm/llvm-project@110e1717b31e
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@10b0aab

### CODE REVIEW

**Comment by jsji** [comment]
This is ready for review.
- [ ] [Update lit test with new dead_on_unwind/writable attr](https://github.com/intel/llvm/pull/12442/commits/c28044fbaea7b44cd367899d2861032ce6c719d7)  Trivial attribute update .@intel/dpcpp-cfe-reviewers 
- [ ] [Remove XFAIL as fixed by](https://github.com/intel/llvm/pull/12442/commits/69c77fee3738bb4713b6e05a2f3efff4afca7127) https://github.com/intel/llvm/commit/aa23e493f2b363982a472fe38caffc69d907402c @mmoadeli

**Review by smanna12 — APPROVED** [review]
CFE change looks good to me

**Comment by jsji** [comment]
https://github.com/intel/llvm/issues/12455 opened to track the reland of a temporarily revert.

> > > [c28044f](https://github.com/intel/llvm/commit/c28044fbaea7b44cd367899d2861032ce6c719d7)
> 
> CFE change looks good to me

Thanks @smanna12 for review. Are you OK with this follow up as well? Thank you.

**Comment by jsji** [comment]
@bader @intel/llvm-gatekeepers  Can we get this merged? If there is any further review comments, we can always do post-commit follow up. Thanks.

**Comment by smanna12** [comment]
> > #12455 opened to track the reland of a temporarily revert.
> 
> Thanks @smanna12 for review. @premanandrao Are you OK with this follow up as well? Thank you.

I am OK with it.

**Comment by jsji** [comment]
> > > #12455 opened to track the reland of a temporarily revert.
> > 
> > 
> > Thanks @smanna12 for review. @premanandrao Are you OK with this follow up as well? Thank you.
> 
> I am OK with it.

Thanks @smanna12

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Tue 23 Jan 2024 05:56:21 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Tue 23 Jan 2024 06:05:17 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
