### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW18)

### PR DESCRIPTION
**Pull request by againull**
LLVM: https://github.com/llvm/llvm-project/commit/5c9a84960de2260f149ee15313998593255a78df
SPIRV-LLVM-Translator: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/535afc15fd042a87c4e708486f4afaf0bf263f72

### CODE REVIEW

**Review by aelovikov-intel — APPROVED** [review]

**Review by v-klochkov — APPROVED** [review]

**Comment by againull** [comment]
OpenCL Gen9 testing was stuck on Setup job. Tested locally, all tests pass.

$ ninja check-sycl-e2e
[0/1] Running the SYCL tests for check-sycl-e2e-opencl-gpu backend
llvm-lit: /iusers2/againull/sycl/pulldown/llvm/sycl/test-e2e/lit.cfg.py:222: note: Aspects: usm_device_allocations ext_intel_device_id queue_profiling usm_host_allocations gpu online_linker fp64 online_compiler atomic64 ext_oneapi_srgb usm_shared_allocations image fp16 ext_intel_legacy_image
llvm-lit: /iusers2/againull/sycl/pulldown/llvm/sycl/test-e2e/lit.cfg.py:280: note: Backend: opencl
llvm-lit: /iusers2/againull/sycl/pulldown/llvm/sycl/test-e2e/lit.cfg.py:366: warning: CPU device not used
llvm-lit: /iusers2/againull/sycl/pulldown/llvm/sycl/test-e2e/lit.cfg.py:381: note: Test GPU device
llvm-lit: /iusers2/againull/sycl/pulldown/llvm/sycl/test-e2e/lit.cfg.py:429: warning: Accelerator device not used
llvm-lit: /iusers2/againull/sycl/pulldown/llvm/sycl/test-e2e/lit.cfg.py:495: note: Found pre-installed AOT device compiler ocloc
llvm-lit: /iusers2/againull/sycl/pulldown/llvm/sycl/test-e2e/lit.cfg.py:495: note: Found pre-installed AOT device compiler opencl-aot
llvm-lit: /iusers2/againull/sycl/pulldown/llvm/sycl/test-e2e/lit.cfg.py:514: note: Kernel fusion extension enabled

Testing Time: 1004.85s
  Unsupported      : 450
  Passed           : 854
  Expectedly Failed:  23

2 warning(s) in tests

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Fri 05 May 2023 09:02:41 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Fri 05 May 2023 09:07:01 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
