### PR TITLE
[SYCL][ABI-break] Remove host_half_impl::half 

### PR DESCRIPTION
**Pull request by raaiq1**

### CODE REVIEW

**Comment by raaiq1** [comment]
@cperkinsintel  request for review

**Comment by sergey-semenov** [comment]
LGTM overall, but  I think it makes sense to rename `half_v2` to just `half` now that the "v1" version is gone.

**Comment by aelovikov-intel** [comment]
> LGTM overall, but I think it makes sense to rename `half_v2` to just `half` now that the "v1" version is gone.

Would it be cleaner to do that in a separate PR though?

**Comment by raaiq1** [comment]
I agree

**Comment by raaiq1** [comment]
Updated files to rename half_v2 to half

**Review by sergey-semenov — APPROVED** [review]

**Comment by raaiq1** [comment]
CI failure is unrelated to PR: unexpectedly passing tests

**Review by sergey-semenov — APPROVED** [review]

**Review by v-klochkov — APPROVED** [review]

**Pull request merged**
