### PR TITLE
[SYCL] Add __imf_max/min/hadd to imf libdevice

### PR DESCRIPTION
**Pull request by jinge90**
This PR adds 3 trivial functions to imf libdevice:
__imf_max---->__nv_max
__imf_min----->__nv_min
__imf_hadd----->__nv_hadd
Those 3 functions are located in imf_fp32_dl.cpp since some AI frameworks also need them.

### CODE REVIEW

**Comment by jinge90** [comment]
Hi, @zettai-reido and @akolesov-intel
Could you help review this PR?
Thanks very much.

**Review by zettai-reido — APPROVED** [review]
LGTM.

**Review by akolesov-intel — APPROVED** [review]
Thank you!

**Review by againull — APPROVED** [review]

**Comment by jinge90** [comment]
Hi, @intel/dpcpp-tools-reviewers 
Could you help review this patch?

**Review by vmaksimo — APPROVED** [review]

**Pull request merged**
