### PR TITLE
[SYCL][CUDA] Allow joint_matrix to be loaded from const T

### PR DESCRIPTION
**Pull request by JackAKirk**
Fixes a bug where if `joint_matrix_load` attempts to load `joint_matrix` from an array of `const T`incorrect behaviour will occur or an error will be thrown. To fix this we make use of `std::remove_const_t<T>` in appropriate places. This is important functionality for integrating joint_matrix with existing SYCL-DNN routines.
I think that similar problems might occur in the intel backends for their existing impl: I have not made corresponding changes because I do not have the hardware to test it.

Signed-off-by: JackAKirk <jack.kirk@codeplay.com>

### CODE REVIEW

**Review by dkhaldi — APPROVED** [review]
LGTM

**Comment by JackAKirk** [comment]
btw the CUDA test failure is the now XFAIL'ed known flaky test Assert/assert_in_simultaneously_multiple_tus.cpp

**Comment by JackAKirk** [comment]
ping @v-klochkov

**Review by v-klochkov — COMMENTED** [review]
Looks good to me. Thank you.
Before proceeding to merge. Please add a test verifying the test case being fixed by this PR.

If there is an existing test, but it is XFAIL due to being flaky, please add a simpler test or a compile-only test.

**Comment by JackAKirk** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1280

**Comment by JackAKirk** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1280

**Comment by JackAKirk** [comment]
> Looks good to me. Thank you. Before proceeding to merge. Please add a test verifying the test case being fixed by this PR.
> 
> If there is an existing test, but it is XFAIL due to being flaky, please add a simpler test or a compile-only test.

Thanks. I've added all new possible use cases in the test here: https://github.com/intel/llvm-test-suite/pull/1280

**Review by v-klochkov — APPROVED** [review]

**Comment by pvchupin** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1280

**Comment by JackAKirk** [comment]
Can this be merge now?

**Pull request merged**
