### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW49)

### PR DESCRIPTION
**Pull request by vmaksimo**
LLVM: llvm/llvm-project@4709bacf18b4
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@ef0015c775791d57c10d573d1de64b423827a225

### CODE REVIEW

**Review by vladimirlaz — APPROVED** [review]

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Tue Nov 30 08:20:25 UTC 2021 --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Tue Nov 30 08:23:29 UTC 2021 --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
