### PR TITLE
[SYCL][ABI-break] Remove kernel::get_work_group_info

### PR DESCRIPTION
**Pull request by raaiq1**
- Removed template definitions of kernel::get_work_group_info.
- Deleted 'sycl/test/warnings/kernel_wg_info_deprecation.cpp' : which tests for deprecated feature
- Removed a unittest call to such feature and updated linux symbols

### CODE REVIEW

**Comment by steffenlarsen** [comment]
Sweet! Since it is an ABI break we should increment the library engineering version as described in [ABIPolicyGuide](https://github.com/intel/llvm/blob/sycl/sycl/doc/developer/ABIPolicyGuide.md#abi-breaking-changes-window-june-15---september-15-2022).

Also, the corresponding symbol should be removed from sycl/test/abi/sycl_symbols_windows.dump.

**Comment by raaiq1** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1082

**Comment by raaiq1** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1082

**Comment by cperkinsintel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1082

**Comment by raaiq1** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1082

**Comment by cperkinsintel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1082

**Comment by cperkinsintel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1082

**Review by cperkinsintel — APPROVED** [review]
LGTM!

**Comment by cperkinsintel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1082

**Comment by cperkinsintel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1082

**Comment by bader** [comment]
@raaiq1, @againull, @aelovikov-intel, could you update SYCL-CTS the same was as you updated [llvm-test-suite](https://github.com/intel/llvm-test-suite/pull/1082), please?
@yinyangsx, is enabling [SYCL-CTS in CI](https://github.com/intel/llvm/pull/6439) and this PR breaks the build of CTS!

CI logs: https://github.com/intel/llvm/runs/7446699040?check_suite_focus=true
Raw log (loads faster): https://pipelines.actions.githubusercontent.com/serviceHosts/9326dcd2-c308-48b6-82dc-50179b80e5ba/_apis/pipelines/1/runs/46459/signedlogcontent/83?urlExpires=2022-07-21T11%3A03%3A16.5700655Z&urlSigningMethod=HMACV1&urlSignature=iXbNsze2MptxokYFp63dqY3aI28e70ue%2BCzBfusr7MY%3D

**Comment by raaiq1** [comment]
Hi @bader.  Can you provide another link to the raw log files. The one previously provided seems to be expired. Thanks

**Comment by againull** [comment]
> @raaiq1, @againull, @aelovikov-intel, could you update SYCL-CTS the same was as you updated [llvm-test-suite](https://github.com/intel/llvm-test-suite/pull/1082), please? @yinyangsx, is enabling [SYCL-CTS in CI](https://github.com/intel/llvm/pull/6439) and this PR breaks the build of CTS!
> 
> CI logs: https://github.com/intel/llvm/runs/7446699040?check_suite_focus=true Raw log (loads faster): https://pipelines.actions.githubusercontent.com/serviceHosts/9326dcd2-c308-48b6-82dc-50179b80e5ba/_apis/pipelines/1/runs/46459/signedlogcontent/83?urlExpires=2022-07-21T11%3A03%3A16.5700655Z&urlSigningMethod=HMACV1&urlSignature=iXbNsze2MptxokYFp63dqY3aI28e70ue%2BCzBfusr7MY%3D

@raaiq1 kindly agreed to take a look at this.

**Pull request merged**
