### PR TITLE
[SYCL-MLIR] Merge from intel/llvm sycl branch

### PR DESCRIPTION
**Pull request by keryell**
Please do not squash and merge this PR.

### CODE REVIEW

**Comment by keryell** [comment]
There are still a few problems related to `libstdc++-13-dev` I have on my system and which are probably not tested on Intel CI.
Just curious by the result of the CI. :-)

**Comment by victor-eds** [comment]
CI failed because PR was missing `disable-lint`. Re-running. Changes LGTM. Will merge if CI passes. 

Thanks a lot for the contribution @keryell!

**Comment by victor-eds** [comment]
Failing tests:
- `check-polygeist`: `polygeist-opt/cpuifyhotspot.mlir`
- `check-cgeist`: `Verification/sycl/raising/host_raising_nd_range.cpp`
- `check-sycl-e2e`:
```
SYCL :: Basic/float_division_precise.cpp
  SYCL :: Basic/vector/bool.cpp
  SYCL :: Basic/vector/int-convert.cpp
  SYCL :: Basic/vector/operators.cpp
  SYCL :: Basic/vector/scalar_access.cpp
  SYCL :: ESIMD/fp_controls.cpp
  SYCL :: ESIMD/noinline_call_from_func.cpp
  SYCL :: ESIMD/private_memory/private_memory.cpp
  SYCL :: ESIMD/unified_memory_api/atomic_update_acc.cpp
  SYCL :: ESIMD/unified_memory_api/atomic_update_acc_64.cpp
  SYCL :: ESIMD/unified_memory_api/atomic_update_acc_cmpxchg.cpp
  SYCL :: ESIMD/unified_memory_api/atomic_update_slm.cpp
  SYCL :: ESIMD/unified_memory_api/atomic_update_slm_acc.cpp
  SYCL :: ESIMD/unified_memory_api/atomic_update_slm_acc_cmpxchg.cpp
  SYCL :: ESIMD/unified_memory_api/atomic_update_slm_cmpxchg.cpp
  SYCL :: ESIMD/unified_memory_api/block_store_slm.cpp
  SYCL :: ESIMD/unified_memory_api/block_store_slm_acc.cpp
  SYCL :: Graph/Explicit/sub_group_prop.cpp
  SYCL :: Graph/RecordReplay/sub_group_prop.cpp
  SYCL :: InvokeSimd/Regression/address_space_cast.cpp
  SYCL :: KernelAndProgram/disable-caching.cpp
  SYCL :: Regression/vec_logical_ops.cpp
  SYCL :: Regression/vec_rel_swizzle_ops.cpp
```

**Comment by keryell** [comment]
I do not have the right to set tags on this repository.
The doc talks about `ignore-lint` with `gh` script but this is `disable-lint` I guess.
More generally, since I do not the details of this project, it is unclear for me how to fix most of the test cases.

**Comment by sommerlukas** [comment]
> I do not have the right to set tags on this repository. The doc talks about `ignore-lint` with `gh` script but this is `disable-lint` I guess. 

`ignore-lint` was renamed to `disable-lint`, I'll fix the docs in that point.

> More generally, since I do not the details of this project, it is unclear for me how to fix most of the test cases.

Explicit SIMD and SYCL Graphs are currently not yet supported with SYCL-MLIR, so you can just add the failing tests to the list of expectedly failing tests [here](https://github.com/intel/llvm/blob/sycl-mlir/sycl/test-e2e/xfail_tests.txt), as described in the documentation.

For the others, a quick investigation to see what causes the error would be useful.

**Comment by victor-eds** [comment]
I'll close this PR now as it's outdated.

**Comment by keryell** [comment]
Yes, you are right!

**Pull request closed without merging**
