### PR TITLE
[Driver][SYCL] Adjust device target triple when compiling for 32-bits

### PR DESCRIPTION
**Pull request by mdtoguchi**
When compiling for 32-bit targets with either a 32-bit hosted compiler
or using and explicit target parameter, always generate to spir64
targets for the device.  We were only doing this for -fsycl-device-only
so match things up across the board.

### CODE REVIEW

**Review by AGindinson — DISMISSED** [review]
LGTM - logically sound, since our device targets are independent from the host target characteristics. Should basically be a NFC for the common compiler usage scenarios.

**Review by hchilama — DISMISSED** [review]

**Comment by kbobrovs** [comment]
One note:
Pointer size for host and device should match. Always generating spir64 (which I assume uses Physical64 addressing model) may cause problems with passing pointers in case of 32-bit host. So I believe we should have a way to override spir64 default for -fsycl-device-only. If it does not exist, this patch should probably add it.

**Comment by mdtoguchi** [comment]
> One note: Pointer size for host and device should match. Always generating spir64 (which I assume uses Physical64 addressing model) may cause problems with passing pointers in case of 32-bit host. So I believe we should have a way to override spir64 default for -fsycl-device-only. If it does not exist, this patch should probably add it.

Thanks @kbobrovs.  The target can always be overridden by using `-fsycl-targets=spir` if the default is not desired.  Conversely, instead of updating `-fsycl-device-only` we can update the default `-fsycl` setting to allow for `spir` instead of `spir64`.

**Comment by kbobrovs** [comment]
@mdtoguchi, you are right, -fsycl-targets=spir should do the job, I missed that.
One more thing is we'd need to update the docs (if any) with the new default target.

**Review by kbobrovs — APPROVED** [review]

**Comment by romanovvlad** [comment]
Won't it break a case when a struct with a raw pointer is passed by value to the kernel?

```
struct StructType {
  int *USMPtr;
};

StructType Struct{USMPtr};

Q.single_task([]() { (void)Struct.USMPtr; });
```

**Comment by mdtoguchi** [comment]
@romanovvlad, my change syncs up what the default triple is for `-fsycl-device-only` as it is for using `-fsycl` only.  The default for `-fsycl` is `spir64` regardless of host target arch.

**Comment by mdtoguchi** [comment]
@romanovvlad, @AGindinson, @kbobrovs, could I get some progress on this?  I can modify defaults for device to match host (spir vs spir64) or keep things how they are with this patch.  This is impacting pulldown verification.

**Comment by mdtoguchi** [comment]
> But now I recalled that the device compiler used in normal host+device joint compilation is run with this option. So the change would only be correct if it is not executed as a part of -cc1 invocation (i.e. we are really only changing the case where -fsycl-device-only comes from the user). Could you confirm that?

@kbobrovs, yes this change is specific to `-fsycl-device-only` usage as triggered by the user.  The behavior of compilation of host+device is not changing.  But, I will have to state that the behavior for host+device is to generate `spir64` regardless of host arch.  Perhaps this discrepancy can be handled in a separate PR if needed.

**Comment by kbobrovs** [comment]
> But, I will have to state that the behavior for host+device is to generate `spir64` regardless of host arch. Perhaps this discrepancy can be handled in a separate PR if needed.

@mdtoguchi, spir64 unconditionally fo `clang++ -fsycl` compilation w/o `-fsycl-device-only` seems wrong, as pointer-size mismatch is possible in that case with all the consequences. Is the separate PR supposed to fix that or something else?

**Comment by mdtoguchi** [comment]
I'm going address the `spir64` setting with 32-bit problem in a different PR.  Closing this one out.

**Pull request closed without merging**
