### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW46-47)

### PR DESCRIPTION
**Pull request by vmaksimo**
LLVM: llvm/llvm-project@0f652d8f527f
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@05e183d

### CODE REVIEW

**Comment by vmaksimo** [comment]
Note: temporarily disabled 3 test-suite tests in https://github.com/intel/llvm-test-suite/pull/580

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Wed Nov 24 16:46:13 UTC 2021 --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Wed Nov 24 16:49:23 UTC 2021 --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
