### PR TITLE
[UR][L0] Refactor to remove default constructor inits

### PR DESCRIPTION
**Pull request by nrspruit**
-pre-commit PR for https://github.com/oneapi-src/unified-runtime/pull/2063

### CODE REVIEW

**Review by aarongreig — APPROVED** [review]

**Comment by aarongreig** [comment]
looks like the nvidia runner is in a bad state:
```
error: Unable to create '/__w/repo_cache/intel/llvm/.git/index.lock': File exists.
Updating e94cfda4fb08..17911151ad75

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```
this tag update only affects the level zero adapter so we should be ok to merge without that job

**Comment by aarongreig** [comment]
@intel/llvm-gatekeepers please merge if you're ok doing so without the cuda build (given the above)

**Comment by sarnex** [comment]
sorry i just fixed the runner, ill restart the job and merge once it passes, sorry for the trouble

**Comment by steffenlarsen** [comment]
@nrspruit - This PR is causing problems on local builds, for example `sycl-ls` fail with

```
SYCL Exception encountered: Native API failed. Native API returns: 2147483646 (UR_RESULT_ERROR_UNKNOWN)
```

UR trace:

```
   ---> urAdapterGet
   <--- urAdapterGet(.NumEntries = 0, .phAdapters = {}, .pNumAdapters = 0x7ffdf96559fc (2)) -> UR_RESULT_SUCCESS;
   ---> urAdapterGet
   <--- urAdapterGet(.NumEntries = 2, .phAdapters = {0x5613e34c2350, 0x5613e34cd910}, .pNumAdapters = nullptr) -> UR_RESULT_SUCCESS;
   ---> urAdapterGetInfo
   <--- urAdapterGetInfo(.hAdapter = 0x5613e34c2350, .propName = UR_ADAPTER_INFO_BACKEND, .propSize = 4, .pPropValue = 0x7ffdf9655a08 (UR_ADAPTER_BACKEND_LEVEL_ZERO), .pPropSizeRet = nullptr) -> UR_RESULT_SUCCESS;
   ---> urAdapterGetInfo
   <--- urAdapterGetInfo(.hAdapter = 0x5613e34cd910, .propName = UR_ADAPTER_INFO_BACKEND, .propSize = 4, .pPropValue = 0x7ffdf9655a08 (UR_ADAPTER_BACKEND_OPENCL), .pPropSizeRet = nullptr) -> UR_RESULT_SUCCESS;
   ---> urPlatformGet
   <--- urPlatformGet(.phAdapters = {0x5613e34c2350}, .NumAdapters = 1, .NumEntries = 0, .phPlatforms = {}, .pNumPlatforms = 0x7ffdf9655a84 (0)) -> UR_RESULT_ERROR_UNKNOWN;
SYCL Exception encountered: Native API failed. Native API returns: 2147483646 (UR_RESULT_ERROR_UNKNOWN)

   ---> urAdapterRelease
   <--- urAdapterRelease(.hAdapter = 0x5613e34c2350) -> UR_RESULT_SUCCESS;
   ---> urAdapterRelease
   <--- urAdapterRelease(.hAdapter = 0x5613e34cd910) -> UR_RESULT_SUCCESS;
```

@kbenzie | @aarongreig - Is it safe to revert this while this gets investigated?

**Comment by kbenzie** [comment]
> @nrspruit - This PR is causing problems on local builds, for example `sycl-ls` fail with
> 
> ```
> SYCL Exception encountered: Native API failed. Native API returns: 2147483646 (UR_RESULT_ERROR_UNKNOWN)
> ```
> 
> UR trace:
> 
> ```
>    ---> urAdapterGet
>    <--- urAdapterGet(.NumEntries = 0, .phAdapters = {}, .pNumAdapters = 0x7ffdf96559fc (2)) -> UR_RESULT_SUCCESS;
>    ---> urAdapterGet
>    <--- urAdapterGet(.NumEntries = 2, .phAdapters = {0x5613e34c2350, 0x5613e34cd910}, .pNumAdapters = nullptr) -> UR_RESULT_SUCCESS;
>    ---> urAdapterGetInfo
>    <--- urAdapterGetInfo(.hAdapter = 0x5613e34c2350, .propName = UR_ADAPTER_INFO_BACKEND, .propSize = 4, .pPropValue = 0x7ffdf9655a08 (UR_ADAPTER_BACKEND_LEVEL_ZERO), .pPropSizeRet = nullptr) -> UR_RESULT_SUCCESS;
>    ---> urAdapterGetInfo
>    <--- urAdapterGetInfo(.hAdapter = 0x5613e34cd910, .propName = UR_ADAPTER_INFO_BACKEND, .propSize = 4, .pPropValue = 0x7ffdf9655a08 (UR_ADAPTER_BACKEND_OPENCL), .pPropSizeRet = nullptr) -> UR_RESULT_SUCCESS;
>    ---> urPlatformGet
>    <--- urPlatformGet(.phAdapters = {0x5613e34c2350}, .NumAdapters = 1, .NumEntries = 0, .phPlatforms = {}, .pNumPlatforms = 0x7ffdf9655a84 (0)) -> UR_RESULT_ERROR_UNKNOWN;
> SYCL Exception encountered: Native API failed. Native API returns: 2147483646 (UR_RESULT_ERROR_UNKNOWN)
> 
>    ---> urAdapterRelease
>    <--- urAdapterRelease(.hAdapter = 0x5613e34c2350) -> UR_RESULT_SUCCESS;
>    ---> urAdapterRelease
>    <--- urAdapterRelease(.hAdapter = 0x5613e34cd910) -> UR_RESULT_SUCCESS;
> ```
> 
> @kbenzie | @aarongreig - Is it safe to revert this while this gets investigated? (#15753)

I've approved the revert @steffenlarsen, I'll need to do the same in UR until a fix is found.

**Comment by nrspruit** [comment]
> > @nrspruit - This PR is causing problems on local builds, for example `sycl-ls` fail with
> > ```
> > SYCL Exception encountered: Native API failed. Native API returns: 2147483646 (UR_RESULT_ERROR_UNKNOWN)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > UR trace:
> > ```
> >    ---> urAdapterGet
> >    <--- urAdapterGet(.NumEntries = 0, .phAdapters = {}, .pNumAdapters = 0x7ffdf96559fc (2)) -> UR_RESULT_SUCCESS;
> >    ---> urAdapterGet
> >    <--- urAdapterGet(.NumEntries = 2, .phAdapters = {0x5613e34c2350, 0x5613e34cd910}, .pNumAdapters = nullptr) -> UR_RESULT_SUCCESS;
> >    ---> urAdapterGetInfo
> >    <--- urAdapterGetInfo(.hAdapter = 0x5613e34c2350, .propName = UR_ADAPTER_INFO_BACKEND, .propSize = 4, .pPropValue = 0x7ffdf9655a08 (UR_ADAPTER_BACKEND_LEVEL_ZERO), .pPropSizeRet = nullptr) -> UR_RESULT_SUCCESS;
> >    ---> urAdapterGetInfo
> >    <--- urAdapterGetInfo(.hAdapter = 0x5613e34cd910, .propName = UR_ADAPTER_INFO_BACKEND, .propSize = 4, .pPropValue = 0x7ffdf9655a08 (UR_ADAPTER_BACKEND_OPENCL), .pPropSizeRet = nullptr) -> UR_RESULT_SUCCESS;
> >    ---> urPlatformGet
> >    <--- urPlatformGet(.phAdapters = {0x5613e34c2350}, .NumAdapters = 1, .NumEntries = 0, .phPlatforms = {}, .pNumPlatforms = 0x7ffdf9655a84 (0)) -> UR_RESULT_ERROR_UNKNOWN;
> > SYCL Exception encountered: Native API failed. Native API returns: 2147483646 (UR_RESULT_ERROR_UNKNOWN)
> > 
> >    ---> urAdapterRelease
> >    <--- urAdapterRelease(.hAdapter = 0x5613e34c2350) -> UR_RESULT_SUCCESS;
> >    ---> urAdapterRelease
> >    <--- urAdapterRelease(.hAdapter = 0x5613e34cd910) -> UR_RESULT_SUCCESS;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @kbenzie | @aarongreig - Is it safe to revert this while this gets investigated? (#15753)
> 
> I've approved the revert @steffenlarsen, I'll need to do the same in UR until a fix is found.

This patch weas authored a while back now, it is possible the code changed enough causing an issue, I will rebase and update the change to verify no issues before re-posting thank you!

**Pull request merged**
