### PR TITLE
[GHA] Uplift Linux GPU RT version to 23.43.27642.18

### PR DESCRIPTION
**Pull request by bb-sycl**
Scheduled drivers uplift

### CODE REVIEW

**Comment by v-klochkov** [comment]
I uploaded the fix for the ESIMD fail here: https://github.com/intel/llvm/pull/12470

We expected the issue with slm_block_load() and slm_block_store() to be fixed in "27556".
slm_block_load() passed, but slm_block_store() still fails - I will need to report another issue to GPU driver.

**Comment by v-klochkov** [comment]
@dpcpp-devops-reviewers The CI testing passed. It may be a good moment to merge it and update the GPU driver finally.

**Review by aelovikov-intel — APPROVED** [review]

**Comment by aelovikov-intel** [comment]
We have some unexpected passes that might be related to this:

```
https://github.com/intel/llvm/actions/runs/7644605306/job/20830461694
Unexpectedly Passed Tests (2):
  SYCL :: InvokeSimd/Spec/ImplicitSubgroup/uniform_retval.cpp
  SYCL :: InvokeSimd/Spec/uniform_retval.cpp
```

@v-klochkov , @sarnex , can you take a look please?

**Comment by sarnex** [comment]
Will fix right now

**Comment by sarnex** [comment]
https://github.com/intel/llvm/pull/12487

**Comment by aelovikov-intel** [comment]
This also introduced (https://github.com/intel/llvm/actions/runs/7643052323/job/20825220868)

```
 SYCL :: Basic/get_backend.cpp
```

I think that happened because we expected it to start passing after the driver update but it didn't. See https://github.com/intel/llvm/pull/12130#issuecomment-1909133748

**Pull request merged**
