### PR TITLE
[SYCL][L0] Update SYCL_PI_LEVEL_ZERO_USM_ALLOCATOR description

### PR DESCRIPTION
**Pull request by igchor**
The description is no longer correct.  Default values have changed.

Ref: https://github.com/oneapi-src/unified-runtime/blob/main/source/common/umf_pools/disjoint_pool_config_parser.cpp#L27

### CODE REVIEW

**Comment by bader** [comment]
@againull, could you review this change, please?

**Comment by againull** [comment]
> @againull, could you review this change, please?

Let me redirect this to @rdeodhar  please as he is the author.
@rdeodhar Could you please help to review this change.

**Comment by rdeodhar** [comment]
The changes are OK, except, it looks like this statement is not correct:
MaxPoolSize is the maximum size of the pool, default 16MB.

MaxPoolSize appears to now be the max value of size_t. Is that the intent? If so it should be documented as such.

**Comment by igchor** [comment]
> The changes are OK, except, it looks like this statement is not correct: MaxPoolSize is the maximum size of the pool, default 16MB.
> 
> MaxPoolSize appears to now be the max value of size_t. Is that the intent? If so it should be documented as such.

Good catch, done.

**Review by rdeodhar — APPROVED** [review]
Looks good.

**Review by bader — APPROVED** [review]

**Pull request merged**
