### PR TITLE
[SPIR-V] Remove FuncParamKindINTEL and FuncParamDescINTEL

### PR DESCRIPTION
**Pull request by MrSidims**
These decorations doesn't present in https://github.com/KhronosGroup/SPIRV-LLVM-Translator

Signed-off-by: Dmitry Sidorov <dmitry.sidorov@intel.com>

### CODE REVIEW

**Review by NikitaRudenkoIntel — COMMENTED** [review]
The patch with `DecorationFuncParamKindINTEL` is not needed anymore and could be reverted.

**Review by NikitaRudenkoIntel — APPROVED** [review]
Before merging, make sure that this repo uses GenXSPIRVWriterAdaptor from vc-intrinsics with `RewriteTypes` parameter set to `true`.

**Comment by MrSidims** [comment]
> Before merging, make sure that this repo uses GenXSPIRVWriterAdaptor from vc-intrinsics with `RewriteTypes` parameter set to `true`.

Looks like it doesn't.
llvm$ grep -rn GenXSPIRVWriterAdaptor --color
llvm/tools/sycl-post-link/sycl-post-link.cpp:23:#include "llvm/GenXIntrinsics/GenXSPIRVWriterAdaptor.h"
llvm/tools/sycl-post-link/sycl-post-link.cpp:517:  MPM.add(createGenXSPIRVWriterAdaptorPass());
llvm$ grep -rn RewriteTypes
llvm$

**Comment by NikitaRudenkoIntel** [comment]
Well, you probably should create a PR with this change. See also:
https://github.com/intel-innersource/drivers.gpu.compute.vc-intrinsics/blob/cmc_experimental/GenXIntrinsics/include/llvm/GenXIntrinsics/GenXSPIRVWriterAdaptor.h

**Comment by NikitaRudenkoIntel** [comment]
Well, you probably should create a PR with enabling this option. See also:
https://github.com/intel/vc-intrinsics/blob/master/GenXIntrinsics/include/llvm/GenXIntrinsics/GenXSPIRVWriterAdaptor.h

**Comment by bader** [comment]
@MrSidims, @AlexeySotkin, @AlexeySachkov, ping.

**Comment by NikitaRudenkoIntel** [comment]
BTW I created a corresponding issue and PR:
https://github.com/intel/llvm/pull/3607
It is awaiting driver update in Jenkins, which fixes a problem causing failure after enabling `RewriteTypes`

**Comment by MrSidims** [comment]
I guess this PR is no longer needed

**Comment by AlexeySachkov** [comment]
@MrSidims, why so? Have we removed those decorations already in some other PR?

**Comment by MrSidims** [comment]
> @MrSidims, why so? Have we removed those decorations already in some other PR?

I though so, because otherwise we couldn't move to external SPIR-V Headers. But I see now, that FuncParamKindINTEL and FuncParamDescINTEL were just moved into spirv_internal.hpp .

**Pull request closed without merging**
