### PR TITLE
[UR] test PR for UR PR 2028

### PR DESCRIPTION
**Pull request by yingcong-wu**
UR PR: https://github.com/oneapi-src/unified-runtime/pull/2028

### CODE REVIEW

**Review by aarongreig — APPROVED** [review]

**Comment by aarongreig** [comment]
@intel/llvm-gatekeepers please merge

**Comment by martygrant** [comment]
@sarnex apologies I never saw your comment, are these guidelines documented somewhere?

**Comment by sarnex** [comment]
@martygrant Np, I think it's [here](https://github.com/intel/llvm/blob/sycl/sycl/doc/developer/ContributeToDPCPP.md#commit-message)

**Comment by sarnex** [comment]
@martygrant Sorry also [here](https://github.com/intel/llvm/blob/sycl/CONTRIBUTING.md#pull-request)

**Pull request merged**
