### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW01)

### PR DESCRIPTION
**Pull request by vmaksimo**
LLVM: llvm/llvm-project@bb84dd81590b
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@987a1ab37f2260742ccb18b261339d497929dd90

### CODE REVIEW

**Comment by vmaksimo** [comment]
OCL x64 Test Suite failure is not related to the PR. The test was disabled here https://github.com/intel/llvm-test-suite/commit/0ee72735391149a0bc96f3c6d6c7fad98abaefb1

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Wed 29 Dec 2021 10:22:44 AM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Wed 29 Dec 2021 10:26:01 AM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
