### PR TITLE
[SYCL][E2E] Disable unsupported tests and enable validated tests for Windows/CUDA

### PR DESCRIPTION
**Pull request by mmoadeli**
- The test [atomic_class.cpp](https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/syclcompat/atomic/atomic_class.cpp) modified to call host function after kernel function finishes. This is because CUDA on Windows does not support accessing host memory while a kernel is running, as discussed in [this forum post](https://forums.developer.nvidia.com/t/cudamallocmanaged-clarification-needed/67611) and [this bug report](https://developer.nvidia.com/bugs/4763389). 
- A number of previously XFAILed printf tests have been enabled for execution on Windows/CUDA. 

- Updated the relevant tests to include the necessary CUDA library and include paths for running tests on Windows.

### CODE REVIEW

**Review by sarnex — APPROVED** [review]
LGTM assuming the cuda windows tests have been manually verified

**Review by dm-vodopyanov — APPROVED** [review]

**Comment by joeatodd** [comment]
@mmoadeli I discussed this with @Alcpz and we think the tests in question only use `usm_shared` and access it concurrently on device/host for convenience. It's not really what we're testing.

Could I suggest the following diff (shift the `wait()` before the HostFunc):
```diff
diff --git a/sycl/test-e2e/syclcompat/atomic/atomic_fixt.hpp b/sycl/test-e2e/syclcompat/atomic/atomic_fixt.hpp
index 09d6beb0451c..4d34db9cfa10 100644
--- a/sycl/test-e2e/syclcompat/atomic/atomic_fixt.hpp
+++ b/sycl/test-e2e/syclcompat/atomic/atomic_fixt.hpp
@@ -131,8 +131,8 @@ public:
     if (skip_)
       return; // skip
     syclcompat::launch<Kernel>(grid_, threads_, atom_arr_device_);
-    HostFunc(atom_arr_host_);
     syclcompat::wait();
+    HostFunc(atom_arr_host_);
 
     verify();
   }
@@ -170,8 +170,8 @@ public:
       return;
     syclcompat::launch<Kernel>(this->grid_, this->threads_,
                                this->atom_arr_device_, atom_arr_shared_in_);
-    HostFunc(this->atom_arr_host_, atom_arr_shared_in_);
     syclcompat::wait();
+    HostFunc(this->atom_arr_host_, atom_arr_shared_in_);
 
     this->verify();
   }

```

If that works on Windows+CUDA (I guess it should) then I think that's the preferable solution.

**Comment by mmoadeli** [comment]
> @mmoadeli I discussed this with @Alcpz and we think the tests in question only use `usm_shared` and access it concurrently on device/host for convenience. It's not really what we're testing.
> 
> Could I suggest the following diff (shift the `wait()` before the HostFunc):
> 
> ```diff
> diff --git a/sycl/test-e2e/syclcompat/atomic/atomic_fixt.hpp b/sycl/test-e2e/syclcompat/atomic/atomic_fixt.hpp
> index 09d6beb0451c..4d34db9cfa10 100644
> --- a/sycl/test-e2e/syclcompat/atomic/atomic_fixt.hpp
> +++ b/sycl/test-e2e/syclcompat/atomic/atomic_fixt.hpp
> @@ -131,8 +131,8 @@ public:
>      if (skip_)
>        return; // skip
>      syclcompat::launch<Kernel>(grid_, threads_, atom_arr_device_);
> -    HostFunc(atom_arr_host_);
>      syclcompat::wait();
> +    HostFunc(atom_arr_host_);
>  
>      verify();
>    }
> @@ -170,8 +170,8 @@ public:
>        return;
>      syclcompat::launch<Kernel>(this->grid_, this->threads_,
>                                 this->atom_arr_device_, atom_arr_shared_in_);
> -    HostFunc(this->atom_arr_host_, atom_arr_shared_in_);
>      syclcompat::wait();
> +    HostFunc(this->atom_arr_host_, atom_arr_shared_in_);
>  
>      this->verify();
>    }
> ```
> 
> If that works on Windows+CUDA (I guess it should) then I think that's the preferable solution.

Thanks @joeatodd, done.

**Review by joeatodd — APPROVED** [review]
LGTM, thanks @mmoadeli

**Pull request merged**
