### PR TITLE
[SYCL][CUDA][HIP] Added support in kernel_bundle_api.cpp for hip || cuda

### PR DESCRIPTION
**Pull request by JackAKirk**
This uses tests from kernel_bundle_api.cpp but with "jit" testing removed, and with cpu specific lit testing removed. This test does not use any "jit" functionality wrt kernel_bundles, such as sycl::compile, sycl::build, sycl::link.

HIP does not yet support such "jit" functionality, but we want to test the "aot" functionality of kernel_bundles for the time being.

### CODE REVIEW

**Comment by aelovikov-intel** [comment]
I've re-read the description a few times but I still haven't decided if "aot" is inaccurate/confusing or not. I think using the term "aot" without explicit `fsycl-targets` isn't accurate. Do we have `lit.cfg.py` set it up automatically here? If so, how do we ever test "jit"?

**Comment by JackAKirk** [comment]
> I've re-read the description a few times but I still haven't decided if "aot" is inaccurate/confusing or not. I think using the term "aot" without explicit `fsycl-targets` isn't accurate. Do we have `lit.cfg.py` set it up automatically here? If so, how do we ever test "jit"?

Yeah maybe "pre-compiled" is better instead of "aot"?

`sycl::compile,`sycl::build`, `sycl::link` works for cuda, but not hip yet, so that this test could run on cuda https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/Basic/kernel_bundle/kernel_bundle_api.cpp except the filecheck checks are specific to the cpu.

But we want to specifically test the functionality tested in kernel_bundle_api.cpp minus unit tests that require those three "jit" apis.
Once the hip kernel_bundle functionality is fully implemented we can probably just use kernel_bundle_api.cpp, but without the FILECHECK stuff.

**Comment by aelovikov-intel** [comment]
> ... we can probably just use kernel_bundle_api.cpp, but without the FILECHECK stuff.

Would something like this work:
```
// RUN: %{build} -DENABLE_ONELINE_COMPILE_CHECKS -o %t.full.out
// RUN: %{build} -o %t.partial.out

// RUN: %if { cuda || hip } %{ %{run} %t.partial.out %}
// RUN: %if { cpu } %{  %{run} %t.full.out | FileCheck %s %}
// checks
#if ENABLE_ONELINE_COMPILE_CHECKS
...
sycl::build(...)
...
#endif
...
```

**Comment by JackAKirk** [comment]
> > ... we can probably just use kernel_bundle_api.cpp, but without the FILECHECK stuff.
> 
> Would something like this work:
> 
> ```
> // RUN: %{build} -DENABLE_ONELINE_COMPILE_CHECKS -o %t.full.out
> // RUN: %{build} -o %t.partial.out
> 
> // RUN: %if { cuda || hip } %{ %{run} %t.partial.out %}
> // RUN: %if { cpu } %{  %{run} %t.full.out | FileCheck %s %}
> // checks
> #if ENABLE_ONELINE_COMPILE_CHECKS
> ...
> sycl::build(...)
> ...
> #endif
> ...
> ```

I can do this for the CUDA backend, However this won't work for the hip backend because the `sycl::compile`,`sycl::build`, `sycl::link` works for cuda, but not hip yet. But the main motivation is to test the existing HIP kernel_bundle functionality that is implemented.
It is a bit annoying because eventually we would just remove this test I've added here and just use the patch you suggest above. I can however switch off the test I've added for cuda and use your suggested patch for the cuda case only in the existing test.

**Comment by JackAKirk** [comment]
@aelovikov-intel I did not find a valid set of `// RUN:` logic that allowed all three backends to run using the same source.
I've now gone back to having a separate test for hip only.
Actually I think that having a separate file for hip suits our purposes better since it more clearly shows the set of kernel_bundle functionality available on hip, which is what really motivated this PR in the first place.
Once the full kernel_bundle hip functionality is added, I can simply remove the `kernel_bundle_api_hip.cpp` test, and add `hip` to run on `kernel_bundle_api.cpp` alongside cuda and cpu.

**Review by aelovikov-intel — APPROVED** [review]

**Pull request merged**
