### PR TITLE
[SYCL] Add missing supported AMDGPU architectures to SYCL

### PR DESCRIPTION
**Pull request by GeorgeWeb**
The three added `gfx7` architectures were previously omitted from the list of supported ones for SYCL targeting AMDGPU.
There is no rational for them to be excluded rather than a potential mistake when all the rest were added, so this PR adds them in.
All of these exactly match the LLVM AMDGPU support docs here: https://llvm.org/docs/AMDGPUUsage.html#processors.
This also makes reusing the current `OffloadArch` enum in clang Driver easier with no concern of whether we have to filter these out for SYCL.

### CODE REVIEW

**Review by AlexeySachkov — APPROVED** [review]

**Review by mdtoguchi — APPROVED** [review]

**Review by gmlueck — APPROVED** [review]

**Review by keryell — APPROVED** [review]
Thanks!

**Comment by GeorgeWeb** [comment]
@intel/llvm-reviewers-runtime gentle ping. Not a prio, just good to get in to support one of the new driver changes wrt allowed --offload-arch targets. Thanks!

**Comment by sarnex** [comment]
I'll merge once CI passes, thanks for merging HEAD in.

**Comment by npmiller** [comment]
ping @intel/llvm-reviewers-runtime @sergey-semenov Could we get a review on this, we're still missing one approval, and it's a fairly small change so it should be quick to review.

**Review by maarquitos14 — APPROVED** [review]
LGTM.

**Comment by npmiller** [comment]
@intel/llvm-gatekeepers this should be ready to merge

**Pull request merged**
