### PR TITLE
[NFC] Fix llvm-spirv LIT test location

### PR DESCRIPTION
**Pull request by sarnex**
Looks like it got messed up in pulldown somehow here, https://github.com/intel/llvm/commit/22d83e0018aab52191c4c8a341a6b4afa8a436ab

It's currently in `test/` not `llvm-spirv/test/`, this moves it to `llvm-spirv/test/` with the other tests.

### CODE REVIEW

**Comment by sarnex** [comment]
@aelovikov-intel For this kind of PR, I wonder if there's a way to update `
SYCL Pre Commit on Linux / detect_changes / Decide which tests could be affected by the changes` to know we don't need to run E2E tests.

**Comment by aelovikov-intel** [comment]
>

**Comment by sarnex** [comment]
@aelovikov-intel thanks for the explanation!

**Review by bader — APPROVED** [review]

**Review by AlexeySachkov — APPROVED** [review]

**Comment by sarnex** [comment]
@intel/llvm-gatekeepers Can we merge this one? It's a LIT only change, so we don't need to run Cuda E2E tests, and they're taking forever today. Thanks!

**Pull request merged**
