### PR TITLE
[BuildBot] Uplift GPU RT version for Linux CI Process

### PR DESCRIPTION
**Pull request by bb-sycl**
Uplift GPU RT version for Linux to 22.14.22890

### CODE REVIEW

**Comment by cperkinsintel** [comment]
@againull  - this PR is automatically created to uplift the GPU driver. I'm investigating the test failures before we merge it.

 But do you know if there is anything needed for LevelZero? When I pull and build this PR then L0 no longer shows up in sycl-ls.  That seems not correct.

**Comment by againull** [comment]
> @againull - this PR is automatically created to uplift the GPU driver. I'm investigating the test failures before we merge it.
> 
> But do you know if there is anything needed for LevelZero? When I pull and build this PR then L0 no longer shows up in sycl-ls. That seems not correct.

There is problem with gpu runtime itself because it doesn't contain L0 runtime (only OpenCL runtime), I've created an issue for our CI team

**Comment by DoyleLi** [comment]
Hi @cperkinsintel @againull 
The driver has been updated and the ci job has been re-executed. Please refer to latest failure.

**Comment by cperkinsintel** [comment]
This PR seems to be pre-empted by https://github.com/intel/llvm/pull/6018  
I'm investigating CI issues for 6018 and if those are resolved, this PR will be closed and not merged.

**Review by cperkinsintel — CHANGES_REQUESTED** [review]
This should not be merged. Has been preempted by https://github.com/intel/llvm/pull/6018/

**Comment by cperkinsintel** [comment]
Can one of the codeowners or repo owners close this PR? It has been pre-empted by https://github.com/intel/llvm/pull/6018/ and is no longer needed.

**Pull request closed without merging**
