### PR TITLE
[NFC] fix build issue in NDEBUG mode

### PR DESCRIPTION
**Pull request by Naghasan**

### CODE REVIEW

**Review by sommerlukas — APPROVED** [review]

**Comment by sommerlukas** [comment]
@intel/llvm-gatekeepers @sarnex This PR should fix the current post-commit failure, can you please merge when CI is done (or now)?

**Comment by sarnex** [comment]
I want at least Windows build to pass (Linux build already did), then I'll merge.

**Comment by sarnex** [comment]
Build + LIT passed on both platforms, merging to unbreak CI.

**Comment by sarnex** [comment]
@Naghasan Still failing in postcommit:

https://github.com/intel/llvm/actions/runs/10099057533/job/27927417771

```
 [6364/8901] Linking CXX shared library lib/libSYCLKernelFusionPasses.so.19.0git
FAILED: lib/libSYCLKernelFusionPasses.so.19.0git 
: && /opt/sycl/bin/clang++ -fPIC -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG  -Wl,-z,defs -Wl,-z,nodelete   -Wl,-rpath-link,/__w/llvm/llvm/build/./lib  -Wl,--gc-sections -shared -Wl,-soname,libSYCLKernelFusionPasses.so.19.0git -o lib/libSYCLKernelFusionPasses.so.19.0git tools/sycl-fusion/passes/CMakeFiles/SYCLKernelFusionPasses.dir/SYCLFusionPasses.cpp.o tools/sycl-fusion/passes/CMakeFiles/SYCLKernelFusionPasses.dir/kernel-fusion/Builtins.cpp.o tools/sycl-fusion/passes/CMakeFiles/SYCLKernelFusionPasses.dir/kernel-fusion/SYCLKernelFusion.cpp.o tools/sycl-fusion/passes/CMakeFiles/SYCLKernelFusionPasses.dir/kernel-fusion/SYCLSpecConstMaterializer.cpp.o tools/sycl-fusion/passes/CMakeFiles/SYCLKernelFusionPasses.dir/kernel-info/SYCLKernelInfo.cpp.o tools/sycl-fusion/passes/CMakeFiles/SYCLKernelFusionPasses.dir/internalization/Internalization.cpp.o tools/sycl-fusion/passes/CMakeFiles/SYCLKernelFusionPasses.dir/syclcp/SYCLCP.cpp.o tools/sycl-fusion/passes/CMakeFiles/SYCLKernelFusionPasses.dir/cleanup/Cleanup.cpp.o tools/sycl-fusion/passes/CMakeFiles/SYCLKernelFusionPasses.dir/debug/PassDebug.cpp.o tools/sycl-fusion/passes/CMakeFiles/SYCLKernelFusionPasses.dir/target/TargetFusionInfo.cpp.o  -Wl,-rpath,"\$ORIGIN/../lib:/__w/llvm/llvm/build/lib:"  lib/libLLVMPasses.so.19.0git  lib/libsycl-fusion-common.so.19.0git  lib/libLLVMTransformUtils.so.19.0git  lib/libLLVMCore.so.19.0git  lib/libLLVMTargetParser.so.19.0git  lib/libLLVMSupport.so.19.0git  -Wl,-rpath-link,/__w/llvm/llvm/build/lib && :
/usr/bin/ld: tools/sycl-fusion/passes/CMakeFiles/SYCLKernelFusionPasses.dir/kernel-fusion/SYCLSpecConstMaterializer.cpp.o: in function `llvm::SYCLSpecConstMaterializer::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&)':
SYCLSpecConstMaterializer.cpp:(.text._ZN4llvm25SYCLSpecConstMaterializer3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE+0x46): undefined reference to `llvm::TargetHelpers::getArchType(llvm::Module const&)'
```

**Comment by sarnex** [comment]
I fixed it in https://github.com/intel/llvm/pull/14780

**Pull request merged**
