### PR TITLE
[SYCL] Add checks to free-memory reported with total-memory

### PR DESCRIPTION
**Pull request by abagusetty**
Adds a test case to check `free_memory < total_memory`

### CODE REVIEW

**Comment by abagusetty** [comment]
Looks like the CI machine gfx1031 is reporting this error:
```
/__w/llvm/llvm/src/sycl/unittests/kernel-and-program/DeviceInfo.cpp:173
Expected: (TotalMemory) >= (FreeMemory), actual: 140736249540080 vs 140736249540240
Expect total_memory >= free_memory
```

**Comment by abagusetty** [comment]
@al42and @zjin-lcf Just wanted to check if you had a chance to test free-mem extension with gfx1031 ?

**Comment by zjin-lcf** [comment]
Are these values read with the SYCL APIs equal to the values read with the HIP APIs ?

**Comment by abagusetty** [comment]
> Are these values read with the SYCL APIs equal to the values read with the HIP APIs ?

for gfx90a they are the same. But I don`t have access to gfx1031 and not sure of the device or the rocm version being used by CI.

**Comment by zjin-lcf** [comment]
I will test it on gfx10xx GPUs, and let you know tomorrow.

**Comment by bader** [comment]
> not sure of the device or the rocm version being used by CI.

These are available in the logs.

**Comment by al42and** [comment]
Trying to run unit-tests for the HIP or any non-`opencl` backend (via `ONEAPI_DEVICE_SELECTOR`) segfaults for me, but that is not limited to the new test.

But when run manually, the reported free memory is equal to the total memory, and not consistent with `rocm-smi` output on `gfx1034`:

```console
$ clang++ --version
clang version 16.0.0 (https://github.com/abagusetty/llvm.git 9736b4c6691d309646262e54ff3599c4ec8ac466)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/aland/intel-sycl/llvm/build/install//bin

$ clang++ -fsycl test.cpp -o test1 && ./test1
sycl::info::device::name                    : NVIDIA GeForce RTX 3060
sycl::info::device::global_mem_size         : 12629508096
sycl::ext::intel::info::device::free_memory : 11319246848

sycl::info::device::name                    : AMD Radeon RX 6400
sycl::info::device::global_mem_size         : 4278190080
sycl::ext::intel::info::device::free_memory : 4278190080

$ rocm-smi --showmeminfo vram


======================= ROCm System Management Interface =======================
============================= Memory Usage (Bytes) =============================
GPU[0]          : VRAM Total Memory (B): 4278190080
GPU[0]          : VRAM Total Used Memory (B): 108814336
================================================================================
============================= End of ROCm SMI Log ==============================
```

**Comment by abagusetty** [comment]
> Trying to run unit-tests for the HIP or any non-`opencl` backend (via `ONEAPI_DEVICE_SELECTOR`) segfaults for me, but that is not limited to the new test.
> 
> When run manually, the reported free memory is equal to the total memory and not consistent with `rocm-smi` output on `gfx1034`:
> 
> ```
> $ clang++ --version
> clang version 16.0.0 (https://github.com/abagusetty/llvm.git 9736b4c6691d309646262e54ff3599c4ec8ac466)
> Target: x86_64-unknown-linux-gnu
> Thread model: posix
> InstalledDir: /home/aland/intel-sycl/llvm/build/install//bin
> 
> $ clang++ -fsycl test.cpp -o test1 && ./test1
> sycl::info::device::name                    : NVIDIA GeForce RTX 3060
> sycl::info::device::global_mem_size         : 12629508096
> sycl::ext::intel::info::device::free_memory : 11319246848
> 
> sycl::info::device::name                    : AMD Radeon RX 6400
> sycl::info::device::global_mem_size         : 4278190080
> sycl::ext::intel::info::device::free_memory : 4278190080
> 
> $ rocm-smi --showmeminfo vram
> 
> 
> ======================= ROCm System Management Interface =======================
> ============================= Memory Usage (Bytes) =============================
> GPU[0]          : VRAM Total Memory (B): 4278190080
> GPU[0]          : VRAM Total Used Memory (B): 108814336
> ================================================================================
> ============================= End of ROCm SMI Log ==============================
> ```
> 
> Update: `hipMemGetInfo(&free, &total)` also returns `4278190080` for both, so I guess that's not SYCL's fault. Trying to allocate some device memory decreases the reported "free" value, so it's not completely broken.
> 
> Update 2: The low-level API reports total memory in bytes, but free memory in KiB, and `hipMemGetInfo` does the conversion: https://github.com/ROCm-Developer-Tools/hipamd/blob/312dff7b794337aa040be0691acc78e9f968a8d2/src/hip_memory.cpp#L749. Perhaps some rounding errors add up and cause the observerd paradox of free > total?

@al42and Thanks for verifying this thoroughly. I was too able to see similar observations with gfx90a, when using both the SYCL and native HIP test cases. (i.e., free = total) and have also retested to check by allocating 1 byte to the total and verify the free space. 
CI is using the `gfx1031`, not sure if this artifact has anything to do with rocm-5.4.0

Tagging @npmiller for any inputs.

**Comment by al42and** [comment]
As far as ROCm versions are concerned: I tested on MI50 (gfx906) with ROCm 4.0.0, 4.5.2, 5.0.2, 5.4.1: in all cases `hipMemGetInfo` reports free == total.

**Comment by zjin-lcf** [comment]
Running a standalone test shows that total memory is equal to free memory using SYCL and HIP APIs.
I reported the HIP results to https://github.com/RadeonOpenCompute/ROCm/issues/1909

**Comment by abagusetty** [comment]
Just realized that the above assert values are in the order of 140 TB for total and free memory. Seems like garbage info but they are so close by a few hundred bytes.

**Comment by abagusetty** [comment]
> As far as ROCm versions are concerned: I tested on MI50 (gfx906) with ROCm 4.0.0, 4.5.2, 5.0.2, 5.4.1: in all cases `hipMemGetInfo` reports free == total.

Same here, I tested gfx908, gfx90a with a few version of rocm. All the cases were producing meaningful results.

**Comment by abagusetty** [comment]
@bader @steffenlarsen Just realized that the CI for HIP plugin uses `gfx1031` (navi-22) arch that is not supported by the rocm-5.4.0. That is likely why this simple test fails while it works fine on all the above GPUs that were tested in the comments were listed in the supported table below. 

Not sure how to approach this. Any pointers on this or which folks to approach ?

List of supported devices for 5.4 is listed at the bottom of this table: https://docs.amd.com/bundle/ROCm-Release-Notes-v5.4/page/About_This_Document.html

**Comment by steffenlarsen** [comment]
@abagusetty - The unit-tests are meant to be device-idependent and should instead define the required queries through mock redefinitions. In the case for these tests it seems that `PI_DEVICE_INFO_GLOBAL_MEM_SIZE` isn't handled by `redefinedDeviceGetInfo` and likewise it does not return anything useful for `PI_EXT_INTEL_DEVICE_INFO_FREE_MEMORY`. You could add these, but I am not sure there's much value in such a test given you control both values.

The alternative is to write an E2E test in https://github.com/intel/llvm-test-suite, but I worry that having it run in parallel with other tests that may allocate memory may invalidate the test.

**Comment by abagusetty** [comment]
Thanks so much, closing this PR.

**Pull request closed without merging**
