### PR TITLE
[CI] Enable llvm-test-suite on CUDA Linux target

### PR DESCRIPTION
**Pull request by pvchupin**
* Update reusable workflow with corresponding config
* Add cuda llvm-test-suite run to pre-commit on Linux
* Fix option typo [NFC]

Failing tests disabled at: https://github.com/intel/llvm-test-suite/pull/1052
Issue: https://github.com/intel/llvm/issues/6285

### CODE REVIEW

**Comment by cperkinsintel** [comment]
Getting lots of failures on the CUDA run of the tests. Are there updated headers we should be using?

**Comment by pvchupin** [comment]
@steffenlarsen, has a fix in progress for a few of these problems. I'm going to mark the rest with UNSUPPORTED:cuda and open a separate issue to address these.
Tagging @AerialMantis

**Review by bader — APPROVED** [review]

**Comment by steffenlarsen** [comment]
Couple of patches up for failing tests:

- https://github.com/intel/llvm/pull/6279
- https://github.com/intel/llvm/pull/6280

Additionally, the following patches should fix some problems seen on Windows testing:
- https://github.com/intel/llvm/pull/6281
- https://github.com/intel/llvm-test-suite/pull/1049
- https://github.com/intel/llvm-test-suite/pull/1050
- https://github.com/intel/llvm-test-suite/pull/1051

In local testing on Windows I still see failure in the following tests after the above changes are applied:
```
  SYCL :: Sampler/unnormalized-clamp-nearest.cpp
  SYCL :: Sampler/unnormalized-clampedge-nearest.cpp
  SYCL :: Sampler/unnormalized-none-nearest.cpp
```
If they continue to fail after the patches have been merged I suggest we disable these and file an issue.

**Comment by pvchupin** [comment]
Ok, after merging bunch of changes above and retesting I see the same 3 fails as @steffenlarsen mentioned. I'm going to disable these and open an issue.

**Comment by pvchupin** [comment]
I realized "/verify with" is useless here because it doesn't run CUDA testing. I actually need to merge that change first and rerun again.

**Pull request merged**
