### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW36)

### PR DESCRIPTION
**Pull request by sys-ce-bb**
LLVM: llvm/llvm-project@73b2c86
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@c6fe12b

### CODE REVIEW

**Comment by jsji** [comment]
@bader @intel/llvm-gatekeepers  This is ready for review . Thanks.

[095b4ac](https://github.com/intel/llvm/pull/11102/commits/095b4ac4e1d1f4874c2760b92f3bbb06d155d2b0) is revert the previous revert so that we can sync with upstream again -- removal of opaque pointer options.

[b18885a](https://github.com/intel/llvm/pull/11102/commits/b18885ab6c3d997eb374d300784cc4167c4d3329) should be a upstream bug, will upstream the fix later.

[4fe5b40](https://github.com/intel/llvm/pull/11102/commits/4fe5b40f3d418a8a9dbb7ebd7743efeff2f5677e) is a testcase fix due to upstream fix.

**Comment by bader** [comment]
To be more specific:

@intel/dpcpp-spirv-reviewers, please take a look at 
> [b18885a](https://github.com/intel/llvm/pull/11102/commits/b18885ab6c3d997eb374d300784cc4167c4d3329) should be a upstream bug, will upstream the fix later.

@intel/dpcpp-cfe-reviewers, please review
> [4fe5b40](https://github.com/intel/llvm/pull/11102/commits/4fe5b40f3d418a8a9dbb7ebd7743efeff2f5677e) is a testcase fix due to upstream fix.

**Review by elizabethandrews — APPROVED** [review]

**Comment by jsji** [comment]
> 

FYI.

[b18885a](https://github.com/intel/llvm/pull/11102/commits/b18885ab6c3d997eb374d300784cc4167c4d3329) and [7533495](https://github.com/intel/llvm/pull/11102/commits/75334951396c54ecab4bb549b83cbe5ee7c8a5ce) has been reviewed by @asudarsa in internal repo, PR #500.

**Review by smanna12 — APPROVED** [review]

**Comment by jsji** [comment]
Ping @intel/dpcpp-spirv-reviewers . Please double check . Thanks.

> FYI.
> 
> [b18885a](https://github.com/intel/llvm/pull/11102/commits/b18885ab6c3d997eb374d300784cc4167c4d3329) and [7533495](https://github.com/intel/llvm/pull/11102/commits/75334951396c54ecab4bb549b83cbe5ee7c8a5ce) have been reviewed by @asudarsa in internal repo, PR #500.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Sat 09 Sep 2023 12:10:23 AM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Sat 09 Sep 2023 12:14:28 AM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
