### PR TITLE
[SYCL] Allow placement new with address space in device code

### PR DESCRIPTION
**Pull request by sergey-semenov**
Signed-off-by: Sergey Semenov <sergey.semenov@intel.com>

### CODE REVIEW

**Comment by asavonic** [comment]
From my understanding, you should be already be able to use placement new if you cast a pointer in a concrete address space to a pointer in default address space (which is then CodeGen'ed to generic).
```
 __global void *ptr;
new ((void*)ptr) foo;
```
It is not very convenient, but we should only have pointers in concrete address space in SYCL standard library, and there should only be a few places with that (only `buffer` and `multi_ptr` classes?).

What use case you're trying to support?
Can you also write clang CodeGen test for placement new? You can add a few cases to the existing test in https://github.com/intel/llvm/blob/sycl/clang/test/CodeGenSYCL/address-space-new.cpp

**Comment by sergey-semenov** [comment]
@asavonic This change is not about the address space of the pointer to memory, but rather the address space of the type being constructed, foo in your example.

Consider the following device function:
`template <typename T>
void bar(T* ptr) {
	new (static_cast<void*>(ptr)) T(42);
}`
used like this in device code:
`bar(&globalIntAccessor[idx]);
`
bar<T> is instantiated as bar<__global int> and leads to compilation error due to address space qualified placement new. While it is possible to circumvent this problem by allocating accessor::value_type instead, usage of T is more straightforward.

**Comment by asavonic** [comment]
> `bar(&globalIntAccessor[idx]); `
> bar is instantiated as bar<__global int>

That should not happen. Address space qualified pointer (or a reference) should not leak from an accessor to user code. 
It looks like a bug in `accessor::operator[]`: it has to return an `int&` instead of `__global int&`.
I fixed a similar problem in multi_ptr: https://github.com/intel/llvm/blob/4bcb91e695869bc1f449eeb9f299c4daf8a9e8f7/sycl/include/CL/sycl/multi_ptr.hpp#L73

**Comment by sergey-semenov** [comment]
Right, I'll fix the problem in the accessor instead then.

**Pull request closed without merging**
