### PR TITLE
[mlir][RegionOp] Add RegionOp

### PR DESCRIPTION
**Pull request by Hardcode84**
* Added into SCF dialect for now, until we decide for better place
* Op taken directly from numba-mlir https://github.com/numba/numba-mlir/blob/6dabd431f756a206c777f1030c35b53b95423f58/mlir/include/numba/Dialect/numba_util/NumbaUtilOps.td#L236
* Canonicalizations are not part of this PR to reduce scope

### CODE REVIEW

**Review by rengolin — APPROVED** [review]
Can regions be nested? Doesn't seem to have any restriction other than the inliner need to be recursive. We also need to discuss region isolation and the attributes, but that's better after this PR.

**Comment by Hardcode84** [comment]
> Can regions be nested? Doesn't seem to have any restriction other than the inliner need to be recursive. We also need to discuss region isolation and the attributes, but that's better after this PR.

Yes, they can, and I'm using nested regions in numba-mlir. Need to mention in doc probably.

**Comment by rengolin** [comment]
> > Can regions be nested? Doesn't seem to have any restriction other than the inliner need to be recursive. We also need to discuss region isolation and the attributes, but that's better after this PR.
> 
> Yes, they can, and I'm using nested regions in numba-mlir. Need to mention in doc probably.

Perhaps a small test, too?

**Comment by Hardcode84** [comment]
> > > Can regions be nested? Doesn't seem to have any restriction other than the inliner need to be recursive. We also need to discuss region isolation and the attributes, but that's better after this PR.
> > 
> > 
> > Yes, they can, and I'm using nested regions in numba-mlir. Need to mention in doc probably.
> 
> Perhaps a small test, too?

done

**Comment by rengolin** [comment]
> done

Awesome, thanks! LGTM!

**Review by fschlimb — APPROVED** [review]
Nice!

**Comment by fschlimb** [comment]
The region can access the values from the parent above; can the parent below access values created inside the region?

**Comment by Hardcode84** [comment]
> The region can access the values from the parent above; can the parent below access values created inside the region?

You can return values from region using yield op and and they will be accessible as region op results.

**Comment by rengolin** [comment]
> > The region can access the values from the parent above; can the parent below access values created inside the region?
> 
> You can return values from region using yield op and and they will be accessible as region op results.

If the question is about the lexical scope, the answer is `no`.

```mlir
%0 = ...
%1 = scf.region {
    %inner_0 = op1 (%0) // This is fine, not isolated from above
    %inner_1 = op2 (%inner_0) // This is in the same lexical context
    scf.yield %inner_1 // Goes into %1
}
// This is fine, access return value
%2 = op3 (%1)  // OK

// This is not, since the lexical context is now dead
%3 = op4 (%inner_0) // ERROR
```

This is necessary, for example:
```mlir
%0 = ...
%1 = scf.region {
    %inner_0 = op1 (%0) // This is fine, not isolated from above
    %inner_1 = op2 (%inner_0) // This is in the same lexical context
    scf.yield %inner_1 // Goes into %1
}

%2 = scf.region {
    %inner_0 = op1 (%1) // This is fine, not isolated from above
    %inner_1 = op2 (%inner_0) // This is in the same lexical context
    scf.yield %inner_1 // Goes into %2
}

// Which one? From the first or the second region?
%3 = op4 (%inner_0) // ERROR
```

If you want to have access to temporary values inside regions, you'll have to return them:
```mlir
%1, %2 = scf.region {
    %inner_0 = op1 (%0) // This is fine, not isolated from above
    %inner_1 = op2 (%inner_0) // This is in the same lexical context
    scf.yield %inner_1, %inner_0 // Goes into %1, %2
}
%3, %4 = scf.region {
    %inner_0 = op1 (%1) // This is fine, not isolated from above
    %inner_1 = op2 (%inner_0) // This is in the same lexical context
    scf.yield %inner_1, %inner_0 // Goes into %3, %4
}

// Now it's clear which one
%3 = op4 (%2) // OK
```

**Comment by fschlimb** [comment]
Thanks, just wanted to mention that we could also let the region really be a group which does not imply a (lexical) scope. In such a construct the yieldOp would probably not make a lot of sense, though.

**Pull request merged**
