### PR TITLE
[SYCL][PI][CUDA][HIP] Fix bugs that can cause events not to be waited on

### PR DESCRIPTION
**Pull request by t4c1**
Fixes two bug in CUDA PI and HIP PI that can cause waiting for events to do nothing:
 - The first one is an off-by-one error when checking if an event needs to be waited on
 - The second one is `last_sync_compute_streams_` /  `last_sync_transfer_streams_` to a new value before checking the streams which can read these variables, expecting the old values.

Both of these are synchronization related and therefore hard to test for.

### CODE REVIEW

**Comment by zjin-lcf** [comment]
Are they bugs in HIP PI ?

**Comment by t4c1** [comment]
That is a good point. Probably, I will check HIP tomorrow.

**Review by aelovikov-intel — APPROVED** [review]
Do we need a dedicated codeowner for HIP plugin similar to CUDA?

**Comment by bader** [comment]
@t4c1, to fix CI checks, please, merge latest commits from the `sycl` branch.

**Review by jchlanda — APPROVED** [review]

**Pull request merged**
