### PR TITLE
[Matrix][AMX] Pass to transform matrix operation into amx intrinsics

### PR DESCRIPTION
**Pull request by yubingex007-a11y**
We define the pass which transforms the following matrix
operations function call into amx's intrinsics:
llvm.experimental.matrix.store => llvm.x86.tilestored64.internal
llvm.experimental.matrix.load => llvm.x86.tileloadd64.internal
llvm.experimental.matrix.mad => llvm.x86.tdpbssd(or tdpbf16ps).internal

Example:
Calculate the formatted size according to the real size, layout&type(i8 or
i16).
%val = call void @llvm.experimental.matrix.store.v4i8.p4i8(<8 x i8> %src,
i32* ptr, i64 %stride, i1 false, i32 4, i32 2, metadata !"matrix.rowmajor",
metadata !"matrix.rowmajor", metadata !"scope.subgroup").
=>
%amxsrc = call x86_amx @llvm.x86.cast.vector.to.tile.v4i8(<4 x i8> %src)
%val = call x86_amx @llvm.x86.tilestored64.internal(i32 1, i32 8, i8* ptr,
i64 stride,x86_amx %amxsrc)

### CODE REVIEW

**Comment by bader** [comment]
@yubingex007-a11y, could you add a description to this PR, please? I don't understand what these changes are needed for.

**Comment by yubingex007-a11y** [comment]
> @yubingex007-a11y, could you add a description to this PR, please? I don't understand what these changes are needed for.

Sure.

**Comment by bader** [comment]
> We define the pass which transforms the following matrix
> operations function call into amx's intrinsics:
> llvm.experimental.matrix.store => llvm.x86.tilestored64.internal
> llvm.experimental.matrix.load => llvm.x86.tileloadd64.internal
> llvm.experimental.matrix.mad => llvm.x86.tdpbssd(or tdpbf16ps).internal

I see that this patch also adds `llvm.experimental.matrix.[mad,load,store]` intrinsics.
Do I understand correctly these are added as intermediate layer between front-end and back-end compilers to expose matrix operations in target independent fashion?
It looks like the idea is to lower them to AMX instructions on x86 with AMX support and to something else on other targets. Right?

@andykaylor, who can review this change? I'm not familiar with target back-ends good enough to say if lowering target-independent intrinsics should be in LLVM IR pass or during translation from LLVM IR to MIR or somewhere else.
Probably we should upload this change to reviews.llvm.org and ask for llvm community feedback on that approach. Does it make sense?

**Comment by bader** [comment]
@yubingex007-a11y, are you still planning to commit this change?

**Pull request closed without merging**
