### PR TITLE
[WIP][SYCL][CUDA] Lit exceptions

### PR DESCRIPTION
**Pull request by bjoernknafla**
Fix LIT tests that are not compiled with assertions enabled but call
assert.

Only done for LIT tests that require fixes during work on CUDA.

Signed-off-by: Bjoern Knafla <bjoern@codeplay.com>

### CODE REVIEW

**Comment by bjoernknafla** [comment]
WIP as it requires: https://github.com/intel/llvm/pull/1302

**Comment by bader** [comment]
> Fix LIT tests that are not compiled with assertions enabled but call
> assert.

Aren't assertions enabled by default and should be explicitly disabled with `NDEBUG`?
https://en.cppreference.com/w/cpp/error/assert

**Comment by bjoernknafla** [comment]
@bader You are right and my PRs to replace `assert` with a different macro are not required. Great catch and removes unnecessary code changes/PRs.

I seemingly got confused due to working for too long with CMake and explicit `CMAKE_BUILD_TYPE` settings which for release builds set `NDEBUG`.

**Comment by bader** [comment]
@bjoernknafla, do you want to proceed with these changes?

**Comment by bjoernknafla** [comment]
I need/want to rework this a bit - should I close and reopen it once ready or keep it open and marked as WIP?

**Comment by bader** [comment]
I'm fine to keep it open.

I was confused by your previous comment:
> WIP as it requires: https://github.com/intel/llvm/pull/1302

#1302 is closed, so it was not clear to me whether you decided to abandon this PR or continue with this approach.

**Comment by bjoernknafla** [comment]
As I learned from you, `assert` won’t be compiled out without explicitly setting `NDEBUG`, so I closed the MR that introduced a `CHECK` macro to replace `assert`. This PR needs to be adapted accordingly.

I striked that old comment through now to prevent future confusion.

**Comment by bjoernknafla** [comment]
This PR is old and outdated and I won't be able to get back to it for a while. While the LIT tests could need another revisit to ensure that exceptions are not ignored I suggest to close this PR.

**Comment by bader** [comment]
Thanks for the update.
Closing...

**Pull request closed without merging**
