### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW13)

### PR DESCRIPTION
**Pull request by vmaksimo**
LLVM: llvm/llvm-project@964398ccb1168
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@a9b9ca0bb995949fc3b4a04627857a3ae4e74979

### CODE REVIEW

**Comment by vmaksimo** [comment]
HIP failure is a known issue, already reverted https://github.com/intel/llvm-test-suite/commit/caf5e249ea920dd0df26f8d5190ca6b6452237a8

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Thu 24 Mar 2022 08:38:27 AM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Thu 24 Mar 2022 08:42:02 AM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
