### PR TITLE
[UR][L0] Fix Multi Device Event handling and remove unhandled events from in order wait list

### PR DESCRIPTION
**Pull request by nrspruit**
-pre-commit PR for https://github.com/oneapi-src/unified-runtime/pull/2134

### CODE REVIEW

**Review by aarongreig — APPROVED** [review]

**Comment by pbalcer** [comment]
windows gen12 runner appears broken:
```
Run mkdir install
mkdir: cannot create directory 'install': File exists
Error: Process completed with exit code 1.
```

**Comment by aarongreig** [comment]
@intel/llvm-gatekeepers the windows fail is due to a bad runner, are we still ok merging things while that's broken?

**Comment by steffenlarsen** [comment]
> @intel/llvm-gatekeepers the windows fail is due to a bad runner, are we still ok merging things while that's broken?

It seems like out CI systems have changed since last I had to handle this Windows runner issue, so sadly I can't do much about it until the people in the US who know wakes up.

I have concerns about merging this untested on Windows. How confident are we that these changes won't cause problems on Windows? Is it urgent or can it wait one more day? We could try another rerun and hope another machine gets picked up.

**Comment by aarongreig** [comment]
I don't have any reason to believe this would be particularly safe to merge without windows testing, @pbalcer or @nrspruit can attest to whether it's sufficiently urgent to risk it

**Comment by steffenlarsen** [comment]
It's green now!

**Pull request merged**
