### PR TITLE
[GHA] Uplift Linux GPU RT version to 23.17.26241.22

### PR DESCRIPTION
**Pull request by bb-sycl**
Scheduled drivers uplift

### CODE REVIEW

**Comment by bader** [comment]
@aelovikov-intel, FYI.

**Comment by aelovikov-intel** [comment]
> @aelovikov-intel, FYI.

I somewhat doubt it's the CI because the testing in https://github.com/intel/llvm/pull/10054 finished successfully. Is it possible the drivers are bad/incompatible?

**Comment by bader** [comment]
> > @aelovikov-intel, FYI.
> 
> I somewhat doubt it's the CI because the testing in #10054 finished successfully. Is it possible the drivers are bad/incompatible?

From the logs:

```
Traceback (most recent call last):
  File "/opt/get_release.py", line 19, in <module>
    release = get_release_by_tag(repo, tag)
  File "/opt/get_release.py", line 6, in get_release_by_tag
    release = urlopen("https://api.github.com/repos/" + repo + "/releases/tags/" + tag).read()
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: rate limit exceeded
```

**Comment by aelovikov-intel** [comment]
Re-run doesn't have that issue.

**Comment by bader** [comment]
> Re-run doesn't have that issue.

Okay, but we should think about preventive cure for `urllib.error.HTTPError: HTTP Error 403: rate limit exceeded` error. Just let it happen and wait + re-run, doesn't sound like a good solution.

**Comment by bader** [comment]
> > Re-run doesn't have that issue.
> 
> Okay, but we should think about preventive cure for `urllib.error.HTTPError: HTTP Error 403: rate limit exceeded` error. Just let it happen and wait + re-run, doesn't sound like a good solution.

FYI: I found a bug report for that issue - https://github.com/intel/llvm/issues/8462.

**Review by bader — APPROVED** [review]

**Comment by dm-vodopyanov** [comment]
Post-commit failure: 
```
Unexpectedly Passed Tests (1):
  SYCL :: ESIMD/hardware_dispatch.cpp
```

For these automated Linux GPU driver updates we could run broader scope of testing on pre-commit step automatically.

**Comment by dm-vodopyanov** [comment]
Fix: https://github.com/intel/llvm/pull/10132

**Comment by aelovikov-intel** [comment]
> For these automated Linux GPU driver updates we could run broader scope of testing on pre-commit step automatically.

I think that could be as easy as making https://github.com/intel/llvm/blob/1bb56482c6eb5c822d4bbb0689e78b5ca96f49a1/.github/workflows/sycl_precommit.yml#L69 conditional on files changed (i.e., don't use "fused" `lin_intel` task and prefer separate `l0_gen9`, `ocl_gen9` and `ocl_x64`).

Condition could probably be based on `contains(needs.detect_changes.outputs.filters, 'drivers_and_configs')` - see https://github.com/intel/llvm/blob/1bb56482c6eb5c822d4bbb0689e78b5ca96f49a1/.github/workflows/sycl_detect_changes.yml#L50-L59.

**Comment by bader** [comment]
@dm-vodopyanov, @aelovikov-intel, could you clarify what testing is missing in this PR pre-commit? Don't we run ESIMD tests on GPU in **all** pre-commits?

**Comment by aelovikov-intel** [comment]
https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/README.md?plain=1#L34-L44

We don't test for `XFAIL` in pre-commit.

**Comment by bader** [comment]
> https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/README.md?plain=1#L34-L44
> 
> We don't test for `XFAIL` in pre-commit.

This text doesn't say if there is any difference in `XFAIL` semantics between post- and pre- commits. Why does the test fail in post-commit?

**Comment by aelovikov-intel** [comment]
> So just having additional devices in the system changes the status of the test?

No.

**Pull request merged**
