### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW09)

### PR DESCRIPTION
**Pull request by vmaksimo**
LLVM: llvm/llvm-project@55639c2
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@f797de28e4f2d87e0f401faa453460f1e6e5a7ee

### CODE REVIEW

**Comment by vmaksimo** [comment]
Hi, @npmiller! I've got the `Clang :: Driver/amdgpu-openmp-toolchain.c` test failed after fixing build failure in 00b7a3aba. 
I found that you've added the third arg to the `getCommonDeviceLibNames()` func earlier. Could you please suggest if I resolved the issue properly, or should I change the offload kind to something else? 
Thanks!

**Comment by npmiller** [comment]
Hello @vmaksimo I've had a look the build fix looks fine to me, I don't think the new test failure is related to that.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Tue 22 Feb 2022 08:17:27 AM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Tue 22 Feb 2022 08:20:44 AM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
