### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW09 2024)

### PR DESCRIPTION
**Pull request by sys-ce-bb**
LLVM: llvm/llvm-project@9f99eda1208787364b1a381b2d4e146fc4868cd5
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@2cd8b788edc53ed144eb8644781b37a741071b09

### CODE REVIEW

**Comment by jsji** [comment]
e2e failures are common to others, also seen in https://github.com/intel/llvm/actions/runs/8104206945/job/22150442787.

**Comment by jsji** [comment]
This is ready for review.
- [ ] [Revert "[HIP] Allow partial linking for -fgpu-rdc (#81700)"](https://github.com/intel/llvm/pull/12868/commits/5c1437631e3b22cccc72d9e0a0d492ec5e7429a5) Conflict with bc support in sycl, @LU-JOHN is working a fix, reverted first according to his suggestion.
- [ ] [Revert "Fix OpGroupNonUniformBroadcast version requirement (](https://github.com/intel/llvm/pull/12868/commits/bbf3800adf1209d062ddb49555bb4f36120575ad)https://github.com/intel/llvm/pull/2378[)"](https://github.com/intel/llvm/pull/12868/commits/bbf3800adf1209d062ddb49555bb4f36120575ad)  @MrSidims helped to have a look. Unfortunately id passed to OpGroupNonUniformBroadcast is always runtime value for SYCL headers. Hence we need to revert the patch.  Also recorded in  https://github.com/intel/llvm/issues/7592.

**Comment by jsji** [comment]
@LU-JOHN @MrSidims Would you please help to add comments or approve explicitly so that this can be merged. Thanks.

**Review by MrSidims — APPROVED** [review]
The revert is lgtm

**Comment by jsji** [comment]
@LU-JOHN Would you please help to add comments or approve explicitly so that this can be merged. Thanks.

**Comment by LU-JOHN** [comment]
Reversion is good.  Community commit has a bug when unbundling an archive of objects.  Community issue tracked in:
 
https://github.com/llvm/llvm-project/issues/83509

**Comment by jsji** [comment]
@bader @intel/llvm-gatekeepers Can we get this merged. Thanks.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Tue 05 Mar 2024 07:00:21 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Tue 05 Mar 2024 07:07:47 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
