### PR TITLE
[clang-offload-wrapper] Clean-up the code a bit

### PR DESCRIPTION
**Pull request by psamolysov-intel**
The following changes are incorporated to the patch:
 - Remove second call to cl::cat for properties
 - Remove unused struct OffloadKindToUint
 - Use std::enable_if_t wherever possible
 - Fix a typo in a comment

### CODE REVIEW

**Review by kbobrovs — DISMISSED** [review]

**Comment by AlexeySachkov** [comment]
@psamolysov-intel, please note that this tool comes from upstream LLVM, so if that is possible, all refactoring should be there first to avoid extra (especially non-functional) customizations

**Comment by psamolysov-intel** [comment]
@AlexeySachkov Thank you for the comment. I'll propose this small refactoring to the upstream and if they won't accept/land it by some reasons then open this PR for merging. Currently, the PR is in draft.

**Comment by psamolysov-intel** [comment]
Hm... I've double checked, the proposed changes are actual for the version of the tool in [intel/llvm](https://github.com/intel/llvm).  So, the PR can be merged and should not add any extra needs of effort for pulldowns.

**Review by mlychkov — APPROVED** [review]

**Comment by psamolysov-intel** [comment]
The `ArgSeq` member function template `get` invocations on lines 2155-2180: `ArgSeq.template get<X>()` can be rewritten without using the `template` keyword: `ArgSeq.get<X>()` because the `.template` syntax is required inside template definitions and when the object depends on the template argument only. But I prefer to save them as is, I'm not sure all the used compilers accept the code without `.template` although they have to.

**Pull request merged**
