### PR TITLE
[SYCL] Move use of __builtin_sycl_mark_kernel_name to fix uses

### PR DESCRIPTION
**Pull request by erichkeane**
The CFE uses the function argument to detect the kernel type for the 
unnamed lambdas.  However, if the user specifies the name of the kernel
we still use THAT.  At that point, we can't "mark" that type, otherwise it
gets the alternate mangling.  

We assumed this didn't happen when this was in KernelInfoData, so we needed
to get this to be in another location.  It seems the most direct place after
@AlexeySachkov and I looked at it, that this is the one location where we
best 'see' the unnamed-kernel names in order to properly mark them.

### CODE REVIEW

**Comment by erichkeane** [comment]
@AlexeySachkov : it looks like at least kernel_functor.cpp creates an unnamed parallel_for without unnamed-lambda extension.

however, the unnamed-lambda test is particularly concerning to me at the moment, I'm not sure why we are in a situation where we're not creating it with the right type...

**Comment by erichkeane** [comment]
@romanovvlad /anyone from Libraries:

it seems improper that we should allow "auto_name" at all without the unique-stable-name extension.  I think this ends up breaking the language if we allow this (like with the case of functor/functor_inheritance.cpp).

**Comment by romanovvlad** [comment]
> 
> 
> @romanovvlad /anyone from Libraries:
> 
> it seems improper that we should allow "auto_name" at all without the unique-stable-name extension. I think this ends up breaking the language if we allow this (like with the case of functor/functor_inheritance.cpp).

Sounds reasonable. We could add a diagnostic for that in headers, but I think we would like to enable ``unnamed-lambda` extension by default anyway.
+ @vladimirlaz

**Comment by erichkeane** [comment]
> 
> 
> > @romanovvlad /anyone from Libraries:
> > it seems improper that we should allow "auto_name" at all without the unique-stable-name extension. I think this ends up breaking the language if we allow this (like with the case of functor/functor_inheritance.cpp).
> 
> Sounds reasonable. We could add a diagnostic for that in headers, but I think we would like to enable ``unnamed-lambda` extension by default anyway.
> 
>     * @vladimirlaz

It would seem to me that it would be more appropriate to remove the 'auto_name' default arguments when the unnamed-lambdas macro isn't present.  That way we end up just rejecting the overloads in the compiler.

**Comment by erichkeane** [comment]
So I don't have any idea here, this bug is somewhere in the way with how library deals with kernel names, but I don't have a good hold of where this could be.  I think someone with more library experience than me needs to take this over.

**Comment by AlexeySachkov** [comment]
@erichkeane, @romanovvlad, I've pushed a version which passes `check-sycl` locally, hopefully that is a correct approach, please take a look

**Comment by erichkeane** [comment]
I think that should work?  Hopefully the rest of pre-commit agrees :)

**Pull request closed without merging**
