### PR TITLE
[SYCL][E2E] Switch some of bindless_images/* tests to use <sycl/detail/core.hpp>

### PR DESCRIPTION
**Pull request by aelovikov-intel**

### CODE REVIEW

**Comment by isaacault** [comment]
So this is all of the bindless image tests except for

- `sycl/test-e2e/bindless_images/sampling_1D.cpp`
- `sycl/test-e2e/bindless_images/vulkan_interop/*`

Is there a specific reason these have been omitted?

**Comment by aelovikov-intel** [comment]
> Is there a specific reason these have been omitted?

Just because they weren't as simple to update. I'm currently focusing on volume and not completeness.

**Comment by aelovikov-intel** [comment]
@intel/bindless-images-reviewers , ping.

**Review by przemektmalon — APPROVED** [review]
LGTM.

I can see why `sycl/test-e2e/bindless_images/sampling_1D.cpp` was omitted due to the feature test macro not being defined, however, the `sycl/test-e2e/bindless_images/vulkan_interop/*` tests work fine for me when using the updated includes without any other changes.

**Comment by aelovikov-intel** [comment]
> however, the `sycl/test-e2e/bindless_images/vulkan_interop/*` tests work fine for me when using the updated includes without any other changes.

I don't have access to configuration where that could be verified, so I decided not to change it blindly. Do we even run that in CI or is it just local setup for you?

**Comment by przemektmalon** [comment]
> > however, the `sycl/test-e2e/bindless_images/vulkan_interop/*` tests work fine for me when using the updated includes without any other changes.
> 
> I don't have access to configuration where that could be verified, so I decided not to change it blindly. Do we even run that in CI or is it just local setup for you?

To my knowledge the interop tests aren't run in CI, I verified it locally.

**Pull request merged**
