### PR TITLE
[SYCL][ABI-break] Remove redundant methods under sycl::handler

### PR DESCRIPTION
**Pull request by raaiq1**
Removed the following redundant methods:
-  void extractArgsAndReqsFromLambda(char *LambdaPtr, size_t KernelArgsNum,
                               const detail::kernel_param_desc_t *KernelArgs);
-  void processArg(void *Ptr, const detail::kernel_param_kind_t &Kind,
                  const int Size, const size_t Index, size_t &IndexShift,
                  bool IsKernelCreatedFromSource);

-  static id<_I_> getDelinearizedIndex(const range<_I_> Range, const size_t Index);
   where _I_ is could be {1,2,3};

### CODE REVIEW

**Review by aelovikov-intel — DISMISSED** [review]
Looks reasonable, but I don't have enough experience to see if it's "complete".

Anyway, it leaves the code in a better state than before, so LGTM.

**Review by cperkinsintel — DISMISSED** [review]
LGTM

**Comment by keryell** [comment]
Minor style wording: methods are names member functions in C++.

**Comment by raaiq1** [comment]
Ohh, yeah, sorry. Still still stuck in Java terms

**Comment by raaiq1** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1114

**Comment by raaiq1** [comment]
@intel/llvm-gatekeepers slight ping to merge commit. Thanks

**Comment by raaiq1** [comment]
@intel/llvm-gatekeepers slight ping to merge commit. Thanks

**Comment by pvchupin** [comment]
@raaiq1, can you resolve a conflict please?

**Review by aelovikov-intel — APPROVED** [review]

**Comment by raaiq1** [comment]
Alternate PR at: https://github.com/intel/llvm/pull/6529

**Pull request closed without merging**
