### PR TITLE
[SYCL][E2E] Refactor/fix bfloat16 test

### PR DESCRIPTION
**Pull request by aelovikov-intel**
Fixes ansi-alias violation and reads from uninitialized buffers. Fixes https://github.com/intel/llvm/issues/13790.

### CODE REVIEW

**Comment by aelovikov-intel** [comment]
Substitutes https://github.com/intel/llvm/pull/14059.

**Review by uditagarwal97 — APPROVED** [review]
Overall, the changes looks good to me. I'm wondering if we should also extend this test to also test for BF16 builtins on the host?

**Comment by aelovikov-intel** [comment]
> I'm wondering if we should also extend this test to also test for BF16 builtins on the host?

That would be an unrelated change.

**Comment by uditagarwal97** [comment]
> > I'm wondering if we should also extend this test to also test for BF16 builtins on the host?
> 
> That would be an unrelated change.

That can be done in a separate PR, not necessarily now.

**Comment by aelovikov-intel** [comment]
> That can be done in a separate PR, not necessarily now.

Just to be clear, I'm not planning on working on that.

**Comment by uditagarwal97** [comment]
> > That can be done in a separate PR, not necessarily now.
> 
> Just to be clear, I'm not planning on working on that.

That's fine - I can create an internal tracker for this.

**Review by AlexeySachkov — APPROVED** [review]

**Comment by aelovikov-intel** [comment]
Failures are unrelated. Since this is a one test change to fix flaky issue merging without green CI.

**Pull request merged**
