### PR TITLE
[SYCL] Allow unittests to use drainThreadPool method on Win

### PR DESCRIPTION
**Pull request by KseniyaTikhomirova**
Signed-off-by: Tikhomirova, Kseniya <kseniya.tikhomirova@intel.com>

### CODE REVIEW

**Comment by KseniyaTikhomirova** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1462

**Review by romanovvlad — APPROVED** [review]

**Comment by KseniyaTikhomirova** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1462

**Comment by KseniyaTikhomirova** [comment]
llvm-test_suite linux failure is infrastructure issue. win passed

**Comment by bader** [comment]
Why do you prefer `/verify with` <merged PR> instead of `/testwin`?

**Comment by KseniyaTikhomirova** [comment]
> Why do you prefer `/verify with` instead of `/testwin`?

It seems that it doen't run llvm-test_suite tests

**Comment by KseniyaTikhomirova** [comment]
> Why do you prefer `/verify with` instead of `/testwin`?

According to Chris https://github.com/intel/llvm/pull/7908
"The "/testwin" directive only makes sure something is buildable on windows and the in-tree tests are run, but not the llvm-test-suite tests on Windows."

**Comment by bader** [comment]
Ah... I forget that https://github.com/intel/llvm/pull/7477 hasn't been merged yet.

**Pull request merged**
