### PR TITLE
[Buildbot] Add windows ocloc for windows CI process

### PR DESCRIPTION
**Pull request by yinyangsx**
Add ocloc on windows.

Signed-off-by: yinyangsx <yin.yang@intel.com>

### CODE REVIEW

**Comment by vladimirlaz** [comment]
According to LIT tests log ocloc tools was not found on windows:
see http://ci.llvm.intel.com:8010/#/builders/18/builds/7334:
```
llvm-lit.py: D:\buildbot\Product_worker_intel\sycl-win-x64-pr\llvm.src\sycl\test\on-device\lit.cfg.py:223: warning: Couldn't find pre-installed AOT device compiler ocloc
```
Please make sure that ocloc is found by LIT infra

**Review by vladimirlaz — CHANGES_REQUESTED** [review]
please address comment: https://github.com/intel/llvm/pull/2958#issuecomment-751597173

**Comment by yinyangsx** [comment]
> please address comment: [#2958 (comment)](https://github.com/intel/llvm/pull/2958#issuecomment-751597173)

New win lit job trigged,  should be pass.

**Review by vladimirlaz — APPROVED** [review]

**Comment by yinyangsx** [comment]
It's ready, please merge.

**Pull request merged**
