### PR TITLE
[SYCL] Expansion of the class CG to CommandGroup

### PR DESCRIPTION
**Pull request by denis-kabanov**
Expansion of the class "CG" to "CommandGroup" to avoid possible name collisions.

### CODE REVIEW

**Comment by romanovvlad** [comment]
I'm curious, what is the motivation for this change?
Also if we are doing renaming, perhaps, we should add double underscores in the type name to avoid collisions - `__CommandGroup`

**Comment by denis-kabanov** [comment]
> I'm curious, what is the motivation for this change?
> Also if we are doing renaming, perhaps, we should add double underscores in the type name to avoid collisions - `__CommandGroup`

Yes, you are right, I did this to prevent possible name collisions. However, I don't think that additional underscores is necessary because there (in a runtime) is a lot of class names without __, also it is already unlikely that the user will try to use #define CommandGroup.

**Comment by bader** [comment]
+1. The purpose of this change is to avoid collision with macro, which are usually use ALL_CAPS, CamelCase seems to be good enough.

**Comment by romanovvlad** [comment]
> 
> 
> +1. The purpose of this change is to avoid collision with macro, which are usually use ALL_CAPS, CamelCase seems to be good enough.

Eventually we would like to have every non-public entity to be prefixed with `__`.  I'm OK leaving the patch as is, but do not see why it cannot be renamed to more "final" version since we are renaming it anyway.

**Comment by denis-kabanov** [comment]
> > +1. The purpose of this change is to avoid collision with macro, which are usually use ALL_CAPS, CamelCase seems to be good enough.
> 
> Eventually we would like to have every non-public entity to be prefixed with `__`. I'm OK leaving the patch as is, but do not see why it cannot be renamed to more "final" version since we are renaming it anyway.

At this time I prefer to leave this PR without changes, because many classes were left without __. Therefore, if we want to add __, then we must do it for each class at once.

**Comment by alexbatashev** [comment]
> > > +1. The purpose of this change is to avoid collision with macro, which are usually use ALL_CAPS, CamelCase seems to be good enough.
> > 
> > 
> > Eventually we would like to have every non-public entity to be prefixed with `__`. I'm OK leaving the patch as is, but do not see why it cannot be renamed to more "final" version since we are renaming it anyway.
> 
> At this time I prefer to leave this PR without changes, because many classes were left without __. Therefore, if we want to add __, then we must do it for each class at once.

I disagree. Renaming many classes at once makes it a) hard to review pull request due to large amount of changes b) hard to merge such pull request due to frequent conflicts.

**Comment by bader** [comment]
> I disagree. Renaming many classes at once makes it a) hard to review pull request due to large amount of changes b) hard to merge such pull request due to frequent conflicts.

I agree with Denis. Let's address one problem at a time and make the code base consistent.

a) if change is mechanical like "rename a class by adding __", it's easy to review.
b) if change is simple and not controversial (I strongly recommend to discuss new naming nomenclature before opening a pull request), it should be merged quite fast, so I don't expect merge conflicts for a new pull request.

**Comment by denis-kabanov** [comment]
> > > > +1. The purpose of this change is to avoid collision with macro, which are usually use ALL_CAPS, CamelCase seems to be good enough.
> > > 
> > > 
> > > Eventually we would like to have every non-public entity to be prefixed with `__`. I'm OK leaving the patch as is, but do not see why it cannot be renamed to more "final" version since we are renaming it anyway.
> > 
> > 
> > At this time I prefer to leave this PR without changes, because many classes were left without __. Therefore, if we want to add __, then we must do it for each class at once.
> 
> I disagree. Renaming many classes at once makes it a) hard to review pull request due to large amount of changes b) hard to merge such pull request due to frequent conflicts.

**Comment by denis-kabanov** [comment]
Sorry, accidentally closed the PR.

**Comment by alexbatashev** [comment]
> Let's address one problem at a time and make the code base consistent.

Why is collision with `CG` considered to be a problem and collision with `CommandGroup` not? Because the first one is all caps?

**Comment by denis-kabanov** [comment]
> > Let's address one problem at a time and make the code base consistent.
> 
> Why is collision with `CG` considered to be a problem and collision with `CommandGroup` not? Because the first one is all caps?

Yes.

**Review by alexbatashev — APPROVED** [review]

**Pull request merged**
