### PR TITLE
[WIP][NOT TESTED][SYCL] Enable post enqueue cleanup for empty command and enqueue dependent tasks after host task completion

### PR DESCRIPTION
**Pull request by KseniyaTikhomirova**
Previously empty command was scheduled to cleanup as dependency for other tasks. Although if we have host_task without any task that is dependent on it - empty cmd deletion will not happen, corresponding resources are not released. This commit is fixing that case and schedule empty command deletion earlier.

Testing: E2E test for memory leaks with llvm-test-suite/SYCL/Basic/event.cpp
Signed-off-by: Tikhomirova, Kseniya <kseniya.tikhomirova@intel.com>

### CODE REVIEW

**Comment by bader** [comment]
> /verify

Did you mean "/summary:run"?

**Comment by KseniyaTikhomirova** [comment]
> > /verify
> 
> Did you mean "/summary:run"?

seems to be so, thank you

**Comment by KseniyaTikhomirova** [comment]
this fix will not work as expected, will redesign

**Pull request closed without merging**
