### PR TITLE
[ESIMD][E2E] Enable few cases in atomic_update after gpu driver update

### PR DESCRIPTION
**Pull request by v-klochkov**

### CODE REVIEW

**Review by sarnex — APPROVED** [review]
Nice!

**Comment by v-klochkov** [comment]
The ESIMD/aot_mixed.cpp fail is not related to other 2 E2E tests updated in this PR.
Also, ESIMD/aot_mixed.cpp is fixed here: https://github.com/intel/llvm/pull/12650

**Comment by ldrumm** [comment]
ESIMD/unified_memory_api/atomic_update_acc_dg2_pvc_cmpxchg.cpp seems to [be broken by this patch](https://github.com/intel/llvm/actions/runs/7821136105/job/21339068624). Could you please forward a fix or revert?

**Comment by ldrumm** [comment]
`ESIMD/unified_memory_api/atomic_update_acc_dg2_pvc_cmpxchg.cpp` includes `atomic_update_acc_dg2_pvc.cpp` which itself includes `Inputs/atomic_update.hpp` changed here

**Pull request merged**
