### PR TITLE
[SYCL] Add sycl_ext_intel_math_inv

### PR DESCRIPTION
**Pull request by jinge90**
This PR aims to add sycl::ext::intel::math::inv for fp32, fp64, half, half2 to sycl intel math header. The real implementation has been provided by SYCL device library via __imf_inv/invf16/invf.

### CODE REVIEW

**Comment by jinge90** [comment]
Hi, @zettai-reido and @akolesov-intel
Could you take a look at this PR?
Thanks very much.

**Review by zettai-reido — APPROVED** [review]
LGTM

**Comment by jinge90** [comment]
Hi, @intel/llvm-reviewers-runtime and @bso-intel 
Could you take a look at this PR?
Thanks very much.

**Comment by aelovikov-intel** [comment]
Where is the test PR for this?

**Comment by jinge90** [comment]
> Where is the test PR for this?

Hi, @aelovikov-intel 
This PR aims to add a new API "inv" in sycl::intel::ext::math, this API is required by SYCLomatic tool. This API depends on "__imf_inv" provided by libdevice.
Thanks very much.

**Comment by aelovikov-intel** [comment]
It doesn't need mean we don't need to test this new API as part of this project.

**Comment by jinge90** [comment]
> It doesn't need mean we don't need to test this new API as part of this project.

Hi, @aelovikov-intel 
I will add a test in llvm-test-suite and once this PR is merged, SYCLomatic developers will add test in their side too.
Thanks very much.

**Comment by jinge90** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1571

**Comment by jinge90** [comment]
> Where is the test PR for this?

Hi, @aelovikov-intel 
The test PR is in https://github.com/intel/llvm-test-suite/pull/1571
Thanks very much.

**Review by aelovikov-intel — APPROVED** [review]

**Comment by jinge90** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1571

**Comment by jinge90** [comment]
Hi, @bso-intel 
Could you take a look at this PR?
Thanks very much.

**Review by bso-intel — APPROVED** [review]
LGTM

**Comment by jinge90** [comment]
Hi, @bader and @aelovikov-intel 
Could you help merge this PR?
Thanks very much.

**Comment by bader** [comment]
> Could you help merge this PR?

@jinge90, please, ping @intel/llvm-gatekeepers team for future merge requests.

More on that here - https://github.com/intel/llvm/blob/sycl/CONTRIBUTING.md#merge.

**Comment by bader** [comment]
Please, add `[SYCL]` tag to the PR title.

**Comment by jinge90** [comment]
Hi, @intel/llvm-gatekeepers 
Could you help merge this patch?
Thanks very much.

**Comment by jinge90** [comment]
> Please, add `[SYCL]` tag to the PR title.

Done.
Thanks very much.

**Pull request merged**
