### PR TITLE
[SYCL][L0] Use compute engine for memory fill command

### PR DESCRIPTION
**Pull request by smaslov-intel**
E2E test in https://github.com/intel/llvm-test-suite/pull/1273
Signed-off-by: Sergey V Maslov <sergey.v.maslov@intel.com>

### CODE REVIEW

**Review by steffenlarsen — APPROVED** [review]
Docs LGTM!

**Review by asudarsa — APPROVED** [review]
LGTM. If possible, please add a comment about why 'fill' operations needs to go to compute engine.

Thanks

**Comment by smaslov-intel** [comment]
> If possible, please add a comment about why 'fill' operations needs to go to compute engine.

I intentionally didn't put any explanation because I don't know a good one. Added env var will allow users to check both and use whatever works best for them.

**Comment by smaslov-intel** [comment]
@steffenlarsen, @againull  : can this be merged? (the pre-commit failure isn't related)

**Pull request merged**
