### PR TITLE
[XPTI] Rename `ur` to `ur.call` in XPTI

### PR DESCRIPTION
**Pull request by RossBrunton**
Closes: #14922

### CODE REVIEW

**Comment by RossBrunton** [comment]
Requires UR changes from https://github.com/oneapi-src/unified-runtime/pull/1940

**Comment by RossBrunton** [comment]
Having a bit of trouble getting CI to behave, but I think the code here is correct and the UR change is approved.

Could someone from @intel/unified-runtime-reviewers and @intel/llvm-reviewers-runtime have a quick look at this and let me know if there's anything I need to change with the code?

**Comment by steffenlarsen** [comment]
CI looks green to me! Just need a conflict resolution.

**Review by steffenlarsen — APPROVED** [review]

**Review by omarahmed1111 — APPROVED** [review]

**Comment by omarahmed1111** [comment]
@intel/llvm-gatekeepers Please merge, Thanks!

**Comment by omarahmed1111** [comment]
This PR bump includes PRs:
* https://github.com/oneapi-src/unified-runtime/pull/1986
* https://github.com/oneapi-src/unified-runtime/pull/1965
* https://github.com/oneapi-src/unified-runtime/pull/1864
* https://github.com/oneapi-src/unified-runtime/pull/1858
* https://github.com/oneapi-src/unified-runtime/pull/1991
* https://github.com/oneapi-src/unified-runtime/pull/1940

**Pull request merged**
