### PR TITLE
[SYCL] Add Clang support for FPGA loop fusion function attributes

### PR DESCRIPTION
**Pull request by elizabethandrews**
This patch adds support for FPGA function attributes loop_fuse and
loop_fuse_independent. [[intel::loop_fuse(N)]] is a strong request,
to the extent possible, to fuse loops within the function, that are
contained in at most N-1 other loops within the function. If the
optional parameter N is omitted, it is a strong request, to the extent
possible, to fuse loops within the function that are not contained in
any other loop within the function. [[intel::loop_fuse_independent(N)]]
is used to guarantee that fusion safety analysis can ignore
negative-distance dependences between these loops.

FrontEnd Specifications:

The attributes take one optional parameter, a constant integral
expression between 0 and 1024*1024. The paramter may be a template
parameter.

The same function definition can have atmost one of these two attributes.

The attributes can be applied explictly to kernel. However, attributes
should not be propagated to callers i.e it should not be propagated from
device functions to kernel.

LLVM IR is function metadata as follows:

  define i32 @foo() !loop_fuse !0
  !0 = !{i32 N, i32 D}

where N is the value specified by the optional attribute argument. If
the optional argument is omitted, N is set to 1. D is equal to 0 for
[[intel::loop_fuse]] and 1 for [[intel::loop_fuse_independent]].

Signed-off-by: Elizabeth Andrews <elizabeth.andrews@intel.com>

### CODE REVIEW

**Comment by elizabethandrews** [comment]
ClangFormat is failing on changes bought in through merge from intel/llvm, not my changes. How do I handle this @bader?

**Comment by bader** [comment]
> ClangFormat is failing on changes bought in through merge from intel/llvm, not my changes. How do I handle this @bader?

You can run clang-format (version 9.x) locally - e.g. using clang-format-diff script https://clang.llvm.org/docs/ClangFormat.html#script-for-patch-reformatting

Another options is to download the patch CI system saves in artifacts and apply it as additional commit in this PR.
https://github.com/intel/llvm/pull/2876/checks?check_run_id=1519244214 - look for "Artifacts" in top right corner.

**Comment by elizabethandrews** [comment]
> > ClangFormat is failing on changes bought in through merge from intel/llvm, not my changes. How do I handle this @bader?
> 
> You can run clang-format (version 9.x) locally - e.g. using clang-format-diff script https://clang.llvm.org/docs/ClangFormat.html#script-for-patch-reformatting

Won't this create a commit with unrelated changes in this PR?

**Comment by bader** [comment]
> > > ClangFormat is failing on changes bought in through merge from intel/llvm, not my changes. How do I handle this @bader?
> > 
> > 
> > You can run clang-format (version 9.x) locally - e.g. using clang-format-diff script https://clang.llvm.org/docs/ClangFormat.html#script-for-patch-reformatting
> 
> Won't this create a commit with unrelated changes in this PR?

It shouldn't not. The patch should fix formatting fir the diff between your branch and PR target branch i.e. for all commits in this PR and nothing else.

**Comment by elizabethandrews** [comment]
> > > > ClangFormat is failing on changes bought in through merge from intel/llvm, not my changes. How do I handle this @bader?
> > > 
> > > 
> > > You can run clang-format (version 9.x) locally - e.g. using clang-format-diff script https://clang.llvm.org/docs/ClangFormat.html#script-for-patch-reformatting
> > 
> > 
> > Won't this create a commit with unrelated changes in this PR?
> 
> It shouldn't not. The patch should fix formatting fir the diff between your branch and PR target branch i.e. for all commits in this PR and nothing else.

Hmm..I'm not sure if I messed up the merge somehow. The tests are failing because of a warning generated on code I didn't add.  I think I'll just try opening another PR

**Comment by elizabethandrews** [comment]
Replaced PR with - https://github.com/intel/llvm/pull/2877

**Pull request closed without merging**
