### PR TITLE
[SYCL] Disallow local accessor misuse

### PR DESCRIPTION
**Pull request by mmoadeli**
* According to the [specification](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:accessor.local) a local accessor must not be used in a SYCL kernel function that is invoked via single_task or via the simple form of parallel_for that takes a range parameter.
* Modifies existing misuse in tests.
* This PR was once reviewed and merged in, but it was reverted as needed AccessTargetMask as an exported symbol on Windows to be added.

### CODE REVIEW

**Comment by mmoadeli** [comment]
@steffenlarsen, @bader 
This PR was once reviewed and merged in, but it was reverted as needed AccessTargetMask as an exported symbol on Windows to be added, as advised by Steffen. 
Regarding another request to update SYCL-CTS accordingly, I could not find any instance where the update to be needed.

**Review by steffenlarsen — APPROVED** [review]
LGTM!

**Comment by aelovikov-intel** [comment]
```
parallel_for(range, reduction, kernel)
```

is implemented internally as calling `parallel_for(nd_range, kernel_wrapper)`. Would our behavior after this PR match the spec in this scenario?

**Comment by mmoadeli** [comment]
> ```
> parallel_for(range, reduction, kernel)
> ```
> 
> 
>     
>   
> 
> is implemented internally as calling `parallel_for(nd_range, kernel_wrapper)`. Would our behavior after this PR match the spec in this scenario?

This PR implements the diagnostic mentioned in [Specification-Local accessor](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:accessor.local). This is called before the process reaches the  internal implementation mentioned above. I do not see any concern on this.

**Pull request merged**
