### PR TITLE
[ESIMD] Renaming ESIMD APIs: format -> bit_cast_view

### PR DESCRIPTION
**Pull request by DenisBakhvalov**

### CODE REVIEW

**Comment by DenisBakhvalov** [comment]
Tagging @Ruyk and @iburyl, who originally requested this change in API some time ago.

**Comment by Pennycook** [comment]
`std::bit_cast` is a free-function, and it's a little confusing to have a `bit_cast` member function with different template arguments.

Is it possible to support your use-cases if you re-use the existing `sycl::bit_cast` (because `std::bit_cast` isn't available until C++20)?  Something like the below:
```c++
simd<float, 32> v1;
auto m1 = sycl::bit_cast<simd_view<float, 4, 8>>(v1);
```

I think `simd_view` is the correct type, but I'm not sure because the examples all use `auto`.

**Comment by kbobrovs** [comment]
I think `bit_cast` is a bad replacement, as in C++ it copies the argument, whereas here it creates a read/write view into the argument. `bit_cast_view` or something like this would be better.

> `auto m1 = simd_view<float, 4, 8>(v1);`

copy constructor is disabled for simd_view.
also, assigning from one simd_view to another means copying data between underlying simd objects

**Comment by kbobrovs** [comment]
\+ @iburyl

**Comment by iburyl** [comment]
That one could be nice:

`auto m1 = simd_view<float, 4, 8>(v1);`

but it is not how it will work now, because simd_view takes a region type as a second template parameter.
With that it will become something like that, which is not that nice:

`auto m1 = simd_view<float, region2d_t<float, 4, 1, 8, 1>>(v1);`

I guess, `bit_cast_view` member function is a reasonable compromise. It keeps some connection with `std::bit_cast` function, but also different enough to be:

- a member function,
- not making a copy and
- having different template parameters set.

**Comment by Pennycook** [comment]
> copy constructor is disabled for simd_view.
> also, assigning from one simd_view to another means copying data between underlying simd objects

But in this case, isn't the user trying to construct a `simd_view` from a `simd`?  We could choose to allow that without enabling copy construction from another `simd_view`.


> but it is not how it will work now, because simd_view takes a region type as a second template parameter.
> With that it will become something like that, which is not that nice:
>
> ```
> auto m1 = simd_view<float, region2d_t<float, 4, 1, 8, 1>>(v1);
> ```

Eugh, you're right.  I suppose `make_simd_view<float, 4, 8>` could work?


> `bit_cast_view` or something like this would be better.
> I guess, `bit_cast_view` member function is a reasonable compromise. It keeps some connection with `std::bit_cast` function...

I think the connection to `bit_cast` is a weakness if this doesn't actually perform a bit-cast.  The only reason to re-use the name would be to help developers understand what this function does, and if it does something different then it's not helpful.

It seems to me like there are a few different use-cases here.  Some of them are tied to bit-cast, but not all of them.  I think bit-cast makes sense for cases where the user is reinterpreting the bytes of a `simd`, but not trying to create a view or change the shape:
```c++
simd<float, 4> f; // NB: 128 bits
simd<char, 16> c = sycl::bit_cast<simd<char, 16>>(f);
... // do something with c
f = sycl::bit_cast<simd<float, 4>>(c);
```

The compiler can optimize these casts away when it knows `f` and `c` can use the same registers, just like a regular non-`simd` `bit_cast`.

Creating a `simd_view` that references an underlying `simd` with a different shape strikes me as a very different concept with quite different semantics.  My preference here would be to tie this to one of the following:
1. Constructing/making a `simd_view` from a `simd`
2. "Reshaping" (bikeshed later) a `simd` via a `simd_view`
3. Some brand-new type of cast, like `view_cast`

**Comment by DenisBakhvalov** [comment]
I implemented the `maske_simd_view` suggestion from @Pennycook, all the ESIMD tests are passing.

@Pennycook, do you think we need a `sycl::bit_cast` for `simd` types?
Can a user just do the following:
```cpp
  simd<int, 8> r = 0x0FF00F0F;
  simd <short, 16> v = make_simd_view<short>(r);
```

**Comment by Pennycook** [comment]
> I implemented the `maske_simd_view` suggestion from @Pennycook, all the ESIMD tests are passing. I will clean up the patch later if the new API will be approved.
> 
> @Pennycook, do you think we need a `sycl::bit_cast` for `simd` types?
> Can a user just do the following:
> 
> ```c++
>   simd<int, 8> r = 0x0FF00F0F;
>   simd <short, 16> v = make_simd_view<short>(r);
> ```

`bit_cast` is the preferred method for this sort of bit conversion, and so I think it should be supported for SIMD types irrespective of what happens with `simd_view`.

That said, I think the overlap in functionality here is more likely to confuse people than to be helpful: a developer has to choose between `sycl::bit_cast` (which copies the variable) and creating a `simd_view` with a different type (which doesn't copy the variable).  Having two functions (i.e. one to change the type, one to change the shape) seems the cleanest option to me, but then that wouldn't be compatible with the concept of `simd_view` referencing the same underlying data.

@rolandschulz, what do you think about this?  Is it okay for `sycl::bit_cast` and `simd_view` to coexist with different semantics?

**Comment by DenisBakhvalov** [comment]
We had a discussion with @rolandschulz and @kbobrovs, which converged on a name `bit_cast_view` as a member function. I.e. :
```cpp
  simd<int, 8> r = 0x0FF00F0F;
  auto v = r.bit_cast_view<short>();
```
The argument against having a free function is that it doesn't act like a factory function, producing objects of different types.

We also agreed that having `sycl::bit_cast` would be needed. There is a chance that it might work already. If not, I will make that in a separate patch.

**Review by kbobrovs — APPROVED** [review]

**Comment by bader** [comment]
@DenisBakhvalov, please, address pre-commit fails.

**Review by kbobrovs — APPROVED** [review]

**Comment by kbobrovs** [comment]
@Pennycook, please review approve as well. @rolandschulz, we've got informal approval from you when discussing it, but formal on here from you would be appreciated.

**Review by Pennycook — APPROVED** [review]

**Pull request merged**
