### PR TITLE
[SPIR-V] Apply changes related to SPIR-V 1.4

### PR DESCRIPTION
**Pull request by vmaksimo**
Signed-off-by: Dmitry Sidorov <dmitry.sidorov@intel.com>

Original commit:
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/c5b3c8e3283b

### CODE REVIEW

**Comment by vmaksimo** [comment]
This PR enables patches mentioned in https://github.com/intel/llvm/issues/3686

**Comment by bader** [comment]
@vmaksimo, should we close this? I see that Dmitry is already ready to commit the same change with https://github.com/intel/llvm/pull/7493.

**Comment by vmaksimo** [comment]
@bader Sure. Closing this one.

**Pull request closed without merging**
