### PR TITLE
[SYCL][JM tests] Remove xfail from JM prefetch test

### PR DESCRIPTION
**Pull request by dkhaldi**

### CODE REVIEW

**Review by YuriPlyakhin — APPROVED** [review]
LGTM

**Review by YuriPlyakhin — APPROVED** [review]
LGTM

**Comment by dkhaldi** [comment]
@intel/llvm-gatekeepers, please help merge.

**Comment by sommerlukas** [comment]
@dkhaldi 

There was one unexpectedly passing test on post-commit CI for this PR:
```
Unexpectedly Passed Tests (1):
  SYCL :: Matrix/SG32/joint_matrix_prefetch.cpp
```

Can you or someone from @intel/sycl-matrix-reviewers please take care of that?

https://github.com/intel/llvm/actions/runs/10175843701/job/28144675804

**Comment by dkhaldi** [comment]
> @dkhaldi
> 
> There was one unexpectedly passing test on post-commit CI for this PR:
> 
> ```
> Unexpectedly Passed Tests (1):
>   SYCL :: Matrix/SG32/joint_matrix_prefetch.cpp
> ```
> 
> Can you or someone from @intel/sycl-matrix-reviewers please take care of that?
> 
> https://github.com/intel/llvm/actions/runs/10175843701/job/28144675804

Thanks, this is being fixed in https://github.com/intel/llvm/pull/14866

**Comment by uditagarwal97** [comment]
@dkhaldi 
`Matrix/joint_matrix_prefetch.cpp` is failing on PVC without dev igc: https://github.com/intel/llvm/actions/runs/10182714951/job/28223556749?pr=14720#step:22:137
```
********************
FAIL: SYCL :: Matrix/joint_matrix_prefetch.cpp (1507 of 2131)
******************** TEST 'SYCL :: Matrix/joint_matrix_prefetch.cpp' FAILED ********************
Exit Code: -11

Command Output (stdout):
--
# RUN: at line 9
/__w/llvm/llvm/toolchain/bin//clang++ -Werror  -fsycl -fsycl-targets=spir64  /__w/llvm/llvm/llvm/sycl/test-e2e/Matrix/joint_matrix_prefetch.cpp -o /__w/llvm/llvm/build-e2e/Matrix/Output/joint_matrix_prefetch.cpp.tmp.out
# executed command: /__w/llvm/llvm/toolchain/bin//clang++ -Werror -fsycl -fsycl-targets=spir64 /__w/llvm/llvm/llvm/sycl/test-e2e/Matrix/joint_matrix_prefetch.cpp -o /__w/llvm/llvm/build-e2e/Matrix/Output/joint_matrix_prefetch.cpp.tmp.out
# note: command had no output on stdout or stderr
# RUN: at line 10
env ONEAPI_DEVICE_SELECTOR=level_zero:gpu  /__w/llvm/llvm/build-e2e/Matrix/Output/joint_matrix_prefetch.cpp.tmp.out
# executed command: env ONEAPI_DEVICE_SELECTOR=level_zero:gpu /__w/llvm/llvm/build-e2e/Matrix/Output/joint_matrix_prefetch.cpp.tmp.out
# note: command had no output on stdout or stderr
# error: command failed with exit status: -11
```

**Pull request merged**
