### PR TITLE
[SYCL][Bindless][Exp] Remove const from non-reference and non-pointer type parameters

### PR DESCRIPTION
**Pull request by isaacault**

### CODE REVIEW

**Review by cppchedy — APPROVED** [review]
LGTM. 

note that these updates are  ABI breaking.

**Comment by isaacault** [comment]
> LGTM.
> 
> note that these updates are ABI breaking.

@cppchedy  The symbols haven't changed, so I don't think it is.

**Comment by cppchedy** [comment]
> > LGTM.
> > note that these updates are ABI breaking.
> 
> @cppchedy The symbols haven't changed, so I don't think it is.

@isaacault my bad. I thought adding/removing `const` will produce different symbols.

**Review by DBDuncan — APPROVED** [review]

**Comment by isaacault** [comment]
@intel/llvm-gatekeepers this is ready for merge.

**Pull request merged**
