### PR TITLE
[GHA] Uplift Linux GPU RT version to 24.13.29138.7

### PR DESCRIPTION
**Pull request by bb-sycl**
Scheduled drivers uplift

### CODE REVIEW

**Comment by sarnex** [comment]
@aelovikov-intel @intel/dpcpp-devops-reviewers Ideally I'd like this PR merged soon because I need the new driver version for something I'm working on. There are 3 failing tests on Gen12 Linux:

```
Failed Tests (3):
SYCL :: Basic/kernel_info.cpp
SYCL :: GroupAlgorithm/root_group.cpp
SYCL :: KernelCompiler/opencl_queries.cpp
```

Can I just disable them and make an internal tracker and then we can merge? Or is there some other process? Thanks

**Comment by sarnex** [comment]
Fixing L0 issues: https://github.com/intel/llvm/pull/13547

**Comment by sarnex** [comment]
Windows L0 fix: https://github.com/intel/llvm/pull/13552

**Comment by sarnex** [comment]
@intel/dpcpp-devops-reviewers @aelovikov-intel All CI is passing now, can we merge this? Thanks!

**Review by aelovikov-intel — APPROVED** [review]

**Pull request merged**
