### PR TITLE
[SPIR] Syncing multiple versions of LIT test arithmetic-fence-builtin.c.

### PR DESCRIPTION
**Pull request by zahiraam**

### CODE REVIEW

**Review by smanna12 — APPROVED** [review]

**Comment by zahiraam** [comment]
@intel/dpcpp-cfe-reviewers I think this is ready to be merged. Can you please review? Thanks.

**Comment by Fznamznon** [comment]
> @intel/dpcpp-cfe-reviewers I think this is ready to be merged. Can you please review? Thanks.

This has already been reviewed. I suppose help from @intel/llvm-gatekeepers is wanted.

**Comment by dm-vodopyanov** [comment]
@zahiraam is this SYCL-related? If yes, please add [SYCL] tag at the beginning of the PR caption.

**Comment by bader** [comment]
> @zahiraam is this SYCL-related? If yes, please add [SYCL] tag at the beginning of the PR caption.

It seems to be not related to SYCL, but rather to SPIR and ARM targets. @zahiraam, I think we should push this PR to llorg. 
Please, add tests for SPIR target as well.

**Comment by bader** [comment]
> > > @zahiraam is this SYCL-related? If yes, please add [SYCL] tag at the beginning of the PR caption.
> > 
> > 
> > It seems to be not related to SYCL, but rather to SPIR and ARM targets. @zahiraam, I think we should push this PR to llorg. Please, add tests for SPIR target as well.
> 
> The LIT test has been added to llorg here: https://reviews.llvm.org/D144299

This test doesn't cover changes in this patch.

**Comment by zahiraam** [comment]
> > > > @zahiraam is this SYCL-related? If yes, please add [SYCL] tag at the beginning of the PR caption.
> > > 
> > > 
> > > It seems to be not related to SYCL, but rather to SPIR and ARM targets. @zahiraam, I think we should push this PR to llorg. Please, add tests for SPIR target as well.
> > 
> > 
> > The LIT test has been added to llorg here: https://reviews.llvm.org/D144299
> 
> This test doesn't cover changes in this patch.

Don't lines 6 and 27 do?

**Comment by bader** [comment]
> > > > > @zahiraam is this SYCL-related? If yes, please add [SYCL] tag at the beginning of the PR caption.
> > > > 
> > > > 
> > > > It seems to be not related to SYCL, but rather to SPIR and ARM targets. @zahiraam, I think we should push this PR to llorg. Please, add tests for SPIR target as well.
> > > 
> > > 
> > > The LIT test has been added to llorg here: https://reviews.llvm.org/D144299
> > 
> > 
> > This test doesn't cover changes in this patch.
> 
> Don't lines 6 and 27 do?

No, they don't test SPIR triples.

**Comment by zahiraam** [comment]
This PR was created in order to sync the multiple versions of arithmetic-fence-builtin.c  But had a conversation with @Fznamznon and it looks like the changes that I uploaded in community (https://reviews.llvm.org/D144299) will be enough and will not lead into a potential conflict in the next pulldown. Therefore, I am closing this PR.

**Pull request closed without merging**
