### PR TITLE
Revert NativePrograms addition for linkedPrograms to insert

### PR DESCRIPTION
**Pull request by omarahmed1111**
This would fix the post-commit fails for [14873](https://github.com/intel/llvm/pull/14873)

### CODE REVIEW

**Review by uditagarwal97 — APPROVED** [review]

**Comment by sarnex** [comment]
Will merge once more CI passes, thanks for quick investigation

**Comment by sarnex** [comment]
Everything except HIP passed, merging.

**Comment by sarnex** [comment]
Looks like these tests passed now but we have a timeout

```

********************
Timed Out Tests (1):
  SYCL :: Basic/group_async_copy.cpp
```

@omarahmed1111 Any idea if it's related?

**Comment by omarahmed1111** [comment]
> Basic/group_async_copy.cpp

Just tried locally and it was passing normally, It doesn't feel that anything could touch that. I also looked on post-commit history and I guess different tests timeout from time to time. Later [commit](https://github.com/intel/llvm/actions/runs/10221526990/job/28284598990) passed normally, so I guess it should be okay.

**Pull request merged**
