### PR TITLE
[SYCL][Clang][HIP] Disable macro __CUDA_ARCH__ for AMD hip-platform

### LINKED ISSUE #7720: [SYCL] [HIP] `__CUDA_ARCH__` defined when compiling for HIP backend
**Describe the bug**
I noticed that `__CUDA_ARCH__` is defined when compiling ahead of time for the HIP backend. 
I don't know if this is wanted, but for example using [Eigen](https://gitlab.com/libeigen/eigen) I get an error because it tries to include CUDA libraries (the workaround here is to define `EIGEN_NO_CUDA`).

As an example, compiling a file that just includes the Eigen library gives this:
```bash
In file included from include_eigen.cpp:3:
In file included from eigen/Eigen/Core:160:
eigen/Eigen/src/Core/util/Meta.h:21:12: fatal error: 'math_constants.h' file not found
  #include <math_constants.h>
           ^~~~~~~~~~~~~~~~~~
```

**To Reproduce**
```bash
$ clang++ -fsycl -std=c++17 dummy.cpp -dM -E  -fsycl-targets=amdgcn-amd-amdhsa -Xsycl-target-backend --offload-arch=gfx900 --rocm-path=/opt/rocm-5.0.2 | grep CUDA_ARCH
#define __CUDA_ARCH__ 1
```
where `dummy.cpp` is just
```cpp
#include <CL/sycl.hpp>

int main(){
    return 0;
}
```

**Environment (please complete the following information):**

- OS: Linux
- Target device and vendor: AMD GPU Radeon PRO WX 9100
- clang version: 16.0.0 (https://github.com/intel/llvm 0f579bae55c48d810e1ed76db29229c854e61d5e) 
   release 2022-09 (but it tried also with the `sycl-nightly/20221208` and the behaviour is the same)

### PR DESCRIPTION
**Pull request by abagusetty**
Fixes #7720

### CODE REVIEW

**Comment by bader** [comment]
"Fixes: Issue #7720" -> "Fixes #7720".

This will link PR with to an issue. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Review by premanandrao — COMMENTED** [review]
Can you please add a test?

**Review by premanandrao — APPROVED** [review]

**Review by smanna12 — APPROVED** [review]

**Comment by bader** [comment]
@abagusetty, there was a bug in CI system, which caused a hang for tests on CUDA. To pull the fix for this problem, could you merge the head of the sycl branch to your `hip-cuda-arch` branch, please? Sorry for inconvenience.

**Comment by abagusetty** [comment]
> @abagusetty, there was a bug in CI system, which caused a hang for tests on CUDA. To pull the fix for this problem, could you merge the head of the sycl branch to your `hip-cuda-arch` branch, please? Sorry for inconvenience.

Sure, thanks for the pointer.

**Pull request merged**
