### PR TITLE
[SYCL] Remove querying for unsupported platforms

### PR DESCRIPTION
**Pull request by jchlanda**
As discussed in https://github.com/intel/llvm/pull/15368 this functionality should not be exposed to the users.

### CODE REVIEW

**Comment by jchlanda** [comment]
If a revert commit would be preferred, the change was split across two:
* https://github.com/intel/llvm/commit/4443eff6c5f613b5038ad8c4a3b3e5a6532b5c8c
* https://github.com/intel/llvm/commit/93ee5b92cdd7502787c444181a34db0b736083b3

**Comment by jchlanda** [comment]
cc: @gmlueck and @steffenlarsen

**Review by steffenlarsen — APPROVED** [review]
LGTM! For other reviewers, this is an ABI break, but not a release-to-release ABI break.

**Comment by jchlanda** [comment]
Friendly ping: @intel/unified-runtime-reviewers and @sergey-semenov

**Comment by jchlanda** [comment]
> If a revert commit would be preferred, the change was split across two:
> 
>     * [4443eff](https://github.com/intel/llvm/commit/4443eff6c5f613b5038ad8c4a3b3e5a6532b5c8c)
> 
>     * [93ee5b9](https://github.com/intel/llvm/commit/93ee5b92cdd7502787c444181a34db0b736083b3)

Please note, this is no longer true, the codebase has moved forward and the patches would not apply correctly anymore.

**Comment by jchlanda** [comment]
Ping: @intel/unified-runtime-reviewers and @sergey-semenov

**Review by sergey-semenov — APPROVED** [review]

**Comment by jchlanda** [comment]
@intel/llvm-gatekeepers this should be ready to roll.

Thank you.

**Pull request merged**
