### PR TITLE
Revert "[SPIR][InstCombine] Work around SPIR-V translator limitation …

### PR DESCRIPTION
**Pull request by KornevNikita**
…(#2143)"

This reverts commit 2fb2468474af921e8f79a38808096201b391ab99.

### CODE REVIEW

**Review by bader — CHANGES_REQUESTED** [review]
The #4026 pre-commit results show the test case requiring this patch:
http://ci.llvm.intel.com:8010/#/builders/2/builds/15098/steps/16/logs/FAIL__SYCL__lower-external-funcs_cpp

@AlexeySotkin, FYI.

**Comment by AlexeySotkin** [comment]
@KornevNikita http://ci.llvm.intel.com:8010/#/builders/2/builds/15098/steps/16/logs/FAIL__SYCL__lower-external-funcs_cpp this is example of non-standard type which we should handle(convert to standard type if possible) in the translator.

**Comment by bader** [comment]
I suggest we close this PR.

**Comment by KornevNikita** [comment]
Closing PR as it was only needed to check the relevance of the problem with bitcasting to non-standard SPIR-V types.

**Pull request closed without merging**
