### PR TITLE
[SYCL][CUDA][HIP] Fix device architecture extension query

### PR DESCRIPTION
**Pull request by konradkusiak97**
Small fix to strip down additional CPU information from AMD query, like: `gfx90a:sramecc+:xnack-` to just `gfx90a`

### CODE REVIEW

**Comment by jinz2014** [comment]
It is okay (permitted) to keep the extra information following gfx90a ?

**Comment by konradkusiak97** [comment]
This fixes one of the e2e tests ([DeviceArchitecture/device_architecture_on_host.cpp](https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/DeviceArchitecture/device_architecture_on_host.cpp)) which currently fails on devices such as MI250. That's because the `DeviceArch` property for AMD has this extra CPU info and we're trying to match it with hardcoded architectures within `NVIDIA_AMD_ARCHES` macro, in [device_info.hpp](https://github.com/intel/llvm/blob/7afc2d03fd0040177009967aca057cc80708747b/sycl/source/detail/device_info.hpp#L562C1-L598C49).

**Comment by jinz2014** [comment]
ok

**Review by ldrumm — CHANGES_REQUESTED** [review]
`strtok` is not thread-safe and modifies its first argument, so I don't think we can use it here:
1. we need everything in the headers to be thread-safe (re-entrant is preferable)
2. DeviceArch could point to constant memory in certain conditions, but strtok modifies its first argument so this will be UB (likely a segfault)

**Comment by konradkusiak97** [comment]
> `strtok` is not thread-safe and modifies its first argument, so I don't think we can use it here:
> 
>     1. we need everything in the headers to be thread-safe (re-entrant is preferable)
> 
>     2. DeviceArch could point to constant memory in certain conditions, but strtok modifies its first argument so this will be UB (likely a segfault)

Thanks for pointing that out! I switched to the reentrant version of strtok, the  `strtok_r` and made sure any constness is removed before modifying `DeviceArch`

**Comment by cperkinsintel** [comment]
Looks like an include might be needed on Windows.
`D:\github\_work\llvm\llvm\src\sycl\source\detail/device_info.hpp(679): error C3861: 'strtok_r': identifier not found`

**Comment by konradkusiak97** [comment]
I dropped the approach of using `strtok` altogether and switched to just using `std::string`.

Is this good to go?

**Review by ldrumm — APPROVED** [review]

**Review by cperkinsintel — APPROVED** [review]

**Pull request merged**
