### PR TITLE
[SYCL][COMPAT] Added atomic header

### PR DESCRIPTION
**Pull request by Alcpz**
SYCLcompat's primary goals and features are documented [here](https://intel.github.io/llvm-docs/syclcompat/README.html).

The PR includes the code that would implement the wrapper to expose atomic operations.
The exposed functionalities include atomic free functions for arithmetic, bitwise, compare-and-exchange, and min and max operations.

Additionally, this PR includes an atomic class to provide similar functionality in an OOP fashion.

### CODE REVIEW

**Review by joeatodd — APPROVED** [review]
As per internal review, this LGTM 👍

**Comment by Alcpz** [comment]
@bader Sorry for the ping, I wrongly committed a unintended change.

**Comment by Alcpz** [comment]
@intel/llvm-gatekeepers We think this is ready to merge. Thanks!

**Comment by Alcpz** [comment]
@intel/llvm-gatekeepers We think this is ready to merge. Thanks!

**Pull request merged**
