### PR TITLE
reproducer for macro's issue

### PR DESCRIPTION
**Pull request by yubingex007-a11y**

### CODE REVIEW

**Comment by yubingex007-a11y** [comment]
clang++ -fsycl -O2 sycl/test/matrix/matrix-bfloat16-test-use.cpp  -DSYCL_EXT_ONEAPI_MATRIX_VERSION=2

**Comment by dkhaldi** [comment]
@JackAKirk, This is the reproducer Bing shared and that is working for him. Is this similar to what you tried on your side?

**Comment by JackAKirk** [comment]
> @JackAKirk, This is the reproducer Bing shared and that is working for him. Is this similar to what you tried on your side?

That can work if you can do that for every definition of `joint_matrix` where AMX overlaps parameters with tensor cores.  e.g.: I see that (int8_t use::a layout::row_major or col_major) case will overlap for AMX and tensor cores according to https://github.com/intel/llvm/blob/f2983fc0d8fcd7bd6022a7006ad489c591838041/sycl/include/sycl/ext/oneapi/matrix/static-query-use.hpp#L66
Then we would need to add this partial specialization:

```
  template <layout Layout>                                                     
  struct joint_matrix<                                                         
      int8_t, use::a, 16, 16, Layout, sycl::sub_group,                           
      typename std::enable_if_t<Layout == layout::row_major ||                 
                                Layout == layout::col_major>> {  
    #if defined(__NVPTX__)
    marray<int8_t, 8> wi_marray;                                              
    inline __SYCL_ALWAYS_INLINE wi_data<int8_t, 8> get_wi_data() {            
      return wi_data(wi_marray);                                               
    };      
#else // revert to intel general impl
  __spv::__spirv_JointMatrixINTEL<
      int8_t, 8, 8, spv_matrix_layout_traits<Layout>::value,
      spv_scope_traits<Group>::value, spv_matrix_use_traits<use::a>::value> *spvm;
inline __SYCL_ALWAYS_INLINE wi_data<int8_t, 8, 8, use::a, Layout, Group>
  get_wi_data() {
    return wi_data<int8_t, 8, 8, use::a, Layout, Group>(*this);
  }
#endif
#endif                                                                         
  };
```
For all cases it is easy for you to check if there is an overlap by looking at the cuda implementation partial specializations in this file:  https://github.com/intel/llvm/blob/5f02a0cccd45ee579dc90cea9efba622f58cefe1/sycl/include/sycl/ext/oneapi/matrix/matrix-tensorcores.hpp#L62
If you could confirm the list of overlaps that would be useful.

 If we go down this route where all `joint_matrix` definitions for tensor cores are visible to AMX users and vice versa I think we will also have to throw errors if a user tries to construct an invalid joint_matrix in one of these backends. Since tensor cores only uses definitions of `joint_matrix` that are partial specializations, the default constructor will have to throw an error in the cuda backend:

```
template <typename T, use Use, size_t Rows, size_t Cols,
          layout Layout = layout::dynamic, typename Group = sycl::sub_group,
          typename Cond = void>
struct joint_matrix
// default intel impl:
{
#if defined(__NVPTX__)
joint_matrix(){
// throw error so default isn't constructible in cuda backend
}
#else // revert to intel general impl
  __spv::__spirv_JointMatrixINTEL<
      T, NumRows, NumCols, spv_matrix_layout_traits<Layout>::value,
      spv_scope_traits<Group>::value, spv_matrix_use_traits<Use>::value> *spvm;
#endif
#endif
};
```

I think this would work fine (It works fine for the cuda backend, I don't see why it would not work for the intel backend too). It means that we would have to remove the macro usage that we have currently in https://github.com/intel/llvm/blob/5f02a0cccd45ee579dc90cea9efba622f58cefe1/sycl/include/sycl/ext/oneapi/matrix/matrix-tensorcores.hpp#L62 (can't have preprocessor statements inside macros) and explicitly write out each partial specialization, but this is not a big deal.

Alternative would be if there is a simple way of including a backend dependant header with joint_matrix defs, but if this is not straightforward then we can move forward with the preprocessor checks inside partial specializations route (so long as there are no issues on Intel side with this).

So to move forward with this can you confirm you want to go down this route, and then give me a list of the cases where `joint_matrix` definitions overlap for AMX and Tensor Cores. Then I can adjust the partial specializations accordingly in https://github.com/intel/llvm/pull/7077
Then it should be straightforward for you to add the intel impl on top.

**Comment by yubingex007-a11y** [comment]
@JackAKirk i saw the issue is how we write joint_matrix's partial specialization for each valid combination of type&size&layout. could NVIDIA verify the combination of type&size&layout in its backend instead of in header file? if so, we don't have to worry about the partial specialization's issue.

**Comment by JackAKirk** [comment]
> @JackAKirk i saw the issue is how we write joint_matrix's partial specialization for each valid combination of type&size&layout for intel and nv's backend. could CUDA verify the combination of type&size&layout in its backend instead of in header file? if so, we don't have to worry about the partial specialization's issue since we don't need to write partial specialization.

I think all things considered you are right and I should try to make this change now. I'll try to do it asap. Thanks for the input.

**Pull request closed without merging**
