### PR TITLE
[DeviceSanitizer] Change "TargetTriple.isSPIR()" to "TargetTriple.isSPIROrSPIRV()" in AddressSanitizer.cpp

### PR DESCRIPTION
**Pull request by AllanZyne**
SYCL is going to switch to SPIR-V backend soon, this PR changed "TargetTriple.isSPIR()" to "TargetTriple.isSPIROrSPIRV()" to improve compatibility

### CODE REVIEW

**Review by sarnex — APPROVED** [review]
TY!

**Review by zhaomaosu — APPROVED** [review]
lgtm

**Comment by asudarsa** [comment]
It seems like this change might have exposed a latent bug in the SPIR-V backend code. @michalpaszkowski, can you please comment how to address the windows failure reported in the CI?

Thanks

**Comment by asudarsa** [comment]
@AllanZyne 

Can you please add a line or two in the PR description about the need for this change? Just for logging purposes.

Thanks

**Comment by AllanZyne** [comment]
> @AllanZyne
> 
> Can you please add a line or two in the PR description about the need for this change? Just for logging purposes.
> 
> Thanks

Done.

**Comment by AllanZyne** [comment]
Hi @intel/llvm-gatekeepers, the failed test is not related to this test, this patch needs test using"-fsanitize=address" flag.
Thanks!

**Comment by michalpaszkowski** [comment]
> It seems like this change might have exposed a latent bug in the SPIR-V backend code. @michalpaszkowski, can you please comment how to address the windows failure reported in the CI?
> 
> Thanks

I wasn't able to reproduce the failure on a Windows build of SPIR-V backend both from this branch or the llvm-project repository. It might be the case that there is some memory leak/ownership issues inside LLVM (either in SPIR-V backend or otherplace), but this will require a bit more investigation. Unfortunately, rerunning this test many times does not help much.

@asudarsa @AllanZyne Would it be possible to rerun the Windows CI run?

**Comment by sommerlukas** [comment]
Can you try merging the latest changes from the `sycl` branch into your branch? There was some improvements made to Windows CI yesterday.

**Comment by AllanZyne** [comment]
> Can you try merging the latest changes from the `sycl` branch into your branch? There was some improvements made to Windows CI yesterday.

Sure

**Comment by AllanZyne** [comment]
Hi @intel/llvm-gatekeepers, please merge.
Thanks!

**Pull request merged**
