### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW15 2024)

### PR DESCRIPTION
**Pull request by iclsrc**
LLVM: llvm/llvm-project@89ba7e183e6e2c64370ed1b963e54c06352211db
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@a7051670770f47106dfd0f1a61e03c3b6235a3fe

### CODE REVIEW

**Comment by jsji** [comment]
This is ready for review.
- [ ] [Add REQUIRES spirv-as feature for GEPOperator.spvasm](https://github.com/intel/llvm/pull/13362/commits/91e7e2d53b7f2d8e9b9f7420cb534db21f51be9f) Cherry-pick of https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2501. No review needed.
- [ ] [[Clang] Look through type sugar when accessing FunctionProtoType](https://github.com/intel/llvm/pull/13362/commits/099d896b87611884d56264de0c440a961e53615b) Cherry-pick of https://github.com/llvm/llvm-project/pull/88428. No review needed.
- [ ] [Disable implicit-float-size-conversion for ustream HLSL tests](https://github.com/intel/llvm/pull/13362/commits/0f3c5a025573329962b9327453b7594bb5bc3ed0) @intel/dpcpp-cfe-reviewers

**Comment by JackAKirk** [comment]
This hasn't triggered any cuda e2e testing from what I can see. It would be good to do this to confirm there are no issues.
I don't see any major amdgpu/cuda changes so I wouldn't expect any issues.

**Comment by jsji** [comment]
> > This hasn't triggered any cuda e2e testing from what I can see. It would be good to do this to confirm there are no issues. I don't see any major amdgpu/cuda changes so I wouldn't expect any issues.
> 
> Thanks @JackAKirk . It is interesting that we did not even trigger CUDA tests with such huge changes.

Actually, we did trigger CUDA e2e test here: https://github.com/intel/llvm/actions/runs/8655894409/job/23735557333
But unfortunately update_check failed. https://github.com/intel/llvm/actions/runs/8655894409/job/23736551645
@intel/dpcpp-devops-reviewers  Looks like password or other credentials expired or something ?
"Error: Unhandled error: HttpError: Resource not accessible by integration" 


Only 1 failures, which also failed before this. So we are good. @JackAKirk .

```
Failed Tests (1):
  SYCL :: bindless_images/read_norm_types.cpp
```

**Review by JackAKirk — APPROVED** [review]
LGTM for hip/cuda

**Comment by jsji** [comment]
> 
> Actually, we did trigger CUDA e2e test here: https://github.com/intel/llvm/actions/runs/8655894409/job/23735557333 But unfortunately update_check failed. https://github.com/intel/llvm/actions/runs/8655894409/job/23736551645 @intel/dpcpp-devops-reviewers Looks like password or other credentials expired or something ? "Error: Unhandled error: HttpError: Resource not accessible by integration"


Hmm... Last CUDA e2e success was https://github.com/intel/llvm/actions/runs/8460746056 2 weeks ago!! So looks like a problem caused by  https://github.com/intel/llvm/pull/13173 again.. FYI.  @stdale-intel  @intel/dpcpp-devops-reviewers

**Comment by jsji** [comment]
> Last CUDA e2e success was https://github.com/intel/llvm/actions/runs/8460746056 2 weeks ago!! So looks like a problem caused by #13173 again.. FYI. @stdale-intel @intel/dpcpp-devops-reviewers

https://github.com/intel/llvm/pull/13377 Posted to fix it.

**Comment by jsji** [comment]
> * [ ]  [Disable implicit-float-size-conversion for ustream HLSL tests](https://github.com/intel/llvm/pull/13362/commits/0f3c5a025573329962b9327453b7594bb5bc3ed0) @intel/dpcpp-cfe-reviewers

@intel/dpcpp-cfe-reviewers Can someone have a quick look at this testcase update and add comments/approval explicitly so that this can be merged. Thanks.

**Comment by elizabethandrews** [comment]
> > * [ ]   [Disable implicit-float-size-conversion for ustream HLSL tests](https://github.com/intel/llvm/pull/13362/commits/0f3c5a025573329962b9327453b7594bb5bc3ed0) @intel/dpcpp-cfe-reviewers
> 
> @intel/dpcpp-cfe-reviewers Can someone have a quick look at this testcase update and add comments/approval explicitly so that this can be merged. Thanks.

It is not clear to me if the solution here is to add the warning flag or modify the tests itself. Where was the warning being fired?@zahiraam can you take a look?

**Comment by zahiraam** [comment]
> > > * [ ]    [Disable implicit-float-size-conversion for ustream HLSL tests](https://github.com/intel/llvm/pull/13362/commits/0f3c5a025573329962b9327453b7594bb5bc3ed0) @intel/dpcpp-cfe-reviewers
> > 
> > 
> > @intel/dpcpp-cfe-reviewers Can someone have a quick look at this testcase update and add comments/approval explicitly so that this can be merged. Thanks.
> 
> It is not clear to me if the solution here is to add the warning flag or modify the tests itself. Where was the warning being fired?@zahiraam can you take a look?

From my reading of https://github.com/intel/llvm/pull/6323 and the original code of the tests, the warnings should stay.

**Comment by jsji** [comment]
> From my reading of #6323 and the original code of the tests, the warnings should stay.

Thanks @zahiraam .
Yes, we still have those warnings if we don't disable them. 
But these are community tests, disabling these warnings using options in RUN lines will help reducing the conflicts and maintenance effort. We keep the testing point of community tests synced with community, without having to check the warnings.

For #6323, we have other tests, especially sycl related code that will test it, so I don't think we need to update the community tests in HLSL to check the warning message as well.

**Review by zahiraam — APPROVED** [review]

**Comment by jsji** [comment]
@bader @intel/llvm-gatekeepers This is ready for merge. Thanks.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Mon 15 Apr 2024 03:53:49 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Mon 15 Apr 2024 03:58:08 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
