### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW24)

### PR DESCRIPTION
**Pull request by pvchupin**
LLVM: https://github.com/llvm/llvm-project/commit/dd6bcdbf21716c56d3defd7f4cacddc7befd5de1
SPIRV-LLVM-Translator: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/24c5671

### CODE REVIEW

**Comment by pvchupin** [comment]
Testing is clean.

"SYCL :: USM/allocator_rebind.cpp" issue is false-positive due to simultaneous changes in compiler (https://github.com/intel/llvm/pull/6191) and llvm-test-suite (https://github.com/intel/llvm-test-suite/pull/1038) done while this testing was in progress, this testing picked up llvm-test-suite change but not the compiler change.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Sat 04 Jun 2022 08:44:43 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Sat 04 Jun 2022 08:48:25 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
