### PR TITLE
[SYCL] Add --host-target flag and remove --arm flag

### PR DESCRIPTION
**Pull request by npmiller**
This patch adds a new flag to `configure.py` to allow changing the host
target to build, this makes it easier to build on different hosts such
as ARM or PowerPC.

This patch also removes the `--arm` flag as it is now redundant,
`--host-target=ARM` or `--host-target=AArch64` should be used instead.

This is slightly different than the original `--arm` flag as it only
allows to enable one of the ARM platforms. But I'm not sure what the use
case was for enabling both, as only one will be the host platform for a
given build. And compilation time was given as a reason to drop the X86
architecture originally so only enabling the correct ARM architecture
should also help with that.

### CODE REVIEW

**Comment by bader** [comment]
> This patch also removes the `--arm` flag as it is now redundant,
> `--host-target=ARM` or `--host-target=AArch64` should be used instead.

> This is slightly different than the original `--arm` flag as it only
> allows to enable one of the ARM platforms. But I'm not sure what the use
> case was for enabling both, as only one will be the host platform for a
> given build. And compilation time was given as a reason to drop the X86
> architecture originally so only enabling the correct ARM architecture
> should also help with that.

The option value is passed as is to "-DLLVM_TARGETS_TO_BUILD=", so technically users can pass multiple targets. Not sure if we need to change the option name, but I think it's worth adding to the description. LLVM's definition for the reference:

> LLVM_TARGETS_TO_BUILD:STRING
> Semicolon-separated list of targets to build, or all for building all targets. Case-sensitive. Defaults to all. Example: -DLLVM_TARGETS_TO_BUILD="X86;PowerPC".

`--host-target=ARM;AArch64` is equivalent to `--arm`.

IIRC, developers who were trying to build DPC++ for ARM host were trying to build DPC++ using GitHub CI on GitHub ARM runners, which are not capable of building X86 target in addition to ARM. The build job exceeds time limit set by GitHub. I suppose if we use self-hosted runners, we can build multiple targets with no problems.

**Comment by npmiller** [comment]
I added a note to the help of the option stating that multiple targets can be provided. And I kept the name of the option as-is, as I couldn't think of a better name for it that wouldn't also make it less clear what the main purpose of the flag is. And I also think adding extra LLVM targets that are not host or offload targets is likely not a very common use case.

**Review by bader — DISMISSED** [review]

**Review by bader — APPROVED** [review]

**Comment by bader** [comment]
@intel/dpcpp-esimd-reviewers, FYI. 

Failed Tests (5):
  SYCL :: dword_atomic_smoke.cpp
  SYCL :: lsc/lsc_fence.cpp
  SYCL :: lsc/lsc_slm.cpp
  SYCL :: lsc/lsc_surf.cpp
  SYCL :: lsc/lsc_usm.cpp

I don't these failures are related to the patch. Could you take a look, please?

**Comment by jeffhammond** [comment]
This does not work: https://github.com/intel/llvm/issues/11061

**Pull request merged**
