### PR TITLE
[Driver][SYCL] Update header inclusion for source + footer

### PR DESCRIPTION
**Pull request by mdtoguchi**
Instead of using -internal-isystem for the source location header inclusion,
use -I as a user header, but be sure it is placed after user defined -I
locations.

### CODE REVIEW

**Review by AGindinson — COMMENTED** [review]
No objections to the change, just curious as to the issues that the previous solution had run into.

**Comment by mdtoguchi** [comment]
> No objections to the change, just curious as to the issues that the previous solution had run into.

Ran into a compilation failure in SYCL_CI with a test where headers weren't being resolved as expected.

**Review by AGindinson — APPROVED** [review]

**Comment by bader** [comment]
> @bader, I believe this PR is safe to merge, since the post-commit failures were [Linux-specific](http://icl-jenkins.sc.intel.com:8080/job/SYCL_CI/job/intel/job/Post_Commit_Summary/1691/display/redirect), and the current Summary shows no such regressions. Thanks.

@AGindinson, why do you think this patch can't regress tests on Windows? Was this version of the patch tested on Windows already?

**Comment by AGindinson** [comment]
> @AGindinson, why do you think this patch can't regress tests on Windows? Was this version of the patch tested on Windows already?

Fair point.

**Pull request merged**
