### PR TITLE
[SYCL] Use boost's unordered maps for kernel caching

### PR DESCRIPTION
**Pull request by sergey-semenov**
Fetching the kernel from the map is a hotspot for applications that repeatedly launch microkernels. As the number of kernels used by the application grows, std::map shows poor performance there.

This patch replaces uses of std::map with boost::unordered_flat_map and boost::unordered_map. The former is used for the fast path to prioritize lookup performance, the latter is used for the slow path since it's expected to be used only once for each newly created kernel, so the higher insertion overhead of the flat map is more of an issue there.

### CODE REVIEW

**Comment by bader** [comment]
> This patch replaces uses of std::map with boost::unordered_flat_map and boost::unordered_map. The former is used for the fast path to prioritize lookup performance, the latter is used for the slow path since it's expected to be used only once for each newly created kernel, so the higher insertion overhead of the flat map is more of an issue there.

What is expected speed-up from using boost library vs std?

**Comment by sergey-semenov** [comment]
> What is expected speed-up from using boost library vs std?

boost::unordered_map and std::unordered_map seem to be more or less on par here (with std::unoredered_map using boost::hash, 
there's no default hash function for tuples in STL). The main draw is boost::unordered_flat_map. I've tested the containers on up to 1024 kernels, and it showed noticable reduction of lookup time of 7.6% on 8 elements, which then grew to 22% by 1024 elements.

kernelcachecontainers

**Comment by sergey-semenov** [comment]
@steffenlarsen Could you please review this change?

**Review by steffenlarsen — APPROVED** [review]
LGTM!

**Pull request merged**
