### PR TITLE
[CI] Fix detection of `level_zero_dev_kit` LIT feature on Win CI with L0

### PR DESCRIPTION
**Pull request by uditagarwal97**
Example run: https://github.com/intel/llvm/actions/runs/9986151153/job/27599398329#step:12:2215

### CODE REVIEW

**Review by aelovikov-intel — APPROVED** [review]

**Comment by uditagarwal97** [comment]
**CI failures:**
E2E tests on Arc, Linux:
```
Failed Tests (2):
  SYCL :: ESIMD/PerformanceTests/invoke_simd_smoke.cpp
  SYCL :: Regression/local-arg-align.cpp
```

`Regression/local-arg-align.cpp` test failure is related to opaque pointers support https://github.com/intel/llvm/issues/10682
Opened a new bug report for `ESIMD/PerformanceTests/invoke_simd_smoke.cpp`: https://github.com/intel/llvm/issues/14647

E2E test on Windows Gen12
```
Failed Tests (1):
  SYCL :: ESIMD/api/functional/ctors/ctor_load_usm_fp_extra.cpp
```

This test failure is related to https://github.com/intel/llvm/issues/14542

Linux LIT tests
```
Failed Tests (1):
  SYCL :: invoke_simd/invoke_simd_address_space_inferral.cpp
```

**Comment by uditagarwal97** [comment]
All the above test failures are unrelated to the changes made in this PR.
@intel/llvm-gatekeepers the PR is ready to be merged.

**Comment by steffenlarsen** [comment]
I believe ESIMD/api/functional/ctors/ctor_load_usm_fp_extra.cpp is unrelated to https://github.com/intel/llvm/issues/14542, but it has been seen in https://github.com/intel/llvm/pull/14631 and https://github.com/intel/llvm/pull/14618.

As for the other failures, I am a little weary given so many tests fail that are failing for the first time. It would be good to have @sarnex's thoughts on this, seeing as most are ESIMD.

**Comment by sarnex** [comment]
Other two issues should be fixed in HEAD, it was introduced by a different commit. I'm comfortable merging this.

**Pull request merged**
