### PR TITLE
[SYCL] Remove manual diagnostic checking for stmt attrs.

### PR DESCRIPTION
**Pull request by AaronBallman**
Statement attributes now have automatic diagnostic checking, so let's
use that. This does have a change in behavior in that passing the wrong
number of arguments is now an error instead of a warning, but that
behavior is more consistent with other attributes.

### CODE REVIEW

**Review by smanna12 — APPROVED** [review]
LGTM

**Review by premanandrao — COMMENTED** [review]
Changes look good to me.   Looks like there is a conflict in attr.td though.

**Review by smanna12 — DISMISSED** [review]

**Review by premanandrao — DISMISSED** [review]
LGTM

**Comment by AaronBallman** [comment]
FYI, I found one more cleanup that I'm in the process of testing out locally. I thought it was an upstream attribute but it turns out it's one of ours. Sorry for the noise on the review!

**Comment by AaronBallman** [comment]
Assuming CI is happy, that should be the last of the changes on this patch. I love seeing all that red with so little green. :-)

**Review by premanandrao — APPROVED** [review]
LGTM

**Comment by smanna12** [comment]
@AaronBallman, we are still using /*opt*/1 for IVDEP attr. Do we still need this?

**Comment by AaronBallman** [comment]
> @AaronBallman, we are still using /_opt_/1 for IVDEP attr. Do we still need this?

I think that's something we should investigate. It looks like we handle the case where no arguments are given (https://github.com/intel/llvm/blob/sycl/clang/lib/Sema/SemaStmtAttr.cpp#L272), but one thing that confuses me is the attribute takes three optional arguments when the semantic handler for it only ever seems to care about two of them. :-/

**Comment by AaronBallman** [comment]
Btw, as best I can tell, the test failure in check-sycl is unrelated to my changes.

**Comment by smanna12** [comment]
> > @AaronBallman, we are still using /_opt_/1 for IVDEP attr. Do we still need this?
> 
> I think that's something we should investigate. It looks like we handle the case where no arguments are given (https://github.com/intel/llvm/blob/sycl/clang/lib/Sema/SemaStmtAttr.cpp#L272), but one thing that confuses me is the attribute takes three optional arguments when the semantic handler for it only ever seems to care about two of them. :-/

Thanks for the explanation. May be we can create a new issue so that we do not forget about this.

**Review by smanna12 — APPROVED** [review]

**Comment by bader** [comment]
> Btw, as best I can tell, the test failure in check-sycl is unrelated to my changes.

The problem has been addressed, so I restarted validation to confirm.

**Comment by bader** [comment]
Resolved merge conflict with #3388 - no functional changes.

**Review by smanna12 — APPROVED** [review]

**Review by premanandrao — APPROVED** [review]
LGTM

**Pull request merged**
