### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW02-03)

### PR DESCRIPTION
**Pull request by vmaksimo**
LLVM: llvm/llvm-project@d6d3000a2f6d
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@f6f7114f295f8561bc72bb12b31562f5f8fa5971

### CODE REVIEW

**Comment by vmaksimo** [comment]
llvm-spirv failures are expected to be fixed by #5221

**Comment by Naghasan** [comment]
> Hi, @Naghasan! Some time ago you've created a test that checks there is no declaration of the function.
> 
> 
> Do you have any idea if the `declare hidden` has the same meaning as not generating a declaration at all? Or is it expected to get some "empty" IR, and we've caught a regression? Could you please help to understand what the test should check? Thank you!

Hello,

The test is checking that you don't have a `declare` which basically means there is a mangling mismatch between the function called and the one in libclc.

Did your test run included this https://github.com/intel/llvm/commit/29047bc97fae34bdbc0a4fb936f4429f78c6c8f1 ?

**Comment by vmaksimo** [comment]
> The test is checking that you don't have a `declare` which basically means there is a mangling mismatch between the function called and the one in libclc.
> 
> Did your test run included this [29047bc](https://github.com/intel/llvm/commit/29047bc97fae34bdbc0a4fb936f4429f78c6c8f1) ?

Oh, I haven't seen this change - I believe it's missing in this PR. Thanks for letting me know, aligning with the recent sycl branch should help!

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Fri 14 Jan 2022 08:28:18 AM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Pull request merged**
