### PR TITLE
[NFC][SYCL] Proper use of fork() in assertion test

### PR DESCRIPTION
**Pull request by s-kanaev**
According to `man 2 fork` there is only a limited set of functions safe to call by child process. These functions are called `async-signal-safe functions`. In the test child process allocates SYCL/OpenCL objects which and calls to functions which are not async-signal-safe (when allocating SYCL RT wil call `malloc` via `operator new`, OpenCL functions, etc). This patch provides a proper use of `fork()` function in the test.

### CODE REVIEW

**Comment by asavonic** [comment]
> According to man 2 fork there is only a limited set of functions safe to call by child process. These functions are called async-signal-safe functions. 

That is not entirely accurate:
> After a fork() in a **multithreaded program**, the  child  can  safely  call  only  async-signal-safe  functions

If my reading is correct, this requirement is only applicable if a program is multi-threaded before fork(). Since main() does not create any threads, this use of fork should be safe.

**Comment by romanovvlad** [comment]
@s-kanaev ping

**Comment by bader** [comment]
@s-kanaev ping

**Comment by s-kanaev** [comment]
> If my reading is correct, this requirement is only applicable if a program is multi-threaded before fork(). Since main() does not create any threads, this use of fork should be safe.

Yes the reading is correct. Yet main can create some threads without user knowing about it. The threads can be created somewhere in SYCL RT lib. This can lead to undefined/malicious/deadlock behaviour of the binary. Here is an example:

1. Main thread creates `cl::sycl::queue` object, name it `Q`.
2. `Q` creates a thread `Thr1`
3. Main thread `fork()`s
4. `Q`'s destructor awaits on `Thr1.join()`.

Step No 4 is OK in main thread as there is a thread to wait for whilst this step won't work OK as there is no thread to wait for in current process.

**Comment by asavonic** [comment]
> Here is an example:
> Main thread creates cl::sycl::queue object, name it Q.

The main function does not create `cl::sycl::queue` before `fork`.
`fork` is literally the first call in the main function.

**Comment by s-kanaev** [comment]
> The main function does not create cl::sycl::queue before fork.
fork is literally the first call in the main function.

The threads can be created somewhere in SYCL RT lib. Especially in some singleton objects.

**Comment by asavonic** [comment]
> > The main function does not create cl::sycl::queue before fork.
> > fork is literally the first call in the main function.
> 
> The threads can be created somewhere in SYCL RT lib. Especially in some singleton objects.

Is this behavior documented anywhere?

**Comment by s-kanaev** [comment]
> Is this behavior documented anywhere?

For SYCL RT the answer is "no, it isn't". Though the behaviour of SYCL RT can change, can't it?

**Comment by asavonic** [comment]
> > Is this behavior documented anywhere?
> 
> For SYCL RT the answer is "no, it isn't". Though the behaviour of SYCL RT can change, can't it?

If you plan to change SYCL runtime to spawn threads from the library init, I suggest to review that first.

**Comment by romanovvlad** [comment]
@s-kanaev ping

**Comment by s-kanaev** [comment]
> If you plan to change SYCL runtime to spawn threads from the library init, I suggest to review that first.

See #1471

**Comment by asavonic** [comment]
> > If you plan to change SYCL runtime to spawn threads from the library init, I suggest to review that first.
> 
> See #1471

The patch doesn't seem to create any threads during the library init.
I see the thread pool created in `queue_impl::getHostTaskAndEventCallbackThreadPool`, but to call this function you need at least a `sycl::queue`.

**Pull request closed without merging**
