### PR TITLE
Revert "[SYCL] XFAIL LIT test due to duplicate diagnostic"

### PR DESCRIPTION
**Pull request by premanandrao**
This reverts commit a28778c2a686f503fad805ca4de963e5a39fdeb6
and fixes the test.

Signed-off-by: Premanand M Rao <premanand.m.rao@intel.com>

### CODE REVIEW

**Comment by premanandrao** [comment]
> Do you know what is the reason for duplicated diagnostics?

Basically what they are trying to solve with: https://reviews.llvm.org/D77028

> Why it didn't reproduce before new deferred diagnostics?

We had a densemap of each caller-callee which had its diagnostic deferred.  That prevented the second visit (at least in this case).   We had other issues with duplicate messages that you had worked on.

**Comment by bader** [comment]
> > Do you know what is the reason for duplicated diagnostics?
> 
> Basically what they are trying to solve with: https://reviews.llvm.org/D77028

@premanandrao, the test is already marked as expected to fail, so could we wait until the fix lands into the llvm-project and pull it into sycl branch, rather than update the test with wrong checks?

**Comment by premanandrao** [comment]
> @premanandrao, the test is already marked as expected to fail, so could we wait until the fix lands into the llvm-project and pull it into sycl branch, rather than update the test with wrong checks?

We could if that is what you prefer.   You had asked @vladimirlaz to revert marking the test as "XFAIL", which is what I trying to help with.

**Comment by bader** [comment]
Sorry for confusion. I draw Vladimir's attention that his approach to fix the test is a temporal workaround, which we should revert asap and replace with proper solution.
Now we know that this issue is caused by the community change and they work on a fix, so I think we can wait for community fix rather than fixing ourselves.

**Comment by vladimirlaz** [comment]
it looks like https://reviews.llvm.org/D77028 was submitted but it doe not resolve the case.
Approving to make tests run.

**Pull request merged**
