### PR TITLE
[SYCL] [NATIVECPU] Avoid passing -emit-only-kernels-as-entry-point on native cpu

### PR DESCRIPTION
**Pull request by PietroGhg**
Similarly to NVPTX and AMD, Native CPU needs to not set ` -emit-only-kernels-as-entry-point` since kernels for this target are not identified by the calling convention.

### CODE REVIEW

**Review by mdtoguchi — COMMENTED** [review]
Change is OK - can you add a test to verify?

**Comment by PietroGhg** [comment]
> Change is OK - can you add a test to verify?

Yeah good point, I've updated our driver lit test, thank you

**Review by mdtoguchi — APPROVED** [review]

**Review by uwedolinsky — APPROVED** [review]
Looks good to me.

**Comment by PietroGhg** [comment]
Hi @intel/llvm-gatekeepers, this looks ready to be merged, thank you

**Pull request merged**
