### PR TITLE
[GHA] Uplift Linux GPU RT version to 23.39.27427.23

### PR DESCRIPTION
**Pull request by bb-sycl**
Scheduled drivers uplift

### CODE REVIEW

**Comment by v-klochkov** [comment]
ESIMD will give this test/fail high priority: SYCL :: ESIMD/local_accessor_block_load_store.cpp

**Comment by YuriPlyakhin** [comment]
Patch to remove Joint Matrix test failures: https://github.com/intel/llvm/pull/12411

**Comment by v-klochkov** [comment]
ESIMD patch to fix `ESIMD/local_accessor_block_load_store.cpp` fail: https://github.com/intel/llvm/pull/12409

**Comment by bader** [comment]
@aelovikov-intel, thanks for pushing this forward! 👍

**Review by YuriPlyakhin — APPROVED** [review]

**Comment by bader** [comment]
@aelovikov-intel, do you know what might cause this failure: https://github.com/intel/llvm/actions/runs/7562810084/job/20594269037?

**Comment by aelovikov-intel** [comment]
> @aelovikov-intel, do you know what might cause this failure: https://github.com/intel/llvm/actions/runs/7562810084/job/20594269037?

No... Looks like something is wrong with the packages we downloaded:

```
#11 8.095 dpkg: dependency problems prevent configuration of intel-level-zero-gpu:
#11 8.095  intel-level-zero-gpu depends on intel-igc-core (= 1.0.15136.22); however:
#11 8.095   Version of intel-igc-core on system is 1.0.15468.11.
#11 8.095 
#11 8.095 dpkg: error processing package intel-level-zero-gpu (--install):
#11 8.095  dependency problems - leaving unconfigured
#11 8.095 dpkg: dependency problems prevent configuration of intel-opencl-icd:
#11 8.095  intel-opencl-icd depends on intel-igc-opencl (= 1.0.15136.22); however:
#11 8.095   Version of intel-igc-opencl on system is 1.0.15468.11.
#11 8.095 
#11 8.095 dpkg: error processing package intel-opencl-icd (--install):
#11 8.095  dependency problems - leaving unconfigured
#11 8.095 Setting up level-zero (1.15.8) ...
#11 8.116 Setting up libigdgmm12:amd64 (22.3.11+ci17757293) ...
#11 8.120 Setting up intel-igc-opencl-devel (1.0.15468.11) ...
#11 8.123 Setting up level-zero-devel (1.15.8) ...
#11 8.127 Setting up libigdgmm-dev:amd64 (22.3.11+ci17757293) ...
#11 8.131 Processing triggers for libc-bin (2.35-0ubuntu3.5) ...
#11 8.430 Errors were encountered while processing:
#11 8.430  intel-level-zero-gpu
#11 8.430  intel-opencl-icd
```

**Comment by bader** [comment]
> > @aelovikov-intel, do you know what might cause this failure: https://github.com/intel/llvm/actions/runs/7562810084/job/20594269037?
> 
> No... Looks like something is wrong with the packages we downloaded:
> 
> ```
> #11 8.095 dpkg: dependency problems prevent configuration of intel-level-zero-gpu:
> #11 8.095  intel-level-zero-gpu depends on intel-igc-core (= 1.0.15136.22); however:
> #11 8.095   Version of intel-igc-core on system is 1.0.15468.11.
> #11 8.095 
> #11 8.095 dpkg: error processing package intel-level-zero-gpu (--install):
> #11 8.095  dependency problems - leaving unconfigured
> #11 8.095 dpkg: dependency problems prevent configuration of intel-opencl-icd:
> #11 8.095  intel-opencl-icd depends on intel-igc-opencl (= 1.0.15136.22); however:
> #11 8.095   Version of intel-igc-opencl on system is 1.0.15468.11.
> #11 8.095 
> #11 8.095 dpkg: error processing package intel-opencl-icd (--install):
> #11 8.095  dependency problems - leaving unconfigured
> #11 8.095 Setting up level-zero (1.15.8) ...
> #11 8.116 Setting up libigdgmm12:amd64 (22.3.11+ci17757293) ...
> #11 8.120 Setting up intel-igc-opencl-devel (1.0.15468.11) ...
> #11 8.123 Setting up level-zero-devel (1.15.8) ...
> #11 8.127 Setting up libigdgmm-dev:amd64 (22.3.11+ci17757293) ...
> #11 8.131 Processing triggers for libc-bin (2.35-0ubuntu3.5) ...
> #11 8.430 Errors were encountered while processing:
> #11 8.430  intel-level-zero-gpu
> #11 8.430  intel-opencl-icd
> ```

It looks like IGC rolled out a new version 10 hours ago, but level zero runtime package depends on older version. I think for "unstable" configuration it should be okay to install "latest" version of packages and ignore dependency inconsistencies. What do you think?

**Comment by aelovikov-intel** [comment]
I don't think we ever use that particular image. The closest thing in actual use (AFAIK) would be experimental drivers for matrix tests. But I don't remember how that is implemented, @YuriPlyakhin knows better.

**Comment by bader** [comment]
> I don't think we ever use that particular image. The closest thing in actual use (AFAIK) would be experimental drivers for matrix tests. But I don't remember how that is implemented, @YuriPlyakhin knows better.

It can be useful to reproduce bugs. Instead of saying install these 10 packages, we can just provide a container with all packages installed.

**Comment by bader** [comment]
Replaced by https://github.com/intel/llvm/pull/12463.

**Comment by YuriPlyakhin** [comment]
> I don't think we ever use that particular image. The closest thing in actual use (AFAIK) would be experimental drivers for matrix tests. But I don't remember how that is implemented, @YuriPlyakhin knows better.

I believe that was never completed...

**Comment by YuriPlyakhin** [comment]
> > I don't think we ever use that particular image. The closest thing in actual use (AFAIK) would be experimental drivers for matrix tests. But I don't remember how that is implemented, @YuriPlyakhin knows better.
> 
> It can be useful to reproduce bugs. Instead of saying install these 10 packages, we can just provide a container with all packages installed.

I would agree that for "unstable" configuration we should install "latest" version of packages and ignore dependency inconsistencies.

**Pull request closed without merging**
