### PR TITLE
[CI][HIP] Switch to using 6.1 rocm and make it use a fixed version.

### PR DESCRIPTION
**Pull request by JackAKirk**
Previously the version of ROCM used by docker was not fixed and could change when rocm latest version is updated by AMD, which could lead to CI problems.

This fixes that and sets the version to 6.1.
Only the rocmdev package is installed which is the minimal required package for the compiler. This reduces the memory overhead.

### CODE REVIEW

**Review by aelovikov-intel — APPROVED** [review]

**Comment by JackAKirk** [comment]
@aelovikov-intel The CI is complaining about intel driver install failures even with the latest commit I made where I used the version of the docker build from the sycl branch unchanged.

Does some part of the intel driver install need to be updated somehow?

**Comment by aelovikov-intel** [comment]
Looks like something @jsji added recently is failing.

**Comment by jsji** [comment]
> Looks like something @jsji added recently is failing.

Yes, that is because we did not update the dependencies.json drivers in time, so the igc-dev ci drivers got removed. So we are not able to install it when rebuilding the docker image.

**Comment by JackAKirk** [comment]
> > Looks like something @jsji added recently is failing.
> 
> Yes, that is because we did not update the dependencies.json drivers in time, so the igc-dev ci drivers got removed. So we are not able to install it when rebuilding the docker image.

Does that mean we cannot edit the docker file at all? If so do you know when we will be able to?
Thanks

**Comment by jsji** [comment]
> Does that mean we cannot edit the docker file at all? If so do you know when we will be able to? Thanks

You can. We should be return to good state once https://github.com/intel/llvm/pull/13393 is merged. Or you can update the devops/dependencies.json to the same as  https://github.com/intel/llvm/pull/13393 in this PR first to unblock your testing.

**Comment by aelovikov-intel** [comment]
Looks like the update image broke pre-commit CI, I've switched to using latest good image at https://github.com/intel/llvm/pull/13606. @JackAKirk @ldrumm , please follow up on the issue.

**Pull request merged**
