### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW14-15)

### PR DESCRIPTION
**Pull request by vmaksimo**
LLVM: llvm/llvm-project@9711118
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@56988bb

### CODE REVIEW

**Comment by bader** [comment]
@vmaksimo, there are no LLVM changes in this pull request - only SPIRV-LLVM-Translator. Is it expected?

**Comment by vmaksimo** [comment]
> @vmaksimo, there are no LLVM changes in this pull request - only SPIRV-LLVM-Translator. Is it expected?

It was expected as there were no new changes in sycl-web till today's morning. I'll test and merge new changes later.

**Comment by bader** [comment]
> > @vmaksimo, there are no LLVM changes in this pull request - only SPIRV-LLVM-Translator. Is it expected?
> 
> It was expected as there were no new changes in sycl-web till today's morning. I'll test and merge new changes later.

It means if you take `llvm-project/main` and merge to `sycl-web`, there will be no conflicts. I suggest doing so for pulldown.

**Pull request merged**
