### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW01)

### PR DESCRIPTION
**Pull request by KornevNikita**
LLVM: llvm/llvm-project@fe5cf48
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@74681f6

### CODE REVIEW

**Comment by KornevNikita** [comment]
There is still some work to do - 81 failed tests, but originally there were ~1000, so I believe we will fix the rest next days. Moving to ready for review so you can add preliminary comments.

**Comment by bader** [comment]
> There is still some work to do - 81 failed tests, but originally there were ~1000, so I believe we will fix the rest next days. Moving to ready for review so you can add preliminary comments.

I hope you are doing this with some script and not manually.

**Comment by KornevNikita** [comment]
There are only few failing tests left in SYCL and one in LLVM.
The last one in LLVM should be fixed soon by https://github.com/intel/llvm/pull/7969.
SYCL also should be fixed in the coming days.
Also, we already working on fixes for disabled tests and their re-enabling.

**Comment by bader** [comment]
> @bader do we need SYCL Nightly Builds / ubuntu2204_opaque_pointers_build_test / Build + LIT (pull_request) (and so on with _opaque_pointers) to pass? 

Opaque pointers build configuration fails check-sycl and check-llvm-spirv. Here are the results for the latest nightly build - https://github.com/intel/llvm/actions/runs/3898749252/jobs/6657783427. Could you check that there no new regressions, please?

> I'm asking because some tests that I disabled "unexpectedly" passing here. As I understand it, the only way to fix it - temporarily remove them. What should we do?

Could you point to the tests you disabled, please? Probably we can just enable them. @jcranmer-intel is fixing some issues in the upstream, so some passes can be expected.

**Comment by KornevNikita** [comment]
@bader 

1. Regarding nightly - 2 new failures in check-llvm-spirv:
```
LLVM_SPIRV :: extensions/EXT/SPV_EXT_shader_atomic_float_/atomicrmw_fsub_double.ll
LLVM_SPIRV :: extensions/EXT/SPV_EXT_shader_atomic_float_/atomicrmw_fsub_float.ll
```
2. I disabled [Clang :: Driver/linker-wrapper.c](https://github.com/intel/llvm/pull/7903/commits/da6bccb8fde70249e679baeab35fcfdff2934d07) and
```
  LLVM :: Bindings/llvm-c/atomics.ll
  LLVM :: Bindings/llvm-c/echo.ll
  LLVM :: Bindings/llvm-c/freeze.ll
  LLVM :: Bindings/llvm-c/globals.ll
  LLVM :: Bindings/llvm-c/invoke.ll
  LLVM :: Bindings/llvm-c/memops.ll
  LLVM :: Bitcode/blockaddress-addrspace.ll
  LLVM :: tools/llvm-reduce/file-output-type.test
  LLVM :: tools/llvm-reduce/operands-skip-parallel.ll
  LLVM :: tools/llvm-reduce/temporary-files-as-bitcode-split.ll
```
([13bbd5d](https://github.com/intel/llvm/pull/7903/commits/13bbd5d1c2a8dddab0e87d87378dda8dd062c02f), https://github.com/intel/llvm/pull/7903/commits/d58c51e3f87df5f64d013f9e2ad761d2c3895985).
P.S. tools/* already fixed, just need to cherry-pick the fix.

**Comment by KornevNikita** [comment]
As I see the most failures are similar to sycl CI, but there is still one failure - **llvm/test/Bitcode/blockaddress-addrspace.ll** - . It fails on non-opaque pointers builds, but "unexpectedly passes" (I disabled it) with the opposite - https://github.com/intel/llvm/actions/runs/3941397821/jobs/6743957748.

**Comment by bader** [comment]
@KornevNikita, thanks. I'm a bit worried about amount of changes we need to make in tests to keep testing clean. @jcranmer-intel, do the changes made by Nikita look good to you?

A few other related questions:
Do you have any ideas if can reduce the diff?
Maybe it would be easier to revert some community changes?
When do you think we can switch to opaque pointers by default?

**Comment by KornevNikita** [comment]
@bader now, after [3396f35](https://github.com/intel/llvm/pull/7903/commits/3396f35926c96b4821cf034f7fa90857d1f92a24) there is no need for such a big changes (about 1k tests). With this patch we only need to update ~110 tests. So, I'm going to reset head to [ed80508](https://github.com/intel/llvm/pull/7903/commits/ed80508cbeaa08abf31553ba0d0f24c8f6f5084c) (from where I started to fix this PR failures), apply a few mandatory patches ([3fbfdaa](https://github.com/intel/llvm/pull/7903/commits/3fbfdaa7734f307eaeed9841650c949a1e514dd8), [fd83d97](https://github.com/intel/llvm/pull/7903/commits/fd83d970cf86c264c4e5d62e0f9d0c8e70799c20), [d3aba23](https://github.com/intel/llvm/pull/7903/commits/d3aba23453771d9af1e8c8d21d63d134825d66f4)) and fix the rest of tests with adding -opaque-pointers. It should reduce changes as well.

**Comment by KornevNikita** [comment]
@bader @jcranmer-intel okay, I've reverted all previous tests changes. Now all '-opaque-pointers' related changes are in 
[dc4a7e9](https://github.com/intel/llvm/pull/7903/commits/dc4a7e9ad7963ec796e9b6cec3b6be6eef7f248e) and [e462e36](https://github.com/intel/llvm/pull/7903/commits/e462e369fa9744c2ce10621cb6171ee8c8e66e80). Now it's not ~1000 changed tests, but ~100.

**Comment by KornevNikita** [comment]
I believe now we are ready to merge... Waiting for your decision @bader @jcranmer-intel

**Comment by jcranmer-intel** [comment]
> @bader @jcranmer-intel okay, I've reverted all previous tests changes. Now all '-opaque-pointers' related changes are in [dc4a7e9](https://github.com/intel/llvm/pull/7903/commits/dc4a7e9ad7963ec796e9b6cec3b6be6eef7f248e) and [e462e36](https://github.com/intel/llvm/pull/7903/commits/e462e369fa9744c2ce10621cb6171ee8c8e66e80). Now it's not ~1000 changed tests, but ~100.

I'm somewhat concerned by the number of tests that need `-opaque-pointers` manually added to them even with the auto-set-opaque-pointers feature added back in. But doing the latter step is absolutely the right thing to do for the moment.

> When do you think we can switch to opaque pointers by default?

One thing I'm looking at doing is making an intermediate opaque pointer mode that enables opaque pointers for host compilation but disables it for offload compilation. There's a few bugs left in the SPIR-V translator with opaque pointer mode enabled, most of which should be fixed once the opencl types patches land, but there are a few other places which are not opaque pointer-ready (e.g., esimd).

**Comment by bader** [comment]
@jcranmer-intel, it sounds like you are okay with merging this solution for now, so I'm going to proceed with merging.
@intel/dpcpp-esimd-reviewers, please, help with moving ESIMD to opaque pointers.

The divergence with community code here significantly slows down pulldowns, so we need to switch to opaque pointers as soon as possible.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Wed 18 Jan 2023 10:47:28 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Wed 18 Jan 2023 10:51:38 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Comment by v-klochkov** [comment]
> hould be fixed once the opencl types patches land, but there are a few other places

@bader - Konst Bobrovsky has written some optimization/conversion for esimd::simd return values: https://github.com/intel/llvm/commit/aa70922c491f2caf5912f81a772d57c9935ffe13 + few more minor patches.
I cannot tell though if that was a good start of the work in ESIMD to switch to opaque pointers or the finalized  work.
How can I verify if ESIMD is fully functional in opaque ptr mode?

**Comment by bader** [comment]
> How do I verify if ESIMD is fully functional in opaque ptr mode?
> I guess, I need to change FALSE to TRUE here: https://github.com/intel/llvm/blob/sycl/llvm/CMakeLists.txt#L883
> and try ESIMD tests, right?

I think that's right. We are running this configuration in our Nightly builds, and I see 14 failed tests in `check-sycl` logs.

```
Failed Tests (14):
  SYCL :: check_device_code/usm_pointers.cpp
  SYCL :: esimd/ctor_codegen.cpp
  SYCL :: esimd/fp16_converts.cpp
  SYCL :: esimd/glob.cpp
  SYCL :: esimd/intrins_trans.cpp
  SYCL :: esimd/sycl_half_basic_ops.cpp
  SYCL :: esimd/sycl_half_math_ops.cpp
  SYCL :: extensions/fpga.cpp
  SYCL :: extensions/properties/properties_kernel_device_has_warning.cpp
  SYCL :: matrix/legacy/matrix-elemwise-ops.cpp
  SYCL :: matrix/legacy/matrix-int8-test.cpp
  SYCL :: matrix/matrix-elemwise-ops.cpp
  SYCL :: matrix/matrix-int8-test.cpp
  SYCL :: warnings/aspect_perserve_srcloc.cpp
```

@jcranmer-intel, do you know if these tests expose the issues you were referring to or we need to run llvm-test-suite tests?
I know that some of these are test issues where we need to update FileCheck rules.

**Comment by jcranmer-intel** [comment]
> @jcranmer-intel, do you know if these tests expose the issues you were referring to or we need to run llvm-test-suite tests? I know that some of these are test issues where we need to update FileCheck rules.

I think it's the llvm-test-suite test failures that I've been seeing large fail rates on.

**Comment by sarnex** [comment]
btw i just spoke with @v-klochkov , i'm investigating the esimd opaque ptr failures right no

**Pull request merged**
