### PR TITLE
[SYCL][CUDA] Add bf16 builtins operating on storage types

### PR DESCRIPTION
**Pull request by t4c1**
Add bf16 builtins operating on storage types. Partially implements https://github.com/intel/llvm/pull/5645/files for CUDA (only operations on storage types).
 
 This PR includes a bugfix for some NVPTX intrinsics, which will also be pushed upstream.
 
 Blocked by https://github.com/intel/llvm/pull/5724.
 
 Tests for this are in https://github.com/intel/llvm-test-suite/pull/897.

### CODE REVIEW

**Review by mlychkov — APPROVED** [review]
Changes in llvm intrinsics LGTM.

**Review by s-kanaev — COMMENTED** [review]
RT changes LGTM.

@t4c1 , should there be a test for this change?

**Comment by t4c1** [comment]
Which change do you have in mind? There are some test being added to the test suite (linked in PR description). Or do you mean something else needs testing?

**Review by s-kanaev — DISMISSED** [review]
RT changes LGTM

**Comment by s-kanaev** [comment]
> There are some test being added to the test suite (linked in PR description). 

@t4c1 , sorry, didn't notice that at first glance. Seem like that'll do.

**Comment by bader** [comment]
I had to merge with the sycl branch to resolve the conflict with https://github.com/intel/llvm/commit/53a9d541660a3f0be9d9fe611e198fe52519610b.

**Comment by t4c1** [comment]
Thanks.

**Comment by bader** [comment]
@t4c1, could you fix these warnings, please?
From https://github.com/intel/llvm/runs/5544122115?check_suite_focus=true
```
/home/runner/work/llvm/llvm/build/include/sycl/ext/oneapi/bf16_storage_builtins.hpp:40:68: error: unused parameter 'x' [-Werror,-Wunused-parameter]
std::enable_if_t<detail::is_bf16_storage_type<T>::value, T> fabs(T x) {
                                                                   ^
/home/runner/work/llvm/llvm/build/include/sycl/ext/oneapi/bf16_storage_builtins.hpp:49:68: error: unused parameter 'x' [-Werror,-Wunused-parameter]
std::enable_if_t<detail::is_bf16_storage_type<T>::value, T> fmin(T x, T y) {
                                                                   ^
/home/runner/work/llvm/llvm/build/include/sycl/ext/oneapi/bf16_storage_builtins.hpp:49:73: error: unused parameter 'y' [-Werror,-Wunused-parameter]
std::enable_if_t<detail::is_bf16_storage_type<T>::value, T> fmin(T x, T y) {
                                                                        ^
/home/runner/work/llvm/llvm/build/include/sycl/ext/oneapi/bf16_storage_builtins.hpp:58:68: error: unused parameter 'x' [-Werror,-Wunused-parameter]
std::enable_if_t<detail::is_bf16_storage_type<T>::value, T> fmax(T x, T y) {
                                                                   ^
/home/runner/work/llvm/llvm/build/include/sycl/ext/oneapi/bf16_storage_builtins.hpp:58:73: error: unused parameter 'y' [-Werror,-Wunused-parameter]
std::enable_if_t<detail::is_bf16_storage_type<T>::value, T> fmax(T x, T y) {
                                                                        ^
/home/runner/work/llvm/llvm/build/include/sycl/ext/oneapi/bf16_storage_builtins.hpp:67:67: error: unused parameter 'x' [-Werror,-Wunused-parameter]
std::enable_if_t<detail::is_bf16_storage_type<T>::value, T> fma(T x, T y, T z) {
                                                                  ^
/home/runner/work/llvm/llvm/build/include/sycl/ext/oneapi/bf16_storage_builtins.hpp:67:72: error: unused parameter 'y' [-Werror,-Wunused-parameter]
std::enable_if_t<detail::is_bf16_storage_type<T>::value, T> fma(T x, T y, T z) {
                                                                       ^
/home/runner/work/llvm/llvm/build/include/sycl/ext/oneapi/bf16_storage_builtins.hpp:67:77: error: unused parameter 'z' [-Werror,-Wunused-parameter]
std::enable_if_t<detail::is_bf16_storage_type<T>::value, T> fma(T x, T y, T z) {
                                                                            ^
8 errors generated.
```

**Pull request merged**
