### PR TITLE
[CI][MLIR] Fuse CPU/GPU E2E task + rename workflow

### PR DESCRIPTION
**Pull request by aelovikov-intel**

### CODE REVIEW

**Comment by whitneywhtsang** [comment]
This is the comment I got before for doing a similar change: https://github.com/intel/llvm/pull/9697#discussion_r1213593237

**Comment by aelovikov-intel** [comment]
> This is the comment I got before for doing a similar change: [#9697 (comment)](https://github.com/intel/llvm/pull/9697#discussion_r1213593237)

Well, we share the machines and I don't see why we'd want to avoid tasks fusion in the MLIR CI. + @stdale-intel

**Comment by etiotto** [comment]
The current setup makes it very easy to determine whether:
  1. a test failure is happening on the CPU or GPU or both
  2. what is the success rate on CPU and GPU

I took a peek at one of the SYCL branch test runs, and is unclear to me how we can easily determine whether a test case run on CPU or GPU or both, and if there is a failure on what architecture the test case failed. 

Can you explain how we could go about finding the information above in the new framework ?

**Comment by aelovikov-intel** [comment]
> a test failure is happening on the CPU or GPU or both

Just look at the last executed RUN line.

> what is the success rate on CPU and GPU

That shouldn't be done in pre-commit.

**Comment by etiotto** [comment]
Thanks for the concise explanation. I am trying to understand why running one workload (CPU + GPU) is expected to be more efficient that running the equivalent tests separately. Can you please explain?

**Comment by aelovikov-intel** [comment]
> I am trying to understand why running one workload (CPU + GPU) is expected to be more efficient that running the equivalent tests separately. Can you please explain?

Because SYCL is *very* slow in compilation. We save an extra compile by doing "compile,run1,run2" instead of "compile1,run1; compile2,run2". Another "saving" is coming from the fact that CPU task can either be dispatched to `amdgpu` *or* `gen9` class of host runners and the latter is much slower. That messes up load balancing and creates bubbles in the pipelines.

**Review by etiotto — APPROVED** [review]

**Pull request merged**
