### PR TITLE
[SYCL][HIP] add missing nearbyint and rint

### PR DESCRIPTION
**Pull request by MoveCloudROY**
Failed to compile OneDNN using DPCPP on AMD with sycl because the code [here](https://github.com/oneapi-src/oneDNN/blob/c852fdc60073a1ae298618c4faf26487b4144755/src/gpu/generic/sycl/eltwise_kernels.hpp#L137) that will run on the device actually calls `nearbyintf` [here](https://github.com/oneapi-src/oneDNN/blob/c852fdc60073a1ae298618c4faf26487b4144755/src/common/math_utils.hpp#L120-L131) , but `nearbyintf` lacks a symbolic definition.
Same solution as https://github.com/intel/llvm/pull/11177 but go straight to the `__ocml` symbols

### CODE REVIEW

**Comment by KseniyaTikhomirova** [comment]
I would leave review (and set my +1 after) to @jinge90 since libdevice is out of SYCL RT expertise

**Review by jinge90 — APPROVED** [review]

**Comment by bader** [comment]
> I would leave review (and set my +1 after) to @jinge90 since libdevice is out of SYCL RT expertise

@intel/llvm-reviewers-runtime, should we fix the CODEOWNERS file? 

I would also review this change with the @MartinWehking, who added NVIDIA and AMD GPU support to libdevice.

**Comment by jinz2014** [comment]
Thank you for the links. I have a question. Is there fp64 ?

https://github.com/intel/llvm/pull/11177/files

**Comment by MoveCloudROY** [comment]
> Thank you for the links. I have a question. Is there fp64 ?
sorry, it's added now.

**Comment by MoveCloudROY** [comment]
Please rerun the CI,  :D

**Comment by aelovikov-intel** [comment]
> @intel/llvm-reviewers-runtime, should we fix the CODEOWNERS file?

Yes, but I don't know who the owners should be... @jinge90 , can you make a PR for that?

**Review by aelovikov-intel — APPROVED** [review]
Formal approval based on @jinge90 's +1.

**Pull request merged**
