### PR TITLE
[NFC][SYCL] Add todo comment for validation of group-local variables definintion

### PR DESCRIPTION
**Pull request by mlychkov**
Signed-off-by: Mikhail Lychkov <mikhail.lychkov@intel.com>

### CODE REVIEW

**Comment by mlychkov** [comment]
@kbobrovs Could you please review this patch?

Failed test is not related to my changes and is a known issue.

**Comment by bader** [comment]
> @kbobrovs Could you please review this patch?
> 
> Failed test is not related to my changes and is a known issue.

@mlychkov, please, disable failing tests and re-run the job to get clean results.

**Comment by mlychkov** [comment]
> > @kbobrovs Could you please review this patch?
> > Failed test is not related to my changes and is a known issue.
> 
> @mlychkov, please, disable failing tests and re-run the job to get clean results.

Looks like failed test was already disabled: https://github.com/intel/llvm-test-suite/pull/205

**Comment by mlychkov** [comment]
@kbobrovs friendly ping

**Review by kbobrovs — APPROVED** [review]

**Pull request merged**
