### PR TITLE
[DeviceASAN] Implement asan_load/store for different address space

### PR DESCRIPTION
**Pull request by zhaomaosu**

### CODE REVIEW

**Review by AllanZyne — APPROVED** [review]
Nice patch!

**Comment by AllanZyne** [comment]
@intel/llvm-gatekeepers, please merge

**Comment by martygrant** [comment]
@AllanZyne there is a merge conflict to resolve before this can be merged

**Comment by zhaomaosu** [comment]
Hi @martygrant, the conflict has been resolved. Thanks.

**Pull request merged**
