### PR TITLE
[SYCL-MLIR][LoopInternalization] Add limitations

### PR DESCRIPTION
**Pull request by whitneywhtsang**
This PR fixes some compile time failures encountered while compiling SYCL-Bench with `LoopInternalization`.

### CODE REVIEW

**Comment by Naghasan** [comment]
Nice, which benchmark compile issue is this addressing ?

**Comment by whitneywhtsang** [comment]
> Nice, which benchmark compile issue is this addressing ?

When adding `LoopInternalization` in the pipeline locally (it is not currently in the pipeline), almost all passing SYCL-Bench are failing, after this PR, `2DConvolution 2mm 3mm atax bicg blocked_transform gemm gesummv matmulchain mvt syr2k syrk` pass.

**Review by Naghasan — APPROVED** [review]
LGTM

**Review by etiotto — APPROVED** [review]
LGTM - thanks

**Pull request merged**
