### PR TITLE
[sycl-post-link] Internalize non SYCL_EXTERNAL functions

### PR DESCRIPTION
**Pull request by LU-JOHN**
With -support-dynamic-linking, non SYCL_EXTERNAL functions are internalized.

### CODE REVIEW

**Review by sarnex — APPROVED** [review]
cannot comment on the background of the change but the change itself looks good to me

**Comment by asudarsa** [comment]
I am surprised why there is no testing being done here. I will try to close and reopen.

**Comment by sarnex** [comment]
There was a CI issue yesterday.

@LU-JOHN Please merge sycl/HEAD into this PR and rerun tests. If we rerun them again without doing that there is a chance we break CI for everyone. Sorry for the inconvenience.

**Review by asudarsa — APPROVED** [review]
Looks good to me. Thanks

**Pull request merged**
