### PR TITLE
[SYCL-MLIR] Make the driver set the output file cgeist should use

### PR DESCRIPTION
**Pull request by Naghasan**
Add -o <file> to the list of argument to cgeist

Signed-off-by: Victor Lomuller <victor@codeplay.com>

### CODE REVIEW

**Review by sommerlukas — APPROVED** [review]
LGTM.

**Comment by etiotto** [comment]
Would be nice to be consistent with what clang usually does w.r.t. emitting LLVM IR (with/without -o):
   - without -o:  `clang++ ~/projects/tmp/hello.cpp   -c -S -emit-llvm` a hello.ll file is produced in the current directory
   - with -o:  ` clang++ ~/projects/tmp/hello.cpp   -c -S -emit-llvm -o ettore.ll`  the file ettore.ll is produced in the current directory
Test cases can be adjusted to not rely on MLIR/LLVM IR to be generated to stdout.

**Comment by whitneywhtsang** [comment]
Please remove the XFAIL from polygeist/tools/cgeist/Test/Verification/sycl/single_task.cpp as one of the test cases for this PR. Thanks.

**Comment by Naghasan** [comment]
> Would be nice to be consistent with what clang usually does w.r.t. emitting LLVM IR (with/without -o):
> 
> * without -o:  `clang++ ~/projects/tmp/hello.cpp   -c -S -emit-llvm` a hello.ll file is produced in the current directory
> * with -o:  ` clang++ ~/projects/tmp/hello.cpp   -c -S -emit-llvm -o ettore.ll`  the file ettore.ll is produced in the current directory
> 
> Test cases can be adjusted to not rely on MLIR/LLVM IR to be generated to stdout.

so that's what happen with the patch (and the cause of the failure actually). I'll add a test checking for that.

**Review by whitneywhtsang — APPROVED** [review]

**Comment by whitneywhtsang** [comment]
Buildbot is failing because `single_task.cpp` is now passing. Please remove `XFAIL`:
```
--- a/polygeist/tools/cgeist/Test/Verification/sycl/single_task.cpp
+++ b/polygeist/tools/cgeist/Test/Verification/sycl/single_task.cpp
@@ -7,7 +7,6 @@
 // RUN: llvm-dis %t.bc
 // RUN: cat %t.ll | FileCheck %s
-// BUG: clang++ -o doesn't redirect the output to the file specified.
-// XFAIL: *
```

**Comment by etiotto** [comment]
I pushed a commit to remove the XFAIL from the test case mentioned here: https://github.com/intel/llvm/pull/6967#issuecomment-1276557621

**Review by etiotto — APPROVED** [review]

**Pull request merged**
