### PR TITLE
[GHA] Uplift Linux IGC Dev RT version to igc-dev-ad75a20

### PR DESCRIPTION
**Pull request by bb-sycl**
Scheduled igc dev drivers uplift

### CODE REVIEW

**Comment by sarnex** [comment]
@jsji Looks like the IGC dev driver install script is [failing](https://github.com/intel/llvm/actions/runs/11771361172/job/32785338435?pr=16039).

If I remember correctly I think you worked on this part of the script. If so, can you take a look? If not I'll figure it out. Thanks

**Comment by jsji** [comment]
> @jsji Looks like the IGC dev driver install script is [failing](https://github.com/intel/llvm/actions/runs/11771361172/job/32785338435?pr=16039).
> 
> If I remember correctly I think you worked on this part of the script. If so, can you take a look? If not I'll figure it out. Thanks

Look like there are some changes in the IGC CI, the packages might be different now?

**Comment by jsji** [comment]
> @jsji Looks like the IGC dev driver install script is [failing](https://github.com/intel/llvm/actions/runs/11771361172/job/32785338435?pr=16039).
> 
> If I remember correctly I think you worked on this part of the script. If so, can you take a look? If not I'll figure it out. Thanks

https://github.com/intel/llvm/pull/16073 to fix it. @sarnex

**Comment by YixingZhang007** [comment]
I have added igc-dev XFAIL to E2E test `ESIMD/PerformanceTests/matrix_transpose.cpp` because the currently igc-dev CI workflow is failing on this test. We will remove the XFAIL if this problem is resolved in future IGC public releases.

**Review by sarnex — APPROVED** [review]

**Review by YuriPlyakhin — APPROVED** [review]
LGTM,
But if XFAIL is added, while waiting for this fix: https://github.com/intel/intel-graphics-compiler/commit/bdce5e87ab841f2da0847c1923092061f982d457
Then maybe it just worth waiting for the next IGC update.
Up to you.

**Comment by sarnex** [comment]
idk if that change will actually fix it so im okay merging this for now

**Comment by YuriPlyakhin** [comment]
> idk if that change will actually fix it so im okay merging this for now

Great. All green. @intel/llvm-gatekeepers , please merge.

**Pull request merged**
