### PR TITLE
[CI][Deps] Uplift CPU/FPGAEMU RT version to 2023.16.6.0.28

### PR DESCRIPTION
**Pull request by yanfeng3721**

### CODE REVIEW

**Comment by yanfeng3721** [comment]
Please @tfzhu help to make the following links available:
https://github.com/intel/llvm/releases/download/2023-WW27/oclcpuexp-2023.16.6.0.28_rel.tar.gz
https://github.com/intel/llvm/releases/download/2023-WW27/fpgaemu-2023.16.6.0.28_rel.tar.gz
https://github.com/intel/llvm/releases/download/2023-WW27/win-oclcpuexp-2023.16.6.0.28_rel.zip
https://github.com/intel/llvm/releases/download/2023-WW27/win-fpgaemu-2023.16.6.0.28_rel.zip

**Comment by tfzhu** [comment]
> Please @tfzhu help to make the following links available: https://github.com/intel/llvm/releases/download/2023-WW27/oclcpuexp-2023.16.6.0.28_rel.tar.gz https://github.com/intel/llvm/releases/download/2023-WW27/fpgaemu-2023.16.6.0.28_rel.tar.gz https://github.com/intel/llvm/releases/download/2023-WW27/win-oclcpuexp-2023.16.6.0.28_rel.zip https://github.com/intel/llvm/releases/download/2023-WW27/win-fpgaemu-2023.16.6.0.28_rel.zip

Done

**Review by bader — CHANGES_REQUESTED** [review]
Please, fix pre-commit failures.

**Comment by yanfeng3721** [comment]
Hi @bader, [the PreCI ](https://github.com/intel/llvm/actions/runs/5938335482/job/16102718479?pr=10237) shows installing the new OpenCL CPU Runtime failed. Could you please help to check? Thanks. 
```
Installing Intel OpenCL CPU Runtime...
CPU Runtime version 2023-WW27
/runtimes/oclcpu exists and will be removed!
Traceback (most recent call last):
  File "/__w/llvm/llvm/devops/scripts/get_release.py", line 19, in <module>
    release = get_release_by_tag(repo, tag)
  File "/__w/llvm/llvm/devops/scripts/get_release.py", line 6, in get_release_by_tag
    release = urlopen("https://api.github.com/repos/" + repo + "/releases/tags/" + tag).read()
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line [56](https://github.com/intel/llvm/actions/runs/5938335482/job/16102718479?pr=10237#step:9:57)3, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line [64](https://github.com/intel/llvm/actions/runs/5938335482/job/16102718479?pr=10237#step:9:65)3, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: rate limit exceeded
tar: *.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
```

**Review by bader — APPROVED** [review]

**Comment by bader** [comment]
> Hi @bader, [the PreCI ](https://github.com/intel/llvm/actions/runs/5938335482/job/16102718479?pr=10237) shows installing the new OpenCL CPU Runtime failed. Could you please help to check? Thanks.

There is nothing unique I can do about this. I restarted CI checks and they passed.

**Comment by bader** [comment]
@yanfeng3721, I see two tests "unexpectedly" pass in Nightly tests on OpenCL CPU: https://github.com/intel/llvm/actions/runs/5946503013/job/16127794742. Could you check if these are caused by the new OpenCL CPU implementation, please?

@aelovikov-intel, do I understand it correctly that pre-commit didn't catch this because we run it on all available devices and these XFAIL marks were ignored?

**Comment by aelovikov-intel** [comment]
> @aelovikov-intel, do I understand it correctly that pre-commit didn't catch this because we run it on all available devices and these XFAIL marks were ignored?

Likely, yes.

**Comment by yanfeng3721** [comment]
> @yanfeng3721, I see two tests "unexpectedly" pass in Nightly tests on OpenCL CPU: https://github.com/intel/llvm/actions/runs/5946503013/job/16127794742. Could you check if these are caused by the new OpenCL CPU implementation, please?
>

Yes, SYCL :: Scheduler/DISABLED_DataMovement.cpp & SYCL :: SubGroup/scan_spirv13.cpp can pass with new OpenCL CPU RT. 
The following line should be removed
```
// Missing GroupNonUniformArithmetic capability on CPU RT
// XFAIL: cpu
```

**Comment by yanfeng3721** [comment]
> > > @yanfeng3721, I see two tests "unexpectedly" pass in Nightly tests on OpenCL CPU: https://github.com/intel/llvm/actions/runs/5946503013/job/16127794742. Could you check if these are caused by the new OpenCL CPU implementation, please?
> > 
> > 
> > Yes, SYCL :: Scheduler/DISABLED_DataMovement.cpp & SYCL :: SubGroup/scan_spirv13.cpp can pass with new OpenCL CPU RT. The following line should be removed
> > ```
> > // Missing GroupNonUniformArithmetic capability on CPU RT
> > // XFAIL: cpu
> > ```
> 
> Who is fixing this? Tagging @intel/llvm-reviewers-runtime for awareness.

@jiezzhang is preparing the PR.

**Comment by jiezzhang** [comment]
@bader I created a PR https://github.com/intel/llvm/pull/10966. Please help to review

**Pull request merged**
