### PR TITLE
[SYCL] Check the kernel defined by a named function object  is trivially copyable.

### PR DESCRIPTION
**Pull request by sarathnandu**
According to SYCL standard, SYCL-2020-provisional specification, the kernel defined by a named function object should be trivially copyable

Signed-off-by: sarathnandu <sarath.nandu.ramachandran.nair@intel.com>

### CODE REVIEW

**Comment by sergey-semenov** [comment]
The SYCL specification restricts named function objects to trivially copyable but not lambdas. This is likely due to the fact that whether the closure type of lambda is trivially copyable or not is an implementation detail.

**Comment by keryell** [comment]
> According to SYCL standards

When you write such a sentence, please precise the version of the standard you are talking about.

**Comment by sarathnandu** [comment]
> > According to SYCL standards
> 
> When you write such a sentence, please precise the version of the standard you are talking about.

This restriction is in the provisional specification in June  2020: https://www.khronos.org/registry/SYCL/specs/sycl-2020-provisional.pdf. Not sure if this is made final?

**Comment by sarathnandu** [comment]
> The SYCL specification restricts named function objects to trivially copyable but not lambdas. This is likely due to the fact that whether the closure type of lambda is trivially copyable or not is an implementation detail.

I have modified the pull request header accordingly, I will go ahead and amend the commit message.

**Comment by sergey-semenov** [comment]
The checks for some specializations of parallel_for_work_group are missing (e. g. L1155, L1187, L1452).

Please, amend the PR description as well.

**Comment by erichkeane** [comment]
@romanovvlad  asked me to comment:

Lambdas themselves aren't guaranteed to be trivially copyable by standard (even if their captures all are).  So this is likely a 'bad' change by C++ standard.

That said, I don't think there are any compilers (at least that we care about) that don't make them trivial if at all possible.  So from a practical perspective, I'd say this is likely fine.

**Comment by sarathnandu** [comment]
Debugging the test failures the accessors are not trivially copyable in host compilation. They are trivially copyable only in the device compilation.

for eg: the output of the following code indicates the same:
auto val = val_buf.template get_access<access::mode::read>(cgh);
std::cout << std::is_trivially_copyable<decltype(val)>::value << std::endl;

**Pull request closed without merging**
