### PR TITLE
[SYCL] Fix postcommit again

### PR DESCRIPTION
**Pull request by sarnex**
Unused param/func warnings

### CODE REVIEW

**Comment by sarnex** [comment]
FYI @KseniyaTikhomirova

**Comment by KseniyaTikhomirova** [comment]
> FYI @KseniyaTikhomirova

sorry and thanks a lot!

**Comment by sarnex** [comment]
No problem, precommit passed so it's not your fault

**Comment by KseniyaTikhomirova** [comment]
I see TEST 'SYCL :: Basic/stream/blocking_pipes_and_stream.cpp' FAILED, working on this.

**Comment by sarnex** [comment]
Thanks!

**Comment by sarnex** [comment]
@KseniyaTikhomirova BTW if you can't fix the test immediately please submit a PR disabling it for now to unblock others. thanks!

**Comment by KseniyaTikhomirova** [comment]
> @KseniyaTikhomirova BTW if you can't fix the test immediately please submit a PR disabling it for now to unblock others. thanks!

It fails with timeout so I would suggest disable it for now https://github.com/intel/llvm/pull/14392
I will work on fix and reenabling with top priority

**Comment by KseniyaTikhomirova** [comment]
more fixes https://github.com/intel/llvm/pull/14396

**Pull request merged**
