### PR TITLE
[ESIMD] Reenable the thread_id test after CI was updated

### PR DESCRIPTION
**Pull request by fineg74**

### CODE REVIEW

**Review by v-klochkov — APPROVED** [review]

**Comment by bader** [comment]
@v-klochkov, please, do not merge unvalidated changes!
I suspect this change will break the pre-commit checks. If so, please, revert ASAP.

**Comment by bader** [comment]
The test fails on Linux. See https://github.com/intel/llvm/actions/runs/4679913898/jobs/8291106986.
Please, fix ASAP. The right fix should be like this - https://github.com/intel/llvm/pull/9017/commits/82d17df817b3c137a2066fa93490e30c90cada9b.

**Comment by v-klochkov** [comment]
> @v-klochkov, please, do not merge unvalidated changes! I suspect this change will break the pre-commit checks. If so, please, revert ASAP.

@bader - I saw 8 passed checks and no fails, then merged. 2 tasks did not start, I thought it was normal, my fault.
Do you know why they did not start? How to initiate those tasks/runs if they refused to start initially?

**Comment by bader** [comment]
> Do you know why they did not start? How to initiate those tasks/runs if they refused to start initially?

See error messages here - https://github.com/intel/llvm/actions/runs/4675184536
The branch must be re-based.

**Pull request merged**
