### PR TITLE
[SYCL][NATIVECPU][CI] Enable Native CPU without OCK on linux build

### PR DESCRIPTION
**Pull request by PietroGhg**
This PR enables the Native CPU plugin in the build jobs for Linux. It is the first PR in series, with the goal of enabling full `e2e` testing for the Native CPU plugin on both Linux and Windows.

This initial PR builds the Native CPU plugin without the oneAPI Construction Kit. While the oneAPI Construction Kit is currently a key component for Native CPU, I would prefer to keep things as simple as possible, and enable CI testing for additional features incrementally, in order to gradually assess the impact of the Native CPU plugin in the overall CI workflow.

### CODE REVIEW

**Comment by PietroGhg** [comment]
Hi @intel/dpcpp-devops-reviewers, the main job affected by this PR (`SYCL Pre Commit on Linux / build / Build + LIT (pull_request) `) is successful, but the `check-sycl` target has been skipped, do you know if there's a way for me to force running that target?

**Comment by aelovikov-intel** [comment]
Should we do `s/plug in/plugin/g` in the PR description?

**Comment by PietroGhg** [comment]
> > Hi @intel/dpcpp-devops-reviewers, the main job affected by this PR (`SYCL Pre Commit on Linux / build / Build + LIT (pull_request) `) is successful, but the `check-sycl` target has been skipped, do you know if there's a way for me to force running that target?
> 
> This change also triggered post-commit task and `check-sycl` seemed to be tested there, see https://github.com/intel/llvm/actions/runs/8326107523/job/22781117393?pr=13052.

Yeah you are right, but I see `native_cpu=False` in the log for the configure step for post commit, do you think I should enable the native cpu plugin for post commit on linux as part of this PR?

**Comment by aelovikov-intel** [comment]
> do you think I should enable the native cpu plugin for post commit on linux as part of this PR

Probably. The main difference in pre- vs post- is that in pre-commit end-to-end tests we use multiple SYCL devices in a single invocation that results in XFAIL-marked tests to be simply skipped. Post-commit uses one SYCL device per `llvm-lit` invocation and XFAILs are properly tested there.

**Comment by PietroGhg** [comment]
The error in the post commit linux build pipeline is due to the fact that we run some SYCL executables in the tests in `sycl/test/native_cpu`, I'll address that in a separate PR and update this one accordingly

**Comment by PietroGhg** [comment]
@intel/dpcpp-devops-reviewers I've undrafted this PR since the Post Commit Linux Build job executed successfully (in the [log](https://github.com/intel/llvm/actions/runs/8555961346/job/23444601826?pr=13052) you can see that the build was configured with `--native_cpu` and  `-DNATIVECPU_USE_OCK=Off`), what do you think about these changes?

**Review by aelovikov-intel — APPROVED** [review]

**Comment by PietroGhg** [comment]
I just realized that post commit tests are being built with `-fsycl-targets=spir64,native_cpu`, which is not intended, I'll address this

**Comment by PietroGhg** [comment]
@aelovikov-intel / @intel/llvm-reviewers-runtime, I've marked `sycl/test-e2e/PerformanceTests/Reduction/reduce_over_sub_group.cpp`  as unsupported on Native CPU, which should fix [this](https://github.com/intel/llvm/actions/runs/8555961346/job/23445424830) error, all the other CI errors I see now should be unrelated to this PR.

**Comment by aelovikov-intel** [comment]
> all the other CI errors I see now should be unrelated to this PR.

Not good enough to merge :) I've restarted the job. If the fail would remain, I'd need a link to the same failure elsewhere to prove it's unrelated.

**Comment by PietroGhg** [comment]
Hi @aelovikov-intel, coming back to this PR, the pre-commit failure on CUDA is seen in other PRs e.g. https://github.com/intel/llvm/pull/13695. The failure on the Arc job seems to appear also in [this](https://github.com/intel/llvm/actions/runs/8990340966/job/24697705620) run, associated to commit `31f1f1c`. I'm not sure about the two `perf-test` failures, on AMD and CUDA, they fail with` cannot find -lstdc++` during cmake config, so the failure seems related to the runner config?

**Pull request merged**
