### PR TITLE
[SYCL] Refactor FPGA Memory Attributes Validation for Clarity and and Efficiency

### PR DESCRIPTION
**Pull request by smanna12**
This commit refactors the CheckValidFPGAMemoryAttributesVar function in SemaDeclAttr.cpp to improve the clarity and efficiency of the validation logic for 11 FPGA memory attributes on variables. The updated implementation streamlines the condition checks, making the code easier to read and understand.

Key changes include:
    - Simplifying the conditional logic to reduce complexity.
    - Using direct return statements for immediate feedback on validation status.
    - Enhancing readability by clearly separating checks for different variable types and attributes.
    
This refactor ensures that the function more clearly expresses its intent, making the codebase more accessible for future development and optimizations. 

No functional changes are intended with this refactor; it aims solely at improving code quality and readability.

Signed-off-by: Soumi Manna <soumi.manna@intel.com>

### CODE REVIEW

**Comment by smanna12** [comment]
The failure is unrelated to my patch: 
Failed Tests (1):
  SYCL :: abi/sycl_classes_abi_neutral_test.cpp

**Review by elizabethandrews — APPROVED** [review]

**Comment by smanna12** [comment]
Thank you @elizabethandrews for reviews!

**Comment by smanna12** [comment]
@intel/llvm-gatekeepers, This PR is ready to merge. Thank you

**Comment by sarnex** [comment]
```
  SYCL :: abi/sycl_classes_abi_neutral_test.cpp
```

not related and already fixed in other commit

**Pull request merged**
