### PR TITLE
[SYCL][CUDA][HIP] Add missing PI_DEVICE_INFO_IMAGE_SRGB case

### PR DESCRIPTION
**Pull request by MartinWehking**
Adds `PI_DEVICE_INFO_IMAGE_SRGB` to the switch case in `piDeviceGetInfo`.
It's a required fix for #8433 .
Before, `sycl-ls --verbose` in #8433 terminated with an error since the default case was invoked (`pi::die`)

### CODE REVIEW

**Comment by GeorgeWeb** [comment]
We should add this case to `hip_piDeviceGetInfo` in `pi_hip.cpp` as well, seems to be missing there as well and the hip plugin's function is set up to assert in the same way as in the cuda plugin.

**Comment by GeorgeWeb** [comment]
LGTM.

**Review by againull — APPROVED** [review]

**Comment by jchlanda** [comment]
A quick grep through CUDA's plugin shows the following enums missing:
```
PI_EXT_CODEPLAY_DEVICE_INFO_SUPPORTS_FUSION
PI_EXT_ONEAPI_DEVICE_INFO_MAX_GLOBAL_WORK_GROUPS
PI_EXT_ONEAPI_DEVICE_INFO_MAX_WORK_GROUPS_1D
PI_EXT_ONEAPI_DEVICE_INFO_MAX_WORK_GROUPS_2D
PI_DEVICE_INFO_IL_VERSION
PI_DEVICE_INFO_QUEUE_PROPERTIES
```
I guess it's OK to call `die` on the extensions, but maybe we should return `PI_ERROR_INVALID_VALUE` for the remaining two?

**Comment by MartinWehking** [comment]
@jchlanda 
That's a good idea.
However, I think it's better to leave that for a future PR since this one's just meant to unblock #8433

**Review by jchlanda — APPROVED** [review]

**Pull request merged**
