### PR TITLE
[SYCL][E2E] Update unsupported tests with issue

### PR DESCRIPTION
**Pull request by KornevNikita**
Update the format of UNSUPPORTED tests that already have an issue link

### CODE REVIEW

**Review by joeatodd — APPROVED** [review]
SYCLcompat changes LGTM, thanks!

**Review by AllanZyne — APPROVED** [review]

**Review by EwanC — APPROVED** [review]
Graph tests LGTM, thanks for fixing this up

**Review by aarongreig — APPROVED** [review]

**Review by sarnex — APPROVED** [review]
lgtm, thanks!

**Comment by KornevNikita** [comment]
hi @sergey-semenov, could you take a look please?

**Review by sergey-semenov — APPROVED** [review]

**Pull request merged**
