### PR TITLE
[UR] disable UMF CUDA provider

### PR DESCRIPTION
**Pull request by pbalcer**
Updates UR to the latest version that no longer
needlessly fetches CUDA headers.

### CODE REVIEW

**Comment by aarongreig** [comment]
this isn't going to build until https://github.com/intel/llvm/pull/14459 gets merged

**Comment by pbalcer** [comment]
> this isn't going to build until #14459 gets merged

rebased

**Comment by pbalcer** [comment]
@intel/unified-runtime-reviewers please review

**Review by aarongreig — APPROVED** [review]

**Comment by aarongreig** [comment]
@intel/llvm-gatekeepers please merge

**Pull request merged**
