### PR TITLE
[UR] Bump HIP tag to 399430da

### PR DESCRIPTION
**Pull request by kbenzie**

### CODE REVIEW

**Review by aarongreig — APPROVED** [review]

**Comment by kbenzie** [comment]
@intel/llvm-gatekeepers please merge

**Comment by dm-vodopyanov** [comment]
@kbenzie why `UNIFIED_RUNTIME_TAG` can't be updated instead for all 5 adapters?

**Comment by kbenzie** [comment]
> @kbenzie why `UNIFIED_RUNTIME_TAG` can't be updated instead for all 5 adapters?

This PR and those which bumped the tags for the other adapters point at different tags, this allowed for asynchronous merging and testing of the changes which only touch single adatpers. This allowed us to merge 13 UR PR's yesterday which is a lot more than the normal 1 or 2. After this goes in, I'll be synchronising all the tags again as the next changes will be affecting multiple adatpers.

**Comment by kbenzie** [comment]
For exmaple, these Level Zero adapter changes #13987 merged to UR after the HIP changes in this PR. If we were to always require setting `UNIFIED_RUNTIME_TAG` we would always need to merge UR tag updates in intel/llvm in the same order as they get merged to UR. This was a major bottleneck in the past, especially for changes only affecting one adapter.

Having the ability to asynchonously merge adapter updates like this has greatly improved UR merge velocity while retaining an acceptable level of quality.

**Pull request merged**
