### PR TITLE
[SYCL][Fusion] Add fusion device info descriptor

### PR DESCRIPTION
**Pull request by sommerlukas**
Implement the `sycl::ext::codeplay::experimental::info::device::supports_fusion` device descriptor defined by the [kernel fusion extension proposal](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/experimental/sycl_ext_codeplay_kernel_fusion.asciidoc). 

Kernel fusion is currently limited to SPIR-V based backends, so support can be determined based on the device's backend.

Signed-off-by: Lukas Sommer <lukas.sommer@codeplay.com>

### CODE REVIEW

**Comment by againull** [comment]
Friendly ping  @cperkinsintel

**Review by victor-eds — APPROVED** [review]

**Review by steffenlarsen — APPROVED** [review]
LGTM!

**Comment by steffenlarsen** [comment]
Failure on CUDA is a CI problem. CUDA backend should be unaffected by these changes.

**Comment by sommerlukas** [comment]
Thanks for the quick review @steffenlarsen!

**Pull request merged**
