### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW19 2024)

### PR DESCRIPTION
**Pull request by iclsrc**
LLVM: llvm/llvm-project@8d9b15497d70ac782d7d01a2d606f9fec7e7f642
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@8878e7bfddbe2cbd86256c8e4e563a9f78a5e321

### CODE REVIEW

**Comment by jsji** [comment]
This is ready for review.

- [ ] [[SYCL][Test] Fix multi-action warning after](https://github.com/intel/llvm/pull/13724/commits/799f69c4169c810569a4d9003308707368203b7e) https://github.com/intel/llvm/commit/e74a7a9fd79a74073277471243a44527c71eb4a9 @intel/dpcpp-cfe-reviewers 
- [ ] [Revert "Revert "[CodeGen] Implement post-opt linking option for built…](https://github.com/intel/llvm/pull/13724/commits/3b303a5cdc9e6749669bf7d9166d2d201f2ad67c) The is to reland a reverted commit, sync the affected files with community. @intel/dpcpp-cfe-reviewers .

**Comment by jsji** [comment]
@intel/dpcpp-cfe-reviewers Please have a look at the two fixes above and comment/approve explicitly so that this can be merged. Thanks.

**Review by smanna12 — APPROVED** [review]
CFE changes LGTM. Thanks

**Comment by jsji** [comment]
@intel/llvm-gatekeepers Can someone help to issue a `/merge`. Thanks.

**Comment by jsji** [comment]
@DoyleLi Looks like the bot is broken? Can you have a look? Thanks.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Wed 15 May 2024 12:47:26 AM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Wed 15 May 2024 12:51:44 AM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
