### PR TITLE
[SYCL-MLIR] Reenable assertion in DenseAnalysis 

### PR DESCRIPTION
**Pull request by whitneywhtsang**
Please do not squash and merge this PR.

### CODE REVIEW

**Comment by whitneywhtsang** [comment]
@victor-eds cherry picking https://github.com/llvm/llvm-project/commit/10ae8ae8375d6b69064204338a33500917749da9 doesn't fix the `constant-propagation.mlir` failure.

**Comment by victor-eds** [comment]
> @victor-eds cherry picking [llvm/llvm-project@10ae8ae](https://github.com/llvm/llvm-project/commit/10ae8ae8375d6b69064204338a33500917749da9) doesn't fix the `constant-propagation.mlir` failure.

Looking into this now

**Comment by etiotto** [comment]
> The bug was definitely introduced by [this patch](https://reviews.llvm.org/D155757). I commented there reporting the error and will ping here when that's ready

The MLIR folks mentioned to submit a patch to remove the assertion.

**Comment by whitneywhtsang** [comment]
https://github.com/intel/llvm/pull/11153 should fix the original issue.

**Pull request closed without merging**
