### PR TITLE
[github/CODEOWNERS] Add code owner for Sanitizer code

### PR DESCRIPTION
**Pull request by cdai2**

### CODE REVIEW

**Review by uditagarwal97 — APPROVED** [review]

**Comment by bader** [comment]
@intel/dpcpp-devops-reviewers, FYI. post-commit fails on windows with:

mkdir: cannot create directory 'install': File exists

**Comment by sarnex** [comment]
Ill reboot the machine

**Comment by bader** [comment]
@sarnex, do you know what caused this problem? What can we do to avoid getting into this situation again?

**Comment by sarnex** [comment]
I have no idea unfortunately.

**Comment by bader** [comment]
I suppose that some process is using the 'install' directory, and that blocked the removal and creation of the directory.

A couple of ideas to improve the situation:
- use unique location for each build. The caveat is we should control the free space on the disk, and make sure that workspaces are cleaned up.
-  automate the "reboot" work-around.

**Pull request merged**
