### PR TITLE
[BuildBot] Uplift GPU RT version for Linux CI Process

### PR DESCRIPTION
**Pull request by bb-sycl**
Uplift GPU RT version for Linux to 21.48.21782

### CODE REVIEW

**Comment by yanfeng3721** [comment]
The same Regression detected as https://github.com/intel/llvm/pull/5037
```
[2021-12-05T20:52:43.225Z] # command stderr:
[2021-12-05T20:52:43.225Z] 'ADLS' is not a recognized processor for this target (ignoring processor)
[2021-12-05T20:52:43.225Z] 'ADLS' is not a recognized processor for this target (ignoring processor)
[2021-12-05T20:52:43.225Z] 'ADLS' is not a recognized processor for this target (ignoring processor)
[2021-12-05T20:52:43.225Z] 'ADLS' is not a recognized processor for this target (ignoring processor)
[2021-12-05T20:52:43.225Z] error: GenXLegalization failed for: <  %call.i.i.i.i = select <1 x i1> %cmp.i.i85.i, <1 x i64> %sub.i.i, <1 x i64> %call.i.i.i27.i.i>: 'i64' data type is not supported by this target <ADLS>
[2021-12-05T20:52:43.225Z] llvm-foreach: 
[2021-12-05T20:52:43.225Z] clang-14: error: gen compiler command failed with exit code 1 (use -v to see invocation)
[2021-12-05T20:52:43.225Z] 
[2021-12-05T20:52:43.225Z] error: command failed with exit status: 1
```

**Comment by bader** [comment]
@kbobrovs, FYI.

**Comment by kbobrovs** [comment]
@bader, mandelbrot and dgetrf are already re-enabled by https://github.com/intel/llvm-test-suite/pull/600 2 days ago. patch for aot_mixed: https://github.com/intel/llvm-test-suite/pull/605

**Comment by bader** [comment]
@vladimirlaz, ping.

**Comment by bader** [comment]
@vladimirlaz, why do we pushing outdated version?
Shouldn't we commit https://github.com/intel/llvm/pull/5129 instead?

**Comment by vladimirlaz** [comment]
> @vladimirlaz, why do we pushing outdated version? Shouldn't we commit #5129 instead?

you are right. closing obsolete PR

**Pull request closed without merging**
