### PR TITLE
[CI] Add Matrix E2E tests in compile-only mode

### PR DESCRIPTION
**Pull request by aelovikov-intel**

### CODE REVIEW

**Comment by aelovikov-intel** [comment]
HIP failures are due to infrastructure issue - I've rebooted the runner since then.

**Review by YuriPlyakhin — APPROVED** [review]

**Comment by bader** [comment]
Can't we make matrix e2e tests to skip the run step on systems w/o matrix HW support (i.e. build only)?

**Comment by aelovikov-intel** [comment]
> Can't we make matrix e2e tests to skip the run step on systems w/o matrix HW support (i.e. build only)?

What we're doing is a workaround and I'd like it to be isolated in a single place. Making the change you're suggesting would require fixing all the matrix tests to behave like that.

**Comment by bader** [comment]
> > Can't we make matrix e2e tests to skip the run step on systems w/o matrix HW support (i.e. build only)?
> 
> What we're doing is a workaround and I'd like it to be isolated in a single place. Making the change you're suggesting would require fixing all the matrix tests to behave like that.

Not necessary. I think it can be done in a lit config for https://github.com/intel/llvm/tree/sycl/sycl/test-e2e/Matrix directory. Right?
BTW, I consider fixing only "the matrix tests" to be an isolated as well.

**Comment by aelovikov-intel** [comment]
> I think it can be done in a lit config

Maybe, but I don't know how.

**Comment by aelovikov-intel** [comment]
We are setting up an ATS-M runner that would support execution of Matrix tests. Closing this PR.

**Pull request closed without merging**
