### PR TITLE
[SYCL] Add new imf simd API

### PR DESCRIPTION
**Pull request by jinge90**
Adds new simd emulate functions.

### CODE REVIEW

**Comment by jinge90** [comment]
Hi, @tangjj11 
This PR adds the new CUDA simd functions, you can prepare in SYCLomatic side once this PR is merged.
Thanks very much.

**Comment by jinge90** [comment]
Hi, @steffenlarsen 
Could you take a look at this PR?
Thanks very much.

**Comment by jinge90** [comment]
Hi, @tangjj11 
Please help review this PR.
Thanks very much.

**Review by steffenlarsen — APPROVED** [review]
LGTM!

**Comment by jinge90** [comment]
Hi, @intel/dpcpp-tools-reviewers 
Could you help review this PR?
Thanks very much.

**Comment by jinge90** [comment]
Hi, @intel/dpcpp-tools-reviewers 
Kind ping~~~

**Comment by jinge90** [comment]
Hi, @stdale-intel 
Could you take a look at this PR?
Thanks very much.

**Comment by jinge90** [comment]
Hi, @intel/dpcpp-tools-reviewers 
Could you take a look at this PR?
Thanks very much.

**Review by asudarsa — APPROVED** [review]
Overall looks good. Thanks

**Comment by jinge90** [comment]
Hi, @intel/llvm-gatekeepers 
Could you merge this PR?
Thanks very much.

**Pull request merged**
