### PR TITLE
[SYCL][NFC] Fix esimg/vadd.cpp: Data need to bring back

### PR DESCRIPTION
**Pull request by TApplencourt**
The buffer destructor should be called to synchronize and bring back the data to the device.
The simplest is to exit the scope.

### CODE REVIEW

**Review by DenisBakhvalov — DISMISSED** [review]
LGTM, besides CI issues.

**Review by kbobrovs — APPROVED** [review]
good catch, thanks!

**Comment by TApplencourt** [comment]
Sorry about all those commits trying to fix the formatting.  I should stop using Github GUI to make PR...

**Comment by kbobrovs** [comment]
> Sorry about all those commits trying to fix the formatting. I should stop using Github GUI to make PR...

No problem. BTW, clang-format is the recommended tool - see the [contribution guide](https://github.com/intel/llvm/blob/sycl/CONTRIBUTING.md#development).

**Review by kbobrovs — APPROVED** [review]

**Pull request merged**
