### PR TITLE
Revert "[InstCombine] Always try to invert non-canonical predicate of…

### PR DESCRIPTION
**Pull request by AlexeySotkin**
… an icmp"

This reverts commit c3b8bd1eea5b74b6cd4a89f3c221bc2dfa891248.

Alse adjust a couple of Clang LIT tests.

Signed-off-by: Alexey Sotkin <alexey.sotkin@intel.com>

### CODE REVIEW

**Comment by Fznamznon** [comment]
What is the reason for this revert?

**Comment by AlexeySotkin** [comment]
> What is the reason for this revert?

In some cases canonicalization of `icmp` predicate gives worse performance than having predicates in non-canonical form.

**Comment by bader** [comment]
It sounds like an issue, which should be addressed by the  back end compiler.
Note, we won't be able to revert this patch in llorg with such justification.

**Comment by AlexeySotkin** [comment]
> /summary:run

Thanks!

**Comment by bader** [comment]
@AlexeySotkin, are still going to commit this change?

**Comment by AlexeySotkin** [comment]
> @AlexeySotkin, are still going to commit this change?

No.

**Pull request closed without merging**
