### PR TITLE
[WIP][SYCL] Improve thread-safety of the Level Zero plugin

### PR DESCRIPTION
**Pull request by againull**
Currently only access to all state of a pi_queue object is guarded with
a mutex. This patch implements similar approach for all other pi objects.

Signed-off-by: Artur Gainullin <artur.gainullin@intel.com>

### CODE REVIEW

**Comment by smaslov-intel** [comment]
@againull : please split this into at least 2 separate PRs

**Comment by againull** [comment]
> @againull : please split this into at least 2 separate PRs

Yes, sure.

**Pull request closed without merging**
