### PR TITLE
[SYCL] Improve all_specialization_constant_native()

### PR DESCRIPTION
**Pull request by KornevNikita**
To apply comments from: https://github.com/intel/llvm/pull/8613

### CODE REVIEW

**Comment by KornevNikita** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1651

**Comment by KornevNikita** [comment]
@AlexeySachkov hi! Take a look please, this is to apply your suggestions from https://github.com/intel/llvm/pull/8613

**Comment by KornevNikita** [comment]
@sergey-semenov take a small look please, there are just few strings.

**Review by AlexeySachkov — APPROVED** [review]

**Review by sergey-semenov — APPROVED** [review]

**Comment by KornevNikita** [comment]
@intel/llvm-gatekeepers merge please

**Pull request merged**
