### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW45)

### PR DESCRIPTION
**Pull request by Fznamznon**
LLVM: llvm/llvm-project@41dba9e
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@a33d3af

### CODE REVIEW

**Comment by Fznamznon** [comment]
Post commit fails are same as in https://reviews.llvm.org/D136281 meaning they are unrelated. Precommit fail looks like infra issue, I'll submit an internal tracker.
@pvchupin , does it look good to go?

**Comment by pvchupin** [comment]
post-commit issues are caused by https://github.com/intel/llvm/pull/7167
There is also another new one caused by https://github.com/intel/llvm/pull/7130

It looks good to go.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Fri 04 Nov 2022 04:55:58 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Fri 04 Nov 2022 04:59:48 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
