### PR TITLE
[SYCL][MacOS] Implement OSUtils::getCurrentDSODir for Darwin OS

### PR DESCRIPTION
**Pull request by AlexeySachkov**
This patch fixes misc.OsUtils unit-test.

Signed-off-by: Alexey Sachkov <sachkov2011@gmail.com>

### CODE REVIEW

**Comment by AlexeySachkov** [comment]
@alexbatashev: FYI

**Review by alexbatashev — APPROVED** [review]

**Review by cperkinsintel — APPROVED** [review]
LGTM

**Comment by bader** [comment]
@AlexeySachkov, this change broke post-commit tests on Windows.
Could you fix it ASAP, please?

**Comment by AlexeySachkov** [comment]
> @AlexeySachkov, this change broke post-commit tests on Windows. Could you fix it ASAP, please?

I will take a look, but I doubt that the regression is caused by my changes: they were all under `#ifdef` branches which are excluded from Windows builds. Additionally, the very next two patches passed post-commit on Windows: [`332e4ee0bc033742920a300537e6b3a4abb00b7e`](https://github.com/intel/llvm/actions/runs/3228915605/jobs/5285612933) and [`b4492808cf84897228f604d3c6d0040fb5ebaa67`](https://github.com/intel/llvm/actions/runs/3229513692/jobs/5286902651), but then it failed again  for [`c44a84a14ff6ab1f55885aae21182f0c70f124b2`](https://github.com/intel/llvm/actions/runs/3233037987/jobs/5294372320)

**Comment by bader** [comment]
Sorry, but you got the short end of the stick with this one.

**Pull request merged**
