### PR TITLE
[SYCL][COMPAT] Memset API updated to support 2-byte and 4-byte memsets

### PR DESCRIPTION
**Pull request by Alcpz**
- The memory interface has changed:
    - fill has been removed
    - memset now offers a templated version (which works as fill did)
    - memset_d8, memset_d16, and memset_d32 were added to allow memsetting 1, 2 and 4 byte-sized values.

### CODE REVIEW

**Comment by joeatodd** [comment]
Working through this PR, I see that we have previously been somewhat inconsistent about `pitched_data`. In a few places the `_x` dimension is described as 'number of elements' but it definitely ought to be in bytes. I will work through that.

**Comment by JackAKirk** [comment]
@konradkusiak97 is this a duplication of your fill work? Maybe there should just be a single interface for this functionality?

**Comment by konradkusiak97** [comment]
> @konradkusiak97 is this a duplication of your fill work? Maybe there should just be a single interface for this functionality?

After https://github.com/intel/llvm/pull/12702 is merged, the fill command will use backend-specific calls like `cuMemsetD16, D32` etc. so I imagine it would be quite similar.

**Comment by Alcpz** [comment]
Closed. Functionalities reintroduced through https://github.com/intel/llvm/pull/13409

**Pull request closed without merging**
