### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW43)

### PR DESCRIPTION
**Pull request by vmaksimo**
LLVM: llvm/llvm-project@4de215f
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@bd4c88a

### CODE REVIEW

**Review by bader — CHANGES_REQUESTED** [review]
Please, resolve merge conflicts.

**Comment by vmaksimo** [comment]
**Jenkins/Summary** failed only for Linux Regression_Performance_GPU - all regressions are less than 1%.
The PR is ready to be merged.

**Comment by vladimirlaz** [comment]
Internal ticket has been created to track regression reported.

**Pull request merged**
