### PR TITLE
[libclc] Cherry-pick two dropped upstream commits

### LINKED ISSUE #16015: Reland libclc patches reverted in sycl-web
### Describe the bug

A lot of libclc-related patches are coming in from upstream causing massive conflicts in sycl-web. Some of them are not easy to apply without deep knowledge of libclc, so they were just reverted and need to be relanded. Please, see below a list of the reverted patches:

- https://github.com/llvm/llvm-project/commit/7be30fd5335ca7fe050ee1789ea2648f014daf1b
- https://github.com/llvm/llvm-project/commit/b231647475b7fa78ad9382a5505889f1167e9cea

Please, feel free to edit the description to add new reverted patches.

### PR DESCRIPTION
**Pull request by frasercrmck**
This PR cherry-picks two upstream libclc commits which were dropped during pulldowns:

- https://github.com/llvm/llvm-project/commit/7be30fd5335ca7fe050ee1789ea2648f014daf1b
- https://github.com/llvm/llvm-project/commit/b231647475b7fa78ad9382a5505889f1167e9cea

Resolves #16015.

There are some changes to NVPTX libspirv generation, for example:

```
in function _Z9__clc_tanDv16_d:
  in block %entry:
    >   %call.i7.i11.i17.i29 = tail call double @llvm.fabs.f64(double noundef %0) #46
    >   %cmp.i8.i12.i18.i30 = fcmp olt double %call.i7.i11.i17.i29, 0x41D0000000000000
    >   br i1 %cmp.i8.i12.i18.i30, label %if.then.i27.i145.i288.i574, label %if.else.i9.i13.i19.i31
    <   %call.i46 = tail call double @__nv_fabs(double noundef %0) #46
    <   %cmp.i8.i12.i18.i30 = fcmp olt double %call.i46, 0x41D0000000000000
    <   br i1 %cmp.i8.i12.i18.i30, label %if.then.i25.i141.i280.i558, label %if.else.i9.i13.i19.i31
```

This is because `__clc` functions are using `__clc` functions internally, as are done in upstream. In the case above, `__clc_tan` now calls `__clc_fabs` instead of `__spirv_ocl_fabs` - the latter of which is specialized on NVPTX to call `__nv_fabs`. This should be fine, and ideally more performant. This shows also that the libspirv builtins are still in an in-between state. Follow-up patches will attempt to bring them more in line with upstream.

### CODE REVIEW

**Review by ldrumm — APPROVED** [review]
Do we know why they were dropped i.e. is this an accident, or was there a reason to avoid this? @jsji could maybe comment.

Also, these will be squashed unless a maintainer can merge them properly.

Otherwise LGTM

**Comment by jsji** [comment]
> * 7be30fd

https://github.com/intel/llvm/issues/16015 They are reverted due to conflicts that needs @frasercrmck 's help.

**Comment by frasercrmck** [comment]
> Also, these will be squashed unless a maintainer can merge them properly.

Yeah. Last time (#15948) we were able to merge them "properly" because they acted as a pulldown. If that's not possible this time around I'll have to create two separate PRs for them - squashing upstream commits isn't a good look.

**Comment by frasercrmck** [comment]
@sarnex would it be possible to merge these two cherry-picks, please? If squashing is the only option I'd rather close this PR and open a new one per cherry-pick.

**Comment by sarnex** [comment]
@frasercrmck Yeah squash is the only option unfortunately:

image

**Comment by frasercrmck** [comment]
> @frasercrmck Yeah squash is the only option unfortunately:
> 
> image

Ah, okay, thanks. Just that in https://github.com/intel/llvm/pull/15948 it seemed like you were able to merge as if it were a pulldown. Has something changed?

**Comment by sarnex** [comment]
ok i think i can do it manually, hold on

**Comment by sarnex** [comment]
@frasercrmck Ok I think I did the right think, if I didn't, I know even know if it's possible to undo it so sorry :P

**Comment by frasercrmck** [comment]
> @frasercrmck Ok I think I did the right thing, if I didn't, I know even know if it's possible to undo it so sorry :P

Thank you! I'll try and avoid it in the future, in that case. It's just that sometimes there can be half a dozen little commits to cherry-pick for libclc, and opening a PR for each individually seems silly to me.

**Comment by sarnex** [comment]
yeah for cherry picking preserving the history is better, thanks!

**Pull request closed without merging**
