### PR TITLE
[SYCL][L0] Avoid PI kernel leak for SYCL-L0 interop kernel

### PR DESCRIPTION
**Pull request by smaslov-intel**
Signed-off-by: Sergey V Maslov <sergey.v.maslov@intel.com>

### CODE REVIEW

**Review by romanovvlad — APPROVED** [review]
Please, add a test to sycl/unittests/

**Comment by smaslov-intel** [comment]
> Please, add a test to sycl/unittests/

There is already an E2E test in llvm-test-suite/SYCL/OnlineCompiler/online_compiler_L0.cpp, which found the problem.
I don't think we need to spend time to create a unittest for this

**Comment by romanovvlad** [comment]
> > Please, add a test to sycl/unittests/
> 
> There is already an E2E test in llvm-test-suite/SYCL/OnlineCompiler/online_compiler_L0.cpp, which found the problem. I don't think we need to spend time to create a unittest for this

Could you please clarify if the test fails without the patch? If not, probably we need to improve it/write a better one.

**Comment by smaslov-intel** [comment]
> > > Please, add a test to sycl/unittests/
> > 
> > 
> > There is already an E2E test in llvm-test-suite/SYCL/OnlineCompiler/online_compiler_L0.cpp, which found the problem. I don't think we need to spend time to create a unittest for this
> 
> Could you please clarify if the test fails without the patch? If not, probably we need to improve it/write a better one.

Yes, the test fails without this patch when run in valgrind.

**Comment by smaslov-intel** [comment]
@againull , @bader : can this be merged, please?

**Pull request merged**
