### PR TITLE
[SYCL][Graph][E2E] Remove float usage from Graph tests

### PR DESCRIPTION
**Pull request by Bensuo**
- Removes usage of float from graph E2E tests to avoid precision differences between host and some GPUs

Addresses issue reported in #10860

### CODE REVIEW

**Review by julianmi — APPROVED** [review]
LGTM

**Comment by Bensuo** [comment]
AMD failure is unrelated to this PR, tests are failing to find a device.

**Review by steffenlarsen — APPROVED** [review]
LGTM!

**Comment by steffenlarsen** [comment]
HIP failures reported in https://github.com/intel/llvm/issues/10460

**Pull request merged**
