### PR TITLE
[SYCL][E2E test] Add -fno-fast-math to math tests that relies on it

### PR DESCRIPTION
**Pull request by KseniyaTikhomirova**

### CODE REVIEW

**Review by sergey-semenov — APPROVED** [review]

**Comment by KseniyaTikhomirova** [comment]
> Do we need here as well? https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/Basic/built-ins/marray_math.cpp

for now, we have seen failures due to fast-math enabled on these 6 tests only. I would suggest to adapt tests one by one if we really see the difference in this option being enabled and disabled.

**Comment by dm-vodopyanov** [comment]
> > Do we need here as well? https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/Basic/built-ins/marray_math.cpp
> 
> for now, we have seen failures due to fast-math enabled on some specific tests. I would suggest to adapt tests one by one if we really see the difference in this option being enabled and disabled.

Sounds good to me. Just FYI, these math build-in overloads with support of marray call scalar math built-ins inside them. The test for scalar math built-ins was modified in this PR.

**Comment by KseniyaTikhomirova** [comment]
> > > Do we need here as well? https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/Basic/built-ins/marray_math.cpp
> > 
> > 
> > for now, we have seen failures due to fast-math enabled on some specific tests. I would suggest to adapt tests one by one if we really see the difference in this option being enabled and disabled.
> 
> Sounds good to me. Just FYI, these math build-in overloads with support of marray call scalar math built-ins inside them. The test for scalar math built-ins was modified in this PR.

thanks for highlighting it! I will double check to confirm if marray test could fail as well.

**Comment by KseniyaTikhomirova** [comment]
@intel/llvm-gatekeepers hello, this PR is ready for merge.

**Pull request merged**
