### PR TITLE
[SYCL][NATIVECPU] Update OCK tag

### PR DESCRIPTION
**Pull request by PietroGhg**
Updates the git tag for the oneAPI Construction Kit.

### CODE REVIEW

**Comment by PietroGhg** [comment]
Hi @intel/llvm-gatekeepers, I'm not sure what is happening with CI on this PR, none of the pre-commit checks has run on it, what do you think I should do?

**Comment by bader** [comment]
> Tried to close and re-open, but pre-commit is still not running.
> 
> The error message is:
> 
> ```
> The workflow is not valid. .github/workflows/sycl-linux-precommit.yml (Line: 36, Col: 3): Error calling workflow 'intel/llvm/.github/workflows/sycl-detect-changes.yml@09188acc625ff1171a76e283cfffbf5d90913e1a'. The workflow is requesting 'actions: read, checks: read, deployments: read, discussions: read, issues: read, packages: read, pages: read, pull-requests: read, repository-projects: read, statuses: read, security-events: read, id-token: read', but is only allowed 'actions: none, checks: none, deployments: none, discus[...]
> ```
> 
> @aelovikov-intel @bader Can you advise on how to proceed here?

@stdale-intel, does https://github.com/intel/llvm/pull/13187 fix this issue?

**Comment by stdale-intel** [comment]
@bader  yes it should address these initial set of errors coming from my permissions change

**Review by uwedolinsky — APPROVED** [review]

**Comment by PietroGhg** [comment]
Hi @intel/llvm-gatekeepers, this looks ready to be merged, thank you

**Pull request merged**
