### PR TITLE
[SYCL][PI][L0] Filter already signaled events from wait lists

### PR DESCRIPTION
**Pull request by kbsmith-intel**
This change filters already signaled events out of the wait lists
used when enqueueing level zero commands into command lists. This
fixes an issue where an already waited/signaled event can appear
in a wait list in a command batch, and before the batch is
submitted a piEventRelease call can remove the ZeEvent that is
being referred to in the batch's command list.

### CODE REVIEW

**Comment by smaslov-intel** [comment]
> This change filters already signaled events out of the wait lists
> used when enqueueing level zero commands into command lists. This
> fixes an issue where an already waited/signaled event can appear
> in a wait list in a command batch, and before the batch is
> submitted a piEventRelease call can remove the ZeEvent that is
> being referred to in the batch's command list.

You filter out the signaled L0 events at the time the commands are added to the commands list with no relation to when the command list is going to be actually submitted for execution, i.e. consumed by the L0 RT. More L0 events may become signaled just after you did the filtering and then a subsequent call to piEventRelease would equally destroy more L0 events still used in the further batched submission.

What am I missing?

**Comment by kbsmith-intel** [comment]
You are correct.  That could happen as jobs finish.  However, in order for the event to have piEventRelease called on it, I believe that piEventsWait will have had to be called on that Queue, and that will force the batch to be submitted.  It isn't that an already signalled event is problematic in the event wait list, it is that the event cannot be deleted by the piEventRelease until the command list that uses it has been submitted to level zero.

**Comment by smaslov-intel** [comment]
> However, in order for the event to have piEventRelease called on it, I believe that piEventsWait will have had to be called on that Queue

I think SYCL RT requests PI event always even if it is not going to wait for it (or it doesn't know if anyone will wait on it). In this case I expect piEventRelease may be called without piEventsWait before. @romanovvlad what do you think?

> I believe that piEventsWait will have had to be called on that Queue, and that will force the batch to be submitted.

In the case it is really so, I'd like this subtle dependency be thoroughly documented in the sources and maybe somehow enforced too.

**Comment by romanovvlad** [comment]
> 
> 
> > However, in order for the event to have piEventRelease called on it, I believe that piEventsWait will have had to be called on that Queue
> 
> I think SYCL RT requests PI event always even if it is not going to wait for it (or it doesn't know if anyone will wait on it). In this case I expect piEventRelease may be called without piEventsWait before. @romanovvlad what do you think?

I think it can if there is no synchronization in the user code, like when user submits a kernel which doesn't depend on any buffer, and doesn't call event::wait or queue::wait.

**Comment by kbsmith-intel** [comment]
If that occurred, then that event couldn't be in the wait list of any other command, could it?

**Comment by smaslov-intel** [comment]
> If that occurred, then that event couldn't be in the wait list of any other command, could it?

I think it could and would for bookkeeping purposes on the device, e.g. in-order queue.

**Comment by kbsmith-intel** [comment]
Abandoning, and will redo.

**Pull request closed without merging**
