### PR TITLE
[SYCL] Fix unresolved reference for ExeModuleHandle.

### PR DESCRIPTION
**Pull request by jyu2-git**
Signed-off-by: Yu <jennifer.yu@intel.com>

### CODE REVIEW

**Comment by bader** [comment]
On related note: `sycl/include/CL/sycl/detail/os_util.hpp` - should this header be located in include directory?
I think source directory is much better place for this utility header.

**Comment by v-klochkov** [comment]
It is not possible to simply move os_util.hpp to source directory because 
- the macro __SYCL_EXPORTED defined in it is used in SYCL headers pi.hpp and clusm.hpp
- OS_Util::getOSModuleHandle() is used in include/cl/sycl/handler.hpp + in 2 more hpp files
- OS_Util::alignedAlloc() is used in 2 different hpp files in include/cl/sycl/ directory.

**Comment by v-klochkov** [comment]
Replacing '__SYCL_EXPORTED static const OSModuleHandle ExeModuleHandle;'
with 'const OSModuleHandle ExeModuleHandle = reinterpret_cast<OSModuleHandle>(-1);'
works, but it also would require changes in os_util.cpp (remove initialization of const ExeModuleHandle),
and also changes in the LIT test program_manager/program_manager.cpp which has such a line:
  auto M = detail::OSUtil::ExeModuleHandle;

  const detail::RT::PiProgram ClProgramFirst = PM.getBuiltOpenCLProgram(M, ContextFirst);
  const detail::RT::PiProgram ClProgramSecond = PM.getBuiltOpenCLProgram(M, ContextSecond);

The only user of ExeModuleHandle const is the LIT test 'program_manager.cpp'. It is not used anywhere else (not in SYCL headers, nor in source directory).

This all together looks like a design mistake. I may be wrong though.
Wouldn't it be better to replace that global function with a static function in OS_Util ?
Something like:
os_util.hpp:
class OS_Util {
  static constexpr  getDefaultExeModuleHandle() {
    return reinterpret_cast<OSModuleHandle>(-1);
  }
  ...
};

**Comment by jyu2-git** [comment]
> Replacing '__SYCL_EXPORTED static const OSModuleHandle ExeModuleHandle;'
> with 'const OSModuleHandle ExeModuleHandle = reinterpret_cast(-1);'
> works, but it also would require changes in os_util.cpp (remove initialization of const ExeModuleHandle),
> and also changes in the LIT test program_manager/program_manager.cpp which has such a line:
> auto M = detail::OSUtil::ExeModuleHandle;
> 
> const detail::RT::PiProgram ClProgramFirst = PM.getBuiltOpenCLProgram(M, ContextFirst);
> const detail::RT::PiProgram ClProgramSecond = PM.getBuiltOpenCLProgram(M, ContextSecond);
> 
> The only user of ExeModuleHandle const is the LIT test 'program_manager.cpp'. It is not used anywhere else (not in SYCL headers, nor in source directory).
> 
> Wouldn't it be better to replace that static field with a static function in OS_Util ?
> Something like:
> os_util.hpp:
> class OS_Util {
> static constexpr getDefaultExeModuleHandle() {
> return reinterpret_cast< OSModuleHandle >(-1);
> }
> ...
> };

Yes, that it is what I am adding a new function that can be reference by other
/// Returns a ExeModuleHandle.
 static OSModuleHandle getExeModuleHandle();

**Comment by kbobrovs** [comment]
What seems not quite OK to me is we unnecessarily export a symbol (function or global). I overlooked this when I created the code, but now we have a chance to make it better. I suggest the attached fix.

**Comment by kbobrovs** [comment]
[os_util.diff.txt](https://github.com/intel/llvm/files/3433749/os_util.diff.txt)

suggested fix

**Comment by jyu2-git** [comment]
> [os_util.diff.txt](https://github.com/intel/llvm/files/3433749/os_util.diff.txt)
> 
> suggested fix

With this change, what you do for the test of sycl/test/program_manager/program_manager.cpp
Are you doing to set hard code to -1 instead?

**Comment by jyu2-git** [comment]
BTW I am having trouble to push new patch.  I will tomorrow.

**Comment by bader** [comment]
> BTW I am having trouble to push new patch. I will tomorrow.

Do you need any help with updating the PR?

**Comment by jyu2-git** [comment]
> > BTW I am having trouble to push new patch. I will tomorrow.
> 
> Do you need any help with updating the PR?

Thank you so much for the offer.  I finally git chance to work on this again.  I had Eirch help with my miss up work space.  Finally can pushed my reversion.

**Comment by jyu2-git** [comment]
> Hi Jennifer,
> Please re-base the patch, then test it on Windows.
> The current version of the patch seems obsolete.
> 
> Ravi implemented support for the function OSUtil::getOSModuleHandle() on Windows few days ago.
> 
> After you re-base, you'll see that the code in OSUtil::getOSModuleHandle() will require additional changes.
> In particular, you'll need to replace:
> return reinterpret_cast< OSModuleHandle >(0);
> with
> return 0;
> to avoid compilation error on Windows.



> Hi Jennifer,
> Please re-base the patch, then test it on Windows.
> The current version of the patch seems obsolete.
> 
> Ravi implemented support for the function OSUtil::getOSModuleHandle() on Windows few days ago.
> 
> After you re-base, you'll see that the code in OSUtil::getOSModuleHandle() will require additional changes.
> In particular, you'll need to replace:
> return reinterpret_cast< OSModuleHandle >(0);
> with
> return 0;
> to avoid compilation error on Windows.

Hi Slava,
I just  checkout //github.com/otcshare/llvm, here is what I see in there.  
static int callback(struct dl_phdr_info *Info, size_t Size, void *Data) {
  auto Base = reinterpret_cast<unsigned char *>(Info->dlpi_addr);
  auto MI = reinterpret_cast<ModuleInfo *>(Data);
  auto TestAddr = reinterpret_cast<const unsigned char *>(MI->VirtAddr);

  for (int i = 0; i < Info->dlpi_phnum; ++i) {
    unsigned char *SegStart = Base + Info->dlpi_phdr[i].p_vaddr;
    unsigned char *SegEnd = SegStart + Info->dlpi_phdr[i].p_memsz;

    // check if the tested address is within current segment
    if (TestAddr >= SegStart && TestAddr < SegEnd) {
      // ... it is - belongs to the module then
      // dlpi_addr is zero for the executable, replace it
      auto H = reinterpret_cast<void *>(Info->dlpi_addr);
      MI->Handle = H ? H : OSUtil::ExeModuleHandle;
      MI->Name = Info->dlpi_name;
      return 1; // non-zero tells to finish iteration via modules
    }
  }
  return 0;
}

**Comment by v-klochkov** [comment]
The piece of code that you showed above is for Linux.
I am talking about Windows implementation.
The code that you have in you current patch is:
  // TODO: implement this function for Windows probably by using
  // GetModuleHandleEx(GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,...)	// 
  GetModuleHandleEx(GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,...)
  OSModuleHandle OSUtil::getOSModuleHandle(const void *VirtAddr) {	OSModuleHandle 
  OSUtil::getOSModuleHandle(const void *VirtAddr) {
    throw runtime_error("OSUtil::getOSModuleHandle() is not implemented yet");	  throw 
  runtime_error("OSUtil::getOSModuleHandle() is not implemented yet");
  }
	}

That code was replaced long ago.

**Comment by jyu2-git** [comment]
> > Hi Jennifer,
> > Please re-base the patch, then test it on Windows.
> > The current version of the patch seems obsolete.
> > Ravi implemented support for the function OSUtil::getOSModuleHandle() on Windows few days ago.
> > After you re-base, you'll see that the code in OSUtil::getOSModuleHandle() will require additional changes.
> > In particular, you'll need to replace:
> > return reinterpret_cast< OSModuleHandle >(0);
> > with
> > return 0;
> > to avoid compilation error on Windows.
> 
> > Hi Jennifer,
> > Please re-base the patch, then test it on Windows.
> > The current version of the patch seems obsolete.
> > Ravi implemented support for the function OSUtil::getOSModuleHandle() on Windows few days ago.
> > After you re-base, you'll see that the code in OSUtil::getOSModuleHandle() will require additional changes.
> > In particular, you'll need to replace:
> > return reinterpret_cast< OSModuleHandle >(0);
> > with
> > return 0;
> > to avoid compilation error on Windows.
> 
> Hi Slava,
> I just checkout //github.com/otcshare/llvm, here is what I see in there.
> static int callback(struct dl_phdr_info *Info, size_t Size, void *Data) {
> auto Base = reinterpret_cast<unsigned char *>(Info->dlpi_addr);
> auto MI = reinterpret_cast<ModuleInfo *>(Data);
> auto TestAddr = reinterpret_cast<const unsigned char *>(MI->VirtAddr);
> 
> for (int i = 0; i < Info->dlpi_phnum; ++i) {
> unsigned char *SegStart = Base + Info->dlpi_phdr[i].p_vaddr;
> unsigned char *SegEnd = SegStart + Info->dlpi_phdr[i].p_memsz;
> 
> ```
> // check if the tested address is within current segment
> if (TestAddr >= SegStart && TestAddr < SegEnd) {
>   // ... it is - belongs to the module then
>   // dlpi_addr is zero for the executable, replace it
>   auto H = reinterpret_cast<void *>(Info->dlpi_addr);
>   MI->Handle = H ? H : OSUtil::ExeModuleHandle;
>   MI->Name = Info->dlpi_name;
>   return 1; // non-zero tells to finish iteration via modules
> }
> ```
> 
> }
> return 0;
> }

I see for the window need to change.

**Comment by v-klochkov** [comment]
you need to run the following commands:
git remote add intel_llvm https://github.com/intel/llvm
git fetch intel_llvm
git rebase intel_llvm/sycl
# THEN DO ADDITIONAL FIX AND TEST THE FIX ON WINDOWS
git push -f origin private/jyu2-git/unresovlesymbol

BTW, when I wrote above commands, I noticed that you created a new branch at intel/llvm, while you were supposed to create a fork, then work in your fork.

**Comment by jyu2-git** [comment]
Create new one using fork

**Pull request closed without merging**
