### PR TITLE
[SYCL][DeviceSanitizer] Add tests for sycl-post-link to cover device global

### PR DESCRIPTION
**Pull request by zhaomaosu**
This is a follow up PR for #12753

### CODE REVIEW

**Comment by maksimsab** [comment]
Please, add test's description.

**Comment by zhaomaosu** [comment]
> Also, check out [BKMs](https://llvm.org/docs/TestingGuide.html#best-practices-for-regression-tests) on regression tests. Especially,
> 
> * `Minimize tests by removing unnecessary instructions, metadata, attributes, etc. Tools like llvm-reduce can help automate this.`

Thanks for the suggestions. Done.

**Comment by zhaomaosu** [comment]
Hi @maksimsab, they are sycl-post-link tests. Actually, I didn't register the new added Sanitizer pass in opt pipeline. So, I cannot run it with opt. And the new added pass will be removed once UR API urProgramGetGlobalVariablePointer is implemented, I think it will be done soon. So, I don't want to make any heavy changes.
The new added tests are enough to cover the new added pass.

**Comment by maksimsab** [comment]
> the new added pass will be removed once UR API urProgramGetGlobalVariablePointer is implemented

Ok then.

**Comment by maksimsab** [comment]
@AlexeySachkov Can we merge it, please?

**Pull request closed without merging**
