### PR TITLE
[SYCL] Make reduction compatible with MSVC host compiler

### PR DESCRIPTION
**Pull request by aelovikov-intel**
This PR addresses two problems:

1) MSVC has a bug in handling this in default mode (fine in /permissive-
though). The issue affected compilation using MSVC as a host compiler. 
Simplified description of the problem:

```
  template <class Derived>
  class Base {
      using T = int;
  };

  template <class T>
  class A : public Base<A<T>> {
      // That's what we had in the codebase prior to this change. MSVC
      // complains here by default, accepts in "/permissive-".
      using T2 = T;
  };

  class Base2 {
      using T = int;
  };

  template <class T>
  class A2 : public Base2 {
      using T2 = T; // That's where the error has to be emitted.
  };

  int main() {
      A<int> a;
      A2<int> a2;
      return 0;
  }
```

2) constexpr variables are part of lambda capture and result in
incompatibilities between clang device and MSVC host. As such, don't use
those when they're used inside kernel lambdas. Instead, make them
regular variables and pay the price of increased number of arguments to
the kernel.

### CODE REVIEW

**Comment by aelovikov-intel** [comment]
OCL's

```
Failed Tests (1):
  SYCL :: XPTI/kernel/content.cpp
```

is known and unrelated.

**Comment by v-klochkov** [comment]
for (2) mentioned in the description: What do you mean by "incompatibilities between clang device and MSVC host"?
The tests (including reduction tests) work/pass on Windows now, right? If Yes, then what does this PR fix? Can you add a LIT test that fails without and passes with PR?

As I read that description tells me that constexpr must never be used, but that seems like a pretty severe restriction. Users can use constexpr variables in kernel/lambda.

Wouldn't it be useful to ask FE experts to take a look at this problem too?

**Comment by v-klochkov** [comment]
> class A : public Base<A<T>>

Can you please give a reference (file & line number) that has such a crazy construction?

**Comment by erichkeane** [comment]
> for (2) mentioned in the description: What do you mean by "incompatibilities between clang device and MSVC host"? The tests (including reduction tests) work/pass on Windows now, right? If Yes, then what does this PR fix? Can you add a LIT test that fails without and passes with PR?
> 
> As I read that description tells me that constexpr must never be used, but that seems like a pretty severe restriction. Users can use constexpr variables in kernel/lambda.
> 
> Wouldn't it be useful to ask FE experts (e.g. @erichkeane ) to take a look at this problem too?

Unfortunately this is a type of implementation divergence that would be an ABI break on either side, and the standard permits both (but, I'll say, clangs implementation is more DEFENSIBLE by standard).

**Comment by aelovikov-intel** [comment]
> @aelovikov-intel - In this case, the XPTI/kernel/content.cpp failure is likely related to this as the removal of the `constexpr` means the lambdas are going to capture more variables, which is part of what that test checks.

You're right. Created https://github.com/intel/llvm-test-suite/pull/1164, let's wait for its pre-commit to finish.

**Review by steffenlarsen — APPROVED** [review]
LGTM!

**Comment by v-klochkov** [comment]
I am Ok with the changes. Thank you.
I still think having at least 1 LIT test (failing without this PR and passing with it) is needed, but consider this is non-blocking comment in this case, also relying on @steffenlarsen approval here.

**Pull request merged**
