### PR TITLE
[SYCL][NFCI] Finalize switch to SPV_KHR_cooperative_matrix

### PR DESCRIPTION
**Pull request by MrSidims**

### CODE REVIEW

**Comment by MrSidims** [comment]
Tested locally on linux both CPU and GPU - the patch shouldn't cause any regressions (unless there is a difference between driver versions used in pre-commit here in CI and drivers used locally (setup by scripts)).
Hasn't yet tested on windows - having troubles finding DG2 machine.

**Review by YuriPlyakhin — APPROVED** [review]
Code changes itself LGTM.

@MrSidims , in addition to stability, could you please also verify performance just in case to make sure no performance regressions are introduced?

**Review by elizabethandrews — APPROVED** [review]

**Review by dkhaldi — CHANGES_REQUESTED** [review]
Let's investigate failures on Windows DG2 before merging this

**Comment by MrSidims** [comment]
@dkhaldi on windows DG2 only these 2 tests are failing:
Failed Tests (2):
  SYCL :: Matrix/SPVCooperativeMatrix/joint_matrix_bf16_fill_k_cache_SLM.cpp
  SYCL :: Matrix/joint_matrix_bf16_fill_k_cache_SLM.cpp


But there are indeed regressions. joint_matrix_out_bounds.cpp was added only for JointMatrices, with the switch it's actually failing. The reason is that __spirv_CooperativeMatrixLoadCheckedINTEL (and Store) are not handled by IGC for Cooperative Matrices at all. This behavior doesn't follow SPIR-V specification as it defines OpCooperativeMatrixLoadCheckedINTEL be used only for OpTypeCooperativeMatrixKHR. Support of TypeJointMatrixINTEL was left in the translator only as an exception for the switch. Prefetch seem to also not handled by IGC when used with TypeCooperativeMatrixKHR. We have to postpone the switch to cooperative matrices as well as promoting the sycl extension from experimental to supported. Note, only new functionality doesn't work. Old functionality works as expected.

**Comment by MrSidims** [comment]
Closing the PR as we can't merge it

**Comment by MrSidims** [comment]
@dkhaldi @YuriPlyakhin apparently I had a problem with the driver. On agama driver performance tests are passing (with OOB loads/stores). No performance regressions observed.

**Comment by MrSidims** [comment]
@dkhaldi @intel/llvm-reviewers-runtime please take a look

**Review by dkhaldi — APPROVED** [review]
LGTM! Let's embrace for impact :)

**Review by dm-vodopyanov — APPROVED** [review]

**Comment by sarnex** [comment]
Cool, thx!

**Pull request merged**
