### PR TITLE
[SYCL] Change negative and static_cast logical for half

### PR DESCRIPTION
**Pull request by AidanBeltonS**
This PR resolves ambiguous operators on windows caused by https://github.com/intel/llvm/commit/ad47114ad8500c78046161d492ac13a8e3e610eb. 
The issue is caused by MSVC not having the same specialisation ranking as linux, and additional operators being considered of similar specialisation through implicit conversions. 
The fix adds logical operators for the host half type, and explicitly converts types for the general half to prevent implicit conversions.

This is a fix for: #6142

### CODE REVIEW

**Comment by AidanBeltonS** [comment]
@steffenlarsen @pvchupin

**Comment by steffenlarsen** [comment]
https://github.com/intel/llvm/pull/6150 takes care of the last two probem classes.

**Comment by steffenlarsen** [comment]
@AidanBeltonS - Based on local testing It seems like we can work around the ABI break by keeping both the `operator-` overload and the new friend variant. In that case you'll just have to add 

```
??0half_v2@host_half_impl@detail@sycl@cl@@QEAA@AEBN@Z
```

to sycl\test\abi\sycl_symbols_windows.dump and it should be passing.

**Comment by AidanBeltonS** [comment]
> @AidanBeltonS - Based on local testing It seems like we can work around the ABI break by keeping both the `operator-` overload and the new friend variant. In that case you'll just have to add
> 
> ```
> ??0half_v2@host_half_impl@detail@sycl@cl@@QEAA@AEBN@Z
> ```
> 
> to sycl\test\abi\sycl_symbols_windows.dump and it should be passing.
> 
> Assuming this is the best available work-around, the old `operator-` should have a comment saying that it should be removed when ABI breaking is allowed.

Thanks, I have tested out the change as well and it works locally. I have updated the PR to keep the old operator

**Review by steffenlarsen — APPROVED** [review]
LGTM!

**Comment by pvchupin** [comment]
@steffenlarsen, @AidanBeltonS, original change was reverted in upstream at e0fcdf5496ca686c8cebb63b63af86e666b42ab3 and it seems it's not going to return back any time soon, or may return under some other flag...

What do you think makes sense here? Should we abandon this? Or you believe it's generally good to land?

**Comment by AidanBeltonS** [comment]
> @steffenlarsen, @AidanBeltonS, original change was reverted in upstream at [e0fcdf5](https://github.com/intel/llvm/commit/e0fcdf5496ca686c8cebb63b63af86e666b42ab3) and it seems it's not going to return back any time soon, or may return under some other flag...
> 
> What do you think makes sense here? Should we abandon this? Or you believe it's generally good to land?

I think it makes sense to close this PR. If the upstream change comes back then it can be reopened to resolve the problem.

**Pull request closed without merging**
