### PR TITLE
[SYCL][XPTI] Fix dangling pointer warnings

### PR DESCRIPTION
**Pull request by frasercrmck**
Building with GCC 13.2 was showing thousands of lines of warnings due to the centrality of this header, with the compiler (rightly?) detecting that ArgsDataPtr may be dangling.

There shouldn't be any performance impact of this change as the unique_ptr should be just as cheap to initialize with nullptr as a regular pointer on the fast path.

### CODE REVIEW

**Comment by frasercrmck** [comment]
Ping @intel/llvm-reviewers-runtime

**Review by uditagarwal97 — APPROVED** [review]
LGTM!

**Comment by frasercrmck** [comment]
@intel/llvm-gatekeepers I think this is good to merge, thanks.

**Comment by steffenlarsen** [comment]
Windows unittests failed in post-commit CI, but passed again in a following commit. It seems to be a flaky issue and unlike to be directly related. Issue tracker has been created: https://github.com/intel/llvm/issues/13457

**Pull request merged**
