### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW35)

### PR DESCRIPTION
**Pull request by vmaksimo**
LLVM: llvm/llvm-project@955b91c19c00
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@e9671a5

### CODE REVIEW

**Comment by Fznamznon** [comment]
In case you are seeing errors like LLVM ERROR: Unsupported vector type with the size of: 1, please try to include https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1172 commit.

**Comment by vmaksimo** [comment]
Hi @steffenlarsen! could you please advise on how to properly resolve lit failures on CUDA (global offset tests)? I suppose I incorrectly fixed build failure by this change https://github.com/intel/llvm/pull/4388/commits/483b18711798db5e3521f9e704146a3192bd2206, but I referred to the LLORG patch changes

**Review by vladimirlaz — APPROVED** [review]

**Review by AlexeySotkin — APPROVED** [review]

**Comment by bb-sycl** [comment]
Tue Aug 31 14:00:37 UTC 2021 --- Merge failed with error: PR is not clean for merge. Please examine approval status or check status before merge.

**Pull request merged**
