### PR TITLE
[SYCL] BE is expecting FP accuracy values without the suffix "f".

### PR DESCRIPTION
**Pull request by zahiraam**
Currently we are passing values of the FP accuracy with an "f" suffix. The backend is expecting those values without the suffix. This patch removes them.

### CODE REVIEW

**Review by premanandrao — APPROVED** [review]
FE test change looks good to me.

**Review by AlexeySachkov — APPROVED** [review]
`llvm/` changes LGTM

**Comment by zahiraam** [comment]
https://github.com/orgs/intel/teams/llvm-gatekeepers can you consider merging this please? Thanks.

**Review by asudarsa — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
