### PR TITLE
Add three missing llvm-spirv commits from Khronos 

### PR DESCRIPTION
**Pull request by sarnex**
The below three commits are missing from intel/llvm llvm-spirv and it's causing differences in internal testing:
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/352ea14d320da10fcf72c19b46c50020e657c89a
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/85815e725ce5bdc970b812b4bbff73d4b2a44046
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/aded5afb04f02b1b057db96cd9a8a5e9d1ff47fc

I also had to add a customization to skip interface global variables.

Signed-off-by: Sarnie, Nick <nick.sarnie@intel.com>

### CODE REVIEW

**Comment by MrSidims** [comment]
Thanks for doing this!
Unfortunately I don't think we ready for them. Here are the reasons:
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/352ea14d320da10fcf72c19b46c50020e657c89a this patch lists GVs in the Interfaces of EntryPoint. Unfortunately there was a bug in IGC, which doesn't handle Interfaces at all. AFAIK the bug is now fixed, but these drivers are not yet in CI.

https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/85815e725ce5bdc970b812b4bbff73d4b2a44046 this patch is addressing SPIR-V 1.4 requirement and we haven't yet switched to it in this repo. There is PR for that https://github.com/intel/llvm/pull/7493 but fresh-new pre-commit runs are showing some tests with very fishy error message failing. I haven't yet investigated them, but it's on my list. Though, probably we still can merge this patch. 

There are actually more 'customizations' in intel/llvm, they are being tracked here: https://github.com/intel/llvm/issues/7592 feel free to update the list if you something that was not mentioned.

**Comment by sarnex** [comment]
@MrSidims You are realy good at sniping my draft PRs

Yeah after looking at these CI failures I came to the same conclusion, I'll close this for now

**Comment by MrSidims** [comment]
If you don't mind, I'd re-open it :) 

The CI failures I see are not related to GPU driver lacking SPIR-V 1.4 support. Not sure about this very PR though. So it's worth a stand-alone investigation

**Comment by sarnex** [comment]
@bader Any idea what's going on with the OCL x64 failure? I merged sycl HEAD into my branch.

```
Starting download for sycl_linux_default
Error: Unable to find an artifact with the name: sycl_linux_default
Run actions/upload-artifact@v1
Error: Path does not exist /localdisk2/github/_work/llvm/llvm/build/results_ocl_x64_default.json
Error: Exit code 1 returned from process: file name '/localdisk2/github/bin.2.301.1/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'.
```

**Comment by sarnex** [comment]
@MrSidims Okay it seems like the 5 failures on OCL CPU are all caused by an old driver. If I use a newer driver locally it works fine.

I have three options here:
1) Disable these 5 tests on OCL CPU until new driver
2) Try to upgrade the driver.
3) Hold off on this change until new driver

What do you recommend? 2) could turn into a nightmare :)

**Comment by MrSidims** [comment]
@cdai2 hi, since CPU runtime is now public, may I ask you whether we expect to have it used in intel/llvm for testing?

**Comment by MrSidims** [comment]
@sarnex 

>> Disable these 5 tests on OCL CPU until new driver

I see
`llvm-foreach: Segmentation fault (core dumped)`
so I would vote for 'no'. Do you know, what exactly is missing in the currently used CPU driver?

**Comment by sarnex** [comment]
> Do you know, what exactly is missing in the currently used CPU driver?

No idea, but I can investigate. Sorry what do you mean by 'vote for no'? Do you support one of the 1-3 options?

**Comment by MrSidims** [comment]
> @MrSidims
> 
> > Do you know, what exactly is missing in the currently used CPU driver?
> 
> No idea, but I can investigate. Sorry what do you mean by 'vote for no'? Do you support one of the 1-3 options?

Sorry :) I would vote for not disabling the tests, until we know, what causes `segfault`.

**Comment by sarnex** [comment]
@MrSidims Okay let me try to look into it and report back

**Comment by sarnex** [comment]
@MrSidims Did you decide on which approach to take here? Thanks

**Comment by asudarsa** [comment]
Hi @sarnex 

Thanks for looking at this. Just a quick comment. Will it make it easier to test/debug if we submit the three PRs separately?

**Comment by sarnex** [comment]
@asudarsa Unfortunately we can't, they are interdependent. We can't merge this anyway because of the OCL CPU issue.

**Comment by sarnex** [comment]
finally new ocl cpu driver, is there hope? let's find out on tonight's episode of i doubt it

**Pull request closed without merging**
