### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW08)

### PR DESCRIPTION
**Pull request by KornevNikita**
LLVM: llvm/llvm-project@890146b
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@4af277c

### CODE REVIEW

**Comment by KornevNikita** [comment]
@bader okay, `SYCL :: GroupAlgorithm/barrier.cpp` also failed here on [Linux / [AWS] CUDA LLVM Test Suite](https://github.com/intel/llvm/actions/runs/4233241780/jobs/7359487999#logs). There are new failures in other workflows:
[Linux / HIP AMDGPU LLVM Test Suite](https://github.com/intel/llvm/actions/runs/4233241780/jobs/7359487893#logs):
Timed Out Tests (3):
  SYCL :: GroupAlgorithm/SYCL2020/reduce_over_group_size.cpp
  SYCL :: HierPar/hier_par_wgscope_O0.cpp
  SYCL :: Regression/unoptimized_stream.cpp
 [Linux / OCL GEN9 LLVM Test Suite](https://github.com/intel/llvm/actions/runs/4233241780/jobs/7359487505#logs):
 Timed Out Tests (1):
  SYCL :: Regression/commandlist/gpu.cpp
  I guess we can fix OCL GEN9, but the other ones will be more difficult. What is the best way here?

**Comment by bader** [comment]
Interesting... it seems that these changes increase execution time of the tests, so that some of them are hitting time limits.
Any ideas what might be the root cause?

@AerialMantis, could your team help with investigating regressions on CUDA and AMD platforms, please?

**Comment by KornevNikita** [comment]
https://github.com/intel/llvm/actions/runs/4233241780/jobs/7378838575 OCL GEN9 passed after re-run. Not sure if it was fixed or flaky as I'm getting assertion trying to run this test locally.

**Comment by JackAKirk** [comment]
> Interesting... it seems that these changes increase execution time of the tests, so that some of them are hitting time limits. Any ideas what might be the root cause?
> 
> @AerialMantis, could your team help with investigating regressions on CUDA and AMD platforms, please?

For the CUDA barrier.cpp failure I think that this patch may fix it: https://github.com/intel/llvm-test-suite/compare/intel...JackAKirk:update-barrier-smversion?expand=1

If the above fixes it then the pulldown is just a coincidence for the cuda failure. I noticed that the CI is running on an sm_86 machine, so I think that the JIT could be failing because it was compiled for sm_80, this would make sense with the image error that is being thrown. I cannot verify this because I do not have an sm_86.

**Comment by bader** [comment]
> > Interesting... it seems that these changes increase execution time of the tests, so that some of them are hitting time limits. Any ideas what might be the root cause?
> > @AerialMantis, could your team help with investigating regressions on CUDA and AMD platforms, please?
> 
> For the CUDA barrier.cpp failure I think that this patch may fix it: https://github.com/intel/llvm-test-suite/compare/intel...JackAKirk:update-barrier-smversion?expand=1
> 
> If the above fixes it then the pulldown is just a coincidence for the cuda failure. I noticed that the CI is running on an sm_86 machine, so I think that the JIT could be failing because it was compiled for sm_80, this would make sense with the image error that is being thrown. I cannot verify this because I do not have an sm_86.

We have a few other tests compiled for sm_80 or even older versions and they work fine.
https://github.com/search?q=repo%3Aintel%2Fllvm-test-suite%20--cuda-gpu-arch%3D&type=code
Is this test a special case where we must match sm version exactly?

**Comment by JackAKirk** [comment]
> > > Interesting... it seems that these changes increase execution time of the tests, so that some of them are hitting time limits. Any ideas what might be the root cause?
> > > @AerialMantis, could your team help with investigating regressions on CUDA and AMD platforms, please?
> > 
> > 
> > For the CUDA barrier.cpp failure I think that this patch may fix it: https://github.com/intel/llvm-test-suite/compare/intel...JackAKirk:update-barrier-smversion?expand=1
> > If the above fixes it then the pulldown is just a coincidence for the cuda failure. I noticed that the CI is running on an sm_86 machine, so I think that the JIT could be failing because it was compiled for sm_80, this would make sense with the image error that is being thrown. I cannot verify this because I do not have an sm_86.
> 
> We have a few other tests compiled for sm_80 or even older versions and they work fine. https://github.com/search?q=repo%3Aintel%2Fllvm-test-suite%20--cuda-gpu-arch%3D&type=code Is this test a special case where we must match sm version exactly?

I don't know the answer to this question but the fact that this CI run in another PR run is passing the barrier.cpp test and also using the same sm_86 device makes me thing that the patch using sm_86 won't fix the failure and that it probably is something upstream. The error it throws however suggests that it is something device architecture specific:

`device kernel image is invalid`

I've run barrier.cpp fine using this branch on sm_61 too.

**Comment by JackAKirk** [comment]
Someone in the team has access to sm_86 and is now trying to reproduced the barrier.cpp cuda failure.

**Comment by KornevNikita** [comment]
@JackAKirk Hello, any updates?

**Comment by JackAKirk** [comment]
> @JackAKirk Hello, any updates?

I believe that the barrier.cpp failure originates with this commit https://github.com/KornevNikita/llvm/commit/0660397e68096a64279b19f913e7de2c283e524f , and following merge conflict resolutions/fixes. Certainly it occurs at this commit: https://github.com/KornevNikita/llvm/commit/cab0b0b5055e99d5659daf371baa0dc7d66b7c63
and does not occur before https://github.com/KornevNikita/llvm/commit/0660397e68096a64279b19f913e7de2c283e524f.
 Although I still do not yet completely understand the problem. There does not appear to be a corresponding problem with clang cuda.

There is nothing specific to barrier.cpp or even other sm_80 specific builtins. In many cases sm_80 specific builtins compile and execute correctly. I have seen the same error thrown from tests containing no sm_80 specific features when compiled for sm_80, but when compiled for sm_75 will execute correctly, even when the ptx generated from compiling with sm_80 matches the ptx when compiling for sm_75 exactly. 

AMD -O0 failures are also being investigated.

**Comment by bader** [comment]
@JackAKirk, I'd like to merge this PR as soon as possible to not delay synchronization with the `main` branch. Do you have any concerns about disabling the tests failing pre-commit checks to unblock the merge? The idea is to resolve them in the `sycl` branch after we merge community commits rather than trying to resolve them in the PR branch (which blocks the pulldown).

There seems to be a limited impact on SYCL functionality.
We need to pull WW09 commits, so I was hoping we can move forward with pulldowns by disabling a few lit tests. What do you think?
@AerialMantis, FYI.

**Comment by JackAKirk** [comment]
> @JackAKirk, I'd like to merge this PR as soon as possible to not delay synchronization with the `main` branch. Do you have any concerns about disabling the tests failing pre-commit checks to unblock the merge? The idea is to resolve them in the `sycl` branch after we merge community commits rather than trying to resolve them in the PR branch (which blocks the pulldown).
> 
> There seems to be a limited impact on SYCL functionality. We need to pull WW09 commits, so I was hoping we can move forward with pulldowns by disabling a few lit tests. What do you think? @AerialMantis, FYI.

Basically I think the effect on the NVPTX backend is that targetting sm_80 or higher using arch specific flags is largely broken.
So there would be many more cuda test failures if they were compiled using architecture specific flags, although interestingly only sm_80 and higher appears to be affected. I think this is a general problem with the wrong device image being used in the driver that appears to have occurred after all the upstream changes to Cuda/NVPTX toolchain were merged.

**Comment by JackAKirk** [comment]
@npmiller spotted that there is an extra `-c` in ptxas commands and can be fixed by updating this line: https://github.com/KornevNikita/llvm/blob/c56da358fefaca54f6251e29a1331eea332e21ac/clang/lib/Driver/ToolChains/Cuda.cpp#L475

to

```
else if (JA.isOffloading(Action::OFK_Cuda) || JA.isOffloading(Action::OFK_SYCL))
```

this prevents the extra `-c` and fixes the cuda problems.

**Comment by KornevNikita** [comment]
@JackAKirk good, let me try.

**Comment by npmiller** [comment]
@bader @KornevNikita I spoke with @AerialMantis if the patch fixing the CUDA tests works we're happy to disable the remaining failing AMD tests and go ahead with the merge.

The AMD failures are fairly limited as they only happen at `-O0` so we can fix them in the `sycl` branch after the merge.

**Comment by bader** [comment]
> > @JackAKirk, I'd like to merge this PR as soon as possible to not delay synchronization with the `main` branch. Do you have any concerns about disabling the tests failing pre-commit checks to unblock the merge? The idea is to resolve them in the `sycl` branch after we merge community commits rather than trying to resolve them in the PR branch (which blocks the pulldown).
> > There seems to be a limited impact on SYCL functionality. We need to pull WW09 commits, so I was hoping we can move forward with pulldowns by disabling a few lit tests. What do you think? @AerialMantis, FYI.
> 
> Basically I think the effect on the NVPTX backend is that targetting a specific architecture via e.g.
> 
> ```
> -Xsycl-target-backend --cuda-gpu-arch=sm_61
> ```
> 
> using arch specific flags is largely broken.
> 
> So there would be many more cuda test failures if they were compiled using architecture specific flags. I think this is a general problem with the wrong device image being used in the driver that appears to have occurred after all the upstream changes to Cuda/NVPTX toolchain were merged.

We have ~18 tests in llvm-test-suite using arch specific flags. Any ideas why these tests pass? It seems like just using arch specific flags is not enough to break the test.

**Comment by JackAKirk** [comment]
> > > @JackAKirk, I'd like to merge this PR as soon as possible to not delay synchronization with the `main` branch. Do you have any concerns about disabling the tests failing pre-commit checks to unblock the merge? The idea is to resolve them in the `sycl` branch after we merge community commits rather than trying to resolve them in the PR branch (which blocks the pulldown).
> > > There seems to be a limited impact on SYCL functionality. We need to pull WW09 commits, so I was hoping we can move forward with pulldowns by disabling a few lit tests. What do you think? @AerialMantis, FYI.
> > 
> > 
> > Basically I think the effect on the NVPTX backend is that targetting a specific architecture via e.g.
> > ```
> > -Xsycl-target-backend --cuda-gpu-arch=sm_61
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > using arch specific flags is largely broken.
> > So there would be many more cuda test failures if they were compiled using architecture specific flags. I think this is a general problem with the wrong device image being used in the driver that appears to have occurred after all the upstream changes to Cuda/NVPTX toolchain were merged.
> 
> We have ~18 tests in llvm-test-suite using arch specific flags. Any ideas why these tests pass? It seems like just using arch specific flags is not enough to break the test.

For some reason the failure doesn't always occur. I don't know why. The cause of the failures has now been fixed by the above mentioned patch.

**Comment by npmiller** [comment]
> We have ~18 tests in llvm-test-suite using arch specific flags. Any ideas why these tests pass? It seems like just using arch specific flags is not enough to break the test.

I believe what's going on for most of these, is that you need the cuda arch flag that matches the specific GPU being used for the issue to show up.

For CUDA we generate fat binaries that contain generic PTX and device specific SASS, the flag only controls what device the SASS is generated for, but the PTX is always there. And at runtime if the version of the SASS matches the version of the GPU being used, the CUDA runtime it will use that, but if the GPU has a more recent version than the SASS, the CUDA runtime will JIT compile the PTX for that specific version. Note that the PTX is forward compatible, not backward compatible, a `sm_60` fat binary can be JIT compiled for `sm_80`, but not the other way around.

So with this `-c` issue, the SASS in the fat binary is incorrect (not linked), but if your GPU is a higher version than the SASS, the CUDA driver will just ignore the incorrect SASS and JIT compile the PTX for the actual GPU version avoiding the issue altogether.

I was able to confirm this locally by using the CUDA environment variable `CUDA_FORCE_PTX_JIT=1`, in that cases there is no issues even with the arch flag set to the correct architecture, simply because the SASS is never used.

That explains the reduction tests for example that use `sm_60`, but it still leaves us with 8 tests that use `sm_80`, the failing barrier test, some joint matrix tests and some bfloat16 tests, and I'm not too sure yet why these other tests using `sm_80` aren't failing.

**Comment by KornevNikita** [comment]
Waiting for https://github.com/intel/llvm/actions/runs/4294083502/jobs/7491959648 to see if it fixes the issue.

**Comment by KornevNikita** [comment]
It looks like there is a big queue for `[AWS] CUDA LLVM Test Suite`, so the workflow failed due to long wait. I'll try to run it one more time.

**Comment by bader** [comment]
@KornevNikita, let's ignore CUDA check - it's broken.
Please, disable tests failing on AMDGPU and file a bug report to fix them.
We will merge once all failing tests are disabled/fixed.

**Comment by KornevNikita** [comment]
@bader okay, waiting for https://github.com/intel/llvm-test-suite/pull/1633 to be merged, then I'lll re-run this one.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Wed 08 Mar 2023 04:54:26 AM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Wed 08 Mar 2023 04:58:32 AM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
