### PR TITLE
[SYCL][CUDA] Add clang builtin for __nvvm_reflect 

### PR DESCRIPTION
**Pull request by hdelan**
This adds a clang builtin `__nvvm_reflect`for the CUDA backend, allowing `__nvvm_reflect` to be called directly from SYCL or openCL kernel code. 

`__nvvm_reflect("__CUDA_ARCH")` will be replaced by the arch that you compile for at compile time. (sm_50 will give replace call to `__nvvm_reflect with 500`, for instance).

Also "__CUDA_PREC_SQRT" and "__CUDA_FTZ" can be used which will return 0 or 1, dependent on the values of the module flags `nvvm-reflect-prec-sqrt` and `nvvm-reflect-ftz`, respectively. 

It also removes the workaround in `libclc/ptx-nvidiacl/libspirv/reflect.ll`

Let me know if you think I should document this somewhere.

### CODE REVIEW

**Comment by bader** [comment]
> This adds a clang builtin `__nvvm_reflect` for the CUDA backend, allowing `__nvvm_reflect` to be called directly from SYCL or openCL kernel code.

Please, create a review request for `__nvvm_reflect` clang built-in in https://reviews.llvm.org/. This can be committed directly to llvm.org repository.

**Comment by hdelan** [comment]
Sure. Posted here https://reviews.llvm.org/D137154. I will wait until I hear feedback. If it looks like it is going to be merged I will modify this PR so that only libclc changes and CodeGenSYCL test is included.

**Comment by hdelan** [comment]
Hi @bader We have got some pretty strong pushback upstream. Do we think that it's worth pursuing this? The main reasons for the change were discussed in the upstream PR, most notably the inability to use `__nvvm_reflect` in openCL code, leading to the workaround in `reflect.ll`. What are your thoughts?

**Comment by asudarsa** [comment]
Hi @hdelan 

Can you please let me know if this is an active PR and if it needs my review.
Sorry for delay.

Thanks

**Comment by hdelan** [comment]
> Hi @hdelan
> 
> Can you please let me know if this is an active PR and if it needs my review. Sorry for delay.
> 
> Thanks

Hi @asudarsa I have a patch that has just been merged upstream relating to this so I will close this and open a new PR as soon as the pulldown is complete.

**Comment by hdelan** [comment]
Here https://reviews.llvm.org/D139213

**Pull request closed without merging**
