### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW35)

### PR DESCRIPTION
**Pull request by sys-ce-bb**
LLVM: llvm/llvm-project@ac2d265
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@8701279

### CODE REVIEW

**Comment by jsji** [comment]
I think this is ready to be merged. Two XFAILS:
1. [b700180](https://github.com/intel/llvm/pull/11031/commits/b700180ed491dfe91567d42988c7961070b67782) This is known failures due to vtable changes needed. Something @jyu2-git has been working on.
2. [5931d0d](https://github.com/intel/llvm/pull/11031/commits/5931d0d41a7501237f136525784b54cd10929a9f) ESIMD failures, @sarnex will have a look , tracking at https://github.com/intel/llvm/issues/11036.

**Comment by jsji** [comment]
@intel/llvm-gatekeepers @bader OK to merge? Thanks!

**Comment by bb-sycl** [comment]
Fri 01 Sep 2023 03:46:12 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Fri 01 Sep 2023 03:50:18 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
