### PR TITLE
[SYCL][Driver] Change default SYCL version to be 2020

### PR DESCRIPTION
**Pull request by cperkinsintel**
Support _for_  `sycl-std=2020` was added in an earlier PR( https://github.com/intel/llvm/pull/2259 ) but the default SYCL version was left alone.  Now we are changing the FE so that if not otherwise specified `sycl-std=2020` is elected as the default.

Signed-off-by: Chris Perkins <chris.perkins@intel.com>

### CODE REVIEW

**Review by AGindinson — APPROVED** [review]

**Comment by keryell** [comment]
Great achievement! It looks like this is the first SYCL implementation aiming at the SYCL 2020 specification.

**Comment by bader** [comment]
@cperkinsintel, this change breaks SYCL-1.2.1 conformance test suite.
I've created a PR to fix the problem - https://github.com/KhronosGroup/SYCL-CTS/pull/57.
Could you check if "fixed" `test_header` passes with your branch, please?
If so, I'd like to commit the CTS PR first to avoid regressions.

**Comment by cperkinsintel** [comment]
@bader   - Done. It passes.


I have my build with SYCL 2020 as the default, and your latest in the conformance tests, and made and ran the test_header test.

It outputs CL_SYCL_LANGUAGE_VERSION = 121 as part of the test, which looks correct.

```
S$ python runtests.py -b build/bin/test_header -d opencl_cpu -p intel
--- header_test
  . CL_SYCL_LANGUAGE_VERSION = 121
  - pass
 
 1 tests ran in total
  - passed : 1
  - failed : 0
  - skipped: 0
  = 100% pass rate
chrisper@scsel-cfl-10:/iusers/cperkins/sycl_workspace/SYCL-CTS$ git log
commit 856f9a2a63bedc2c72c4ffb2ae745b0657d7aa2d (HEAD -> SYCL-1.2.1/master, origin/SYCL-1.2.1/master, origin/HEAD)
Author: Alexey Bader <alexey.bader@intel.com>
Date:   Thu Sep 3 17:58:38 2020 +0300

    Specify SYCL standard version for Intel implementation (#57)
    
    Intel's implementation is about to switch default SYCL version to
    SYCL-2020 and it will be a breaking change for test_header, which checks
    if `CL_SYCL_LANGUAGE_VERSION` macro is defined by the compiler.
```

**Pull request merged**
