### PR TITLE
[SYCL] Update windows driver version

### PR DESCRIPTION
**Pull request by NikitaRudenkoIntel**

### CODE REVIEW

**Comment by bader** [comment]
@tfzhu, I guess before changing the configuration file, the driver must be updated on machines manually. Am I right?

**Comment by NikitaRudenkoIntel** [comment]
This update is required for https://github.com/intel/llvm/pull/3607

**Comment by bader** [comment]
> This update is required for #3607

According to my understanding updating Windows driver in buildbot/dependency.conf doesn't impact product validation by CI. This works only for Linux drivers, where CI automatically uses the driver version specified in this file. Windows version is specified for documentation purpose, the driver is installed manually. @tfzhu, am I right?

**Comment by yinyangsx** [comment]
> > This update is required for #3607
> 
> According to my understanding updating Windows driver in buildbot/dependency.conf doesn't impact product validation by CI. This works only for Linux drivers, where CI automatically uses the driver version specified in this file. Windows version is specified for documentation purpose, the driver is installed manually. @tfzhu, am I right?

Right. I have the new driver on #4232, the result is ok. I think we can merge this change. Let me know once this change is merged.
Here is the test using 100.9684,
http://ci.llvm.intel.com:8010/#builders/18/builds/16988

**Review by bader — APPROVED** [review]

**Pull request merged**
