### PR TITLE
[SYCL][CUDA][HIP AMD] Correct cuda/hip spirv libclc .bc and module triple.

### PR DESCRIPTION
**Pull request by JackAKirk**
People have been getting confused, see e.g. https://github.com/intel/llvm/issues/6922, due to warnings of mismatching triples in the HIP AMD and CUDA backends during linking. This warning occurs because the bitcode compiled from spirv libclc does not use the same triples as those passed to clang to compile SYCL in the CUDA, "nvptx64-nvidia-cuda", and HIP "amdgcn-amd-amdhsa" backends. 
However these modules are created only to be linked with clang compiled SYCL code and the modules are always compatible.
Therefore in this patch we update the triples of the final remangled spirv modules and update the names of the final remangled .bcs that are built/installed/linked with the clang built .bcs.

Fixes https://github.com/intel/llvm/issues/6922

### CODE REVIEW

**Comment by JackAKirk** [comment]
By the way, we would like to have this cherry-picked for the 2023.0 release.

**Review by mdtoguchi — APPROVED** [review]
OK for driver

**Review by romanovvlad — APPROVED** [review]

**Comment by JackAKirk** [comment]
Thanks for reviewing. I've put it as draft since I may refactor it a bit before merging. Will get back to it shortly.

**Comment by JackAKirk** [comment]
> Thanks for reviewing. I've put it as draft since I may refactor it a bit before merging. Will get back to it shortly.

cc @AerialMantis @romanovvlad @steffenlarsen @pvchupin 

I've moved it from draft so it can be merged for the 2023.0 cherry pick. We were thinking of refactoring to avoid retyping the lib name everywhere but since it now needs to be in ASAP for the cherry pick we will leave it as it is for this PR. Correcting the lib names and triples has removed the red herring warning.

Test failure is known unrelated issue:
https://github.com/intel/llvm/issues/7222

**Pull request merged**
