### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW49)

### PR DESCRIPTION
**Pull request by Fznamznon**
LLVM: llvm/llvm-project@fa06d4d3e206d838c8ff8e5a982dc1ffc9b4c1ae
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@b95227e980fd632e478c1faa2fc1544d42b4c355

### CODE REVIEW

**Comment by Fznamznon** [comment]
@intel/dpcpp-devops-reviewers , I'm under impression that SYCL / Linux / Build + LIT (pull_request_target) happens in one thread. Am I right? Is that expected?

**Comment by pvchupin** [comment]
> @intel/dpcpp-devops-reviewers , I'm under impression that SYCL / Linux / Build + LIT (pull_request_target) happens in one thread. Am I right? Is that expected?

CI just runs configure.py/compile.py and they are occupying machine by full number of available cores by default.

**Comment by Fznamznon** [comment]
SYCL / Linux / HIP AMDGPU LLVM Test Suite (pull_request_target) fails for other PRs as well.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Fri 02 Dec 2022 06:04:26 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Fri 02 Dec 2022 06:08:30 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
