### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW07 2024)

### PR DESCRIPTION
**Pull request by sys-ce-bb**
LLVM: llvm/llvm-project@16e7d6842ef6a5c904422c6dba034e0888ea8b7b
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@262395da9234fe4

### CODE REVIEW

**Comment by jsji** [comment]
@bader @intel/llvm-gatekeepers  This is ready for merge. Thanks.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Fri 16 Feb 2024 01:55:07 AM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Fri 16 Feb 2024 01:59:38 AM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
