### PR TITLE
[NFC] Remove erroneous debug output introduced in a pulldown

### PR DESCRIPTION
**Pull request by aelovikov-intel**
Manifsted itself as "TEST: flang" output during CMake invocation.

### CODE REVIEW

**Review by bader — APPROVED** [review]

**Comment by aelovikov-intel** [comment]
The failure on 

```
Timed Out Tests (1):
  SYCL-Unit :: scheduler/./SchedulerTests/17/19
```

can't be related but failing `check-sycl` results in llvm-test-suite not being run at all, so restarting the whole testing. Writing this comment so that a future github search on the test (if it will fail elsewhere sometime) would point to this run.

**Comment by bader** [comment]
> The failure on
> 
> ```
> Timed Out Tests (1):
>   SYCL-Unit :: scheduler/./SchedulerTests/17/19
> ```
> 
> can't be related but failing `check-sycl` results in llvm-test-suite not being run at all, so restarting the whole testing. Writing this comment so that a future github search on the test (if it will fail elsewhere sometime) would point to this run.

FYI: hit a failure in `check-sycl` recently too. https://github.com/intel/llvm/actions/runs/4289215301/jobs/7472100523
Turned out to be a bug in the test - https://github.com/intel/llvm/pull/8485#issuecomment-1448683048.

I suggest you either investigate this failure right away or file a bug report to investigate it later.

**Comment by aelovikov-intel** [comment]
`SYCL :: Basic/reqd_work_group_size.cpp` failing on HIP is tracked in https://github.com/intel/llvm/issues/8146

**Comment by aelovikov-intel** [comment]
@dpcpp-tools-reviewers can I get this approved and merged please?

**Review by sarnex — APPROVED** [review]
Relinquishing to Alexey's approval, I don't have merge permission though, sorry

**Comment by bader** [comment]
There are not results for "Linux / [AWS] CUDA LLVM Test Suite". Please, file a bug report for this issue.

**Pull request merged**
