### PR TITLE
[SYCL][Bindless][Exp] 3D images accept 3 component vecs instead of 4

### PR DESCRIPTION
**Pull request by DBDuncan**
Update read/write image functions to only accept coords with three arguments instead of the current four, for 3D images. 

Before this patch, when reading or writing to 3D bindless images, 4D coordinates had to be used, where the last coord is always ignored. This patch aligns bindless images to the rest of SYCL and other solutions.

### CODE REVIEW

**Review by Seanst98 — APPROVED** [review]

**Review by ldrumm — CHANGES_REQUESTED** [review]
I'm fine with the code changes in principal (though it's not my area of expertise so I'll let others do a more detailed review there), but I have the following requests to make this a better patchset

- The title has a typo and is long
- Your PR description (which will become the squashed commit message) should use the imperative mood e.g.
`s/This commit changes/change/`
- I'd like some rationale as to why this change is made. Clearly you are changing from 4 element to 3, but *why* is that necessary?

**Comment by DBDuncan** [comment]
> I'm fine with the code changes in principal (though it's not my area of expertise so I'll let others do a more detailed review there), but I have the following requests to make this a better patchset
> 
>     * The title has a typo and is long
> 
>     * Your PR description (which will become the squashed commit message) should use the imperative mood e.g.
>       `s/This commit changes/Change/` (though even "change" is a bit weak because it's obviously a change or it'd be an empty commit)
> 
>     * I'd like some rationale as to why this change is made. Clearly you are changing from 4 element to 3, but _why_ is that necessary?

Thanks for the feedback. Updated the title to be shorter. (and remove that spelling mistake...). Have to admit, did not think about adhering to the imperative commit message style when writing it. Will definitely do so in the future.

Also, added a better explanation as to why the change was made. Made no sense to always require 4D coords to index a 3D image leading to the last coord to always never be used. Also aligns better with the rest of SYCL and other similar solutions.

**Review by ldrumm — APPROVED** [review]

**Comment by DBDuncan** [comment]
@sergey-semenov  Could you please take a look? Made some changes to image.cl.

**Review by sergey-semenov — APPROVED** [review]

**Comment by DBDuncan** [comment]
Got approvals. @intel/llvm-gatekeepers Can this get merged?

**Pull request merged**
