### PR TITLE
HIP reqd_work_group_size attribute

### PR DESCRIPTION
**Pull request by jchlanda**

### CODE REVIEW

**Comment by jchlanda** [comment]
@steffenlarsen I was going to submit this patch, to add `reqd_work_group_size` attribute for HIP, till I discovered your previous patch https://github.com/intel/llvm/pull/7450. 
It seems that we've discovered the same problem/idiosyncrasy in AMD's asm printer, the fact that it expect all 3 dimensions to be present for the attribute. Without realising the existence of the problems you described in the patch, I went ahead and added placeholders values for missing dimensions.
Would you be able to suggest a way forward with non-three-dim attributes? Perhaps, we could patch the printer to spot SYCL mode and relax the validation?

**Comment by steffenlarsen** [comment]
> Perhaps, we could patch the printer to spot SYCL mode and relax the validation?

I think that would be the way to go. I believe we need the dimensionality all the way down to sycl-post-link, so either we would have to change it there or make the printer smarter. I figure making the printer smarter is the better design decision. 😄

**Comment by jchlanda** [comment]
> > Perhaps, we could patch the printer to spot SYCL mode and relax the validation?
> 
> I think that would be the way to go. I believe we need the dimensionality all the way down to sycl-post-link, so either we would have to change it there or make the printer smarter. I figure making the printer smarter is the better design decision. 😄

Agreed, I'll see what I can do.
Thank you for your feedback.

**Comment by jchlanda** [comment]
@steffenlarsen before I split it across UR and intel/llvm repos, what do you think about patching in missing dimensions in lower kernel attribute pass: 160bd1d9ef5804b897d99a773871120cf691c2b5 ? Also, would you say it makes sense to bring it to upstream llvm, my worry is that it can never be triggered without sycl compilation, and so it seems more suited for Intel's fork.

**Comment by steffenlarsen** [comment]
@jchlanda - I still think it would be worth trying to get the behavior into upstream. It should just be relaxing existing restrictions and would not have to be SYCL specific, so getting it into upstream would mean less potential conflicts during pulldowns. Testing it should also be doable, so even if there is no use for it currently, I wouldn't expect much resistance to the idea.

**Comment by hdelan** [comment]
@jchlanda would you be able to rebase this please? My rebase is crashing clang somehow :crying_cat_face:

**Comment by jchlanda** [comment]
> @jchlanda would you be able to rebase this please? My rebase is crashing clang somehow 😿

That's not the branch you want :)
I'll reach out to you in PM.

**Comment by jchlanda** [comment]
Done in a different PR, closing.

**Pull request closed without merging**
