### PR TITLE
[SYCL] Remove _class aliases

### PR DESCRIPTION
**Pull request by alexbatashev**

### CODE REVIEW

**Review by s-kanaev — DISMISSED** [review]
RT changes LGTM.

Should any tests be updated for this change?

**Comment by alexbatashev** [comment]
> RT changes LGTM.
> 
> Should any tests be updated for this change?

No, I removed alias usages from tests a while ago.

**Review by gmlueck — DISMISSED** [review]

**Comment by bader** [comment]
@alexbatashev, please, resolve merge conflicts.

**Review by s-kanaev — APPROVED** [review]
RT changes LGTM

**Review by gmlueck — APPROVED** [review]

**Pull request merged**
