### PR TITLE
[SYCL][UR][L0] Rename ur level_zero files to match ur cuda filenames

### PR DESCRIPTION
**Pull request by hdelan**
There was some divergence in the naming of ur/adapters/level_zero and ur/adapters/cuda files. This PR makes the naming consistent across both. Let me know if any other changes are required.

### CODE REVIEW

**Review by jandres742 — APPROVED** [review]
no major concerns. Please rebase to resolve the conflicts.

**Comment by hdelan** [comment]
> no major concerns. Please rebase to resolve the conflicts.

Thanks @jandres742 . Have rebased

**Review by jandres742 — APPROVED** [review]

**Comment by hdelan** [comment]
Noticed that the l0 were called mem.xpp and CUDA called memory.xpp so renamed

**Comment by hdelan** [comment]
@jandres742 can we merge this please?

**Comment by dm-vodopyanov** [comment]
@hdelan just in case you can ping @intel/llvm-gatekeepers to ask for merging (https://github.com/intel/llvm/blob/sycl/CONTRIBUTING.md#merge)

**Comment by dm-vodopyanov** [comment]
@hdelan also please avoid force-push.

**Comment by dm-vodopyanov** [comment]
Will be merged after all pre-commit checks will be completed.

**Comment by dm-vodopyanov** [comment]
@hdelan there are new merge conflicts, could you please address them?

**Comment by hdelan** [comment]
@dm-vodopyanov pushed merge commit

**Comment by hdelan** [comment]
@dm-vodopyanov looks like it can be merged. Thanks

**Pull request merged**
