### PR TITLE
[SYCL][ESIMD] Rename sbarrier => split_barrier

### PR DESCRIPTION
**Pull request by sndmitriev**
Signed-off-by: Sergey Dmitriev <serguei.n.dmitriev@intel.com>

### CODE REVIEW

**Comment by sndmitriev** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/938

**Review by v-klochkov — APPROVED** [review]

**Comment by v-klochkov** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/938

**Comment by sndmitriev** [comment]
SYCL :: ESIMD/slm_split_barrier.cpp is expected to fail on this patch. The test will be updated by https://github.com/intel/llvm-test-suite/pull/938

**Comment by sndmitriev** [comment]
Does this change (and the accompanying change https://github.com/intel/llvm-test-suite/pull/938) need any additional actions to be merged?

**Comment by sndmitriev** [comment]
ping

**Comment by sndmitriev** [comment]
"Jenkins/verify-test-suite-logs" has completed successfully, what is preventing this PR from being merged?

**Review by kbobrovs — APPROVED** [review]

**Comment by sndmitriev** [comment]
@vladimirlaz, can you please explain what prevents this PR (along with https://github.com/intel/llvm-test-suite/pull/938) from being merged?

**Comment by kbobrovs** [comment]
@vladimirlaz or @pvchupin, could you please merge this PR together with  https://github.com/intel/llvm-test-suite/pull/938?  Both updates depend on each other and can't report clean pass. I can't myself merge llvm-test-suite PRs with failures.

**Pull request merged**
