### PR TITLE
[SYCL] Skip loading imf fp64 fallback library on platform without fp64 ext

### PR DESCRIPTION
**Pull request by jinge90**

### CODE REVIEW

**Comment by jinge90** [comment]
libsycl-fallback-imf-fp64.spv uses fp64, we should skip loading it when fp64 extension is not available.

**Comment by jinge90** [comment]
Hi, @intel/llvm-reviewers-runtime 
Could you help review this PR? we need it to fix a urgent issue.
Thanks very much.

**Comment by jinge90** [comment]
Failed Tests (2):
  SYCL :: AtomicRef/sub_generic_native_fp.cpp
  SYCL :: GroupLocalMemory/no_early_opt.cpp
Should not be related to this PR.

**Comment by jinge90** [comment]
Hi, @intel/llvm-reviewers-runtime 
Kind ping~

**Review by bso-intel — APPROVED** [review]

**Comment by jinge90** [comment]
Hi, @intel/llvm-gatekeepers 
Could you help review and merge this PR?
Pre-ci reported following failures on AMD HIP platform:
Failed Tests (2):
  SYCL :: AtomicRef/sub_generic_native_fp.cpp
  SYCL :: GroupLocalMemory/no_early_opt.cpp
It seems this PR is not related to these 2 tests.
Thanks very much.

**Comment by bader** [comment]
> Could you help review and merge this PR?

This PR is approved by code owners. What help with review do you expect from the gatekeepers team?

**Pull request merged**
