### PR TITLE
[NFC] Run CI.

### PR DESCRIPTION
**Pull request by maksimsab**
Not for commit. Just to run CI.

### CODE REVIEW

**Comment by maksimsab** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1641

**Comment by bader** [comment]
@maksimsab, please, use your private fork to create PR.
Do you need a review for this PR? If no, please, create a draft PR next time and convert this PR.
Please, elaborate why do you need "just run CI".

**Comment by bader** [comment]
> @maksimsab, please, use your private fork to create PR. Do you need a review for this PR? If no, please, create a draft PR next time and convert this PR. Please, elaborate why do you need "just run CI".

@maksimsab, ping.

**Comment by bader** [comment]
@maksimsab, I don't see any value in this PR for the project, so I'm going to close it to remove the private branch. 
If you still want to run some tests, please, open another PR following contribution guidelines i.e. create PR using the private fork and provide clear description for the PR.

**Comment by maksimsab** [comment]
No need for this PR now. It has been created for running tests on CUDA.

**Pull request closed without merging**
