### PR TITLE
[SYCL][COMPAT] Add a free function version of has_capability_or_fail

### PR DESCRIPTION
**Pull request by zhiweij1**
Signed-off-by: Jiang, Zhiwei <zhiwei.jiang@intel.com>

### CODE REVIEW

**Review by ziranzha — COMMENTED** [review]
LGTM

**Review by tomflinda — APPROVED** [review]
LGTM

**Review by Alcpz — APPROVED** [review]

**Comment by zhiweij1** [comment]
Hi @Alcpz, I moved the definition of has_capability_or_fail() to before the device_ext class (b5a2593) to fix the compile fail in CI. Now CI has passed. Can this PR be merged?

**Comment by Alcpz** [comment]
@zhiweij1 Yes. I am fine with that. 
We don´t  have rights to merge PRs into DPC++, in order to merge stuff, please ping the intel/llvm-gatekeepers group. As long as you have the approvals and CI passes, they will merge with no issues.

**Comment by Alcpz** [comment]
@intel/llvm-gatekeepers This PR is ready for merging. Thanks!

**Pull request merged**
