### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW48)

### PR DESCRIPTION
**Pull request by Fznamznon**
LLVM: llvm/llvm-project@7994e5144aa52530fca9af0d81ca7134368034fe
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@b378140863da53bd9fdc313514e00d8c8f45a98f

### CODE REVIEW

**Comment by Fznamznon** [comment]
https://github.com/intel/llvm/pull/7473/commits/6423c97f186f3285b795a0a6ef83a22c737bc426 passed post commit.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Tue 22 Nov 2022 08:19:30 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Tue 22 Nov 2022 08:24:04 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
