### PR TITLE
[SYCL][Matrix] Fix joint_matrix_apply build command.

### PR DESCRIPTION
**Pull request by arnamoy10**

### CODE REVIEW

**Review by dkhaldi — APPROVED** [review]
LGTM

**Comment by arnamoy10** [comment]
@intel/llvm-gatekeepers Help merge this patch please?  The test failures seem unrelated to my changes.

**Comment by arnamoy10** [comment]
@intel/llvm-reviewers-runtime Can you please approve this?  We need this merged ASAP.

**Comment by arnamoy10** [comment]
@steffenlarsen Help merge please?

**Comment by steffenlarsen** [comment]
L0 Failed Tests (1):
  SYCL :: Basic/memory-consumption.cpp - Reported in https://github.com/intel/llvm/issues/9008.

ESIMD Emu failures are known and are being investigated separately.

**Pull request merged**
