### PR TITLE
[SYCL][CUDA][libclc] Add support for generic AS in atomics

### PR DESCRIPTION
**Pull request by t4c1**
Adds support for generic address space in atomics. 

Also fixes `__attribute__((always_inline))` being in wrong place for some of the atomics (it was placed so it applied to some forward declaration of functions used in the implementation of the atomic, instead of the definition of atomic).

Also contains a fix for a bug in libclc remangler that caused wrong remangled names for some of the new functions in this PR (by @AidanBeltonS).

Closes https://github.com/intel/llvm/issues/5215. Closes https://github.com/intel/llvm/issues/5647.

Tests for this are enabled in https://github.com/intel/llvm-test-suite/pull/929.

### CODE REVIEW

**Review by bader — COMMENTED** [review]
@t4c1, please, fix tests on HIP platform and verify your patch with updated tests (i.e. add a comment "/verify with https://github.com/intel/llvm-test-suite/pull/929").

**Comment by t4c1** [comment]
These unexpected passes on HIP do not seem to be related to my changes. I can reproduce them even with `sycl` branch. Also I did not realize I can run the tests myself. Thanks.

**Comment by t4c1** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/929

**Comment by t4c1** [comment]
@bader I don't think this worked.

**Comment by bader** [comment]
> These unexpected passes on HIP do not seem to be related to my changes. I can reproduce them even with `sycl` branch.

I think they are related. These tests fail in all on other pre-commit runs and this patch makes multiple fixes into functionality covered by these tests, so it's very likely that these unexpected passes are caused by your changes.

Even if they are not related, we should remove XFAIL to fix the test status.

**Comment by t4c1** [comment]
Yep, I did that. It is just that the command to run the tests from specific tests suite PR does not work when I comment it.

**Comment by bader** [comment]
> @bader I don't think this worked.

@tfzhu, could you check why this comment https://github.com/intel/llvm/pull/5849#issuecomment-1074939220 haven't triggered PRs validation, please?

**Comment by bader** [comment]
> > These unexpected passes on HIP do not seem to be related to my changes. I can reproduce them even with `sycl` branch.
> 
> I think they are related. These tests fail in all on other pre-commit runs and this patch makes multiple fixes into functionality covered by these tests, so it's very likely that these unexpected passes are caused by your changes.
> 
> Even if they are not related, we should remove XFAIL to fix the test status.

Hm... I just found the same results in pre-commit for https://github.com/intel/llvm/pull/5782 - https://github.com/intel/llvm/runs/5631254024?check_suite_focus=true. Interesting...

**Comment by denis-kabanov** [comment]
@t4c1, looks like your commit [0c113e0](https://github.com/intel/llvm/pull/5849/commits/0c113e07b3ce102b320c6bedecbfaa28e952307e) does not contain changes from syclos [5430](https://github.com/intel/llvm/pull/5430).

**Comment by t4c1** [comment]
I think timeouts for L0 tests are likely unrelated to changes in this PR.

**Comment by bader** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/929

**Comment by bader** [comment]
@t4c1, could you take a look at test results on Windows, please?

> ptxas fatal   : Unresolved extern function '_Z22__spirv_GroupAsyncCopyjPU3AS3Dv2_aPU3AS1KS_yy9ocl_event'

Are you able to reproduce this failure?

**Comment by bader** [comment]
> Yep, I did that. It is just that the command to run the tests from specific tests suite PR does not work when I comment it.

@intel/llvm-external-read, this issue has been fixed and you should be able to tests PRs to llvm and llvm-test-suite together by adding a comment "/verify with <link>", where <link> is either link to the PR from another repository.
Please, let me know if you have any issues with using this testing.

**Review by bader — CHANGES_REQUESTED** [review]
> @t4c1, could you take a look at test results on Windows, please?
> 
> > ptxas fatal   : Unresolved extern function '_Z22__spirv_GroupAsyncCopyjPU3AS3Dv2_aPU3AS1KS_yy9ocl_event'
> 
> Are you able to reproduce this failure?

@t4c1, I restarted to check if this some env. issue, but the same test failed again, so it looks like a regression. Please, take a look.

**Comment by t4c1** [comment]
Sorry for forgetting to respond. We believe this is an issue with the change to remangler and @AidanBeltonS  is looking into it.

**Comment by jchlanda** [comment]
This can be closed now that https://github.com/intel/llvm/pull/7391 is in, right @t4c1 ?

**Comment by t4c1** [comment]
Yes, I think so.

**Pull request closed without merging**
