### PR TITLE
[BuildBot] Uplift GPU RT version for Linux CI Process

### PR DESCRIPTION
**Pull request by bb-sycl**
Uplift GPU RT version for Linux to 21.23.20043

### CODE REVIEW

**Comment by yanfeng3721** [comment]
Hi @vladimirlaz  and @bader , all regression has been analyzed. 
Should we move on with XFAIL flagged, or should we wait for new driver version to fix the regression? 
Known regression:
SYCL :: Basic/reqd_work_group_size.cpp
SYCL :: ESIMD/fp_call_from_func.cpp
SYCL :: OnlineCompiler/online_compiler_L0.cpp, 
Known Pass:
SYCL :: USM/badmalloc.cpp] XDEPS-2135

**Comment by bader** [comment]
> Should we move on with XFAIL flagged, or should we wait for new driver version to fix the regression?
> Known regression:
> SYCL :: Basic/reqd_work_group_size.cpp
> SYCL :: ESIMD/fp_call_from_func.cpp
> SYCL :: OnlineCompiler/online_compiler_L0.cpp,
> Known Pass:
> SYCL :: USM/badmalloc.cpp]

@yanfeng3721, I'm confused. If all these regressions are known, why tests are still failing?
We should disable all failing tests to not block the commit like we have here. There are (at least) two ways to disable lit tests:
1. XFAIL - we can apply this for the tests which are failing reliably. One caveat though - if test is located in llvm-test-suite repository, but bug is not in the test, there will be two commits which should be committed at the same time to avoid pre-/post-commit validation regressions.
2. UNSUPPORTED - this will disable test execution. The difference with XFAIL is that LIT will not notify us when test is fixed. We will have to check the status of manually. OTOH, this way the negative impact on pre-/post-commit is minimal.

More information is available on https://llvm.org/docs/TestingGuide.html#constraining-test-execution and https://llvm.org/docs/CommandGuide/lit.html.

Please, make sure that all regressions are reported to corresponding teams, disable all failing tests and restart the job to pass pre-commit.

**Comment by vladimirlaz** [comment]
complementary test changes: https://github.com/intel/llvm-test-suite/pull/305

**Pull request merged**
