### PR TITLE
[SYCL][L0] Honor property::queue::enable_profiling

### PR DESCRIPTION
**Pull request by smaslov-intel**
E2E test: https://github.com/intel/llvm-test-suite/pull/825
Signed-off-by: Sergey V Maslov <sergey.v.maslov@intel.com>

### CODE REVIEW

**Review by againull — DISMISSED** [review]
It would be nice to have a test in llvm-test-suite for this.

**Comment by smaslov-intel** [comment]
> Failed Tests (1):
  SYCL :: Plugin/level_zero_device_scope_events.cpp

Fixed in https://github.com/intel/llvm-test-suite/pull/825/commits/d17b3936270958ca52a94b466d38a856d2a5c35c

**Review by againull — APPROVED** [review]

**Comment by smaslov-intel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/825

**Comment by smaslov-intel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/841

**Comment by smaslov-intel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/841

**Comment by smaslov-intel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/841

**Review by againull — APPROVED** [review]

**Comment by againull** [comment]
Associated testing passed on Linux and Windows. CUDA testing stalled, but change is isolated to L0 plugin, so cuda testing is unnecessary.

**Pull request merged**
