### PR TITLE
[SYCL][E2E] Move XFAIL to driver check in get_backend.cpp

### PR DESCRIPTION
**Pull request by sarnex**
It passes with a newer driver so just check for that.

### CODE REVIEW

**Comment by sarnex** [comment]
```
********************
Unexpectedly Passed Tests (2):
  SYCL :: Graph/Explicit/work_group_size_prop.cpp
  SYCL :: Graph/RecordReplay/work_group_size_prop.cpp
```

Not related

**Review by aelovikov-intel — APPROVED** [review]

**Comment by sarnex** [comment]
@intel/llvm-gatekeepers This one should be ready for merge, CUDA fail not related. Thanks!

**Comment by aelovikov-intel** [comment]
We've updated the driver and the test started to fail again: https://github.com/intel/llvm/actions/runs/7643052323

@sarnex , do you remember how you found the version to check for?

**Comment by aelovikov-intel** [comment]
@sarnex, ping.

**Comment by sarnex** [comment]
@aelovikov-intel Sorry, somehow I missed the email. I don't remember how but I'll fix this again

**Comment by sarnex** [comment]
https://github.com/intel/llvm/pull/12511

**Pull request merged**
