### PR TITLE
[SYCL] Silence a "local variable is initialized but not referenced" warning; NFC

### PR DESCRIPTION
**Pull request by AaronBallman**

### CODE REVIEW

**Review by AGindinson — APPROVED** [review]

**Comment by AaronBallman** [comment]
By some miracle, I happened to notice this one jump out from the hundreds of warnings generated by the SYCL pi.hpp header.

Build failures are config issues unrelated to the patch:
```
Cloning into 'vc-intrinsics-src'...
fatal: unable to access 'https://github.com/intel/vc-intrinsics.git/': Couldn't connect to server
Cloning into 'vc-intrinsics-src'...
fatal: unable to access 'https://github.com/intel/vc-intrinsics.git/': Couldn't connect to server
Cloning into 'vc-intrinsics-src'...
fatal: unable to access 'https://github.com/intel/vc-intrinsics.git/': Couldn't connect to server
-- Had to git clone more than once:
          3 times.
CMake Error at vc-intrinsics-subbuild/vc-intrinsics-populate-prefix/tmp/vc-intrinsics-populate-gitclone.cmake:31 (message):
  Failed to clone repository: 'https://github.com/intel/vc-intrinsics.git'
```

**Review by mdtoguchi — APPROVED** [review]

**Comment by AGindinson** [comment]
> Build failures are config issues unrelated to the patch.

These are; they seem to be happening in all PRs that are based off a relatively old revision (e.g. doesn't fire for https://github.com/intel/llvm/pull/3869, which is only 14 commits behind intel/sycl).

**Comment by bader** [comment]
> > Build failures are config issues unrelated to the patch.
> 
> These are; they seem to be happening in all PRs that are based off a relatively old revision (e.g. no such thing firing for #3869, which is only 14 commits behind intel/sycl).

I don't think failures are related to the base version. Buildbot merges tip of the sycl branch before building the compiler, so base version should be irrelevant.
Here is the example of such issue for the branch branched from from the tip of the `sycl` branch: branch - https://github.com/intel/llvm/tree/private/ansotkin/fix-duplicate-pointers
Log - http://ci.llvm.intel.com:8010/#/builders/37/builds/9196

@tfzhu, @pvchupin, any ideas what could be wrong here?

**Comment by pvchupin** [comment]
> > > Build failures are config issues unrelated to the patch.
> > 
> > 
> > These are; they seem to be happening in all PRs that are based off a relatively old revision (e.g. no such thing firing for #3869, which is only 14 commits behind intel/sycl).
> 
> I don't think failures are related to the base version. Buildbot merges tip of the sycl branch before building the compiler, so base version should be irrelevant.
> Here is the example of such issue for the branch branched from from the tip of the `sycl` branch: branch - https://github.com/intel/llvm/tree/private/ansotkin/fix-duplicate-pointers
> Log - http://ci.llvm.intel.com:8010/#/builders/37/builds/9196
> 
> @tfzhu, @pvchupin, any ideas what could be wrong here?

It looks like bot connection problem to me. Basically git clone doesn't work because can't get to the deps source repo. @tfzhu, can you take a look?

**Comment by pvchupin** [comment]
Restart helped, but we probably have this intermittent issue in any case.

**Pull request merged**
