### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW44)

### PR DESCRIPTION
**Pull request by sys-ce-bb**
LLVM: llvm/llvm-project@98da18344eed96cabfd2214131185686b1983412
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@a76f24e

### CODE REVIEW

**Comment by jsji** [comment]
This is ready for review.
- [ ] [[SYCL][Test] Add datalayout due to](https://github.com/intel/llvm/pull/11757/commits/a3c60da773da3bc0b8f1bab1961020ed74f999bc) https://github.com/intel/llvm/commit/e39f6c1844fab59c638d8059a6cf139adb42279a opt will infer datalayout so the default layout is different now.

**Comment by jsji** [comment]
Failed Tests (1):
  SYCL :: extensions/annotated_usm/invalid_compile_time_properties.cpp

This is due to https://github.com/intel/llvm/pull/10235, should be fixed in https://github.com/intel/llvm/pull/11762.

**Review by steffenlarsen — APPROVED** [review]

**Comment by bader** [comment]
> This is ready for review.
> 
> * [ ]  [[SYCL][Test] Add datalayout due to](https://github.com/intel/llvm/pull/11757/commits/a3c60da773da3bc0b8f1bab1961020ed74f999bc) [e39f6c1](https://github.com/intel/llvm/commit/e39f6c1844fab59c638d8059a6cf139adb42279a) opt will infer datalayout so the default layout is different now.  @againull

@intel/dpcpp-devops-reviewers, please, take a look.

**Comment by aelovikov-intel** [comment]
> https://github.com/orgs/intel/teams/dpcpp-devops-reviewers, please, take a look.

Did you mean @intel/dpcpp-tools-reviewers ?

**Comment by bader** [comment]
> > https://github.com/orgs/intel/teams/dpcpp-devops-reviewers, please, take a look.
> 
> Did you mean @intel/dpcpp-tools-reviewers ?

Thanks. Fixed!

**Review by againull — APPROVED** [review]

**Comment by jsji** [comment]
Thanks @againull for reviewing the testchanges in llvm/test/SYCLLowerIR/convergent.ll.

@bader @intel/llvm-gatekeepers  Can we get this merged ? Thanks!

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Mon 06 Nov 2023 09:47:12 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Mon 06 Nov 2023 09:52:06 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
