### PR TITLE
[SYCL] Remove sycl_ext_oneapi_nd_range_reductions docs

### PR DESCRIPTION
**Pull request by aelovikov-intel**
The extension implementation had been removed mid-2022.

### CODE REVIEW

**Review by Pennycook — CHANGES_REQUESTED** [review]
According to https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/removed/README.md, the extension specification should be moved from deprecated/ to removed/.

**Comment by aelovikov-intel** [comment]
> According to https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/removed/README.md, the extension specification should be moved from deprecated/ to removed/.

There are no specifications there. Is the requirement really up-to-date?

**Comment by gmlueck** [comment]
>There are no specifications there. Is the requirement really up-to-date?

Yes, that is still the process.  You are the first person to remove a deprecated extension, which is why there are none in that folder yet.

**Comment by Pennycook** [comment]
> There are no specifications there. Is the requirement really up-to-date?

I'm not sure.  @gmlueck, is this the first time we've removed an extension that didn't get merged into SYCL 2020 without changes?

**Review by gmlueck — APPROVED** [review]

**Comment by aelovikov-intel** [comment]
@intel/llvm-gatekeepers , PR is ready.

**Pull request merged**
