### PR TITLE
[SYCL][L0] address Coverity issue with active_barrier::clear

### PR DESCRIPTION
**Pull request by smaslov-intel**
Signed-off-by: Sergey V Maslov <sergey.v.maslov@intel.com>

### CODE REVIEW

**Comment by smaslov-intel** [comment]
@bso-intel : please review/approve in @againull absence

**Review by bso-intel — APPROVED** [review]
LGTM

**Comment by smaslov-intel** [comment]
@intel/llvm-reviewers-runtime : please merge this PR

**Comment by steffenlarsen** [comment]
ESIMD EMU Failed Tests (1):
  SYCL :: dword_atomic_smoke.cpp
Fixed with https://github.com/intel/llvm-test-suite/pull/1552.

**Comment by steffenlarsen** [comment]
No other level zero reviewers available. Merging with runtime approval.

**Pull request merged**
