### PR TITLE
[SYCL][NFC] Cast unchecked return value to void.

### PR DESCRIPTION
**Pull request by schittir**

### CODE REVIEW

**Comment by schittir** [comment]
@tahonermann - I am unable to add you as a reviewer here. Please feel free to take a look anyway.

**Review by elizabethandrews — APPROVED** [review]

**Comment by tahonermann** [comment]
> @tahonermann - I am unable to add you as a reviewer here. Please feel free to take a look anyway.

Interesting. I don't seem to be able to add myself either. At any rate, the change looks fine to me!

**Review by premanandrao — APPROVED** [review]

**Comment by premanandrao** [comment]
> > @tahonermann - I am unable to add you as a reviewer here. Please feel free to take a look anyway.
> 
> Interesting. I don't seem to be able to add myself either. At any rate, the change looks fine to me!

Do you have an intel email address associated with your profile?

**Comment by schittir** [comment]
Hi, @bader Could you please merge this?

**Comment by bader** [comment]
> Hi, @bader Could you please merge this?

@schittir, please ping https://github.com/orgs/intel/teams/llvm-gatekeepers for this.
Process: https://github.com/intel/llvm/blob/sycl/CONTRIBUTING.md#merge

**Pull request merged**
