### PR TITLE
[SYCL][CI] Add zstd to our build image

### PR DESCRIPTION
**Pull request by aelovikov-intel**
I will remove unneeded package (lz4 or/and zstd) once we settle which one is the best for our use.

### CODE REVIEW

**Comment by bader** [comment]
> I will remove unneeded package (lz4 or/and zstd) once we settle which one is the best for our use.

Don't we know already that zstd is better for our use?

**Comment by aelovikov-intel** [comment]
> Don't we know already that zstd is better for our use?

I kind of have an answer for this in the PR's description:

> I will remove unneeded package (lz4 **or/and** zstd) once we settle which one is the best for our use.

In my local experiments `zstd -9` results in about 25% bigger size while taking about 20x less time than our current compression.

**Comment by aelovikov-intel** [comment]
> So, why do we keep lz4? `zstd` seems to be a better choice.

Because I want to ensure that CI results match what I have locally first. Also, I don't see any issues keeping it here for a few days.

**Review by bader — APPROVED** [review]
Don't forget to remove lz4!

**Pull request merged**
