### PR TITLE
[SYCL] Make backend a property of a platform

### PR DESCRIPTION
**Pull request by smaslov-intel**

### CODE REVIEW

**Review by steffenlarsen — APPROVED** [review]
Good stuff! This looks much cleaner.

**Review by v-klochkov — APPROVED** [review]

**Comment by smaslov-intel** [comment]
@intel/llvm-gatekeepers: please merge.
The CUDA failure is unrelated and is tracked here: https://github.com/intel/llvm/issues/9174
> Failed Tests (1):
  SYCL :: Regression/same_unnamed_kernels.cpp

**Comment by FreddyLeaf** [comment]
I saw a build fail after this patch:
```
llvm/sycl/unittests/pi/BackendString.hpp:20:10: error: returning address of local temporary object [-Werror,-Wreturn-stack-address]
  return Str.str().c_str();
         ^~~~~~~~~

**Comment by FreddyLeaf** [comment]
> I saw a build fail after this patch:
> 
> ```
> llvm/sycl/unittests/pi/BackendString.hpp:20:10: error: returning address of local temporary object [-Werror,-Wreturn-stack-address]
>   return Str.str().c_str();
>          ^~~~~~~~~
> ```

Hello, could any of you help resolve this? Thanks a lot!

**Comment by smaslov-intel** [comment]
> > I saw a build fail after this patch:
> > ```
> > llvm/sycl/unittests/pi/BackendString.hpp:20:10: error: returning address of local temporary object [-Werror,-Wreturn-stack-address]
> >   return Str.str().c_str();
> >          ^~~~~~~~~
> > ```
> 
> Hello, could any of you help resolve this? Thanks a lot!

What build is failing?

**Comment by FreddyLeaf** [comment]
> > > I saw a build fail after this patch:
> > > ```
> > > llvm/sycl/unittests/pi/BackendString.hpp:20:10: error: returning address of local temporary object [-Werror,-Wreturn-stack-address]
> > >   return Str.str().c_str();
> > >          ^~~~~~~~~
> > > ```
> > 
> > 
> > Hello, could any of you help resolve this? Thanks a lot!
> 
> What build is failing?

I think it's with -Werror,-Wreturn-stack-address when building check-all

**Comment by againull** [comment]
> > > I saw a build fail after this patch:
> > > ```
> > > llvm/sycl/unittests/pi/BackendString.hpp:20:10: error: returning address of local temporary object [-Werror,-Wreturn-stack-address]
> > >   return Str.str().c_str();
> > >          ^~~~~~~~~
> > > ```
> > 
> > 
> > Hello, could any of you help resolve this? Thanks a lot!
> 
> What build is failing?

I think the build with -Werror will fail. In any case, this looks like a real bug, in the code indeed C string is returned which is going to be freed after end of scope of this function (when std::stringstream Str; is destructed).

**Comment by smaslov-intel** [comment]
> > > > I saw a build fail after this patch:
> > > > ```
> > > > llvm/sycl/unittests/pi/BackendString.hpp:20:10: error: returning address of local temporary object [-Werror,-Wreturn-stack-address]
> > > >   return Str.str().c_str();
> > > >          ^~~~~~~~~
> > > > ```
> > > 
> > > 
> > > Hello, could any of you help resolve this? Thanks a lot!
> > 
> > 
> > What build is failing?
> 
> I think the build with -Werror will fail. In any case, this looks like a real bug, in the code indeed C string is returned which is going to be freed after end of scope of this function (when std::stringstream Str; is destructed).

I know and fixing in https://github.com/intel/llvm/pull/9232/files#diff-bdd3b8fe78c5f95c7ee4d61de34a1123646835047a2d0c5f85124d02655c4ce1

Just wanted to know how to test locally.

**Comment by FreddyLeaf** [comment]
> > > > > I saw a build fail after this patch:
> > > > > ```
> > > > > llvm/sycl/unittests/pi/BackendString.hpp:20:10: error: returning address of local temporary object [-Werror,-Wreturn-stack-address]
> > > > >   return Str.str().c_str();
> > > > >          ^~~~~~~~~
> > > > > ```
> > > > 
> > > > 
> > > > Hello, could any of you help resolve this? Thanks a lot!
> > > 
> > > 
> > > What build is failing?
> > 
> > 
> > I think the build with -Werror will fail. In any case, this looks like a real bug, in the code indeed C string is returned which is going to be freed after end of scope of this function (when std::stringstream Str; is destructed).
> 
> I know and fixing in https://github.com/intel/llvm/pull/9232/files#diff-bdd3b8fe78c5f95c7ee4d61de34a1123646835047a2d0c5f85124d02655c4ce1
> 
> Just wanted to know how to test locally.

Thanks for fixing!

**Comment by FreddyLeaf** [comment]
FYI it is my second time reporting similar fails under -werror=on, last fix is https://github.com/intel/llvm/pull/9130

**Pull request merged**
