### PR TITLE
[SYCL][L0]: Kernel Destroy in piKernelRelease

### PR DESCRIPTION
**Pull request by nrspruit**
Signed-off-by: Spruit, Neil R <neil.r.spruit@intel.com>

### CODE REVIEW

**Review by smaslov-intel — APPROVED** [review]
LGTM

**Comment by smaslov-intel** [comment]
@bader , @vladimirlaz any idea how LeveL-Zero plugin change may possibly affect "Lit_With_Cuda"?

**Comment by vladimirlaz** [comment]
> @bader , @vladimirlaz any idea how LeveL-Zero plugin change may possibly affect "Lit_With_Cuda"?

it looks like flaky issue.

**Comment by smaslov-intel** [comment]
> > @bader , @vladimirlaz any idea how LeveL-Zero plugin change may possibly affect "Lit_With_Cuda"?
> 
> it looks like flaky issue.

I've seen this recently in 2 other PR, what we can do to fix it asap?

**Comment by vladimirlaz** [comment]
> > > @bader , @vladimirlaz any idea how LeveL-Zero plugin change may possibly affect "Lit_With_Cuda"?
> > 
> > 
> > it looks like flaky issue.
> 
> I've seen this recently in 2 other PR, what we can do to fix it asap?

I think, ticket is needed with proper priority.

**Comment by romanovvlad** [comment]
The fails are not related to the patch and are being fixed in https://github.com/intel/llvm/pull/2481. Merging.

**Pull request merged**
