### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW12 2024)

### PR DESCRIPTION
**Pull request by sys-ce-bb**
LLVM: llvm/llvm-project@e6b5bd5854c80eac05f415ad282ba84b840b8af8
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@98729ef13ca970b98a149c18318746df8d921f20

### CODE REVIEW

**Comment by jsji** [comment]
AMD/HIP failure is common to others, also seen in https://github.com/intel/llvm/actions/runs/8443005736/job/23125974887.

@bader  @intel/llvm-gatekeepers This is read for merge. There are a few cherry-picks to fix failures, but all code are from llorg, no review required. Thanks.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Wed 27 Mar 2024 02:20:01 AM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Wed 27 Mar 2024 02:24:16 AM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
