### PR TITLE
[SYCL][Doc] Clarify restrictions on device global variables

### PR DESCRIPTION
**Pull request by gmlueck**
Clarify the restrictions for declaring variables of type
`device_global`.  These restrictions are similar to those we have
already for `specialization_id` variables.

The restriction against arrays of `device_global` variables is not
strictly necessary, but it would take extra effort to implement and
we do not have a compelling use case.  We could lift the restriction
later if we find a need.

### CODE REVIEW

**Review by jbrodman — DISMISSED** [review]

**Comment by gmlueck** [comment]
@bader: Can this be merged?  This PR changes only the extension API specification, and a member of @intel/dpcpp-specification-reviewers has signed off.

**Comment by dm-vodopyanov** [comment]
@gmlueck, can you please resolve a conflict in
```sycl/doc/extensions/DeviceGlobal/SYCL_INTEL_device_global.asciidoc```?

**Comment by gmlueck** [comment]
> @gmlueck, can you please resolve a conflict in sycl/doc/extensions/DeviceGlobal/SYCL_INTEL_device_global.asciidoc?

Done.

**Comment by gmlueck** [comment]
ping to @dm-vodopyanov.  Can this be merged now?  The conflicts are resolved.

**Pull request merged**
