### PR TITLE
[ESIMD] Implement accessor based gather_rgba/scatter_rgba

### PR DESCRIPTION
**Pull request by v-klochkov**

### CODE REVIEW

**Comment by v-klochkov** [comment]
The corresponding changes in LIT tests are: https://github.com/intel/llvm/pull/6131

**Comment by v-klochkov** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1022

**Review by kbobrovs — APPROVED** [review]

**Comment by kbobrovs** [comment]
One comment which can be applied as a separate PR is default RGBAMask template parameter value to `channel_mask::ABGR`

**Comment by v-klochkov** [comment]
> One comment which can be applied as a separate PR is default RGBAMask template parameter value to `channel_mask::ABGR`

Thank you. I uploaded the fix to make ABGR default value for rgba mask in gather/scatter: https://github.com/intel/llvm/pull/6141

**Pull request merged**
