### PR TITLE
[GHA] Uplift Linux GPU RT version to 23.52.28202.14

### PR DESCRIPTION
**Pull request by bb-sycl**
Scheduled drivers uplift

### CODE REVIEW

**Comment by aelovikov-intel** [comment]
```
Failed Tests (1):
  SYCL :: ESIMD/aot_mixed.cpp
```

**Comment by aelovikov-intel** [comment]
I also think we might need to change CI to do some extended testing for those uplifts (e.g. full post-commit).

**Comment by sarnex** [comment]
@aelovikov-intel Should I disable aot_mixed? It looks like an IGC bug.

**Comment by aelovikov-intel** [comment]
> @aelovikov-intel Should I disable aot_mixed? It looks like an IGC bug.

Probably yes. We can't uplift without green CI task.

**Comment by sarnex** [comment]
https://github.com/intel/llvm/pull/12630

**Comment by sarnex** [comment]
@aelovikov-intel I merged that PR, we can probably rebase this PR and rerun tests

**Comment by bader** [comment]
🚀

**Review by sarnex — APPROVED** [review]
Ship it baby

**Review by aelovikov-intel — APPROVED** [review]

**Pull request merged**
