### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW25)

### PR DESCRIPTION
**Pull request by dwoodwor-intel**
LLVM: llvm/llvm-project@7dbfcfa735f2
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@583d365ab266

### CODE REVIEW

**Comment by pvchupin** [comment]
Renamed title because we have ww25 already :) Hope testing is clean and we'll merge.

**Comment by dwoodwor-intel** [comment]
> Renamed title because we have ww25 already :) Hope testing is clean and we'll merge.

The last one that I saw was ww24 (#6249); did I miss one?

**Comment by dwoodwor-intel** [comment]
Testing is clean

**Comment by bb-sycl** [comment]
Fri 10 Jun 2022 07:38:19 PM UTC --- Merge failed with error: Comment user is not in llvm_gatekeepers group or doesn't have merge right for target branch. Please contact with admins of the repo if there is any question.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Fri 10 Jun 2022 07:39:57 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by pvchupin** [comment]
@dwoodwor-intel, I'll add you to the group

**Comment by bb-sycl** [comment]
Fri 10 Jun 2022 07:43:33 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
