### PR TITLE
ESIMD EMU single_task():

### PR DESCRIPTION
**Pull request by lsatanov**
Discussion: we can call single_task kernel not from plugin.

- ESIMD EMU: single_task() support.
- ESIMD plugin: misc clarifying refactoring.

### CODE REVIEW

**Comment by lsatanov** [comment]
ok, sycl/lint , how do I clang-format it...

**Comment by dongkyunahn-intel** [comment]
For clang-formatting : 
```
./clang/tools/clang-format/git-clang-format `git merge-base origin/sycl HEAD`
```

https://github.com/intel/llvm/blob/sycl/CONTRIBUTING.md#development

**Comment by lsatanov** [comment]
> ```
> 
> ```

Read it, however, I've applied the patch emitted by linter check.

**Comment by dongkyunahn-intel** [comment]
I would suggest separating this PR into two PRs as follows and merge the first one first.

* One for `sycl/include/CL/sycl/detail/cg_types.hpp` and `sycl/include/CL/sycl/handler.hpp`.
* The other for remaining files.

This is because the first two files are sycl runtime changes while others pertain only to `esimd_emulator` backend.

**Comment by lsatanov** [comment]
> I would suggest separating this PR into two PRs as follows and merge the first one first.
> 
> * One for `sycl/include/CL/sycl/detail/cg_types.hpp` and `sycl/include/CL/sycl/handler.hpp`.
> * The other for remaining files.
> 
> This is because the first two files are sycl runtime changes while others pertain only to `esimd_emulator` backend.

We can always make more entities, but only if the reason is justified (in particular case I want the whole picture in one place).

P.S. I'll make more changes to the draft,
1. Maybe I'll remove change to NDRDescT which can/should be done separately
2. There are two variants of single_task launch exposed here either of which can be considered (in and out of plugin), but, for current variant, maybe we can wrap it in "normalization" stage so that passing kernel pointer to plugin was uniform. Need to check it.

**Comment by dongkyunahn-intel** [comment]
> So, apparently my local clang-format doesn't like the NamespaceMacros setting found in sycl/.clang-format file, I've checked with versions 11, 9, 6.0.

I have same problem. It seems that the macro works for some editors while others fail. You can remove the second line from the file then the command line should work fine.

**Comment by lsatanov** [comment]
+ Need to debug and address cases when MArgs.size () > 0 for single_task (e.g. simd_any_all) and we erroneously dispatch to non-single-task launch.

**Review by dongkyunahn-intel — COMMENTED** [review]
I would suggest getting comments from SYCL runtime folks for any changes in runtime asap.

**Pull request closed without merging**
