### PR TITLE
[SYCL][HIP] Support lowerWGScope and fix hip event

### PR DESCRIPTION
**Pull request by malixian**
Support lowerWGScope for AMDGPU and fix _pi_event::is_completed() function.

### CODE REVIEW

**Comment by malixian** [comment]
Ang questions about this PR?

**Review by kbobrovs — APPROVED** [review]
LowerWGScope.cpp LGTM. Good to see enabling HIP is that simple.

Should corresponding tests from https://github.com/intel/llvm-test-suite/tree/intel/SYCL/HierPar
be enabled for HIP as well?

**Comment by malixian** [comment]
> Should corresponding tests from https://github.com/intel/llvm-test-suite/tree/intel/SYCL/HierPar be enabled for HIP as well?
I test from SYCL-CTS/tests/h_item, handler and stream.

**Comment by kbobrovs** [comment]
> I test from SYCL-CTS/tests/h_item, handler and stream.

OK. But llvm-test-suite/tree/intel/SYCL/HierPar should still pass - correct? If so, why not enable them?

**Comment by malixian** [comment]
> OK. But llvm-test-suite/tree/intel/SYCL/HierPar should still pass - correct? If so, why not enable them?
Yes, it's a good case to test this feature. But I first encountered this problem in the  sycl-cts benchmark.

**Review by againull — APPROVED** [review]

**Pull request merged**
