### PR TITLE
[SYCL] Switch to correct name "OpenCL.DebugInfo.100"

### PR DESCRIPTION
**Pull request by NikitaRudenkoIntel**
for SPIRV debug info extension

### CODE REVIEW

**Review by AlexeySachkov — COMMENTED** [review]
The change itself looks good to me, but I wonder whether we actually have some tests for debug info in our pre-commit: we need to be sure that SPIR-V consumers in low-level runtimes has been updated to consume `OpenCL.DebugInfo.100` extended instruction set.

@vladimirlaz, do you know if we have any tests with `-g` in our pre-commit?

**Comment by vladimirlaz** [comment]
> The change itself looks good to me, but I wonder whether we actually have some tests for debug info in our pre-commit: we need to be sure that SPIR-V consumers in low-level runtimes has been updated to consume `OpenCL.DebugInfo.100` extended instruction set.
> 
> @vladimirlaz, do you know if we have any tests with `-g` in our pre-commit?

We do not have reliable tests in pre-commit CI. A few tests use it but coverage is not sufficient.

**Comment by MrSidims** [comment]
We should have FPGA tests that are being compiled with `-fintelfpga` flag, that adds `-g` by default, so if this change doesn't bring regressions on such a wild hardware we can claim, that the patch was OK tested.

**Review by MrSidims — APPROVED** [review]

**Review by mdtoguchi — APPROVED** [review]
LGTM

**Pull request merged**
