### PR TITLE
[SYCL][Devops] Fix containers build

### PR DESCRIPTION
**Pull request by AlexeySachkov**
We already have `sycl` user created by a base image, no need to repeat that.
This is a follow-up to intel/llvm#16290 to address an issue which was not caught by pre-commit.

### CODE REVIEW

**Comment by sarnex** [comment]
did we change anything about permissions or groups? sorry i forget

**Comment by AlexeySachkov** [comment]
> did we change anything about permissions or groups? sorry i forget

Well, technically we do switch into `sycl` user in a base image, which is generally earlier than it used to be. But if that's an issue, then it would have failed like this even before this PR.

I'm not entirely sure which exact user is doing `apt-get` here

**Comment by sarnex** [comment]
i think it used be running as `root `but now its running as `sycl`. `sycl `should have sudo nopass, can you try just adding a sudo to the failing line?

**Comment by sarnex** [comment]
```
 #7 0.324 sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
#7 0.325 sudo: a password is required```

uuh

**Comment by AlexeySachkov** [comment]
> ```
>  #7 0.324 sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
> #7 0.325 sudo: a password is required
> ```
> 
> uuh

Perhaps I need to move `USER sycl` to the beginning. I'm not entirely sure how those base docker images work, i.e. it could be that  we invoke those instructions as some "default" user which is not in sudoers

**Comment by sarnex** [comment]
@AlexeySachkov I think we need [this](https://github.com/intel/llvm/blob/sycl/devops/containers/ubuntu2204_base.Dockerfile#L25) in the `_build` image too. 

I tried to do the same thing before but it kinda [got](https://github.com/intel/llvm/pull/15017) push back

**Comment by sarnex** [comment]
oh yeah my bad

**Comment by AlexeySachkov** [comment]
Considering that we have reverted the original commit, I will close this for now in favor of a new PR which will be a complete re-submit of the whole refactoring.

**Pull request closed without merging**
