### PR TITLE
[BuildBot] Sync testlist.cfg with latest sycl-cts repo

### PR DESCRIPTION
**Pull request by yanfeng3721**

### CODE REVIEW

**Comment by yanfeng3721** [comment]
There was a CTS regression(https://github.com/intel/llvm/pull/3004) not cached by Post commit testing due to missing some test category:
Regression:
```
--- specialization_constants_via_handler_core
  . line: 212
  . case 8 for unsigned char
  . line: 212
  . case 8 for sycl::byte
  . line: 212
  . case 8 for std::uint8_t
  - fail

  . Passed 0/2 tests (0%)
```
Missing tests:
```
exceptions
host_task
reduction
specialization_constants
usm
```

**Comment by bader** [comment]
> There was a CTS regression(#3004) not catch by Post commit testing due to missing some test category:

@yanfeng3721, please, file a bug report and assign to @mdtoguchi.

**Comment by yanfeng3721** [comment]
> > There was a CTS regression(#3004) not catch by Post commit testing due to missing some test category:
> 
> @yanfeng3721, please, file a bug report and assign to @mdtoguchi.

Sure, the bug is already reported.

**Comment by yanfeng3721** [comment]
Adding missing 5 tests does not impact the CTS regression time observably compared with recently finished post commit
Current PR: 
Linux:
```
Regression_CTS_GPU:             1h 5m 35s
Regression_CTS_CPU:             1h 11m 59
Regression_CTS_FPGA:           1h 13m 26s
```
Windows:
```
Regression_CTS_GPU_WIN:    1h 20m 53s
Regression_CTS_CPU_WIN:    1h 50m 59s
Regression_CTS_FPGA_WIN:  2h 15m 19s
```
https://github.com/intel/llvm/pull/5172:
Linux:
```
Regression_CTS_GPU:             1h 5m 13s
Regression_CTS_CPU:             1h 24m 49s
Regression_CTS_FPGA:           1h 13m 2s
```
Windows:
```
Regression_CTS_GPU_WIN:   1h 55m 36s
Regression_CTS_CPU_WIN:   1h 55m 36s
Regression_CTS_FPGA_WIN: 1h 51m 19s
```

**Comment by yanfeng3721** [comment]
The failure "SYCL :: XPTI/basic_event_collection.cpp" is unrelated.

**Review by bader — APPROVED** [review]

**Pull request merged**
