### PR TITLE
[BuildBot] Uplift GPU RT version for Linux CI Process

### PR DESCRIPTION
**Pull request by bb-sycl**
Uplift GPU RT version for Linux to 21.49.21786

### CODE REVIEW

**Comment by vladimirlaz** [comment]
@yanfeng3721, @yinyangsx could you check that all required libraries and dependencies uploaded properly. there are some misconfiguration for the OnlineCompiler/online_compiler_L0.cpp test.
```
[2021-12-13T07:38:43.497Z] Command was: ocloc -q -spv_only -device skl -64 -options -cmc -file main.cl
[2021-12-13T07:38:43.497Z] Compilation to IL failed: ocloc reported compilation errors: {
[2021-12-13T07:38:43.497Z] AdaptorCM: could not load FEWrapper: <libclangFEWrapper.so>: libclangFEWrapper.so: cannot open shared object file: No such file or directory
[2021-12-13T07:38:43.497Z] Build failed with error code: -11
[2021-12-13T07:38:43.497Z] 
[2021-12-13T07:38:43.497Z] }
[2021-12-13T07:38:43.497Z] 
```
@kbobrovs could you have a look into other failures? All of them have the same error.
```
[2021-12-13T07:31:57.304Z] error: GenXLegalization failed for: <  %call.i.i.i.i = select <1 x i1> %cmp.i.i85.i, <1 x i64> %sub.i.i, <1 x i64> %call.i.i.i27.i.i>: 'i64' data type is not supported by this target <ADLS>
[2021-12-13T07:31:57.304Z] llvm-foreach: 
[2021-12-13T07:31:57.304Z] clang-14: error: gen compiler command failed with exit code 1 (use -v to see invocation)
```

**Comment by DoyleLi** [comment]
Hi @vladimirlaz and @yanfeng3721, there is wget error when we do the RT uplift process for https://api.github.com/repos/intel/cm-compiler/releases/latest.
So some files missed.
I have add protection in the script and updated the files. 
The files will be ready in about 8 hours later.
I will trigger the ci again if I have got a chance.

**Comment by vladimirlaz** [comment]
@kbobrovs The problems below are still in place.

> @yanfeng3721, @yinyangsx could you check that all required libraries and dependencies uploaded properly. there are some misconfiguration for the OnlineCompiler/online_compiler_L0.cpp test.
> 
> ```
> [2021-12-13T07:38:43.497Z] Command was: ocloc -q -spv_only -device skl -64 -options -cmc -file main.cl
> [2021-12-13T07:38:43.497Z] Compilation to IL failed: ocloc reported compilation errors: {
> [2021-12-13T07:38:43.497Z] AdaptorCM: could not load FEWrapper: <libclangFEWrapper.so>: libclangFEWrapper.so: cannot open shared object file: No such file or directory
> [2021-12-13T07:38:43.497Z] Build failed with error code: -11
> [2021-12-13T07:38:43.497Z] 
> [2021-12-13T07:38:43.497Z] }
> [2021-12-13T07:38:43.497Z] 
> ```
> 
> @kbobrovs could you have a look into other failures? All of them have the same error.
> 
> ```
> [2021-12-13T07:31:57.304Z] error: GenXLegalization failed for: <  %call.i.i.i.i = select <1 x i1> %cmp.i.i85.i, <1 x i64> %sub.i.i, <1 x i64> %call.i.i.i27.i.i>: 'i64' data type is not supported by this target <ADLS>
> [2021-12-13T07:31:57.304Z] llvm-foreach: 
> [2021-12-13T07:31:57.304Z] clang-14: error: gen compiler command failed with exit code 1 (use -v to see invocation)
> ```

**Comment by kbobrovs** [comment]
@vladimirlaz,
re online compiler - please disable it if it fails and file a tracker assigning to @v-klochkov 
re other failures:
 - I only one ESIMD-specific: LLVM :: ESIMD/api/simd_copy_to_from.cpp - this looks like testing was done on a build w/o https://github.com/intel/llvm/pull/5135. + @sndmitriev for awareness (PR author)
 - `error: GenXLegalization failed for: <  %call.i.i.i.i = select <1 x i1> %cmp.i.i85.i, <1 x i64> %sub.i.i, <1 x i64> %call.i.i.i27.i.i>: 'i64' data type is not supported by this target <ADLS>` - this one is neither ESIMD not OnlineCompile - specific, coming from LLVM :: AOT/gpu.cpp. I believe the problem here is that the new driver's ocloc started supporting AlderLake-S graphics, where i64 is not supoprted, but the test generates i64 ops. Looks like this should be redirected to IGC folks. Another way is disable ADLS in the target platform list for ocloc.

**Pull request closed without merging**
