### PR TITLE
[SYCL][ESIMD] Fix test failure when built with icpx and executed in emulator

### PR DESCRIPTION
**Pull request by fineg74**

### CODE REVIEW

**Review by sarnex — APPROVED** [review]
lgtm and i manually confirmed by adding an assert in `__esimd_wrregion` that there are no more out of bound writes

**Comment by turinevgeny** [comment]
> lgtm and i manually confirmed by adding an assert in `__esimd_wrregion` that there are no more out of bound writes

Nice! Can you share a patch? (just curious and might help others).

**Review by turinevgeny — APPROVED** [review]

**Comment by sarnex** [comment]
> Nice! Can you share a patch? (just curious and might help others).

Sure, nothing special though

```
diff --git a/sycl/include/sycl/ext/intel/esimd/detail/intrin.hpp b/sycl/include/sycl/ext/intel/esimd/detail/intrin.hpp
index 3b9d6f134772..05c61d7d1c93 100644
--- a/sycl/include/sycl/ext/intel/esimd/detail/intrin.hpp
+++ b/sycl/include/sycl/ext/intel/esimd/detail/intrin.hpp
@@ -310,6 +310,7 @@ __esimd_wrregion(__ESIMD_DNS::vector_type_t<T, N> OldVal,
   int Index = 0;
   for (int i = 0; i < NumRows; ++i) {
     for (int j = 0; j < Width; ++j) {
+      assert(i * VStride + j * Stride + EltOffset < N);
       if (Mask[Index])
         Result[i * VStride + j * Stride + EltOffset] = NewVal[Index];
       ++Index;
```

**Comment by v-klochkov** [comment]
Please specify the test name in the commit-title to make it more informative without need to look inside the commit.
E.g. "[ESIMD][E2E] Fix slm_gather_scatter_rgba.cpp failure with icpx+emulator"

**Pull request merged**
