### PR TITLE
[SYCL][Doc]Comparisons in "if_architecture_is"

### PR DESCRIPTION
**Pull request by gmlueck**
Update the "if_architecture_is" extension spec to allow greater-than and less-than comparisons between architecture values.

### CODE REVIEW

**Comment by gmlueck** [comment]
Note that this PR is "stacked" on top of #12258.  Once #12258 is merged, I'll change the target of this PR to the "sycl" branch.

**Comment by gmlueck** [comment]
@intel/llvm-gatekeepers do you have any suggestion about the CI failure?  I think CI is somehow confused here.  It is probably related to the way I created this PR.  I initially created it as a "stacked" PR on top of #12258.  (I.e. the destination branch of this PR was the branch containing #12258.  Thus, this PR showed only the incremental changes.)  Once #12258 was merged, I rebased this PR on top of it, and I also changed the destination branch of this PR to be "sycl", which is the normal destination branch for PRs in this repo.

My guess is that this somehow confused the CI system.  Is there some way to rerun the CI tests from scratch?

**Comment by aelovikov-intel** [comment]
> My guess is that this somehow confused the CI system. Is there some way to rerun the CI tests from scratch?

My best and only guess would be to close/re-open this PR.

**Review by zettai-reido — APPROVED** [review]
Looks good.

I would have renamed `fallback` to `generic` at L990 because fallback usually is not what is decided in the kernel.

**Comment by dm-vodopyanov** [comment]
@intel/dpcpp-specification-reviewers, friendly ping

**Comment by dm-vodopyanov** [comment]
> Looks good.
> 
> I would have renamed `fallback` to `generic` at L990 because fallback usually is not what is decided in the kernel.

Will be addressed in the separate PR.

**Comment by aelovikov-intel** [comment]
Post commit failures (for future references/searches):

```
# Arc GPU:
Failed Tests (2):
  SYCL :: ESIMD/lsc/local_accessor_atomic_smoke_cmpxchg.cpp
  SYCL :: ESIMD/lsc/lsc_slm_atomic_smoke.cpp
```

**Pull request merged**
