### PR TITLE
[SYCL][NATIVECPU] Add SPIR-V work-group/item builtins on Windows

### PR DESCRIPTION
**Pull request by uwedolinsky**
1. Enabling translation of calls to SpirV workgroup and workitem functions into calls to NativeCPU builtins on Windows.
2. Enabling NativeCPU test previously unsupported on Windows.
3. BuiltinMap now uses StringRef making the initialization static.

### CODE REVIEW

**Review by PietroGhg — APPROVED** [review]
LGTM, thank you

**Comment by uwedolinsky** [comment]
Hello @intel/llvm-gatekeepers , we think this PR could be merged. Thank you!

**Review by dm-vodopyanov — CHANGES_REQUESTED** [review]
Permissions of llvm/lib/SYCLLowerIR/PrepareSYCLNativeCPU.cpp changed from 644 to 755, please fix.

**Review by dm-vodopyanov — APPROVED** [review]

**Comment by uwedolinsky** [comment]
> Permissions of llvm/lib/SYCLLowerIR/PrepareSYCLNativeCPU.cpp changed from 644 to 755, please fix.

Thank you for spotting this. I've changed it back to 644

**Pull request merged**
