### PR TITLE
[SYCL][NFC] Use std::nullopt instead of llvm::None

### PR DESCRIPTION
**Pull request by Fznamznon**
llvm::None is deprecated and causes warnings and can cause build fails in the future.

### CODE REVIEW

**Review by AlexeySachkov — APPROVED** [review]

**Review by elizabethandrews — APPROVED** [review]
Looks ok to me. Were similar changes made in community?

**Comment by Fznamznon** [comment]
> Looks ok to me. Were similar changes made in community?

Yes, example https://github.com/llvm/llvm-project/commit/13f489e75077a49aa3b44a369eeb1e1b3998691a .

**Comment by Fznamznon** [comment]
HIP AMDGPU LLVM Test Suite failure is unrelated and is being fixed here - https://github.com/intel/llvm-test-suite/pull/1487/files

**Comment by Fznamznon** [comment]
@intel/dpcpp-devops-reviewers , why would "SYCL / Linux / Start AWS (pull_request_target)" fail? It doesn't say why.

**Review by premanandrao — APPROVED** [review]

**Review by smanna12 — APPROVED** [review]

**Review by bader — CHANGES_REQUESTED** [review]
@Fznamznon, please, resolve merge conflicts.

**Comment by Fznamznon** [comment]
> @Fznamznon, please, resolve merge conflicts.

Done.

**Review by bader — APPROVED** [review]

**Comment by bader** [comment]
> @intel/dpcpp-devops-reviewers , why would "SYCL / Linux / Start AWS (pull_request_target)" fail? It doesn't say why.

This description provides some explanation: https://github.com/intel/llvm/pull/7942#issue-1521454004

**Pull request merged**
