### PR TITLE
[CI] Switch post-commit jobs to self-hosted runners

### PR DESCRIPTION
**Pull request by alexbatashev**
Should not be a problem with the increased machine count

### CODE REVIEW

**Review by bader — APPROVED** [review]
How about switching `linux_clang_shared_libs` too?

**Comment by alexbatashev** [comment]
> How about switching `linux_clang_shared_libs` too?

Plan is to re-write it completely as part of https://github.com/intel/llvm/pull/5130

**Comment by bader** [comment]
> > How about switching `linux_clang_shared_libs` too?
> 
> Plan is to re-write it completely as part of #5130

Okay, but I must say that this exactly configuration fails on GitHub machines.

**Comment by alexbatashev** [comment]
> > > How about switching `linux_clang_shared_libs` too?
> > 
> > 
> > Plan is to re-write it completely as part of #5130
> 
> Okay, but I must say that this exactly configuration fails on GitHub machines.

Failures that I see are all build failures. They're not failing due to timeouts.

**Comment by bader** [comment]
Okay, let's see post-commit results for https://github.com/intel/llvm/commit/18df1162e613128c304f48a0e5985822741afb90. I guess it should fix the build problem you are referring to. @sergey-semenov, am I right?

**Comment by sergey-semenov** [comment]
@bader The warnings that https://github.com/intel/llvm/commit/18df1162e613128c304f48a0e5985822741afb90 addresses are part of that, but when I look at the post-commit results for the previous commit I see other warnings unrelated to that coming from the CUDA plugin: https://github.com/intel/llvm/runs/4533614173?check_suite_focus=true, so I'm pretty sure https://github.com/intel/llvm/commit/18df1162e613128c304f48a0e5985822741afb90  won't be enough.

**Comment by bader** [comment]
Thanks for clarification. I think CUDA plug-in issue is exposed by https://github.com/intel/llvm/commit/a95c12accdae52518d30d4983ab95ad6d87e77d6, which added testing of new configuration for CUDA and HIP plug-ins - with disabled assertions.

**Pull request merged**
