### PR TITLE
[Matrix][SYCL] Add bfloat16 support for joint_matrix

### PR DESCRIPTION
**Pull request by yubingex007-a11y**

### CODE REVIEW

**Comment by yubingex007-a11y** [comment]
i reopened https://github.com/intel/llvm/pull/5566 in this PR.

**Comment by yubingex007-a11y** [comment]
Are we able to run post-checkin when the patch is under review?

**Comment by steffenlarsen** [comment]
> Are we able to run post-checkin when the patch is under review?

Not as far as I know. I believe the most frequent failure difference between the pre- and post-commit testing is werror. You should be able to turn it on locally and that should hopefully help detect it before post-commit.

**Comment by yubingex007-a11y** [comment]
> > Are we able to run post-checkin when the patch is under review?
> 
> Not as far as I know. I believe the most frequent failure difference between the pre- and post-commit testing is werror. You should be able to turn it on locally and that should hopefully help detect it before post-commit.

i tried "python configure.py --werror" but can't work. however, i copied the command from compile_commands.json and add"-Werror=unused-parameter", then i can reproduce the issue in post-commit.

**Comment by yubingex007-a11y** [comment]
there is another thing in https://github.com/intel/llvm/runs/6310070794?check_suite_focus=true.
we can find that  "-Wno-unused-parameter" is used in compiling opencl.cpp but still "unused-parameter" warning is reported as error.

**Comment by mdtoguchi** [comment]
It looks like `-Wextra` is turning on `-Wunused-parameter`.  Can you move `-Wno-unused-parameter` after `-Wextra`?

**Comment by yubingex007-a11y** [comment]
> It looks like `-Wextra` is turning on `-Wunused-parameter`. Can you move `-Wno-unused-parameter` after `-Wextra`?

i can't manually move `-Wno-unused-parameter` after `-Wextra` since the command is generated by ninja
besides, if `-Wno-unused-parameter` after `-Wextra`,  `-Wno-unused-parameter` can work.

**Review by dkhaldi — APPROVED** [review]
LGTM

**Comment by yubingex007-a11y** [comment]
ping? @steffenlarsen

**Comment by steffenlarsen** [comment]
@yubingex007-a11y - Just to make sure I follow the intention of this patch. This is a reopening of https://github.com/intel/llvm/pull/5566 as it was reverted in https://github.com/intel/llvm/pull/6108. Are there any changes in this relative to https://github.com/intel/llvm/pull/5566 or were all the issues handled in https://github.com/intel/llvm/pull/6111?

**Comment by yubingex007-a11y** [comment]
> @yubingex007-a11y - Just to make sure I follow the intention of this patch. This is a reopening of #5566 as it was reverted in #6108. Are there any changes in this relative to #5566 or were all the issues handled in #6111?

all the issues were handled in #6111, and this PR carries the same patch in  #5566.

**Review by steffenlarsen — APPROVED** [review]

**Comment by yubingex007-a11y** [comment]
@steffenlarsen could you help us merge it as well?

**Pull request merged**
