### PR TITLE
[SYCL] Remove ONEAPI/INTEL namespaces

### PR DESCRIPTION
**Pull request by maximdimakov**
ONEAPI/INTEL namespaces are deprecated in SYCL 2020
This patch depends on tests : https://github.com/intel/llvm-test-suite/pull/442

### CODE REVIEW

**Review by AaronBallman — DISMISSED** [review]
FE bits look good to me, but there should be a release note about the removal.

**Review by kbobrovs — APPROVED** [review]
ESIMD part LGTM

**Comment by maximdimakov** [comment]
Jenkins/precommit is failing due to old versions of oneDPL headers. There is a permission from oneDPL team to merge this patch with failing tests.
@dm-vodopyanov @AaronBallman @kbobrovs @romanovvlad  could you, please, review?

**Review by alexbatashev — APPROVED** [review]

**Review by romanovvlad — APPROVED** [review]

**Review by AaronBallman — APPROVED** [review]
LGTM, but with a reminder about the release note request.

**Review by kbobrovs — COMMENTED** [review]
ESIMD LGTM

**Pull request merged**
