### PR TITLE
[NFC] Add bandit annotations to Python script

### PR DESCRIPTION
**Pull request by wwXing0**

### CODE REVIEW

**Comment by wwXing0** [comment]
JIRA : [CMPLRLLVM-41950](https://jira.devtools.intel.com/browse/CMPLRLLVM-41950)

**Review by elizabethandrews — COMMENTED** [review]
IIUC correctly, this change makes bandit ignore the line. I don't see an issue from compiler code review process but since this is related to security and not the compiler itself, I do not think I am the correct reviewer for this/who should be reviewing this.

**Comment by wwXing0** [comment]
@elizabethandrews, Thanks for your comment. Do you know who should review this patch? It shows "Waiting on code owner review from intel/dpcpp-cfe-reviewers"

**Comment by elizabethandrews** [comment]
I'm not sure to be honest. It shows "Waiting for intel/dpcpp-cfe-reviewers"  because you modified a frontend file. I can approve it to unblock merge but I'm not sure if that will be enough. @bader is there anyone who needs to take a look at this?

**Comment by bader** [comment]
> I am not familiar with bandit and so I do not think my review is worth anything

The same. I have concern that we put a comment to community source files.
@wwXing0, can we put this annotation to a separate file? Preferably outside of the source code base.
If possible, we should avoid modifying community files w/o a reason as add maintenance costs for our team.

**Comment by wwXing0** [comment]
@bader. I had a sync with @wphuhn-intel. Unfortunately, annotating files is the only approved way for files that we release to customers, because he need clean proof of scans for SDL.

**Pull request closed without merging**
