### PR TITLE
[SYCL] Don't use C++17 CTAD causing post-commit failures

### PR DESCRIPTION
**Pull request by againull**
Using C++17 results in post-commit failures: https://github.com/intel/llvm/actions/runs/3617075742/jobs/6095609311

### CODE REVIEW

**Review by steffenlarsen — APPROVED** [review]

**Comment by romanovvlad** [comment]
HIP failures are unrelated.

**Comment by keryell** [comment]
I think I was the culprit for this CTAD suggestion... But SYCL 2020 requires C++17!

**Comment by aelovikov-intel** [comment]
CTAD support is still imperfect in compilers we use. We have internal testing with "-fsycl-use-host-compiler=cl"  (MSVC) that results in CTAD-related issues for `sycl::accessor`, unless `/std:c++latest` is used (and fails in `/std:c++17` mode).

**Comment by keryell** [comment]
Ok, I guess this is a bug in MacOS Xcode 14 and their C++ library. :-(

**Pull request merged**
