### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW38 2024)

### PR DESCRIPTION
**Pull request by iclsrc**
LLVM: llvm/llvm-project@34b10e165d809bb133d37dfe934859800f21a100
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@dc1221cd83e67ef

### CODE REVIEW

**Comment by jsji** [comment]
This is ready for merge. Two reverts in SPIRV are being tracked in internal issue 62002 assigned to @vmaksimo , will reland once it is fixed.

@intel/llvm-gatekeepers  Can we get this merged. Thanks.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Mon 23 Sep 2024 11:41:52 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Mon 23 Sep 2024 11:46:40 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
