### PR TITLE
Add extension proposal for an interop API with ownership handling

### PR DESCRIPTION
**Pull request by t4c1**
Add extension proposal for an interop API with ownership handling. Such API allows to specify in each interop function whether to keep or transfer ownership of the backend object in each interop function.

### CODE REVIEW

**Comment by t4c1** [comment]
> However, I would rather address this by relaxing the proscriptive language in the core SYCL 2020 specification.

We do intend this extension as a temporary solution, until we propose this for the SYCL next specification.

> However, we have since learned that different backends have different requirements for these arguments. This "ownership" flag seems like just one example.

This does not remove the need for detailing the interface in the backend specification. However we do feel this is something all backends that do not natively reference count their objects have in common. 

Allowing backends to specify complete interface of the interop functions could be an alternative solution. However that would require a more intrusive change in the SYCL specification and it would remove the ability to use template traits to specify arguments to interop functions.

> For example, the application can never take ownership of the native handle for a root device object because the runtime caches a copy of these objects internally for the entire duration of the application.

That is a very good point. Due to how the same set of platforms and devices must exist for the entire run time of the application, transferring ownership of these when calling `get_native()` does not make sense. I believe this issue can be avoided by not providing this interface for platform and device types.

However we do not feel that strongly about this extension. We would also be ok with finding an alternative solution for this problem.

**Comment by gmlueck** [comment]
My preference would be to not add this oneAPI extension until we get these issues with the core SYCL spec sorted out.  It's not clear to me that exposing as common "ownership" flag is the right direction.  If we want a short-term solution for the CUDA backend, I'd rather pass a struct with an "ownership" flag as we do with the Level Zero interop API.  We need that anyways in order to be conformant to the existing SYCL 2020 specification.

Regarding adding an "ownership" flag to `get_native()`, I feel generally uneasy about this.  Do we have some use-case that requires this?  I think the safer option is to always assume that the SYCL implementation retains ownership of the native handles for all SYCL objects, unless that SYCL object was specifically created with the `make_OBJECT()` interop API.

If we feel there is a general need to transfer ownership with `get_native()`, then I think the backend interop spec needs to provide some strict guarantees on the lifetime of a SYCL object.  In essence, we need to forbid the implementation from keeping a reference to any SYCL object when the application does not also have a reference.  I'm not sure if this is currently the case with the DPC++ implementation.

**Comment by npmiller** [comment]
> However, we have since learned that different backends have different requirements for these arguments. This "ownership" flag seems like just one example.

I do feel like there is a slight difference with the ownership flag because it instructs the SYCL runtime beyond just the creation of the SYCL object. But I suppose looking at it from a different angle dictating how backend objects must be cleaned up by the SYCL runtime also makes sense to leave in the scope of the backend spec.

> I think a better solution would be to change the core SYCL specification to remove any description of the arguments to the interop functions.

That's a very interesting suggestion, it does require more details in the backend specs and makes the interop interface less uniform across backends, but then again it already differs because of the types and is already non standard SYCL code as defined by the spec. It does seem like the idea of a single native handle the interop API is built around doesn't really match the level zero or cuda backends.

> Because many SYCL objects have "common reference semantics", the application can never be sure that all references to these objects have been dropped. Therefore, there's no safe point at which the application can destroy the native handle.

That's a really good point, although it makes me wonder, does it not also apply to `make_native` with `ownership::keep` then? It ends up in the same scenario where the user as no way to know if the SYCL runtime has dropped all references to their backend object. This would essentially mean that the only safe solution is `ownership::transfer`.

> My preference would be to not add this oneAPI extension until we get these issues with the core SYCL spec sorted out.

After reading through the discussion carefully again I think that makes sense.

If you're happy with that as well @t4c1 I'm okay to drop this and stick with the struct approach for now, and maybe we can start considering more comprehensive interop changes for the SYCL spec to reflect the experience of working on non-OpenCL backend.

**Comment by t4c1** [comment]
We have decided for a different approach to this.

**Pull request closed without merging**
