### PR TITLE
[libclc][NFC] Refactor generic AS checks into common define

### PR DESCRIPTION
**Pull request by frasercrmck**

### CODE REVIEW

**Review by bader — APPROVED** [review]
> One worry with this approach might be that it's now easier to accidentally miss a generic AS definition by not including the common header that defines the common macro.

You can address this by checking the value of the macro:
```c++
#if __OPENCL_C_VERSION__ == CL_VERSION_2_0 ||                                  \
    (__OPENCL_C_VERSION__ >= CL_VERSION_3_0 &&                                 \
     defined(__opencl_c_generic_address_space))
  #define _CLC_GENERIC_AS_SUPPORTED 1
#else
  #define _CLC_GENERIC_AS_SUPPORTED 0
#endif

#if _CLC_GENERIC_AS_SUPPORTED
_CLC_OVERLOAD _CLC_DECL __CLC_GENTYPE fract(__CLC_GENTYPE x, generic __CLC_GENTYPE *iptr);
#endif
```
`if _CLC_GENERIC_AS_SUPPORTED` will give you an error if `_CLC_GENERIC_AS_SUPPORTED` value is not set.

Please, add [NFC] tag to PR title.

**Comment by frasercrmck** [comment]
> > One worry with this approach might be that it's now easier to accidentally miss a generic AS definition by not including the common header that defines the common macro.
> 
> You can address this by checking the value of the macro:
> 
> ```c++
> #if __OPENCL_C_VERSION__ == CL_VERSION_2_0 ||                                  \
>     (__OPENCL_C_VERSION__ >= CL_VERSION_3_0 &&                                 \
>      defined(__opencl_c_generic_address_space))
>   #define _CLC_GENERIC_AS_SUPPORTED 1
> #else
>   #define _CLC_GENERIC_AS_SUPPORTED 0
> #endif
> 
> #if _CLC_GENERIC_AS_SUPPORTED
> _CLC_OVERLOAD _CLC_DECL __CLC_GENTYPE fract(__CLC_GENTYPE x, generic __CLC_GENTYPE *iptr);
> #endif
> ```
> 
> `if _CLC_GENERIC_AS_SUPPORTED` will give you an error if `_CLC_GENERIC_AS_SUPPORTED` value is not set.
> 
> Please, add [NFC] tag to PR title.

Good idea, done. Thank you - not sure why I didn't think of that.

**Review by jchlanda — APPROVED** [review]

**Review by steffenlarsen — APPROVED** [review]
Great! Thanks for remembering. 😉

**Comment by jchlanda** [comment]
> > > One worry with this approach might be that it's now easier to accidentally miss a generic AS definition by not including the common header that defines the common macro.
> > 
> > 
> > You can address this by checking the value of the macro:
> > ```c++
> > #if __OPENCL_C_VERSION__ == CL_VERSION_2_0 ||                                  \
> >     (__OPENCL_C_VERSION__ >= CL_VERSION_3_0 &&                                 \
> >      defined(__opencl_c_generic_address_space))
> >   #define _CLC_GENERIC_AS_SUPPORTED 1
> > #else
> >   #define _CLC_GENERIC_AS_SUPPORTED 0
> > #endif
> > 
> > #if _CLC_GENERIC_AS_SUPPORTED
> > _CLC_OVERLOAD _CLC_DECL __CLC_GENTYPE fract(__CLC_GENTYPE x, generic __CLC_GENTYPE *iptr);
> > #endif
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `if _CLC_GENERIC_AS_SUPPORTED` will give you an error if `_CLC_GENERIC_AS_SUPPORTED` value is not set.
> > Please, add [NFC] tag to PR title.
> 
> Good idea, done. Thank you - not sure why I didn't think of that.

This is exactly what I woke up this morning to say :)

**Comment by frasercrmck** [comment]
@intel/llvm-gatekeepers this looks good to merge, thanks

**Pull request merged**
