### PR TITLE
[SYCL][ESIMD][EMU] Remove obsolete patching.

### PR DESCRIPTION
**Pull request by lsatanov**

### CODE REVIEW

**Review by dongkyunahn-intel — APPROVED** [review]

**Comment by lsatanov** [comment]
Hi. Logging-related patching is not necessary for recent variant of CM EMU.
This patch removes it.

**Review by dongkyunahn-intel — APPROVED** [review]

**Comment by lsatanov** [comment]
Hi, people. Can we merge this one?

**Review by kbobrovs — APPROVED** [review]

**Comment by kbobrovs** [comment]
@smaslov-intel, please review/approve

**Comment by kbobrovs** [comment]
@smaslov-intel , ping

**Comment by bader** [comment]
> @smaslov-intel , ping

I suggest we make @intel/dpcpp-esimd-reviewers team the code owner of esimd_emulator plug-in.

**Comment by bader** [comment]
@lsatanov, could you resolve merge conflicts, please?

**Comment by dongkyunahn-intel** [comment]
This PR is no longer valid as CM_EMU library package is updated and this CMake file is updated accordingly - https://github.com/intel/llvm/pull/6027.

**Pull request closed without merging**
