### PR TITLE
[UR][L0] Enable Immediate Command List by default given Intel DG2

### PR DESCRIPTION
**Pull request by nrspruit**
-pre-commit PR for https://github.com/oneapi-src/unified-runtime/pull/1951

### CODE REVIEW

**Comment by sarnex** [comment]
@nrspruit sorry i just happened to see notice PR and I know it's a still draft, but since this looks like a DG2 specific change, DG2 testing isn't run in precommit besides trivial matrix tests. if you want to do full testing we need to run postcommit as part of PR testing, which you can do by creating a branch in intel/llvm prefixed with `sycl-devops-pr/` and making a PR from there.

**Comment by nrspruit** [comment]
> Member

devops PR here:
https://github.com/intel/llvm/pull/15053

**Comment by sarnex** [comment]
Thanks, looks like postcommit is running there as expected!

**Review by omarahmed1111 — APPROVED** [review]

**Comment by omarahmed1111** [comment]
@intel/llvm-gatekeepers Please merge, Thanks!

**Comment by omarahmed1111** [comment]
This will be included in this [PR](https://github.com/intel/llvm/pull/15105)

**Pull request closed without merging**
