### PR TITLE
[BuildBot] Uplift GPU RT version for Linux CI Process

### PR DESCRIPTION
**Pull request by bb-sycl**
Uplift GPU RT version for Linux to 21.11.19310

### CODE REVIEW

**Review by smaslov-intel — APPROVED** [review]

**Review by smaslov-intel — APPROVED** [review]

**Review by bader — CHANGES_REQUESTED** [review]
Please, pass pre-commit validation.

**Comment by yanfeng3721** [comment]
Need to remove llvm-test-suite "//XFAIL: level_zero" for ESIMD test, and "//XFAIL:*" for InlineAsm test after https://github.com/intel/llvm/pull/3386 is merged.

@vladimirlaz, could you please help to update the llvm-test-suite once PR3386 is merged? Thanks.

**Comment by vladimirlaz** [comment]
> The following 4 tests unexpected pass on level_zero:gpu
> SYCL :: ESIMD/spec_const/spec_const_char.cpp
> SYCL :: ESIMD/spec_const/spec_const_short.cpp
> SYCL :: ESIMD/spec_const/spec_const_uchar.cpp
> SYCL :: ESIMD/spec_const/spec_const_ushort.cpp
> The following 2 tests unexpected pass on level_zero:gpu/opencl:gpu
> SYCL :: InlineAsm/asm_loop.cpp
> SYCL :: InlineAsm/asm_switch.cpp
> 
> Need to remove llvm-test-suite "//XFAIL: level_zero" for ESIMD test, and "//XFAIL:*" for InlineAsm test after #3386 is merged.
> 
> @vladimirlaz, could you please help to update the llvm-test-suite before/after PR3386 is merged? Thanks.

@yanfeng3721, can you do it yourself? It is quite trivial change

**Comment by yanfeng3721** [comment]
> > The following 4 tests unexpected pass on level_zero:gpu
> > SYCL :: ESIMD/spec_const/spec_const_char.cpp
> > SYCL :: ESIMD/spec_const/spec_const_short.cpp
> > SYCL :: ESIMD/spec_const/spec_const_uchar.cpp
> > SYCL :: ESIMD/spec_const/spec_const_ushort.cpp
> > The following 2 tests unexpected pass on level_zero:gpu/opencl:gpu
> > SYCL :: InlineAsm/asm_loop.cpp
> > SYCL :: InlineAsm/asm_switch.cpp
> > Need to remove llvm-test-suite "//XFAIL: level_zero" for ESIMD test, and "//XFAIL:*" for InlineAsm test after #3386 is merged.
> > @vladimirlaz, could you please help to update the llvm-test-suite before/after PR3386 is merged? Thanks.
> 
> @yanfeng3721, can you do it yourself? It is quite trivial change

@vladimirlaz ,sure. I have prepared a PR https://github.com/intel/llvm-test-suite/pull/193, could you please help to review? Thanks.

**Comment by bader** [comment]
https://github.com/intel/llvm-test-suite/pull/193 is merge. Could you restart pre-commit testing to confirm that it passes now, please?

**Review by yanfeng3721 — DISMISSED** [review]

**Comment by bader** [comment]
It look like L0 loader update broke `sycl-ls` tool on Windows. 
Does it require Windows drivers update too?

**Comment by yanfeng3721** [comment]
@bader , yes, sycl-ls crash with the following error info:
Unhandled exception at 0x00007FF845919129 in sycl-ls.exe: Microsoft C++ exception: cl::sycl::runtime_error at memory location 0x000000084A98F650.

**Comment by bader** [comment]
> @bader , yes, sycl-ls crash with the following error info:
> Unhandled exception at 0x00007FF845919129 in sycl-ls.exe: Microsoft C++ exception: cl::sycl::runtime_error at memory location 0x000000084A98F650.

@intel/llvm-reviewers-runtime, FYI.

**Comment by yanfeng3721** [comment]
Hi @bader @smaslov-intel , the regression detected in llvm-test-suites is gone, but the sycl-ls check in buildbot/sycl-win-x64-pr is still failed, and the backtrace of the failures is quite the same. May I ask if there is any change has been made during the past few days to resolve the regression? Thanks. 
`Exp run 3 case(s) failed. Failed case(s): [SYCL :: Plugin/sycl-ls-gpu-default.cpp, SYCL :: Plugin/sycl-ls-gpu-level-zero.cpp, SYCL :: Plugin/sycl-ls.cpp]`

**Comment by yanfeng3721** [comment]
> > @bader , yes, sycl-ls crash with the following error info:
> > Unhandled exception at 0x00007FF845919129 in sycl-ls.exe: Microsoft C++ exception: cl::sycl::runtime_error at memory location 0x000000084A98F650.
> 
> @intel/llvm-reviewers-runtime, FYI.

Hi @bader @smaslov-intel , the regression detected in llvm-test-suites is gone, but the sycl-ls check in buildbot/sycl-win-x64-pr is still failed, and the backtrace of the failures is quite the same. May I ask if there is any change has been made during the past few days to resolve the regression? Thanks.
Exp run 3 case(s) failed. Failed case(s): [SYCL :: Plugin/sycl-ls-gpu-default.cpp, SYCL :: Plugin/sycl-ls-gpu-level-zero.cpp, SYCL :: Plugin/sycl-ls.cpp]

**Comment by smaslov-intel** [comment]
> May I ask if there is any change has been made during the past few days to resolve the regression?

I am not aware of any changes that were done to resolve this.

> sycl-ls crash with the following error info:
Unhandled exception at 0x00007FF845919129 in sycl-ls.exe: Microsoft C++ exception: cl::sycl::runtime_error at memory location 0x000000084A98F650.

@againull does it bell any rings to you?

**Comment by yanfeng3721** [comment]
> > May I ask if there is any change has been made during the past few days to resolve the regression?
> 
> I am not aware of any changes that were done to resolve this.
> 
> > sycl-ls crash with the following error info:
> > Unhandled exception at 0x00007FF845919129 in sycl-ls.exe: Microsoft C++ exception: cl::sycl::runtime_error at memory location 0x000000084A98F650.
> 
> @againull does it bell any rings to you?

Is the following information helpful?

> ---> piPlatformsGet(
>         <unknown> : 0
>         <nullptr>
>         <unknown> : 000000C7A258F9A8
> ) --->  pi_result : -999

**Comment by smaslov-intel** [comment]
> ---> piPlatformsGet(
> : 0
> 
> : 000000C7A258F9A8
> ) ---> pi_result : -999

Yeah, it looks like `zeInit` call to initialize Level-Zero driver failed for unknown reason. Are you testing with compatible loader & driver? Which versions? How to reproduce this locally?

**Comment by againull** [comment]
> > May I ask if there is any change has been made during the past few days to resolve the regression?
> 
> I am not aware of any changes that were done to resolve this.
> 
> > sycl-ls crash with the following error info:
> > Unhandled exception at 0x00007FF845919129 in sycl-ls.exe: Microsoft C++ exception: cl::sycl::runtime_error at memory location 0x000000084A98F650.
> 
> @againull does it bell any rings to you?

Sorry, unfortunately I don't know root cause from the top of my head, needs investigation.

**Comment by smaslov-intel** [comment]
FWIW, https://github.com/intel/llvm/pull/3470 is going to make SYCL RT to handles more gracefully plugin initialization failure.

**Comment by yanfeng3721** [comment]
> FWIW, #3470 is going to make SYCL RT to handles more gracefully plugin initialization failure.

@sergey-semenov , thanks for the fix. The crash issue is not reproduce any more. But the sycl-ls check is still failed due to unable to find L0GPU device. It looks like some binary is missing in ~\llvm\build\install\bin folder, because the sycl-ls check can pass if I run it from ~\llvm\build\bin fodler.
Unexpected failure
`D:\iusers\yanfeng1\SYCLOS\sycl_workspace_new\llvm\build\install>D:\iusers\yanfeng1\SYCLOS\sycl_workspace_new\llvm\build\install\bin\sycl-ls.exe --verbose
Platforms: 1
Platform [#1]:
    Version  : OpenCL 3.0
    Name     : Intel(R) OpenCL HD Graphics
    Vendor   : Intel(R) Corporation
    Devices  : 1
        Device [#0]:
        Type       : GPU
        Version    : 3.0
        Name       : Intel(R) UHD Graphics 630
        Vendor     : Intel(R) Corporation
        Driver     : 27.20.100.9030
default_selector()      : GPU : Intel(R) OpenCL HD Graphics 3.0 [27.20.100.9030]
host_selector()         : No device of requested type available. -1 (CL_DEVI...
accelerator_selector()  : No device of requested type available. -1 (CL_DEVI...
cpu_selector()          : No device of requested type available. -1 (CL_DEVI...
gpu_selector()          : GPU : Intel(R) OpenCL HD Graphics 3.0 [27.20.100.9030]
custom_selector(gpu)    : GPU : Intel(R) OpenCL HD Graphics 3.0 [27.20.100.9030]
custom_selector(cpu)    : No device of requested type available. -1 (CL_DEVI...
custom_selector(acc)    : No device of requested type available. -1 (CL_DEVI...`

Expected pass
`D:\iusers\yanfeng1\SYCLOS\sycl_workspace_new\llvm\build\install>D:\iusers\yanfeng1\SYCLOS\sycl_workspace_new\llvm\build\bin\sycl-ls.exe --verbose
Platforms: 3
Platform [#1]:
    Version  : OpenCL 3.0
    Name     : Intel(R) OpenCL HD Graphics
    Vendor   : Intel(R) Corporation
    Devices  : 1
        Device [#0]:
        Type       : GPU
        Version    : 3.0
        Name       : Intel(R) UHD Graphics 630
        Vendor     : Intel(R) Corporation
        Driver     : 27.20.100.9030
Platform [#2]:
    Version  : 1.0
    Name     : Intel(R) Level-Zero
    Vendor   : Intel(R) Corporation
    Devices  : 1
        Device [#1]:
        Type       : GPU
        Version    : 1.0
        Name       : Intel(R) Graphics Gen9 [0x3e92]
        Vendor     : Intel(R) Corporation
        Driver     : 1.0.0
Platform [#3]:
    Version  : 1.2
    Name     : SYCL host platform
    Vendor   :
    Devices  : 1
        Device [#2]:
        Type       : HOST
        Version    : 1.2
        Name       : SYCL host device
        Vendor     :
        Driver     : 1.2
default_selector()      : GPU : Intel(R) Level-Zero 1.0 [1.0.0]
host_selector()         : HOST: SYCL host platform 1.2 [1.2]
accelerator_selector()  : No device of requested type available. -1 (CL_DEVI...
cpu_selector()          : No device of requested type available. -1 (CL_DEVI...
gpu_selector()          : GPU : Intel(R) Level-Zero 1.0 [1.0.0]
custom_selector(gpu)    : GPU : Intel(R) Level-Zero 1.0 [1.0.0]
custom_selector(cpu)    : No device of requested type available. -1 (CL_DEVI...
custom_selector(acc)    : No device of requested type available. -1 (CL_DEVI...`

**Comment by yanfeng3721** [comment]
@bader @sergey-semenov , the latest public Windows igfx driver igfx_win10_100.9316( https://downloadcenter.intel.com/download/30266/Intel-Graphics-Windows-10-DCH-Drivers) is not compatible with L0 Loader 1.2.3. 
Do you have any suggestion to unblock the current regular  GPU RT version uplift? 
Since Linux GPU RT version >=21.11.19310 requires L0 loader 1.2.3(otherwise there will be a lot of regression), could we skip the sycl-ls check in buildbot/sycl-win-x64-pr?  I expect other tests in pre-commit test and post commit test will not blocked by L0 loader init failure, since the L0 loader is actually loaded from pre installed Windows igfx drivers.

**Comment by bader** [comment]
> @bader @sergey-semenov , the latest public Windows igfx driver igfx_win10_100.9316( https://downloadcenter.intel.com/download/30266/Intel-Graphics-Windows-10-DCH-Drivers) is not compatible with L0 Loader 1.2.3.
> Do you have any suggestion to unblock the current regular GPU RT version uplift?
> Since Linux GPU RT version >=21.11.19310 requires L0 loader 1.2.3(otherwise there will be a lot of regression), could we skip the sycl-ls check in buildbot/sycl-win-x64-pr? I expect other tests in pre-commit test and post commit test will not blocked by L0 loader init failure, since the L0 loader is actually loaded from pre installed Windows igfx drivers(v1.1.0).

Does L0 loader update break `sycl-ls` only? If so, I suggest fixing `sycl-ls` if possible.
I have concerns that this is the case because there are failures in llvm-test-suite and there no results for `check-sycl` on Windows.

We might consider using different L0 loader version on Windows as a back-up plan.

**Comment by smaslov-intel** [comment]
> Does L0 loader update break `sycl-ls` only? If so, I suggest fixing `sycl-ls` if possible.

There is nothing in `sycl-ls` that can fix this. 

> We might consider using different L0 loader version on Windows as a back-up plan.

Please consider uplifting the Level-Zero driver along with th1 v1.2.3. loader.

**Comment by bader** [comment]
> Please consider uplifting the Level-Zero driver along with th1 v1.2.3. loader.

Do you have a link to the driver we can use?
According to [this comment](https://github.com/intel/llvm/pull/3386#issuecomment-816528260) there is no such driver!

**Comment by yanfeng3721** [comment]
> > Please consider uplifting the Level-Zero driver along with th1 v1.2.3. loader.
> 
> Do you have a link to the driver we can use?
> According to [this comment](https://github.com/intel/llvm/pull/3386#issuecomment-816528260) there is no such driver!

Can we add some logic to handle L0 Loader version by OS? There currently is no release windows gpu driver that supports v1.1 of the L0 Specification, but Linux does.

**Review by vladimirlaz — APPROVED** [review]
LGTM

**Review by smaslov-intel — APPROVED** [review]
LGTM

**Comment by yanfeng3721** [comment]
The sycl-ls check can pass on Windows now. 
The following 6 tests unexpected pass can be resolved by https://github.com/intel/llvm-test-suite/pull/193/.
Hi @vladimirlaz , could you please to merge this PR and https://github.com/intel/llvm-test-suite/pull/193 at the same time? Thanks!

**Review by bader — APPROVED** [review]

**Comment by bader** [comment]
> The sycl-ls check can pass on Windows now.
> The following 6 tests unexpected pass can be resolved by [intel/llvm-test-suite#193](https://github.com/intel/llvm-test-suite/pull/193).
> Hi @vladimirlaz , could you please to merge this PR and [intel/llvm-test-suite#193](https://github.com/intel/llvm-test-suite/pull/193) at the same time? Thanks!

@yanfeng3721, @vladimirlaz, please, open another PR to update llvm-test-suite tests -  https://github.com/intel/llvm-test-suite/pull/193 is already merged.

**Comment by vladimirlaz** [comment]
> > The sycl-ls check can pass on Windows now.
> > The following 6 tests unexpected pass can be resolved by [intel/llvm-test-suite#193](https://github.com/intel/llvm-test-suite/pull/193).
> > Hi @vladimirlaz , could you please to merge this PR and [intel/llvm-test-suite#193](https://github.com/intel/llvm-test-suite/pull/193) at the same time? Thanks!
> 
> @yanfeng3721, @vladimirlaz, please, open another PR to update llvm-test-suite tests - [intel/llvm-test-suite#193](https://github.com/intel/llvm-test-suite/pull/193) is already merged.

it is misprint: https://github.com/intel/llvm-test-suite/pull/232 should be used instead

**Comment by bader** [comment]
> Hi @vladimirlaz , could you please to merge this PR and [intel/llvm-test-suite#193](https://github.com/intel/llvm-test-suite/pull/193) at the same time? Thanks!

@vladimirlaz, ping.

**Pull request merged**
