### PR TITLE
[GHA] Uplift Linux IGC Dev RT version to igc-dev-15caa46

### PR DESCRIPTION
**Pull request by bb-sycl**
Scheduled igc dev drivers uplift

### CODE REVIEW

**Review by sarnex — APPROVED** [review]
LGTM but I hope we have a tracker for IGC to fix the root problem

**Comment by jsji** [comment]
> LGTM but I hope we have a tracker for IGC to fix the root problem

Thanks @sarnex . I had a look at the issue, the problem should be in how they build the dev igc in the CI. If I build the igc myself, the test pass.  And they build the *release* packaged differently.. :( 
So I would think this is a somehow limitation of how dev igc was build in the CI.
But sure, I will open an issue to track it.

**Comment by sarnex** [comment]
I wonder why it's only one test if it's a build issue, that seems really weird

**Comment by jsji** [comment]
> I wonder why it's only one test if it's a build issue, that seems really weird

Yes, it is weird to me too. Maybe it is somehow specific the API used in hardware_dispatch.cpp ?

**Review by sergey-semenov — APPROVED** [review]

**Comment by jsji** [comment]
@intel/llvm-gatekeepers Can someone help to merge this. Thanks.

**Pull request merged**
