### PR TITLE
[DeviceSanitizer] Disable handling no return calls

### PR DESCRIPTION
**Pull request by zhaomaosu**
'__asan_handle_no_return' is used to unpoison stack before non return calls.
And we didn't poison stack in device code, so we don't need to handle such
case.

### CODE REVIEW

**Comment by zhaomaosu** [comment]
> lgtm, but should have a test maybe?

sure, added.

**Review by yingcong-wu — APPROVED** [review]

**Comment by AllanZyne** [comment]
Can you add a brief description on why disable instrumentation on no return calls?
Thanks!

**Comment by zhaomaosu** [comment]
> Can you add a brief description on why disable instrumentation on no return calls? Thanks!

Done.

**Review by AllanZyne — APPROVED** [review]

**Comment by zhaomaosu** [comment]
Hi @intel/llvm-gatekeepers, could you please help merge this PR. Thanks.

**Pull request merged**
