### PR TITLE
[SYCL][NFC] Fix SYCL lit test execution on a system w/o GPU

### PR DESCRIPTION
**Pull request by bader**
This should fix post-commit failures introduced by #2492.

### CODE REVIEW

**Comment by bader** [comment]
@v-klochkov, @cperkinsintel, I'm going to merge this w/o review to fix LIT tests in post-commit job.
Feel free to leave your comments - I'll address them in a separate PR.

**Comment by cperkinsintel** [comment]
What is the difference between %GPU_CHECK_PLACEHOLDER% and piping to FileCheck?  Just convention?
I think the oversight is that I should have put CPU and ACC test lines in there for completeness .

**Comment by bader** [comment]
> What is the difference between %GPU_CHECK_PLACEHOLDER% and piping to FileCheck? Just convention?

%GPU_CHECK_PLACEHOLDER replaced with an empty line if test system doesn't have GPU device. 
%GPU_RUN_PLACEHOLDER is replaced with `true` on the system with GPU, so we should avoid running FileCheck in this case.
The replacement logic is implemented here: https://github.com/intel/llvm/blob/sycl/sycl/test/lit.cfg.py#L148

> I think the oversight is that I should have put CPU and ACC test lines in there for completeness .

Feel free to add them.

**Comment by cperkinsintel** [comment]
> Feel free to add them.
done.
https://github.com/intel/llvm/pull/2589/files

**Pull request merged**
