### PR TITLE
[SYCL] Fix handler::set_arg for local_accessor

### PR DESCRIPTION
**Pull request by AlexeySachkov**
Added missing `setArgHelper` overload for `local_accessor`.

### CODE REVIEW

**Comment by AlexeySachkov** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1367

**Review by steffenlarsen — APPROVED** [review]
LGTM!

**Comment by AlexeySachkov** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1367

**Comment by AlexeySachkov** [comment]
Failures in `llvm-test-suite` are not related to the changes, I will merge this and try to investigate and/or temporary disable some tests

**Comment by pvchupin** [comment]
@AlexeySachkov, please follow up on post commit issue: https://github.com/intel/llvm/actions/runs/3423451915/jobs/5702059148

```
??$get_info@Uparent_device@device@info@_V1@sycl@@@device@_V1@sycl@@QEBA?AV012@XZ
```

**Comment by steffenlarsen** [comment]
> @AlexeySachkov, please follow up on post commit issue: https://github.com/intel/llvm/actions/runs/3423451915/jobs/5702059148
> 
> ```
> ?setLocalAccessorArgHelper@handler@_V1@sycl@@AEAAXHAEAVLocalAccessorBaseHost@detail@23@@Z
> ```

Added in https://github.com/intel/llvm/pull/7331

**Pull request merged**
