### PR TITLE
[SYCL] Clean `-Wcomment` warning

### PR DESCRIPTION
**Pull request by aelovikov-intel**
Fixes https://github.com/intel/llvm/issues/15063.

### CODE REVIEW

**Review by maarquitos14 — APPROVED** [review]

**Comment by AlexeySachkov** [comment]
We have a test for warnings coming out of our headers: [`sycl/test/warnings/warnings.cpp`](https://github.com/intel/llvm/blob/sycl/sycl/test/warnings/warnings.cpp), but it didn't help in this case. Do you know if we can maybe do some updates to it to prevent cases like this happen in the future?

I've tried locally to add `-Wcomment` in there, but it didn't work.
I wonder if we need to run that test with `gcc` as well to have a better coverage.

**Comment by dvrogozh** [comment]
> I wonder if we need to run that test with gcc as well to have a better coverage.

Yes, you need gcc as host compiler and use `-Wall`. The following reproduces the warning on my side on ubuntu 22.04:
```
$ cat a.cpp
#include <sycl/sycl.hpp>
int main(int argc, char** argv) {}

$ PATH=build/install/bin/:$PATH LD_LIBRARY_PATH=build/install/lib clang-19 -fsycl -fsycl-host-compiler=g++ -fsycl-host-compiler-options="-Wall" ~/tmp/a.cpp
In file included from /home/dvrogozh/git/llvm/build/install/bin/../include/sycl/builtins.hpp:13,
                 from /home/dvrogozh/git/llvm/build/install/bin/../include/sycl/detail/image_accessor_util.hpp:17,
                 from /home/dvrogozh/git/llvm/build/install/bin/../include/sycl/accessor_image.hpp:4,
                 from /home/dvrogozh/git/llvm/build/install/bin/../include/sycl/sycl.hpp:13,
                 from /home/dvrogozh/tmp/a.cpp:1:
/home/dvrogozh/git/llvm/build/install/bin/../include/sycl/detail/builtins/builtins.hpp:235:1: warning: multi-line comment [-Wcomment]
  235 | // clang++ -[DU]__SYCL_DEVICE_ONLY__ -x c++ math_functions.inc  \
      | ^

$ g++ --version
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by aelovikov-intel** [comment]
> I wonder if we need to run that test with gcc as well to have a better coverage.

I wouldn't expect our headers to be warning-clean in that scenario even after this PR. IMO, that should be a separate activity to craft a working test and then to clean all of the warnings it will detect.

**Comment by AlexeySachkov** [comment]
> > I wonder if we need to run that test with gcc as well to have a better coverage.
> 
> I wouldn't expect our headers to be warning-clean in that scenario even after this PR. IMO, that should be a separate activity to craft a working test and then to clean all of the warnings it will detect.

No objections to that, I've submitted #15081 to follow-up

**Pull request merged**
