### PR TITLE
[CI] Don't restrict pre-commit for PRs from inside the repo

### PR DESCRIPTION
**Pull request by aelovikov-intel**
If the PR's source branch is already inside `origin` then it is known to be safe.

### CODE REVIEW

**Comment by aelovikov-intel** [comment]
Tested in https://github.com/intel/llvm/pull/10441/checks.

**Comment by bader** [comment]
> Tested in https://github.com/intel/llvm/pull/10441/checks.

You use `sycl-devops-pr` prefix for your test branch and we already allow running modified scripts for them. Right?

**Comment by aelovikov-intel** [comment]
> > Tested in https://github.com/intel/llvm/pull/10441/checks.
> 
> You use `sycl-devops-pr` prefix for your test branch and we already allow running modified scripts for them. Right?

Yes, it's been described in PR/commit message for https://github.com/intel/llvm/pull/10002.

**Comment by bader** [comment]
> > > Tested in https://github.com/intel/llvm/pull/10441/checks.
> > 
> > 
> > You use `sycl-devops-pr` prefix for your test branch and we already allow running modified scripts for them. Right?
> 
> Yes, it's been described in PR/commit message for #10002.

Right. I don't think https://github.com/intel/llvm/pull/10441/checks really checks this change.

**Review by bader — APPROVED** [review]

**Pull request merged**
