### PR TITLE
[SYCL][joint matrix] Add col major case to prefetch and correct the VNNI case

### PR DESCRIPTION
**Pull request by dkhaldi**
Clarification to the spec is added in https://github.com/intel/llvm/pull/13796

### CODE REVIEW

**Comment by dkhaldi** [comment]
@fda0, please use this updated test for the VNNI and column major cases.

**Review by YuriPlyakhin — APPROVED** [review]
LGTM

**Comment by dkhaldi** [comment]
@intel/llvm-gatekeepers, please help merge this.

**Comment by aelovikov-intel** [comment]
> @intel/llvm-gatekeepers, please help merge this.

image

**Comment by dkhaldi** [comment]
@aelovikov-intel, checks should be done now. Please help merge this.

**Pull request merged**
