### PR TITLE
Add missing LIT test after pulldown from community

### PR DESCRIPTION
**Pull request by zahiraam**
After community pulldown of https://github.com/llvm/llvm-project/commit/627868263cd4 the LIT test associated to the patch didn't get to be added (or might have been deleted inadvertently. This patch is to add back the LIT test.

### CODE REVIEW

**Review by elizabethandrews — DISMISSED** [review]

**Review by smanna12 — DISMISSED** [review]

**Review by smanna12 — APPROVED** [review]

**Comment by zahiraam** [comment]
These fails are not related to the changes in this patch. @bader can this patch be merged in? Thanks.

**Comment by bader** [comment]
Jenkins/Precommit job is required, so it doesn't block the merge. @intel/dpcpp-esimd-reviewers, please, investigate multiple ESIMD test failures.

Testing on CUDA is required, so we need this check to pass to unblock the merge.
@tfzhu, it looks like there is no space left on the machine. Could you fix it, please?
Meanwhile, @zahiraam, please, try restarting the CUDA job.

**Comment by bader** [comment]
@tfzhu, I've paused broken worker.

**Comment by bader** [comment]
> After community pulldown of [llvm/llvm-project@6278682](https://github.com/llvm/llvm-project/commit/627868263cd4) the LIT test associated to the patch didn't get to be added (or might have been deleted inadvertently. This patch is to add back the LIT test.

I see a lot of changes not related to missing lit test.

**Pull request closed without merging**
