### PR TITLE
[UR][L0] Upgrade L0 loader to v1.15.1

### PR DESCRIPTION
**Pull request by jandres742**
This to use latest features present in L0 spec.

### CODE REVIEW

**Comment by jandres742** [comment]
@smaslov-intel : please review

**Comment by jandres742** [comment]
@smaslov-intel : I need this for several new features in L0 spec. is it ok to upgrade the L0 loader here in the intel/llvm? I'm upgrading it in the UR L0 adapter here https://github.com/oneapi-src/unified-runtime/pull/1061

**Comment by smaslov-intel** [comment]
> @smaslov-intel : I need this for several new features in L0 spec. is it ok to upgrade the L0 loader here in the intel/llvm? I'm upgrading it in the UR L0 adapter here [oneapi-src/unified-runtime#1061](https://github.com/oneapi-src/unified-runtime/pull/1061)

I think we should then also update the L0 loader that is used in CI testing.

**Comment by jandres742** [comment]
> > @smaslov-intel : I need this for several new features in L0 spec. is it ok to upgrade the L0 loader here in the intel/llvm? I'm upgrading it in the UR L0 adapter here [oneapi-src/unified-runtime#1061](https://github.com/oneapi-src/unified-runtime/pull/1061)
> 
> I think we should then also update the L0 loader that is used in CI testing.

thanks @smaslov-intel . How can we do that? is it something I can add as part of this PR or does it need to be done by someone else?

**Comment by smaslov-intel** [comment]
> > > @smaslov-intel : I need this for several new features in L0 spec. is it ok to upgrade the L0 loader here in the intel/llvm? I'm upgrading it in the UR L0 adapter here [oneapi-src/unified-runtime#1061](https://github.com/oneapi-src/unified-runtime/pull/1061)
> > 
> > 
> > I think we should then also update the L0 loader that is used in CI testing.
> 
> thanks @smaslov-intel . How can we do that? is it something I can add as part of this PR or does it need to be done by someone else?

@bader : could you help answering this?
Perhaps, it is somehow pre-built into a package loaded for testing: https://github.com/intel/llvm/blob/156b730a6886b1394b7b91e2455d6e6b42ac6ec1/.github/workflows/sycl_linux_precommit.yml#L84C20-L84C63

**Comment by bader** [comment]
@aelovikov-intel, could you suggest the way to test L0 loader update?

**Comment by aelovikov-intel** [comment]
Sorry, I don't know how the closing happened...

**Comment by aelovikov-intel** [comment]
Why can't we get that update as part of the GPU driver? We don't want to run our testing with pre-release GPU stack...

**Comment by smaslov-intel** [comment]
> e don't want to run our testing with pre-release GPU stac

It looks we need all the right components spelled (in sync with each other) in https://github.com/intel/llvm/blob/sycl/devops/dependencies.json

**Comment by jandres742** [comment]
> Why can't we get that update as part of the GPU driver? We don't want to run our testing with pre-release GPU stack...

thanks @bader ., Definitely, we can update the loader as part of the GPU driver. How can we do that? What is the next GPU driver to be upgraded, and when is it planned?

**Review by kbenzie — APPROVED** [review]

**Review by EwanC — APPROVED** [review]
Cosmetic modification to graphs tests

**Comment by kbenzie** [comment]
@intel/llvm-gatekeepers please merge.

**Pull request merged**
