### PR TITLE
[SYCL][FPGA] Drop the duplicate attribute when adding or merging

### PR DESCRIPTION
**Pull request by smanna12**
This patch drops a duplicate attribute when adding or merging for FPGA attributes below:

1. [[intel::private_copies()]
2. [[intel::max_replicates()]]
3. [[intel::reqd_sub_group_size()]]
4. [[intel::num_simd_work_items()]]
5. [[intel::loop_fuse()]]
6. [[intel::loop_fuse_independent()]]
7. [[intel::no_global_work_offset()]]
8. [[intel::scheduler_target_fmax_mhz()]]

Also adds tests for each of the attributes with duplicate arguments.

Fixes https://github.com/intel/llvm/issues/3336

Signed-off-by: Soumi Manna <soumi.manna@intel.com>

### CODE REVIEW

**Comment by AaronBallman** [comment]
I think in general we should not be calling `dropAttr` as in this patch -- better to not call `addAttr` in the first place (either by returning `nullptr` from the merge function or doing an early return from the add function).

**Comment by smanna12** [comment]
> I think in general we should not be calling `dropAttr` as in this patch -- better to not call `addAttr` in the first place (either by returning `nullptr` from the merge function or doing an early return from the add function).

Done. Thanks.

**Review by AaronBallman — APPROVED** [review]
LGTM!

**Comment by smanna12** [comment]
> LGTM!

Thanks Aaron for the reviews.

**Pull request merged**
