### PR TITLE
[UR][L0] Add Support for External Semaphores

### PR DESCRIPTION
**Pull request by nrspruit**
-pre-commit PR for https://github.com/oneapi-src/unified-runtime/pull/2361

### CODE REVIEW

**Comment by JackAKirk** [comment]
Can you please test this feature via 

- https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/bindless_images/dx12_interop/read_write_unsampled_semaphore.cpp
- https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/bindless_images/examples/example_6_import_memory_and_semaphores.cpp

and/or any L0 specific testing as appropriate.

Thanks

**Comment by GeorgeWeb** [comment]
Ideally we'd like to see this enable testing by either adding `level-zero` to the relevant tests' `REQUIRES` line or maybe via aspect support check, i.e., `REQUIRES: aspect-ext_oneapi_bindless_images`. Thanks!

**Comment by nrspruit** [comment]
> Can you please test this feature via enabling l0 testing in
> 
> * https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/bindless_images/dx12_interop/read_write_unsampled_semaphore.cpp
> * https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/bindless_images/examples/example_6_import_memory_and_semaphores.cpp
> 
> and/or any L0 specific testing as appropriate.
> 
> Thanks

Currently there is no driver that exists that supports this functionality so enabling the tests will have to wait until the L0 driver is released and installed in the CI that handles these features,

**Comment by nrspruit** [comment]
> I assume the external semaphore related interop testing has been ran locally to ensure the feature implementation works correctly. Ideally we'd like to see this PR to enable the testing on L0 devices by either adding `level-zero` to the relevant tests' `REQUIRES` line or via aspect support check, i.e., `REQUIRES: aspect-ext_oneapi_bindless_images`. Thanks!

The tests can be enabled after we have an L0 driver released that supports this feature. Until then, this is enabling the UR L0 adapter to "enable" usage of the feature once an L0 driver with the support is available. When we have the driver which supports this feature in the CI, then I can post a patch to have this tested, otherwise this will fail.

**Review by kbenzie — APPROVED** [review]

**Pull request merged**
