### PR TITLE
[SYCL][NATIVECPU] Empty implementation for urCommandBufferAppendUSMMemcpyExp 

### PR DESCRIPTION
**Pull request by PietroGhg**

### CODE REVIEW

**Comment by aelovikov-intel** [comment]
We have issues with the CI, please avoid re-running the tests needlessly. If new run is scheduled while the previous has not finished yet, please cancel unnecessary old runs manually in the actions tab.

**Comment by PietroGhg** [comment]
> We have issues with the CI, please avoid re-running the tests needlessly. If new run is scheduled while the previous has not finished yet, please cancel unnecessary old runs manually in the actions tab.

Sorry, I'll keep it in mind next time

**Comment by PietroGhg** [comment]
Marked this as draft after https://github.com/intel/llvm/pull/11227

**Comment by PietroGhg** [comment]
Closing this PR since `urCommandBufferAppendUSMMemcpyExp` etc are now part of the Native CPU adapter

**Pull request closed without merging**
