### PR TITLE
[SYCL] Fix Ambiguity in Overloaded Unary Minus Operator for bfloat16

### PR DESCRIPTION
**Pull request by smanna12**
This commit resolves an overload resolution ambiguity on Windows self-builds in downstream pulldown when using the unary minus operator with bfloat16. The operator now takes a const-qualified argument, enabling its use with both lvalues and rvalues and fixing the reported build error.

### CODE REVIEW

**Review by tahonermann — APPROVED** [review]
Looks good to me!

**Comment by smanna12** [comment]
Thank you @tahonermann for review!

**Review by bso-intel — APPROVED** [review]
LGTM

**Comment by smanna12** [comment]
Thank you @bso-intel for reviews!

**Comment by smanna12** [comment]
@intel/llvm-gatekeepers, this PR is ready to merge. Thank you

**Pull request merged**
