### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW04)

### PR DESCRIPTION
**Pull request by vmaksimo**
LLVM: llvm/llvm-project@c84b8be516bc
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@984ce6e379dd1c563c80435ff035c3138e462846

### CODE REVIEW

**Comment by vmaksimo** [comment]
Hi @premanandrao! Could you please take a look at the changes made in c1ed45f13? Hope the test still checks its initial purpose.

**Comment by Fznamznon** [comment]
> Hi @premanandrao! Could you please take a look at the changes made in [c1ed45f](https://github.com/intel/llvm/commit/c1ed45f13c89df203cdeae8c2824f146d0b877f2)? Hope the test still checks its initial purpose.

I believe this is a valid change after https://github.com/vmaksimo/llvm/commit/4eaf5846d0e738264d9328b4a919bc352ea83b7a .

**Comment by vmaksimo** [comment]
> I believe this is a valid change after [vmaksimo@4eaf584](https://github.com/vmaksimo/llvm/commit/4eaf5846d0e738264d9328b4a919bc352ea83b7a) .

Thanks, @Fznamznon! I'll proceed the pulldown with this fix.

**Comment by premanandrao** [comment]
> > Hi @premanandrao! Could you please take a look at the changes made in [c1ed45f]

> I believe this is a valid change after [vmaksimo@4eaf584]

Thanks @Fznamznon!

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Fri 21 Jan 2022 07:24:47 AM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Fri 21 Jan 2022 07:28:18 AM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request closed without merging**
