### PR TITLE
[clang-offload-bundler] Initialize assembly parsers

### PR DESCRIPTION
**Pull request by sndmitriev**
This is needed for reading bitcode objects with inline assembly. And add
a workaround for spir target which does not have asm parser yet.

Signed-off-by: Sergey Dmitriev <serguei.n.dmitriev@intel.com>

### CODE REVIEW

**Review by bader — APPROVED** [review]

**Comment by sndmitriev** [comment]
ping

**Comment by romanovvlad** [comment]
@mdtoguchi @kbobrovs @AGindinson 
Could you please review?

**Review by mdtoguchi — APPROVED** [review]
LGTM

**Review by romanovvlad — APPROVED** [review]

**Comment by sndmitriev** [comment]
ping

**Comment by sndmitriev** [comment]
ping

**Review by kbobrovs — APPROVED** [review]
The implementation LGTM.
However, I don't quite understand why availability of SPIR asm will help when there is host-target (e.g. x86) module level assembly. SPIR asm does not understand x86 anyway.

**Comment by sndmitriev** [comment]
> However, I don't quite understand why availability of SPIR asm will help when there is host-target (e.g. x86) module level assembly. SPIR asm does not understand x86 anyway.

Right now the absence of asm parsers triggers an assertion when module contains module-level assembly, so asm parsers are needed anyway for other targets. As for the SPIR target, I think this is a separate problem that needs a discussion what should be done with it (probably in FE). As you said propagating host x86 assembly to SPIR module does not look right.

**Comment by kbobrovs** [comment]
> > However, I don't quite understand why availability of SPIR asm will help when there is host-target (e.g. x86) module level assembly. SPIR asm does not understand x86 anyway.
> 
> Right now the absence of asm parsers triggers an assertion when module contains module-level assembly, so asm parsers are needed anyway for other targets. As for the SPIR target, I think this is a separate problem that needs a discussion what should be done with it (probably in FE). As you said propagating host x86 assembly to SPIR module does not look right.

OK, I see. This problem seems not unique to SPIR target then.

**Comment by sndmitriev** [comment]
> OK, I see. This problem (propagation of host asm) seems not unique to SPIR target then. It should be filtered for other targets as well.

Most likely yes.

**Comment by kbobrovs** [comment]
> OK, I see. This problem (propagation of host asm) seems not unique to SPIR target then. It should be filtered for other targets as well.

just to clarify - this does not affect this PR and should be addressed separately.

**Comment by sndmitriev** [comment]
Accidentally closed this branch, reopening.

**Comment by sndmitriev** [comment]
Does this change need any additional actions to be merged?

**Pull request merged**
