### PR TITLE
[SYCL-MLIR] Enable -sycl-constant-propagation by default

### PR DESCRIPTION
**Pull request by victor-eds**
Run `-sycl-constant-propagation` after `-sycl-raise-host`.

Signed-off-by: Victor Perez <victor.perez@codeplay.com>

### CODE REVIEW

**Comment by victor-eds** [comment]
Depends in #10735

**Review by sommerlukas — APPROVED** [review]
I reviewed only the changes that are not part of #10735

**Review by jopperm — APPROVED** [review]
(same as @sommerlukas)

**Review by Naghasan — APPROVED** [review]
reviewed last patch

**Pull request merged**
