### PR TITLE
[SYCL] Make Level-Zero events visible on the host

### PR DESCRIPTION
**Pull request by smaslov-intel**
Make all events visible on the host, since we are waiting for many of them there.
Signed-off-by: Sergey V Maslov <sergey.v.maslov@intel.com>

### CODE REVIEW

**Review by romanovvlad — CHANGES_REQUESTED** [review]
Could you please add a test?

**Comment by smaslov-intel** [comment]
> Could you please add a test?

As it is often the case with the plugin, it is hard to make a dedicated test, especially LIT test.
Currently this change is a no-op since driver's default assumption is just what I've made explicit here.
Without this change when the driver is really looking at this flag, every benchmark would actually fail to run, so we have the tests.

**Comment by romanovvlad** [comment]
> As it is often the case with the plugin, it is hard to make a dedicated test, especially LIT test.
Please, take a look at how similar tests are written for the CUDA plugin:

https://github.com/intel/llvm/tree/sycl/sycl/unittests/pi/cuda

> Currently this change is a no-op since driver's default assumption is just what I've made explicit here.

Ok, agree.

**Review by romanovvlad — APPROVED** [review]

**Comment by bader** [comment]
Updated commit message to:

"[SYCL] Make Level-Zero events visible on the host (#2576)

The runtime is waiting for many of them there.

Signed-off-by: Sergey V Maslov <sergey.v.maslov@intel.com>"

**Pull request merged**
