### PR TITLE
[SYCL][L0] allow use of sub-devices with their root-device context 

### PR DESCRIPTION
**Pull request by smaslov-intel**
After https://github.com/intel/llvm/pull/5882 a context may only contain root-devices and its sub (and sub-sub) devices are implicitly in this context too. Follow this in L0 Plugin. Also fix the sub-sub device index calculation such that it is tied to a specific compute engine at user's request.

E2E test in https://github.com/intel/llvm-test-suite/pull/1139

### CODE REVIEW

**Review by sergey-semenov — APPROVED** [review]

**Comment by smaslov-intel** [comment]
@sergey-semenov , @asudarsa : please review

**Comment by smaslov-intel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1139

**Review by sergey-semenov — APPROVED** [review]

**Comment by smaslov-intel** [comment]
The failed CUDA testing is unrelated as the change is entirely in L0 Plugin.
Can this get merged then?

**Review by againull — APPROVED** [review]

**Comment by pvchupin** [comment]
@smaslov-intel, there is post-commit issue on shared libs build: https://github.com/intel/llvm/runs/7773239794?check_suite_focus=true

**Comment by smaslov-intel** [comment]
> @smaslov-intel, there is post-commit issue on shared libs build: https://github.com/intel/llvm/runs/7773239794?check_suite_focus=true

This was addressed in https://github.com/intel/llvm/commit/0cc408ea0053a2c9b19de9ac13d000cccba3938d

**Pull request merged**
