### PR TITLE
[BuildBot] Uplift GPU RT version for Linux CI Process

### PR DESCRIPTION
**Pull request by bb-sycl**
Uplift GPU RT version for Linux to 21.19.19792

### CODE REVIEW

**Comment by yanfeng3721** [comment]
cl::sycl::platform::get_platforms() throw Arithmetic exception "Floating point exception" when using Linux GPURT version 21.19.19792 with CUDA Version 10.1.243 installed, the last good to known version is 21.17.19709

**Comment by vladimirlaz** [comment]
> cl::sycl::platform::get_platforms() throw Arithmetic exception "Floating point exception" when using Linux GPURT version 21.19.19792 with CUDA Version 10.1.243 installed, the last good to known version is 21.17.19709

Possible solutions are under investigation. I will update once final solution will be implemented

**Comment by vladimirlaz** [comment]
The fix for test BE setup (intel/llvm#3825) should be applied to fix failure on CUDA.

**Review by vladimirlaz — APPROVED** [review]

**Pull request merged**
