### PR TITLE
[SYCL] Add llvm no spirv kernel tool

### PR DESCRIPTION
**Pull request by domiyan**
This tool is needed in offline compilation device link process for
correctness checking. The compiler need to check host files does not
contain device kernel entry point.

Background knowledge:
Device link is used in the scenario where the user separates their
device part and host part into different files. The benefits of this is
it removes the dependency from device binary to host only source files.
The user can save re-compile time when host only change happened. (This
is extremely important when targeting FPGA since device binary
generation takes hours)

An example of compiling dev.cpp and host.cpp w/o device link:
Dependency using Full link (no device link):
dev.cpp host.cpp -> dev.o host.o -> dev_fpga_binary.o (contain FPGA
image)
Compiler does not know what file contains kernel code, it assumes
dependency on every input source file. Any modification of source file
will trigger FPGA device binary generation.

Dependency using Device Link:
dev.cpp -> dev.o -> dev_fpga_binary.o (contain FPGA image)
If user only modify host.cpp, he/she will run:
1. host.cpp -> host.o
2. Link: host.o dev_fpga_binary.o -> executable
This skips FPGA binary generation.
The error we want to catch here is : "the user separates their codes in
a wrong way."
In step 2, we want to make sure host.p does not contain any device.
There are 2 cases:
1. It contains a new kernel.
2. It does not contain a new kernel but symbols like functions
or global variables
used in other kernels.
Case 2 can be identified in the FPGA binary generation stage.
llvm-no-spirv-kernel tool is used (automatically) by the compiler driver
to detect and make sure that host.o does not introduce new kernels by
checking spirv function entry point. This addresses case 1.

In this example. Driver will call this tool in step 2:
llvm-no-spirv-kernel host.bc (unbundled from host.o)
If it return 0 (no new kernel), call linker for linking. Otherwise error
out.

Signed-off-by: Domi Yan domi.yan@intel.com

### CODE REVIEW

**Comment by agozillon** [comment]
Interesting and awesome addition! 

I have one request, is it possible to have it not called llvm-no-spirv-kernel? As from what I can tell it's a little misleading. It seems to be checking for the SPIR_KERNEL calling convention which holds true for SPIR/SPIR-df as well... or anything that really wants to make use of the SPIR calling convention.

**Comment by domiyan** [comment]
@agozillon Thanks for your suggestion :)
1. My goal is to detect the translating unit (*.bc) file does not contain entry point of device code which is a spir-v kernel. If my detection is not accurate (by just checking calling convention), I should change that part of logic. (@kbobrovs. Do we use spir-df currently? Should we exclude/include it?)

2. I have considered a pure functional descriptive name like: "llvm-no-device-code-entry-point", but that's not very well defined. 

3. Do you have any suggestion on the name? What about "llvm-no-spirv-kernel-calling-convention" ?

**Comment by domiyan** [comment]
Seems like we agreed on when to call this tool and how to check for kernel :)
The thing left is the name of the tool:
We have 3 options so far:
1. llvm-no-spir-kernel
2. llvm-no-spriv-kernel
3. llvm-no-sycl-kernel

@kbobrovs @mdtoguchi  What do you think? I like the first one "llvm-no-spir-kernel".

**Comment by mdtoguchi** [comment]
> Seems like we agreed on when to call this tool and how to check for kernel :)
> The thing left is the name of the tool:
> We have 3 options so far:
> 
> 1. llvm-no-spir-kernel
> 2. llvm-no-spriv-kernel
> 3. llvm-no-sycl-kernel
> 
> @kbobrovs @mdtoguchi What do you think? I like the first one "llvm-no-spir-kernel".

I would agree - llvm-no-spir-kernel.

**Comment by domiyan** [comment]
Updated tool name to llvm-no-spir-kernel.

**Pull request merged**
