### PR TITLE
[SYCL] Disable submission of AssertInfoCopier for FPGA

### PR DESCRIPTION
**Pull request by s-kanaev**
Tests update: https://github.com/intel/llvm-test-suite/pull/533

### CODE REVIEW

**Comment by s-kanaev** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/533

**Comment by s-kanaev** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/533

**Comment by s-kanaev** [comment]
@intel/llvm-reviewers-runtime , a friendly ping. Testing with corresponding test changes (intel/llvm-test-suite#533) has been successful.

**Review by steffenlarsen — APPROVED** [review]
LGTM!

**Comment by romanovvlad** [comment]
> @intel/llvm-reviewers-runtime , a friendly ping. Testing with corresponding test changes ([intel/llvm-test-suite#533](https://github.com/intel/llvm-test-suite/pull/533)) has been successful.

Shouldn't we see all jobs passing with `/ve_rify with intel/llvm-test-suite#533` then?

**Pull request merged**
