### PR TITLE
Added an extension that introduces compile-time-constant properties t…

### PR DESCRIPTION
**Pull request by GarveyJoe**
…o property_list and accessor

### CODE REVIEW

**Comment by bader** [comment]
@GarveyJoe, I'd like to use following commit title:
"[SYCL][Doc] Add SYCL_INTEL_accessor_properties extension specification (#1925)"

And move current PR title to the commit message body:
"Added an extension that introduces compile-time-constant properties to property_list and accessor"

Are you okay with it?

**Comment by MrSidims** [comment]
AFAIK Joe is on vacation. Readdressing the question to @mohammadfawaz

**Comment by mohammadfawaz** [comment]
> @GarveyJoe, I'd like to use following commit title:
> "[SYCL][Doc] Add SYCL_INTEL_accessor_properties extension specification (#1925)"
> 
> And move current PR title to the commit message body:
> "Added an extension that introduces compile-time-constant properties to property_list and accessor"
> 
> Are you okay with it?

On behalf of Joe. I believe this is reasonable. Thanks!

**Comment by bader** [comment]
@mohammadfawaz, thanks.

**Pull request merged**
