### PR TITLE
[Buildbot] Upgrade Windows GPU driver to 100.9864

### PR DESCRIPTION
**Pull request by yinyangsx**
Signed-off-by: Yin Yang <yin.yang@intel.com>

### CODE REVIEW

**Comment by bader** [comment]
@yinyangsx, is it ready for review already?

**Comment by yinyangsx** [comment]
> @yinyangsx, is it ready for review already?

Be waiting Jenkins/Summary done

**Comment by yinyangsx** [comment]
@bader, please let me know when you merge it.

**Comment by bader** [comment]
> @bader, please let me know when you merge it.

@yinyangsx, I think GitHub should send a notification automatically.
Anyway, the patch is merged.

**Pull request merged**
