### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW29)

### PR DESCRIPTION
**Pull request by dwoodwor-intel**
LLVM: llvm/llvm-project@132d711554cbb3db0b0efd1e88d2acb9278b6be9
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@18d1f41f4d168bf3ea99263155e83350016bb6fe

### CODE REVIEW

**Comment by dwoodwor-intel** [comment]
It looks like the sphinx build failure has been fixed upstream; I've cherry-picked that commit.

**Comment by dwoodwor-intel** [comment]
A couple more test fixes:

* d278c671900108309e2a6faf229a4e3f56a19ddb adds a new testcase that also needs to be updated for the new static_assert error format
* https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/bb4ead0d84870afe1f6f4ce829ba985b1b7950c7 enables a test that is failing on Windows, so I'm leaving it out of this week's pulldown (via a revert) and I'll try to figure out what's going on with it and pull it in for next week instead.

**Comment by dwoodwor-intel** [comment]
I'm seeing some test failures that look like they're caused by https://github.com/intel/llvm-test-suite/pull/1076—they should be fixed by #6400 so I've merged that in

**Comment by dwoodwor-intel** [comment]
@intel/llvm-gatekeepers, it looks like all of the (non-lint) tests are passing now, except that ProtexIP step crashed/was terminated after running for 20 hours. Is that expected for pulldowns? Should I go ahead with the merge?

**Comment by bader** [comment]
> @intel/llvm-gatekeepers, it looks like all of the (non-lint) tests are passing now, except that ProtexIP step crashed/was terminated after running for 20 hours. Is that expected for pulldowns? Should I go ahead with the merge?

No, it's not expected. I expect this job to work for any PR. If you are 100% sure that the changes **you did on top of pulled ones** are fine, you can merge it.

@dwoodwor-intel, do you track the llvm-spirv changes made here? https://github.com/intel/llvm/pull/6420/commits/be9bfe67173f649e7077902fe03d63cb415077d0 reverts on of the commits. Will you merge it with next pulldown or cherry-pick separately?

**Comment by dwoodwor-intel** [comment]
> No, it's not expected. I expect this job to work for any PR. If you are 100% sure that the changes **you did on top of pulled ones** are fine, you can merge it.

Those should be fine; I'll go ahead with the merge.

> @dwoodwor-intel, do you track the llvm-spirv changes made here? [be9bfe6](https://github.com/intel/llvm/commit/be9bfe67173f649e7077902fe03d63cb415077d0) reverts on of the commits. Will you merge it with next pulldown or cherry-pick separately?

Yes, I've updated the commit hash in the message above to not include the reverted commit and my plan is to merge it with the next pulldown instead.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Tue 12 Jul 2022 05:29:40 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Tue 12 Jul 2022 06:00:24 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Comment by dwoodwor-intel** [comment]
I hunted down the Windows bug in `LLVM-SPIRV :: test/transcoding/image_signedness.ll` that forced me to back out https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/bb4ead0d84870afe1f6f4ce829ba985b1b7950c7 and posted a fix here: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1550

**Comment by bader** [comment]
Thanks a lot!
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1550 is merged, so I hope we can merge both patches with the next pulldown.

**Pull request merged**
