### PR TITLE
[SYCL] Host device & queue removal (internal part, not breaking ABI) 

### PR DESCRIPTION
**Pull request by KseniyaTikhomirova**
Host device support is deprecated long time ago. Although our internal host task & host accessor implementation was still using it.
This change eliminates it and remove possibility to create host queue/context and device. This brings the following changes:

- Commands & Events could not guarantee queried Context != nullptr and Queue!= nullptr since for host task stuff no device queue/context is involved. For host task we have submitted queue instance stored in event to be able to report exceptions to user and to be able to properly handle dependencies. Submitted queue for host task is guaranteed to be not null.
- Connection command for cross context dependencies is now attached to the queue of new command (dependency for which is being analyzed). Previously it was also related to host queue only. No perf impact is expected.
- Stream flush command is now submitted to the same queue as corresponding kernel (previously it was submitted to the host queue). This could bring negative perf impact for stream usage with in-order queue but stream is not perf oriented feature.
ABI breaking changes to remove is_host methods and some SYCL_EXTERN stuff will be submitted separately.

### CODE REVIEW

**Comment by KseniyaTikhomirova** [comment]
original PR was https://github.com/intel/llvm/pull/14027 but I made a mistake during sycl branch merge caused addition of sycl commits to PR and requesting corresponding reviewers not related to my changes.

**Comment by KseniyaTikhomirova** [comment]
@isaacault hi, may I ask you to approve it again? I spoiled my original PR (https://github.com/intel/llvm/pull/14027) approved by you and opened this one. Thank you.

**Review by sergey-semenov — APPROVED** [review]

**Comment by bader** [comment]
> original PR was #14027 but I made a mistake during sycl branch merge caused addition of sycl commits to PR and requesting corresponding reviewers not related to my changes.

@KseniyaTikhomirova, I can help you to fix #14370. Ping me if you are interested.

**Review by isaacault — APPROVED** [review]
`sycl/source/detail/bindless_images.cpp` LGTM.

**Comment by isaacault** [comment]
CI failure seems related to https://github.com/intel/llvm/issues/14248. I'm not sure what the fix is, but I've had luck working around this by frequently merging `sycl` branch until a successful CI run.

**Comment by KseniyaTikhomirova** [comment]
@intel/llvm-gatekeepers hi, Win E2E testing failed at the last step - infrastructure issue. could we merge this PR despite on this?
CI Win result is green itself:

Total Discovered Tests: 2091
  Skipped    : 1959 (93.69%)
  Unsupported:   65 (3.11%)
  Passed     :   67 (3.20%)

**Comment by steffenlarsen** [comment]
Windows failure is after tests run and is infrastructural. Merging this.

**Comment by KseniyaTikhomirova** [comment]
Monitoring post-commit shows MacOS build failure with unused var in program_impl. 
I will prepare PR to fix but merging https://github.com/intel/llvm/pull/14368 is preferable - it completely removes program_impl.* files.

**Comment by KseniyaTikhomirova** [comment]
post commit failures fix https://github.com/intel/llvm/pull/14385 and https://github.com/intel/llvm/pull/14389

**Comment by KseniyaTikhomirova** [comment]
more fixes https://github.com/intel/llvm/pull/14396

**Pull request merged**
