### PR TITLE
[SYCL] Adding versioninfo.rc to proxyloader.dll

### PR DESCRIPTION
**Pull request by cperkinsintel**
Copyright declaration needed for 2024.1

### CODE REVIEW

**Review by aelovikov-intel — APPROVED** [review]
Did you try to re-use https://github.com/intel/llvm/blob/079fc97b51fe541ba5a4ba271bcc4dd6f43df21a/llvm/resources/windows_version_resource.rc somehow?

**Comment by cperkinsintel** [comment]
@aelovikov-intel , no I did not know that we had that.  Should we be using it?

SYCL is using https://github.com/intel/llvm/blob/079fc97b51fe541ba5a4ba271bcc4dd6f43df21a/sycl/source/version.rc.in   

I'll try windows_version_resource.rc

**Comment by aelovikov-intel** [comment]
> Should we be using it?

No idea, today was the first time I've seen any of this.

**Comment by cperkinsintel** [comment]
@aelovikov-intel  - I dropped the source versioninfo.rc file and am using the the LLVM windows_versions_resource.rc file.  I'm guessing that some of these other DLLs will need copyright info, so it'll be a better practice for us overall to use that common template rather than bespoke ones.

**Pull request merged**
