### PR TITLE
[SYCL][E2E] Remove Matrix/get_coord_int8_matB.cpp's XFAIL on CPU after uplift OCLCPURT to 2024.18.6.0.02

### PR DESCRIPTION
**Pull request by yanfeng3721**

### CODE REVIEW

**Review by dkhaldi — CHANGES_REQUESTED** [review]
We should also be able to remove xfail from https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/Matrix/SG32/get_coord_int8_matB.cpp

**Comment by yanfeng3721** [comment]
> We should also be able to remove xfail from https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/Matrix/SG32/get_coord_int8_matB.cpp

Thanks @dkhaldi, I have updated Matrix/SG32/get_coord_int8_matB.cpp.

**Review by dkhaldi — APPROVED** [review]
LGTM

**Comment by yanfeng3721** [comment]
Hi @dkhaldi , could you please help to merge the PR? Thanks.

**Comment by dkhaldi** [comment]
@intel/llvm-gatekeepers, please help merge this.

**Pull request merged**
