### PR TITLE
[SYCL][FPGA][NFC] Change the identifier names

### PR DESCRIPTION
**Pull request by smanna12**
This patch changes the identifier names because
we do not use FPGA attribute spelling anymore (Ref:
https://github.com/intel/llvm/pull/4532)

Fixes https://github.com/intel/llvm/issues/5105

Signed-off-by: Soumi Manna [soumi.manna@intel.com](mailto:soumi.manna@intel.com)

### CODE REVIEW

**Comment by premanandrao** [comment]
It looks like these are all name changes from IntelFPGA to SYCLIntel and from SYCLIntelFPGA to SYCLIntel, and these are okay to me.   But there are some that changed from IntelFPGA... to Intel... (and not SYCLIntel...).   Is this intentional?   Are the new spellings/mappings listed somewhere?

**Comment by smanna12** [comment]
> . But there are some that changed from IntelFPGA... to Intel... (and not SYCLIntel...). Is this intentional? Are the new spellings/mappings listed somewhere?

Thanks @premanandrao for reviews! This is intentional . I thought to update them as well by removing FPGA. Those are not listed anywhere. If you prefer, i could leave them unchanged

**Comment by premanandrao** [comment]
> If you prefer, i could leave them unchanged

My suggestion would be to change them to SYCLIntel... to be consistent with the other similar changes.

**Comment by smanna12** [comment]
ping @premanandrao

**Review by elizabethandrews — APPROVED** [review]

**Review by premanandrao — APPROVED** [review]

**Comment by smanna12** [comment]
Failings do not seem related to my PR.

@intel/llvm-gatekeepers, this PR is ready for merge. Thank you

**Pull request merged**
