### PR TITLE
[SYCL] Fix conflicting visibility attributes

### PR DESCRIPTION
**Pull request by alexbatashev**
`inline` implies internal linkage, when `__SYCL_EXPORT` sets external linkage. These attributes can't co-exist. Remove `__SYCL_EXPORT` for symbols that are supposed to be internal.

Signed-off-by: Alexander Batashev <alexander.batashev@intel.com>

### CODE REVIEW

**Comment by s-kanaev** [comment]
@alexbatashev  Please, describe the problem eliminated by this patch in patch description.

**Comment by alexbatashev** [comment]
> @alexbatashev Please, describe the problem eliminated by this patch in patch description.

Done

**Comment by s-kanaev** [comment]
> inline implies internal linkage, when __SYCL_EXPORT sets external linkage. These attributes can't co-exist. Remove __SYCL_EXPORT for symbols that are supposed to be internal.

Were these symbols visible when both modifiers where applied?

**Comment by alexbatashev** [comment]
> > inline implies internal linkage, when __SYCL_EXPORT sets external linkage. These attributes can't co-exist. Remove __SYCL_EXPORT for symbols that are supposed to be internal.
> 
> Were these symbols visible when both modifiers where applied?

I'm not sure. But it caused compile errors on some configurations.

**Pull request merged**
