### PR TITLE
[NFC][SYCL][MATRIX] Add std::ignore for unused parameters to fix warnings.

### PR DESCRIPTION
**Pull request by arnamoy10**

### CODE REVIEW

**Review by dkhaldi — APPROVED** [review]
LGTM

**Comment by bader** [comment]
@intel/dpcpp-esimd-reviewers, @arnamoy10, it seems like ESIMD tests are broken in pre-commit. It doesn't look like this patch can cause such failures.

```
********************
Timed Out Tests (8):
  SYCL :: lsc/lsc_usm_block_load_u8_u16.cpp
  SYCL :: lsc/lsc_usm_block_load_u8_u16_64.cpp
  SYCL :: lsc/lsc_usm_prefetch_u32.cpp
  SYCL :: lsc/lsc_usm_prefetch_u32_64.cpp
  SYCL :: lsc/lsc_usm_prefetch_u32_scalar_off.cpp
  SYCL :: lsc/lsc_usm_prefetch_u64.cpp
  SYCL :: lsc/lsc_usm_prefetch_u64_64.cpp
  SYCL :: lsc/lsc_usm_prefetch_u64_scalar_off.cpp

********************
Failed Tests (25):
  SYCL :: lsc/lsc_surf_load_u16u32.cpp
  SYCL :: lsc/lsc_surf_load_u32.cpp
  SYCL :: lsc/lsc_surf_load_u32_stateless.cpp
  SYCL :: lsc/lsc_surf_load_u64.cpp
  SYCL :: lsc/lsc_surf_load_u64_stateless.cpp
  SYCL :: lsc/lsc_surf_load_u8_u16.cpp
  SYCL :: lsc/lsc_surf_load_u8_u16_stateless.cpp
  SYCL :: lsc/lsc_surf_load_u8u32.cpp
  SYCL :: lsc/lsc_surf_prefetch_u16u32.cpp
  SYCL :: lsc/lsc_surf_prefetch_u32.cpp
  SYCL :: lsc/lsc_surf_prefetch_u64.cpp
  SYCL :: lsc/lsc_surf_prefetch_u8u32.cpp
  SYCL :: lsc/lsc_surf_store_u16u32.cpp
  SYCL :: lsc/lsc_surf_store_u32.cpp
  SYCL :: lsc/lsc_surf_store_u32_stateless.cpp
  SYCL :: lsc/lsc_surf_store_u64.cpp
  SYCL :: lsc/lsc_surf_store_u64_stateless.cpp
  SYCL :: lsc/lsc_surf_store_u8_u16.cpp
  SYCL :: lsc/lsc_surf_store_u8u32.cpp
  SYCL :: lsc/lsc_usm_block_load_u32.cpp
  SYCL :: lsc/lsc_usm_block_load_u32_64.cpp
  SYCL :: lsc/lsc_usm_block_load_u32_scalar_off.cpp
  SYCL :: lsc/lsc_usm_block_load_u64.cpp
  SYCL :: lsc/lsc_usm_block_load_u64_64.cpp
  SYCL :: lsc/lsc_usm_block_load_u64_scalar_off.cpp
```

**Comment by v-klochkov** [comment]
> @intel/dpcpp-esimd-reviewers, @arnamoy10, it seems like ESIMD tests are broken in pre-commit. It doesn't look like this patch can cause such failures.
> 
> ```
> ********************
> Timed Out Tests (8):
>   SYCL :: lsc/lsc_usm_block_load_u8_u16.cpp
>   SYCL :: lsc/lsc_usm_block_load_u8_u16_64.cpp
>   SYCL :: lsc/lsc_usm_prefetch_u32.cpp
>   SYCL :: lsc/lsc_usm_prefetch_u32_64.cpp
>   SYCL :: lsc/lsc_usm_prefetch_u32_scalar_off.cpp
>   SYCL :: lsc/lsc_usm_prefetch_u64.cpp
>   SYCL :: lsc/lsc_usm_prefetch_u64_64.cpp
>   SYCL :: lsc/lsc_usm_prefetch_u64_scalar_off.cpp
> 
> ********************
> Failed Tests (25):
>   SYCL :: lsc/lsc_surf_load_u16u32.cpp
>   SYCL :: lsc/lsc_surf_load_u32.cpp
>   SYCL :: lsc/lsc_surf_load_u32_stateless.cpp
>   SYCL :: lsc/lsc_surf_load_u64.cpp
>   SYCL :: lsc/lsc_surf_load_u64_stateless.cpp
>   SYCL :: lsc/lsc_surf_load_u8_u16.cpp
>   SYCL :: lsc/lsc_surf_load_u8_u16_stateless.cpp
>   SYCL :: lsc/lsc_surf_load_u8u32.cpp
>   SYCL :: lsc/lsc_surf_prefetch_u16u32.cpp
>   SYCL :: lsc/lsc_surf_prefetch_u32.cpp
>   SYCL :: lsc/lsc_surf_prefetch_u64.cpp
>   SYCL :: lsc/lsc_surf_prefetch_u8u32.cpp
>   SYCL :: lsc/lsc_surf_store_u16u32.cpp
>   SYCL :: lsc/lsc_surf_store_u32.cpp
>   SYCL :: lsc/lsc_surf_store_u32_stateless.cpp
>   SYCL :: lsc/lsc_surf_store_u64.cpp
>   SYCL :: lsc/lsc_surf_store_u64_stateless.cpp
>   SYCL :: lsc/lsc_surf_store_u8_u16.cpp
>   SYCL :: lsc/lsc_surf_store_u8u32.cpp
>   SYCL :: lsc/lsc_usm_block_load_u32.cpp
>   SYCL :: lsc/lsc_usm_block_load_u32_64.cpp
>   SYCL :: lsc/lsc_usm_block_load_u32_scalar_off.cpp
>   SYCL :: lsc/lsc_usm_block_load_u64.cpp
>   SYCL :: lsc/lsc_usm_block_load_u64_64.cpp
>   SYCL :: lsc/lsc_usm_block_load_u64_scalar_off.cpp
> ```

Most likely that is the typical scenario with Old(morning) compiler build used by CI and NEW tests.
We recently merged 2 commits:
PR: https://github.com/intel/llvm/pull/8316 
Test PR: https://github.com/intel/llvm/pull/8316 

PR (8316) did not catch the morning compiler build time.

@fineg74 - can you please check/confirm if that is new regression caused by your fix, or just bad timing for the merge?

**Comment by bader** [comment]
@v-klochkov, I checked before commenting that @arnamoy10's branch is based on `HEAD` of sycl branch, so all compiler commits are there. AFAIK, CI takes `HEAD` of `intel` branch in llvm-test-suite repository. You put wrong link for the test PR. Could you tell of test PR was committed less than hour ago?

**Review by steffenlarsen — APPROVED** [review]

**Comment by steffenlarsen** [comment]
I am merging this as it is very clearly a NFC and it would be best to get post-commit building again. Feel free to continue the discussion.

**Comment by bader** [comment]
> I am not sure it is related to the change but likely some emulator issue: The test was merged together with compiler and bad timing would lead to compilation errors rather than execution errors All the tests fail with following error: EMU: *** Error -------------------------------------------------------------------------- Received signal 6 SIGABRT. Terminating.
> 
> # command stderr:
> terminate called after throwing an instance of 'sycl::_V1::memory_allocation_error' what(): EMU: *** Error -------------------------------------------------------------------------- Received signal 6 SIGABRT. Terminating
> 
> The only change that could be related to allocation is use of aligned memory allocation i.e. sycl::aligned_alloc_shared and sycl::usm_allocator<T, sycl::usm::alloc::host, Flags::template alignment<__ESIMD_DNS::__raw_t>> in the tests. The code patch doesn't do any allocation. I am not sure that there is a difference between regular allocation vs aligned allocation from emulator perspective. Not every test affected by the change has failed here and different CI runs produce different set of failing sets (https://github.com/intel/llvm/actions/runs/4439865937/jobs/7794571728 for example has 3 timeouts and 34 failures vs 8 timeouts and 25 failures here)

@fineg74, @intel/dpcpp-esimd-reviewers, please, investigate and fix this issues as soon as possible. This issue impact pre-commit validation.
See https://github.com/intel/llvm/actions/runs/4447776170/jobs/7810525573?pr=8688 - pre-commit results for https://github.com/intel/llvm/pull/8688. I need time for analysis, I suggest disabling tests temporarily.

**Comment by bader** [comment]
Failed for my [NFC patch](https://github.com/intel/llvm/pull/8694) too - https://github.com/intel/llvm/actions/runs/4451701743/jobs/7818993494#step:22:2268

**Pull request merged**
