### PR TITLE
[SYCL-MLIR] Merge from intel/llvm sycl branch

### PR DESCRIPTION
**Pull request by whitneywhtsang**
Please only review https://github.com/intel/llvm/pull/9351/commits/ec1c3d08c587997beed49af7ea92a270bee3c278 and files with merge conflicts:
```
        both modified:   .github/CODEOWNERS
        both modified:   libclc/CMakeLists.txt
        both modified:   libclc/utils/libclc-remangler/LibclcRemangler.cpp
        both modified:   mlir/include/mlir/Dialect/LLVMIR/LLVMIntrinsicOps.td
        both added:      mlir/test/Target/LLVMIR/Import/exception.ll
```

Please do not squash and merge this PR.

### CODE REVIEW

**Review by sommerlukas — APPROVED** [review]
I reviewed https://github.com/intel/llvm/commit/6c6ab62a5e4e67d987dcc6c3c9747ce4ac3fbfc7, LGTM. I could not review all conflict files, as my browser could not load some due to the large diff.

**Comment by victor-eds** [comment]
> I reviewed [6c6ab62](https://github.com/intel/llvm/commit/6c6ab62a5e4e67d987dcc6c3c9747ce4ac3fbfc7), LGTM. I could not review all conflict files, as my browser could not load some due to the large diff.

Same here

**Comment by whitneywhtsang** [comment]
> What made the changes to `polygeist/test/polygeist-opt/bareptrlowering-typed-pointer.mlir` and polygeist/test/polygeist-opt/bareptrlowering.mlir necessary? Is that caused by an upstream change?

Yes, it is caused by e02d4142dca48d9359ad304fec629ea3d7e6924c.

**Comment by whitneywhtsang** [comment]
Addressed a review comment, the new commit is https://github.com/intel/llvm/pull/9351/commits/c0ade3949e73aa19bfb5882fd980662f0cc6a89a.

**Pull request merged**
