### PR TITLE
[SYCL] Add generic fabs imp for bf16

### PR DESCRIPTION
**Pull request by jinge90**
Signed-off-by: jinge90 <ge.jin@intel.com>

### CODE REVIEW

**Comment by jinge90** [comment]
Hi, @bader and @aelovikov-intel 
I re-submit https://github.com/intel/llvm/pull/7959 , CUDA pre-ci test suite passed here and I also tested the patch on a machine with backend, I used following command to build bfloat16_builtin.cpp and it passed too

clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda -Xsycl-target-backend --cuda-gpu-arch=sm_80 bfloat16_builtins.cpp
What else test should I verify?
Thanks very much.

**Review by aelovikov-intel — APPROVED** [review]
If no llvm-test-suite changes are required to be made simultaneously with this PR, I think we can merge it.

**Comment by bader** [comment]
> If no llvm-test-suite changes are required to be made simultaneously with this PR, I think we can merge it.

The problem is that we can't validate test changes on non-Intel HW.
https://github.com/intel/llvm-test-suite/pull/1495 must be validated manually on HIP and CUDA systems before we can enable testing of "generic" fabs.

**Comment by jinge90** [comment]
> > If no llvm-test-suite changes are required to be made simultaneously with this PR, I think we can merge it.
> 
> The problem is that we can't validate test changes on non-Intel HW. [intel/llvm-test-suite#1495](https://github.com/intel/llvm-test-suite/pull/1495) must be validated manually on HIP and CUDA systems before we can enable testing of "generic" fabs.

OK, then I will re-submit [intel/llvm-test-suite#1495] and find HIP and CUDA backend to have a try.

Thanks very much.

**Comment by jinge90** [comment]
Hi, @bader and @aelovikov-intel 
Could you help merge this PR now?
Thanks very much.

**Comment by bader** [comment]
Failed Tests (1):
  SYCL :: OptionalKernelFeatures/is_compatible.cpp

**Pull request merged**
