### PR TITLE
[SYCL] Support bf16 isnan for sycl::marray<bfloat16, N>

### PR DESCRIPTION
**Pull request by jinge90**

### CODE REVIEW

**Comment by jinge90** [comment]
Hi, @JackAKirk and @gmlueck 
As we discussed in https://github.com/intel/llvm/pull/7958 , this PR aims to support sycl::marray<bfloat16, N> for isnan.

**Review by romanovvlad — COMMENTED** [review]
Could you please add a test in https://github.com/intel/llvm-test-suite ?

**Comment by jinge90** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1509

**Comment by jinge90** [comment]
> Could you please add a test in https://github.com/intel/llvm-test-suite ?

Hi, @romanovvlad 
The test is in https://github.com/intel/llvm-test-suite/pull/1509

**Review by romanovvlad — APPROVED** [review]

**Review by JackAKirk — APPROVED** [review]

**Pull request merged**
