### PR TITLE
[SYCL] Turn ext_oneapi_submit_barrier() into nop if waitlist empty and queue is in-order

### PR DESCRIPTION
**Pull request by againull**

### CODE REVIEW

**Comment by againull** [comment]
@sergey-semenov Could you please take a look?

**Comment by al42and** [comment]
Are there any known issues with this change? I'm observing segfaults with L0 and HIP backends with b6947172, and reverting this PR (7e08c15) helps.

**Comment by againull** [comment]
> Are there any known issues with this change? I'm observing segfaults with L0 and HIP backends with [b694717](https://github.com/intel/llvm/commit/b6947172553a66d9519f7701e8d77a9282353c2a), and reverting this PR ([7e08c15](https://github.com/intel/llvm/commit/7e08c15dddfdb938767a73d6d9c0c31a8149c9b3)) helps.

No issues were reported yet, so it's not known. Can you clarify what tests are failing for you and how to reproduce the problem? The link you provided points to the commit in the clang driver, I don't how it's related.

**Comment by al42and** [comment]
> No issues were reported yet, so it's not known. Can you clarify what tests are failing for you and how to reproduce the problem?

Ok, I'll file a bug report then. The problem is observed in a larger application, so I'll need a bit of time to make a detailed writeup or a reproducer.

> The link you provided points to the commit in the clang driver, I don't see how it's related.

I just pointed to the tip of the `sycl` branch (at the time of writing) with which I was observing the problem. The problem is caused by this PR (#12045).

**Pull request merged**
