### PR TITLE
[GHA] Uplift Linux IGC Dev RT version to igc-dev-246be8e

### PR DESCRIPTION
**Pull request by bb-sycl**
Scheduled igc dev drivers uplift

### CODE REVIEW

**Comment by sarnex** [comment]
@jsji FYI same test is still failing in this igc-dev version

**Comment by jsji** [comment]
> @jsji FYI same test is still failing in this igc-dev version

Thanks @sarnex ! We will have a look.

**Comment by jsji** [comment]
The failures is due to Remove ZEBin user options and internal option https://github.com/intel/intel-graphics-compiler/commit/2ae4dd8724f0411b497490197a7799edde1e4ac7

So it will require the corresponding compute runtime changes, eg: https://github.com/intel/compute-runtime/commit/5ae2709e6e38585d2fb2d2fcb78930897ca2c932 which was committed around 3 weeks ago.

Unfortunately, we haven't updated the compute runtime for a while -- it is still from Apr (3 months old). 
We should update GPU RT first,  with https://github.com/intel/llvm/pull/14376 . Then the test should pass.

**Comment by sarnex** [comment]
Thanks I will work on merging the new runtime

**Comment by jsji** [comment]
> Thanks I will work on merging the new runtime

Thanks @sarnex

**Comment by jsji** [comment]
Rebased to latest.

**Pull request closed without merging**
