### PR TITLE
Added tests to verify that devicelib APIs have no 'noinline' attribute.

### PR DESCRIPTION
**Pull request by vzakhari**
Device compilers may (and should) honor 'noinline' attribute
even when optimizations are turned on. At the same time, we do not want
to prevent inlining of devicelib wrappers and fallback implementations,
since this may result in degraded performance. These tests verify that
the devicelib APIs are not marked with 'noinline' attribute.

Signed-off-by: Vyacheslav Zakharin <vyacheslav.p.zakharin@intel.com>

### CODE REVIEW

**Review by bader — APPROVED** [review]

**Comment by vzakhari** [comment]
Thank you for the review, @bader.  The composite-spec-const fails have nothing to do with this change-set.  How do I proceed with the merge?

**Comment by bader** [comment]
Don't we need to get an approval from @jinge90?

**Comment by vzakhari** [comment]
> Don't we need to get an approval from @jinge90?

Sure, I will wait for @jinge90's approval.  I was asking in advance.  If you are able to merge this after Ge's approval, then I do not have any more questions :-)

**Comment by bader** [comment]
> If you are able to merge this after Ge's approval, then I do not have any more questions :-)

Yes. I can merge if Ge approves.

**Review by jinge90 — APPROVED** [review]

**Pull request merged**
