### PR TITLE
[SYCL] Remove using std namespace as appropriate header is not included

### PR DESCRIPTION
**Pull request by romanovvlad**
Signed-off-by: Vlad Romanov <vlad.romanov@intel.com>

### CODE REVIEW

**Comment by rolandschulz** [comment]
I agree (I'm not authorized to merge).

**Comment by romanovvlad** [comment]
Hot fix merging.

**Comment by keryell** [comment]
Then where does `size_t` come from if it is not `std::size_t`?
Including some C `<stddef.h>` instead of C++ `#include <cstddef>`?

**Comment by rolandschulz** [comment]
The header includes detail/os_util.hpp which includes stdlib.h and defines size_t. But only some versions of GCC/libstdc++ also define std::size_t.

**Comment by alexeyvoronov** [comment]
For example there is `using size_type = std::size_t;` inside `exception_list` class in SYCL specification.
We did just that, and we have the `<cstddef>` header file included there.

**Pull request merged**
