### PR TITLE
[SYCLToLLVM]: Make Memref2PointerOp use the memspace of the source…

### PR DESCRIPTION
**Pull request by etiotto**
When creating a polygeist::MemRef2Pointer operation the result pointer type should have the same address space of the source value. Example: 
```
%2 = "polygeist.memref2pointer"(%0) : (memref<1xi8,4>) -> !llvm.ptr<i8, 4>
```
Signed-off-by: Tiotto, Ettore <ettore.tiotto@intel.com>

### CODE REVIEW

**Comment by victor-eds** [comment]
I think we might be missing some cases (both in `clang-mlir.cc` and in `CGCall.cc`). Also, could you add some tests for this?

**Comment by whitneywhtsang** [comment]
```

**Comment by whitneywhtsang** [comment]
```
%2 = "polygeist.memref2pointer"(%0) : (memref<1x!sycl_id_2_, 4>) -> !llvm.ptr<i8, 4>
```
This may not be a good example, how about 
```
%2 = "polygeist.memref2pointer"(%0) : (memref<1xi8>) -> !llvm.ptr<i8, 4>
```

**Review by whitneywhtsang — APPROVED** [review]

**Comment by etiotto** [comment]
https://github.com/intel/llvm/pull/6864#issuecomment-1256315086 --> done

**Comment by etiotto** [comment]
Note: this PR does not have associated C++ test cases because is difficult to generate the memref -> ptr pattern where the memref is not in the default MLIR address space (starting from C++ code). I have a subsequent PR which will generate the pattern, that PR will adjust the SYCL specific test cases to check that `polygeist::MemRef2Pointer` preserves the source operand address space.

**Pull request merged**
