### PR TITLE
[SYCL][DOC] DeviceLib doc update to add new supported items

### PR DESCRIPTION
**Pull request by jinge90**
Signed-off-by: gejin <ge.jin@intel.com>

### CODE REVIEW

**Comment by bader** [comment]
@jinge90, could you remind me PR/commit IDs where these functions were added, please?

**Comment by jinge90** [comment]
> @jinge90, could you remind me PR/commit IDs where these functions were added, please?

Hi, @bader 
https://github.com/intel/llvm/pull/3262 is for adding support div, ldiv, lldiv.
https://github.com/intel/llvm/pull/3364 is for adding support abs, labs,llabs

And a bunch of math functions are removed from list of math function unsupported although we didn't add any support in SYCL device library. The reason is those math functions are converted to corresponding llvm intrinsic and llvm-spirv has supported those intrinsic, so they can work in SYCL device now, The corresponding PR is: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/855
Thanks very much.

**Comment by bader** [comment]
Thanks, but I can't find `scalbn` and `nextafter` implementations in provided PRs.

**Comment by jinge90** [comment]
> Thanks, but I can't find `scalbn` and `nextafter` implementations in provided PRs.

Hi, @bader 
For scalbn, we added long time ago but didn't update the doc
https://github.com/intel/llvm/pull/2558

For nextafter, I think it was a mistake in initial version of the doc, this API was added long time ago in the first patch for cmath, complex device library, https://github.com/intel/llvm/pull/975
Thanks very much.

**Review by bader — APPROVED** [review]

**Comment by jinge90** [comment]
Hi, @intel/dpcpp-specification-reviewers 
Could you help review this change?
Thanks very much.

**Review by pvchupin — APPROVED** [review]

**Pull request merged**
