### PR TITLE
[SYCL][ESIMD] Update vc-intrinsics

### PR DESCRIPTION
**Pull request by asidoren-intel**
This update will allow to remove the temporary workaround brought by #2015 pull request.

### CODE REVIEW

**Review by bader — APPROVED** [review]
What tests cover this change?

**Comment by asidoren-intel** [comment]
> What tests cover this change?

Each ESIMD test covers this change, e.g. llvm/test/SYCLLowerIR/esimd_lower_intrins.ll

**Comment by bader** [comment]
> > What tests cover this change?
> 
> Each ESIMD test covers this change, e.g. llvm/test/SYCLLowerIR/esimd_lower_intrins.ll

Are all ESIMD tests fail w/o this patch?
I meant: is there any observable change from this patch, which is reflected in the tests?

The description mentioned:

> This update will allow to remove the temporary workaround brought by #2015 pull request.

Why don't we remove the workaround in this PR to confirm this statement?

**Comment by asidoren-intel** [comment]
Well.. I've mistaken a bit. The vc-intrinsics change that I wanted to propagate here is only in SPIRV reader adapter, so, it is not necessary to bring it in dpc++. The patch removal will be possible when IGC is updated with the required vc-intrinsics version.

**Pull request closed without merging**
