### PR TITLE
[SYCL][NATIVECPU] Fix linking bug 

### PR DESCRIPTION
**Pull request by PietroGhg**
This fixes a bug were functions called by the kernel were linked to the host version of the function, and lead to uncurrect behaviour when the function is defined differently between the host and the device.

### CODE REVIEW

**Comment by PietroGhg** [comment]
Hi @intel/dpcpp-devops-reviewers, is it possible to trigger the windows pipelines for this PR? Thanks :)

**Comment by steffenlarsen** [comment]
> Hi @intel/dpcpp-devops-reviewers, is it possible to trigger the windows pipelines for this PR? Thanks :)

Absolutely! We are currently letting PRs through slowly to ensure we solve the issue with Windows CI appropriately, so it may take some time before this PR gets its turn. Sorry for the inconvenience!

**Comment by PietroGhg** [comment]
Hi @steffenlarsen , is it possible to re-trigger the windows pipelines on this PR? Should I merge `sycl` into this branch first?

**Comment by steffenlarsen** [comment]
@PietroGhg - You might need to push a merge commit.

**Review by uwedolinsky — APPROVED** [review]

**Comment by PietroGhg** [comment]
Hi @intel/llvm-gatekeepers, I think that this is ready to be merged :)

**Pull request merged**
