### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW31)

### PR DESCRIPTION
**Pull request by dwoodwor-intel**
LLVM: llvm/llvm-project@46e6dd84b778dd2e30368183fec265beceecdd0f
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@c8cd2f6895091f84823d94a661753c0a9765a7a7

### CODE REVIEW

**Comment by dwoodwor-intel** [comment]
The documentation build failure is a simple whitespace fix, so I've pushed a fix for that. The cuda lit failures might be more involved—the `linker-wrapper-image.c` one looks like a standard opaque pointer issue, but it already has `-opaque-pointers` flags and they don't seem to be working for some reason. I'm having trouble reproducing the other cuda lit failures because all 8 of those tests pass when I run them locally.

I'll get back to this next week.

**Comment by dwoodwor-intel** [comment]
ProtexIP crashed/was terminated again after running for 16 and a half hours. but there shouldn't be anything problematic in these changes. I'll go ahead with the merge.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Tue 26 Jul 2022 03:16:25 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Tue 26 Jul 2022 03:20:17 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
