### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW20)



### PR DESCRIPTION
**Pull request by jsji**
LLVM: llvm/llvm-project@2051755
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@772c7be

### CODE REVIEW

**Comment by sarnex** [comment]
@againull @kchusha @jsji 

I have a PR to fix the llvm-spirv test failures [here](https://github.com/intel/llvm/pull/9505), feel free to merge it

**Comment by againull** [comment]
> @againull @kchusha @jsji
> 
> I have a PR to fix the llvm-spirv test failures [here](https://github.com/intel/llvm/pull/9505), feel free to merge it

@sarnex Thanks a ton for providing the fix!

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Thu 18 May 2023 08:49:09 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Thu 18 May 2023 08:54:14 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
