### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW47)

### PR DESCRIPTION
**Pull request by jsji**
LLVM: llvm/llvm-project@752c21be68613f92e2de16cd380098cf830bc261
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@f18e64da496cc836628b5a4a2dd7646084333267

### CODE REVIEW

**Comment by jsji** [comment]
>SYCL::basic_tests/reduction/reducer_copy_move_negative.cpp
SYCL::check_device_code/no_offset_error.cpp
SYCL::esimd/block_load_store.cpp
SYCL::esimd/gather_scatter.cpp
SYCL::esimd/simd_copy_align_flags.cpp
SYCL::extensions/properties/properties_kernel_device_has.cpp
SYCL::extensions/properties/properties_kernel_sub_group_size.cpp
SYCL::extensions/properties/properties_kernel_work_group_size.cpp
SYCL::extensions/properties/properties_kernel_work_group_size_hint.cpp
SYCL::warnings/sycl_2020_deprecations.cpp

These are exposed by https://github.com/llvm/llvm-project/commit/aafad2d214246bae4d53ce3178b11486ebc83890
Tracked in 53743.

> Clang::CodeGen/code_align.c
Clang::CodeGenCXX/attr-musttail.cpp
Clang::CodeGenCXX/pragma-gcc-unroll.cpp
Clang::CodeGenCXX/pragma-loop.cpp
Clang::CodeGenCXX/pragma-unroll.cpp
Clang::CodeGenCXX/stmtexpr.cpp
Clang::CodeGenSYCL/intel-fpga-ivdep-array.cpp
Clang::CodeGenSYCL/intel-fpga-loops.cpp
Clang::CodeGenSYCL/loop_unroll.cpp
Clang::CodeGenSYCL/loop_unroll_host.cpp
Clang::CodeGenSYCL/max-concurrency.cpp
Clang::PCH/delayed-template-with-pragma.cpp
Clang::Sema/code_align_ast.c
Clang::SemaCXX/attr-musttail.cpp
Clang::SemaSYCL/intel-fpga-loops.cpp
Clang::SemaSYCL/loop_unroll.cpp

These are caused/exposed by https://github.com/intel/llvm/commit/48ff35415c06cdbd9115bfe5318449afddcc7ff5
Tracked in 53802.

**Comment by jsji** [comment]
- [ ] [[CI] Only run libcxx in llvm repo](https://github.com/intel/llvm/pull/12003/commits/e033650d2d9ae82612fd698c5b845403f840a118) This is cherry-pick of https://github.com/llvm/llvm-project/commit/85ee351aa7b1112b1b9ac2e0ead547e9af8712b5 . **No review required.**
 - [ ]  [Revert "Revert "[AMDGPU] PromoteAlloca: Handle load/store subvectors …](https://github.com/intel/llvm/pull/12003/commits/97cb50e92fdac7293e3991c2b9e8ecc651f6cc5a) This is undo a revert made before , tracked in https://github.com/intel/llvm/issues/11857. **No review required.**
 - [ ] [[SYCL][Sema] Fix missing return due to conflict](https://github.com/intel/llvm/pull/12003/commits/bbb0d8a356297fa503a15b2a047b502327be11cd) , [[SYCL][CodeGenModule] Fix conflcit resolution for](https://github.com/intel/llvm/pull/12003/commits/5a87103286c9ab28cde23e72a23f193d62358d0b) https://github.com/intel/llvm/commit/ed73121ffeb636e75162f116bfeca56e7ec310de , [[SYCL] Fix conflict resoluition in CGLoopInfo](https://github.com/intel/llvm/pull/12003/commits/8d27c2ce3eabbfce72366e25d0ea6e3641fe6fc1)  Several conflict resolution corrections to fix failures.  **Reviewed by [smanna12](https://github.com/smanna12)**
 - [ ] [[SYCL][Sema] Disable deprecated warning for sycl](https://github.com/intel/llvm/pull/12003/commits/8cc6e9ecc195276c7ca162e965abbed22f5b38e1) Workaround fix to disable new deprecated warning in templates headers. **Reviewed by [premanandrao](https://github.com/premanandrao)**

**Comment by jsji** [comment]
@bader @intel/llvm-gatekeepers This is ready for merge. Thanks.

**Comment by bader** [comment]
> [x] [[SYCL][Sema] Disable deprecated warning for sycl](https://github.com/intel/llvm/pull/12003/commits/8cc6e9ecc195276c7ca162e965abbed22f5b38e1) Workaround fix to disable new deprecated warning in templates headers. **Reviewed by [premanandrao](https://github.com/premanandrao)**

@jsji, please, open a tracker to replace this workaround with a proper solution.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Tue 28 Nov 2023 05:08:16 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Tue 28 Nov 2023 05:14:04 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Comment by jsji** [comment]
> > [x] [[SYCL][Sema] Disable deprecated warning for sycl](https://github.com/intel/llvm/pull/12003/commits/8cc6e9ecc195276c7ca162e965abbed22f5b38e1) Workaround fix to disable new deprecated warning in templates headers. **Reviewed by [premanandrao](https://github.com/premanandrao)**
> 
> @jsji, please, open a tracker to replace this workaround with a proper solution.

Thanks. It was tracked in 53743.

**Pull request merged**
