### PR TITLE
[SYCL] Improve sycl::event::get_profiling_info exception message if default constructed 

### PR DESCRIPTION
**Pull request by raaiq1**
The default constructed sycl::event would emit a misleading message when querying profiling information. The message would assume a queue is attached to such sycl::event, even if it's not the case. Added a condition to handle such case, and emit a more proper message, and updated appropriate unit test.

### CODE REVIEW

**Review by v-klochkov — COMMENTED** [review]
The additional field is added _solely_ for the purpose of slightly more clear exception message....
I do not object, but also do not support the idea.
Would be useful to hear from @bader and @steffenlarsen

**Review by steffenlarsen — COMMENTED** [review]
The clearer error message is definitely a great addition, but I think it can be done without the new member. Sadly we cannot base it on whether the `weak_ptr` has expired, as we could have an event for which the associated queue had profiling info but has since been destroyed. However, [std::weak_ptr<T>::owner_before](https://en.cppreference.com/w/cpp/memory/weak_ptr/owner_before) specifies that

> The order is such that two smart pointers compare equivalent only if they are both empty or if they both own the same object ...

Using this, we can determine if there was a (potentially now expired) `queue` associated with `event`. See https://godbolt.org/z/3v8144j1o for an example of this. Of the top of my head, the only potential problem I could see here would be if at some point `reset` is called on the `weak_ptr`, but I don't see why we would ever need that.

On a different note, could you please add a test-case to `GetProfilingInfo` for the new exception message?

**Review by steffenlarsen — DISMISSED** [review]
LGTM!

**Review by steffenlarsen — APPROVED** [review]

**Comment by raaiq1** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1114

**Comment by raaiq1** [comment]
\verify with https://github.com/intel/llvm-test-suite/pull/1120

**Comment by raaiq1** [comment]
\verify with https://github.com/intel/llvm-test-suite/pull/1120

**Comment by bader** [comment]
I think it should be forward slash i.e. /verify, not \verify.

**Comment by raaiq1** [comment]
Thanks for pointing that out

**Comment by raaiq1** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1120

**Comment by raaiq1** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1120

**Comment by raaiq1** [comment]
@intel/llvm-gatekeepers  ping to merge commit

**Pull request merged**
