### PR TITLE
[Buildbot] Update Windows GPU driver to 27.20.100.9168

### PR DESCRIPTION
**Pull request by yinyangsx**
Signed-off-by: yinyangsx <yin.yang@intel.com>

### CODE REVIEW

**Review by vladimirlaz — APPROVED** [review]

**Comment by bader** [comment]
@yinyangsx, please, run Jenkins/Summary test suite.

**Comment by vladimirlaz** [comment]
@yinyangsx, could you please confirm that all windows jobs in Jenkins/Summary will be executed on machine with updated driver?

**Comment by yinyangsx** [comment]
> @yinyangsx, could you please confirm that all windows jobs in Jenkins/Summary will be executed on machine with updated driver?

Hi @vladimirlaz , as far as know, all windows machines of Jenkins/Summary already have been updated with new driver by IT team.

**Comment by yinyangsx** [comment]
This PR is ready, @bader, @vladimirlaz, could you help merge it, please?

**Review by yanfeng3721 — APPROVED** [review]

**Review by vladimirlaz — APPROVED** [review]

**Comment by vladimirlaz** [comment]
The PR should be merged together with https://github.com/intel/llvm-test-suite/pull/133

**Review by bader — COMMENTED** [review]
The change looks good to me.
@vladimirlaz, please, merge it when all tests pass (including SYCL conformance tests).

**Pull request merged**
