### PR TITLE
[SYCL][ABI-Break] Implement property interface for local_accessor &

### PR DESCRIPTION
**Pull request by KornevNikita**
usm_allocator

### CODE REVIEW

**Comment by aelovikov-intel** [comment]
Is there a test being added for this?

**Comment by KornevNikita** [comment]
@aelovikov-intel not yet and I'm not sure if we can do this, as these classes don't have any properties yet

**Comment by KornevNikita** [comment]
This is an additional patch for https://github.com/intel/llvm/pull/6614

**Review by aelovikov-intel — DISMISSED** [review]
The change looks ok by itself but I lack experience to tell if something is missing or reason about the bigger picture. Please consider asking other people if you want to have a reviewer with deeper knowledge in the area :)

**Comment by aelovikov-intel** [comment]
Also, can you increment the dev version in sycl/CMakeLists.txt ?

**Comment by KornevNikita** [comment]
@steffenlarsen @AlexeySachkov could you take a look please?

**Review by steffenlarsen — APPROVED** [review]
LGTM!

**Comment by KornevNikita** [comment]
Re-trigger test

**Comment by KornevNikita** [comment]
I believe these fails are unrelated, since it was okay for the first run.

**Comment by KornevNikita** [comment]
Re-trigger tests

**Comment by KornevNikita** [comment]
Re-trigger (sorry for spam, I believe this is the last attempt)

**Pull request merged**
