### PR TITLE
UR fix for MaxRegsPerBlock check in setKernelParams

### PR DESCRIPTION
**Pull request by rafbiels**
Bring the fix for MaxRegsPerBlock check from https://github.com/oneapi-src/unified-runtime/pull/1299 to `intel/llvm`. No changes needed other than updating the UR repo hash.

### CODE REVIEW

**Comment by kbenzie** [comment]
@rafbiels could you pull in the latest changes from the sycl branch to see if the test failure goes away?

**Comment by rafbiels** [comment]
rebased onto the tip of the `sycl` branch

**Comment by rafbiels** [comment]
Ah I need to update https://github.com/oneapi-src/unified-runtime/pull/1299 to the tip of UR main as well, don't I?

**Comment by kbenzie** [comment]
> Ah I need to update [oneapi-src/unified-runtime#1299](https://github.com/oneapi-src/unified-runtime/pull/1299) to the tip of UR main as well, don't I?

yeah, that could also be the cause of these failures.

**Comment by rafbiels** [comment]
Rebased the UR branch on top of the same hash as used in this llvm branch. Can we run the CI again, please?

**Review by kbenzie — APPROVED** [review]

**Comment by kbenzie** [comment]
@intel/llvm-gatekeepers please merge

**Comment by sommerlukas** [comment]
Unrelated post-commit failures:
```
Failed Tests (2):
  SYCL :: ESIMD/unified_memory_api/scatter_lacc_dg2_pvc.cpp
  SYCL :: Reduction/reduction_range_3d_rw_reducer_skip.cpp
```

**Comment by aelovikov-intel** [comment]
> Unrelated post-commit failures:
> 
> ```
> Failed Tests (2):
>   SYCL :: ESIMD/unified_memory_api/scatter_lacc_dg2_pvc.cpp
>   SYCL :: Reduction/reduction_range_3d_rw_reducer_skip.cpp
> ```

Has `ESIMD/unified_memory_api/scatter_lacc_dg2_pvc.cpp` been reported anywhere? Just claiming it's unrelated when it fails in every post-commit isn't enough.

**Comment by sommerlukas** [comment]
> Has `ESIMD/unified_memory_api/scatter_lacc_dg2_pvc.cpp` been reported anywhere? Just claiming it's unrelated when it fails in every post-commit isn't enough.

I created #12769 and also commented on the PR introducing the test (#12675).

**Pull request merged**
