### PR TITLE
[SYCL] Re-enable SemaSYCL/sycl-dllimport-dllexport

### PR DESCRIPTION
**Pull request by Fznamznon**
The test was XFAIL-ed after pulldown some time ago.
This fixes https://github.com/intel/llvm/issues/2758

### CODE REVIEW

**Review by smanna12 — APPROVED** [review]
The test is not labelled as XFAIL in down stream. i remember that i reviewed same test changes by @jyu2-git a month ago to resolve pulldown LIT test failure. 

LGTM.

**Review by jyu2-git — APPROVED** [review]
LGTM.  I do remember there is change for attribute, previous attribute in declaration will be take effect.

**Comment by dm-vodopyanov** [comment]
@Fznamznon can you please address clang-format failures?

**Comment by Fznamznon** [comment]
> @Fznamznon can you please address clang-format failures?

Not really. This seems to be a bug in clang-format or in scripts that run it. It happens when the first line of the file is deleted. Though, I agreed to volunteer to look at it during offline team meeting, but I haven't got a spare time to look at it yet and this bug shouldn't patches from merge.

**Review by premanandrao — APPROVED** [review]

**Comment by Fznamznon** [comment]
Ping.

**Comment by smanna12** [comment]
@dm-vodopyanov, could you merge this PR? Thanks.

**Pull request merged**
