### PR TITLE
[SYCL] Remove unexpected double in complex SPIRV for float support

### PR DESCRIPTION
**Pull request by jinge90**
Signed-off-by: gejin <ge.jin@intel.com>

### CODE REVIEW

**Comment by bader** [comment]
I think there is a better way to solve this problem.
We should make use of `-cl-single-precision-constant` option that emits f32 values to LLVM for OpenCL C doubles.

**Comment by vzakhari** [comment]
> I think there is a better way to solve this problem.
> We should make use of `-cl-single-precision-constant` option that emits f32 values to LLVM for OpenCL C doubles.

Alexey, is there such an option for C++ compiler?

**Comment by bader** [comment]
> > I think there is a better way to solve this problem.
> > We should make use of `-cl-single-precision-constant` option that emits f32 values to LLVM for OpenCL C doubles.
> 
> Alexey, is there such an option for C++ compiler?

I don't know, but my point is that the same problem might appear in the user's code and compiler is able to help the user to identify unsupported type uses or even fix them. The necessary logic is implemented in the compiler, we just need to expose it to the user.
If C++ doesn't have this option we can add SYCL mode alias for `-cl-single-precision-constant`.
Does it make sense?

**Comment by vzakhari** [comment]
> > > I think there is a better way to solve this problem.
> > > We should make use of `-cl-single-precision-constant` option that emits f32 values to LLVM for OpenCL C doubles.
> > 
> > 
> > Alexey, is there such an option for C++ compiler?
> 
> I don't know, but my point is that the same problem might appear in the user's code and compiler is able to help the user to identify unsupported type uses or even fix them. The necessary logic is implemented in the compiler, we just need to expose it to the user.
> If C++ doesn't have this option we can add SYCL mode alias for `-cl-single-precision-constant`.
> Does it make sense?

Sure, it makes sense.  I was just hoping to use that option right now.

**Comment by bader** [comment]
> > > > I think there is a better way to solve this problem.
> > > > We should make use of `-cl-single-precision-constant` option that emits f32 values to LLVM for OpenCL C doubles.
> > > 
> > > 
> > > Alexey, is there such an option for C++ compiler?
> > 
> > 
> > I don't know, but my point is that the same problem might appear in the user's code and compiler is able to help the user to identify unsupported type uses or even fix them. The necessary logic is implemented in the compiler, we just need to expose it to the user.
> > If C++ doesn't have this option we can add SYCL mode alias for `-cl-single-precision-constant`.
> > Does it make sense?
> 
> Sure, it makes sense. I was just hoping to use that option right now.

It's possible for the libraries written in OpenCL C/C++ kernel language, which seems to be a good option for SPIR target libraries.

**Pull request merged**
