### PR TITLE
Revert "[SYCL] Enable PI unit testing on multiple plugins. (#1647)"

### PR DESCRIPTION
**Pull request by vladimirlaz**
This reverts commit 98119bd1fd25c301deb7007b346b2f95a249a5d8 due to regressions:
  -  SYCL-Unit::CudaInteropGetNativeTests.interopTaskGetMem (http://ci.llvm.intel.com:8010/#/builders/37/builds/859, http://ci.llvm.intel.com:8010/#/builders/37/builds/869)
 - SYCL-Unit :: pi/./PiTests/* tests for OpenCL BE on machine without OpenCL RT installed (https://github.com/intel/llvm/runs/673664063)

### CODE REVIEW

**Comment by StuartDAdams** [comment]
Sorry to see the new test is causing regressions on systems with no available OpenCL plugin. I think it would be more valuable to address the issues that the unit test exposed, rather than removing the unit test. Myself and the team at codeplay are happy to help to fix this issue.

**Comment by Ruyk** [comment]
I am curious, how did this get merged in the first place? is there a different group of test being run on master than per PR?

**Comment by bader** [comment]
> Sorry to see the new test is causing regressions on systems with no available OpenCL plugin. I think it would be more valuable to address the issues that the unit test exposed, rather than removing the unit test. 

This is not the reason we revert the patch because developers are expected to have OpenCL installed and this issue impact is minimal - post-commit status only.

The main reason is that pre-commit checks are failing and it impacts the development process.

> Myself and the team at codeplay are happy to help to fix this issue.

Thanks! I appreciate your readiness to help and from our side we are committed to provide any information you need to fix this issue.

> I am curious, how did this get merged in the first place? 

I don't know, but it's either sporadic problem or conflict with other PR.

**Comment by bader** [comment]
@StuartDAdams, could you investigate the problems I reported to in https://github.com/intel/llvm/pull/1647 and re-submit the fixed patch, please?

**Pull request merged**
