### PR TITLE
[Buildbot] Remove FPGA HW dependency

### PR DESCRIPTION
**Pull request by yanfeng3721**

### CODE REVIEW

**Comment by bader** [comment]
@yanfeng3721, what are next steps for this PR?

**Comment by bader** [comment]
I'm closing this PR as testing is done.
@yanfeng3721, please, use a private fork to open a PR i.e. do not push private branches to intel/llvm repository.

**Comment by yanfeng3721** [comment]
> @yanfeng3721, what are next steps for this PR?

Hi @bader, QA would like to remove the FPGA HW dependency from opens ource CI since the test result shows there is no testing related to FPGA HW.  Add @cdai2.

**Comment by MrSidims** [comment]
>> Hi @bader, QA would like to remove the FPGA HW dependency from opens ource CI since the test result shows there is no testing related to FPGA HW. Add @cdai2.

I would expect just an opposite: add this testing if not in pre-commit, but at least in nightly/weekly testing (which I assume uses the same dependency files).

**Comment by bader** [comment]
I don't understand what's going in this PR. AFAIK, BuildBot doesn't have any dependencies on FPGA HW as it covers only CPU and GPU devices. FPGA functionality is tested using emulator, so there should be no dependency on FPGA HW.

@yanfeng3721, you should probably review this patch with someone who understands how BuildBot infrastructure works.

I'm closing this PR as it violates our contribution guide. @yanfeng3721, please, create a pull request from a private fork. See https://github.com/intel/llvm/blob/sycl/CONTRIBUTING.md#development for more details.

**Comment by yanfeng3721** [comment]
>> I'm closing this PR as it violates our contribution guide. @yanfeng3721, please, create a pull request from a private fork. See https://github.com/intel/llvm/blob/sycl/CONTRIBUTING.md#development for more details.

Sure,  it looks like if I am editing the source code directly, it will not work on my private fork. Will pay more attention next time.

**Pull request closed without merging**
