### PR TITLE
[SYCL] Reland community changes to support RawAddress

### PR DESCRIPTION
**Pull request by premanandrao**
As it was a complex set of changes
https://github.com/llvm/llvm-project/commit/84780af4b02cb3b86e4cb724f996bf8e02f2f2e7 
was not applied during normal pulldown.  This PR relands that commit as well as a couple of
additional fixes needed.

### CODE REVIEW

**Review by AlexeySachkov — APPROVED** [review]

**Comment by premanandrao** [comment]
@intel/dpcpp-cfe-reviewers, can I please get a review on this?   You only need to review the minor changes in my second commit.   The first commit is a community cherry-pick.

**Review by smanna12 — APPROVED** [review]
LGTM. Thanks

**Comment by elizabethandrews** [comment]
Can you explain why the additional fixes were needed?

**Comment by premanandrao** [comment]
> Can you explain why the additional fixes were needed?

Not sure what you are asking, but the getPointer member function was removed from the Address class.

**Comment by elizabethandrews** [comment]
> > Can you explain why the additional fixes were needed?
> 
> Not sure what you are asking, but the getPointer member function was removed from the Address class.

I did not realize the code you modified was not present in community. I was wondering why the original PR did not make these changes.

**Review by elizabethandrews — APPROVED** [review]

**Comment by premanandrao** [comment]
@intel/llvm-gatekeepers, can this be merged please?   The test failure about code formatting points to community changes not the additional changes that I made.

**Comment by ldrumm** [comment]
Can you please manually squash the commits so author attribution is correct?

image

**Comment by premanandrao** [comment]
> Can you please manually squash the commits so author attribution is correct?
> 
> Since the bulk of the work here is by @ahatanak

Thank you for pointing this out.   Should be fixed now.   (Unless I messed it up.)

**Comment by bader** [comment]
> Can you please manually squash the commits so author attribution is correct?
> 
> image
> 
> Since the bulk of the work here is by @ahatanak

https://github.com/intel/llvm/commit/4563116c5e5ad5726451597e91ddcffe56f0e675 - the author attribution was correct before the manual squash. As far as I can tell it's preserved by GitHub squash and merge, so manual squash is not needed. @ldrumm, did I miss anything?

**Comment by premanandrao** [comment]
@intel/llvm-gatekeepers, will it help if I commit this in as two separate patches?  One: that is exclusively the community changes and two: my changes?   For a brief period in between, our builds will break, but my changes will fix that.   That will keep the authorship entirely separate.

(There is further downstream work that I need to do after this is merged here.   Hence the time sensitivity.)

**Comment by ldrumm** [comment]
No. There's apparently no way to preserve correct authorship, nor the original commit message. We need an admin to merge this manually rather than github do it.

**Comment by ldrumm** [comment]
@stdale-intel  Can you merge this commit manually with the complete, correctly attributed 02b4109935864620e3b4a34b1025c6d94966ce53, please?

**Pull request merged**
