### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW37)

### PR DESCRIPTION
**Pull request by vmaksimo**
LLVM: llvm/llvm-project@cc2d4dc
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@4ccb1b29bbdd0b37ce369d82fa52f8305c7c032c

### CODE REVIEW

**Review by AlexeySachkov — APPROVED** [review]

**Comment by bb-sycl** [comment]
Fri Sep 10 09:10:40 UTC 2021 --- Merge failed with error: Comment user is not in admin group or doesn't have merge right for target branch. Please contact with admins of the repo if there is any question.

**Comment by bb-sycl** [comment]
Fri Sep 10 09:39:37 UTC 2021 --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Fri Sep 10 09:42:53 UTC 2021 --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
