### PR TITLE
[SYCL][COMPAT] Added Complex muladd to syclcompat

### PR DESCRIPTION
**Pull request by Alcpz**
Adds the documentation, functionality and tests for complex multiplication addition to SYCLcompat.

### CODE REVIEW

**Comment by JackAKirk** [comment]
@jle-quel does this overlap with your sycl::complex extension?

**Comment by jle-quel** [comment]
> @jle-quel does this overlap with your sycl::complex extension?

Yes, it does.
The `sycl::vec<ValueT, 2>` type could be replaced by `sycl::ext::oneapi::experimental::complex` as well as the `marray`.
Finally, the `conj` operation is already part of the `sycl::complex` API.

**Comment by Alcpz** [comment]
> > @jle-quel does this overlap with your sycl::complex extension?
> 
> Yes, it does. The `sycl::vec<ValueT, 2>` type could be replaced by `sycl::ext::oneapi::experimental::complex` as well as the `marray`. Finally, the `conj` operation is already part of the `sycl::complex` API.

I've changed the implementation to go through the sycl::complex API, thanks for the input there. We have a dependency that use these functions so I cannot remove them.

**Review by AidanBeltonS — APPROVED** [review]
Looks good to me

**Comment by Alcpz** [comment]
@intel/llvm-gatekeepers PR is ready for merging. Thanks

**Pull request merged**
