### PR TITLE
[SYCL] Fix --shared-libs builds for generic AS printf support

### PR DESCRIPTION
**Pull request by AGindinson**
Fixes post-commit failures for https://github.com/intel/llvm/pull/5069.

Signed-off-by: Artem Gindinson <artem.gindinson@intel.com>

### CODE REVIEW

**Comment by AGindinson** [comment]
@intel/llvm-gatekeepers, would it be OK if this got merged ahead of ESIMD code-owner approval? This aims to fix https://github.com/intel/llvm/runs/4604129664?check_suite_focus=true. I've verified locally via a `--shared-libs` build.

**Review by AlexeySachkov — APPROVED** [review]

**Comment by AGindinson** [comment]
Failures in `Basic/get_backend.cpp` and `XPTI` tests do not seem related. Should I file the issue for these?

**Comment by AlexeySachkov** [comment]
> Failures in `Basic/get_backend.cpp` and `XPTI` tests do not seem related. Should I file an issue for these?

Absolutely, if we don't have such already. Also, failing (even sporadically) tests should be disabled

**Comment by bader** [comment]
> Failures in `Basic/get_backend.cpp` and `XPTI` tests do not seem related. Should I file an issue for these?

You shouldn't ask, you should always do this. It's your pull request and you are responsible for passing pre-commit checks.

FYI: https://github.com/intel/llvm-test-suite/pull/659 - fix for `XPTI` test. 
https://github.com/intel/llvm-test-suite/pull/660 - a workaround for `Basic\get_backend.cpp` test.

**Comment by bader** [comment]
@kbobrovs, @kychendev, @sndmitriev, @v-klochkov, ping.

**Comment by bader** [comment]
@kbobrovs, @kychendev, @sndmitriev, @v-klochkov, I'm merging this to fix post-commit validation.
If you have any concerns, please, leave them in the comments.

**Pull request merged**
