### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW21 2024)

### PR DESCRIPTION
**Pull request by iclsrc**
LLVM: llvm/llvm-project@781b13538e55a42b2d02bb4d21779f15ff8a640c
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@04972917552b08e6cb4e971c7b1707f68e1aa43e

### CODE REVIEW

**Comment by jsji** [comment]
This is ready for review.

- [ ] [Add AS for Globals to SPIR & SPIRV datalayouts] (https://github.com/intel/llvm/pull/13894/commits/423ffdb2edf7c53a7b57f7dfb84390de25e038b3) Sync changes from community to update addrespaces for SPIR.
- [ ] [Disable SPIR triple RUN line in bitfield-access-tail temporaily](https://github.com/intel/llvm/pull/13894/commits/b3ea5126387ae630ad455be6e952a88136ed1aa0)  This start to fail after SPIR data layout change in [Add AS for Globals to SPIR & SPIRV datalayouts](https://github.com/intel/llvm/pull/13894/commits/423ffdb2edf7c53a7b57f7dfb84390de25e038b3) 
- [ ] [Disable SYCL Device RUNs till we determine required behavior](https://github.com/intel/llvm/pull/13894/commits/6257b0ab2747b4461d2ae43bc1e0f984bece3323) , ,  [Disable SYCL Device RUNs till we determine required behavior](https://github.com/intel/llvm/pull/13894/commits/e4a2c453f465541cdc521cd59a29beac0e818749) Temporarily disable some SPIR RUN lines after addressspace change -- Most tests start to fail after [10edb4991c12738e60843d55cd9edbf6d702d9eb](https://github.com/intel/llvm/commit/10edb4991c12738e60843d55cd9edbf6d702d9eb) , @elizabethandrews had a quick look .  "For now I think it makes sense disabling these new RUN lines locally to unblock pulldown. I don't think this change actually makes sense from sycl perspective because we do not support RTTI in sycl kernels and it looks like this change is changing address space for that".

@intel/dpcpp-cfe-reviewers  Can you have a look? Thanks.

**Comment by jsji** [comment]
@intel/dpcpp-cfe-reviewers  Can you have a look at the 4 commits above, and leave comments/approvals explicitly so that this can be merged. Thanks.

**Review by elizabethandrews — APPROVED** [review]

**Comment by bader** [comment]
> This is ready for review.
> 
> * [ ]  [Add AS for Globals to SPIR & SPIRV datalayouts] ([423ffdb](https://github.com/intel/llvm/commit/423ffdb2edf7c53a7b57f7dfb84390de25e038b3)) Sync changes from community to update addrespaces for SPIR.
> * [ ]  [Disable SPIR triple RUN line in bitfield-access-tail temporaily](https://github.com/intel/llvm/pull/13894/commits/b3ea5126387ae630ad455be6e952a88136ed1aa0)  This start to fail after SPIR data layout change in [Add AS for Globals to SPIR & SPIRV datalayouts](https://github.com/intel/llvm/pull/13894/commits/423ffdb2edf7c53a7b57f7dfb84390de25e038b3)
> * [ ]  [Disable SYCL Device RUNs till we determine required behavior](https://github.com/intel/llvm/pull/13894/commits/6257b0ab2747b4461d2ae43bc1e0f984bece3323) , ,  [Disable SYCL Device RUNs till we determine required behavior](https://github.com/intel/llvm/pull/13894/commits/e4a2c453f465541cdc521cd59a29beac0e818749) Temporarily disable some SPIR RUN lines after addressspace change -- Most tests start to fail after [10edb4991c12738e60843d55cd9edbf6d702d9eb](https://github.com/intel/llvm/commit/10edb4991c12738e60843d55cd9edbf6d702d9eb) , @elizabethandrews had a quick look .  "For now I think it makes sense disabling these new RUN lines locally to unblock pulldown. I don't think this change actually makes sense from sycl perspective because we do not support RTTI in sycl kernels and it looks like this change is changing address space for that".
> 
> @intel/dpcpp-cfe-reviewers Can you have a look? Thanks.

This PR disables a number of tests. @jsji, could you make sure that we have an issue to re-enable all these tests ASAP, please?

**Comment by jsji** [comment]
> This PR disables a number of tests. @jsji, could you make sure that we have an issue to re-enable all these tests ASAP, please?

yes,  @bader . @elizabethandrews has been looking at those tests. Tracked in internal tracker 58687.

**Comment by jsji** [comment]
@bader @intel/llvm-gatekeepers Can someone help to issue a `/merge`?  Thanks

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Thu 30 May 2024 06:26:27 AM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Thu 30 May 2024 06:30:49 AM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
