### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW20)

### PR DESCRIPTION
**Pull request by pvchupin**
LLVM: https://github.com/llvm/llvm-project/commit/8b626a2caa672a174829105ff7749d8d9a080f2a
SPIRV-LLVM-Translator: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/f727f4d

### CODE REVIEW

**Comment by asudarsa** [comment]
It looks good from the SPIRV side. I will check from the DPCPP tools perspective soon. Thanks.

**Comment by pvchupin** [comment]
Thanks @asudarsa. I don't expect actual reviews in these pulldown PRs as these are usually hundreds of changes coming from upstream projects (llvm or spirv), they've been reviewed and merged there and we just picking these up as is.
Sometimes they may produce problems in our downstream project and may require changes on top. If there is anything blocking I'll raise it separately. It seems this is almost good to go. I'm running some final checks.

**Comment by pvchupin** [comment]
Remaining testing issues were fixed already.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Tue 10 May 2022 09:05:42 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Tue 10 May 2022 09:09:31 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Comment by bader** [comment]
@pvchupin, this PR broke the build on Windows platform.

```
d:\github\_work\llvm\llvm\build\bin\..\include\sycl\CL/sycl/half_type.hpp:390:17: error: use of overloaded operator '-' is ambiguous (operand type 'const sycl::detail::half_impl::StorageT' (aka 'const sycl::detail::host_half_impl::half_v2'))
    return half(-other.Data);
                ^~~~~~~~~~~
```

**Pull request merged**
