### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW22 2024)

### PR DESCRIPTION
**Pull request by iclsrc**
LLVM: llvm/llvm-project@73e22ff
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@d4098cdd72bce730133d44e72b30f6198322fe46

### CODE REVIEW

**Comment by jsji** [comment]
This is ready for review.
- [ ] [Fix lit fails associated with capitalization changes in error messages](https://github.com/intel/llvm/pull/13969/commits/dd9efc6a34028660686c66e2d8bd991a6585cafe) 
- [ ] [[Clang] Format diagnostic message in](https://github.com/intel/llvm/pull/13969/commits/dadc1ff47f6df309f154920ed08320e89fda581a) https://github.com/intel/llvm/commit/7ed3c29907bf452a6a14d99767c1a0cce1487f96 [with community convention.](https://github.com/intel/llvm/pull/13969/commits/dadc1ff47f6df309f154920ed08320e89fda581a)

These two are trivial fixes in tests or message. @intel/dpcpp-cfe-reviewers  Can someone have a quick look?

**Review by premanandrao — APPROVED** [review]

**Review by premanandrao — APPROVED** [review]

**Comment by jsji** [comment]
@intel/llvm-gatekeepers Can someone help to issue a `/merge`. Thanks!

**Comment by asudarsa** [comment]
Is it ok for PR to be in 'draft' state when we issue '/merge'?

Thanks

**Comment by jsji** [comment]
I think so.  @bader  recommended to keep the PR in *draft* state to avoid sending out notifications for unintended reviewers.

**Comment by sarnex** [comment]
Not sure if I have permission, but if I do, it was a pleasure serving with all of you.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Wed 26 Jun 2024 03:54:58 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Wed 26 Jun 2024 03:59:15 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
