### PR TITLE
[SYCL] Fix ABI break caused by changes in CG and CGTYPE

### PR DESCRIPTION
**Pull request by denis-kabanov**
Fix ABI break on windows by adding back old names for CG and CGTYPE

### CODE REVIEW

**Review by dm-vodopyanov — APPROVED** [review]
LGTM

**Comment by denis-kabanov** [comment]
Patch failed on unrelated changes: http://icl-jenkins.sc.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FLin%2FLLVM_Test_Suite/detail/LLVM_Test_Suite/6647/pipeline/
On test "Reduction/reduction_range_1d_s1_rw.cpp".
Ticket on this problem was created.
I'm going to restart Jenkins/Precommit.

**Comment by bader** [comment]
> I'm going to restart Jenkins/Precommit.

Please, disable `Reduction/reduction_range_1d_s1_rw.cpp` first. Otherwise it might fail again.

**Comment by dm-vodopyanov** [comment]
> Please, disable Reduction/reduction_range_1d_s1_rw.cpp first. Otherwise it might fail again.

https://github.com/intel/llvm-test-suite/pull/396

**Pull request merged**
