### PR TITLE
[SYCL][NFC] Do not use non-standard aliases in image utils

### PR DESCRIPTION
**Pull request by AlexeySachkov**
SYCL 2020 spec do not contain definition of aliases like `cl_float4` and therefore we can't use them in our implementation.

The lack of such aliases may be a mistake in the spec, but SYCL 2020 images do not reference any `cl_*` types anyway and modified code is mostly for images support on host. It should be fine to switch to new SYCL 2020 aliases and fixed width integer types because they provide the same size guarantees as their `cl_*` counterparts.

### CODE REVIEW

**Comment by AlexeySachkov** [comment]
```
Failed Tests (1):
  SYCL :: OptionalKernelFeatures/is_compatible.cpp
```

This failure is unrelated. It is reported in https://github.com/intel/llvm/issues/8146 and the test is being disabled in https://github.com/intel/llvm-test-suite/pull/1556

**Comment by aelovikov-intel** [comment]
Why do we have to use `opencl::*` instead of standard SYCL?

**Comment by AlexeySachkov** [comment]
> Why do we have to use `opencl::*` instead of standard SYCL?

I at first though that we can't use other types, because we must follow the spec, but after some investigation I think that not using `opencl::*` types should be ok:
- 99% of the changed code is for operating on images on host, so there is no risk of emitting a call of some built-in with wrong signature
- SYCL 2020 vec aliases have requirements for base type width, making them the same as `opencl::*` aliases we used

I only left a couple of places where we explicitly use `opencl::*` types, because they seem to be a part of user-faced interface defined by SYCL 1.2.1 spec. So, for now I decided not to change them significantly until we dropped 1.2.1 support completely.

**Review by aelovikov-intel — APPROVED** [review]

**Comment by bader** [comment]
Failed Tests (1):
  SYCL :: ESIMD/dword_atomic_smoke_scalar_off.cpp

**Pull request merged**
