### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW30)

### PR DESCRIPTION
**Pull request by vmaksimo**
LLVM: llvm/llvm-project@fb0cf01
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@9e234d9

### CODE REVIEW

**Comment by vmaksimo** [comment]
@steffenlarsen could you please help with build failure on CUDA? I've tried to add `-fdeclare-opencl-builtins` flag to build (https://github.com/intel/llvm/pull/4133/commits/570cb20f5b4b0f519d914bdfa2471d6c8ff52762) but unfortunately it didn't help.

**Comment by steffenlarsen** [comment]
> 
> 
> @steffenlarsen could you please help with build failure on CUDA? I've tried to add `-fdeclare-opencl-builtins` flag to build ([570cb20](https://github.com/intel/llvm/commit/570cb20f5b4b0f519d914bdfa2471d6c8ff52762)) but unfortunately it didn't help.

It looks like the culprit is https://github.com/vmaksimo/llvm/commit/1ccc436558641298603972e509558354d6e96467#diff-a74fdaefdc7b79eeee6d67dc1ed4f57389f15864b3e0cd47efc39a2cde137e3cR149 which disables the implicitly included OpenCL standard headers. This broke libclc a couple months ago, where the solution was https://github.com/intel/llvm/pull/3505. It should be sufficient to revert https://github.com/intel/llvm/commit/64622b64402109fb621989ef46de01632abe36b4.

**Comment by steffenlarsen** [comment]
> It should be sufficient to revert 64622b6.

I have done this locally and it appears to have fixed the issue. Let me know if it doesn't fix it on your end.

**Comment by vmaksimo** [comment]
Hi again @steffenlarsen! We fixed build on CUDA, but there appeared a lit-test failure in `clang/test/Driver/cuda-arch-translation.cu`. It looks like a community test bug, but it can be something else. Possible culprit could be in https://github.com/vmaksimo/llvm/commit/01d3a3dcabaf862581b1d1aee604fcee6a18b240 or https://github.com/vmaksimo/llvm/commit/25629bb45f0a4b8c8e99dbde4f4a7e3d980b9fd7
Could you please take a look? Thanks!

**Comment by steffenlarsen** [comment]
@vmaksimo Looks to me like "v4" isn't appended to the "hip" part of the triple, which the tests expect. I suspect the problem is https://github.com/intel/llvm/commit/ec6122280baa859bdec8c65d2a6e439f35c7471b#diff-eefa159a6526f756b7260f310595827f33f96fd91a8d336f4d20ad8b72738d17R121

**Comment by steffenlarsen** [comment]
> 
> 
> @vmaksimo Looks to me like "v4" isn't appended to the "hip" part of the triple, which the tests expect. I suspect the problem is [ec61222#diff-eefa159a6526f756b7260f310595827f33f96fd91a8d336f4d20ad8b72738d17R121](https://github.com/intel/llvm/commit/ec6122280baa859bdec8c65d2a6e439f35c7471b#diff-eefa159a6526f756b7260f310595827f33f96fd91a8d336f4d20ad8b72738d17R121)

I have tried removing the changes at that line and the test passes. That said, I don't know what the motivation of that change was.

**Comment by bader** [comment]
> > @vmaksimo Looks to me like "v4" isn't appended to the "hip" part of the triple, which the tests expect. I suspect the problem is [ec61222#diff-eefa159a6526f756b7260f310595827f33f96fd91a8d336f4d20ad8b72738d17R121](https://github.com/intel/llvm/commit/ec6122280baa859bdec8c65d2a6e439f35c7471b#diff-eefa159a6526f756b7260f310595827f33f96fd91a8d336f4d20ad8b72738d17R121)
> 
> I have tried removing the changes at that line and the test passes. That said, I don't know what the motivation of that change was.

Tagging @malixian to clarify.

**Comment by malixian** [comment]
> > @vmaksimo Looks to me like "v4" isn't appended to the "hip" part of the triple, which the tests expect. I suspect the problem is [ec61222#diff-eefa159a6526f756b7260f310595827f33f96fd91a8d336f4d20ad8b72738d17R121](https://github.com/intel/llvm/commit/ec6122280baa859bdec8c65d2a6e439f35c7471b#diff-eefa159a6526f756b7260f310595827f33f96fd91a8d336f4d20ad8b72738d17R121)
> 
> I have tried removing the changes at that line and the test passes. That said, I don't know what the motivation of that change was.

The motivation for this change comes from some of our tests. Through testing, we found that if the compiler does not have the option of `mcode_object_version`, even if the version obtained by `getAMDGPUCodeObjectVersion` is V4, the generated amd binary cannot be executed correctly in ROCm. So we use `haveAMDGPUCodeObjectVersionArgument` to determine whether `code_object_version` is included, and only when these two functions are true, will OffloadKind attach v4. In fact, we also found through testing that even if the version obtained by `getAMDGPUCodeObjectVersion` is V4, it is not necessary to attach v4 to OffloadKind, so that there is no problem in rocm execution. 

I can’t explain this phenomenon yet, and I’m also confused about this problem. This may be related to the version of ROCm or the version of llvm.

**Pull request merged**
