### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW40)

### PR DESCRIPTION
**Pull request by sys-ce-bb**
LLVM: llvm/llvm-project@c72d3a0966af
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@deb6ee9

### CODE REVIEW

**Comment by jsji** [comment]
One test case update due to https://github.com/intel/llvm/commit/2da4960f20f7
- [ ] [Update check_device_code math bifs](https://github.com/intel/llvm/pull/11444/commits/1cf5302d43f473565149e22994ae0bcb1b722dfb)

@bader @intel/llvm-gatekeepers  I think anyone can review this and merge . Thanks.

**Comment by ldrumm** [comment]
> LLVM: [llvm/llvm-project@6dc7717](https://github.com/llvm/llvm-project/commit/6dc7717) SPIRV-LLVM-Translator: [KhronosGroup/SPIRV-LLVM-Translator@deb6ee9](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/deb6ee9)
LLVM: https://github.com/llvm/llvm-project/commit/6dc7717 is a 404. That short hash is suspiciously short for a repo of llvm's history. Could you provide the full SHA1 on which this merge is based, please?

**Comment by jsji** [comment]
> LLVM: [llvm/llvm-project@6dc7717](https://github.com/llvm/llvm-project/commit/6dc7717) is a 404. That short hash is suspiciously short for a repo of llvm's history. Could you provide the full SHA1 on which this merge is based, please?

It was https://github.com/intel/llvm/commit/6dc7717bca14d79a7aeacfef485f57ad9738fb2c. Looks like there is a bug in the automation that getting this hash, I will fix it. I will update it to use full hash instead of short one from now on.
I have updated it to be the correct one in https://github.com/intel/llvm/commit/c72d3a0966afd2dcb4421dde922c0faf06d65c0e

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Mon 09 Oct 2023 09:41:04 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Mon 09 Oct 2023 09:46:13 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
