### PR TITLE
fix revert of libclc fp16

### PR DESCRIPTION
**Pull request by calebwat**

### CODE REVIEW

**Comment by ldrumm** [comment]
Why was this patch merged without review?
Why is there no description that describes what was broken to be fixed and to which commit the "revert" refers?
Why was I requested for review?

**Comment by ldrumm** [comment]
> This just seems like a fix to a merge conflict in sycl-web

It would be nice not to have to guess. There are "no description" patches appearing all the time, and it makes it hard to review, and hard to debug later when looking at `git log`

**Comment by jsji** [comment]
> This just seems like a fix to a merge conflict in sycl-web. @jsji - Do you normally open PRs for these or just push directly to sycl-web?

> It would be nice not to have to guess. There are "no description" patches appearing all the time, and it makes it hard to review, and hard to debug later when looking at git log

For conflict resolutions, we normally push directly to `sycl-web`.
And yes, it is recommended to provide informational commit message.

**Comment by calebwat** [comment]
Sorry, I rushed this since it was in the process of causing build failures. This patch deleted a fragment of leftover conflicting code, from a conflict with commit 7e6a73959ae97b1f9476a90290a492ba90cb950d.

**Comment by hdelan** [comment]
+1 to not merging no description PRs. Is this something that @intel/llvm-gatekeepers could enforce, in the same way that commits must be attributable to an email address?

**Comment by sommerlukas** [comment]
This PR is probably missing appropriate tags in the title. 

I have seen PRs, especially smaller fixes, where the PR title was sufficient as a commit message. 

As the email address is currently only enforced manually by gatekeepers, I'm -1 on having gatekeepers enforce this (if we agree to not allow no-description PRs), as it would be an additional burden on gatekeepers.

**Comment by ldrumm** [comment]
Thanks for clarification @calebwat. However, even in a hurry I think there's time to get that into the commit message so please be cognisant that git history matters hugely for future users and debuggers and the difference between a good commit message and a bad one can save weeks of work (true story too horrifying to go into here)


Clearly there's a balance, though:

```
Fix spelling mistake in comment

I found a spelling mistake in a comment and fixed it.
You're going to love my new spelling!
```
:point_up: This is a waste of my reading glasses

```
Fix bug

<no description provided>
```
:point_up: I'm going to scream into a pillow

As to the other points raised: I'm not going to speak on policy, because it's beyond me. However if I'm personally asked to review or merge a patch that looks like it needs a better description, then I will flag this.

One final thing I'm intrigued about regarding the sycl-web branch is that if users have the ability to merge directly for emergent fixes like this, then why does there need to be a merge request associated with it. Isn't that just extra work?

**Comment by jsji** [comment]
> One final thing I'm intrigued about regarding the sycl-web branch is that if users have the ability to merge directly for emergent fixes like this, then why does there need to be a merge request associated with it. Isn't that just extra work?

You are right. For sycl-web branch, for emergent fixes, pulldown coordinators are allowed to push fixes directly *without posting PR*. We don't need such PR.

**Comment by calebwat** [comment]
Yes, this commit was a series of mistakes on my part (the initial incomplete revert, not providing a commit description, then creating an unnecessary PR). I can't speak to policy, but I would expect that issues like this would be very infrequent due to the GitHub permissions required in order for this to occur. Regardless, I apologize for the error and hassle that followed due to the PR.

**Pull request merged**
