### PR TITLE
[SYCL][Graph] Fix access modes not being respected

### PR DESCRIPTION
**Pull request by Bensuo**
- Fix access modes not being respected and creating unnecessary edges
- Update printing E2E tests since output has changed
- Add unit tests for access modes

Addresses #12473

### CODE REVIEW

**Review by EwanC — APPROVED** [review]
LGTM

**Review by cperkinsintel — APPROVED** [review]
lgtm

**Comment by Bensuo** [comment]
@intel/llvm-gatekeepers Can this be merged please?

**Comment by Bensuo** [comment]
Seeing a failing test in the post-commit that's unrelated to this PR, and seems to be failing in other post-commit runs too: https://github.com/intel/llvm/actions/runs/8373464872/job/22927632703

**Pull request merged**
