### PR TITLE
[SYCL] Fix address space for spec constants buffer

### PR DESCRIPTION
**Pull request by dm-vodopyanov**
This patch sets OpenCL global address space for specialization constants
buffer instead of generic one. 

This buffer passes to the kernel function as kernel argument through 
`clSetKernelArg`. According to OpenCL spec, if the argument is declared
to be a pointer of a built-in or user defined type with the `__global` or
`__constant` qualifier, the memory object specified as argument value
must be a buffer object (or nullptr).

The buffer had generic address space, so there was a crash in run time
due to wrong address space.

Although OpenCL specification explicitly states that a string literal
should reside in constant address space, it does not work for SYCL
with "generic by default" address space rules.

Co-authored-by: Vlad Romanov <vlad.romanov@intel.com>

### CODE REVIEW

**Review by AaronBallman — COMMENTED** [review]
Adding @bader as reviewer because this seems somewhat related to existing upstream work in https://reviews.llvm.org/D89909.

It looks like you're missing test coverage for the change. Also, I would appreciate a bit more information about why this is the correct fix (as opposed to checking for nullptr in the crashing API).

**Review by bader — CHANGES_REQUESTED** [review]
LGTM.
It looks like we already have tests, but they were checking for wrong IR.
Please, update kernel-handler.cpp tests.

**Comment by dm-vodopyanov** [comment]
Thanks, fixed tests and updated description.

**Review by bader — APPROVED** [review]

**Review by AaronBallman — APPROVED** [review]
LGTM!

**Pull request merged**
