### PR TITLE
[SYCL] Add missing fabs

### PR DESCRIPTION
**Pull request by hdelan**
`fabs` was missing for Nvidia compilation

### CODE REVIEW

**Comment by jinz2014** [comment]
I have a question. Are the functions specific to Nvidia compilation ?  Thanks.

**Comment by hdelan** [comment]
The symbol is mostly needed for NVidia compilation. Other triples might have `fabs` using a compiler intrinsic. But emission of compiler intrinsics is disabled for NVidia as most intrinsics do not have lowerings for NVPTX

**Comment by hdelan** [comment]
Friendly ping @dm-vodopyanov

**Comment by hdelan** [comment]
Friendly ping @intel/llvm-reviewers-runtime can I get a review on this please?

**Review by steffenlarsen — APPROVED** [review]
LGTM!

**Comment by hdelan** [comment]
Thanks @steffenlarsen !

**Pull request merged**
