### PR TITLE
[SYCLLowerIR] Remove !amdgcn.annotations metadata

### PR DESCRIPTION
**Pull request by frasercrmck**
The `!amdgcn.annotations` metadata was a SYCL-specific addition. The concept of annotations for AMDGPU makes it appear as if it's a mirror of NVVM annotations, when in fact it's just a kernel tagging mechanism. It is not a feature supported by AMD's drivers. We don't need to rely on this, as the functions' calling conventions identify kernels. We also rely on the "sycl-device" module flag to restrict the passes to SYCL code.

This patch re-uses the existing `TargetHelpers` namespace to hide the target-specific logic behind a new class: the `KernelCache`. This provides a way of maintaining a cache of kernels, with optional annotation metadata (it could be expanded in the future with more types of payload). It also provides abstracted ways of handling certain RAUW operations on kernels, though currently only a minimum required to support the two existing patterns. The aim of this is to hide all concept of "annotations" from the passes, and make it an implementation detail of the `KernelCache`.

During this work, it was noticed that our handling of annotations was incomplete. NVVM annotations are not required to only only have 3 operands, as the official documentation shows. It's actually a list of pairs, any one of which may declare the function a kernel. Thus we may have missed valid kernels. Tests have been added to check for this.

The `GlobalOffset` pass was also treating "unsupported" architectures as AMDGPU architectures, so that has been tightened up and the tests have been updated to ensure they actually register as AMD modules.

LIT tests have been cleaned up somewhat, to remove unnecessary features like comments and function linkage types.

Several LIT tests have been converted to use
the `update_test_checks.py` or `update_llc_test_checks.py` scripts, where appropriate. These tools cannot currently emit checks for named metadata nor certain assembly features, so some tests must remain as they are.

### CODE REVIEW

**Review by sommerlukas — APPROVED** [review]
Only reviewed kernel fusion changes, those LGTM.

**Review by premanandrao — APPROVED** [review]
FE changes look okay to me.

**Review by smanna12 — APPROVED** [review]

**Comment by frasercrmck** [comment]
Ping @intel/dpcpp-tools-reviewers, thanks. I'd like to merge this before #14634 which I need to merge before I can continue with #14518 which is high priority.

**Comment by maksimsab** [comment]
Sorry for the waiting. I will take a look today.

**Review by maksimsab — APPROVED** [review]
LGTM

**Comment by sarnex** [comment]
@frasercrmck We are seeing postcommit failures:

```
 /__w/llvm/llvm/src/sycl-fusion/passes/kernel-fusion/SYCLSpecConstMaterializer.cpp:301:28: error: no member named 'getArchType' in namespace 'llvm::TargetHelpers'
  301 |   auto AT = TargetHelpers::getArchType(*Mod);
      |             ~~~~~~~~~~~~~~~^
/__w/llvm/llvm/src/sycl-fusion/passes/kernel-fusion/SYCLSpecConstMaterializer.cpp:302:22: error: no member named 'ArchType' in namespace 'llvm::TargetHelpers'
  302 |   if (TargetHelpers::ArchType::Cuda != AT &&
      |       ~~~~~~~~~~~~~~~^
/__w/llvm/llvm/src/sycl-fusion/passes/kernel-fusion/SYCLSpecConstMaterializer.cpp:303:22: error: no member named 'ArchType' in namespace 'llvm::TargetHelpers'
  303 |       TargetHelpers::ArchType::AMDHSA != AT) {
      |       ~~~~~~~~~~~~~~~^
3 errors generated.
ninja: build stopped: subcommand failed.
```

https://github.com/intel/llvm/actions/runs/10148224615/job/28060449427

Can you please take a look?

**Comment by frasercrmck** [comment]
> @frasercrmck We are seeing postcommit failures:
> 
> ```
>  /__w/llvm/llvm/src/sycl-fusion/passes/kernel-fusion/SYCLSpecConstMaterializer.cpp:301:28: error: no member named 'getArchType' in namespace 'llvm::TargetHelpers'
>   301 |   auto AT = TargetHelpers::getArchType(*Mod);
>       |             ~~~~~~~~~~~~~~~^
> /__w/llvm/llvm/src/sycl-fusion/passes/kernel-fusion/SYCLSpecConstMaterializer.cpp:302:22: error: no member named 'ArchType' in namespace 'llvm::TargetHelpers'
>   302 |   if (TargetHelpers::ArchType::Cuda != AT &&
>       |       ~~~~~~~~~~~~~~~^
> /__w/llvm/llvm/src/sycl-fusion/passes/kernel-fusion/SYCLSpecConstMaterializer.cpp:303:22: error: no member named 'ArchType' in namespace 'llvm::TargetHelpers'
>   303 |       TargetHelpers::ArchType::AMDHSA != AT) {
>       |       ~~~~~~~~~~~~~~~^
> 3 errors generated.
> ninja: build stopped: subcommand failed.
> ```
> 
> https://github.com/intel/llvm/actions/runs/10148224615/job/28060449427
> 
> Can you please take a look?

Looks like #14280 was merged in first and caused the issues. Ideally CI would have been re-run before merging this.

**Comment by frasercrmck** [comment]
See #14833

**Pull request merged**
