### PR TITLE
[SYCL] Move non device code checks outside of check_device_code

### PR DESCRIPTION
**Pull request by ianayl**
In the same vein as #14174, this PR moves test cases that do not check device code outside of the `check_device_code` folder.  This is a separate PR as #14174 because the code is technically owned by another team.

### CODE REVIEW

**Comment by ianayl** [comment]
@ldrumm Friendly ping, thank you!

**Review by steffenlarsen — APPROVED** [review]
Looks reasonable!

**Review by YuriPlyakhin — APPROVED** [review]
LGTM

**Comment by ianayl** [comment]
@intel/llvm-gatekeepers This PR is ready, thank you!

**Comment by ianayl** [comment]
@intel/llvm-gatekeepers Friendly ping, thanks!

**Pull request merged**
