### PR TITLE
[SYCL] Fix LIT tests to take into account LLVM_LIBDIR_SUFFIX

### PR DESCRIPTION
**Pull request by fwyzard**
[sycl/test/CMakeLists.txt]() uses
```
set(LLVM_BUILD_LIBRARY_DIRS "${LLVM_BINARY_DIR}/lib/")
```
instead of
```
set(LLVM_BUILD_LIBRARY_DIRS "${LLVM_BINARY_DIR}/lib${LLVM_LIBDIR_SUFFIX}")
```
making all LIT tests will fail if a `LLVM_LIBDIR_SUFFIX` is specified.

This PR updates the path to take `LLVM_LIBDIR_SUFFIX` into account.

### CODE REVIEW

**Comment by bader** [comment]
@fwyzard, could you check if https://github.com/intel/llvm/pull/1165 fixes the problem, please?
It allows to validate "deployed" compiler and it's already reviewed and approved for commit.

**Comment by fwyzard** [comment]
> @fwyzard, could you check if #1165 fixes the problem, please?

I think it misses ${LLVM_LIBDIR_SUFFIX} as well.

> It allows to validate "deployed" compiler and it's already reviewed and approved for commit.

Does it mean it allows to validate *only* a deployed compiler, or *also* a deployed compiler ?

In fact, how does the deployment work ?
The instructions at [GetStartedWithSYCLCompiler.md](https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedWithSYCLCompiler.md#build-sycl-toolchain) say only 
> TODO: add instructions how to deploy built SYCL toolchain.

**Comment by bader** [comment]
> > It allows to validate "deployed" compiler and it's already reviewed and approved for commit.
> 
> Does it mean it allows to validate _only_ a deployed compiler, or _also_ a deployed compiler ?
> 

It allows to validate both: built and deployed compilers.

> In fact, how does the deployment work ?
> The instructions at [GetStartedWithSYCLCompiler.md](https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedWithSYCLCompiler.md#build-sycl-toolchain) say only
> 
> > TODO: add instructions how to deploy built SYCL toolchain.

There is a special cmake target `deploy-sycl-toolchain`, which is supposed to prepare a compiler toolchain with SYCL support.
Thanks for noticing missing instructions. I'll update the document later.

**Comment by fwyzard** [comment]
> > @fwyzard, could you check if #1165 fixes the problem, please?
> 
> I think it misses ${LLVM_LIBDIR_SUFFIX} as well.

Seems to work with https://github.com/intel/llvm/pull/1165#discussion_r386433230 .

**Comment by fwyzard** [comment]
#1165 together with https://github.com/intel/llvm/pull/1165#discussion_r386433230 should already fix this issue.

**Pull request closed without merging**
