### PR TITLE
[ESIMD] Fix namespace and bug in the docs.

### PR DESCRIPTION
**Pull request by kbobrovs**

### CODE REVIEW

**Review by v-klochkov — APPROVED** [review]
The changes are good.
IMO, there are few more places where changes are needed, e.g. the line 107:
sycl::ext::intel::experimental::esimd::block_store
-->
sycl::ext::intel::esimd::block_store

**Comment by kbobrovs** [comment]
@smaslov-intel, please be aware of the libpi_level_zero.so build failure

**Comment by smaslov-intel** [comment]
> @smaslov-intel, please be aware of the libpi_level_zero.so build failure

Thanks. This is already fixed in https://github.com/intel/llvm/pull/6059

**Comment by kbobrovs** [comment]
> The changes are good. IMO, there are few more places where changes are needed, e.g. the line 107: sycl::ext::intel::experimental::esimd::block_store --> sycl::ext::intel::esimd::block_store

Did not notice this message. You are right, will fix too.

**Pull request merged**
