### PR TITLE
[SYCL] Fix triple in offload mismatch warning

### PR DESCRIPTION
**Pull request by npmiller**
This patch fixes small issues after https://github.com/intel/llvm/pull/9631

When standardizing the triples the format should be:

```
<arch><sub>-<vendor>-<sys>-<env>
```

* https://clang.llvm.org/docs/CrossCompilation.html#target-triple

And then we add our offload arch afterwards, so the final triples should look something like: `nvptx64-nvidia-cuda--sm_50`, instead of `nvptx64-nvidia-cuda-sm_50-`.

In addition never skip standardization so that triples like `nvptx64-nvidia-cuda-`, are also properly standardized to `nvptx64-nvidia-cuda--`.

### CODE REVIEW

**Review by mdtoguchi — APPROVED** [review]
LGTM, would like a look from @asudarsa as he made the original changes

**Review by asudarsa — APPROVED** [review]
LGTM. Thanks for the fix.

**Comment by asudarsa** [comment]
Hi @npmiller 

Thanks for the fix again. can you please sync your PR to get latest changes? The fix to the build issue was checked in yesterday and so the testing after the sync should be useful.

**Comment by asudarsa** [comment]
@AlexeySachkov 

Can you please take a look and merge if it looks ok to you?

Thanks
Sincerely

**Pull request merged**
