### PR TITLE
[UR] phase 2 of counter-based event

### PR DESCRIPTION
**Pull request by winstonzhang-intel**
PR in UR: https://github.com/oneapi-src/unified-runtime/pull/2138

### CODE REVIEW

**Review by aarongreig — APPROVED** [review]

**Comment by aarongreig** [comment]
@intel/llvm-gatekeepers please merge

**Comment by sarnex** [comment]
@aarongreig @winstonzhang-intel Seeing this failure in postcommit:

https://github.com/intel/llvm/actions/runs/11349817562/job/31567246324
```
FAIL: SYCL :: syclcompat/util/util_shift_sub_group_right.cpp (2208 of 2211)
```

```
Exit Code: -6

Command Output (stdout):
--
# RUN: at line 34
/__w/llvm/llvm/toolchain/bin//clang++  -Werror  -Wno-error=#warnings -Wno-error=deprecated-declarations -fsycl -fsycl-targets=spir64  /__w/llvm/llvm/llvm/sycl/test-e2e/syclcompat/util/util_shift_sub_group_right.cpp -o /__w/llvm/llvm/build-e2e/syclcompat/util/Output/util_shift_sub_group_right.cpp.tmp.out
# executed command: /__w/llvm/llvm/toolchain/bin//clang++ -Werror '-Wno-error=#warnings' -Wno-error=deprecated-declarations -fsycl -fsycl-targets=spir64 /__w/llvm/llvm/llvm/sycl/test-e2e/syclcompat/util/util_shift_sub_group_right.cpp -o /__w/llvm/llvm/build-e2e/syclcompat/util/Output/util_shift_sub_group_right.cpp.tmp.out
# .---command stderr------------
# | In file included from /__w/llvm/llvm/llvm/sycl/test-e2e/syclcompat/util/util_shift_sub_group_right.cpp:38:
# | In file included from /__w/llvm/llvm/toolchain/bin/../include/syclcompat.hpp:25:
# | In file included from /__w/llvm/llvm/toolchain/bin/../include/syclcompat/syclcompat.hpp:27:
# | /__w/llvm/llvm/toolchain/bin/../include/syclcompat/device.hpp:421:2: warning: "Querying the number of bytes of free memory is not supported" [-W#warnings]
# |   421 | #warning "Querying the number of bytes of free memory is not supported"
# |       |  ^
# | 1 warning generated.
# | In file included from /__w/llvm/llvm/llvm/sycl/test-e2e/syclcompat/util/util_shift_sub_group_right.cpp:38:
# | In file included from /__w/llvm/llvm/toolchain/bin/../include/syclcompat.hpp:25:
# | In file included from /__w/llvm/llvm/toolchain/bin/../include/syclcompat/syclcompat.hpp:27:
# | /__w/llvm/llvm/toolchain/bin/../include/syclcompat/device.hpp:421:2: warning: "Querying the number of bytes of free memory is not supported" [-W#warnings]
# |   421 | #warning "Querying the number of bytes of free memory is not supported"
# |       |  ^
# | 1 warning generated.
# `-----------------------------
# RUN: at line 35
env ONEAPI_DEVICE_SELECTOR=level_zero:gpu  /__w/llvm/llvm/build-e2e/syclcompat/util/Output/util_shift_sub_group_right.cpp.tmp.out
# executed command: env ONEAPI_DEVICE_SELECTOR=level_zero:gpu /__w/llvm/llvm/build-e2e/syclcompat/util/Output/util_shift_sub_group_right.cpp.tmp.out
# .---command stdout------------
# | void test_shift_sub_group_right()
# `-----------------------------
# .---command stderr------------
# | util_shift_sub_group_right.cpp.tmp.out: /__w/llvm/llvm/llvm/sycl/test-e2e/syclcompat/util/util_shift_sub_group_right.cpp:50: void verify_data(T *, T *, int, int) [T = unsigned int]: Assertion `data[i] == expect[i]' failed.
# `-----------------------------
# error: command failed with exit status: -6
```

Could it be related to this PR?

**Comment by aarongreig** [comment]
@sarnex I did a quick A/B test and it looks like this change is responsible for the new fail, I won't have bandwidth to look into this myself so we should revert until @winstonzhang-intel has a chance to look into it

**Comment by aarongreig** [comment]
revert PR https://github.com/intel/llvm/pull/15720

**Comment by sarnex** [comment]
@aarongreig Thank you!

**Pull request merged**
