### PR TITLE
[SYCL] Remove direct initialization constructor from bfloat16 class

### LINKED ISSUE #4871: [SYCL] error: ambiguous conversion for functional-style cast from 'int' to 'bfloat16' when call `bfloat16(0)`
> background: on framework or library side, we often call T(0) to initialize type T with zero value, and T maybe float or integer type

- reproduce
```c++
#include "CL/sycl.hpp"
#include <sycl/ext/intel/experimental/bfloat16.hpp>

using bfloat16 = sycl::ext::intel::experimental::bfloat16;

int main() {
  auto val = bfloat16(0);

  return 0;
}
```

- error
```
ctor.cc:7:14: error: ambiguous conversion for functional-style cast from 'int' to 'bfloat16' (aka 'sycl::ext::intel::experimental::bfloat16')
  auto val = bfloat16(0);
             ^~~~~~~~~~
/home/gta/intel/linux_prod/compiler/linux/bin/../include/sycl/ext/intel/experimental/bfloat16.hpp:47:3: note: candidate constructor
  bfloat16(const storage_t &a) : value(a) {}
  ^
/home/gta/intel/linux_prod/compiler/linux/bin/../include/sycl/ext/intel/experimental/bfloat16.hpp:50:3: note: candidate constructor
  bfloat16(const float &a) { value = from_float(a); }
  ^
1 error generated.
```

### PR DESCRIPTION
**Pull request by AlexeySotkin**
This constructor is being removed to resolve ambiguity when user trying
initialize bfloat16 with int, like `auto a = bfloat16(0);`

Fixes #4871.

### CODE REVIEW

**Review by steffenlarsen — DISMISSED** [review]
LGTM. Is this something that should be reflected in the [extension document](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/Bf16Conversion/SYCL_INTEL_bf16_conversion.asciidoc)?

**Comment by dm-vodopyanov** [comment]
@AlexeySotkin, can you please answer the question below before merging of this PR?

**Comment by vladimirlaz** [comment]
> @AlexeySotkin, can you please answer the question above before merging of this PR?

in fact, the spec does not contain the removed constructor. So nothing to be changed.

**Review by vladimirlaz — DISMISSED** [review]

**Comment by AlexeySotkin** [comment]
> > @AlexeySotkin, can you please answer the question above before merging of this PR?
> 
> in fact, the spec does not contain the removed constructor. So nothing to be changed.

The latest change contains a new method which should be added to the spec. Also I'd like to hear feedback from @GHGmc2. Marking this PR as a draft for now.

**Comment by AlexeySotkin** [comment]
This PR fixes #4871

**Comment by GHGmc2** [comment]
@AlexeySotkin Thanks, I'll have have try and give feedback soon.

**Comment by GHGmc2** [comment]
@AlexeySotkin ambiguous error when cast bfloat16 to long "error: conversion from 'bfloat16' (aka 'sycl::ext::intel::experimental::bfloat16') to 'long' is ambiguous":
```c++
#include <CL/sycl.hpp>
#include <sycl/ext/intel/experimental/bfloat16.hpp>

constexpr int ALIGN = 64;
constexpr int M = 100;

using bfloat16 = sycl::ext::intel::experimental::bfloat16;

int main() {
  long ret = bfloat16(3.14f);

  return 0;
}
```

**Comment by vladimirlaz** [comment]
@AlexeySotkin could you please fix the CI failure?

**Comment by AlexeySotkin** [comment]
> LGTM. Is this something that should be reflected in the [extension document](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/Bf16Conversion/SYCL_INTEL_bf16_conversion.asciidoc)?

Yes

**Comment by GHGmc2** [comment]
LGTM

**Review by vladimirlaz — APPROVED** [review]

**Review by steffenlarsen — APPROVED** [review]

**Pull request merged**
