### PR TITLE
[UR][L0] reset command lists on error unknown

### PR DESCRIPTION
**Pull request by nrspruit**
pre-commit PR for https://github.com/oneapi-src/unified-runtime/pull/1539

### CODE REVIEW

**Review by kbenzie — APPROVED** [review]

**Comment by kbenzie** [comment]
I've got a fix for these build issues in https://github.com/oneapi-src/unified-runtime/pull/1548 which I'll pull in here to get this passing again.

**Comment by kbenzie** [comment]
@intel/llvm-gatekeepers please merge

**Comment by ldrumm** [comment]
```
 $ git show 196f62f34e70dd79f3f683abe103cc33d3c49a92 -m
commit 196f62f34e70dd79f3f683abe103cc33d3c49a92 (from 37242e39480d8bb73cb8cc3a54152edab43fd85b) (origin/main, origin/HEAD)
Merge: 37242e39 275c753a
Author: Kenneth Benzie (Benie) <k.benzie@codeplay.com>
Date:   Thu Apr 25 15:03:51 2024 +0100

    Merge pull request #1548 from kbenzie/benie/l0-fix-decoupled-use-case
    
    [L0] Use relative includes for adapter internals

diff --git a/source/adapters/level_zero/adapter.hpp b/source/adapters/level_zero/adapter.hpp
index 5de83b02..36eedb0f 100644
--- a/source/adapters/level_zero/adapter.hpp
+++ b/source/adapters/level_zero/adapter.hpp
@@ -7,6 +7,7 @@
 // SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
 //
 //===----------------------------------------------------------------------===//
+#pragma once
 
 #include "logger/ur_logger.hpp"
 #include <atomic>
diff --git a/source/adapters/level_zero/context.cpp b/source/adapters/level_zero/context.cpp
index 782fa1c8..f9cf5009 100644
--- a/source/adapters/level_zero/context.cpp
+++ b/source/adapters/level_zero/context.cpp
@@ -13,9 +13,9 @@
 #include <mutex>
 #include <string.h>
 
-#include "adapters/level_zero/queue.hpp"
 #include "context.hpp"
 #include "logger/ur_logger.hpp"
+#include "queue.hpp"
 #include "ur_level_zero.hpp"
 
 UR_APIEXPORT ur_result_t UR_APICALL urContextCreate(
diff --git a/source/adapters/level_zero/queue.cpp b/source/adapters/level_zero/queue.cpp
index 0701ad43..c6aaf4b0 100644
--- a/source/adapters/level_zero/queue.cpp
+++ b/source/adapters/level_zero/queue.cpp
@@ -16,8 +16,8 @@
 #include <vector>
 
 #include "adapter.hpp"
-#include "adapters/level_zero/event.hpp"
 #include "common.hpp"
+#include "event.hpp"
 #include "queue.hpp"
 #include "ur_api.h"
 #include "ur_level_zero.hpp"
```
Is that right? It doesn't match the description is all

**Comment by ldrumm** [comment]
Nevermind. Just saw your other comment

**Comment by kbenzie** [comment]
Yeah, the previous commit https://github.com/intel/llvm/pull/13522/commits/e9d50d4b7c000908bc20195c05f66a79bbe92d4d is the commit which lines up with the description.

**Pull request merged**
