### PR TITLE
[SYCL][ESIMD][E2E] Disable matrix_transpose_glb.cpp

### PR DESCRIPTION
**Pull request by sarnex**
It's failing in postcommit, we need this to fix the CI.

### CODE REVIEW

**Comment by sarnex** [comment]
@intel/dpcpp-esimd-reviewers Hey guys, can someone review ASAP, postcommit on Arc is broken. Thanks!

**Comment by sarnex** [comment]
@fineg74 Thank you!

**Comment by aelovikov-intel** [comment]
```
Unresolved Tests (1):
  SYCL :: ESIMD/matrix_transpose_glb.cpp
```

in https://github.com/intel/llvm/actions/runs/7643656810/job/20826790391. From log:

```
UNRESOLVED: SYCL :: ESIMD/matrix_transpose_glb.cpp (680 of 1848)
******************** TEST 'SYCL :: ESIMD/matrix_transpose_glb.cpp' FAILED ********************
Exception during script execution:
Traceback (most recent call last):
  File "/__w/llvm/llvm/llvm/llvm/utils/lit/lit/BooleanExpression.py", line [32](https://github.com/intel/llvm/actions/runs/7643656810/job/20826790391#step:21:33), in evaluate
    return parser.parseAll()
  File "/__w/llvm/llvm/llvm/llvm/utils/lit/lit/BooleanExpression.py", line 151, in parseAll
    self.token = next(self.tokens)
  File "/__w/llvm/llvm/llvm/llvm/utils/lit/lit/BooleanExpression.py", line 62, in tokenize
    raise ValueError("couldn't parse text: %r" % string)
ValueError: couldn't parse text: '*'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/__w/llvm/llvm/llvm/sycl/test-e2e/format.py", line 94, in getMatchedFromList
    return [
  File "/__w/llvm/llvm/llvm/sycl/test-e2e/format.py", line 95, in <listcomp>
    item for item in alist if BooleanExpression.evaluate(item, features)
  File "/__w/llvm/llvm/llvm/llvm/utils/lit/lit/BooleanExpression.py", line [34](https://github.com/intel/llvm/actions/runs/7643656810/job/20826790391#step:21:35), in evaluate
    raise ValueError(str(e) + ("\nin expression: %r" % string))
ValueError: couldn't parse text: '*'
in expression: '*'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/__w/llvm/llvm/llvm/llvm/utils/lit/lit/worker.py", line 76, in _execute_test_handle_errors
    result = test.config.test_format.execute(test, lit_config)
  File "/__w/llvm/llvm/llvm/sycl/test-e2e/format.py", line 1[56](https://github.com/intel/llvm/actions/runs/7643656810/job/20826790391#step:21:57), in execute
    devices_for_test = self.select_devices_for_test(test)
  File "/__w/llvm/llvm/llvm/sycl/test-e2e/format.py", line 107, in select_devices_for_test
    if self.getMatchedFromList(features, test.unsupported):
  File "/__w/llvm/llvm/llvm/sycl/test-e2e/format.py", line 98, in getMatchedFromList
    raise ValueError("Error in UNSUPPORTED list:\n%s" % str(e))
ValueError: Error in UNSUPPORTED list:
couldn't parse text: '*'
in expression: '*'
```

**Comment by sarnex** [comment]
@aelovikov-intel Already working on it, https://github.com/intel/llvm/pull/12485

**Pull request merged**
