### PR TITLE
[SYCL][ESIMD] Add a check for number of blocks for 2d block store

### PR DESCRIPTION
**Pull request by turinevgeny**
Previously the check was missing.

### CODE REVIEW

**Comment by bader** [comment]
@turinevgeny, ESIMD/api/functional/operators/operator_assignment_glb_mask.cpp failed in post-commit https://github.com/intel/llvm/actions/runs/6154402623/job/16700306212. Please, fix ASAP.

**Comment by turinevgeny** [comment]
> @turinevgeny, ESIMD/api/functional/operators/operator_assignment_glb_mask.cpp failed in post-commit https://github.com/intel/llvm/actions/runs/6154402623/job/16700306212. Please, fix ASAP.

This test could not be affected by this change. Were there any driver updates recently?

**Comment by bader** [comment]
No.

**Comment by dm-vodopyanov** [comment]
@turinevgeny can be related: https://github.com/intel/llvm/issues/10293. Could be very rarely reproducible flaky failure. I will move this issue to the internal tracking system.

**Pull request merged**
