### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW38)

### PR DESCRIPTION
**Pull request by vmaksimo**
LLVM: llvm/llvm-project@29b44ca896e7
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@2f81f311538abcc57be25529c983ce21c9be9a50

### CODE REVIEW

**Comment by vladimirlaz** [comment]
The test failures in Jenkins/Precommit caused by infra issue: they have passed after restart: http://llvm-ci.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FLin%2FBasic_E2E/detail/Basic_E2E/435/pipeline

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Sat Sep 18 17:21:32 UTC 2021 --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Sat Sep 18 17:24:28 UTC 2021 --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
