### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW12)

### PR DESCRIPTION
**Pull request by FreddyLeaf**
LLVM: https://github.com/llvm/llvm-project/commit/de7639ddb05e
SPIRV-LLVM-Translator: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/3fe4393

### CODE REVIEW

**Comment by FreddyLeaf** [comment]
> I created #8739 to investigate SYCL / lint behavior.

Not sure if it is due to I add the label `ignore-lint` after creating the PR, directly added it on the page by UI button. I don't know other ways to add label, new to here :)

**Comment by bader** [comment]
> > I created #8739 to investigate SYCL / lint behavior.
> 
> Not sure if it is due to I add the label `ignore-lint` after creating the PR, directly added it on the page by UI button. I don't know other ways to add label, new to here :)

No, it's not related. BTW, you should add this label while you create the PR. Lint job is quite fast, so if label is not added before the check, the rest of the testing pre-commit workflow won't be executed.

**Comment by bader** [comment]
@FreddyLeaf, checks status looks good to me. Let me know if it's ready for merge.

**Comment by bader** [comment]
@intel/dpcpp-spirv-reviewers, please, take a look at https://github.com/intel/llvm/pull/8738/commits/617a2ccbd4d6c6340bc544ccc0c31ad356775990 and https://github.com/intel/llvm/pull/8738/commits/8d8c74e40d61098157bbd297f44de6ba9e9315e8.

https://github.com/intel/llvm/pull/8738/commits/96e96c4f3621fb8da66c0c05be5193b1234c67d3, @FreddyLeaf what is the plan to bring this commit back?

**Comment by mdtoguchi** [comment]
> @intel/dpcpp-spirv-reviewers, please, take a look at [617a2cc](https://github.com/intel/llvm/commit/617a2ccbd4d6c6340bc544ccc0c31ad356775990) and [8d8c74e](https://github.com/intel/llvm/commit/8d8c74e40d61098157bbd297f44de6ba9e9315e8).
> 
> [96e96c4](https://github.com/intel/llvm/commit/96e96c4f3621fb8da66c0c05be5193b1234c67d3), @FreddyLeaf what is the plan to bring this commit back?

@bader, Seems as though our target usage doesn't match with other bundler users, so while these changes are backward compatible for them, the same cannot be said for us.  see: https://reviews.llvm.org/D145770 for continued discussions

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Tue 28 Mar 2023 04:07:25 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Tue 28 Mar 2023 04:11:34 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Comment by bader** [comment]
> > @intel/dpcpp-spirv-reviewers, please, take a look at [617a2cc](https://github.com/intel/llvm/commit/617a2ccbd4d6c6340bc544ccc0c31ad356775990) and [8d8c74e](https://github.com/intel/llvm/commit/8d8c74e40d61098157bbd297f44de6ba9e9315e8).
> > [96e96c4](https://github.com/intel/llvm/commit/96e96c4f3621fb8da66c0c05be5193b1234c67d3), @FreddyLeaf what is the plan to bring this commit back?
> 
> @bader, Seems as though our target usage doesn't match with other bundler users, so while these changes are backward compatible for them, the same cannot be said for us. see: https://reviews.llvm.org/D145770 for continued discussions

This reminds me of the same issue we had with sycldevice environment component of the target triple. 

https://reviews.llvm.org/D145770#4225765 it's supposed to be backward compatible. Why is this change not backward compatible? Is it because we always add a new component for the triple? Shouldn't we keep the patch and add support for old triple for backward compatibility instead?

**Comment by mdtoguchi** [comment]
> 
> This reminds me of the same issue we had with sycldevice environment component of the target triple.
> 
> https://reviews.llvm.org/D145770#4225765 it's supposed to be backward compatible. Why is this change not backward compatible? Is it because we always add a new component for the triple? Shouldn't we keep the patch and add support for old triple for backward compatibility instead?

Yes, that seems like the correct thing to do.  @asudarsa could you provide some assistance?  It looks like we want to retain the patch that was reverted and make sure the behavior is backwards compatible for our usage.

**Pull request merged**
