### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW05)

### PR DESCRIPTION
**Pull request by sys-ce-bb**
LLVM: llvm/llvm-project@178719e86043c1e830a7e24de027a84f6f8ea28f
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@a1b1f49825bdcd287bdf5383bcc30517c3900ea6

### CODE REVIEW

**Comment by jsji** [comment]
This is ready for review.

- [ ] [Revert "Update add-ir-annotations tests after](https://github.com/intel/llvm/pull/12577/commits/21e703a0b0c4598179273fc3e731248a71e9cf3e) Revert our testcase update because upstream commit is reverted.  @intel/dpcpp-cfe-reviewers

**Review by smanna12 — APPROVED** [review]

**Comment by smanna12** [comment]
> This is ready for review.
> 
> * [ ]  [Revert "Update add-ir-annotations tests after](https://github.com/intel/llvm/pull/12577/commits/21e703a0b0c4598179273fc3e731248a71e9cf3e) Revert our testcase update because upstream commit is reverted.  @intel/dpcpp-cfe-reviewers Please have a look and explicitly comment for this change so that this can be merged. Thanks.

LGTM.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Thu 01 Feb 2024 08:13:10 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Pull request merged**
