### PR TITLE
[SYCL][OpenMP] Update compilation behaviors with fat archives

### PR DESCRIPTION
**Pull request by mdtoguchi**
Allow for compilation using multiple objects and also enable compilation
from source.  Initial support for compilation from fat archives only allowed
the compile to be from a single object and the fat archive.  These changes
expand on that to allow compilation direct from source files and multiple
objects.

Signed-off-by: Michael D Toguchi <michael.d.toguchi@intel.com>

### CODE REVIEW

**Comment by mdtoguchi** [comment]
Looks like one of the checks hasn't moved in a while (or even started) - how do kick it to get it to start?

**Comment by bader** [comment]
@vladimirlaz, @ikurtchen, could you document the process, please?

**Comment by vladimirlaz** [comment]
> @vladimirlaz, @ikurtchen, could you document the process, please?

It is described. PR should be approved to let testing start on intel/llvm

**Comment by bader** [comment]
> > @vladimirlaz, @ikurtchen, could you document the process, please?
> 
> It is described. PR should be approved to let testing start on intel/llvm

Could you provide a link to the documentation?
Ideally the process should be clear from the information available in PR.

**Pull request merged**
