### PR TITLE
[CI] Reduce cts_exclude_filter

### PR DESCRIPTION
**Pull request by KornevNikita**
also turn off h_item due to fail - https://github.com/intel/llvm/issues/12926

### CODE REVIEW

**Comment by KornevNikita** [comment]
Takes 1h40min - https://github.com/intel/llvm/actions/runs/8360599058
marray requires ~3.5h, so we need to investigate it and refactor.
some binary from kernel_bundle set also takes too much time, so need to investigate.

**Review by aelovikov-intel — APPROVED** [review]
What's the plan for the failing `test_h_item`? Should we disable it until the failure is fixed?

**Comment by KornevNikita** [comment]
> What's the plan for the failing `test_h_item`? Should we disable it until the failure is fixed?

Yep, thought of it, let's probably just turn it off.

**Comment by KornevNikita** [comment]
After the commits above: https://github.com/intel/llvm/actions/runs/8372423378/job/22923358211

**Pull request merged**
