### PR TITLE
[CI] Don't upload MacOS artifacts

### PR DESCRIPTION
**Pull request by bader**

### CODE REVIEW

**Comment by bader** [comment]
@alexbatashev, please, let me know if you have any feedback.

**Comment by bader** [comment]
Actually, I think we should not upload artifacts in the first place. We don't use macos artifacts, so there is no need to upload them.

**Review by alexbatashev — APPROVED** [review]
LGTM.
@bader actually, the idea of having artifacts uploaded was that the developers can download them to quickly check something. But since there're no active users or developers, I'm okay to remove artifacts.

**Comment by bader** [comment]
> LGTM. @bader actually, the idea of having artifacts uploaded was that the developers can download them to quickly check something. But since there're no active users or developers, I'm okay to remove artifacts.

I see that clean-up job immediately removes Linux and Windows artifacts after workflow is finished. So, even if we had this idea originally, it doesn't work anymore.

**Comment by bader** [comment]
> But since there're no active users or developers, I'm okay to remove artifacts.

BTW, you added this configuration. Is it still useful? If no, I prefer to remove it (or at least switch from regular runs to manual).

**Comment by alexbatashev** [comment]
@bader I don't have much bandwidth to contribute to SYCL after I left Intel. I wouldn't mind if you disable this configuration completely, or come up with a less frequent schedule.

**Comment by bader** [comment]
> @bader I don't have much bandwidth to contribute to SYCL after I left Intel. I wouldn't mind if you disable this configuration completely, or come up with a less frequent schedule.

Thanks for the feedback. I saw @AlexeySachkov contributed some fixes for MacOS, so I'd like to hear from him before making this change.

**Comment by AlexeySachkov** [comment]
> > @bader I don't have much bandwidth to contribute to SYCL after I left Intel. I wouldn't mind if you disable this configuration completely, or come up with a less frequent schedule.
> 
> Thanks for the feedback. I saw @AlexeySachkov contributed some fixes for MacOS, so I'd like to hear from him before making this change.

I'm fine with not uploading macOS artifacts, I didn't even know about such functionality.

**Pull request merged**
