### PR TITLE
[SYCL] Enable SPV_INTEL_memory_access_aliasing extension

### PR DESCRIPTION
**Pull request by MrSidims**
Signed-off-by: Sidorov, Dmitry <dmitry.sidorov@intel.com>

### CODE REVIEW

**Review by mdtoguchi — APPROVED** [review]

**Comment by againull** [comment]
@MrSidims  Sorry, could you please merge the origin/sycl branch into this PR so that I can merge this.

**Comment by bader** [comment]
> @MrSidims Sorry, could you please merge the origin/sycl branch into this PR so that I can merge this.

@MrSidims, ping. Please, resolve merge conflicts.

**Comment by MrSidims** [comment]
@bader @againull thanks for the reminder! There were some ESIMD tests failing, which seemed to be unrelated to the patch, though, locally they were looking like a regression caused by this patch. Lets make one more pre-commit attempt.

**Comment by MrSidims** [comment]
Ok, "invoke_simd has SPMD function as invoke target.Only ESIMD functions can be invoked by this function" is unrelated known issue reported elsewhere, so the PR can be merged.

**Comment by bader** [comment]
> Ok, "invoke_simd has SPMD function as invoke target.Only ESIMD functions can be invoked by this function" is unrelated known issue reported elsewhere, so the PR can be merged.

I don't see any failures in recent pre-commit results. E.g. https://github.com/intel/llvm/pull/7893 - all tests pass.
Could you clarify why these failures are expected?
Tagging @intel/dpcpp-esimd-reviewers.

**Comment by bader** [comment]
> Could you clarify why these failures are expected?

@MrSidims, ping.

**Comment by MrSidims** [comment]
I made a misjudgment, need to double check.

**Pull request closed without merging**
