### PR TITLE
[SYCL] Fix doc typos

### PR DESCRIPTION
**Pull request by sarnex**
Just doing this to get familiar with submission process, no functional change

Signed-off-by: Sarnie, Nick <nick.sarnie@intel.com>

### CODE REVIEW

**Review by aelovikov-intel — APPROVED** [review]
Unfortunately, people from @intel/dpcpp-doc-reviewers are on vacation, so not the best PR to get familiar with the normal submission process...

@againull , can you please merge this in using your maintainer rights without component owner approval?

**Comment by sarnex** [comment]
Wow, what luck I have. Thanks for merging

**Comment by bader** [comment]
I suggest adding [Doc] tag for PRs updating only documentation.

**Comment by sarnex** [comment]
@bader Thanks for the suggestion, will do in the future

**Pull request merged**
