### PR TITLE
[SYCL] Mark sycl::marray device copyable

### PR DESCRIPTION
**Pull request by vladimirlaz**
sycl::marray is device copyable if the element type is device copyable.
Also test was added to verify that the following types are device copyable:
 - sycl::marray<T> when T is device copyable;
 - sycl::vec<T> (all supported element types are device copyable);
 - sycl::id;
 - sycl::range.

### CODE REVIEW

**Review by turinevgeny — APPROVED** [review]

**Comment by vladimirlaz** [comment]
@intel/llvm-reviewers-runtime, could you please review the PR?

**Review by alexbatashev — COMMENTED** [review]
Overall LGTM, but I think we need a better test. On Windows the compiler can (possibly) produce types with different alignment on host and device. We either need a runtime test or a static test, that checks the alignment.

**Comment by vladimirlaz** [comment]
> we need a better test. On Windows the compiler can (possibly) produce types with
@alexbatashev, my expectation here is that if a type is device copyable it should have the same alignment on host and device. Otherwise scalar variable of element type will go into trouble as well.

**Comment by alexbatashev** [comment]
> @alexbatashev, my expectation here is that if a type is device copyable it should have the same alignment on host and device. Otherwise scalar variable of element type will go into trouble as well.

I share these expectations, I'm just not sure if compiler has the same point of view. Since device and host compilation are two separate processes, with two different ABIs. For SYCL-defined types we must ensure ABI is the same on host and device, at least we should update this test: https://github.com/intel/llvm/blob/sycl/sycl/test/abi/symbol_size_alignment.cpp

**Comment by vladimirlaz** [comment]
> > @alexbatashev, my expectation here is that if a type is device copyable it should have the same alignment on host and device. Otherwise scalar variable of element type will go into trouble as well.
> 
> I share these expectations, I'm just not sure if compiler has the same point of view. Since device and host compilation are two separate processes, with two different ABIs. For SYCL-defined types we must ensure ABI is the same on host and device, at least we should update this test: https://github.com/intel/llvm/blob/sycl/sycl/test/abi/symbol_size_alignment.cpp

The requested test change does not look like connected to the PR. If there are gaps in testing it should be covered as separate issue/PR.

**Review by alexbatashev — APPROVED** [review]

**Pull request merged**
