### PR TITLE
[NFC][SYCL] Use std::make_unique instead of make_unique_ptr

### PR DESCRIPTION
**Pull request by aelovikov-intel**

### CODE REVIEW

**Comment by bader** [comment]
This looks more like an "API-breaking" change rather a "non-functional" change.

**Comment by aelovikov-intel** [comment]
> This looks more like an "API-breaking" change rather a "non-functional" change.

How so? It's the same `std::unique_ptr` that crosses any boundary.

**Comment by bader** [comment]
> > This looks more like an "API-breaking" change rather a "non-functional" change.
> 
> How so? It's the same `std::unique_ptr` that crosses any boundary.

It removes a function template from `sycl` namespace, which is part of SYCL API users may use it their code.

**Comment by aelovikov-intel** [comment]
> make_unique_ptr should have been added to sycl::detail namespace.

Yes!

> It removes a function template from sycl namespace, which is part of SYCL API users may use it their code.

See it now, thanks. Guess I'll have to restore it unless in preview mode. Can't imagine anyone sane actually using it though.

**Comment by bader** [comment]
> Guess I'll have to restore it unless in preview mode. Can't imagine anyone sane actually using it though.

I agree with both these statements. :)

**Review by bso-intel — APPROVED** [review]

**Pull request merged**
