### PR TITLE
[SYCL] Test for PR #7918 - invalid value in named_sub_group_size

### PR DESCRIPTION
**Pull request by premanandrao**
When PR #7918 was submitted, a test wasn't added along with it.

### CODE REVIEW

**Comment by premanandrao** [comment]
I was not looking in the right place yesterday, sorry about that.   I was able to come up with a test for #7918.  Please review.

**Review by Fznamznon — APPROVED** [review]

**Review by smanna12 — APPROVED** [review]

**Review by elizabethandrews — APPROVED** [review]

**Comment by premanandrao** [comment]
The CUDA LLVM Test Suite has been waiting for over 4 hours for a runner to start the tests.

**Comment by bader** [comment]
> The CUDA LLVM Test Suite has been waiting for over 4 hours for a runner to start the tests.

I'm looking into this.

**Comment by bader** [comment]
https://github.com/intel/llvm/pull/7942 fixes the problem with missing validation on NVIDIA GPU for future requests. I'm going to merge this PR as it's covered well already.

**Pull request merged**
