### PR TITLE
[CI] Turn on test_kernel_bundle and marray

### PR DESCRIPTION
**Pull request by KornevNikita**
These tests were turned off as we used some unstable runner previously. Turning them on since we moved to reliable runners.

### CODE REVIEW

**Comment by KornevNikita** [comment]
test runs:
https://github.com/intel/llvm/actions/runs/11777858220/job/32803078874
https://github.com/intel/llvm/actions/runs/11777862462/job/32803091207

**Comment by uditagarwal97** [comment]
> were turned off as we used some unstable runner previously

Are you referring to the HIP runner?

**Comment by KornevNikita** [comment]
> > were turned off as we used some unstable runner previously
> 
> Are you referring to the HIP runner?

Nope, I think it was the runner with the "cts-cpu" label. For some reason it goes (or at least went) offline, when I tried to run SYCL-CTS there.

**Review by uditagarwal97 — APPROVED** [review]
If the previous failures were not flaky, I think we can go ahead with this PR.

**Comment by KornevNikita** [comment]
> If the previous failures were not flaky, I think we can go ahead with this PR.

Yes, I'm sure that was a machine issue.

**Comment by KornevNikita** [comment]
@intel/llvm-gatekeepers could you please merge? note - It doesn't affect pre-/post-commit, so there is no need to wait for CI.

**Pull request merged**
