### PR TITLE
[SYCL][KernelFusion] Ensure queue_impl is not unnecessarily referenced

### PR DESCRIPTION
**Pull request by Naghasan**
The KernelFusionCmd keeps a references to the queue on which it was submitted. However these commands are also kept on the side in order to ensure event validity and are only reset when start fusion is called again on the same queue.
This forces queue_impl and events to be kept alive as the command keeps the last reference until the sycl shutdown procedure.

The patch forces 1) the command to reset it pointers to the queue once enqueued and 2) to clean up the KernelFusionCmd attached to the queue to free up events.

Note: there is no new test as kernel fusion already cover this and I'm not too sure on how to approach it. I'm happy to try out any suggestion.

### CODE REVIEW

**Review by cperkinsintel — APPROVED** [review]
So this looks good. 

Question: mightn't it be better to hold weak pointers to the queue_impls?  Then you might avoid the whole rigamarole.

**Comment by Naghasan** [comment]
I don't think you can, the command needs the queue for its execution so it needs to stick around. This actually issue is the need for `MFusionMap`, but that should hopefully go away when we switch to the graph based version.

**Comment by Naghasan** [comment]
@intel/llvm-gatekeepers this is now approved, can we have it merged ? thanks

**Comment by jsji** [comment]
@Naghasan This is causing a memory corruption in Extensions.

```tools/sycl/unittests/Extensions/./ExtensionsTests': **corrupted double-linked list:** 0x00000000011aa760 ***```

It fails a lot in our internal test env, but can also be reproduced in ubuntu 22, just harder to reproduce.
But should be able to reproduce by running it around 100.

`for i in {1..100} ; do echo "Running test $i... "; tools/sycl/unittests/Extensions/ExtensionsTests ; done`

**Pull request merged**
