### PR TITLE
[SYCL][NFC] Remove __SYCL_INLINE_VER_NAMESPACE macro

### PR DESCRIPTION
**Pull request by bader**

### CODE REVIEW

**Comment by bader** [comment]
Note for reviewers.
99% of changes are done with "find and replace": `__SYCL_INLINE_VER_NAMESPACE(_V1)` to `inline namespace _V1`. clang-format adds a comment `// namespace _V1` i.e. `inline` is dropped in the closing comment.

There are just a few files worth reviewing:
1. sycl/.clang-format
2. sycl/doc/doxygen.cfg.in
3. sycl/include/sycl/detail/defines_elementary.hpp and clang/test/SemaSYCL/Inputs/sycl/detail/defines_elementary.hpp

**Review by sommerlukas — APPROVED** [review]
Only reviewed the following files relating to kernel fusion, those look good.
```
fusion_properties.hpp
fusion_wrapper.hpp
fusion_wrapper.cpp
fusion_wrapper_impl.cpp
fusion_wrapper_impl.hpp
jit_compiler.cpp
jit_compiler.hpp
jit_device_binaries.cpp
jit_device_binaries.hpp
```

**Review by premanandrao — APPROVED** [review]
FE changes look okay to me.   (I reviewed just a few random files.)

**Review by victor-eds — APPROVED** [review]

**Review by steffenlarsen — APPROVED** [review]
LGTM!

**Review by v-klochkov — APPROVED** [review]

**Comment by bader** [comment]
@intel/llvm-gatekeepers, FYI.
Please, make sure that "ready to merge" patches don't add new uses of `__SYCL_INLINE_VER_NAMESPACE` macro. The best way to validate is to merge tip of the sycl branch.

**Pull request merged**
