### PR TITLE
Make Intel attributes consistent with clang attributes.

### LINKED ISSUE #2910: [SYCL] Enable let PragmaAttributeSupport for SYCL attributes
The typical upstream expectation is that new attributes are supported via #pragma clang attribute (https://clang.llvm.org/docs/LanguageExtensions.html#specifying-an-attribute-for-multiple-declarations-pragma-clang-attribute) unless there's some reason for them not to (like statement or type attributes). 

This does NOT enable pragma spellings for attribute as previously thought and is actually a useful functionality. See comment thread - https://github.com/intel/llvm/pull/2877#discussion_r538777558 for details

### PR DESCRIPTION
**Pull request by AaronBallman**
Clang allows attributes to be specified via a special pragma named
`#pragma clang attribute` and many of the Intel-specified attributes
were opting out of this support for no real reason.

This changes allows Intel attributes to be specified via this pragma,
similar to how almost all other Clang attributes are.

Closes #2910.

### CODE REVIEW

**Comment by AaronBallman** [comment]
This addresses #2910

**Review by elizabethandrews — COMMENTED** [review]
I quite literally just completed this patch but thanks for taking care of it. I think you will need to update the test - pragma-attribute-supported-attributes-list.test as well

**Comment by bader** [comment]
Fixes #2910

FYI: https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by AaronBallman** [comment]
> Closes #2910.
> 
> FYI: https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

Oh jeez. Go figure that I'd use a different word than what's on the supported list. :-D Thanks for pointing this out!

**Comment by AaronBallman** [comment]
> I quite literally just completed this patch but thanks for taking care of it :) I think you will need to update the test - `pragma-attribute-supported-attributes-list.test` as well

Sorry for the duplicated effort! And you're right -- I hadn't noticed that because my local build has a *ton* of failures that are unrelated to the patch (I think they have to do with separator differences between a normal Windows shell and our shell). I'll update the test and push a change.

**Comment by elizabethandrews** [comment]
> > I quite literally just completed this patch but thanks for taking care of it :) I think you will need to update the test - `pragma-attribute-supported-attributes-list.test` as well
> 
> Sorry for the duplicated effort! And you're right -- I hadn't noticed that because my local build has a _ton_ of failures that are unrelated to the patch (I think they have to do with separator differences between a normal Windows shell and our shell). I'll update the test and push a change.

No problem! Thanks!

**Review by elizabethandrews — APPROVED** [review]

**Comment by bader** [comment]
> > Closes #2910.
> > FYI: https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
> 
> Oh jeez. Go figure that I'd use a different word than what's on the supported list. :-D Thanks for pointing this out!

Note, that it works only if these words are used in PR description or commit message and it doesn't work for PR comments.

Anyway, you can always link/close issues manually - this feature automates a few clicks only.

**Pull request merged**
