### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW06)

### PR DESCRIPTION
**Pull request by vmaksimo**
LLVM: llvm/llvm-project@8ce99dadb007
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@fb2dd0eb36ae743481c5bdc5021b180b8f06ed7b

### CODE REVIEW

**Comment by jchlanda** [comment]
> Hi, @jchlanda! After some LLORG changes, `CodeGen/AMDGPU/local-accessor-to-shared-memory-valid-triple.ll` test (added in #5149) started to fail. Could you please take a look, if it's a real regression or we just need to change some checks? Thanks!

Hi, looks like the default pointee alignment for local AS was changed from `4` to `1` (in https://reviews.llvm.org/D118229). I suggest removing `; CHECK-NO-OPT-NEXT: .pointee_align: 4` it's not relevant to the transformation the pass does.

**Comment by vmaksimo** [comment]
> Hi, looks like the default pointee alignment for local AS was changed from `4` to `1` (in https://reviews.llvm.org/D118229). I suggest removing `; CHECK-NO-OPT-NEXT: .pointee_align: 4` it's not relevant to the transformation the pass does.

Thanks! Changed in d74dec1d

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Thu 03 Feb 2022 07:15:42 AM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Thu 03 Feb 2022 07:19:17 AM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
