### PR TITLE
[SYCL][Graph] Finalize Graph for single device

### PR DESCRIPTION
**Pull request by EwanC**
Only finalize a modifiable `command_graph` for the SYCL device that was passed on construction. We
currently finalize for every device in the context, which is unnecessary overhead and may lead to
unintended interactions with buffers used in these contexts.

PR also includes code to start waiting on for deps when adding commands to a command graph. This prevents issues where allocation commands with dependent copies could be delayed due to device being busy and execute in an incorrect order with regards to future command graph executions.

### CODE REVIEW

**Review by steffenlarsen — APPROVED** [review]
LGTM!

**Review by reble — APPROVED** [review]
LGTM

**Comment by EwanC** [comment]
@intel/llvm-gatekeepers Could we merge this please

**Comment by EwanC** [comment]
Based on post-commit CI https://github.com/intel/llvm/actions/runs/6572360130/job/17855217912 it looks like this fixes the command-buffer tests on Arc disabled in #11434

```
Unexpectedly Passed Tests (13):
  SYCL :: Graph/Explicit/basic_buffer.cpp
  SYCL :: Graph/Explicit/buffer_copy_host2target.cpp
  SYCL :: Graph/Explicit/buffer_copy_host2target_2d.cpp
  SYCL :: Graph/Explicit/buffer_copy_host2target_offset.cpp
  SYCL :: Graph/Explicit/temp_buffer_reinterpret.cpp
  SYCL :: Graph/Explicit/usm_copy.cpp
  SYCL :: Graph/RecordReplay/basic_buffer.cpp
  SYCL :: Graph/RecordReplay/buffer_copy_host2target.cpp
  SYCL :: Graph/RecordReplay/buffer_copy_host2target_2d.cpp
  SYCL :: Graph/RecordReplay/buffer_copy_host2target_offset.cpp
  SYCL :: Graph/RecordReplay/temp_buffer_reinterpret.cpp
  SYCL :: Graph/RecordReplay/usm_copy.cpp
  SYCL :: Graph/RecordReplay/usm_copy_in_order.cpp
```

Will create a PR to remove XFAIL for this platform.

**Pull request merged**
