### PR TITLE
[SYCL] Deprecate half from global namespace

### PR DESCRIPTION
**Pull request by vladimirlaz**
KhronosGroup/SYCL-Docs#40 fix was submitted.

Complementary E2E tests intel/llvm-test-suite#413
Fix to CTS KhronosGroup/SYCL-CTS#154

### CODE REVIEW

**Comment by bader** [comment]
> /Summary:run

S->s

**Comment by vladimirlaz** [comment]
Jenkins/Summary failures are caused by CTS misalignment with spec. It is fixed in KhronosGroup/SYCL-CTS#154

**Comment by bader** [comment]
> Jenkins/Summary failures are caused by CTS misalignment with spec. It is fixed in [KhronosGroup/SYCL-CTS#154](https://github.com/KhronosGroup/SYCL-CTS/pull/154)

Should we merge the test fixes before this PR? If so, I suggest we convert this PR to "draft".

**Review by bader — DISMISSED** [review]
LGTM, although this change might break some "non-conforming" code.

**Comment by vladimirlaz** [comment]
@pvchupin, @romanovvlad can we remove half alias or should deprecate first?

**Comment by romanovvlad** [comment]
> 
> 
> @pvchupin, @romanovvlad can we remove half alias or should deprecate first?

It seems we need to deprecate it first.

**Review by bader — APPROVED** [review]

**Comment by vladimirlaz** [comment]
@intel/llvm-reviewers-runtime could you please review the PR?

**Review by alexbatashev — APPROVED** [review]

**Pull request merged**
