### PR TITLE
[SYCL][Driver] Enable SPV_INTEL_memory_access_aliasing extension

### PR DESCRIPTION
**Pull request by maarquitos14**

### CODE REVIEW

**Comment by mdtoguchi** [comment]
@maarquitos14, will there be additional changes done to the `clang-linker-wrapper` to add this extension for the new offloading model?

**Comment by maarquitos14** [comment]
> @maarquitos14, will there be additional changes done to the `clang-linker-wrapper` to add this extension for the new offloading model?

Tbh, I just adapted https://github.com/intel/llvm/pull/4025 to the current codebase. What additional changes do we need to add this extension for the new offloading model?

**Comment by mdtoguchi** [comment]
> > @maarquitos14, will there be additional changes done to the `clang-linker-wrapper` to add this extension for the new offloading model?
> 
> Tbh, I just adapted #4025 to the current codebase. What additional changes do we need to add this extension for the new offloading model?

Perform a similar addition to https://github.com/intel/llvm/blob/2422e854ada5252f9ccfbfea9187a70abd0068bf/clang/tools/clang-linker-wrapper/ClangLinkerWrapper.cpp#L764 should take care of it

**Comment by maarquitos14** [comment]
> > > @maarquitos14, will there be additional changes done to the `clang-linker-wrapper` to add this extension for the new offloading model?
> > 
> > 
> > Tbh, I just adapted #4025 to the current codebase. What additional changes do we need to add this extension for the new offloading model?
> 
> Perform a similar addition to
> 
> https://github.com/intel/llvm/blob/2422e854ada5252f9ccfbfea9187a70abd0068bf/clang/tools/clang-linker-wrapper/ClangLinkerWrapper.cpp#L764
> 
> should take care of it

Done :)

**Review by mdtoguchi — APPROVED** [review]
Thanks - OK for driver.  Is there some test for the extensions for clang-linker-wrapper?

**Comment by maarquitos14** [comment]
> Thanks - OK for driver. Is there some test for the extensions for clang-linker-wrapper?

I checked, but didn't find any. Glad to update it if I missed it.

**Comment by AlexeySachkov** [comment]
> > Thanks - OK for driver. Is there some test for the extensions for clang-linker-wrapper?
> 
> I checked, but didn't find any. Glad to update it if I missed it.

@maksimsab, @asudarsa, do you know?

**Comment by maarquitos14** [comment]
> > Thanks - OK for driver. Is there some test for the extensions for clang-linker-wrapper?
> 
> It looks like we are missing such a test.

@mdtoguchi @AlexeySachkov should I add it here or should that be addressed in a different PR?

**Comment by maarquitos14** [comment]
@mdtoguchi @AlexeySachkov ping

**Review by AlexeySachkov — APPROVED** [review]

**Comment by maarquitos14** [comment]
@intel/llvm-gatekeepers I think this is ready to merge :)

**Pull request merged**
