### PR TITLE
[SYCL][libdevice] Add always_inline for libdevice functions.

### PR DESCRIPTION
**Pull request by jinge90**
Signed-off-by: jinge90 <ge.jin@intel.com>

### CODE REVIEW

**Comment by jinge90** [comment]
This PR decorates all functions in SYCL libdevice with "always_inline" which is friendly to underlying runtime to do inline optimization.

**Comment by jinge90** [comment]
Hi, @xtian-github 
This PR adds "__attribute__((always_inline))" to all libdevice functions. With this patch, we can see "AlwaysInline" is used to decorated all libdevice functions in LLVM IR level. Does this meet underlying runtime's requirement?

Thanks very much.

**Comment by xtian-github** [comment]
> Hi, @xtian-github This PR adds "**attribute**((always_inline))" to all libdevice functions. With this patch, we can see "AlwaysInline" is used to decorated all libdevice functions in LLVM IR level. Does this meet underlying runtime's requirement?
> 
> Thanks very much.

Yes. Thanks.

**Review by xtian-github — APPROVED** [review]
LGTM

**Comment by xtian-github** [comment]
> > This PR decorates all functions in SYCL libdevice with "always_inline" which is friendly to underlying runtime to do inline optimization.
> 
> I still have questions about reasoning of this fix. 1) Can "underlying runtime" do inlining without this attribute now? 2) If (1) is Yes, then wouldn't adding this attribute unconditionally to all device funcs increase the code size on device too much?

Actually, the current compiler is trying to do "always_inline" for device already, adding this attribute is to add certain guarantee. It does not increase the code size on device much.

**Comment by v-klochkov** [comment]
> > > This PR decorates all functions in SYCL libdevice with "always_inline" which is friendly to underlying runtime to do inline optimization.
> > 
> > 
> > I still have questions about reasoning of this fix. 1) Can "underlying runtime" do inlining without this attribute now? 2) If (1) is Yes, then wouldn't adding this attribute unconditionally to all device funcs increase the code size on device too much?
> 
> Actually, the current compiler is trying to do "always_inline" for device already, adding this attribute is to add certain guarantee. It does not increase the code size on device much.

It sounds like the compiler is doing great job already and "is trying to do always_inline for device always". If there are cases where inlining is not done, then there are good reasons for that, right?

Also, is this fix motivated by correctness performance reasons?

**Comment by xtian-github** [comment]
@v-klochkov  provide guarantee on performance.

**Review by v-klochkov — APPROVED** [review]

**Comment by al42and** [comment]
Note: there are now numerous warnings in libdevice due to conflicting attributes:

```
/home/aland/intel-sycl/llvm/libdevice/device_itt.h:78:1: warning: 'always_inline' attribute ignored [-Wignored-attributes]
DEVICE_EXTERN_C ITT_STUB_ATTRIBUTES void
^
/home/aland/intel-sycl/llvm/libdevice/device.h:26:25: note: expanded from macro 'DEVICE_EXTERN_C'
#define DEVICE_EXTERN_C DEVICE_EXTERNAL EXTERN_C
                        ^
/home/aland/intel-sycl/llvm/libdevice/device.h:21:54: note: expanded from macro 'DEVICE_EXTERNAL'
  SYCL_EXTERNAL __attribute__((weak)) __attribute__((always_inline))
                                                     ^
/home/aland/intel-sycl/llvm/libdevice/device_itt.h:78:17: note: conflicting attribute is here
DEVICE_EXTERN_C ITT_STUB_ATTRIBUTES void
                ^
/home/aland/intel-sycl/llvm/libdevice/device_itt.h:17:54: note: expanded from macro 'ITT_STUB_ATTRIBUTES'
#define ITT_STUB_ATTRIBUTES __attribute__((noinline, optnone))
```

**Pull request merged**
