### PR TITLE
[SYCL][HIP][libclc] Add group collective functions for HIP

### PR DESCRIPTION
**Pull request by t4c1**
Adds group collective functions (reduce, scans, broadcast) for HIP.

Tested by: https://github.com/intel/llvm-test-suite/pull/656

### CODE REVIEW

**Review by Pennycook — APPROVED** [review]

**Review by bader — APPROVED** [review]

**Comment by bader** [comment]
@intel/llvm-reviewers-runtime, ping.

**Review by s-kanaev — APPROVED** [review]
Test changes seem fine for SYCL RT.

Should there be any test changes for libclc/amdgcn-amdhsa?

**Comment by bader** [comment]
> Should there be any test changes for libclc/amdgcn-amdhsa?

According to the description these changes are covered by https://github.com/intel/llvm-test-suite/pull/656. Are these enough or want to have libclc specific tests?
@t4c1, what is your opinion?

**Comment by t4c1** [comment]
Sorry, I missed the question. In my opinion the test in test suite should suffice.

**Comment by bader** [comment]
@againull, https://github.com/intel/llvm-test-suite/pull/656 must be merged at the same time, otherwise, pre-commit checks on AMD GPU will be broken.

**Comment by againull** [comment]
> @againull, [intel/llvm-test-suite#656](https://github.com/intel/llvm-test-suite/pull/656) must be merged at the same time, otherwise, pre-commit checks on AMD GPU will be broken.

Thank you, merged.

**Pull request merged**
