### PR TITLE
[SYCL] Optimize 1D accessor.

### PR DESCRIPTION
**Pull request by romanovvlad**
In case of 1D buffer, adjust pointer to buffer offset during
initialization(__init method) rather then each time in operator[] or
get_pointer functions.

+ Fix some bugs related to missing offset calculations in several
methods.

Signed-off-by: Vlad Romanov <vlad.romanov@intel.com>

### CODE REVIEW

**Comment by keryell** [comment]
By looking at this I realize that in triSYCL we do not use the same formula...
https://github.com/triSYCL/triSYCL/blob/master/include/CL/sycl/detail/linear_id.hpp
By looking at the specification it is not clear to me whether the computation should take into account the offset (Intel) or not (triSYCL)...

**Comment by romanovvlad** [comment]
> 
> 
> By looking at this I realize that in triSYCL we do not use the same formula...
> https://github.com/triSYCL/triSYCL/blob/master/include/CL/sycl/detail/linear_id.hpp
> By looking at the specification it is not clear to me whether the computation should take into account the offset (Intel) or not (triSYCL)...

Yeah... it's also not clear to me.

**Comment by romanovvlad** [comment]
> 
> 
> Could you please add tests covering changed use cases

Lit test test/basic_tests/buffer/subbuffer.cpp already tests this functionality. Is it enough?

**Comment by vladimirlaz** [comment]
> > Could you please add tests covering changed use cases
> 
> Lit test test/basic_tests/buffer/subbuffer.cpp already tests this functionality. Is it enough?

Ok for me

**Pull request merged**
