### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW04)

### PR DESCRIPTION
**Pull request by sys-ce-bb**
LLVM: llvm/llvm-project@cd7ea4ea657ea41b42fcbd0e6b33faa46608d18e
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@8c357de0dde425eb7d46810b354d143b790caba2

### CODE REVIEW

**Comment by jsji** [comment]
This is ready for review.

- [ ] [Update add-ir-annotations tests after](https://github.com/intel/llvm/pull/12495/commits/3d4c6c7631ed91039ffae824182ba5aeb5bcb657) https://github.com/intel/llvm/commit/5518a9d7673bfe55b4110bea049140316d032fbf  Testcase update from @steffenlarsen 
- [ ] [[Driver,test] Add --target= to unsupported-option-gpu.c](https://github.com/intel/llvm/pull/12495/commits/93bcfa2314014e3b8ef88756ec0ba2317a9ac54e) Cherry-pick of fixes from llorg, no review needed.
- [ ] [XFAIL internalize_vfunc.cpp on AMD HIP](https://github.com/intel/llvm/pull/12495/commits/aa3a377cc18b56c63692a2bb788be4f72c485cfa) Some bug caused/exposed by GEP i8 canonicalization https://github.com/llvm/llvm-project/commit/90ba33099cbb , XFAIL test first, @sommerlukas will follow up in https://github.com/intel/llvm/issues/12517
- [ ] [XFAIL joint_matrix_bf16_fill_k_cache_unroll.cpp on GPU](https://github.com/intel/llvm/pull/12495/commits/d4ce4f3d1c353f7c15ad51e16d05b164519f800e) Some bug caused/exposed by GEP i8 canonicalization https://github.com/llvm/llvm-project/commit/90ba33099cbb, XFAIL test first, @YuriPlyakhin will follow up in https://github.com/intel/llvm/issues/12518

**Comment by jsji** [comment]
> Generate Doxygen documentation / build (pull_request)

This is CI failures common to other PR, irrelevant .

**Comment by aelovikov-intel** [comment]
cuda e2e failure looks real.

**Comment by jsji** [comment]
> cuda e2e failure looks real.

it is the same as AMD HIP failure, I will update the XFAIL then.

**Comment by jsji** [comment]
@bader @intel/llvm-gatekeepers Can we get this merged? Thanks.

**Comment by bader** [comment]
@jsji, I'd like code owners to review the changes made on top of community commits.

**Comment by jsji** [comment]
> @jsji, I'd like code owners to review the changes made on top of community commits.

@intel/dpcpp-cfe-reviewers @sommerlukas @YuriPlyakhin Would you please add comment *explicitly* in this PR so that this can be merged. Thanks.

**Review by sommerlukas — APPROVED** [review]
Reviewed commit e2a8b3e510bd7c3b8b7d0b2c8a36d08ce1fd8ffe. 

We're already investigating the issue, but makes sense to XFAIL the test while we investigate.

**Comment by jsji** [comment]
> Reviewed commit [e2a8b3e](https://github.com/intel/llvm/commit/e2a8b3e510bd7c3b8b7d0b2c8a36d08ce1fd8ffe).
> 
> We're already investigating the issue, but makes sense to XFAIL the test while we investigate.

Thanks @sommerlukas

**Review by smanna12 — APPROVED** [review]
CFE changes look good to me.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Tue 30 Jan 2024 04:22:33 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Tue 30 Jan 2024 04:28:11 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
