### PR TITLE
[BuildBot] Sync testlist.cfg with sycl-cts repo

### PR DESCRIPTION
**Pull request by yanfeng3721**
Add new test category  test_extension/test_kernel_bundle/test_optional_kernel_features/

### CODE REVIEW

**Comment by bader** [comment]
@yanfeng3721, is it ready for review?

**Comment by bader** [comment]
@yanfeng3721, please, let me know when do you plan to merge this patch? I'd like to remove `Sync_testlist` branch ASAP.

**Comment by yanfeng3721** [comment]
Hi 

> @yanfeng3721, please, let me know when do you plan to merge this patch? I'd like to remove `Sync_testlist` branch ASAP.

Hi @bader , I am OK to merge the PR.

**Review by bader — APPROVED** [review]

**Pull request merged**
