### PR TITLE
[CI] Add windows build and LIT to pre-commit

### PR DESCRIPTION
**Pull request by pvchupin**
Task time is ~1h10m.
Will see how it impacts the pool.

### CODE REVIEW

**Comment by bader** [comment]
> Task time is ~1h10m. Will see how it impacts the pool.

I'm looking at existing pre-commit and I see that it takes ~36 min (19 min build + 17 min longest test), which is twice faster than expected Windows job. At the same time we have 2 times less Windows machines than Linux machines.
It sounds like we are going to have delays in pre-commit results.

**Comment by pvchupin** [comment]
> > Task time is ~1h10m. Will see how it impacts the pool.
> 
> I'm looking at existing pre-commit and I see that it takes ~36 min (19 min build + 17 min longest test), which is twice faster than expected Windows job. At the same time we have 2 times less Windows machines than Linux machines. It sounds like we are going to have delays in pre-commit results.

Yes, that's a drawback I'd like to highlight. Pros: getting Windows issues earlier. Cons: pre-commit will take longer.
Opinions?

**Comment by bader** [comment]
I'd like to note that pre-commit/post-commit CI jobs ratio today is 4/1.
As an alternative, I would consider configuring a notification email with post-commit results to PR author + a mailing list.

**Comment by pvchupin** [comment]
> As an alternative, I would consider configuring a notification email with post-commit results to PR author + a mailing list.

That's a reasonable alternative. Do you have any good pointers to explore?

Meanwhile just added a commit to reduce the load, skipping check-llvm and check-clang which take ~half of the time. That should make this approach a little bit more bearable...

**Review by cperkinsintel — APPROVED** [review]
LGTM

**Comment by bader** [comment]
> Do you have any good pointers to explore?

No, unfortunately, but I didn't looked for it. AFAIK, GitHub sends notifications to the account, which triggered the event only, so probably it can be some bot or third-party action.

**Pull request closed without merging**
