### PR TITLE
[ESIMD] Enable variable slm_init support.

### PR DESCRIPTION
**Pull request by kychendev**

### CODE REVIEW

**Review by v-klochkov — COMMENTED** [review]
Looks good to me. I have 1 comment and 1 question before approving the fix.
1) It would be good to have a LIT test for non-const slm_init. Perhaps a test that would also check the situation from (2) below.
2) if 'kernel' has slm_init(Constant_1024), then 1024 would be pushed to kernel's attributes (SLMSize=1024). Now what if 'kernel' calls 'other_func' that has a call of slm_init(variable_2048). Would everything work properly in this case?
    The 'other_func' may be inlined into a 'kernel' and it will end up with having attrubute SLMSize=1024 and having a call slm_init(var_2048) in it.

**Comment by kychendev** [comment]
> It would be good to have a LIT test for non-const slm_init. Perhaps a test that would also check the situation from (2) below.

It's validated with E2E functional test. But we'll need VC/BE sync to add that to test suite. I have added a LIT test for lowering in this patch.

> If 'kernel' has slm_init(Constant_1024), then 1024 would be pushed to kernel's attributes (SLMSize=1024). Now what if 'kernel' calls 'other_func' that has a call of slm_init(variable_2048). Would everything work properly in this case?
The 'other_func' may be inlined into a 'kernel' and it will end up with having attrubute SLMSize=1024 and having a call slm_init(var_2048) in it.

This extension shouldn't change the existing convention. The programmer is responsible to summarize the SLM usage and use a single slm_init to set up SLM properly for the kernel.

**Review by v-klochkov — APPROVED** [review]

**Comment by kychendev** [comment]
LIT test failed due to VC out of sync. Pushed a patch to disable it for now.

**Review by v-klochkov — APPROVED** [review]

**Comment by kychendev** [comment]
Passed esimd tests. There is one failure which should be irrelevant to this PR:
Failed Tests (1):
  SYCL :: KernelAndProgram/undefined-symbol.cpp

**Review by kbobrovs — APPROVED** [review]

**Pull request merged**
