### PR TITLE
[SYCL] Get set rounding mode in kernel

### PR DESCRIPTION
**Pull request by jinge90**
This PR is for some experiments, no need to review for now.

### CODE REVIEW

**Comment by xtian-github** [comment]
All code owners please review JinGe's PR, we need to merge this PR soon for an DSE OKR. Thanks!

**Comment by dm-vodopyanov** [comment]
@jinge90 @xtian-github is there a reason why the patch is in draft state? Also lint is failing, so no tests started.

**Comment by bso-intel** [comment]
> @jinge90 @xtian-github is there a reason why the patch is in draft state? Also lint is failing, so no tests started.

I don't think this PR is ready for review.
The PR description says clearly:
`This PR is for some experiments, no need to review for now.`

**Comment by xtian-github** [comment]
@jinge90  When we can move this PR to ready for review? Thanks.

**Pull request closed without merging**
