### PR TITLE
[SYCLLowerIR] Promote i8 and i16 arguments in MutatePrintfAddrspace

### PR DESCRIPTION
**Pull request by hewj03**

### CODE REVIEW

**Comment by hewj03** [comment]
@AGindinson could you please take a look?

**Comment by AlexeySachkov** [comment]
@hewj03, could you please share some insights about the motivation for this change?

My understanding is that such integer promotions will automatically occur for variadic printf, from [cppreference](https://en.cppreference.com/w/cpp/language/variadic_arguments):

> <html>
<body>
<h3 style="color: rgb(0, 0, 0); background: none rgb(255, 255, 255); font-weight: bold; margin: 0px 0px 0.3em; overflow: hidden; padding: 1.1em 0px 0.2em 0.75em; border-bottom: none; width: auto; font-size: 16.896px; font-family: DejaVuSans, &quot;DejaVu Sans&quot;, arial, sans-serif; font-style: normal; font-variant-ligatures: no-common-ligatures; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="mw-headline" id="Default_conversions">Default conversions</span></h3><p style="margin: 0.4em 0px 0.5em; line-height: 1.2em; color: rgb(0, 0, 0); font-family: DejaVuSans, &quot;DejaVu Sans&quot;, arial, sans-serif; font-size: 12.8px; font-style: normal; font-variant-ligatures: no-common-ligatures; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">When a variadic function is called, after lvalue-to-rvalue, array-to-pointer, and function-to-pointer<span> </span><a href="https://en.cppreference.com/w/cpp/language/implicit_conversion#Value_transformations" title="cpp/language/implicit conversion" style="text-decoration: none; color: rgb(6, 69, 173); background: none;">conversions</a>, each argument that is a part of the variable argument list undergoes additional conversions known as<span> </span><i>default argument promotions</i>:</p>

std::nullptr_t is converted to void* | (since C++11)
-- | --


<ul style="line-height: 1.5em; list-style-type: square; margin: 0.3em 0px 0.5em 1.6em; padding: 0px; list-style-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAANCAMAAABW4lS6AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRFAFKM////QIUK9QAAAAJ0Uk5T/wDltzBKAAAAGklEQVR42mJgBAEGokgGBjBGBxBxsBqAAAMACHwALd5r8ygAAAAASUVORK5CYII=&quot;); color: rgb(0, 0, 0); font-family: DejaVuSans, &quot;DejaVu Sans&quot;, arial, sans-serif; font-size: 12.8px; font-style: normal; font-variant-ligatures: no-common-ligatures; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="margin-bottom: 0.1em; line-height: 1.2em; margin-top: 0.3em;"><span class="t-c" style="background-color: rgba(0, 0, 0, 0.03); border: 1px solid rgb(214, 214, 214); border-radius: 3px; margin: 0px 2px; padding: 0px 2px; display: inline-block;"><span class="mw-geshi cpp source-cpp" style="font-family: monospace; line-height: normal; white-space: nowrap;"><span class="kw4" style="color: rgb(0, 0, 255);">float</span></span></span><span> </span>arguments are converted to<span> </span><span class="t-c" style="background-color: rgba(0, 0, 0, 0.03); border: 1px solid rgb(214, 214, 214); border-radius: 3px; margin: 0px 2px; padding: 0px 2px; display: inline-block;"><span class="mw-geshi cpp source-cpp" style="font-family: monospace; line-height: normal; white-space: nowrap;"><span class="kw4" style="color: rgb(0, 0, 255);">double</span></span></span><span> </span>as in<span> </span><a href="https://en.cppreference.com/w/cpp/language/implicit_conversion#Floating-point_promotion" title="cpp/language/implicit conversion" style="text-decoration: none; color: rgb(6, 69, 173); background: none;">floating-point promotion</a></li><li style="margin-bottom: 0.1em; line-height: 1.2em; margin-top: 0.3em;"><span class="t-c" style="background-color: rgba(0, 0, 0, 0.03); border: 1px solid rgb(214, 214, 214); border-radius: 3px; margin: 0px 2px; padding: 0px 2px; display: inline-block;"><span class="mw-geshi cpp source-cpp" style="font-family: monospace; line-height: normal; white-space: nowrap;"><span class="kw4" style="color: rgb(0, 0, 255);">bool</span></span></span>,<span> </span><span class="t-c" style="background-color: rgba(0, 0, 0, 0.03); border: 1px solid rgb(214, 214, 214); border-radius: 3px; margin: 0px 2px; padding: 0px 2px; display: inline-block;"><span class="mw-geshi cpp source-cpp" style="font-family: monospace; line-height: normal; white-space: nowrap;"><span class="kw4" style="color: rgb(0, 0, 255);">char</span></span></span>,<span> </span><span class="t-c" style="background-color: rgba(0, 0, 0, 0.03); border: 1px solid rgb(214, 214, 214); border-radius: 3px; margin: 0px 2px; padding: 0px 2px; display: inline-block;"><span class="mw-geshi cpp source-cpp" style="font-family: monospace; line-height: normal; white-space: nowrap;"><span class="kw4" style="color: rgb(0, 0, 255);">short</span></span></span>, and unscoped enumerations are converted to<span> </span><span class="t-c" style="background-color: rgba(0, 0, 0, 0.03); border: 1px solid rgb(214, 214, 214); border-radius: 3px; margin: 0px 2px; padding: 0px 2px; display: inline-block;"><span class="mw-geshi cpp source-cpp" style="font-family: monospace; line-height: normal; white-space: nowrap;"><span class="kw4" style="color: rgb(0, 0, 255);">int</span></span></span><span> </span>or wider integer types as in<span> </span><a href="https://en.cppreference.com/w/cpp/language/implicit_conversion#Integral_promotion" title="cpp/language/implicit conversion" style="text-decoration: none; color: rgb(6, 69, 173); background: none;">integer promotion</a></li></ul>
</body>
</html>

If you are trying to fix non-variadic printf which we have introduced, then I'm not sure that this is a correct fix, because at SPIR-V level, [`printf`](https://www.khronos.org/registry/SPIR-V/specs/1.0/OpenCL.ExtendedInstructionSet.100.html#printf) is not variadic by its nature and therefore, no promotions should be expected.

**Comment by hewj03** [comment]
> @hewj03, could you please share some insights about the motivation for this change?
> 
> My understanding is that such integer promotions will automatically occur for variadic printf, from [cppreference](https://en.cppreference.com/w/cpp/language/variadic_arguments):
> 
> > 
> 
> ### Default conversions
> When a variadic function is called, after lvalue-to-rvalue, array-to-pointer, and function-to-pointer [conversions](https://en.cppreference.com/w/cpp/language/implicit_conversion#Value_transformations), each argument that is a part of the variable argument list undergoes additional conversions known as default argument promotions:
> 
> std::nullptr_t is converted to void*	(since C++11)
> * float arguments are converted to double as in [floating-point promotion](https://en.cppreference.com/w/cpp/language/implicit_conversion#Floating-point_promotion)
> * bool, char, short, and unscoped enumerations are converted to int or wider integer types as in [integer promotion](https://en.cppreference.com/w/cpp/language/implicit_conversion#Integral_promotion)
> 
> If you are trying to fix non-variadic printf which we have introduced, then I'm not sure that this is a correct fix, because at SPIR-V level, [`printf`](https://www.khronos.org/registry/SPIR-V/specs/1.0/OpenCL.ExtendedInstructionSet.100.html#printf) is not variadic by its nature and therefore, no promotions should be expected.

@AlexeySachkov thanks for the explanation. I agree.

This is only for variadic printf. I see in the header of this file that this pass is a temporary solution. How long will this pass stay? I think ideally this pass shall make a clone of _ZN2cl4sycl3ext6oneapi12experimental6printf with AS changed.

**Comment by AlexeySachkov** [comment]
> This is only for variadic printf. I see in the header of this file that this pass is a temporary solution. How long will this pass stay? I think ideally this pass shall make a clone of _ZN2cl4sycl3ext6oneapi12experimental6printf with AS changed.

@hewj03, we plan to implement proper support for format string in address spaces other than the constant one, see KhronosGroup/SPIRV-LLVM-Translator#1364. Once the support for that new SPIR-V extension is implemented and adopted across our SYCL BEs, we will drop the pass. So, I would expect it to be there for at least several months more

**Comment by hewj03** [comment]
@AlexeySachkov thank you for the info.

**Pull request closed without merging**
