### PR TITLE
Merge from intel/llvm sycl branch (85851165290d)

### PR DESCRIPTION
**Pull request by whitneywhtsang**
Please only review 7d2f11ff685bb98b59a33f7bd2988e72197ddfb1, which fixes the merge failures.

fee486e149ac99e7a61937e1346730048c4c6754 causes  `single_task.cpp` to fail at runtime.
Reverted fee486e149ac99e7a61937e1346730048c4c6754 in 243bd7eb3f321082f22ed732ccf82826a8c7df73 to unblock the merge.
Will need to investigate the failure and put back fee486e149ac99e7a61937e1346730048c4c6754 .

All files changed in 7d2f11ff685bb98b59a33f7bd2988e72197ddfb1 are clang-formatted. I intentionally not clang-format files that I didn't modify. 
So the lint failure is expected.

Manually verified: `check-mlir-sycl`, `check-polygeist-opt`, `check-cgeist`, and running `single_task.cpp` on CPU device.

**Please do not to squash and merge this PR.**

### CODE REVIEW

**Comment by sommerlukas** [comment]
How does this PR relate to #7206?

**Comment by whitneywhtsang** [comment]
> How does this PR relate to #7206?

#7206 merge to commit 2cefad19dfb7, and this PR merge to commit 85851165290d, which is after commit 2cefad19dfb7.

**Comment by whitneywhtsang** [comment]
> Reviewed the changes in [7d2f11f](https://github.com/intel/llvm/commit/7d2f11ff685bb98b59a33f7bd2988e72197ddfb1)

Thanks!
> 
> These changes look good, as these are mostly changes due to upstream MLIR/LLVM API changes. Just posted a single question here: [7d2f11f#r88162840](https://github.com/intel/llvm/commit/7d2f11ff685bb98b59a33f7bd2988e72197ddfb1#r88162840)

Replied.
> For the changes to the llvm-lit tests in `Verification/` for polygeist, I did a random sampling, assuming these checks are generated automatically/with some script, right?

Unfortunately, they are not auto generated.  Do we have such a script in MLIR?

**Comment by sommerlukas** [comment]
> Unfortunately, they are not auto generated. Do we have such a script in MLIR?

I was thinking of this script here: https://github.com/intel/llvm/blob/sycl/mlir/utils/generate-test-checks.py

It's been a while since I last used it, but back then I found it quite handy to build larger MLIR llvm-lit tests.

**Comment by whitneywhtsang** [comment]
> > Unfortunately, they are not auto generated. Do we have such a script in MLIR?
> 
> I was thinking of this script here: https://github.com/intel/llvm/blob/sycl/mlir/utils/generate-test-checks.py
> 
> It's been a while since I last used it, but back then I found it quite handy to build larger MLIR llvm-lit tests.

Good to know, I used the one for LLVM before, didn't know there is one for MLIR.

**Pull request merged**
