### PR TITLE
[BuildBot] Uplift GPU RT version for Linux CI Process

### PR DESCRIPTION
**Pull request by bb-sycl**
Uplift GPU RT version for Linux to 22.42.24548

### CODE REVIEW

**Comment by yanfeng3721** [comment]
Hi @bader , do we still use buildbot/dependency.conf to maintain the dependency? I checked the sycl-ls output for "SYCL / Linux / L0 GEN9 LLVM Test Suite (pull_request_target", it looks like it was aligned with the version in https://github.com/intel/llvm/blob/sycl/devops/dependencies.json.
```
 [opencl:gpu:0] Intel(R) OpenCL HD Graphics, Intel(R) UHD Graphics [0x9bca] 3.0 [22.38.24278]
```

**Comment by bader** [comment]
> Hi @bader , do we still use buildbot/dependency.conf to maintain the dependency? I checked the sycl-ls output for "SYCL / Linux / L0 GEN9 LLVM Test Suite (pull_request_target", it looks like it was aligned with the version in https://github.com/intel/llvm/blob/sycl/devops/dependencies.json.
> 
> ```
>  [opencl:gpu:0] Intel(R) OpenCL HD Graphics, Intel(R) UHD Graphics [0x9bca] 3.0 [22.38.24278]
> ```

GitHub Action CI uses https://github.com/intel/llvm/blob/sycl/devops/dependencies.json.
AFAIK, Jenkins is still using buildbot/dependency.conf file. @DoyleLi, could you confirm, please?

**Comment by DoyleLi** [comment]
> > Hi @bader , do we still use buildbot/dependency.conf to maintain the dependency? I checked the sycl-ls output for "SYCL / Linux / L0 GEN9 LLVM Test Suite (pull_request_target", it looks like it was aligned with the version in https://github.com/intel/llvm/blob/sycl/devops/dependencies.json.
> > ```
> >  [opencl:gpu:0] Intel(R) OpenCL HD Graphics, Intel(R) UHD Graphics [0x9bca] 3.0 [22.38.24278]
> > ```
> 
> GitHub Action CI uses https://github.com/intel/llvm/blob/sycl/devops/dependencies.json. AFAIK, Jenkins is still using buildbot/dependency.conf file. @DoyleLi, could you confirm, please?

Yes, currently the Jenkins is still using .conf file, since we have CI process to parse dependency values. Currently tools team is preparing to switch to .json file to align with other CI jobs. Before that, please keep the PR to uplift .conf file, thanks. I will suspend the uplift process when we switched to .json totally.

**Comment by pvchupin** [comment]
This specific version of driver is broken

**Pull request closed without merging**
