### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW38)

### PR DESCRIPTION
**Pull request by sys-ce-bb**
LLVM: llvm/llvm-project@ca3ed7b
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@aab0dac

### CODE REVIEW

**Comment by jsji** [comment]
This is ready for review, changes need to be reviewed.

- [ ] [Revert](https://github.com/intel/llvm/pull/11253/commits/56a5cb3a879463fa3f4b5cc3345e37de940757f6) https://github.com/intel/llvm/commit/8060cd36fe2060c23a397e059b88b1bac0559c42 [Revert [clang] Replace use of Type::getPointerTo() (NFC)](https://github.com/intel/llvm/pull/11253/commits/56a5cb3a879463fa3f4b5cc3345e37de940757f6)  This is change to sync with upstream to fix the ICE in Clang::CodeGenCXX/try-catch-with-address-space.cpp. 
@jyu2-git @intel/dpcpp-cfe-reviewers @bader

**Comment by jsji** [comment]
Ping @intel/dpcpp-cfe-reviewers @bader. Thanks!

**Review by elizabethandrews — APPROVED** [review]
Change look ok to me. @jyu2-git can you also take a look? This may conflict with changes you've made downstream.

**Comment by jsji** [comment]
@intel/llvm-gatekeepers Can we get this merged? Thanks.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Tue 26 Sep 2023 09:30:59 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Tue 26 Sep 2023 09:35:32 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
