### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW16 2024)

### PR DESCRIPTION
**Pull request by iclsrc**
LLVM: llvm/llvm-project@af7a82fdc717c9cbd1b77ff4168292098a1f6e8a
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@e1f7ebee5ed8b90

### CODE REVIEW

**Comment by jsji** [comment]
This is ready for review.
- [ ] [Fix integration_header.cpp test due to](https://github.com/intel/llvm/pull/13484/commits/07007595e3ec2df0854c75434d3f2e3b34909bf5) https://github.com/intel/llvm/commit/71c0784dc4a2ef40039a97af122ba78549193120  Testcase update due to final keyword change. @intel/dpcpp-cfe-reviewers 
- [ ] [Disable OpLessOrGreater test until SPIR-V 1.5 is supported](https://github.com/intel/llvm/pull/13484/commits/d800d17cf26419eb2381b445d97c3c80543ba626) Essentially @vmaksimo 's fixes . @intel/dpcpp-spirv-reviewers 
- [ ] [Call updateModeleVersion to enable SPIRV inst version check](https://github.com/intel/llvm/pull/13484/commits/3c89596885adb865b3d1be2fbb381599489147fe) Essentially @vmaksimo 's fixes . @intel/dpcpp-spirv-reviewers

**Comment by jsji** [comment]
@intel/dpcpp-cfe-reviewers @intel/dpcpp-spirv-reviewers @vmaksimo Can you have a look and add comments/approval explicitly so that this can be merged. Thanks.

**Review by vmaksimo — APPROVED** [review]
Approve for llvm-spirv fixes.

**Review by smanna12 — APPROVED** [review]
CFE change looks good to me. Thanks

**Comment by jsji** [comment]
Thank you @vmaksimo and @smanna12 .

@bader @intel/llvm-gatekeepers This is ready for merge == arc failures are due to not available runners, common to other PRs. Thanks.

**Comment by jsji** [comment]
Incorporate https://github.com/intel/llvm/pull/13358 into pulldown.
@premanandrao @ldrumm Can you please have a look to see whether I do it right to resolve the conflicts and keep the correct authorship. Thanks.

**Comment by ldrumm** [comment]
> Incorporate #13358 into pulldown. @premanandrao @ldrumm Can you please have a look to see whether I do it right to resolve the conflicts and keep the correct authorship. Thanks.

https://github.com/intel/llvm/pull/13484/commits/f27e5de82dae8af5a09913179849d2304bb5b6e3

Looks great. Thanks for making sure this is done right

**Comment by jsji** [comment]
@bader @intel/llvm-gatekeepers This is ready for merge now. Thanks.

**Comment by jsji** [comment]
@bader is on vacation. @intel/llvm-gatekeepers Can someone issue a `/merge` to get this merged. Thanks.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Wed 24 Apr 2024 03:16:27 AM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Wed 24 Apr 2024 03:20:42 AM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Comment by jsji** [comment]
> /merge

Thank you @aelovikov-intel

**Pull request merged**
