### PR TITLE
[SYCL][E2E] Disable reduction_span.cpp on AMD HIP

### PR DESCRIPTION
**Pull request by sarnex**
It's failing
https://github.com/intel/llvm/issues/15227

### CODE REVIEW

**Comment by aelovikov-intel** [comment]
I don't think we should be disabling tests failing in nightly. Instead, analysis and fix should be high priority.

**Comment by sarnex** [comment]
> I don't think we should be disabling tests failing in nightly. Instead, analysis and fix should be high priority.

@bader Any opinion on how we should handle nightly failures?

**Comment by sarnex** [comment]
Discussed offline, seems legit to me, at least for this case. Seems like the pulldown broke it.

**Comment by bader** [comment]
> Seems like the pulldown broke it.

Don't we run this test during pulldown PR pre-commit validation?
If we do, I expect the test to fail in pre-commit (unless the failure is unstable).

> > I don't think we should be disabling tests failing in nightly. Instead, analysis and fix should be high priority.
> 
> @bader Any opinion on how we should handle nightly failures?

@sarnex, as you are the only person who closely watching nightly results, I leave it to you to decide. I agree with @aelovikov-intel that the issue you opened should be high priority. From my POV "analysis and fix should be high priority" and "disabling tests failing in nightly" are not mutually exclusive.

**Comment by sarnex** [comment]
Thanks for the opinion.

**Pull request closed without merging**
