### PR TITLE
[SYCL] Remove -full-main-file-name and -fsycl-use-main-file-name options.

### PR DESCRIPTION
**Pull request by zahiraam**
These two options were implemented to solve two issues (missing `checksum` for the main file on Windows and host compilation `DICompileUnit` pointing to a temporary file instead of the original source file). The introduction of the `-include-footer` solves these issues. These options can now be removed.

### CODE REVIEW

**Comment by zahiraam** [comment]
@stevemerr I have done some local test including the one I mentioned to you offline and it's passing. I think it would be nice to have you test full DBG testing to see if this change works for you. Thanks.

**Review by mdtoguchi — APPROVED** [review]
Cleanup OK for driver

**Review by elizabethandrews — COMMENTED** [review]
FE cleanup looks ok to me. However, I am not very familiar with this functionality. Please wait for approval from @premanandrao and/or someone from the debug team

**Review by bwyma — APPROVED** [review]
LGTM.

**Review by smanna12 — APPROVED** [review]

**Comment by zahiraam** [comment]
@premanandrao Can you please review this? Thanks.

**Review by premanandrao — APPROVED** [review]
FE changes LGTM

**Comment by zahiraam** [comment]
@intel/llvm-gatekeepers Can this be merged please? Thanks.

**Pull request merged**
