### PR TITLE
Revert "[SYCL] disallow mutable lambdas"

### PR DESCRIPTION
**Pull request by romanovvlad**
Reverts intel/llvm#1785

### CODE REVIEW

**Comment by romanovvlad** [comment]
The patch breaks CTS.

**Comment by andykaylor** [comment]
Are you reverting this because of the failure in test_hierarchical_opencl? I saw the same test fail in the same way with PR 2159. I wondered if it might be a flaky test issue.

**Comment by romanovvlad** [comment]
> 
> 
> Are you reverting this because of the failure in test_hierarchical_opencl? I saw the same test fail in the same way with PR 2159. I wondered if it might be a flaky test issue.

No. Do not think these fails are connected.

**Comment by andykaylor** [comment]
> > Are you reverting this because of the failure in test_hierarchical_opencl? I saw the same test fail in the same way with PR 2159. I wondered if it might be a flaky test issue.
> 
> No. Do not think these fails are connected.

OK, I see. There are many other failures here. I didn't see the others in the partial Jenkins log file in the first view I got.

Thanks.

**Comment by vladimirlaz** [comment]
> > > Are you reverting this because of the failure in test_hierarchical_opencl? I saw the same test fail in the same way with PR 2159. I wondered if it might be a flaky test issue.
> > 
> > 
> > No. Do not think these fails are connected.
> 
> OK, I see. There are many other failures here. I didn't see the others in the partial Jenkins log file in the first view I got.
> 
> Thanks.

The real regressions are. All next post-comit jobs have the same failures.

[2020-07-29T17:54:20.319Z] [2020-07-29 17:54:19,847] SYCL CTS INFO: List of new failures:

[2020-07-29T17:54:20.319Z] test_stream_opencl

[2020-07-29T17:54:20.319Z] test_opencl_interop_opencl

[2020-07-29T17:54:20.319Z] test_accessor_opencl

[2020-07-29T17:54:20.319Z] test_atomic_opencl

[2020-07-29T17:54:20.319Z] test_invoke_opencl

[2020-07-29T17:54:20.319Z] test_program_opencl

[2020-07-29T17:54:20.319Z] test_event_opencl

[2020-07-29T17:54:20.319Z] test_handler_opencl

[2020-07-29T17:54:20.319Z] test_kernel_opencl

[2020-07-29T17:54:20.319Z] test_item_opencl

[2020-07-29T17:54:20.319Z] test_nd_item_opencl

**Pull request merged**
