### PR TITLE
[NFC][SYCL] Remove explicit cl:: namespace usage

### PR DESCRIPTION
**Pull request by aelovikov-intel**
That is part of the change of removing cl:: entirely according to the
SYCL 2020 specification.

### CODE REVIEW

**Review by v-klochkov — DISMISSED** [review]

**Comment by v-klochkov** [comment]
Please add the link to corresponding changes in llvm-test-suite here.

**Comment by aelovikov-intel** [comment]
> Please add the link to corresponding changes in llvm-test-suite here.

It was supposed to be a standalone change. I'll investigate the failures.

**Comment by aelovikov-intel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1118

**Comment by aelovikov-intel** [comment]
Ping.

**Review by v-klochkov — APPROVED** [review]

**Comment by aelovikov-intel** [comment]
@intel/llvm-gatekeepers , PR is ready, I think.

**Comment by keryell** [comment]
Nice.
I do not think this really qualify for `[NFC]`.
Any program using the old non standard namespace will know fail to compile.

**Comment by aelovikov-intel** [comment]
This one only changed the references to the symbols and is NFC. Non-NFC elimination has been done later in https://github.com/intel/llvm/pull/6518.

**Comment by keryell** [comment]
@aelovikov-intel I missed the big picture. Thanks for the clarification!

**Pull request merged**
