### PR TITLE
[NFC][sycl-post-link] Move -support-dynamic-linking option

### PR DESCRIPTION
**Pull request by LU-JOHN**
--support-dynamic-linking affects behavior of ModuleSplitter.cpp.  Move option from sycl-post-link.cpp to ModuleSplitter.cpp so it does not have to be passed through many function calls.

### CODE REVIEW

**Review by VyacheslavLevytskyy — APPROVED** [review]

**Comment by asudarsa** [comment]
Implementation looks ok. but I have couple of concerns.
1. It seems like quite a bit of plumbing just to avoid a couple of extra arguments to be passed in.
2. Why is '-support-dynamic-linking' the only option handled like this? Are there no other options? Can we not avoid passing EmitKernelsOnlyAsEntryPoints as well?

Thanks.

**Comment by sarnex** [comment]
I have similar questions to Arvind, thanks.

**Comment by LU-JOHN** [comment]
> Implementation looks ok. but I have couple of concerns.
> 
> 1. It seems like quite a bit of plumbing just to avoid a couple of extra arguments to be passed in.
> 2. Why is '-support-dynamic-linking' the only option handled like this? Are there no other options? Can we not avoid passing EmitKernelsOnlyAsEntryPoints as well?
> 
> Thanks.

This change was done in preparation for doing Internalization.  Internalization requires SupportDynamicLinking to be used in cleanup which would require a lot more passing.  Even before Internalization SupportDynamicLinking already had 12 call-sites and parameter declarations that were eliminated by this change. 

This approach could also be taken for EmitKernelsOnlyAsEntryPoints, but I was only focused on preparing for Internalization.

I would have preferred:
`extern cl::opt<bool> SupportDynamicLinking;`
in ModuleSplitter.cpp, but this failed because ModuleSplitter.cpp was in a library and this dependency was not allowed.

**Review by sarnex — APPROVED** [review]
I found many other examples of similar code throughout the general LLVM codebase, so seems fine to me.

**Pull request merged**
