### PR TITLE
[SYCL] Make context constructors explicit to avoid unintended conversions

### PR DESCRIPTION
**Pull request by jbrodman**
Signed-off-by: James Brodman <james.brodman@intel.com>

### CODE REVIEW

**Comment by keryell** [comment]
And also generally track this in the specification committee since often there happen to be specification bugs...

**Comment by jbrodman** [comment]
@keryell Expect a spec PR. :)

**Comment by elizabethandrews** [comment]
Should this be done for queue class as well? device to queue conversions cause crashes as well. I haven't verified this but I am pretty sure that a call cl::sycl::free(ptr_1k, device); will crash once this patch is merged in, due to the device to queue conversion.

**Comment by jbrodman** [comment]
> Should this be done for queue class as well? device to queue conversions cause crashes as well. I haven't verified this but I am pretty sure that a call cl::sycl::free(ptr_1k, device); will crash once this patch is merged in, due to the device to queue conversion.

Probably.  It would also be good to add a test.

**Comment by elizabethandrews** [comment]
I can update this patch (https://github.com/otcshare/llvm/pull/830) to just include queue constructors. Is the test there enough?

**Comment by elizabethandrews** [comment]
Ok. Will do.

**Pull request merged**
