### PR TITLE
[SYCL] Re-introduce "Use mp11 to sort compile-time properties"

### PR DESCRIPTION
**Pull request by uditagarwal97**
This PR reintroduces #8168 that was reverted by #8325 due to some build errors with MSVC compilers. Upon inspection, it was found that the build errors occur only in the case of incremental builds. With clean builds - i.e. completely removing the build directory and re-configuring/re-building again - there won't be any errors.

--------------
Currently, compile-time properties are sorted using a hand-written implementation of merge-sort. However, this PR propose to sort compile-time properties using Boost's MP11 metaprogramming library instead. Mp11's sorting functionality is more optimized and it also improves the overall code readability (83 LOC vs just 11 LOC).

PS:- This PR does not introduce any new dependency as Mp11 is already integrated into the code base (See https://github.com/intel/llvm/pull/5791).

### CODE REVIEW

**Comment by bader** [comment]
@uditagarwal97, please, create a draft PR to prevent unexpected merges. See step 6: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request#creating-the-pull-request.

**Review by steffenlarsen — APPROVED** [review]
Thanks! Let's give it another go! 🚀

**Comment by uditagarwal97** [comment]
@bader the PR is ready. One of the CI job for this PR is queued for about 19 hours, I tried restarting it but that didn't worked. Any help on that would also be appreciated. Thanks!

**Comment by bader** [comment]
> @bader the PR is ready. One of the CI job for this PR is queued for about 19 hours, I tried restarting it but that didn't worked. Any help on that would also be appreciated. Thanks!

I see that you re-running CI jobs. Did you re-run only failed jobs or all jobs?

**Comment by uditagarwal97** [comment]
> > @bader the PR is ready. One of the CI job for this PR is queued for about 19 hours, I tried restarting it but that didn't worked. Any help on that would also be appreciated. Thanks!
> 
> I see that you re-running CI jobs. Did you re-run only failed jobs or all jobs?

I have re-run'd only the failed jobs.

**Comment by bader** [comment]
> > > @bader the PR is ready. One of the CI job for this PR is queued for about 19 hours, I tried restarting it but that didn't worked. Any help on that would also be appreciated. Thanks!
> > 
> > 
> > I see that you re-running CI jobs. Did you re-run only failed jobs or all jobs?
> 
> I have re-run'd only the failed jobs.

@apstasen, I think this functionality is broken i.e. we can't restart only jobs failed on AWS instance. Am I right?

**Comment by bader** [comment]
@steffenlarsen, please, merge this PR, if you think the issue has been resolved.

**Comment by steffenlarsen** [comment]
> @steffenlarsen, please, merge this PR, if you think the issue has been resolved.

I suspect it is, but I would like to wait for a green post-commit to avoid false-positives. @uditagarwal97 - Please remind me if I forget.

**Comment by uditagarwal97** [comment]
> > @steffenlarsen, please, merge this PR, if you think the issue has been resolved.
> 
> I suspect it is, but I would like to wait for a green post-commit to avoid false-positives. @uditagarwal97 - Please remind me if I forget.

@steffenlarsen the post-commit is in green.

**Pull request merged**
