### PR TITLE
SPIRV-Translator change for kernel arg annotation

### PR DESCRIPTION
**Pull request by broxigarchen**
A SPIRV translator change is merged recently to Khronos/SPIRV-LLVM-Translator. The Pull request is here
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1632

It seems the pull down sequence has some problems, thus manually merge the SPIRV-Headers and SPIRV-LLVM-Translator here.

### CODE REVIEW

**Review by MrSidims — CHANGES_REQUESTED** [review]
The change will be automatically brought here by the pulldown. So until there is a rush - I suggest no to cherry-pick the change.

**Comment by KornevNikita** [comment]
@MrSidims yes, we're having troubles with PD, so it's taking some time.

**Comment by broxigarchen** [comment]
> @MrSidims yes, we're having troubles with PD, so it's taking some time.

Hi Dmitry. Can we merge this patch manually first? Would it be a problem for future merging?

The "ESIMD Emu" test failure is a known issue tracked by another ticket here https://github.com/intel/llvm/issues/8098

**Comment by MrSidims** [comment]
> > @MrSidims yes, we're having troubles with PD, so it's taking some time.
> 
> Hi @MrSidims. Can we merge this patch manually first? Would it be a problem for future merging?
> 
> The "ESIMD Emu" test failure is a known issue tracked by another ticket here #8098

Please reason the merge to intel/llvm repository of this patch. We can discuss it offline.

**Comment by MrSidims** [comment]
I was pointer out, that we need this for https://github.com/intel/llvm/pull/6904 .

**Review by MrSidims — APPROVED** [review]
LGTM since it's needed for enabling the extension in FE patch from here https://github.com/intel/llvm/pull/6904 and the following E2E testing.

**Comment by bader** [comment]
@broxigarchen, @MrSidims, we just made a pulldown. Do we still need this patch?

**Comment by bader** [comment]
> @broxigarchen, @MrSidims, we just made a pulldown. Do we still need this patch? FYI: [0e1966f](https://github.com/intel/llvm/commit/0e1966f0e1b76d40c36d10f59448a486ba2b11fb)

I checked myself I see that pulldown commit doesn't merge this change.
@KornevNikita, just for your information - I'm merging this PR.

**Pull request merged**
