### PR TITLE
[SYCL][DeviceSanitizer] Fix incorrect private shadow range check

### PR DESCRIPTION
**Pull request by al42and**
A simple typo introduced in https://github.com/intel/llvm/pull/13450

Was causing false-positive `[kernel] Private shadow memory out-of-bound` errors.

### CODE REVIEW

**Comment by al42and** [comment]
Ping @AllanZyne

**Review by AllanZyne — APPROVED** [review]
Thanks very much!

**Comment by al42and** [comment]
CI errors look unrelated:

- Windows job fails with "rm: cannot remove <...> Device or resource busy", which in the past was solved by rebooting the affected host.
- Linux job fails due to missing HIP device (or misbehaving drivers).

**Comment by AllanZyne** [comment]
@intel/llvm-gatekeepers, please merge.
Thanks very much!

**Comment by al42and** [comment]
Ping @intel/llvm-gatekeepers, could this get merged?

**Pull request merged**
