### PR TITLE
[SYCL][JointMatrix] Remove xfail for joint matrix prefetch on CPU.

### PR DESCRIPTION
**Pull request by gpei-dev**

### CODE REVIEW

**Comment by gpei-dev** [comment]
Hi @dkhaldi, please help to review.

**Comment by dkhaldi** [comment]
@intel/llvm-gatekeepers, can you please help merge?

**Review by dkhaldi — APPROVED** [review]
LGTM

**Comment by dkhaldi** [comment]
@intel/llvm-gatekeepers, please help merge

**Pull request merged**
