### PR TITLE
[SYCL] Add MAJOR_VERSION to the name of the sycl library on Win

### PR DESCRIPTION
**Pull request by aelovikov-intel**

### CODE REVIEW

**Comment by aelovikov-intel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1237

**Review by mdtoguchi — COMMENTED** [review]
Overall, the changes are pretty straightforward and prevent any unexpected usage of an old library at runtime.  Just feels... odd.

**Review by romanovvlad — APPROVED** [review]
LGTM

**Review by mdtoguchi — APPROVED** [review]

**Comment by aelovikov-intel** [comment]
> [2013](https://github.com/intel/llvm/runs/8260664195?check_suite_focus=true#step:8:2036)  SYCL :: Plugin/level_zero_events_caching.cpp

Known issue - being addressed at https://github.com/intel/llvm-test-suite/pull/1138

**Comment by aelovikov-intel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1237

**Comment by aelovikov-intel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1237

**Review by mdtoguchi — APPROVED** [review]

**Review by romanovvlad — APPROVED** [review]

**Comment by aelovikov-intel** [comment]
The failure in ESMID Emu task looks unrelated and I believe I saw another notification (for another PR) saying it's being worked on already.

@intel/llvm-gatekeepers , please merge this together with https://github.com/intel/llvm-test-suite/pull/1237

**Pull request merged**
