### PR TITLE
[SYCL][ABI-Break] Drop `pi::die`

### PR DESCRIPTION
**Pull request by AlexeySachkov**
It is not used from SYCL headers, there is no reason for it to be exported and moreover it only has a single use since `pi::assertion` was removed.

This is patch is essentially a by-product of intel/llvm#14145 and it is done to simplify that change, i.e. PI plugins removal should not be ABI-breaking by itself, we just need to cleanup some of our exported symbols.

### CODE REVIEW

**Review by steffenlarsen — APPROVED** [review]

**Review by aelovikov-intel — COMMENTED** [review]
I don't know how we can be sure it isn't used on some code path that isn't instantiated in our tests.

**Comment by AlexeySachkov** [comment]
> I don't know how we can be sure it isn't used on some code path that isn't instantiated in our tests.

You mean someone uses it directly in their application? I did `grep` for every endpoint that I'm hiding to find if it is used and that's what I'm basing my conclusion that it is unused on

**Comment by aelovikov-intel** [comment]
> > I don't know how we can be sure it isn't used on some code path that isn't instantiated in our tests.
> 
> You mean someone uses it directly in their application? I did `grep` for every endpoint that I'm hiding to find if it is used and that's what I'm basing my conclusion that it is unused on

No, only internal (current and future) uses. In other words, I don't like that there is implicit dependency of not using this inside our header resulting in the symbol used in user's program.

**Comment by AlexeySachkov** [comment]
> > > I don't know how we can be sure it isn't used on some code path that isn't instantiated in our tests.
> > 
> > 
> > You mean someone uses it directly in their application? I did `grep` for every endpoint that I'm hiding to find if it is used and that's what I'm basing my conclusion that it is unused on
> 
> No, only internal (current and future) uses. In other words, I don't like that there is implicit dependency of not using this inside our header resulting in the symbol used in user's program.
> 
> To clarify - if the symbol is only used under `source/`, then declaration should happen under a header in that folder, not in public headers.

Thanks, I see, that makes sense. It is also used by plugins, but I suppose that I can define it in every plugin as well as a temporary measure until they are deleted

**Comment by AlexeySachkov** [comment]
> > To clarify - if the symbol is only used under `source/`, then declaration should happen under a header in that folder, not in public headers.
> 
> Thanks, I see, that makes sense. It is also used by plugins, but I suppose that I can define it in every plugin as well as a temporary measure until they are deleted

Plugins currently use their own definition of `die` which they bring from UR by including `pi2ur.hpp`. Therefore my plan is to completely remove the function. Its only use is to report an unsupported platform type when we convert it to string, which I believe we can handle simply by reporting a special string saying that the platform is unknown. SYCL error reporting mechanism is exceptions and if we need something else, we can re-introduce it

**Pull request merged**
