### PR TITLE
[SYCL] Enable LIT image.cpp

### PR DESCRIPTION
**Pull request by v-klochkov**
Signed-off-by: Vyacheslav N Klochkov <vyacheslav.n.klochkov@intel.com>

### CODE REVIEW

**Comment by v-klochkov** [comment]
The test on Windows will pass only after pre-checkin/CI will start using the most recent GPU driver version 100.7158. I already sent request to them to update it.

**Comment by v-klochkov** [comment]
I re-based the patch to pass CI testing (pull the fix for fails caused by unrecognized cl::sycl::half type).

**Comment by v-klochkov** [comment]
I simply re-based the patch to pull Artur's fix disabling 3 LIT tests on Windows that caused CI machine hangs.

**Comment by v-klochkov** [comment]
I don't understand, why image.cpp still fails. It seems like CI still uses GPU version 100.7000 ?

**Comment by vladimirlaz** [comment]
The test will fail will fail on windows because GPU RT has not been updated. Update is planned 2019/09/17.

**Pull request merged**
