### PR TITLE
[DeviceASAN] Enable e2e test "private_nullptr.cpp"

### PR DESCRIPTION
**Pull request by AllanZyne**

### CODE REVIEW

**Comment by AllanZyne** [comment]
@intel/llvm-gatekeepers, the failed test is unrelated to this PR, please merge. Thank you

**Review by yingcong-wu — APPROVED** [review]

**Review by zhaomaosu — APPROVED** [review]

**Comment by steffenlarsen** [comment]
Hi @AllanZyne! The failing test is not unrelated. It tracks all unspecified XFAILs we have, i.e. ones without XFAIL-TRACKER. Since you're removing such a case, you also need to remove the [corresponding test from the list](https://github.com/intel/llvm/blob/sycl/sycl/test/e2e_test_requirements/no-xfail-without-tracker.cpp#L59) (you will likely have the change the following line to `CHECK` instead of `CHECK-NEXT`) and decrement the [test-counter](https://github.com/intel/llvm/blob/sycl/sycl/test/e2e_test_requirements/no-xfail-without-tracker.cpp#L54).

**Comment by AllanZyne** [comment]
Thanks, fixed it. @steffenlarsen

**Review by steffenlarsen — APPROVED** [review]
Very nice! 👍

**Pull request merged**
