### PR TITLE
[NFC][SYCL] Initialize class member pointer to nullptr.

### PR DESCRIPTION
**Pull request by schittir**

### CODE REVIEW

**Comment by schittir** [comment]
@tahonermann - could you please take a look at this? Thank you!

**Comment by bader** [comment]
@schittir, this looks like something unrelated to SYCL and should go to directly to review.llvm.org. Am I right?

**Comment by schittir** [comment]
> @schittir, this looks like something unrelated to SYCL and should go to directly to review.llvm.org. Am I right?

Hi @bader https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Analysis/CallGraph.h doesn't contain ASTContext *Ctx member, therefore that change belongs with intel/llvm. 

However, it does contain https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Analysis/CallGraph.h#L52 CallGraphNode *Root, and I can move that change to llorg.

**Review by tahonermann — APPROVED** [review]
Looks good to me. Thanks for shuffling these changes through all the systems, Sindhu!

**Review by elizabethandrews — APPROVED** [review]

**Comment by schittir** [comment]
@bader @AaronBallman can this be merged? 
Thanks,
Sindhu

**Comment by schittir** [comment]
@intel/llvm-gatekeepers - could you please merge this?

**Review by smanna12 — APPROVED** [review]

**Comment by aelovikov-intel** [comment]
> @intel/llvm-gatekeepers - could you please merge this?

The testing is more than month-old!

**Comment by schittir** [comment]
> > @intel/llvm-gatekeepers - could you please merge this?
> 
> The testing is more than month-old! Please merge in `origin/sycl` into this PR's branch.

I accidentally did a git --rebase instead of a merge (habit from committing to llorg), so I had to force push to update this branch. Sorry about that.

**Pull request merged**
