### PR TITLE
[SYCL] Fix include loop and use-before-def

### PR DESCRIPTION
**Pull request by ldrumm**
There are two issues present here that aren't obviously visible:
  1. The `sycl::half_type` alias isn't defined in sycl/half_type.hpp; it actually comes from detail/generic_type_lists.hpp seemingly accidentally.
  2. detail/type_traits.hpp transitively includes sycl/half_type.hpp as it has templates that use sycl::half. However, the half implementation itself needs type_traits.hpp for computing alignment. Depending on the order of headers included, this causes an unfulfillable declaration-before-use issue in client code. In doing so ESIMD was found to be guilty of not including all the correct headers.

There are many such transitive header issues lurking which keep the headers tightly coupled and the final preprocess very large. Until they are solved in a more general way I've had to introduce some copy-paste for the `vector_alignment` helper to avoid including type_traits.hpp inside half_type.hpp.

This patch is a prerequisite of the future complex_half group algorithms work ending up in a working order

### CODE REVIEW

**Comment by ldrumm** [comment]
@intel/llvm-gatekeepers

**Review by steffenlarsen — APPROVED** [review]
Sorry for the delay! Just a small comment about the repeat code, but otherwise LGTM!

If reviewers are slow to react, please feel free to ping.

**Comment by steffenlarsen** [comment]
@intel/dpcpp-esimd-reviewers - Friendly ping.

**Review by sarnex — APPROVED** [review]
esimd.hpp lgtm

**Comment by ldrumm** [comment]
On Fri Mar 3, 2023 at 3:08 PM GMT, Steffen Larsen wrote:
> Would it make sense to move this to a new file, e.g.
> `vector_traits.hpp`, similar to what you did with memcpy? Hopefully that
> should avoid problems in case we ever need to change this.
Yeah. That seems sensible and more consistent. I'll update
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/intel/llvm/pull/8407#pullrequestreview-1324005115
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
Codeplay Software Ltd.
Company registered in England and Wales, number: 04567874.
Registered office: 2 New Bailey, 6 Stanley Street, Salford, United Kingdom, M35GS

**Comment by ldrumm** [comment]
Is it worth rerunning the HIP timeouts?

**Comment by steffenlarsen** [comment]
> Is it worth rerunning the HIP timeouts?

Not at the moment. They are considered unsupported for now will be disabled with https://github.com/intel/llvm-test-suite/pull/1639.

**Pull request merged**
