### PR TITLE
[SYCL][XPTI] Fix off-by-one error in USMAnalyzer

### PR DESCRIPTION
**Pull request by al42and**
When looking for the correct allocation, the upper bound check was inclusive (Ptr <= Alloc.first + Alloc.second.Length). If we have two allocations back-to-back, the pointer to the beginning of the second allocation would incorrectly be determined as belonging to the first allocation. This caused false-positives errors about out-of-bounds memory operations.

### CODE REVIEW

**Review by againull — APPROVED** [review]

**Comment by al42and** [comment]
The CI failure on Windows seem unrelated to the current change and are also seen in other PRs (e.g., https://github.com/intel/llvm/actions/runs/9503560228/job/26197279464). Something directory being locked for no reason:

```
Post job cleanup.
Cleaning D:\github\_work\llvm\llvm/*
rm: cannot remove 'D:\github\_work\llvm\llvm/build-e2e/Plugin': Device or resource busy
rm: cannot remove 'D:\github\_work\llvm\llvm/install/bin': Device or resource busy
node:child_process:935
    throw err;
    ^

Error: Command failed: rm -rf D:\github\_work\llvm\llvm/*
rm: cannot remove 'D:\github\_work\llvm\llvm/build-e2e/Plugin': Device or resource busy
rm: cannot remove 'D:\github\_work\llvm\llvm/install/bin': Device or resource busy
```

**Comment by bader** [comment]
> The CI failure on Windows seem unrelated to the current change and are also seen in other PRs (e.g., https://github.com/intel/llvm/actions/runs/9503560228/job/26197279464). Something directory being locked for no reason:
> 
> ```
> Post job cleanup.
> Cleaning D:\github\_work\llvm\llvm/*
> rm: cannot remove 'D:\github\_work\llvm\llvm/build-e2e/Plugin': Device or resource busy
> rm: cannot remove 'D:\github\_work\llvm\llvm/install/bin': Device or resource busy
> node:child_process:935
>     throw err;
>     ^
> 
> Error: Command failed: rm -rf D:\github\_work\llvm\llvm/*
> rm: cannot remove 'D:\github\_work\llvm\llvm/build-e2e/Plugin': Device or resource busy
> rm: cannot remove 'D:\github\_work\llvm\llvm/install/bin': Device or resource busy
> ```

@intel/dpcpp-devops-reviewers, this is the same machine as I mentioned in [this comment](https://github.com/intel/llvm/pull/14144#issuecomment-2166341270). Could you disable this machine until the problem is fixed, please?

**Comment by sarnex** [comment]
@bader I just restarted the machine and it should be fixed now.

**Comment by al42and** [comment]
@intel/llvm-gatekeepers, could you please re-trigger the CI now that the problematic machine is restarted?

**Comment by bader** [comment]
> @intel/llvm-gatekeepers, could you please re-trigger the CI now that the problematic machine is restarted?

@al42and, I suggest you merge tip of the SYCL branch to your branch. This will re-trigger CI testing with the latest state of the project.

**Pull request merged**
