### PR TITLE
[SYCL] Define interop type for images in Level-Zero and OpenCL backends

### PR DESCRIPTION
**Pull request by mikhail-nikolskiy**
Currently interop type defined for buffers only.
Tests: [llvm-test-suite#252](https://github.com/intel/llvm-test-suite/pull/252)

### CODE REVIEW

**Comment by romanovvlad** [comment]
LGTM, @alexbatashev  could you please take a look as well?

**Comment by alexbatashev** [comment]
I think we agreed with @smaslov-intel we want to retire `interop` struct in favor of `backend_traits`.

**Review by smaslov-intel — DISMISSED** [review]

**Comment by mikhail-nikolskiy** [comment]
Tests instability [fixed in test code](https://github.com/intel/llvm-test-suite/pull/252/commits/df07c9ebffd72c5de401fdd055ffebdf3f5591e8) by replacing '&' with '=' in interop_task lambda - copy accessor objects by value, not by reference. Otherwise accessor could be destroyed before interop_task starts.

**Comment by smaslov-intel** [comment]
> accessor could be destroyed before interop_task starts

The accessor should stay alive until it goes out of scope. I don't understand why this early destruction was possible.
If it is truly something that's going on then we should have it explained to the users in some form.

**Comment by alexbatashev** [comment]
> > accessor could be destroyed before interop_task starts
> 
> The accessor should stay alive until it goes out of scope. I don't understand why this early destruction was possible.
> If it is truly something that's going on then we should have it explained to the users in some form.

If I'm not mistaken, interop tasks run in a separate thread. Tagging @s-kanaev

**Comment by s-kanaev** [comment]
> If I'm not mistaken, interop tasks run in a separate thread.

There're two kinds of interop tasks:
 - the ones launched with `cl::handler::interop_task()`
 - host tasks with interop

The former are executed within the enqueueing thread.
The latter ones are executed in a distinct thread belonging to thread pool. See `queue_impl::initHostTaskAndEventCallbackThreadPool()`. Though the method is available in any queue, it's called only for default host queue.

**Comment by romanovvlad** [comment]
@mikhail-nikolskiy Could you please apply clang-format suggestion?

**Comment by smaslov-intel** [comment]
> The former are executed within the enqueueing thread.

So how could accessors be destroyed earlier that the `interop_task` is completed?
https://github.com/intel/llvm-test-suite/pull/252/commits/df07c9ebffd72c5de401fdd055ffebdf3f5591e8#diff-bf582222f4ea3305ae98fd3a169c8bdbb8ff7df2782592610154ced2d0edf6feR43

**Comment by s-kanaev** [comment]
> So how could accessors be destroyed earlier that the interop_task is completed?

We've got two lambdas here:
 - the one passed to `queue::submit`, lets call it command group handler lambda
 - the one passed to `handler::interop_task`, lets call it interop task lambda

Now, the accessor is created in command group handler lambda and referred to in interop task lambda. Though, upon call to `handler::interop_task` the interop lambda doesn't get to be executed. It's only stored. The enqueue process is started after command group handler lambda finishes, i.e. it returns and all its local objects got destroyed. Interop lambda is executed only whilst enqueue process.

**Comment by mikhail-nikolskiy** [comment]
> @mikhail-nikolskiy Could you please apply clang-format suggestion?
done

**Comment by smaslov-intel** [comment]
> Now, the accessor is created in command group handler lambda and referred to in interop task lambda. Though, upon call to `handler::interop_task` the interop lambda doesn't get to be executed. It's only stored. The enqueue process is started after command group handler lambda finishes, i.e. it returns and all its local objects got destroyed. Interop lambda is executed only whilst enqueue process.

Thanks for explaining this non-obvious behavior!
I think this may be a big source of user errors in future.
Is there a chance to give a compile-time error by building this knowledge into FE?

**Review by smaslov-intel — APPROVED** [review]

**Pull request merged**
