### PR TITLE
[ESIMD] Add basic operations code generation test for half type.

### PR DESCRIPTION
**Pull request by kbobrovs**
Signed-off-by: Konstantin S Bobrovsky <konstantin.s.bobrovsky@intel.com>

### CODE REVIEW

**Review by v-klochkov — APPROVED** [review]

**Comment by kbobrovs** [comment]
The pre-commit failure is unrelated to this change:
- Reduction/reduction_nd_ext_double.cpp

**Comment by bader** [comment]
@kbobrovs, this change breaks post-commit check - https://github.com/intel/llvm/runs/4708566128?check_suite_focus=true.
Please, fix as soon as possible.

**Comment by pvchupin** [comment]
Tagging @v-klochkov, as konst was out today.

**Comment by v-klochkov** [comment]
Sure, I uploaded the fix for the test: https://github.com/intel/llvm/pull/5278
The test passed when was build with default configuration, but failed with "configure --no-assertions".

**Pull request merged**
