### PR TITLE
[NFCI][SYCL] Remove some unnecessary string allocs during int-header …

### PR DESCRIPTION
**Pull request by erichkeane**
…emit

These two have resulted in some awkwardly written code in order to
provide/return std::strings, so replace them with streams, which creates
a more natural interface.  Additionally, this should reduce the amount
of std::string allocations, so we should go a little faster.

### CODE REVIEW

**Comment by erichkeane** [comment]
Huh... I correctly fixed the clang-format issue and the build bot seems to still be picking up the wrong commit.  I think we've seen this before.  @bader  is there a good person to report this to?  I tried restarting this as well, but it still got the format check wrong.

**Comment by bader** [comment]
> Huh... I correctly fixed the clang-format issue and the build bot seems to still be picking up the wrong commit. 

It's GitHub Actions CI check.

> I think we've seen this before. 

Interesting... I haven't seen this issue before.

> @bader is there a good person to report this to? I tried restarting this as well, but it still got the format check wrong.

This seems like a bug in the ["checkout" step](https://github.com/intel/llvm/blob/sycl/.github/workflows/clang-format.yml#L12). I added this check, so I'll take a look what is wrong.

@alexbatashev, do you have any idea, what might be the reason of this issue?

**Comment by erichkeane** [comment]
> 
> 
> > Huh... I correctly fixed the clang-format issue and the build bot seems to still be picking up the wrong commit.
> 
> It's GitHub Actions CI check.
> 
> > I think we've seen this before.
> 
> Interesting... I haven't seen this issue before.
> 
> > @bader is there a good person to report this to? I tried restarting this as well, but it still got the format check wrong.
> 
> This seems like a bug in the ["checkout" step](https://github.com/intel/llvm/blob/sycl/.github/workflows/clang-format.yml#L12). I added this check, so I'll take a look what is wrong.
> 
> @alexbatashev, do you have any idea, what might be the reason of this issue?

I think I saw this once on one of @zahiraam 's patches, but I think it was a different build bot?  Anyway, I'm glad we have a repro on a patch that doesn't matter much :)

**Comment by alexbatashev** [comment]
> > Huh... I correctly fixed the clang-format issue and the build bot seems to still be picking up the wrong commit.
> 
> It's GitHub Actions CI check.
> 
> > I think we've seen this before.
> 
> Interesting... I haven't seen this issue before.
> 
> > @bader is there a good person to report this to? I tried restarting this as well, but it still got the format check wrong.
> 
> This seems like a bug in the ["checkout" step](https://github.com/intel/llvm/blob/sycl/.github/workflows/clang-format.yml#L12). I added this check, so I'll take a look what is wrong.
> 
> @alexbatashev, do you have any idea, what might be the reason of this issue?

Actually, this looks like a GitHub bug. It should create a merge branch, that contains PR merged into primary branch. But for some reason this branch only contains the first commit with hash 5c84a2b9f0663a04343d8a89e04d02443e0e3822 and not the adcd159acc67ee6ada4e6cd39471101dd02b9d4b. @erichkeane have you tried restarting job?

**Comment by bader** [comment]
I think Erich mentioned above that he tried to re-run the job. I also tried, but it failed again.

**Comment by erichkeane** [comment]
Yeah, I've restarted it about a half dozen times.

**Comment by bader** [comment]
> Actually, this looks like a GitHub bug. It should create a merge branch, that contains PR merged into primary branch. But for some reason this branch only contains the first commit with hash [5c84a2b](https://github.com/intel/llvm/commit/5c84a2b9f0663a04343d8a89e04d02443e0e3822) and not the [adcd159](https://github.com/intel/llvm/commit/adcd159acc67ee6ada4e6cd39471101dd02b9d4b). 

This is a bit scary. Do you know if GitHub uses merge branch during "merge" action? I hope not.

@erichkeane, I introduced a merge conflict by merging previously approved patches. Could you resolve the merge conflict, please? I hope this also will help with clang-format check issue.

**Comment by zahiraam** [comment]
> > > Huh... I correctly fixed the clang-format issue and the build bot seems to still be picking up the wrong commit.
> > 
> > 
> > It's GitHub Actions CI check.
> > > I think we've seen this before.
> > 
> > 
> > Interesting... I haven't seen this issue before.
> > > @bader is there a good person to report this to? I tried restarting this as well, but it still got the format check wrong.
> > 
> > 
> > This seems like a bug in the ["checkout" step](https://github.com/intel/llvm/blob/sycl/.github/workflows/clang-format.yml#L12). I added this check, so I'll take a look what is wrong.
> > @alexbatashev, do you have any idea, what might be the reason of this issue?
> 
> I think I saw this once on one of @zahiraam 's patches, but I think it was a different build bot? Anyway, I'm glad we have a repro on a patch that doesn't matter much :)

Yes it was the sycl-win buildbot that I saw this behavior.

**Comment by alexbatashev** [comment]
> This is a bit scary. Do you know if GitHub uses merge branch during "merge" action? I hope not.

AFAIK, no, it performs a genuine merge.

**Comment by erichkeane** [comment]
The merge wasn't particularly clean, I ended up having to rework a bit of what @zahiraam did (I mistakenly started this patch thinking her patch was already in), and the web-tool isn't particularly great at doing the merge, so I apologize in advance if I have to fight the buildbots a little :)

**Pull request merged**
