### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW14)

### PR DESCRIPTION
**Pull request by vmaksimo**
LLVM: llvm/llvm-project@522712e2d241e
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@3b00f15

### CODE REVIEW

**Comment by vmaksimo** [comment]
Hi, @mdtoguchi! After afaefb67 change in LLORG we got the failing tests on Linux (74 tests on `check-sycl` target). The linker fails in finding `-lsycl`.
Some tests also have such a warning before the fail (for cuda target):
` Linking two modules of different target triples: 'lib/clang/15.0.0/../../clc/remangled-l64-signed_char.libspirv-nvptx64--nvidiacl.bc' is 'nvptx64-unknown-nvidiacl' whereas 'sycl/test/basic_tests/accessor/accessor_property_list_ct.cpp' is 'nvptx64-nvidia-cuda'`.
And for Windows runs only `Driver/sycl-offload-static-lib-2.cpp` clang test fails, but this one is most likely not related to the mentioned community change.
Could you please take a look at this issue?

**Comment by vladimirlaz** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/957

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Thu 31 Mar 2022 09:36:07 AM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Thu 31 Mar 2022 09:39:44 AM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
