### PR TITLE
[NFCI][SYCL] Refactor getBinaryImageFormat

### PR DESCRIPTION
**Pull request by aelovikov-intel**
A future PR will add support for magic numbers other than four bytes. Refactor the code to make those future changes easier to review.

### CODE REVIEW

**Review by bso-intel — APPROVED** [review]

**Review by steffenlarsen — APPROVED** [review]
Overall good, with a few nits in https://github.com/intel/llvm/pull/12587.

**Review by steffenlarsen — APPROVED** [review]
LGTM!

**Comment by aelovikov-intel** [comment]
Post commit failed on Arc GPU:
```
Failed Tests (1):
  SYCL :: Reduction/reduction_range_3d_rw.cpp
```
```
FAIL: SYCL :: Reduction/reduction_range_3d_rw.cpp (1551 of 1862)
******************** TEST 'SYCL :: Reduction/reduction_range_3d_rw.cpp' FAILED ********************
Exit Code: 1

Command Output (stdout):
--
# RUN: at line 1
/__w/llvm/llvm/toolchain/bin//clang++   -fsycl -fsycl-targets=spir64 /__w/llvm/llvm/llvm/sycl/test-e2e/Reduction/reduction_range_3d_rw.cpp -o /__w/llvm/llvm/build-e2e/Reduction/Output/reduction_range_3d_rw.cpp.tmp.out
# executed command: /__w/llvm/llvm/toolchain/bin//clang++ -fsycl -fsycl-targets=spir64 /__w/llvm/llvm/llvm/sycl/test-e2e/Reduction/reduction_range_3d_rw.cpp -o /__w/llvm/llvm/build-e2e/Reduction/Output/reduction_range_3d_rw.cpp.tmp.out
# note: command had no output on stdout or stderr
# RUN: at line 2
env ONEAPI_DEVICE_SELECTOR=level_zero:gpu  /__w/llvm/llvm/build-e2e/Reduction/Output/reduction_range_3d_rw.cpp.tmp.out
# executed command: env ONEAPI_DEVICE_SELECTOR=level_zero:gpu /__w/llvm/llvm/build-e2e/Reduction/Output/reduction_range_3d_rw.cpp.tmp.out
# .---command stdout------------
# | Device: Intel(R) Arc(TM) A750 Graphics, MaxWGSize: 1024, LocalMemSize: 65536, Driver: 1.3.27912
# | Start, T=i, BOp=St4plusIvE, Range={1, 1, 1}. PASSED
# | Start, T=i, BOp=St4plusIvE, Range={2, 2, 2}. PASSED
# | Start, T=i, BOp=St4plusIvE, Range={2, 3, 4}. PASSED
# | Start, T=l, BOp=St4plusIvE, Range={1, 1, 1025}. PASSED
# | Start, T=l, BOp=St4plusIvE, Range={1, 1025, 1}. PASSED
# | Start, T=l, BOp=St4plusIvE, Range={1025, 1, 1}. PASSED
# | Start, T=l, BOp=St4plusIvE, Range={2, 5, 2048}. PASSED
# | Start, T=l, BOp=St4plusIvE, Range={3, 3072, 2}. PASSED
# | Start, T=l, BOp=St4plusIvE, Range={3072, 8, 4}. PASSED
# | Start, T=i, BOp=St7bit_xorIvE, Range={2, 3072, 3}. PASSED
# | Start, T=i, BOp=St7bit_andIvE, Range={3072, 4, 3}. PASSED
# | Start, T=i, BOp=St6bit_orIvE, Range={2, 2, 3072}. PASSED
# | Start, T=m, BOp=St10multipliesIvE, Range={2, 3, 5}. PASSED
# | Start, T=m, BOp=St10multipliesIvE, Range={5, 2, 3}. PASSED
# | Start, T=i, BOp=N4sycl3_V17minimumIvEE, Range={1024, 8, 3}. PASSED
# | Start, T=i, BOp=N4sycl3_V17maximumIvEE, Range={3, 1024, 3}. PASSED
# | Start, T=f, BOp=St10multipliesIvE, Range={3, 3, 4}. PASSED
# | Start, T=9CustomVecIxE, BOp=13CustomVecPlusIxE, Range={2, 33, 1024}. PASSED
# | Start, T=9CustomVecIxE, BOp=13CustomVecPlusIxE, Range={2, 33, 1024}. PASSED
# | Start, T=i, BOp=19PlusWithoutIdentityIiE, Range={1, 1, 1}. PASSED
# | Start, T=i, BOp=19PlusWithoutIdentityIiE, Range={2, 2, 2}. PASSED
# | Start, T=i, BOp=19PlusWithoutIdentityIiE, Range={2, 3, 4}. PASSED
# | Start, T=l, BOp=19PlusWithoutIdentityIlE, Range={1, 1, 1025}. PASSED
# | Start, T=l, BOp=19PlusWithoutIdentityIlE, Range={1, 1025, 1}. PASSED
# | Start, T=l, BOp=19PlusWithoutIdentityIlE, Range={1025, 1, 1}. PASSED
# | Start, T=l, BOp=19PlusWithoutIdentityIlE, Range={2, 5, 2048}. PASSED
# | Start, T=l, BOp=19PlusWithoutIdentityIlE, Range={3, 3072, 2}. PASSED
# | Start, T=l, BOp=19PlusWithoutIdentityIlE, Range={3072, 8, 4}. FAILED
# | Start, T=i, BOp=25MultipliesWithoutIdentityIiE, Range={1, 1, 1}. PASSED
# | Start, T=i, BOp=25MultipliesWithoutIdentityIiE, Range={2, 2, 2}. PASSED
# | Start, T=i, BOp=25MultipliesWithoutIdentityIiE, Range={2, 3, 4}. PASSED
# | Start, T=l, BOp=25MultipliesWithoutIdentityIlE, Range={1, 1, 1025}. PASSED
# | Start, T=l, BOp=25MultipliesWithoutIdentityIlE, Range={1, 1025, 1}. PASSED
# | Start, T=l, BOp=25MultipliesWithoutIdentityIlE, Range={1025, 1, 1}. PASSED
# | Start, T=l, BOp=25MultipliesWithoutIdentityIlE, Range={2, 5, 2048}. PASSED
# | Start, T=l, BOp=25MultipliesWithoutIdentityIlE, Range={3, 3072, 2}. PASSED
# | Start, T=l, BOp=25MultipliesWithoutIdentityIlE, Range={3072, 8, 4}. PASSED
# `-----------------------------
# .---command stderr------------
# | Device: Intel(R) Arc(TM) A750 Graphics, MaxWGSize: 1024, LocalMemSize: 65536, Driver: 1.3.27912
# | Error, T=l, BOp=19PlusWithoutIdentityIlE, Range={3072, 8, 4}, Computed value=291941, Expected value=295013
# | 1 test-cases failed
# `-----------------------------
# error: command failed with exit status: 1
```

I believe I've seen it before and it's not specific to this PR.

**Comment by aelovikov-intel** [comment]
SYCL Nigthly failures.

OpenCL CPU (on AMD runner):
```
Timed Out Tests (1):
  SYCL :: GroupAlgorithm/root_group.cpp
```

OpenCL CPU (Intel Arc GPU runner):
```
Unexpectedly Passed Tests (1):
  SYCL :: KernelFusion/Reduction/reduction.cpp
```

OpenCL CPU (Intel GEN12 runner) failed due to infrastructure issues.

**Comment by aelovikov-intel** [comment]
Another run of SYCL Nightly (it was still latest commit over the weekend):
OpenCL CPU (AMD runner):
```
Timed Out Tests (2):
  SYCL :: Basic/accessor/accessor.cpp
  SYCL :: GroupAlgorithm/root_group.cpp
```

OpenCL CPU (Intel Arc GPU runner):
```
Timed Out Tests (1):
  SYCL :: Scheduler/SubBufferRemapping.cpp

********************
Unexpectedly Passed Tests (1):
  SYCL :: KernelFusion/Reduction/reduction.cpp
```

OpenCL CPU (Intel GEN12 runner) failed due to infrastructure issues.

**Comment by aelovikov-intel** [comment]
And the third SYCL Nightly run:

OpenCL CPU (AMD runner):
```
Timed Out Tests (1):
  SYCL :: GroupAlgorithm/root_group.cpp
```

OpenCL CPU (Intel Arc GPU runner):
```
Unexpectedly Passed Tests (1):
  SYCL :: KernelFusion/Reduction/reduction.cpp
```

**Pull request merged**
