### PR TITLE
[SYCL] Remove outdated & invalid device score boost

### PR DESCRIPTION
**Pull request by KseniyaTikhomirova**
Every device that satisfies filter options receives 1000 as starting score.
Device that doesn't satisfy filter settings is filtered out on get_devices step. So no need to do extra boost for devices which DeviceNum is equal to the one specified in filter.

### CODE REVIEW

**Comment by romanovvlad** [comment]
LGTM
@bso-intel   Could you please take a look?

**Review by s-kanaev — COMMENTED** [review]
Should there be any tests updated or added?

**Review by bso-intel — APPROVED** [review]
LGTM.
Yes, we don't need this legacy filtering code since we already filter devices in platform_impl::filterDeviceFilter. Thanks.

**Comment by KseniyaTikhomirova** [comment]
uploaded PR for test https://github.com/intel/llvm-test-suite/pull/775

**Comment by s-kanaev** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/786

**Comment by KseniyaTikhomirova** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/775

**Comment by KseniyaTikhomirova** [comment]
@vladimirlaz hi, this PR and the linked one passed checks with each one. Could you please review and merge them if no concerns?

**Comment by KseniyaTikhomirova** [comment]
Hi @vladimirlaz, this PR passed checks with the corresponding change in test suite. Could you please review and merge if no concerns? Thank you.

**Comment by vladimirlaz** [comment]
Will be merged later today.

**Review by vladimirlaz — APPROVED** [review]

**Pull request merged**
