### PR TITLE
[sycl-post-link] Fix a crash during spec-constant properties generation

### PR DESCRIPTION
**Pull request by psamolysov-intel**
The sycl-post-link tool crashed during processing an IR where a
specialization constant with a padding is present, for example a
specialization constant of such type:

struct alignas(32) coeff_str_aligned_t {
  std::array<float, 3> coeffs;
  size_t number;
};

In the IR, the constant looks like the following:

@_ZL8coeff_id = internal addrspace(1) constant %"class.cl::sycl::specialization_id" { %struct.coeff_str_aligned_t { %"class.std::array" zeroinitializer, i64 0, [8 x i8] undef } }, align 32

That '[8 x i8] undef' led to the crash.

This patch fixes the issue and adds the following optimization: if the
default value of a specialization constant or a part of such default value
is undefined, the value (or its part) is passed into an invocation of the
'__spirv_SpecConstantComposite' function as is.

Co-authored-by: Steffen Larsen <steffen.larsen@intel.com>
Signed-off-by: Pavel Samolysov <pavel.samolysov@intel.com>

### CODE REVIEW

**Comment by psamolysov-intel** [comment]
Good idea, @steffenlarsen I've extended the vector convolution demo test in llvm-test-suite to handle an aligned structure.

**Review by AlexeySachkov — DISMISSED** [review]

**Comment by psamolysov-intel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/830

**Comment by psamolysov-intel** [comment]
Some problems with the test infrastructure.

**Comment by psamolysov-intel** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/830

**Comment by psamolysov-intel** [comment]
I tried the solution locally with this test: https://github.com/intel/llvm-test-suite/pull/830/files#diff-ec64dcd370d47e70aa3c7dcb41f18fb8780a11422e6065b9866fce62e75f1973 and the application crushes in the runtime (at `program_manager.cpp`). It's the time to debug.

**Comment by psamolysov-intel** [comment]
I've pushed a new commit with changes in the spec. constant metadata generation, this works along with the changes from @steffenlarsen applied in commit 12d7c1f995c6d463070bcf220f6d046d6d92fd23 The idea is to skip undefined values during metadata IDs generation to let the padding processing handle such values as padding that they actually are.

**Comment by psamolysov-intel** [comment]
Some tests failed but they are unrelated to the changes. The `SYCL :: SpecConstants/vector-convolution-demo.cpp` test added in https://github.com/intel/llvm-test-suite/pull/830 passed.

**Comment by mlychkov** [comment]
> Some tests failed but they are unrelated to the changes. The `SYCL :: SpecConstants/vector-convolution-demo.cpp` test added in [intel/llvm-test-suite#830](https://github.com/intel/llvm-test-suite/pull/830) passed.

Could you please check if failed tests have issues or create new ones for them?

**Comment by psamolysov-intel** [comment]
@mlychkov I've created one and there already is one for another failure.

**Review by mlychkov — APPROVED** [review]

**Comment by psamolysov-intel** [comment]
I would like to get a review from @steffenlarsen before merging. @steffenlarsen Could you have a look, please?

**Review by steffenlarsen — APPROVED** [review]
LGTM! It's a little confusing that `ID` has an `ID` member, but not enough that I worry about it.

**Comment by psamolysov-intel** [comment]
I thought about it but didn't manage to make better naming.

**Review by AlexeySachkov — APPROVED** [review]

**Pull request merged**
