### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW45 2024)

### PR DESCRIPTION
**Pull request by iclsrc**
LLVM: llvm/llvm-project@7f2e937469a8cec3fe977bf41ad2dfb9b4ce648a
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@cf697333b60d200

### CODE REVIEW

**Comment by jsji** [comment]
This is ready for review.
- [ ] [[Clang] Recover missing changes from](https://github.com/intel/llvm/pull/16022/commits/5c562c968cfa089cc47346c6471a82b39479c69c) https://github.com/intel/llvm/commit/9c760ca8ecfd570212b47a5e980d38575b879029 
- [ ] [[clang] Sync with community to use UnqualPtrTy](https://github.com/intel/llvm/pull/16022/commits/9162b695cd9f1af64c6a9624c41b27a1994284a3) 
Sync to community code to fix test failures, clean up of opaque pointer leftovers. @intel/dpcpp-cfe-reviewers    
- [ ] [[SYCL][Test] Update attributes in tests after](https://github.com/intel/llvm/pull/16022/commits/28165194bda10c49bffe29387e2be92fb5874863) https://github.com/intel/llvm/commit/69a798a996e0cd9d521db38167cadf841d629d38 https://github.com/intel/llvm/commit/095d49da76be09143582e07a807c86d3b4334dec @intel/dpcpp-cfe-reviewers 
- [ ] [[SYCL] Use union to do bitcast after bif removal in](https://github.com/intel/llvm/pull/16022/commits/1457e00ab4fad9333860d1df26b16ed93e3ef523) https://github.com/intel/llvm/commit/8be6b108fbd35c6f50db488a0a5462eba6852cfd @intel/sycl-matrix-reviewers @intel/dpcpp-cfe-reviewers 
- [ ] [[ORC] skip reoptimization tests on windows] (https://github.com/intel/llvm/pull/16022/commits/2057848d2f3b7cec84bb6617f317256dd14f7357) Temporarily disable test. To be follow up in https://github.com/intel/llvm/issues/16036.

**Comment by hvdijk** [comment]
This update results in an incompatibility with the version of oneAPI Construction Kit that is used for NativeCPU, which is currently not tested in CI (`configure.py --native_cpu` *without* `-DNATIVECPU_USE_OCK=OFF`).

```
/home/harald/dpcppllvm/build/x86_64-linux/_deps/oneapi-ck-src/modules/compiler/multi_llvm/include/multi_llvm/loop_utils.h:29:16: error: ‘createSimpleTargetReduction’ is not a member of ‘llvm’; did you mean ‘createSimpleReduction’?
   29 |   return llvm::createSimpleTargetReduction(B, Src, RdxKind);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                createSimpleReduction
```

We have updated OCK already when we saw those changes in LLVM upstream, we can just bump to the current version. Can that be added to this PR, or would you prefer having that as a separate follow-up PR?

```diff
diff --git a/llvm/lib/SYCLNativeCPUUtils/CMakeLists.txt b/llvm/lib/SYCLNativeCPUUtils/CMakeLists.txt
index bdbbff1e96cf..4adb406e4e02 100644
--- a/llvm/lib/SYCLNativeCPUUtils/CMakeLists.txt
+++ b/llvm/lib/SYCLNativeCPUUtils/CMakeLists.txt
@@ -34,13 +34,15 @@ endif()
 if(NATIVECPU_USE_OCK)
   if(NATIVECPU_OCK_USE_FETCHCONTENT)
     set(OCK_GIT_INTERNAL_REPO "https://github.com/codeplaysoftware/oneapi-construction-kit.git")
-    # commit 0e913951b61b709ce5c5c136f7557dd88d6e200c
-    # Merge: 0cf91055 85624e50
-    # Author: Colin Davidson <colin.davidson@codeplay.com>
-    # Date:   Mon Jul 1 15:39:36 2024 +0100
-    #     Merge pull request #485 from coldav/colin/fix_memmove_bug_finegrained
-    #     Fix risc-v memmove creating memcpy instrinsic
-    set(OCK_GIT_INTERNAL_TAG 0e913951b61b709ce5c5c136f7557dd88d6e200c)
+    # commit 6ca1e931802624d50b71777101a0254841f6bb11
+    # Merge: 86f13d7f 91a39fe7
+    # Author: Harald van Dijk <harald.vandijk@codeplay.com>
+    # Date:   Tue Nov 12 09:23:33 2024 +0000
+    #
+    #     Merge pull request #584 from hvdijk/avoid-deprecated-getpointerto
+    #
+    #     [NFC] Avoid deprecated Type::getPointerTo.
+    set(OCK_GIT_INTERNAL_TAG 6ca1e931802624d50b71777101a0254841f6bb11)

     # Overwrite OCK_GIT_INTERNAL_REPO/OCK_GIT_INTERNAL_TAG if the corresponding options are set
     if(OCK_GIT_REPO)
```

**Comment by jsji** [comment]
> This update shows an incompatibility with the version of oneAPI Construction Kit that is used for NativeCPU, which is currently not tested in CI (`configure.py --native_cpu` _without_ `-DNATIVECPU_USE_OCK=OFF`). Edit: this incompatibility is because it is based on an older version of the `sycl` branch and possibly will not cause problems after merging.

Yes, the please test it by merging this branch to `sycl`.

**Comment by jsji** [comment]
> Github is acting up and not allowing me to approve/review changes. FE Changes LGTM.
> 
> However, the following PRs are not FE PRs and require review from other components. The IR changes are due to LLVM passes IIUC
> 
> [[SYCL][Test] Update attributes in tests after](https://github.com/intel/llvm/pull/16022/commits/28165194bda10c49bffe29387e2be92fb5874863) [69a798a](https://github.com/intel/llvm/commit/69a798a996e0cd9d521db38167cadf841d629d38) [095d49d](https://github.com/intel/llvm/commit/095d49da76be09143582e07a807c86d3b4334dec) @intel/dpcpp-cfe-reviewers [[SYCL] Use union to do bitcast after bif removal in](https://github.com/intel/llvm/pull/16022/commits/1457e00ab4fad9333860d1df26b16ed93e3ef523) [8be6b10](https://github.com/intel/llvm/commit/8be6b108fbd35c6f50db488a0a5462eba6852cfd) @intel/sycl-matrix-reviewers @intel/dpcpp-cfe-reviewers

Thanks @elizabethandrews !

@intel/dpcpp-tools-reviewers Can someone help to have a look at 

[[SYCL][Test] Update attributes in tests after](https://github.com/intel/llvm/pull/16022/commits/28165194bda10c49bffe29387e2be92fb5874863) https://github.com/intel/llvm/commit/69a798a996e0cd9d521db38167cadf841d629d38 https://github.com/intel/llvm/commit/095d49da76be09143582e07a807c86d3b4334dec @intel/dpcpp-tools-reviewers
 [[SYCL] Use union to do bitcast after bif removal in](https://github.com/intel/llvm/pull/16022/commits/1457e00ab4fad9333860d1df26b16ed93e3ef523) https://github.com/intel/llvm/commit/8be6b108fbd35c6f50db488a0a5462eba6852cfd @intel/sycl-matrix-reviewers @intel/dpcpp-tools-reviewers

**Comment by AlexeySachkov** [comment]
> [[SYCL][Test] Update attributes in tests after](https://github.com/intel/llvm/pull/16022/commits/28165194bda10c49bffe29387e2be92fb5874863) https://github.com/intel/llvm/commit/69a798a996e0cd9d521db38167cadf841d629d38 https://github.com/intel/llvm/commit/095d49da76be09143582e07a807c86d3b4334dec @intel/dpcpp-tools-reviewers

I'm not a code owner of those files, but those changes LGTM.

> [[SYCL] Use union to do bitcast after bif removal in](https://github.com/intel/llvm/pull/16022/commits/1457e00ab4fad9333860d1df26b16ed93e3ef523) https://github.com/intel/llvm/commit/8be6b108fbd35c6f50db488a0a5462eba6852cfd @intel/sycl-matrix-reviewers @intel/dpcpp-tools-reviewers

That I would defer to @intel/sycl-matrix-reviewers, I'm not familiar enough with the topic. Strictly speaking, bitcast through union is UB. Either `bit_cast` or `memcpy` should be used, but I will leave it up to actual code owners to decide

**Comment by jsji** [comment]
> > [[SYCL][Test] Update attributes in tests after](https://github.com/intel/llvm/pull/16022/commits/28165194bda10c49bffe29387e2be92fb5874863) [69a798a](https://github.com/intel/llvm/commit/69a798a996e0cd9d521db38167cadf841d629d38) [095d49d](https://github.com/intel/llvm/commit/095d49da76be09143582e07a807c86d3b4334dec) @intel/dpcpp-tools-reviewers
> 
> I'm not a code owner of those files, but those changes LGTM.
> 
> > [[SYCL] Use union to do bitcast after bif removal in](https://github.com/intel/llvm/pull/16022/commits/1457e00ab4fad9333860d1df26b16ed93e3ef523) [8be6b10](https://github.com/intel/llvm/commit/8be6b108fbd35c6f50db488a0a5462eba6852cfd) @intel/sycl-matrix-reviewers @intel/dpcpp-tools-reviewers
> 
> That I would defer to @intel/sycl-matrix-reviewers, I'm not familiar enough with the topic. Strictly speaking, bitcast through union is UB. Either `bit_cast` or `memcpy` should be used, but I will leave it up to actual code owners to decide

@intel/sycl-matrix-reviewers Can you comment on [[SYCL] Use union to do bitcast after bif removal in](https://github.com/intel/llvm/pull/16022/commits/1457e00ab4fad9333860d1df26b16ed93e3ef523) https://github.com/intel/llvm/commit/8be6b108fbd35c6f50db488a0a5462eba6852cfd

**Review by dkhaldi — APPROVED** [review]
float to tf32 change LGTM

**Comment by jsji** [comment]
@intel/llvm-gatekeepers This is ready for merge. Can someone help to issue a "/merge"? Thanks

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Wed 13 Nov 2024 02:45:28 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Wed 13 Nov 2024 02:50:16 PM UTC --- Merge failed with error: Please check whether the PR is mergeable

**Comment by sarnex** [comment]
@jsji Uuuh, never seen that before. Does that mean we need to merge again?

**Comment by jsji** [comment]
> @jsji Uuuh, never seen that before. Does that mean we need to merge again?

Let me check the mergeable state locally first.

**Comment by jsji** [comment]
> > @jsji Uuuh, never seen that before. Does that mean we need to merge again?
> 
> Let me check the mergeable state locally first.

It works for me locally. Yes, let us try another `/merge` again? @sarnex

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Wed 13 Nov 2024 02:57:03 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Wed 13 Nov 2024 03:01:59 PM UTC --- Merge failed with error: Please check whether the PR is mergeable

**Comment by jsji** [comment]
> Wed 13 Nov 2024 03:01:59 PM UTC --- Merge failed with error: Please check whether the PR is mergeable

@DoyleLi Can you help to check what is going on with the bot? The PR is certainly mergeable here.

**Pull request merged**
