### PR TITLE
[CI] Enable running tests with dev igc driver w label

### PR DESCRIPTION
**Pull request by jsji**
Developers can choose the docker image by label.

There are a few failures when using igc-dev build, we will need to investigate and fix them first before turning on it by default for joint matrix, but this can be merged first so that we can test using ci + label when needed.

Ref: #11552

### CODE REVIEW

**Comment by aelovikov-intel** [comment]
Please change manual dispatch in https://github.com/intel/llvm/blob/sycl/.github/workflows/sycl-linux-run-tests.yml instead. That's what we use for experiments.

**Comment by jsji** [comment]
> Please change manual dispatch in https://github.com/intel/llvm/blob/sycl/.github/workflows/sycl-linux-run-tests.yml instead. That's what we use for experiments.

Yes, that will be done in another PR -- to enable doing `install_driver` test with dev igc when there are driver update.

This PR is to enable running tests for any sycl changes using installed docker image.

**Comment by aelovikov-intel** [comment]
> This PR is to enable running tests for any sycl changes using installed docker image.

I don't think we should be allowing multiple versions of pre-commit.

**Comment by jsji** [comment]
> Please change manual dispatch in https://github.com/intel/llvm/blob/sycl/.github/workflows/sycl-linux-run-tests.yml instead. That's what we use for experiments.

oh, do you mean adding more image options in  
https://github.com/intel/llvm/blob/a14d0b548e96014c643b00927be128193781769c/.github/workflows/sycl-linux-run-tests.yml#L90

**Comment by jsji** [comment]
> I don't think we should be allowing multiple versions of pre-commit.

Why not? HW resource limitation again?

**Comment by aelovikov-intel** [comment]
> do you mean adding more image options in

Yes

> Why not? HW resource limitation again?

Because if one does *non-default* pre-commit, gets green results, and gatekeepers merge based on that, then it's not verified that the *default* pre-commit won't get broken by all other people.

**Comment by jsji** [comment]
> 
> Because if one does _non-default_ pre-commit, gets green results, and gatekeepers merge based on that, then it's not verified that the _default_ pre-commit won't get broken by all other people.

This is true, I will fix it to ensure the workflow won't be green if non default are run.

**Comment by jsji** [comment]
Close this first for now per offline discussion with @aelovikov-intel. Use https://github.com/intel/llvm/pull/13380 instead.

**Pull request closed without merging**
