### PR TITLE
[Driver][SYCL] Make /MD the default for -fsycl

### PR DESCRIPTION
**Pull request by mdtoguchi**
When using -fsycl on Windows, make /MD the default behavior.  Any usage
of /MT will not be allowed and the driver will error upon usage.

### CODE REVIEW

**Review by elizabethandrews — APPROVED** [review]
LGTM

**Review by v-klochkov — DISMISSED** [review]
Looks good to me. Thank you.
One test for clang driver failed, probably the checks need to be updated there.

**Comment by v-klochkov** [comment]
Just one minor comment: shouldn't this line be deleted? https://github.com/intel/llvm/blob/sycl/clang/lib/Driver/ToolChains/MSVC.cpp#L379

**Comment by mdtoguchi** [comment]
> Just one minor comment: shouldn't this line be deleted? https://github.com/intel/llvm/blob/sycl/clang/lib/Driver/ToolChains/MSVC.cpp#L379

Yes, it can be deleted, but there is no harm in it being there.  I'll update.

**Comment by mdtoguchi** [comment]
Test failure is not due to my change.  The recent fix for default device libs for SYCL was probably tested and checked in before my change to add this test.  I will update the test to match current expectations.

**Review by v-klochkov — APPROVED** [review]

**Comment by mdtoguchi** [comment]
rebased to address conflicts.

**Review by elizabethandrews — APPROVED** [review]

**Review by v-klochkov — APPROVED** [review]

**Review by AGindinson — APPROVED** [review]
The patch LGTM. For the bigger picture, what nasty scenarios does forbidding `MT` rule out?

**Comment by v-klochkov** [comment]
> The patch LGTM. For the bigger picture, what nasty scenarios does forbidding `MT` rule out?

This is to avoid situations like here: https://docs.microsoft.com/en-us/cpp/c-runtime-library/potential-errors-passing-crt-objects-across-dll-boundaries?view=vs-2019 

I also wrote some more details in the commit message here: https://github.com/intel/llvm/pull/2480

**Pull request merged**
