### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW37)

### PR DESCRIPTION
**Pull request by sys-ce-bb**
LLVM: llvm/llvm-project@a866ce7
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@1c154ff

### CODE REVIEW

**Comment by jsji** [comment]
This is ready for review, 3 fixes:

* [Fix NVPTX code due to inlineasm enum class refactor in](https://github.com/intel/llvm/pull/11185/commits/73e2ef56978fd34d10c78dbe44fc1b51816e08c9) https://github.com/intel/llvm/commit/2ca4d136124d151216aac77a0403dcb5c5835bcd @intel/dpcpp-tools-reviewers 
* [Fix FPAccurary bug exposed by new builtin exp10](https://github.com/intel/llvm/pull/11185/commits/63da2bc4acc30ceb5e2749270796709a152ae2ca) @intel/dpcpp-cfe-reviewers 
* [Fix conflict resolution for vtable info to be [0 x ptr] in](https://github.com/intel/llvm/pull/11185/commits/b2609f1d1949fe62ce1e39788c081661827e0d23) https://github.com/intel/llvm/commit/8a2d68f6be5058f88588c31928ff40d8eb16c20a @intel/dpcpp-cfe-reviewers FYI. @jyu2-git This is another vtable related incoming change.

**Comment by jsji** [comment]
@aelovikov-intel Looks like there are some workflow files coming from community, eg: `Check Python Formatting / python_formatting (pull_request)` , `PR Receive Label / pr-subscriber (pull_request) ` Do we want to remove those?

**Comment by aelovikov-intel** [comment]
> @aelovikov-intel Looks like there are some workflow files coming from community, eg: `Check Python Formatting / python_formatting (pull_request)` , `PR Receive Label / pr-subscriber (pull_request) ` Do we want to remove those?

It seems the upstream is still actively tweaking their CI, I'd rather let it settle first.

**Comment by jsji** [comment]
> It seems the upstream is still actively tweaking their CI, I'd rather let it settle first.

OK. Thanks.

**Comment by bader** [comment]
I quickly skimmed through these patches:

> * [Fix NVPTX code due to inlineasm enum class refactor in](https://github.com/intel/llvm/pull/11185/commits/73e2ef56978fd34d10c78dbe44fc1b51816e08c9) [2ca4d13](https://github.com/intel/llvm/commit/2ca4d136124d151216aac77a0403dcb5c5835bcd) @intel/dpcpp-tools-reviewers

Tagging @npmiller as this is NVPTX specific patch. Should this fix be done in upstream? It doesn't seem to be specific to SYCL, so I hope we don't have NVPTX customizations in the sycl branch. AFAIK, Codeplay team makes NVPTX back-end fixes in llorg directly.

> * [Fix FPAccurary bug exposed by new builtin exp10](https://github.com/intel/llvm/pull/11185/commits/63da2bc4acc30ceb5e2749270796709a152ae2ca) @intel/dpcpp-cfe-reviewers

This also doesn't seem like a change directly related to SYCL, so we should expect it to be done in upstream too. Am I right?
@andykaylor, is this related to https://github.com/intel/llvm/pull/8134?

> * [Fix conflict resolution for vtable info to be [0 x ptr] in](https://github.com/intel/llvm/pull/11185/commits/b2609f1d1949fe62ce1e39788c081661827e0d23) [8a2d68f](https://github.com/intel/llvm/commit/8a2d68f6be5058f88588c31928ff40d8eb16c20a) @intel/dpcpp-cfe-reviewers FYI. @jyu2-git This is another vtable related incoming change.

This looks reasonable.

**Comment by jsji** [comment]
> Tagging @npmiller as this is NVPTX specific patch. Should this fix be done in upstream? It doesn't seem to be specific to SYCL, so I hope we don't have NVPTX customizations in the sycl branch. AFAIK, Codeplay team makes NVPTX back-end fixes in llorg directly.

Right, this has been done in upstream too, in 86735a4353aee.  I fixed it before upstream fix it. We merged 86735a4353aee too, no conflict, exact same change, so no review needed anymore. Thanks.

> This also doesn't seem like a change directly related to SYCL, so we should expect it to be done in upstream too. Am I right? @andykaylor, is this related to #8134?

This is related to https://github.com/intel/llvm/pull/8280. The feature mentioned it is for `SYCL`.

**Review by zahiraam — APPROVED** [review]
Changes made in CGBuiltin.cpp for the exp2 builtin look god to me.

**Comment by jsji** [comment]
@bader Ready to merge?

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Fri 15 Sep 2023 08:04:04 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Fri 15 Sep 2023 08:08:06 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
