### PR TITLE
[SPIR-V] Reland SPV_KHR_untyped_pointers commits

### PR DESCRIPTION
**Pull request by vmaksimo**
They were reverted in pulldown PR #15464 because of the regressions.
Don't use this extension in the SYCL tests as the extension is not fully implemented yet.

Commits:
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/7dacb7cdedc9c01
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/484e4070adb0a95

### CODE REVIEW

**Comment by vmaksimo** [comment]
CI failures look unrelated to the change

**Review by jsji — APPROVED** [review]
LGTM. Thanks.

**Comment by vmaksimo** [comment]
Rerun CI

**Review by bso-intel — APPROVED** [review]

**Comment by vmaksimo** [comment]
@intel/llvm-gatekeepers could you please merge? Thanks!

**Comment by martygrant** [comment]
@vmaksimo this still needs an approval from @intel/dpcpp-spirv-reviewers

**Comment by vmaksimo** [comment]
> this still needs an approval from @intel/dpcpp-spirv-reviewers

@martygrant it was approved by @asudarsa on behalf of the spirv reviewers group

**Review by VyacheslavLevytskyy — APPROVED** [review]

**Review by AlexeySachkov — APPROVED** [review]

**Pull request merged**
