### PR TITLE
[SYCL] Update bfloat16.cpp test to pass in no-assert mode

### PR DESCRIPTION
**Pull request by pvchupin**
Test was modified at https://github.com/intel/llvm/pull/6524

Change fixes post-commit issue in no-asserts mode

### CODE REVIEW

**Comment by pvchupin** [comment]
Actually that doesn't work. It looks like asserts are not supported in sycl. Need some other solution.

**Review by steffenlarsen — APPROVED** [review]

**Comment by pvchupin** [comment]
@steffenlarsen, do you have any idea why these appeared on HIP? I've seen it in a few other PRs as well but cannot easily connect to any recent change.

```
Unresolved Tests (5):
  SYCL :: Assert/assert_in_kernels.cpp
  SYCL :: Assert/assert_in_multiple_tus.cpp
  SYCL :: Assert/assert_in_multiple_tus_one_ndebug.cpp
  SYCL :: Assert/assert_in_one_kernel.cpp
  SYCL :: Assert/assert_in_simultaneously_multiple_tus_one_ndebug.cpp
```

**Comment by steffenlarsen** [comment]
> @steffenlarsen, do you have any idea why these appeared on HIP? I've seen it in a few other PRs as well but cannot easily connect to any recent change.
> 
> ```
> Unresolved Tests (5):
>   SYCL :: Assert/assert_in_kernels.cpp
>   SYCL :: Assert/assert_in_multiple_tus.cpp
>   SYCL :: Assert/assert_in_multiple_tus_one_ndebug.cpp
>   SYCL :: Assert/assert_in_one_kernel.cpp
>   SYCL :: Assert/assert_in_simultaneously_multiple_tus_one_ndebug.cpp
> ```

It looks like LIT is having trouble reading some exit code for one of the RUN lines. It is curious that it only happens for HIP, but the failure itself is not very informative.

**Review by rdeodhar — COMMENTED** [review]
Changes look good for now.

**Pull request merged**
