### PR TITLE
[Buildbot] Add retry function on fetching resource

### PR DESCRIPTION
**Pull request by yinyangsx**
Currently our network is unstable, this PR is for adding retry function on fetching resource on dependency.py script.

Signed-off-by: yinyangsx <yin.yang@intel.com>

### CODE REVIEW

**Comment by bader** [comment]
> Currently our network is unstable, this PR is for adding retry function on fetching resource on dependency.py script.

I think the good solution is to fix "our network", rather than add retry function.
+@pvchupin to decide if we want to have this workaround for "the network issues".

**Comment by yinyangsx** [comment]
> > Currently our network is unstable, this PR is for adding retry function on fetching resource on dependency.py script.
> 
> I think the good solution is to fix "our network", rather than add retry function.
> +@pvchupin to decide if we want to have this workaround for "the network issues".

I think so, but sometimes IT need time to fix the network issues. Before they fix the issue, our builds maybe fail due to network issues.
For the current network issue, tools team reported to IT two days ago, but now it's not be fixed yet.

**Comment by bader** [comment]
> > > Currently our network is unstable, this PR is for adding retry function on fetching resource on dependency.py script.
> > 
> > 
> > I think the good solution is to fix "our network", rather than add retry function.
> > +@pvchupin to decide if we want to have this workaround for "the network issues".
> 
> I think so, but sometimes IT need time to fix the network issues. Before they fix the issue, our builds maybe fail due to network issues.
> For the current network issue, tools team reported to IT two days ago, but now it's not be fixed yet.

The problem with retry script is that it hides such issues and this might not be detected, but we will load the system with meaningless work. Can we revert this patch as soon as network issue is fixed?

**Comment by yinyangsx** [comment]
> The problem with retry script is that it hides such issues and this might not be detected, but we will load the system with meaningless work.

I just added retry function for "git clone/fetch/pull" commands, I think no issues will be hided, right?

>Can we revert this patch as soon as network issue is fixed?

Yes, of course we can.

And we have another way, we can add retry function on CI side ( I mean changing scripts in llvm_ci repo), but it need to retry whole script.

**Comment by bader** [comment]
> > The problem with retry script is that it hides such issues and this might not be detected, but we will load the system with meaningless work.
> 
> I just added retry function for "git clone/fetch/pull" commands, I think no issues will be hided, right?

So your change hides sporadic fails of `git clone/fetch/pull` commands, which might signal about issues in network configuration or some other places.

> 
> > Can we revert this patch as soon as network issue is fixed?
> 
> Yes, of course we can.
> 
> And we have another way, we can add retry function on CI side ( I mean changing scripts in llvm_ci repo), but it need to retry whole script.

The problem with "retry" approach is that each failure is a signal that something is wrong, if retry is successful noone will ever know about these problems and they will pile up until system will be completely broken. Retry can be a good back-up solution if each time re-try is triggered it's reported and someone investigates why workflow didn't work as expected from the first run.
Does your suggestion imply configuring such process?

**Comment by pvchupin** [comment]
I agree with @bader, it worked reliably well until recently, so it looks like degradation we need to keep pushing for resolution. We can restart manually if needed until issue is resolved. Thanks @yinyangsx for follow up on this. We can reserve this restart functionality if it becomes really bad.

**Comment by yinyangsx** [comment]
Ok, let me close the PR. I will work with the IT team to solve the network issues as soon as possible.

**Pull request closed without merging**
