### PR TITLE
[SYCL][ASAN] apply only-needed when link asan libdevice

### PR DESCRIPTION
**Pull request by jinge90**
This patch removes some unused code in sanitizer libdevice and also appied 'only-needed' option when linking libsycl-santizer libdevice.

### CODE REVIEW

**Review by zhaomaosu — APPROVED** [review]
lgtm

**Comment by jinge90** [comment]
Hi, @intel/llvm-reviewers-runtime and @intel/dpcpp-clang-driver-reviewers 
Could you take a look at this pr?
Thanks very much.

**Review by AllanZyne — APPROVED** [review]
LGTM

**Review by mdtoguchi — APPROVED** [review]

**Comment by jinge90** [comment]
Hi, @steffenlarsen 
Could you help review this PR?
Thanks very much.

**Review by steffenlarsen — APPROVED** [review]
Apologies, @jinge90! LGTM. 👍

**Comment by jinge90** [comment]
Hi, @tfzhu 
Could you check whether the failure in pre-ci is a infrastructure issue?
Thanks very much.

**Comment by tfzhu** [comment]
> Hi, @tfzhu Could you check whether the failure in pre-ci is a infrastructure issue? Thanks very much.

passed on re-run. Seems a runner in bad state. Rebooted

**Comment by jinge90** [comment]
Hi, @intel/llvm-gatekeepers 
Could you help merge this PR?
Thanks very much.

**Pull request merged**
