### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW45)

### PR DESCRIPTION
**Pull request by sys-ce-bb**
LLVM: llvm/llvm-project@e3c120a585d2740bd1a4de23112fccd82013adbc
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@74b2540

### CODE REVIEW

**Comment by jsji** [comment]
This is ready for review.
- [ ] [[NFC] Fix CHECKs FortranArray.ll](https://github.com/intel/llvm/pull/11838/commits/9cdd658e0d5273141fa39fdacce77f6bcdae9293) # 2211 Cherry-pick of testcase fix from KhronosGroup. No review needed.
- [ ] [[NFC][TableGen] Update CHECK lines in test typeof-errors.td](https://github.com/intel/llvm/pull/11838/commits/1a5c0fff64800bfcd364d9e2bcf1ef7619774956) Cherry-pick of changes from main branch to fix test failures in TableGen. No review needed.
- [ ] [Fix bad build failure fix for getInt8PtrTy](https://github.com/intel/llvm/pull/11838/commits/13be85bee0b2d2eeec516b2493ccac0b1fb18fda) Fix a bad build failure fix done, which leads to SPIRV test failures. The code is just recovered. @intel/dpcpp-spirv-reviewers 
- [ ] [Revert "[AMDGPU] PromoteAlloca: Handle load/store subvectors using no…](https://github.com/intel/llvm/pull/11838/commits/e80f9e8fab1fc5874378219b6936d72e813ebab5) Temporary revert to fix 8 AMDGPU math builtin e2e test failures.  [AMDGPU] math E2E tests failed with 5db63d29fdc1fbf301c3d010d6e00e004d82fcdc #11857 opened to track the investigation and reland. 
- [ ] [Revert "[CodeGen] Implement post-opt linking option for builtin bitoc…](https://github.com/intel/llvm/pull/11838/commits/6607425a7556fa2963490deca2fbe5b8af50bc38) Temporary  revert to fix 3 timeout in AMDGPU e2e test in https://github.com/intel/llvm/actions/runs/6828866219/job/18575037948 . The timeout also observed in our internal build for libclc, it is massive failures, so prefer to revert it instead of xfail tests here during investigation. We have internal issue ( # 53477) opened to track the investgiation.

**Comment by jsji** [comment]
@bader @intel/dpcpp-cfe-reviewers  Can we get this review and merged? Thanks!

**Comment by premanandrao** [comment]
> @bader @intel/dpcpp-cfe-reviewers Can we get this review and merged? Thanks!

@jsji, for pulldowns, unless it is something very specific, it is hard for me to review all the changes.   What CFE changes are you concerned about?

**Comment by jsji** [comment]
> > @bader @intel/dpcpp-cfe-reviewers Can we get this review and merged? Thanks!
> 
> @jsji, for pulldowns, unless it is something very specific, it is hard for me to review all the changes. What CFE changes are you concerned about?

@premanandrao  Thanks! Yes, you don't need to review ALL the commits. I have listed the only one need your input in https://github.com/intel/llvm/pull/11838#issuecomment-1806616297 .

[Revert "[CodeGen] Implement post-opt linking option for builtin bitoc…](https://github.com/intel/llvm/pull/11838/commits/6607425a7556fa2963490deca2fbe5b8af50bc38) Temporary revert to fix 3 timeout in AMDGPU e2e test in https://github.com/intel/llvm/actions/runs/6828866219/job/18575037948 . The timeout also observed in our internal build for libclc, it is massive failures, so prefer to revert it instead of xfail tests here during investigation. We have internal issue ( # 53477) opened to track the investigation. https://github.com/orgs/intel/teams/dpcpp-cfe-reviewers

**Comment by premanandrao** [comment]
> > > @bader @intel/dpcpp-cfe-reviewers Can we get this review and merged? Thanks!
> > 
> > 
> > @jsji, for pulldowns, unless it is something very specific, it is hard for me to review all the changes. What CFE changes are you concerned about?
> 
> @premanandrao Thanks! Yes, you don't need to review ALL the commits. I have listed the only one need your input in [#11838 (comment)](https://github.com/intel/llvm/pull/11838#issuecomment-1806616297) .
> 
> [Revert "[CodeGen] Implement post-opt linking option for builtin bitoc…](https://github.com/intel/llvm/pull/11838/commits/6607425a7556fa2963490deca2fbe5b8af50bc38) Temporary revert to fix 3 timeout in AMDGPU e2e test in https://github.com/intel/llvm/actions/runs/6828866219/job/18575037948 . The timeout also observed in our internal build for libclc, it is massive failures, so prefer to revert it instead of xfail tests here during investigation. We have internal issue ( # 53477) opened to track the investigation. https://github.com/orgs/intel/teams/dpcpp-cfe-reviewers

Thanks for the details.  I am okay with this then.

**Review by premanandrao — APPROVED** [review]

**Comment by jsji** [comment]
@bader @intel/llvm-gatekeepers  I think this is ready to merge. Thanks.

**Comment by bader** [comment]
> * [Fix bad build failure fix for getInt8PtrTy](https://github.com/intel/llvm/pull/11838/commits/13be85bee0b2d2eeec516b2493ccac0b1fb18fda) Fix a bad build failure fix done, which leads to SPIRV test failures. The code is just recovered. @intel/dpcpp-spirv-reviewers

@jsji, do we have "okay" from the @intel/dpcpp-spirv-reviewers team?

**Review by asudarsa — APPROVED** [review]
LGTM from SPIR-V Gen side of things.

Thanks

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Tue 14 Nov 2023 11:09:07 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Tue 14 Nov 2023 11:14:32 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
