### PR TITLE
[XPTI] Added new class xpti::framework::tracepoint_t

### PR DESCRIPTION
**Pull request by tovinkere**
+ Supports the creation of universal IDs and posting
  them to TLS storage. Public entry points will need
  to use the new approach to propagate Universal IDs
  through multiple layers of the SW Stack.
+ Added tests to ensure the correctness of new APIs
  to support this feature and the functionality of
  the tracepoint object.
+ New methods added to the spec:
  - xptiRegisterPayload
  - xptiQueryPayloadByUID

Signed-off-by: Vasanth Tovinkere <vasanth.tovinkere@intel.com>

### CODE REVIEW

**Review by alexbatashev — DISMISSED** [review]
Thanks!

**Review by alexbatashev — APPROVED** [review]

**Comment by alexbatashev** [comment]
Jenkins job failure is not related to this patch. @bader @romanovvlad could you please take a look and help merging?

**Comment by romanovvlad** [comment]
Reduction/reduction_nd_s1_rw.cpp is a known issue. Merging.
@v-klochkov  FYI.

**Comment by v-klochkov** [comment]
> Reduction/reduction_nd_s1_rw.cpp is a known issue. Merging.
> @v-klochkov FYI.

Yes, that is a known issue. The test passes all test cases and SegFaults at exit from 'int main'. It is level_zero:gpu specific and the issue is being investigated by GPU RT team.
stack during the SegFault:
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x000014a9cc106b36 in ?? () from < path >/libze_intel_gpu.so.1
#2  0x000014a9cc0fc9b2 in ?? () from < path >/libze_intel_gpu.so.1
#3  0x000014a9cc130f98 in ?? () from < path >/libze_intel_gpu.so.1
#4  0x000014a9cf4cd609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x000014a9cf61d293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Pull request merged**
