### PR TITLE
[NFC][SYCL] Re-format python files using "black"

### PR DESCRIPTION
**Pull request by aelovikov-intel**
https://github.com/intel/llvm/pull/12184 enable format check for python files but we never properly formatted them. Do it now.

### CODE REVIEW

**Review by bader — APPROVED** [review]
sycl/doc/conf.py changes look good to me.

Please, fix pre-commit checks.

**Review by againull — APPROVED** [review]

**Review by steffenlarsen — APPROVED** [review]
I am personally a little on the fence regarding Python formatters, but consistency is nice. Should we have a comment at the top of each of these files encouraging the use of the formatter?

**Comment by aelovikov-intel** [comment]
> I am personally a little on the fence regarding Python formatters, but consistency is nice. Should we have a comment at the top of each of these files encouraging the use of the formatter?

Not necessary - pre-commit formatting check would just fail if it's not properly formatted.

**Comment by steffenlarsen** [comment]
> Not necessary - pre-commit formatting check would just fail if it's not properly formatted.

Ah, so it is part of the new formatting check? Great, then disregard the concern! 😄

**Comment by aelovikov-intel** [comment]
@unified-runtime-reviewers, ping.

**Comment by aelovikov-intel** [comment]
@intel/unified-runtime-reviewers, ping x2.

**Review by fabiomestre — APPROVED** [review]
sycl/plugin changes LGTM

**Pull request merged**
