### PR TITLE
[SYCL][FPGA] Refactor statments attributes to align with community the way we handle conflicting vs duplicate values

### PR DESCRIPTION
**Pull request by smanna12**
This patch updates ExprArgument<> to use same routine CheckForDuplicateAttrs() that was added on https://github.com/intel/llvm/pull/12243 to diagnose non-identical duplicates as a 'conflicting' loop attributes and suppresse duplicate errors in cases where the two match for FPGA SYCL attributes: [[intel::max_concurrency()]] and [[intel::initiation_interval()]] to align with clang community change (Ref: https://github.com/llvm/llvm-project/pull/70762).

### CODE REVIEW

**Review by premanandrao — APPROVED** [review]
LGTM

**Comment by smanna12** [comment]
Thank you @premanandrao for reviews.

**Comment by smanna12** [comment]
The failing is unrelated to my patch.

@intel/llvm-gatekeepers, could you please merge this PR? Thanks

**Comment by smanna12** [comment]
Ping @intel/llvm-gatekeepers, please merge.

**Pull request merged**
