### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW17 2024)

### PR DESCRIPTION
**Pull request by iclsrc**
LLVM: llvm/llvm-project@07e6c1609d0a57f7ddc0537b7794be2e0296658b
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@a2783135be3f37f1e210aaf219b45a3226d32813

### CODE REVIEW

**Comment by jsji** [comment]
Massive failures in https://github.com/intel/llvm/actions/runs/8835546930/job/24266101186 is due to SPIRV commit 992e4beaf60a54908bfdb74e920e0393fd4fb12f. (https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/5e0f14b5a09d961)

**Comment by jsji** [comment]
- [ ] [Revert "Translate icmp eq and icmp ne to PtrEqual and PtrNotEqual res…](https://github.com/intel/llvm/pull/13566/commits/c4be8858f391563a63f18ba55dc73ca13c680fcb) This is temporarily revert to resolve massive failures in e2e tests https://github.com/intel/llvm/actions/runs/8835546930/job/24266101186 . @vmaksimo @intel/dpcpp-spirv-reviewers  Please review and follow up. Thanks.

**Review by frasercrmck — COMMENTED** [review]
`libclc` LGTM

**Comment by jsji** [comment]
@vmaksimo @intel/dpcpp-spirv-reviewers Can you please review and comments explicitly on this PR so that this can be merged. Thansk.

**Comment by asudarsa** [comment]
SPIR-V Revert looks ok to me. Needs further investigation to understand root cause and unrevert at a later stage.

Thanks

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Wed 01 May 2024 01:24:11 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Wed 01 May 2024 01:28:26 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
