### PR TITLE
[SYCL] Return some Windows symbols in library back

### PR DESCRIPTION
**Pull request by dm-vodopyanov**
This patch returns some of the symbols of the library which
had @ONEAPI@sycl@ before #4014 , and after that they were
renamed to @oneapi@ext@sycl@. These symbols can't be used
by users because the fully internal class stream_impl was exported,
so nothing breaks. Anyway, some symbols were removed in
comparison with Gold, and we can't change ABI yet. During the
timeframe where we can break ABI, we can fix stream_impl by
removing `__SYCL_EXPORT` from it.

### CODE REVIEW

**Review by alexbatashev — APPROVED** [review]

**Review by s-kanaev — APPROVED** [review]

**Comment by dm-vodopyanov** [comment]
Jenkins/Summary failures cannot be related to this patch as test suite in it failed on Linux only. This patch has only Windows changes.
@bader if everything is ok, this PR can be merged.

**Comment by bader** [comment]
> Jenkins/Summary failures cannot be related to this patch as test suite in it failed on Linux only. This patch has only Windows changes.
> @bader if everything is ok, this PR can be merged.

I would prefer if @romanovvlad gives another look and merge it. @dm-vodopyanov, please, file a ticket on unrelated failure.

**Comment by bader** [comment]
> This patch returns some unnecessary exported symbols on Windows which
> could not be used by customers, and their absence didn't break anything
> in user's application.

This sounds like you are adding some garbage to the library. Could you clarify why you are doing that?

**Comment by dm-vodopyanov** [comment]
> please, file a ticket on unrelated failure.

Created an internal ticket. The failure looks like an infra issue.

> This sounds like you are adding some garbage to the library. Could you clarify why you are doing that?

That's absolutely true. These garbage symbols were removed from the library because Windows has very broad names of exported symbols and some of the symbols of the library had `@ONEAPI@sycl@` before #4014 , and after that they were renamed to `@oneapi@ext@sycl@`. These symbols can't be used by users because the fully internal class `stream_impl` was exported, so nothing breaks. Anyway, the amount of symbols changed since Gold, and we can't change it yet. During timeframe where we can break ABI, we can fix stream_impl by removing `__SYCL_EXPORT` from it.

**Pull request merged**
