### PR TITLE
[SYCL][Headers cleanup] Add a test for dependencies of some of the headers

### PR DESCRIPTION
**Pull request by aelovikov-intel**
The test would serve two purposes:
- Prevent changes from introducing unnecessary dependencies
- Showcase reductions in those dependencies for PRs that try to cleanup our headers.

### CODE REVIEW

**Comment by aelovikov-intel** [comment]
Will be used like this: https://github.com/intel/llvm/pull/13211/commits/3f34e51032aa305b28cfe4188633e8e31ccde598.

**Comment by bader** [comment]
> No description provided.

What is this change about? Why do we need it?

**Comment by aelovikov-intel** [comment]
> What is this change about? Why do we need it?

> This is ready for review/**discussion**. 

> Will be used like this: https://github.com/intel/llvm/commit/3f34e51032aa305b28cfe4188633e8e31ccde598.

**Comment by bader** [comment]
> > What is this change about? Why do we need it?
> 
> > This is ready for review/**discussion**.
> 
> > Will be used like this: [3f34e51](https://github.com/intel/llvm/commit/3f34e51032aa305b28cfe4188633e8e31ccde598).

Thanks, but I don't see how it answers my questions.

@aelovikov-intel, please, provide more detailed description for this change.
Pay attention to this part of our [contribution guide](https://github.com/intel/llvm/blob/sycl/CONTRIBUTING.md#pull-request).

> [The seven rules of a great Git commit message](https://cbea.ms/git-commit) are recommended read and follow.

It should give a starting point for the discussion you are looking for.

**Comment by aelovikov-intel** [comment]
> Thanks, but I don't see how it answers my questions.

I don't understand what exactly your concern is. Are you saying that the PR's description doesn't satisfy the requirements for the approval to be granted or that you have absolutely zero idea and, as of now, see zero value in the test and can't even start a meaningful discussion?

If the former (approval criteria), then I don't disagree at all. If the latter (you don't see any value in this even *after* looking at https://github.com/intel/llvm/commit/3f34e51032aa305b28cfe4188633e8e31ccde598 and thus it's impossible to start any productive discussion), then I'd guess I need to find some other way to organize the work on headers cleanup, because my idea was that the test updates for the cleanup changes would be self-explanatory.

**Comment by bader** [comment]
> I need to find some other way to organize the work on headers cleanup, because my idea was that the test updates for the cleanup changes would be self-explanatory.

I don't think this change is self-explanatory (at least for me) and that's the reason I pointed to the contribution guide, which includes recommendations for commit messages (i.e. PR description in our case).

**Comment by againull** [comment]
So, is the main goal of this test is to prevent from adding unnecessary inclusions to these headers after we clean them up? I.e. to avoid increasing the build time.
Changes in the PR look good to me. Even though with the latest compiler I don't see
```
// CHECK-NEXT: null.o: /dev/null
// CHECK-NEXT: detail/defines_elementary.hpp
// CHECK-NEXT: /dev/null: /dev/null
// CHECK-NEXT: detail/defines_elementary.hpp
```
I see only:
{noformat}
// CHECK-NEXT: /dev/null: /dev/null
// CHECK-NEXT: detail/defines_elementary.hpp
{noformat}
Not sure what has changed. As far as I understand these are supposed to be checks for host and device compiler accordingly.

**Comment by bader** [comment]
> So, is the main goal of this test is to prevent from adding unnecessary inclusions to these headers after we clean them up?

I don't know. What I meant in my previous comments - we should not try to guess the intent of author. It should be explicitly stated in the PR description.

**Review by againull — COMMENTED** [review]
LGTM

**Review by againull — APPROVED** [review]

**Pull request merged**
