### PR TITLE
[SYCL] Remove function pointers extension

### PR DESCRIPTION
**Pull request by alexbatashev**

### CODE REVIEW

**Comment by alexbatashev** [comment]
Depends on https://github.com/intel/llvm-test-suite/pull/437

**Comment by alexbatashev** [comment]
Lit failure is a known flaky issue

**Comment by alexbatashev** [comment]
@intel/llvm-reviewers-runtime @AlexeySachkov friendly ping

**Review by AlexeySachkov — APPROVED** [review]

**Review by s-kanaev — APPROVED** [review]
LGTM

**Pull request merged**
