### PR TITLE
[SYCL][NFC] Move SYCL_EXT_ONEAPI_USER_DEFINED_REDUCTIONS to experimental

### PR DESCRIPTION
**Pull request by dm-vodopyanov**

### CODE REVIEW

**Comment by gmlueck** [comment]
Please update the Status section to indicate that the extension is now experimental.  See the [template](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/template.asciidoc#status) for the correct text.

**Comment by AlexeySachkov** [comment]
> Please update the Status section to indicate that the extension is now experimental. See the [template](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/template.asciidoc#status) for the correct text.

@dm-vodopyanov, could you please apply this comment so we can merge the PR?

**Comment by dm-vodopyanov** [comment]
@gmlueck sorry for late response, the comment is applied.

**Comment by gmlueck** [comment]
> sorry for late response, the comment is applied.

Thanks.  That looks good.  One minor thing ... could you change the copyright date to "2022 - 2023" too?

**Comment by dm-vodopyanov** [comment]
> > sorry for late response, the comment is applied.
> 
> Thanks. That looks good. One minor thing ... could you change the copyright date to "2022 - 2023" too?

Thanks, done

**Review by gmlueck — APPROVED** [review]

**Pull request merged**
