### PR TITLE
[CI][OSSF]Set permissions on sycl-issues-ping-assignee

### PR DESCRIPTION
**Pull request by stdale-intel**
Set read-all permissions on this workflow as it should not require any write permissions

### CODE REVIEW

**Review by uditagarwal97 — APPROVED** [review]
LGTM.

**Comment by uditagarwal97** [comment]
This PR just sets the permissions for `sycl_issue_ping_assignee` GH workflow and so the CI failures are unrelated.

**Comment by uditagarwal97** [comment]
@stdale-intel FYI: https://github.com/intel/llvm/actions/runs/9654231116 the workflow failed due to insufficient permissions.
I think we need to add `issues: write` permission to the job.

**Comment by stdale-intel** [comment]
@uditagarwal97  I was thinking about that during dinner (if gh command did need permissions) https://github.com/intel/llvm/pull/14275

**Pull request merged**
