### PR TITLE
[GHA] Uplift Linux GPU RT version to 22.43.24558

### PR DESCRIPTION
**Pull request by bb-sycl**
Scheduled drivers uplift

### CODE REVIEW

**Comment by MrSidims** [comment]
Do we have plans to update windows drivers as well? It does look like the last time it was done is 2022-02-06
I see the following in git blame:
```
f4b31230fc861 (Alexander Batashev  2022-02-06 12:40:26 +0300  84)   "windows": {
f4b31230fc861 (Alexander Batashev  2022-02-06 12:40:26 +0300  85)     "compute_runtime": {
f4b31230fc861 (Alexander Batashev  2022-02-06 12:40:26 +0300  86)       "version": "101.1191",
f4b31230fc861 (Alexander Batashev  2022-02-06 12:40:26 +0300  87)       "url": "https://downloadmirror.intel.com/691496/igfx_win_101.1191.zip",
f4b31230fc861 (Alexander Batashev  2022-02-06 12:40:26 +0300  88)       "root": ""
f4b31230fc861 (Alexander Batashev  2022-02-06 12:40:26 +0300  89)     },
```

**Comment by MrSidims** [comment]
Tagging @bader @pvchupin 
old version of GPU driver prevents us from, for example, updating supported SPIR-V version to 1.4.

**Comment by pvchupin** [comment]
@MrSidims, in github actions we don't have an automatic mechanism to update driver on Windows. We don't have containers on windows.
In fact we don't have any testing on GPU on Windows as well in github actions.
So when you said that it prevents us from moving onto SPIRV-1.4, where exactly do you see the failure?

This specific GPU driver version is still broken. It doesn't have all dependencies needed for Ubuntu 20.

**Comment by MrSidims** [comment]
@pvchupin  Previously I attempted to update SPIR-V version in https://github.com/intel/llvm/pull/6899 , and the regression was reported in https://github.com/intel/llvm/pull/7018 in ESIMD testing on Windows.

>> In fact we don't have any testing on GPU on Windows as well in github actions.

Doesn't /verify command run the tests? Otherwise I don't see how these tests were run in Steffan's PR.

**Comment by MrSidims** [comment]
>> Doesn't /verify command run the tests?

It does look like it doesn't, at least right now. Guess it's a chance for to squeeze a path :)

**Comment by pvchupin** [comment]
@MrSidims I think you are confusing jenkins and github actions. These are 2 different systems.
Let's chat offline.

**Pull request closed without merging**
