### PR TITLE
[SYCL][L0] Support for >4Gb device allocations.

### PR DESCRIPTION
**Pull request by smaslov-intel**
E2E test is coming in https://github.com/intel/llvm-test-suite/pull/298.
Signed-off-by: Sergey V Maslov <sergey.v.maslov@intel.com>

### CODE REVIEW

**Review by againull — APPROVED** [review]

**Comment by bader** [comment]
@smaslov-intel, please, address pre-commit failure.

**Comment by smaslov-intel** [comment]
> @smaslov-intel, please, address pre-commit failure.

@bader , the changes in PR revealed an issue in the Level Zero driver that is being addressed.
Should this wait for the updated driver or we can allow regression (it's really not a harmful one)?

**Comment by bader** [comment]
> > @smaslov-intel, please, address pre-commit failure.
> 
> @bader , the changes in PR revealed an issue in the Level Zero driver that is being addressed.
> Should this wait for the updated driver or we can allow regression (it's really not a harmful one)?

Let's mark these tests as "expected to fail" until driver update.

**Comment by smaslov-intel** [comment]
> > > @smaslov-intel, please, address pre-commit failure.
> > 
> > 
> > @bader , the changes in PR revealed an issue in the Level Zero driver that is being addressed.
> > Should this wait for the updated driver or we can allow regression (it's really not a harmful one)?
> 
> Let's mark these tests as "expected to fail" until driver update.

Disabled USM/badmalloc in https://github.com/intel/llvm-test-suite/pull/298

**Review by bader — APPROVED** [review]
Thanks!

**Pull request merged**
