### PR TITLE
[UR][L0] Enable default support for L0 in-order lists

### PR DESCRIPTION
**Pull request by raiyanla**

### CODE REVIEW

**Review by kbenzie — APPROVED** [review]

**Review by kbenzie — APPROVED** [review]

**Comment by kbenzie** [comment]
@intel/llvm-gatekeepers please merge

**Comment by steffenlarsen** [comment]
There seems to be a unified_runtime/CMakeLists.txt conflict.

**Comment by kbenzie** [comment]
> There seems to be a unified_runtime/CMakeLists.txt conflict.

Okay, I'll fix this. I was sure this wasn't a conflict last night...

**Comment by kbenzie** [comment]
@intel/llvm-gatekeepers please merge

**Pull request merged**
