### PR TITLE
[SYCL][ESIMD][E2E] Fix slm_init_no_inline compiler flags on Windows

### PR DESCRIPTION
**Pull request by sarnex**
We need to use /clang there.

### CODE REVIEW

**Comment by sarnex** [comment]
@intel/dpcpp-devops-reviewers I think the HIP machine is in a weird state again, can someone reset it? I tried restarting the CI a few times but it didn't fix it.

```
Platforms: 0
default_selector()      : No device of requested type available. -1 (PI_ERRO...
accelerator_selector()  : No device of requested type available. -1 (PI_ERRO...
cpu_selector()          : No device of requested type available. -1 (PI_ERRO...
gpu_selector()          : No device of requested type available. -1 (PI_ERRO...
custom_selector(gpu)    : No device of requested type available. -1 (PI_ERRO...
custom_selector(cpu)    : No device of requested type available. -1 (PI_ERRO...
custom_selector(acc)    : No device of requested type available. -1 (PI_ERRO...
````

**Comment by aelovikov-intel** [comment]
> @intel/dpcpp-devops-reviewers I think the HIP machine is in a weird state again, can someone reset it?

rebooted.

**Comment by sarnex** [comment]
```
Failed Tests (2):
  SYCL :: Annotated_arg_ptr/annotated_arg.cpp
  SYCL :: Annotated_arg_ptr/annotated_ptr.cpp
```

Windows issue not related

**Review by v-klochkov — APPROVED** [review]

**Comment by sarnex** [comment]
@intel/llvm-gatekeepers Can we merge this one? I tried to rerun the Win E2E CI but it seems stuck, here are the results from a previous run (no changes with current, I just restarted it) and it has unrelated failures:

https://github.com/intel/llvm/actions/runs/6224435385/job/16906814653?pr=11171

```
 ********************
Failed Tests (2):
  SYCL :: Annotated_arg_ptr/annotated_arg.cpp
  SYCL :: Annotated_arg_ptr/annotated_ptr.cpp

```

**Pull request merged**
