### PR TITLE
[SYCL] Remove outdated template aliases (optimize headers pt2)

### PR DESCRIPTION
**Pull request by alexbatashev**
Remove some outdated template aliases, since minimally required C++ standard is now 14. This is mostly mechanical change.

### CODE REVIEW

**Review by keryell — APPROVED** [review]
Good cleaning!

**Review by romanovvlad — DISMISSED** [review]

**Review by kbobrovs — DISMISSED** [review]
ESIMD LGTM

**Review by AlexeySachkov — APPROVED** [review]
`spirv.hpp` LGTM

**Review by Pennycook — APPROVED** [review]
spirv.hpp changes LGTM.

**Review by romanovvlad — APPROVED** [review]

**Pull request closed without merging**
