### PR TITLE
[SYCL] Add dependency configuration file

### PR DESCRIPTION
**Pull request by vladimirlaz**
Signed-off-by: Vladimir Lazarev <vladimir.lazarev@intel.com>

### CODE REVIEW

**Comment by bader** [comment]
@vladimirlaz 
```
28:   . Check parallel_for_work_group(range, functor)
1/1 Test #28: test_handler_opencl ..............***Exception: SegFault 92.18 sec
```
:-(

**Comment by bader** [comment]
The trick doesn't work.
http://ci.llvm.intel.com:8010/#/builders/29/builds/706/steps/9/logs/stdio

**Comment by bader** [comment]
Should we close PR?

**Comment by vladimirlaz** [comment]
I suggest to wait for reply from tools team

**Comment by bader** [comment]
> I suggest to wait for reply from tools team

What will it change? I don't think we should merge this patch in any case.

**Pull request closed without merging**
