### PR TITLE
[BuildBot] Uplift GPU RT version for Linux CI Process

### PR DESCRIPTION
**Pull request by bb-sycl**
Uplift GPU RT version for Linux to 21.36.20889

### CODE REVIEW

**Comment by vladimirlaz** [comment]
@smaslov-intel could you please have a look? It looks like L0 interoperability test is failing on the latest GPU driver? Is it known regression in driver or we need update out product/test?

**Comment by smaslov-intel** [comment]
> @smaslov-intel could you please have a look? It looks like L0 interoperability test is failing on the latest GPU driver? Is it known regression in driver or we need update out product/test?



> @smaslov-intel could you please have a look? It looks like L0 interoperability test is failing on the latest GPU driver? Is it known regression in driver or we need update out product/test?

@vladimirlaz: while it looks like a GPU RT regression, I found it to be a bug in the test. Fixed in https://github.com/intel/llvm-test-suite/pull/460

**Comment by vladimirlaz** [comment]
@yinyangsx, @yanfeng3721 it looks like the test jobs are failing on the merge step. Could you please merge resent changes from the sycl branch to the PR to resolve conflicts

**Comment by yanfeng3721** [comment]
> @yinyangsx, @yanfeng3721 it looks like the test jobs are failing on the merge step. Could you please merge resent changes from the sycl branch to the PR to resolve conflicts

Hi @vladimirlaz , the conflict has been resolved, waiting for new preci testing result.

**Comment by yanfeng3721** [comment]
The regression on CPU looks like a flaky crash of clang, rerunning the failed sub test. 
```
[2021-09-15T08:52:28.608Z] [47/47] : && /netbatch/donb670734_00/runDir/jenkins-dir/workspace/SYCL_CI/intel/Lin/Regression_CTS_CPU/llvm.obj/bin/clang++ -ffp-model=precise  -fsycl -fsycl-targets=spir64-unknown-unknown-sycldevice -sycl-std=2020 -fsycl-device-code-split=per_kernel tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_char.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_signed_char.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_unsigned_char.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_short.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_unsigned_short.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_int.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_unsigned_int.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_long.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_unsigned_long.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_long_long.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_unsigned_long_long.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_float.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_double.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_sycl__half.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_sycl__byte.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_int8_t.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_int16_t.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_int32_t.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_int64_t.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_uint8_t.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_uint16_t.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_uint32_t.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_uint64_t.cpp.o tests/common/CMakeFiles/main_function_object.dir/main.cpp.o -o bin/test_vector_swizzles  -Wl,-rpath,/netbatch/donb670734_00/runDir/jenkins-dir/workspace/SYCL_CI/intel/Lin/Regression_CTS_CPU/llvm.obj/lib util/libutil.a oclmath/liboclmath.a /netbatch/donb670734_00/runDir/jenkins-dir/workspace/SYCL_CI/intel/Lin/Regression_CTS_CPU/llvm.obj/lib/libOpenCL.so && :
[2021-09-15T08:52:28.608Z] FAILED: bin/test_vector_swizzles 
[2021-09-15T08:52:28.608Z] : && /netbatch/donb670734_00/runDir/jenkins-dir/workspace/SYCL_CI/intel/Lin/Regression_CTS_CPU/llvm.obj/bin/clang++ -ffp-model=precise  -fsycl -fsycl-targets=spir64-unknown-unknown-sycldevice -sycl-std=2020 -fsycl-device-code-split=per_kernel tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_char.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_signed_char.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_unsigned_char.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_short.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_unsigned_short.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_int.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_unsigned_int.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_long.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_unsigned_long.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_long_long.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_unsigned_long_long.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_float.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_double.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_sycl__half.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_sycl__byte.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_int8_t.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_int16_t.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_int32_t.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_int64_t.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_uint8_t.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_uint16_t.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_uint32_t.cpp.o tests/vector_swizzles/CMakeFiles/test_vector_swizzles_objects.dir/vector_swizzles_uint64_t.cpp.o tests/common/CMakeFiles/main_function_object.dir/main.cpp.o -o bin/test_vector_swizzles  -Wl,-rpath,/netbatch/donb670734_00/runDir/jenkins-dir/workspace/SYCL_CI/intel/Lin/Regression_CTS_CPU/llvm.obj/lib util/libutil.a oclmath/liboclmath.a /netbatch/donb670734_00/runDir/jenkins-dir/workspace/SYCL_CI/intel/Lin/Regression_CTS_CPU/llvm.obj/lib/libOpenCL.so && :
[2021-09-15T08:52:28.608Z] clang++: warning: argument 'spir64-unknown-unknown-sycldevice' is deprecated, use 'spir64' instead [-Wdeprecated]
[2021-09-15T08:52:28.608Z] clang++: error: unable to execute command: Killed
[2021-09-15T08:52:28.608Z] clang++: error: sycl-post-link command failed due to signal (use -v to see invocation)
[2021-09-15T08:52:28.608Z] clang version 14.0.0 (https://70a399a8332ecdd9cdb9e48e3b58dc897a6dc842@github.com/intel/llvm.git adf3aaf4d7a9b0ada17f22df488b04b433dda1ba)
[2021-09-15T08:52:28.608Z] Target: x86_64-unknown-linux-gnu
[2021-09-15T08:52:28.608Z] Thread model: posix
[2021-09-15T08:52:28.608Z] InstalledDir: /netbatch/donb670734_00/runDir/jenkins-dir/workspace/SYCL_CI/intel/Lin/Regression_CTS_CPU/llvm.obj/bin
[2021-09-15T08:52:28.608Z] clang++: note: diagnostic msg: Error generating preprocessed source(s).
[2021-09-15T08:52:28.608Z] ninja: build stopped: cannot make progress due to previous errors.
```

**Comment by bader** [comment]
GPU driver is already updated to more recent version in https://github.com/intel/llvm/pull/4598.

**Pull request closed without merging**
