### PR TITLE
[SYCL][ESIMD][NFC] Split up memory_properties.cpp

### PR DESCRIPTION
**Pull request by sarnex**
It was really slow. We can split it more later if someone complains.

Top 4 slowest:
```
121.13s: SYCL :: esimd/memory_properties.cpp
38.22s: SYCL :: regression/async_work_group_copy.cpp
32.57s: SYCL :: basic_tests/stdcpp_compat.cpp
28.73s: SYCL :: basic_tests/reduction/reducer_aliases.cpp
```

After
```
56.61s: SYCL :: esimd/memory_properties_gather.cpp
51.17s: SYCL :: regression/async_work_group_copy.cpp
49.94s: SYCL :: esimd/memory_properties_atomic_update.cpp
44.52s: SYCL :: esimd/memory_properties_scatter.cpp
```

### CODE REVIEW

**Comment by bader** [comment]
@sarnex, what is the goal of this change? Based on the provided data, the overall e2e test execution time will increase!

**Comment by sarnex** [comment]
@bader Won't they run in parallel?

**Comment by bader** [comment]
> @bader Won't they run in parallel? 

It depends on where and how you run them. LIT uses all available CPU cores by default, but it's not clear if it helps.

> Are we really optimizing for per-test time total vs user-experienced runtime?

I think both are important. Could you provide "user-experienced runtime" for CI machines, please?

**Comment by sarnex** [comment]
Before
```
Slowest Tests:
--------------------------------------------------------------------------
93.93s: SYCL :: esimd/memory_properties.cpp
41.13s: SYCL :: basic_tests/stdcpp_compat.cpp
40.95s: SYCL :: basic_tests/types.cpp
35.85s: SYCL :: regression/multi_targeting.cpp
33.62s: SYCL :: regression/async_work_group_copy.cpp
```

**Comment by sarnex** [comment]
After
```
Slowest Tests:
--------------------------------------------------------------------------
49.96s: SYCL :: regression/multi_targeting.cpp
45.31s: SYCL :: regression/async_work_group_copy.cpp
44.85s: SYCL :: basic_tests/types.cpp
44.68s: SYCL :: esimd/memory_properties_gather.cpp
37.63s: SYCL :: esimd/memory_properties_atomic_update.cpp
35.36s: SYCL :: basic_tests/device-selectors-exception.cpp
31.56s: SYCL :: esimd/memory_properties_scatter.cpp
```

**Comment by sarnex** [comment]
@bader Data is above, in your opinion should I proceed with this change?

**Comment by bader** [comment]
From "before" logs:
Testing Time: 164.75s

From "after" logs:
Testing Time: 258.21s

I'm not sure if it's correct to compare these numbers as tests executed on different machines. 

I found another post-commit executed on the same runner as "after" run and I see no difference in the "Testing Time" metric.
https://github.com/intel/llvm/actions/runs/8537157176/job/23387151815
Testing Time: 259.79s

> Data is above, in your opinion should I proceed with this change?

I still think we make things worse by splitting one slow test into 5 which are faster individually, but slower combined. CI runs 1000 tests in parallel and new tests are slower by the margin, which is hard to notice on our CI system. I would rather carefully review the scope of the work the test is doing to see if we can do less work. The test seems to be very exhaustive, so we can probably do better by distributing the load between pre-/post- and nightly tests.

I just looked at some random place in the deleted test and see following check:
```c++
  // 3) prefetch(usm, offset): offset is scalar
  // CHECK-COUNT-8: call void @llvm.genx.lsc.prefetch.stateless.v1i1.v1i64(<1 x i1> {{[^)]+}}, i8 0, i8 2, i8 1, i16 1, i32 0, i8 3, i8 1, i8 2, i8 0, <1 x i64> {{[^)]+}}, i32 0)
  __ESIMD_NS::prefetch(ptrf, byte_offset32, props_cache_load);
  __ESIMD_NS::prefetch(ptrf, byte_offset64, props_cache_load);
  __ESIMD_NS::prefetch(ptrf, props_cache_load);
  __ESIMD_NS::prefetch(ptrf, mask_n1, props_cache_load);
  __ESIMD_NS::prefetch(ptrf, byte_offset32, mask_n1, props_cache_load);
  __ESIMD_NS::prefetch(ptrf, byte_offset64, mask_n1, props_cache_load);
  __ESIMD_NS::prefetch(ptrf, byte_offset32, mask_n1, props_cache_load);
  __ESIMD_NS::prefetch(ptrf, byte_offset64, mask_n1, props_cache_load);
```

1. What is the point of two last line, which are same as two lines just above them? Copy-paste bug? 
2. Do we really need to validate all combinations for each change in the SYCL code? I see the value for thorough testing of the driver update. Can we go lighter for the SYCL level changes (e.g. involve less compilation stages)?

**Comment by sarnex** [comment]
I'll just drop this change for now. 
1 appears to be a copy paste bug, feel free to open an issue.
2 the ESIMD API is very complicated and has many cases. I'm not sure if every thing being tested has value, but it being more complicated than basic SYCL is expected.

**Comment by v-klochkov** [comment]
I don't think closing this JIRA is correct thing to do.
Here is what I see locally - the 1 slowest test limits the total runtime for the suite: 1 test - 105.70 sec, total for 1403 tests - 105.95 sec:

-- Testing: 1403 tests, 224 workers --
...
105.70s: SYCL :: esimd/memory_properties.cpp                                                                                                                                                                                                                           
41.60s: SYCL :: regression/async_work_group_copy.cpp                                                                                                                                                                                                                   
29.44s: SYCL :: basic_tests/stdcpp_compat.cpp                                                                                                                                                                                                                          
28.64s: SYCL :: extensions/properties/properties_kernel_work_group_size_hint.cpp                                                                                                                                                                                       
28.60s: SYCL :: extensions/properties/properties_kernel_sub_group_size.cpp                                                                                                                                                                                             
28.55s: SYCL :: extensions/properties/properties_kernel_work_group_size.cpp                                                                                                                                                                                            
27.90s: SYCL :: gdb/accessors.cpp                                                                                                                                                                                                                                      
27.69s: SYCL :: basic_tests/reduction/reducer_aliases.cpp                                                                                                                                                                                                              
26.62s: SYCL :: regression/multi_ptr_gen_casting.cpp                                                                                                                                                                                                                   
26.53s: SYCL :: basic_tests/vectors/vectors.cpp                                                                                                                                                                                                                        
26.21s: SYCL :: basic_tests/vectors/constexpr-constructor.cpp                                                                                                                                                                                                          
26.14s: SYCL :: basic_tests/valid_kernel_args.cpp                                                                                                                                                                                                                      
26.11s: SYCL :: basic_tests/types.cpp                                                                                                                                                                                                                                  
26.09s: SYCL :: basic_tests/reduction/reduction_range_deduction.cpp                                                                                                                                                                                                    
25.74s: SYCL :: gdb/private-memory.cpp                                                                                                                                                                                                                                 
25.29s: SYCL :: esimd/odr.cpp                                                                                                                                                                                                                                          
25.27s: SYCL :: warnings/warnings.cpp                                                                                                                                                                                                                                  
24.87s: SYCL :: basic_tests/builtins/relational_builtins.cpp                                                                                                                                                                                                           
24.78s: SYCL :: basic_tests/no_math_in_global_ns.cpp                                                                                                                                                                                                                   
24.63s: SYCL :: basic_tests/handler/parallel_for_args.cpp

Tests Times:                                                                                                                                                                                                                                                           
--------------------------------------------------------------------------                                                                                                                                                                                             
[   Range   ] :: [               Percentage               ] :: [ Count ]
--------------------------------------------------------------------------
[100s,110s) :: [                                        ] :: [  1/850]
[ 90s,100s) :: [                                        ] :: [  0/850]
[ 80s, 90s) :: [                                        ] :: [  0/850]
[ 70s, 80s) :: [                                        ] :: [  0/850]
[ 60s, 70s) :: [                                        ] :: [  0/850]
[ 50s, 60s) :: [                                        ] :: [  0/850]
[ 40s, 50s) :: [                                        ] :: [  1/850]
[ 30s, 40s) :: [                                        ] :: [  1/850]
[ 20s, 30s) :: [**                                      ] :: [ 44/850]
[ 10s, 20s) :: [********                                ] :: [188/850]
[  0s, 10s) :: [****************************            ] :: [615/850]
--------------------------------------------------------------------------

Testing Time: 105.95s

**Pull request closed without merging**
