### PR TITLE
[SYCL] Use /bigobj to compile builtins.cpp on Windows

### PR DESCRIPTION
**Pull request by v-klochkov**
Signed-off-by: Klochkov <vyacheslav.n.klochkov@intel.com>

### CODE REVIEW

**Comment by v-klochkov** [comment]
Without /bigobj the file builtins.cpp cannot be built on Windows in Debug mode.

**Comment by bader** [comment]
> Without /bigobj the file builtins.cpp cannot be built on Windows in Debug mode.

Please, consider splitting builtins.cpp into several files.
This should fix the Windows/Debug problem and speed-up compilation.

**Comment by v-klochkov** [comment]
>Please, consider splitting builtins.cpp into several files.
>This should fix the Windows/Debug problem and speed-up compilation.

Alexey, I gave it a thought, but I don't see any visible positive impact from such work on splitting the file.

What do you mean by "speed-up compilation"? 
It takes a tiny bit a second to build builtins.cpp with /bigobj. 
Splitting builtins.cpp will not make the user's programs compilation faster all that builtins (1 obj file or several obj file) gets to the same sycl.lib.

builtins.cpp now is:

400+ lines of macro defines, helper template classes. THESE lines will be duplicated, or moved to a header.
400+ lines of template functions for sections listed below. THESE lines need to be carefully split

/* ----------------- 4.13.3 Math functions. Host version --------------------*/
round(), rsqrt(), sincos(), log1p(), half_fmin(), ...

/* --------------- 4.13.4 Integer functions. Host version -------------------*/
u_abs(), u_add_sat(), ...

/* --------------- 4.13.5 Common functions. Host version --------------------*/
fclamp(), degrees(), mix(), step(), smoothstep()

/* --------------- 4.13.6 Geometric Functions. Host version -----------------*/
cross(), FMul(), length(), ...

/* --------------- 4.13.7 Relational functions. Host version --------------*/
FOrdEqual(), FUnordNotEqual(), IsNan(), SignBitSet(), ...

/* --------------- 4.13.3 Native Math functions. Host version ---------------*/
native_cos(), native_log2(), native_rsqrt(), ...

/* ----------------- 4.13.3 Half Precision Math functions. Host version -----*/
half_cos(), half_tan(), ...

**Comment by bader** [comment]
> 400+ lines of macro defines, helper template classes. THESE lines will be duplicated, or moved to a header.

I prefer a header.

> 400+ lines of template functions for sections listed below. THESE lines need to be carefully split

Sounds like a plan.

**Comment by bader** [comment]
> > 400+ lines of macro defines, helper template classes. THESE lines will be duplicated, or moved to a header.
> 
> I prefer a header.
> 
> > 400+ lines of template functions for sections listed below. THESE lines need to be carefully split
> 
> Sounds like a plan.

@v-klochkov, could you clarify the intention for this patch, please?
Are you going to split the builtins.cpp or you are willing to merge current version of the patch?

**Comment by v-klochkov** [comment]
I am working on a different version of a patch that splits builtins.cpp into 5 cpp files: common, geo, math, int, rel.
Have not decided yet how to deal with 400 lines of macro and helper struct definitions that are common for them:
`
#define MAKE_1V_2V_3P(Fun, Ret, Arg1, Arg2, Arg3)                              \
  __MAKE_1V_2V_3P(Fun, 2, Ret, Arg1, Arg2, Arg3)                               \
  __MAKE_1V_2V_3P(Fun, 3, Ret, Arg1, Arg2, Arg3)                               \
  __MAKE_1V_2V_3P(Fun, 4, Ret, Arg1, Arg2, Arg3)                               \
  __MAKE_1V_2V_3P(Fun, 8, Ret, Arg1, Arg2, Arg3)                               \
  __MAKE_1V_2V_3P(Fun, 16, Ret, Arg1, Arg2, Arg3)
 ...
 template <int N> struct helper {
 ...
`

**Comment by v-klochkov** [comment]
The alternative approach - with splitting of builtins.cpp to 5 cpp + 1 hpp files is uploaded here:
https://github.com/intel/llvm/pull/298

**Pull request closed without merging**
