### PR TITLE
[SYCL][E2E][Bindless] Check and use DedicatedAllocation in vulkan interop test for L0

### PR DESCRIPTION
**Pull request by wenju-he**
Vulkan interop in L0 backend currently has an issue that image sizes are not correctly passed to graphics memory management (GMM). Using dedicated allocation is an approach to solve the issue. In this case, image and device memory has 1:1 mapping and GMM is aware of the image info.
This PR enables VK_KHR_GET_MEMORY_REQUIREMENTS_2_EXTENSION_NAME extension and checks if VkMemoryDedicatedRequirements.requiresDedicatedAllocation is true. The value is false by default in CUDA and L0 backends.

### CODE REVIEW

**Review by przemektmalon — APPROVED** [review]
LGTM. We've tested this with the CUDA backend on Windows and Linux. Tests pass.

**Comment by wenju-he** [comment]
@intel/llvm-gatekeepers please merge, thank you.

**Comment by sommerlukas** [comment]
@wenju-he Is this PR really NFC or should we remove this tag from the title?

**Comment by wenju-he** [comment]
> @wenju-he Is this PR really NFC or should we remove this tag from the title?

@sommerlukas this PR only modify tests, so it is not changing compiler.

**Comment by wenju-he** [comment]
> @wenju-he - We normally mark it with [E2E] or similar when it only touches test-e2e tests. Would you mind if we change [NFC] to [E2E]?

@steffenlarsen done, thank you

**Comment by steffenlarsen** [comment]
> @steffenlarsen done, thank you

Thanks! 😄

**Pull request merged**
