### PR TITLE
[UR][L0] Return the build log on compilation failure

### PR DESCRIPTION
**Pull request by sarnex**
Fix L0 build log, https://github.com/oneapi-src/unified-runtime/pull/1923

### CODE REVIEW

**Comment by sarnex** [comment]
My reading of the UR contribution guide is that I should mark this as a ready for review now (UR PR is approved but not merged) and that I should still use my custom branch in the CMake file for now. Once the UR PR is merged I will update the CMake file here.

**Comment by sarnex** [comment]
@intel/unified-runtime-reviewers Ping on this one, thanks!

**Comment by omarahmed1111** [comment]
> @intel/unified-runtime-reviewers Ping on this one, thanks!

Will merge that next in the merge queue, will first merge UR part, then once we update CMake in this PR, will approve that so we could merge it.

**Comment by sarnex** [comment]
@omarahmed1111 Thanks, I updated the CMake file to point at the UR commit. Am I good to merge this? There are no other commits in UR in between the last version bump and my UR commit. Thanks

**Comment by omarahmed1111** [comment]
> @omarahmed1111 Thanks, I updated the CMake file to point at the UR commit. Am I good to merge this? There are no other commits in UR in between the last version bump and my UR commit. Thanks

Yeah, this is good to go.

**Pull request merged**
