### PR TITLE
[CI] Uplift oclcpu/oclfpgaemu from 2024.17.3.0.09 to 2024.18.10.0.08

### PR DESCRIPTION
**Pull request by yanfeng3721**

### CODE REVIEW

**Comment by yanfeng3721** [comment]
Waiting for oneTBB 2022.0 public release  in https://github.com/oneapi-src/oneTBB/releases.

**Comment by zhaomaosu** [comment]
Hi @yanfeng3721, looks like TBB 2022.0 is released. Is there any other blocking issue for this PR?

**Comment by yanfeng3721** [comment]
> Hi @yanfeng3721, looks like TBB 2022.0 is released. Is there any other blocking issue for this PR?

Hi @zhaomaosu , yes, the PR failed to pass sycl-ls check, could not detect oclcpu 2024.18.10.0.08
```
Run sycl-ls --verbose
[level_zero:gpu][level_zero:0] Intel(R) oneAPI Unified Runtime over Level-Zero, Intel(R) Iris(R) Xe Graphics [12](https://github.com/intel/llvm/actions/runs/11623185850/job/33174845944?pr=15827#step:17:13).0.0 [1.6.31294.120000]
[opencl:gpu][opencl:0] Intel(R) OpenCL Graphics, Intel(R) Iris(R) Xe Graphics OpenCL 3.0 NEO  [24.39.31294.12]
[native_cpu:cpu][native_cpu:0] SYCL_NATIVE_CPU, SYCL Native CPU 0.1 [0.0.0]
 the TBB 2022.0.0  and oclcpu 2024.18.10.0.08 package works
```

Hi @sarnex , since we have tried TBB 2022.0.0 and oclcpu oclcpu 2024.18.10.0.08 package locally and it works fine, could you please take a look why the deps does not work for intel/llvm CI? Thanks.

**Comment by sarnex** [comment]
I'll take a look.

**Comment by sarnex** [comment]
@yanfeng3721 @zhaomaosu 
I manually reproduced the problem on the runner and it looks like there's a problem with the TBB dependency used by the new OCL CPU driver:

image

This seems to be captured in CMPLRTST-25760. 

Is there some way we can work around this now or do we need to wait for a resolution to that ticket?

**Comment by sarnex** [comment]
@zhaomaosu @yanfeng3721 I fixed the problem and pushed it to your branch, hopefully that was ok. All the tests passed too, so if you guys are ready I think this PR is ready for merge.

**Review by sarnex — APPROVED** [review]

**Comment by zhaomaosu** [comment]
Thanks @sarnex for your quick fix!

**Comment by yanfeng3721** [comment]
Thanks @sarnex , please also help to merge the PR.

**Comment by sarnex** [comment]
Merged, thanks all!

**Pull request merged**
