### PR TITLE
[SYCL] Fix exception duplication for copy back command

### PR DESCRIPTION
**Pull request by KseniyaTikhomirova**
kernel_features_device_has_exceptions fails due to duplication of sync and async exceptions when command before copy back (copy back dependency) fails. This commit adds check if failed command is really some of copy back related commands or something already reported. 
Except from this it makes enqueueImp for mem copy host command handle exception instead of ignoring and bypassing (MemoryManager operations return void and throws exceptions) to enable proper enqueueCommand results handling.

### CODE REVIEW

**Comment by KseniyaTikhomirova** [comment]
in addition to description - I will create a task for proper handling of MemoryManager operations in enqueueImp for other commands. I am really confident current behavior with exceptions is not what we expect to have because it makes enqueueCommand error handling and reporting useless.

**Comment by KseniyaTikhomirova** [comment]
would be better to merge https://github.com/intel/llvm/pull/14145 first, so that I could easily update UT with ur api usage.

**Comment by KseniyaTikhomirova** [comment]
it is been a week since this PR was approved and plugin interface removal is still not merged. I think there is no sense in waiting then.

@intel/llvm-gatekeepers this PR is ready for merge, thanks

**Comment by aarongreig** [comment]
we are going to merge https://github.com/intel/llvm/pull/14145 today if you don't mind waiting a little longer

**Comment by KseniyaTikhomirova** [comment]
> we are going to merge #14145 today if you don't mind waiting a little longer

cool, waiting.

**Comment by KseniyaTikhomirova** [comment]
@intel/llvm-gatekeepers hi, this PR is ready for merge, thanks

**Pull request merged**
