### PR TITLE
[SYCL][CUDA] Make plugin specific error return an error

### PR DESCRIPTION
**Pull request by hdelan**
The `UR_RESULT_ADAPTER_SPECIFIC_ERROR` was not returning an error to the SYCL RT which meant all errors were treated as warnings and ignored unless `SYCL_RT_WARNING_LEVEL` is set to geq 2. This changes things so the adapter specific error is now reported as such, meaning all uses `UR_RESULT_ADAPTER_SPECIFIC_ERROR` meant as warnings are now caught as errors.

### CODE REVIEW

**Comment by ldrumm** [comment]
Most of your description should be in the commit message proper. Code looks good to me.

Also, because of how this project has been configured, your mention of steffen will end up in project history. I've tried arguing against that without success, but for now you should treat descriptions on github as if they will end up in git history (because they will)

**Comment by hdelan** [comment]
(Editing after @ldrumm has mentioned we should move conversation out of PR description to avoid contaminating the commit message.)

I am not sure if this is desirable behaviour. @steffenlarsen what do you think?

I have also added a test to check that the `SYCL_PI_CUDA_MAX_LOCAL_MEM_SIZE` env variable can fail reliably.

**Comment by hdelan** [comment]
Sorry I meant the behaviour introduced by this PR. I have actually changed the behaviour so `UR_RESULT_ADAPTER_SPECIFIC_ERROR` can correctly error out if  `setErrorMessage` is called with `UR_RESULT_ADAPTER_SPECIFIC_ERROR` as second arg, and continue if `UR_RESULT_SUCCESS` is second arg. So everything working as intended. 

As a sidenote I think for clarity it might be nice to split `UR_RESULT_ADAPTER_SPECIFIC_ERROR` into two: `UR_RESULT_ADAPTER_SPECIFIC_ERROR` and `UR_RESULT_ADAPTER_SPECIFIC_WARNING` so the semantics of `setErrorMessage` was a bit clearer.

**Review by steffenlarsen — APPROVED** [review]
Good catch! I believe this was indeed the intended behavior. Tag @smaslov-intel on his thoughts as well as for the split error code for distinguishing between warnings and errors.

**Review by jchlanda — APPROVED** [review]
👍 for error/warning split

**Comment by hdelan** [comment]
https://github.com/oneapi-src/unified-runtime/issues/762

**Comment by steffenlarsen** [comment]
@intel/dpcpp-l0-pi-reviewers approval is missing. Friendly ping.

**Review by smaslov-intel — APPROVED** [review]

**Review by smaslov-intel — APPROVED** [review]

**Comment by JackAKirk** [comment]
@intel/llvm-gatekeepers can this now be merged?

**Pull request merged**
