### PR TITLE
[SYCL][Test E2E] Temporarily disabled due to GPU hanging on Gen12+

### PR DESCRIPTION
**Pull request by myler**

### CODE REVIEW

**Comment by myler** [comment]
@AlexeySachkov please help to review.

**Comment by myler** [comment]
@intel/dpcpp-esimd-reviewers 
This PR is to disable one test, CI failures are unrelated. Please help to merge.

**Review by turinevgeny — APPROVED** [review]

**Comment by turinevgeny** [comment]
@intel/llvm-gatekeepers, according to @myler, the patch is ready for landing.

**Comment by aelovikov-intel** [comment]
Failures can be ignored here because nightly toolchain is used for PR changing just E2E tests.

**Pull request merged**
