### PR TITLE
[GHA] Uplift Linux GPU RT version to 23.22.26516.18

### PR DESCRIPTION
**Pull request by bb-sycl**
Scheduled drivers uplift

### CODE REVIEW

**Comment by aelovikov-intel** [comment]
> Do you know anything about the rest of the failures

I don't see anything else infrastructure-related. What failures are you talking about?

**Comment by bader** [comment]
> > Do you know anything about the rest of the failures
> 
> I don't see anything else infrastructure-related. What failures are you talking about?

The failures on Windows and AMD/HIP.

**Comment by aelovikov-intel** [comment]
> The failures on Windows and AMD/HIP.

Couple of failed tests do not indicate anything infrastructure related. What am I missing?

**Comment by bader** [comment]
> > The failures on Windows and AMD/HIP.
> 
> Couple of failed tests do not indicate anything infrastructure related. What am I missing?

I don't claim that these failures are "infrastructure related" (at the same time I don't see any proofs that they are not), I'm just asking if you know anything about these failures. I'm asking because I don't expect them to be caused by the PR changes.

@bb-sycl, please, file bug reports for the tests failing on Windows and AMD/HIP and disable them in CI to pass pre-commit checks.

**Review by aelovikov-intel — APPROVED** [review]

**Pull request merged**
