### PR TITLE
 [SYCL][NATIVECPU] Fix missing declarations for broadcast and shuffle operations

### PR DESCRIPTION
**Pull request by coldav**
Multiple declarations were missing for shuffle and broadcast operations,  in particular work group broadcast ones. This adds them.

### CODE REVIEW

**Comment by dm-vodopyanov** [comment]
@coldav, hello, please follow https://github.com/intel/llvm/blob/sycl/sycl/doc/developer/ContributeToDPCPP.md#commit-message

**Comment by coldav** [comment]
> @coldav, hello, please follow https://github.com/intel/llvm/blob/sycl/sycl/doc/developer/ContributeToDPCPP.md#commit-message

This should be done now.

**Comment by dm-vodopyanov** [comment]
> > @coldav, hello, please follow https://github.com/intel/llvm/blob/sycl/sycl/doc/developer/ContributeToDPCPP.md#commit-message
> 
> This should be done now.

Thank you. 

Should there be some tests in the patch?

**Comment by coldav** [comment]
> > > @coldav, hello, please follow https://github.com/intel/llvm/blob/sycl/sycl/doc/developer/ContributeToDPCPP.md#commit-message
> > 
> > 
> > This should be done now.
> 
> Thank you.
> 
> Should there be some tests in the patch?

No, I think e2e covers quite well, along with sycl cts.

**Comment by dm-vodopyanov** [comment]
> > > > @coldav, hello, please follow https://github.com/intel/llvm/blob/sycl/sycl/doc/developer/ContributeToDPCPP.md#commit-message
> > > 
> > > 
> > > This should be done now.
> > 
> > 
> > Thank you.
> > Should there be some tests in the patch?
> 
> No, I think e2e covers quite well, along with sycl cts.

This patch adds new functionality, were there any e2e and/or CTS tests that failed due to lack of this?

**Comment by coldav** [comment]
> > > > > @coldav, hello, please follow https://github.com/intel/llvm/blob/sycl/sycl/doc/developer/ContributeToDPCPP.md#commit-message
> > > > 
> > > > 
> > > > This should be done now.
> > > 
> > > 
> > > Thank you.
> > > Should there be some tests in the patch?
> > 
> > 
> > No, I think e2e covers quite well, along with sycl cts.
> 
> This patch adds new functionality, were there any e2e and/or CTS tests that failed due to lack of this?

For native cpu yes, there were multiple errors from native cpu both on SYCL CTS and e2e (shown as link errors).

**Review by PietroGhg — APPROVED** [review]

**Comment by coldav** [comment]
@intel/llvm-gatekeepers please merge.

**Pull request merged**
