### PR TITLE
[SYCL][libdevice] Add bfloat16 imf utils.

### PR DESCRIPTION
**Pull request by jinge90**
Signed-off-by: jinge90 <ge.jin@intel.com>
This PR adds a new SYCL device library for bf16 type. Some bf16 util functions will be supported via this new added device library. This patch includes fundamental changes to add this bf16 device library and provide necessary conversion functions between fp32 and bf16 types, some trival math functions are also provided.
Currently, we use fp32 to emulate all those fb16 functions, so the bf16 sycl device library doesn't need native bf16 support.

### CODE REVIEW

**Comment by jinge90** [comment]
Hi, @zettai-reido and @akolesov-intel
Although this patch is a draft, I'd like to invite you to take a rough look to see if it meets our requirement to implement bf16 functions based on fp32.

Thanks very much.

**Comment by akolesov-intel** [comment]
The draft looks good for me so far, thank you!

**Review by akolesov-intel — APPROVED** [review]

**Comment by jinge90** [comment]
Hi, @intel/dpcpp-clang-driver-reviewers , @intel/dpcpp-tools-reviewers , @intel/llvm-reviewers-runtime 
Could you help review this patch?

Thanks very much.

**Review by mdtoguchi — APPROVED** [review]

**Comment by jinge90** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1364

**Comment by jinge90** [comment]
Hi, @intel/dpcpp-tools-reviewers 
Could you take a look at this patch?

Thanks very much.

**Comment by jinge90** [comment]
Hi, @asudarsa 
Could you take a look at this patch?

Thanks very much.

**Comment by jinge90** [comment]
Hi, @pvchupin @intel/dpcpp-tools-reviewers 
Could you take a look at this patch?

Thanks very much.

**Comment by jinge90** [comment]
Hi, @pvchupin and @intel/dpcpp-tools-reviewers 
Kind ping~

Thanks very much.

**Review by asudarsa — COMMENTED** [review]
Looks ok to me. There are some empty .o and .obj files in test/Driver directory. Can you please check and comment if they need to be removed?
Thanks

**Comment by jinge90** [comment]
> Looks ok to me. There are some empty .o and .obj files in test/Driver directory. Can you please check and comment if they need to be removed? Thanks

Hi, @asudarsa 
This empty files are required by clang lit test. Those tests aim to test behavior of linking libdevice files as expected, we  must build both clang and libdevice to run those clang lit tests if without those empty files, otherwise, error such as "no such file" will be reported by clang and lead to lit test failure.

Thanks very much for the review.

**Review by asudarsa — APPROVED** [review]
Thanks for clarification. LGTM.

**Comment by jinge90** [comment]
Hi, @pvchupin 
Could you help merge this patch?
Thanks very much.

**Pull request merged**
