### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW03)

### PR DESCRIPTION
**Pull request by KornevNikita**
LLVM: llvm/llvm-project@debfa43
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@3ff87c3

### CODE REVIEW

**Comment by KornevNikita** [comment]
Now there are ~10k failed tests due to lack of default opaque-pointers support, so it make take some time to fix them all.

**Comment by bader** [comment]
> Now there are ~10k failed tests due to lack of default opaque-pointers support, so it can take some time to fix them all.

I don't think we should manually modify all these tests. 
@jcranmer-intel, do you think we can cherry-pick your patches pending the review and switch to opaque-pointers by default in this repository?

**Comment by KornevNikita** [comment]
@jcranmer-intel Hi! I believe you have much work to do regarding opaque pointers problem. So, just curious - is there any ETA about intel/llvm?

**Comment by bader** [comment]
@KornevNikita, we merged https://github.com/intel/llvm/commit/4e8e9f0c2b47a9d6afe2328058aa6be4e3cbfff5. Could you update the validation status, please?

**Comment by KornevNikita** [comment]
Hi @intel/dpcpp-cfe-reviewers! Could you please check if the last commit ([c31c4e6](https://github.com/intel/llvm/pull/8053/commits/c31c4e6e3de3a875095c1ad7913a9f05a769f828)) is ok? It was hitting the assertion in https://github.com/llvm/llvm-project/blob/main/clang/lib/Basic/DiagnosticIDs.cpp#L158

**Comment by KornevNikita** [comment]
@bader @jcranmer-intel there are stiil >10k failed tests locally even with the patch. The main reason - some tools (such as opt, llc etc) still throw warning "ptr type is only supported in -opaque-pointers mode".

**Comment by smanna12** [comment]
> Hi @intel/dpcpp-cfe-reviewers! Could you please check if the last commit ([c31c4e6](https://github.com/intel/llvm/pull/8053/commits/c31c4e6e3de3a875095c1ad7913a9f05a769f828)) is ok? It was hitting the assertion in https://github.com/llvm/llvm-project/blob/main/clang/lib/Basic/DiagnosticIDs.cpp#L158

@KornevNikita, Use the patch that @mdtoguchi send me to fix build issues won sycl-web instead

```
diff --git a/clang/include/clang/Basic/DiagnosticIDs.h b/clang/include/clang/Basic/DiagnosticIDs.h
index a6a4d52ce7d6..5cce3b3b9108 100644
--- a/clang/include/clang/Basic/DiagnosticIDs.h
+++ b/clang/include/clang/Basic/DiagnosticIDs.h
@@ -31,7 +31,7 @@ namespace clang {
     // Size of each of the diagnostic categories.
     enum {
       DIAG_SIZE_COMMON        =  300,
-      DIAG_SIZE_DRIVER        =  300,
+      DIAG_SIZE_DRIVER        =  350,
       DIAG_SIZE_FRONTEND      =  150,
       DIAG_SIZE_SERIALIZATION =  120,
       DIAG_SIZE_LEX           =  400,

```

**Comment by jcranmer-intel** [comment]
> @bader @jcranmer-intel there are stiil >10k failed tests locally even with the patch. The main reason - some tools (such as opt, llc etc) throw warning "ptr type is only supported in -opaque-pointers mode".

Did you try reverting https://github.com/llvm/llvm-project/commit/9ed2f14c87174e316de03407442eed2c643f3695 ?

**Comment by KornevNikita** [comment]
@jcranmer-intel oh, yes, now there are only 133 failed tests. As I understand the main part failing due to redundant `-opaque-pointers` flag and some little part due to some real problems. I will try to fix the rest.

**Comment by KornevNikita** [comment]
The main part of test is failing due to llvm-lto2 call.
On example of LTO/Resolution/X86/dead-strip-alias.ll:
llvm-lto2 with `-opaque-pointers` throws:
`llvm/llvm/lib/IR/LLVMContextImpl.cpp:269: void llvm::LLVMContextImpl::setOpaquePointers(bool): Assertion (!OpaquePointers || *OpaquePointers == OP) && "Cannot change opaque pointers mode once set" failed.`
But, without this flag it also fails with:
`llvm-lto2: LTO::run failed: Opaque pointers are only supported in -opaque-pointers mode (Producer: 'LLVM16.0.0git' Reader: 'LLVM 16.0.0git')`
Is there anything I can do to fix it?

**Comment by jcranmer-intel** [comment]
> @jcranmer-intel the main part of test is failing due to llvm-lto2 call. On example of LTO/Resolution/X86/dead-strip-alias.ll: llvm-lto2 with `-opaque-pointers` throws: `llvm/llvm/lib/IR/LLVMContextImpl.cpp:269: void llvm::LLVMContextImpl::setOpaquePointers(bool): Assertion (!OpaquePointers || *OpaquePointers == OP) && "Cannot change opaque pointers mode once set" failed.` But, without this flag it also fails with: `llvm-lto2: LTO::run failed: Opaque pointers are only supported in -opaque-pointers mode (Producer: 'LLVM16.0.0git' Reader: 'LLVM 16.0.0git')` Is there anything I can do to fix it?

It looks like `llvm-lto2` needs to use the `-lto-opaque-pointers` command line option to enable opaque pointers, rather than `-opaque-pointers`.

**Comment by KornevNikita** [comment]
8 failed tests locally, as I understand they are not related to opaque-pointers. I'll try to fix them.

**Comment by dwoodwor-intel** [comment]
I've posted a fix for `LLVM_SPIRV :: extensions/INTEL/SPV_INTEL_function_pointers/alias.ll` in KornevNikita/llvm#3

**Comment by bader** [comment]
@KornevNikita, thanks!

**Comment by bb-sycl** [comment]
Wed 01 Feb 2023 07:08:44 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Wed 01 Feb 2023 07:12:55 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
