### PR TITLE
[SYCL][libdevice]Add imf libdevice functions to do bfloat162integral conversion

### PR DESCRIPTION
**Pull request by jinge90**

### CODE REVIEW

**Comment by jinge90** [comment]
Hi, @xtian-github @zettai-reido @akolesov-intel
This PR includes 48 APIs to do conversions between bfloat16 and integral type, could you take a look?
The corresponding tests which cover all APIs are in https://github.com/intel/llvm-test-suite/pull/1473
Thanks very much.

**Review by akolesov-intel — APPROVED** [review]

**Comment by jinge90** [comment]
Hi, @intel/llvm-reviewers-runtime 
Could you take a look at this PR?
Thanks very much.

**Comment by jinge90** [comment]
Hi, @intel/llvm-reviewers-runtime and @KseniyaTikhomirova 
Kind ping~

Thanks very much.

**Comment by KseniyaTikhomirova** [comment]
sycl RT part LGTM

**Review by KseniyaTikhomirova — APPROVED** [review]

**Comment by jinge90** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1473

**Comment by jinge90** [comment]
Hi, @bader 
Could you help merge this patch?
Thanks very much.

**Pull request merged**
