### PR TITLE
[ESIMD][NFC] Added a comment about honoring integer promotion rules

### PR DESCRIPTION
**Pull request by DenisBakhvalov**

### CODE REVIEW

**Comment by DenisBakhvalov** [comment]
There is a ESIMD/reduction.cpp test failure in the CI, which exposes why there is `auto` in the signature.
I think it's made to honor C++ integer promotion rules, e.g. `short + short -> int`. And `auto` in the signature is to being able to have:
```cpp
simd <short, 32> a;
simd <short, 32> b;
a + b; // yield simd <int, 32>
```

@kychendev , @cmc-rep , please confirm.

**Comment by kychendev** [comment]
Yes, we need to honor integral promotion.

**Review by kbobrovs — COMMENTED** [review]
Denis - can you please add few test cases checking that promotion really happens as expected?
(E2E test to the LLVM test suite)

**Comment by DenisBakhvalov** [comment]
> Denis - can you please add few test cases checking that promotion really happens as expected?
> 
> * E2E test to the LLVM test suite
> * in-tree test which uses std::is_same to test the result of a binary op

OK, will add.

**Comment by DenisBakhvalov** [comment]
> * E2E test to the LLVM test suite

https://github.com/intel/llvm-test-suite/pull/322

> * in-tree test which uses std::is_same to test the result of a binary op

Done.

**Review by kbobrovs — APPROVED** [review]
@rolandschulz, please review

**Comment by rolandschulz** [comment]
Why do you want integer promotion to happen? This seems like a really odd, efficient, and unexpected choice. Of the many other SIMD libraries I'm aware of none does integer promotion. It is inefficient because it means you require extra register space. And because it happens as part of the operator there isn't even a way for the user to manually opt-out of it.

**Comment by DenisBakhvalov** [comment]
> Why do you want integer promotion to happen? This seems like a really odd, efficient, and unexpected choice. Of the many other SIMD libraries I'm aware of none does integer promotion. It is inefficient because it means you require extra register space. And because it happens as part of the operator there isn't even a way for the user to manually opt-out of it.

@kychendev , @cmc-rep , can you comment?

**Comment by DenisBakhvalov** [comment]
According to @kychendev , there are no inefficiencies in the current implementation which does integer promotion. Everything is handled by the backend vector compiler. Also, this is what CM customers are expecting.

**Comment by rolandschulz** [comment]
> there are no inefficiencies in the current implementation which does integer promotion

I wasn't worried that the conversion is inefficient. The inefficient I was referring to is that after a type is promoted it takes more resources (e.g. register space). 

> Also, this is what CM customers are expecting.

We will have both the the GPU specific SIMD type (`esimd::simd`) and the portable types (e.g. `oneapi::simd` / `std::simd`). I think it will be very confusing to users if something as basic as arithmetic promotion is different between the our abstraction layers. @kbobrovs would you agree?

**Comment by DenisBakhvalov** [comment]
> I wasn't worried that the conversion is inefficient. The inefficient I was referring to is that after a type is promoted it takes more resources (e.g. register space and compute cycles operating on wider types).

AFAIU, that's not the case and is handled by the code generation. +@kychendev 

But regarding portable simd types, yes, I agree it's a mismatch. I'll create a meeting to discuss this.

**Comment by kbobrovs** [comment]
As agreed between @rolandschulz, @kychendev , @DenisBakhvalov, auto-integer promotion for simd types will be in effect only under internal option, default will be std::experimental::simd behavior. This PR does not change the behavior, just adds a comment and verifies the current behavior (auto-promotion by default). This will carry over to the future implementation (under option), so approving and merging.

**Pull request merged**
