### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW22)

### PR DESCRIPTION
**Pull request by sys-ce-bb**
LLVM: llvm/llvm-project@40c26ec
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@c2ff406

### CODE REVIEW

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Wed 07 Jun 2023 06:40:47 AM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Wed 07 Jun 2023 06:45:08 AM UTC --- Merge failed with error: Please check whether the PR is mergeable

**Comment by bb-sycl** [comment]
Wed 07 Jun 2023 01:07:02 PM UTC --- Merge failed with error: Comment user is not in llvm_gatekeepers group or doesn't have merge right for target branch. Please contact with admins of the repo if there is any question.

**Comment by bb-sycl** [comment]
Wed 07 Jun 2023 01:09:10 PM UTC --- Merge failed with error: Comment user is not in llvm_gatekeepers group or doesn't have merge right for target branch. Please contact with admins of the repo if there is any question.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Wed 07 Jun 2023 01:58:26 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Wed 07 Jun 2023 02:04:02 PM UTC --- Merge failed with error: Please check whether the PR is mergeable

**Comment by jsji** [comment]
> Wed 07 Jun 2023 02:04:02 PM UTC --- Merge failed with error: Please check whether the PR is mergeable

Is there a log somewhere that we can see *WHY* it is failing?

**Comment by againull** [comment]
> > Wed 07 Jun 2023 02:04:02 PM UTC --- Merge failed with error: Please check whether the PR is mergeable
> 
> Is there a log somewhere that we can see _WHY_ it is failing?

@jsji I've sent an email with details. I wasn't able to reach the log at first so decided to try merging sycl branch.

**Comment by jsji** [comment]
> > > Wed 07 Jun 2023 02:04:02 PM UTC --- Merge failed with error: Please check whether the PR is mergeable
> > 
> > 
> > Is there a log somewhere that we can see _WHY_ it is failing?
> 
> @jsji I've sent an email with details. I wasn't able to reach the log at first so decided to try merging sycl branch.

Thanks @againull . Yes, please merge it manually first if you have permission to do so.

**Comment by bader** [comment]
@aelovikov-intel, FYI. https://github.com/intel/llvm/actions/runs/5201061665/jobs/9380669587?pr=9694

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Thu 08 Jun 2023 05:28:43 AM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Thu 08 Jun 2023 05:33:06 AM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
