### PR TITLE
[SYCL][NFC] Removing "default label in switch" revealed by self build.

### PR DESCRIPTION
**Pull request by zahiraam**

### CODE REVIEW

**Review by smaslov-intel — COMMENTED** [review]
Default cases are very useful for plugin, so we added -Wno-covered-switch-default to sycl/plugins/CMakeLists.txt.

Do you still see the problem? Which?

**Comment by zahiraam** [comment]
> Default cases are very useful for plugin, so we added -Wno-covered-switch-default to sycl/plugins/CMakeLists.txt.
> 
> Do you still see the problem? Which?
Oh! I hadn't merged in the CMakeList.txt. With this a few of them are gone. There is one (so far) that I still see:
sycl/source/detail/device_info.hpp
But adding the flag in sycl/source/CMakeList.txt seems to fix the issue.
In this case for the upcoming one(s) I will instead add the flag in the corresponding CMakeList.

**Comment by smaslov-intel** [comment]
> But adding the flag in sycl/source/CMakeList.txt seems to fix the issue.

I think we didn't agree that we want that flag generally for all of SYCL, so chose to use that for plugins only.
The "default" in sycl/source/detail/device_info.hpp is to be removed.

**Comment by zahiraam** [comment]
> > But adding the flag in sycl/source/CMakeList.txt seems to fix the issue.
> 
> I think we didn't agree that we want that flag generally for all of SYCL, so chose to use that for plugins only.
> The "default" in sycl/source/detail/device_info.hpp is to be removed.

Understood. I will therefore abandon this change. But more will be coming with the default case removed.

**Comment by v-klochkov** [comment]
> > > But adding the flag in sycl/source/CMakeList.txt seems to fix the issue.
> > 
> > 
> > I think we didn't agree that we want that flag generally for all of SYCL, so chose to use that for plugins only.
> > The "default" in sycl/source/detail/device_info.hpp is to be removed.
> 
> Understood. I will therefore abandon this change. But more will be coming with the default case removed.

@zahiraam - is this tracker abandoned? If yes, please close it.

**Pull request closed without merging**
