### PR TITLE
[SYCL] Unify naming convention for devicelib assert

### PR DESCRIPTION
**Pull request by jinge90**
Signed-off-by: gejin <ge.jin@intel.com>

### CODE REVIEW

**Comment by jinge90** [comment]
Hi, @vzakhari and @bader 
Previously, the wrapper library for assert support is "libsycl-crt"(crt means C RT) and the corresponding fallback library is "libsycl-fallback-cassert.spv". It doesn't align with the style of other devicelib such as cmath, complex:
libsycl-cmath.o     libsycl-fallback-cmath.spv/.o cl_intel_devicelib_cmath.

This PR unifies the naming for assert devicelib, now the name becomes:
libsycl-cassert.o libsycl-fallback-cassert.spv/.o cl_intel_devicelib_cassert.

And it seems that we had better group all device library based on C header since each devicelib corresponds a "cl_intel_devicelib_XXX" extension and if underlying runtime plans to support one "cl_intel_devicelib_XX" extension, all functions in corresponding library must be supported.

Thanks very much.

**Comment by vzakhari** [comment]
I am not against it, but I think the idea behind `crt` part of the library was to provide implementation for APIs from the host `libc`.  So at some point we may want to add more APIs somewhere, but there will be no place for it :-)

I also think that the current structure is temporary until we can support "fat" static library linking in all configurations.  When this is ready, we will just have something like `libdevice.a`.

If you want, you can rename it now, but I do not see much value in this.

**Comment by jinge90** [comment]
> I am not against it, but I think the idea behind `crt` part of the library was to provide implementation for APIs from the host `libc`. So at some point we may want to add more APIs somewhere, but there will be no place for it :-)
> 
> I also think that the current structure is temporary until we can support "fat" static library linking in all configurations. When this is ready, we will just have something like `libdevice.a`.
> 
> If you want, you can rename it now, but I do not see much value in this.

Hi, @vzakhari 
Your suggestion is convincing, this change only unifies all lib name but have no real value.
In fact, with "-only-needed", we can merge all wrapper devicelib and all fallback ".o" library, the only problem is we still have to support -fsycl-device-lib=libc,libm.... If it is proved that no users use those options, we can remove them and merge all ".o/.obj" libraries.
Thanks very much.

**Pull request closed without merging**
