### PR TITLE
[NFC][OpaquePtrs] Update SYCLLowerIR tests to use opaque pointers

### PR DESCRIPTION
**Pull request by LU-JOHN**
Update SYCLLowerIR tests to use opaque pointers.

### CODE REVIEW

**Comment by sarnex** [comment]
@asudarsa Hey, the only match I found was [LowerESIMDVecArg](https://github.com/intel/llvm/blob/45fb7aea2d93a26edb8df3cb2d65f2a6aeebf63e/llvm/lib/SYCLLowerIR/ESIMD/LowerESIMDVecArg.cpp#L50). This pass actually is never run if opaque pointers are on, you can see that [here](https://github.com/intel/llvm/blob/45fb7aea2d93a26edb8df3cb2d65f2a6aeebf63e/llvm/tools/sycl-post-link/sycl-post-link.cpp#L611). So I think we are good.

**Comment by asudarsa** [comment]
> @asudarsa Hey, the only match I found was [LowerESIMDVecArg](https://github.com/intel/llvm/blob/45fb7aea2d93a26edb8df3cb2d65f2a6aeebf63e/llvm/lib/SYCLLowerIR/ESIMD/LowerESIMDVecArg.cpp#L50). This pass actually is never run if opaque pointers are on, you can see that [here](https://github.com/intel/llvm/blob/45fb7aea2d93a26edb8df3cb2d65f2a6aeebf63e/llvm/tools/sycl-post-link/sycl-post-link.cpp#L611). So I don't think there's any work to do.
> 
> We can just delete the pass whenever we pull down the change removing `getNonOpaquePointerElementType`.

Ah. Interesting, Thanks so much @sarnex. I wonder why @LU-JOHN is seeing the call to this function in his stack trace above. One thing I noted, the checking condition in the code you pointed to, it has a call to supportsTypedPointers which is also deprecated. We might need a cleanup of sycl-post-link I suppose.
@LU-JOHN, can you please try to sync your branch with latest sycl tip and try to run these tests again?

Thanks

**Comment by sarnex** [comment]
> Wouldn't you get a compilation error if method declaration is removed before all uses?

I meant as part of the pulldown. We can also remove it whenever we enable opaque pointers by default in this repo.

**Comment by sarnex** [comment]
@bader Sure just ping me when it gets merged.

**Comment by asudarsa** [comment]
> pulldown

Thanks @bader. I agree. I think changes might be required across the board here. Here, we have noticed ESIMD lowering and sycl-post-link. Think there will be lot more. All components (SYCL related) might need to respond to this?

Thanks

**Comment by LU-JOHN** [comment]
> Ah. Interesting, Thanks so much @sarnex. I wonder why @LU-JOHN is seeing the call to this function in his stack trace above.

I see the crash when invoking the opt tool, not sycl-post-link:

/SYCLOS/llvm/build/bin/opt < SYCLOS/llvm/llvm/test/SYCLLowerIR/ESIMD/global.ll -passes=LowerESIMD,ESIMDLowerVecArg -S

ESIMDLowerVecArg pass is initialized with opt.cpp:462

  initializeESIMDLowerVecArgLegacyPassPass(Registry);
  
The crash occurs in line 714:

    // The user has asked to use the new pass manager and provided a pipeline
    // string. Hand off the rest of the functionality to the new code for that
    // layer.
    return runPassPipeline(argv[0], *M, TM.get(), &TLII, Out.get(),
                           ThinLinkOut.get(), RemarksFile.get(), Pipeline,
                           PluginList, OK, VK, PreserveAssemblyUseListOrder,
                           PreserveBitcodeUseListOrder, EmitSummaryIndex,
                           EmitModuleHash, EnableDebugify,
                           VerifyDebugInfoPreserve)

**Comment by LU-JOHN** [comment]
SYCLLowerIR/CompileTimePropertiesPass/sycl-properties-alignment-loadstore.ll does not fail before this PR.  Mistaken conclusion is due to a stale build of opt.  Edits to opt.cpp do not trigger a rebuild.  Issue filed in CMPLRLLVM-50206.

**Comment by LU-JOHN** [comment]
@broxigarchen Can you look at the changes in sycl-properties-alignment-loadstore.ll ?   This PR changes:

>  %3 = bitcast i8 addrspace(4)* %2 to i32 addrspace(4)*
>  %4 = load i32, i32 addrspace(4)* %3, align 8
> ; CHECK: load {{.*}}, align 64

to:

> %2 = load i32, ptr addrspace(4) %1, align 8
> ; CHECK: load {{.*}}, align 64

The CHECK no longer passes in this PR.  Is the CHECK still valid?

**Comment by sarnex** [comment]
@LU-JOHN Sure, I just took a look and sorry, I should have been able to figure out the problem without actually debug it lol.

The problem is we are running the pass directly, whereas when actually called from a real compiler run the pass won't get run if opaque pointers are disabled.

So I think the correct fix is to let the test use typed pointers for now and then just delete the test and the pass when we enable opaque pointers by default.

**Comment by sarnex** [comment]
PR to remove LowerESIMDVecArg  https://github.com/intel/llvm/pull/10738, still a draft but will publish once tests pass

**Review by sarnex — APPROVED** [review]
esimd test changes lgtm, i didn't review this from tools pov

**Comment by sarnex** [comment]
@bader ah thanks for requesting review explicitly from tools, i'll do that in the future, i didn't think of doing that

**Comment by broxigarchen** [comment]
> @broxigarchen Can you look at the changes in sycl-properties-alignment-loadstore.ll ? This PR changes:
> 
> > %3 = bitcast i8 addrspace(4)* %2 to i32 addrspace(4)*
> > %4 = load i32, i32 addrspace(4)* %3, align 8
> > ; CHECK: load {{.*}}, align 64
> 
> to:
> 
> > %2 = load i32, ptr addrspace(4) %1, align 8
> > ; CHECK: load {{.*}}, align 64
> 
> The CHECK no longer passes in this PR. Is the CHECK still valid?

Hi. This PR should fix the issue
https://github.com/intel/llvm/pull/10748

**Review by MrSidims — APPROVED** [review]
LGTM

**Comment by sarnex** [comment]
@intel/llvm-gatekeepers Can this one be merged? Here is a comment from @LU-JOHN:

```
It has two approvals, and it has a disabled test that exposed a bug in handling compileTimeProperty alignment with opaque pointers.  This bug is fixed in PR 10748, but PR 10748 should enable the disabled test. (i.e.  PR 10748 is waiting for 10687 to be merged).
```

**Pull request merged**
