### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW36 2024)

### PR DESCRIPTION
**Pull request by iclsrc**
LLVM: llvm/llvm-project@70f3863
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@7dacb7cdedc9c01

### CODE REVIEW

**Comment by jsji** [comment]
This is ready for review.

- [ ] [Fix conflict resoultion in annotations-field.c](https://github.com/intel/llvm/pull/15322/commits/283129afa020377d6466ec699d572b8d03f2a125)
- [ ] [Add nuw in GEP for CodeGenSYCL tests](https://github.com/intel/llvm/pull/15322/commits/3b965b9da9735c1f8de0d9fbbc0137d737f4af6a) 
- [ ] [Partially revert "Add nuw in GEP for CodeGenSYCL tests"](https://github.com/intel/llvm/pull/15322/commits/cb2cc2f78a4fa72765111b481a585b24d8f8c501)
- [ ] [Fix conflict resolution in Ctor for Device Global](https://github.com/intel/llvm/pull/15322/commits/c7b96d36894f7aa07ea1d0af24db975a6d59a22b)
- [ ] [Add nuw in GEP for check_device_code tests](https://github.com/intel/llvm/pull/15322/commits/5f180013c233e9ed2dcf4c85ff779e35cf57989a)

@intel/dpcpp-cfe-reviewers 

- [ ] [XFAIL amdgpu_unsafe_atomics.cpp due to](https://github.com/intel/llvm/pull/15322/commits/f3cf6bd8fead083b090624d8728f76c3feb13485) https://github.com/intel/llvm/commit/b5e63cc533b5e752eb475ac657f09b9bb5eb2373 Tracked in https://github.com/intel/llvm/issues/15376
- [ ] [XFAIL NewOffloadDriver tests](https://github.com/intel/llvm/pull/15322/commits/0b929976514ead9747bc402fb2f60c10d9b1d741) Tracked in https://github.com/intel/llvm/issues/15377 @intel/dpcpp-tools-reviewers

**Comment by jsji** [comment]
@intel/llvm-gatekeepers I think this is ready for merge (with two follow issue opened) .Thanks.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Fri 13 Sep 2024 11:16:51 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Fri 13 Sep 2024 11:21:29 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
