### PR TITLE
[SYCL][FPGA][NFC] LSU builtin test and documentation update

### PR DESCRIPTION
**Pull request by aditikum**
Updating documentation to reflect change to multi_ptr. 
Updating test so it tests device, host ptrs as well as accessor method.

### CODE REVIEW

**Review by romanovvlad — COMMENTED** [review]
LGTM, but would like that @mlychkov takes a look as well.

**Review by mlychkov — APPROVED** [review]
LGTM, thanks.

**Review by romanovvlad — APPROVED** [review]

**Comment by aditikum** [comment]
merged to get this change: https://github.com/intel/llvm/pull/3578 and enable the checks to pass.

**Review by bader — APPROVED** [review]

**Review by romanovvlad — APPROVED** [review]

**Comment by aditikum** [comment]
@bader Anything pending for the merge?

**Comment by bader** [comment]
@intel/dpcpp-specification-reviewers team should approve the spec.
@mkinsner, could you take a look, please?

**Review by mkinsner — APPROVED** [review]

**Pull request merged**
