### PR TITLE
[SYCL][Matrix] Support matrix-tf32 label in testing infrastructure

### PR DESCRIPTION
**Pull request by yubingex007-a11y**

### CODE REVIEW

**Review by aelovikov-intel — APPROVED** [review]
If that's what matrix team wants, let it be.

**Comment by yubingex007-a11y** [comment]
ping? @intel/llvm-gatekeepers

**Comment by yubingex007-a11y** [comment]
@YuriPlyakhin @dkhaldi please approve, i just saw it needs your approval before gatekeeper's merging it

**Review by dkhaldi — APPROVED** [review]
LGTM

**Pull request merged**
