### PR TITLE
[SYCL] Move SPIRV test into proper directory

### PR DESCRIPTION
**Pull request by aelovikov-intel**
Something bad happened during SPIRV pulldown, fix it.

### CODE REVIEW

**Comment by asudarsa** [comment]
I think this is the guilty commit: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/1564

**Comment by aelovikov-intel** [comment]
These

```
Failed Tests (1):
  SYCL :: XPTI/kernel/content.cpp

********************
Unexpectedly Passed Tests (2):

  SYCL :: SubGroup/reduce_spirv13.cpp
  SYCL :: SubGroup/reduce_spirv13_fp64.cpp
```

In OCL Linux testing are unrelated. I'll try to see if they have been reported already.

**Review by asudarsa — APPROVED** [review]
LGTM. Thanks

**Comment by aelovikov-intel** [comment]
https://github.com/intel/llvm-test-suite/pull/1040 seems to take care of the failing test.

**Comment by aelovikov-intel** [comment]
@intel/llvm-gatekeepers  PR is ready.

**Comment by steffenlarsen** [comment]
Seems to need approval from @pvchupin as code owner.

**Review by AlexeySachkov — APPROVED** [review]

**Review by pvchupin — APPROVED** [review]

**Comment by pvchupin** [comment]
@dbudanov-cmplr, can you follow up on this?
Would be good to know how it happened.

**Comment by pvchupin** [comment]
> https://github.com/intel/llvm-test-suite/pull/1040 seems to take care of the failing test.

It used to fail on OpenCL CPU and GPU, but in your testing fails on CPU only.
I hope CPU testing just picked up this change, and GPU didn't. Otherwise we may have different behaviors per target.
Can watch in next PRs.
Tagging @steffenlarsen

**Comment by steffenlarsen** [comment]
> I hope CPU testing just picked up this change, and GPU didn't. Otherwise we may have different behaviors per target. Can watch in next PRs.

I am currently attempting to reproduce the failure.

**Comment by dbudanov-cmplr** [comment]
@pvchupin 

The problem was introduced by commit 36a19b647a03b37126c93d41a26c6defb87dc4e9.
Which is actually a pick of https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/a827fb0
image

The only reasonable explanation of what happened is that there were 2 patches one for lib/SPIRV/SPIRVUtil.cpp which was taken and applied properly. And the second for test/transcoding/SPV_INTEL_joint_matrix/sycl_2020_namespace.ll which was taken relativity to llvm-spirv but applied to llvm.
I'm not sure if this is an automation issues or something else.

**Pull request merged**
