### PR TITLE
[SYCL][libdevice] Use saturated __spirv builtin when convert fp16 to ull

### PR DESCRIPTION
**Pull request by jinge90**

### CODE REVIEW

**Review by steffenlarsen — APPROVED** [review]

**Review by AGindinson — COMMENTED** [review]
IMO similar adjustments would be needed to all `__devicelib_imf_half2<int_type>_<mode>` functions to _guarantee_ that saturated conversions will take place (as long as it's expected from SYCL spec viewpoint)

**Comment by jinge90** [comment]
Hi, @intel/llvm-gatekeepers 
Could you help review and merge this patch?
Thanks very much.

**Comment by aelovikov-intel** [comment]
Hi @jinge90 , I've pushed a change to CI in https://github.com/intel/llvm/pull/10444 to address its effect on this PR's pre-commit behavior. Can you please merge origin/sycl into you PR's branch? Results should be available by the morning time in Europe time zone once gatekeepers from there are online.

**Comment by jinge90** [comment]
> Hi @jinge90 , I've pushed a change to CI in #10444 to address its effect on this PR's pre-commit behavior. Can you please merge origin/sycl into you PR's branch? Results should be available by the morning time in Europe time zone once gatekeepers from there are online.

Hi, @aelovikov-intel 
Already done, but 2 failures still happen and these 2 failures have nothing to do with this PR.
Thanks very much.

**Comment by jinge90** [comment]
Hi, @intel/llvm-gatekeepers 
Pre-ci passed, could you help review and merge this patch?
Thanks very much.

**Pull request merged**
