### PR TITLE
[SYCL][CUDA][libclc] Add software atomics implementations for lower sm versions

### PR DESCRIPTION
**Pull request by t4c1**
Adds software implementations for various atomics for sm versions blow ones where they are supported natively. Now all atomics, except for the ones using system scope are supported regardless of the sm version.

Now `SYCL_USE_NATIVE_FP_ATOMICS` is also defined for CUDA by default.

Closes https://github.com/intel/llvm/issues/5936.

Tested by: https://github.com/intel/llvm-test-suite/pull/985

### CODE REVIEW

**Comment by t4c1** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/985

**Review by elizabethandrews — APPROVED** [review]
FE changes look ok to me

**Review by premanandrao — APPROVED** [review]
FE changes look okay to me.

**Review by steffenlarsen — APPROVED** [review]
LGTM!

**Comment by steffenlarsen** [comment]
Test failures are unrelated.
Precommit:
- SYCL :: Basic/context-with-multiple-devices.cpp
OCL x64 test suite:
- SYCL :: DiscardEvents/invalid_event.cpp

**Pull request merged**
