### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW27)

### PR DESCRIPTION
**Pull request by dwoodwor-intel**
LLVM: llvm/llvm-project@9aaba9d9bb4fc3648a9417820858086b14b6b73e
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@ae904012e2739fa152412e0f1bfc8eb32a808854

### CODE REVIEW

**Comment by dwoodwor-intel** [comment]
These test failures seem to all be caused by 4d3c010f1d012ade0ca36fdd7bc8b8baeb8df1f2, but I'm not sure how to update the tests for this. I'll be getting back to this on Monday, but of course fixes from people more familiar with the cuda target and/or these tests are welcome in the meantime.

**Comment by pvchupin** [comment]
@AerialMantis, could somebody take a look please?

**Comment by npmiller** [comment]
Hello @dwoodwor-intel so I had a quick look, I don't have a full patch yet but the main problem of https://github.com/intel/llvm/commit/4d3c010f1d012ade0ca36fdd7bc8b8baeb8df1f2 seems to be in this part of the patch: https://github.com/intel/llvm/commit/4d3c010f1d012ade0ca36fdd7bc8b8baeb8df1f2#diff-6ffb509f195719a3d311315a823f7f9b222b273a58e6d5a80d251773eead7026L696

You see beforehand it `getInputFilename` was only using the `cubin` for OpenMP, and everything else still got the standard `.o`, but now it is also doing it for SYCL.

Where the problems seem to come from is that in the SYCL toolchain we're by-passing this `getInputFilename` function and simply getting the filename from the action, which means that the extension gets translated to `cubin` in the CUDA toolchain when building `ptxas` commands and such, but it doesn't get translated in the SYCL toolchain when building the `llvm-foreach` commands.

So I think what we need to do here is to make sure that the SYCL toolchain always does, for example `TC.getInputFilename(II)` rather than `II.getFilename()`, that way we should get the correctly transformed filename. And the toolchain class as a default implementation of `getInputFilename` that simply returns `II.getFilename()` for toolchains that don't make use of this.

For example this patch seems to fix the issue for `llvm-foreach` commands built by the SYCL toolchain:
```diff
diff --git a/clang/lib/Driver/ToolChains/SYCL.cpp b/clang/lib/Driver/ToolChains/SYCL.cpp
index 272462ff2260..b4462c8bf219 100644
--- a/clang/lib/Driver/ToolChains/SYCL.cpp
+++ b/clang/lib/Driver/ToolChains/SYCL.cpp
@@ -68,10 +68,10 @@ void SYCL::constructLLVMForeachCommand(Compilation &C, const JobAction &JA,
   // The llvm-foreach command looks like this:
   // llvm-foreach --in-file-list=a.list --in-replace='{}' -- echo '{}'
   ArgStringList ForeachArgs;
-  std::string OutputFileName(Output.getFilename());
+  std::string OutputFileName(T->getToolChain().getInputFilename(Output));
   ForeachArgs.push_back(C.getArgs().MakeArgString("--out-ext=" + Ext));
   for (auto &I : InputFiles) {
-    std::string Filename(I.getFilename());
+    std::string Filename(T->getToolChain().getInputFilename(I));
     ForeachArgs.push_back(
         C.getArgs().MakeArgString("--in-file-list=" + Filename));
     ForeachArgs.push_back(
```

I need to finish fixing this and test it a bit more but hopefully I should be able to get you a full patch for this tomorrow.

**Comment by npmiller** [comment]
Okay, so I think this should be the minimal patch to make it work:

* https://github.com/npmiller/llvm/commit/ccea66d8d304db4888190144952e5c16a0300039

I've tested it a bit on AMD to see if there wasn't any obvious issues with other toolchains but it seems fine.

I'm curious to see how it goes in the CI, please feel free to ping me if the CI flags further issues after this patch is applied.

**Comment by dwoodwor-intel** [comment]
Thanks for the patch, @npmiller! I am seeing a new fail in `Clang :: Driver/sycl-device-lib.cpp`; can you take a look at it?

**Comment by npmiller** [comment]
Aaah of course, this should fix it:
* https://github.com/npmiller/llvm/commit/0f72d923259117e42cc1302156b82d5bbbfea38d

**Comment by dwoodwor-intel** [comment]
@npmiller, it looks like there is one problem on AMD in `SYCL :: Reduction/reduction_span_pack.cpp`

**Comment by npmiller** [comment]
I had a quick look, it's not related to the other patch as far as I can tell.

I also couldn't reproduce it on MI100 so I'm not too sure what's going on. We've had such cases in the past, MI100 and the CI GPU are pretty different (32 threads vs 64 threads wavefronts for example, https://github.com/intel/llvm/pull/5386), and I don't have access to a GPU similar to what the CI uses at the moment, so it's difficult to investigate.

Would you be able to try track down which revision broke it like you did for the other bugs? That might give us a lead on what's going on.

**Comment by dwoodwor-intel** [comment]
I'm having a lot of trouble reproducing this too; @pvchupin also tried re-running the CI but we're seeing the same test failure and also a few new cuda ones. I'll have to get back to this on Tuesday.

**Comment by dwoodwor-intel** [comment]
The `SYCL :: Reduction/reduction_span_pack.cpp` failure is being tracked in #6409 and has been temporarily diabled in https://github.com/intel/llvm-test-suite/pull/1079; all other tests are passing. It should be safe to merge this now.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Wed 06 Jul 2022 06:43:59 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Wed 06 Jul 2022 06:47:39 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
