### PR TITLE
[SYCL][Doc] Add NonUniformSubGroup extension

### PR DESCRIPTION
**Pull request by Pennycook**
First draft of an extension exposing support for group functions
and group algorithms in diverged control flow.

Signed-off-by: John Pennycook <john.pennycook@intel.com>

### CODE REVIEW

**Comment by Pennycook** [comment]
This extension is related to the one proposed by Codeplay in https://github.com/intel/llvm/pull/4903.  Opening a draft PR here to facilitate discussion and comparison of alternative designs.

**Comment by FMarno** [comment]
Hi John,
Thanks for your comments on the PR I put up for Codeplay.

Could you explain the benefit of templating the non_uniform_sub_group class?

**Comment by Pennycook** [comment]
> Thanks for your comments on the PR I put up for Codeplay.

You're very welcome!  Thanks for working on the proposal; I think this is important functionality to expose in SYCL.


> Could you explain the benefit of templating the non_uniform_sub_group class?

Our thinking here was driven primarily by SPIR-V, although we've tried to think about how things map to CUDA intrinsics as well.  The idea was that an implicit non-uniform sub-group (selected via control flow, hardware divergence mechanism, etc) might require a different implementation than an explicit non-uniform sub-group (selected by the user).

For the implicit case, the SPIR-V implementation could be as simple as forwarding to one of the `OpGroupNonUniform*` instructions.  Something like `reduce(non_uniform_sub_group<group_members::active_at_construction>, float, plus<>())` could be a thin wrapper around `OpGroupNonUniformFAdd`, which is defined as applying only to the active work-items.  Active here means "took the same control flow", and so an implementation doesn't need to do any additional tracking of group state in the headers.   My understanding is that CUDA provides different convergence guarantees, so an implementation would need to store some representation of which work-items encountered the constructor.

For the explicit case, every implementation would need to store the mask provided by the user.  In the SPIR-V case, we may also need to generate different code -- there aren't any SPIR-V instructions that accept an explicit mask, and we'll need to find a way to generate `OpGroupNonUniform*` instructions that correctly handles complicated corner cases (e.g. work-items on the same control flow path have different mask values).

**Comment by FMarno** [comment]
So does that mean that `OpGroupNonUniformFAdd` doesn't give you a choice in the participating work-items? It will just use the currently active work-items, so no bit mask is used?

One of the motivating examples for our proposal comes from [here](https://developer.nvidia.com/blog/using-cuda-warp-level-primitives/), specifically under the "Opportunistic Warp-level Programming" heading. In this example (listing 9) the threads are grouped together since they are all active when they execute `__activemask()` and then that group is maintained throughout the rest of the function so they can all perform the atomic together (reducing contention) but also not wait for all the threads of the warp. If you are not maintaining some kind of state detailing the members of the group, this doesn't seem possible. Of course, this is maybe not an issue if SPIR-V doesn't allow for divergence in a case like this.

I suppose that might all the related to your explicit case, since you somehow need to select the work-items to participate in the operation.

**Comment by Pennycook** [comment]
> So does that mean that `OpGroupNonUniformFAdd` doesn't give you a choice in the participating work-items? It will just use the currently active work-items, so no bit mask is used?

That is my understanding, yes.  You can see that the definition [here](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#OpGroupNonUniformFAdd) says that the instruction involves the "active invocations" implicitly.  There's a `ClusterSize` argument that allows for some explicit subsetting, but it's not a general-purpose mask.

> One of the motivating examples for our proposal comes from [here](https://developer.nvidia.com/blog/using-cuda-warp-level-primitives/), specifically under the "Opportunistic Warp-level Programming" heading. In this example (listing 9) the threads are grouped together since they are all active when they execute `__activemask()` and then that group is maintained throughout the rest of the function so they can all perform the atomic together (reducing contention) but also not wait for all the threads of the warp. If you are not maintaining some kind of state detailing the members of the group, this doesn't seem possible. Of course, this is maybe not an issue if SPIR-V doesn't allow for divergence in a case like this.
>
> I suppose that might all the related to your explicit case, since you somehow need to select the work-items to participate in the operation.

Thanks for sharing the example.  I agree that in this case it's more related to the explicit example, because the mask is not _just_ the active mask, but represents the set of work-items operating on the same address.

If the example were simpler -- say, you knew that all the addresses were the same but still wanted the opportunistic execution -- it might help to see why the implicit group is useful.  Note that we were careful to say "active at construction" and not "active".  So you could write a snippet like:

```c++
auto active_group = it.get_non_uniform_sub_group();
auto sum = reduce_over_group(active_group, ...);
if (active_group.leader()) {
  atomic_ref(...) += sum;
}
group_barrier(active_group);
```

This could have been expressed via an explicitly masked group, but it's simpler without.

We think that the SPIR-V expression is natural here, and follows from the way the user wrote the code (i.e. once a user has created a group, it's their responsibility to use it in control flow that is uniform for all the work-items in that group).  You're right that in the CUDA case you'd need to store the result of `__activemask()`, but that could be an implementation detail.

Is your concern that different implementations might end up with different representations of the groups in the headers?

**Comment by FMarno** [comment]
I would say my bigger concern is that I'm unsure exactly how useful the implicit `non_uniform_sub_group` is if you can't guarantee which work-items will participate in a given operation. If it's down to the user to use uniform control flow then the group seems a bit like false hope. Even in your example you have divergence to do the atomic add.

In general I think things like `OpGroupNonUniformFAdd` only make sense for architecture where sub-groups always operate in lockstep.

**Comment by Pennycook** [comment]
> I would say my bigger concern is that I'm unsure exactly how useful the implicit `non_uniform_sub_group` is if you can't guarantee which work-items will participate in a given operation. If it's down to the user to use uniform control flow then the group seems a bit like false hope. Even in your example you have divergence to do the atomic add.

I may be wrong about this -- and I'm still trying to wrap my head around all the corner cases -- but I don't think the requirement here is stronger than the mask requirement.  The call to the `group_barrier` occurs after the divergence, and control flow at that point has converged again.  (I understand not all hardware works this way, and I also appreciate that a lot of this is hand-wavy.)  Even if the user has an explicit mask representing the set of work-items that were active at some point in the past, I would expect that they can't ignore control flow -- doesn't the user still need to ensure that all of the work-items in the mask encounter the same operations in the same order to avoid deadlocks or weird results?

> In general I think things like `OpGroupNonUniformFAdd` only make sense for architecture where sub-groups always operate in lockstep.

I definitely agree that this is the easiest case to support, but I think the `OpGroupNonUniform` instructions are still implementable on other architectures.

All of this stuff is very complicated, especially when considering portability across architectures.  The discussion across these two PRs has convinced me that we need more implementation experience with these sorts of ideas if we hope to design an abstraction that works well everywhere.

**Comment by bader** [comment]
@rolandschulz, should we keep this PR open? I think the discussion is not over yet. Right?

**Comment by crtrott** [comment]
@Pennycook what is the status of this, as far as we can tell this is still causing us issues on the Kokkos side, leading to deadlocking code.

**Comment by Pennycook** [comment]
@crtrott: We've recently introduced a new proposal (https://github.com/intel/llvm/pull/6169) that replaces this one. It's intended to be pretty flexible, and hopefully it will address the Kokkos use-cases.  It would be great if you could take a look.

I've just got back from an extended leave, so I'm not caught up yet on implementation status.

**Pull request closed without merging**
