### PR TITLE
[SYCL] Add imf simd emulation APIs to sycl_ext_intel_math

### PR DESCRIPTION
**Pull request by jinge90**
CUDA math provides a series of simd intrinsic: https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__INTRINSIC__SIMD.html#group__CUDA__MATH__INTRINSIC__SIMD
We provided corresponding APIs in SYCL libdevice which emulates the behaviors of these CUDA simd intrinsic.
The PR  adds these APIs to sycl_ext_intel_math header file, so users can invoke them when porting CUDA code to SYCL.

### CODE REVIEW

**Comment by jinge90** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1587

**Comment by jinge90** [comment]
Hi, @sergey-semenov and @intel/llvm-reviewers-runtime 
Could you take a look at this PR?
Thanks very much.

**Comment by jinge90** [comment]
> Is this API covered by an existing extension document?
> 
> The changes themselves LGTM.

Hi, @sergey-semenov 
We are going to provide doc to cover all APIs in sycl_ext_intel_math namespace.
Thanks very much.

**Review by sergey-semenov — APPROVED** [review]

**Comment by jinge90** [comment]
Hi, @intel/llvm-gatekeepers 
Could you help review and merge this PR?
Thanks very much.

**Pull request merged**
