### PR TITLE
[SYCL-MLIR] Merge from intel/llvm sycl branch

### PR DESCRIPTION
**Pull request by whitneywhtsang**
Please only review https://github.com/intel/llvm/pull/8600/commits/1e90026030f410d702b9b060d3e74f45d1f3abcf, and 
```
CONFLICT (content): Merge conflict in mlir/include/mlir/Dialect/GPU/IR/GPUOps.td
CONFLICT (content): Merge conflict in mlir/lib/Conversion/FuncToLLVM/FuncToLLVM.cpp
CONFLICT (content): Merge conflict in mlir/lib/Dialect/LLVMIR/IR/LLVMDialect.cpp
```

Reverted https://github.com/intel/llvm/commit/02f9cf9266c35795aa44ded0c37f0c44d8c49069, as it forces to use opaque pointers.

Will remove `Plugin/interop-opencl-make-kernel-bundle.cpp` and `Basic/gpu_max_wgs_error.cpp` from xfail.

Please do not squash and merge this PR.

### CODE REVIEW

**Comment by sommerlukas** [comment]
Looks good overall, just one question: What's the reason to switch from `FailureOr<MemoryAccessMode>` to plain `MemoryAccessNode` in `SYCLOpTypes.{h,cpp}`? Some upstream API change?

**Comment by victor-eds** [comment]
> Looks good overall, just one question: What's the reason to switch from `FailureOr<MemoryAccessMode>` to plain `MemoryAccessNode` in `SYCLOpTypes.{h,cpp}`? Some upstream API change?

By looking [at the docs](https://mlir.llvm.org/docs/DefiningDialects/Operations/#custom-directives), this change seems to be correct. However, I don't see at which point did this change. 

Note that this will be obsolete when we switch to defining these attributes as [enum attributes](https://mlir.llvm.org/docs/DefiningDialects/Operations/#enum-attributes) (builtin parser). I have that in the pipeline.

**Comment by etiotto** [comment]
LGTM. Now we have more test passing. Thanks @whitneywhtsang !

**Review by etiotto — APPROVED** [review]

**Comment by etiotto** [comment]
Guys I have asked the MLIR folks whether they are willing to revert their breaking change.  See https://reviews.llvm.org/rG02f9cf9266c35795aa44ded0c37f0c44d8c49069 and subscribe to the issue to follow the conversation (and weight in).

**Comment by etiotto** [comment]
> > Guys I have asked the MLIR folks whether they are willing to revert their breaking change. See https://reviews.llvm.org/rG02f9cf9266c35795aa44ded0c37f0c44d8c49069 and subscribe to the issue to follow the conversation (and weight in).
> 
> I get that this would avoid some work right now, but the switch probably is inevitable, right?
> 
> Currently, status is:
> 
> > Typed pointers are not supported on the main branch as a matter of policy. Fixes for typed pointer support are not accepted. Typed pointer support code may be removed without notice at any time.
> 
> IIUC, typed pointers will defacto be [unsupported with LLVM 17](https://llvm.org/docs/OpaquePointers.html#version-support), so it might be a matter of weeks/months before that happens.

Yes I actually missed that LLVM 17 (in principle) no longer allows typed pointers. So we (and the DPC++ compiler as well) will need to switch.

**Comment by whitneywhtsang** [comment]
Created https://github.com/intel/llvm/issues/8616 to handle opaque pointers.

**Pull request merged**
