### PR TITLE
[SYCL][XPTI] Fix using xptifw in external projects

### PR DESCRIPTION
**Pull request by pbalcer**
Currently, xptifw, when built outside of SYCL, downloads its own copy
of the googletest framework. This leads to target name collisions
when xptifw is included in other CMake projects (e.g., unified runtime), so add an option to disable tests in xptifw.

This project also hardcodes the location for the XPTI proxy implementation. This prevents its use outside of SYCL, so allow setting external xpti dir in xptifw.

### CODE REVIEW

**Review by aelovikov-intel — APPROVED** [review]

**Comment by bader** [comment]
> We are in the process of integrating XPTI into Unified Runtime (UR), and we need xptifw dispatcher to run tests. We had two issues; see commits for details.

@pbalcer, note that all PR commits are squashed during merge. If you need to have two separate commits in git log, please, open two PRs.

**Comment by pbalcer** [comment]
I'm OK with these commits being squashed during merge - they are tiny fixes localized in a single file.

**Comment by bader** [comment]
> I'm OK with these commits being squashed during merge - they are tiny fixes localized in a single file.

Good. It'd be better if we copy individual commit messages to the PR description (which will be a log message body for the squashed commit).

**Comment by pbalcer** [comment]
I didn't know github would use PR's description as the commit message when squashing. Neat :)

Done. Thanks for help @bader.

**Comment by bader** [comment]
> I didn't know github would use PR's description as the commit message when squashing. Neat :)
> 
> Done. Thanks for help @bader.

This is the policy established in this repository. See https://github.com/intel/llvm/blob/sycl/CONTRIBUTING.md#pull-request
GitHub can use PR title/description, but there are a couple of other options. You can learn more from the documentation:

* https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#merge-message-for-a-squash-merge
* https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests.

**Pull request merged**
