### PR TITLE
[SYCL] Fix naming of SSA registers in SYCL matrix tests

### PR DESCRIPTION
**Pull request by hdelan**
Some sycl tests were failing in docker because of the naming of SSA registers. This patch fixes that

### CODE REVIEW

**Comment by hdelan** [comment]
Ping @intel/llvm-reviewers-runtime

**Review by steffenlarsen — APPROVED** [review]
Looks reasonable! Could you please update the title of this PR to be a little more informative?

**Comment by hdelan** [comment]
Thanks @steffenlarsen yep have done

**Comment by bader** [comment]
@hdelan, please, resolve merge conflicts.

**Pull request merged**
