### PR TITLE
[SYCL-PTX] Fix geometric and common builtin categories

### PR DESCRIPTION
**Pull request by Naghasan**
Remove old forward declared SPIR-V builtin from the geometric and common categories.
Update the binding file using the header generator.
Add relevant binding test.
Remove XFAIL from related SYCL tests.

Note there is a dependency with #1828 but can be reviewed independently.

Signed-off-by: Victor Lomuller <victor@codeplay.com>

### CODE REVIEW

**Comment by bader** [comment]
LGTM

**Comment by bader** [comment]
@Naghasan, could you resolve merge conflicts, please?

**Comment by bader** [comment]
@Naghasan, could you resolve merge conflicts, please?

**Comment by Naghasan** [comment]
I rebased the patch

**Comment by Naghasan** [comment]
@bader I have rebased to tip, I'm sure why the build failed before. Last version compiles fine on my side.

**Comment by bader** [comment]
> @bader I have rebased to tip, I'm sure why the build failed before. Last version compiles fine on my side.

According to the logs `_CLC_OVERLOAD` is not defined in `unary_decl.inc`, which is included from `sqrt.cl`.
```
In file included from /localdisk2/sycl_ci/buildbot/worker/Lit_With_Cuda/llvm.src/libclc/generic/libspirv/math/sqrt.cl:9:
In file included from /localdisk2/sycl_ci/buildbot/worker/Lit_With_Cuda/llvm.src/libclc/generic/include/math/clc_sqrt.h:3:
In file included from /localdisk2/sycl_ci/buildbot/worker/Lit_With_Cuda/llvm.src/libclc/generic/include/clc/math/gentype.inc:7:
/localdisk2/sycl_ci/buildbot/worker/Lit_With_Cuda/llvm.src/libclc/generic/include/clc/math/unary_decl.inc:1:1: error: unknown type name '_CLC_OVERLOAD'
_CLC_OVERLOAD _CLC_DECL __CLC_GENTYPE __CLC_FUNCTION(__CLC_GENTYPE x);
^
/localdisk2/sycl_ci/buildbot/worker/Lit_With_Cuda/llvm.src/libclc/generic/include/clc/math/unary_decl.inc:1:24: error: expected ';' after top level declarator
_CLC_OVERLOAD _CLC_DECL __CLC_GENTYPE __CLC_FUNCTION(__CLC_GENTYPE x);
                       ^
```

**Comment by Naghasan** [comment]
Oh I see what happened now, not all the target where built on my side and there is a `sqrt` specialization for the ptx side. Thus hiding the issue on my side ...

This is fixed.

**Pull request merged**
