### PR TITLE
[SYCL] Print supported SG sizes in sycl-ls --verbose

### PR DESCRIPTION
**Pull request by aelovikov-intel**
And use that as dynamic features in our SYCL End-to-End tests framework.

### CODE REVIEW

**Comment by steffenlarsen** [comment]
> I'm not sure if that really belongs to `sycl-ls` (and if so, what else does) so uploading it mostly to start the discussion.

I definitely think it does! Supported sub-group sizes share some behavior with aspects and is a device-specific thing. Having an easy way to get it for a given device without having to write a custom program every time could be super-useful!

**Comment by gmlueck** [comment]
This seems like a useful extension.  Do we have any documentation for the "REQUIRE" syntax that we use in our e2e tests?  It seems like that would be useful for people writing tests, otherwise they won't know about this new feature.

**Comment by aelovikov-intel** [comment]
> Do we have any documentation

I'm in the middle of changing the LIT infrastructure in a significant way and will work on updating the docs once everything is finalized and implemented (probably about a week or two from today).

**Comment by Pennycook** [comment]
> I definitely think it does! Supported sub-group sizes share some behavior with aspects and is a device-specific thing. Having an easy way to get it for a given device without having to write a custom program every time could be super-useful!

I agree.  Users are already requesting this, and so we could even consider this the first step towards implementing https://github.com/intel/llvm/issues/9104.

**Review by gmlueck — APPROVED** [review]

**Comment by aelovikov-intel** [comment]
@intel/dpcpp-esimd-reviewers , can you take a look at the missing esimd_emulator's support for this?

**Pull request merged**
