### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW11)

### PR DESCRIPTION
**Pull request by vmaksimo**
LLVM: llvm/llvm-project@bb50d47a40f66
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@1538cf59bb1f4db549cd7ec9ebb65b5db1875144

### CODE REVIEW

**Comment by vmaksimo** [comment]
Hi @AidanBeltonS! Could you please help with the libclc demangler? 
The build has failed after the community change 64221645a (e.g., see https://github.com/intel/llvm/runs/5478714460?check_suite_focus=true). The OutputBuffer became non-copyable, but demangler actively uses this class as a copiable one.

**Comment by AidanBeltonS** [comment]
> Hi @AidanBeltonS! Could you please help with the libclc demangler? The build has failed after the community change [6422164](https://github.com/intel/llvm/commit/64221645a824f0b70ae130001b37ac01095aa806) (e.g., see https://github.com/intel/llvm/runs/5478714460?check_suite_focus=true). The OutputBuffer became non-copyable, but demangler actively uses this class as a copiable one.

Yes, I can take a look at it and see how to handle the change.

**Comment by vmaksimo** [comment]
> This should fix the build failure. It just changes printNode to use pass by reference instead of a return copy. I have attached the diff to this comment. [printNode.txt](https://github.com/intel/llvm/files/8216555/printNode.txt)

Thank you, @AidanBeltonS!

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Wed 16 Mar 2022 10:48:05 AM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Wed 16 Mar 2022 10:51:41 AM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Comment by vmaksimo** [comment]
The test failures in Jenkins/Precommit caused by infra issue: they have passed after restart: http://llvm-ci.intel.com:8080/blue/organizations/jenkins/SYCL_CI%2Fintel%2FLin%2FBasic_E2E/detail/Basic_E2E/2175/pipeline/

**Pull request merged**
