### PR TITLE
[SYCL][Matrix] Update element_wise_all_ops_tf32_impl.hpp to use consistent dimension names (e.g. M, K, TM, TK).

### PR DESCRIPTION
**Pull request by arnamoy10**

### CODE REVIEW

**Review by dkhaldi — APPROVED** [review]
LGTM

**Comment by aelovikov-intel** [comment]
We don't have any testing results on Intel GPU. Please merge origin/sycl to restart the testing.

**Comment by arnamoy10** [comment]
> We don't have any testing results on Intel GPU. Please merge origin/sycl to restart the testing.

Sorry I did not understand the comment. Could you please clarify?

**Comment by aelovikov-intel** [comment]
image

**Review by YuriPlyakhin — APPROVED** [review]

**Comment by YuriPlyakhin** [comment]
@intel/llvm-gatekeepers, all green, please, merge. Thanks.

**Comment by dm-vodopyanov** [comment]
@arnamoy10 please, avoid force-pushing in this project. We lose history of what was changed from commit to commit inside a single PR.

**Pull request merged**
