### PR TITLE
[UR][L0] Make the queue [root-]device appear first in the context

### PR DESCRIPTION
**Pull request by smaslov-intel**

### CODE REVIEW

**Review by jandres742 — APPROVED** [review]

**Comment by smaslov-intel** [comment]
@intel/llvm-gatekeepers : are these known E2E failures on Windows:
>  SYCL :: Annotated_arg_ptr/annotated_arg.cpp
  SYCL :: Annotated_arg_ptr/annotated_ptr.cpp

**Comment by aelovikov-intel** [comment]
Windows testing was completely broken yesterday, and I haven't seen any progress on analysis overnight.

**Comment by smaslov-intel** [comment]
> @intel/llvm-gatekeepers : are these known E2E failures on Windows:
> 
> > SYCL :: Annotated_arg_ptr/annotated_arg.cpp
> > SYCL :: Annotated_arg_ptr/annotated_ptr.cpp

These are unrelated to this PR and tracked in https://github.com/intel/llvm/issues/11224

**Comment by aelovikov-intel** [comment]
> @intel/llvm-gatekeepers : can this be merged without Windows testing result, or what do I do to get those generated?

Our CI was broken for a few days, so I've cancelled multiple runs that would have failed anyway while trying to see if a revert of a particular patch. The revert has been merged since.

CI is better now but it seems it's not 100% healthy yet. You can try to just restart testing but it's not guaranteed to work and might make our job in fully stabilizing CI harder. If you can, please wait and restart later once CI is fully restored.

**Comment by smaslov-intel** [comment]
@intel/llvm-gatekeepers : The Window testing passed now but there is this one fail in HIP testing that cannot be related to my changes to L0 adapter:
> Failed Tests (1):
  SYCL :: AtomicRef/add_generic_local.cpp

Please merge PR.

**Pull request merged**
