### PR TITLE
[SYCL][clang] Fix ivdep attribute in template contexts

### PR DESCRIPTION
**Pull request by Fznamznon**
Several ivdep attributes without safelen argument used to fail if applied inside of a template function. That is because in this case template instantiator passes a pair of expressions to `BuildSYCLIntelIVDepAttr`, first is `nullptr` second is an array argument. Due to incorrect check the attribute was built with wrong arguments and failed correctness check later.

### CODE REVIEW

**Review by premanandrao — APPROVED** [review]
LGTM.

Is there a non-opaque-ptr version of the CodeGenSYCL test?   If not, we should probably create one (not necessarily as part of this PR).

**Comment by Fznamznon** [comment]
> Is there a non-opaque-ptr version of the CodeGenSYCL test?

Oh, yes there is. Should I update it as well? (note: llvm17 doesn't even support non-opaque pointers).

**Comment by premanandrao** [comment]
> > Is there a non-opaque-ptr version of the CodeGenSYCL test?
> 
> Oh, yes there is. Should I update it as well? (note: llvm17 doesn't even support non-opaque pointers).

If llvm17 is cutting over to exclusively opaque pointers, perhaps the risk of not worth it.  I will leave it up to you.

**Comment by Fznamznon** [comment]
> > > Is there a non-opaque-ptr version of the CodeGenSYCL test?
> > 
> > 
> > Oh, yes there is. Should I update it as well? (note: llvm17 doesn't even support non-opaque pointers).
> 
> If llvm17 is cutting over to exclusively opaque pointers, perhaps the risk of not worth it. I will leave it up to you.

I gave it some thought. Actually the fact that llvm 17 doesn't support non-opaque pointers and we still use them puts us at higher risk to encounter bugs related to broken non-opaque pointers, so while they are still used it is better to double check. I updated the test.

**Comment by Fznamznon** [comment]
`SYCL Pre Commit / Linux / SYCL E2E on Intel CPU/GEN9 GPU ` job seems to be stuck for several hours. The latest commit is only different from the first in changes to clang LIT test. All LIT tests passed. `SYCL Pre Commit / Linux / SYCL E2E on Intel CPU/GEN9 GPU ` passed for the first commit.
@intel/llvm-gatekeepers this is ready to merge.

**Review by elizabethandrews — APPROVED** [review]

**Comment by Fznamznon** [comment]
@intel/llvm-gatekeepers ping, please merge.

**Pull request merged**
