### PR TITLE
Revert "Disable VectorCombine pass for SYCL device"

### PR DESCRIPTION
**Pull request by Fznamznon**
This reverts commit 42c68d687865481061c13dcd04947c085fee6a82.

With https://github.com/intel/llvm/pull/7632 and https://github.com/intel/llvm/pull/7673 we don't need to disable it.

### CODE REVIEW

**Review by AlexeySachkov — APPROVED** [review]

**Review by bader — COMMENTED** [review]
It looks like more fixes to ESIMD passes are needed.

**Comment by bader** [comment]
> It looks like more fixes to ESIMD passes are needed.

@Fznamznon, @intel/dpcpp-esimd-reviewers, could you investigate pre-commit failures, please?

**Comment by Fznamznon** [comment]
I will be on vacation starting from tomorrow. I filed internal tracker for ESIMD folks to finalize it.
The fix doesn't seem to be trivial. Apparently LowerESIMD pass makes hard assumptions on which instructions around SPIR-V it can see, and VectorCombine pass breaks them.
I've tried to debug one of the tests - https://github.com/intel/llvm-test-suite/blob/intel/SYCL/ESIMD/vadd_usm_opqptr.cpp , it expects loads from vector spirv global variables to be used only by extractelement instructions, but after the pass, one of the users becomes `%mul.i = shl nuw nsw i64 %3, 5` .

**Comment by bader** [comment]
@Fznamznon, I suggest we sync with the tip of the sycl branch to get up-to-date CI results.

**Comment by bader** [comment]
Failed Tests (1):
  SYCL :: ESIMD/vadd_usm_opqptr.cpp

This is not related to the change. @Fznamznon, am I right?

**Comment by Fznamznon** [comment]
> Failed Tests (1): SYCL :: ESIMD/vadd_usm_opqptr.cpp
> 
> This is not related to the change. @Fznamznon, am I right?

I think it is related. It fails with the same assertion I tried to debug earlier, see https://github.com/intel/llvm/pull/7809#issuecomment-1372357837 .

**Review by bader — CHANGES_REQUESTED** [review]
@Fznamznon, please, fix pre-commit checks.
@v-klochkov, FYI.

**Comment by sarnex** [comment]
@Fznamznon I'm working on this from the ESIMD side and I /think/ I have a fix for the one remaining issue. Do you want me to just submit the ESIMD pass fix or also include reenabling VectorCombine?

**Comment by Fznamznon** [comment]
> @Fznamznon I'm working on this from the ESIMD side and I /think/ I have a fix for the one remaining issue. Do you want me to just submit the ESIMD pass fix or also include reenabling VectorCombine?

I would prefer doing this at the same time in the same PR since last time when fixes to ESIMD were submitted separately we ended up with not all the fixes in place. You can just include reenabling of VectorCombine into your new PR and I will close this one.

**Comment by sarnex** [comment]
@Fznamznon Sure, thanks. For now you can just close this PR

**Pull request closed without merging**
