### PR TITLE
[SYCL][Codegen] Add -opaque-pointers to fix LIT tests

### PR DESCRIPTION
**Pull request by KanRobert**
Guard tests under macro `INTEL_SYCL_OPAQUEPOINTER_READY`

### CODE REVIEW

**Comment by dm-vodopyanov** [comment]
@KanRobert please follow https://github.com/intel/llvm/blob/sycl/sycl/doc/developer/ContributeToDPCPP.md#commit-message for the PR caption

**Review by asudarsa — APPROVED** [review]
LGTM. Just a quick question. Is it not possible to change the test and make it work?

Thanks

**Comment by asudarsa** [comment]
Please also provide a short description (1-2 lines) for such changes.

Thanks

**Comment by KanRobert** [comment]
> LGTM. Just a quick question. Is it not possible to change the test and make it work?
> 
> Thanks

I think it's possible. But since the test is shared with llorg, we should update it in llorg first.

**Pull request merged**
