### PR TITLE
[SYCL-MLIR] Add intrinsics to LLVM dialect

### PR DESCRIPTION
**Pull request by sommerlukas**
Add support for multiple intrinsics to the LLVM dialect.

These intrinsics are present in host LLVM IR, so for full host raising support, they need to be added to the LLVM dialect. 

The following intrinsics are added in this PR:
* `llvm.rint`, `llvm.nearbyint`, `llvm.lround`, `llvm.llround`, `llvm.lrint`, `llvm.llrint`
* `llvm.threadlocal.address`

### CODE REVIEW

**Comment by sommerlukas** [comment]
I intend to create a patch on upstream LLVM for these changes after review and approval here.

**Comment by sommerlukas** [comment]
Another intrinsic relevant for the host raising is `llvm.is.constant`, which was already added to upstream LLVM in https://reviews.llvm.org/D150660. We should be able to use this after the next pulldown.

**Review by etiotto — APPROVED** [review]

**Review by Naghasan — APPROVED** [review]

**Review by whitneywhtsang — APPROVED** [review]

**Comment by sommerlukas** [comment]
Upstream LLVM patches: 
* Rounding intrinsics: https://reviews.llvm.org/D151558
* `threadlocal.address`: https://reviews.llvm.org/D151566

**Comment by sommerlukas** [comment]
Both upstream patches have now been accepted and merged. 
I updated this PR with the changes from the upstream patches, so changes should now be identical.

**Pull request merged**
