### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW30 2024)

### PR DESCRIPTION
**Pull request by iclsrc**
LLVM: llvm/llvm-project@09cbb45edd149d30766c87be4628e4df13f3496d
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@dad1f0eaab8047a4f73c50ed5f3d1694b78aae97

### CODE REVIEW

**Review by aUsABuisnessman — APPROVED** [review]

**Review by aUsABuisnessman — APPROVED** [review]

**Comment by jsji** [comment]
This is ready for review.

Header and API update:

- [ ] [[SYCL] Add Module include after header change](https://github.com/intel/llvm/pull/14813/commits/a1cf771817e0f2752fb08246e588725a28d5bf42)
- [ ] [Add module include after header refactoring](https://github.com/intel/llvm/pull/14813/commits/109efd697b21824095f44b2c621b8c9631be3357)
- [ ] [[ClangLinkerWrapper] Update the CUDA API](https://github.com/intel/llvm/pull/14813/commits/04046b4e7fbc2c5f7c17003394ce233df1bad349)

 @intel/dpcpp-tools-reviewers 

Bug fix/workarounds:
- [ ] [[ClangOffloadWrapper] Disable note section verification for now](https://github.com/intel/llvm/pull/14813/commits/2115a2dcd7093286b63621632e8c2843277f2d1d) @intel/dpcpp-tools-reviewers 
- [ ] [[SYCL] Use MapVector instead of DenseMap to get deterministtic order …](https://github.com/intel/llvm/pull/14813/commits/829781c7f503958d113499aa2ff57c44e527ceef) @intel/dpcpp-cfe-reviewers 



Test updates:
- [ ] [[NFC] Update memcpyopt test due to new opt](https://github.com/intel/llvm/pull/14813/commits/2ac435d842d7b11eb8ddb4b1eaf5702c7ace8dac) @intel/dpcpp-tools-reviewers 
- [ ] [[SYCL][Test] Update ap_fixed test after IR change](https://github.com/intel/llvm/pull/14813/commits/fc235e11463ee14340b2d63e5d338a82cfd2efac)
- [ ] [[SYCL][Test] Fix attr order](https://github.com/intel/llvm/pull/14813/commits/3049520a538f58fea4c7450523546362a9e2a4ab)
- [ ] [[Driver] Fix offload package command line order in test](https://github.com/intel/llvm/pull/14813/commits/600939370a9f87f9a13510987f462e306fb43832)
- [ ] [[Driver] Allow different order of GV in clang-offload-deps.c](https://github.com/intel/llvm/pull/14813/commits/ccdd84ada93346e48c9da2b8b6c64003c2b71d25)
- [ ] [[SYCL][Test] Update CHECK with new range attr](https://github.com/intel/llvm/pull/14813/commits/63051bb659471f6bd9e0e41a6cf4564214b7a568)
- [ ] [[SYCL] Update offload test due to different order](https://github.com/intel/llvm/pull/14813/commits/f00d6c7ed33eb39520250072c5e23758fcfcb8e0)
- [ ] [[Clang] Fix conflict resolution use return instead of break](https://github.com/intel/llvm/pull/14813/commits/2ee0e64d15fefd298d16d7e14f1a7a8acc1664c0)

@intel/dpcpp-cfe-reviewers 

- [ ] [[LLVM-SPIRV] Update test due to EntryPoint customization](https://github.com/intel/llvm/pull/14813/commits/cf4e0b42b37d0bfb359e1eccf32ced16fb794fe3)

@intel/dpcpp-spirv-reviewers 

XFAIL:
- [ ] [[SYCL] Temporarily XFAIL e2e test](https://github.com/intel/llvm/pull/14813/commits/f1a3dc039aeaac96287b5fa771ded5fb0db8bab4)
https://github.com/intel/llvm/issues/14850 opened to track investigation.

**Comment by jsji** [comment]
Ping @intel/dpcpp-cfe-reviewers @intel/dpcpp-spirv-reviewers @intel/dpcpp-tools-reviewers @intel/dpcpp-clang-driver-reviewers

**Review by mdtoguchi — APPROVED** [review]
OK for driver.

**Review by smanna12 — APPROVED** [review]
CFE changes LGTM

**Review by AlexeySachkov — APPROVED** [review]
Would be great to have @maksimsab feedback about `clang-linker-wrapper` changes, but otherwise tools part LGTM

**Comment by jsji** [comment]
@intel/llvm-gatekeepers
AMD/HIP failure is infrastructure issue. I tried to rerun only it for 3 times, unfortunately we can't get it fixed. I don't think we need to re-run all other CIs just for it.

So, I think this is ready for merge, can someone help to issue a `/merge`? THanks.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Thu 08 Aug 2024 07:50:15 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Thu 08 Aug 2024 07:54:39 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
