### PR TITLE
[SYCL] Delete the workaround for wrong s_upsample mangling

### PR DESCRIPTION
**Pull request by imashkov**
Signed-off-by: Ilya Mashkov <ilya.mashkov@intel.com>

### CODE REVIEW

**Comment by imashkov** [comment]
Patch can not be merged yet, fpga emulator test fell. Close this pull request until fix is in runtime.

**Comment by imashkov** [comment]
Same pull request passed all checks in private repo, so after all successful checks here it can be merged

**Comment by imashkov** [comment]
@bader this pull request is ready to be merged, please do it, when you have time.

**Comment by AlexeySachkov** [comment]
> @bader this pull request is ready to be merged, please do it, when you have time.

It wasn't really ready without approval, fixed

**Pull request merged**
