### PR TITLE
[SYCL][ESIMD] Move some ESIMD APIs outside of experimental namespace

### PR DESCRIPTION
**Pull request by sndmitriev**
Signed-off-by: Sergey Dmitriev <serguei.n.dmitriev@intel.com>

### CODE REVIEW

**Comment by sndmitriev** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/892

**Comment by sndmitriev** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/892

**Review by kbobrovs — APPROVED** [review]
LGTM. Please move floor, ceil, trunc out of experimental as a separate patch.

**Comment by kbobrovs** [comment]
@intel/llvm-reviewers-runtime, please review accessor.hpp - just few lines, would really appreciate if you could to this ASAP, as the patch is giant and can have conflicts very soon.

**Comment by sndmitriev** [comment]
Unexpected failures on llvm-test-suite will disappear once https://github.com/intel/llvm-test-suite/pull/892 is merged, '/verify with' testing has completed successfully for that patch.

**Review by vladimirlaz — APPROVED** [review]
accessor.hpp - LGTM

**Review by alexbatashev — APPROVED** [review]

**Review by v-klochkov — APPROVED** [review]

**Comment by dongkyunahn-intel** [comment]
Building with `ESIMD_EMULATOR` support fails (`--enable-esimd-emulator`) as header file path in `pi_esimd_emulator.hpp` is not updated accordingly.

**Pull request merged**
