### PR TITLE
[SPIR-V] Add support for SPV_INTEL_usm_storage_classes extension

### PR DESCRIPTION
**Pull request by MrSidims**
With this extension 2 new Storage Classes are introduced:
DeviceOnlyINTEL and HostOnlyINTEL appropriately mapped on
global_device and global_host SYCL/OpenCL address spaces which
are part of SYCL_INTEL_usm_address_spaces extension.

Co-authored-by: Viktoria Maksimova <viktoria.maksimova@intel.com>

Signed-off-by: Dmitry Sidorov <dmitry.sidorov@intel.com>
Signed-off-by: Viktoria Maksimova <viktoria.maksimova@intel.com>

### CODE REVIEW

**Comment by MrSidims** [comment]
It's a cherry-pick of https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/579

**Comment by MrSidims** [comment]
@bader can I ignore clang-format concerns or I shall apply it to spirv.hpp?

**Comment by bader** [comment]
> @bader can I ignore clang-format concerns or I shall apply it to spirv.hpp?

Isn't clang-formating patches required by the translator project as well?

**Comment by MrSidims** [comment]
> > @bader can I ignore clang-format concerns or I shall apply it to spirv.hpp?
> 
> Isn't clang-formating patches required by the translator project as well?

They are required, but not firing in this case, prove: https://travis-ci.org/github/KhronosGroup/SPIRV-LLVM-Translator/jobs/701976405 . I think that is because spirv.hpp is excluded from clang-format there and it's not clang-formated in general.

**Comment by bader** [comment]
> > > @bader can I ignore clang-format concerns or I shall apply it to spirv.hpp?
> > 
> > 
> > Isn't clang-formating patches required by the translator project as well?
> 
> They are required, but not firing in this case, prove: https://travis-ci.org/github/KhronosGroup/SPIRV-LLVM-Translator/jobs/701976405 . I think that is because spirv.hpp is excluded from clang-format there and it's not clang-formated in general.

I see at least two solutions.
1. We should remove copy of SPIR-V translator project from our source base and use Khronos repository version directly.
2. Apply similar filter to our clang-format check.

**Comment by MrSidims** [comment]
> 
> I see at least two solutions.
> 
> 1. We should remove copy of SPIR-V translator project from our source base and use Khronos repository version directly.
> 2. Apply similar filter to our clang-format check.

In the translator clang-format rules file is just a single line:
 `BasedOnStyle: LLVM`
thus my theory about special rules for spirv.hpp is incorrect. But still there might be differences, with our rules, since in this repo we have wrote them manually. 

Is it possible to merge the patch with a clang-format check failed? I see no required label.

**Comment by bader** [comment]
> > I see at least two solutions.
> > 
> > 1. We should remove copy of SPIR-V translator project from our source base and use Khronos repository version directly.
> > 2. Apply similar filter to our clang-format check.
> 
> In the translator clang-format rules file is just a single line:
> `BasedOnStyle: LLVM`
> thus my theory about special rules for spirv.hpp is incorrect. But still there might be differences, with our rules, since in this repo we have wrote them manually.

I meant "filter" not "rule" - more specifically using this script https://github.com/intel/llvm/blob/sycl/llvm-spirv/utils/check_code_format.sh in this workflow: https://github.com/intel/llvm/blob/sycl/.github/workflows/clang-format.yml#L21.

This should fix your pre-commit checks.

> @bader is it possible to merge the patch with a clang-format check failed? I see no required label.

Yes. Do you want to?

**Comment by MrSidims** [comment]
> > > I see at least two solutions.
> > > 
> > > 1. We should remove copy of SPIR-V translator project from our source base and use Khronos repository version directly.
> > > 2. Apply similar filter to our clang-format check.
> > 
> > 
> > In the translator clang-format rules file is just a single line:
> > `BasedOnStyle: LLVM`
> > thus my theory about special rules for spirv.hpp is incorrect. But still there might be differences, with our rules, since in this repo we have wrote them manually.
> 
> I meant "filter" not "rule" - more specifically using this script https://github.com/intel/llvm/blob/sycl/llvm-spirv/utils/check_code_format.sh in this workflow: https://github.com/intel/llvm/blob/sycl/.github/workflows/clang-format.yml#L21.
> 
> This should fix your pre-commit checks.
> 

Thanks, I'll try to exclude spirv.hpp today.


> > @bader is it possible to merge the patch with a clang-format check failed? I see no required label.
> 
> Yes. Do you want to merge it with failing clang-format check?

Yes, since I'm not planning to apply clang-format to spirv.hpp anyway, hence there will be no changes in the code for this PR.

**Comment by MrSidims** [comment]
(that's quiet interesting, that https://github.com/intel/llvm/blob/sycl/llvm-spirv/utils/check_code_format.sh is the same as https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/master/utils/check_code_format.sh)

**Pull request merged**
