### PR TITLE
[SYCL] Fix DAE by avoiding creation of obsolete device images

### PR DESCRIPTION
**Pull request by AGindinson**
Due to an unintentional copy of the `RTDeviceBinaryImage` object that
was happening in `ProgramManager::build()`, the `NativePrograms` map
was getting populated by an extra entry. No duplicating entry was
being created in the `m_EliminatedKernelArgMasks`, which made the
image-based lookup in `ProgramManager::getEliminatedKernelArgMask()`
exit early. The returned empty `KernelArgMask` led to errors during
kernel argument setting whenever several native programs were created
(e.g. for `kernel_bundle` or device code split use cases).

Tested in intel/llvm-test-suite#575.

Signed-off-by: Artem Gindinson <artem.gindinson@intel.com>
Co-authored-by: Maksim Sabianin <maksim.sabianin@intel.com>

### CODE REVIEW

**Comment by AGindinson** [comment]
Converted back to draft - I've found that a) the duplicate native program is still created, b) the copy vs by-pointer mechanism is not actually what I've described. Will investigate deeper why the change **actually** helps the DAE handling.

**Comment by AGindinson** [comment]
CUDA compilation failures for reduction tests in Jenkins/llvm-test-suite do not seem to be related to either of my patches.

**Comment by bader** [comment]
> CUDA compilation failures for reduction tests in Jenkins/llvm-test-suite do not seem to be related to either of my patches.

FYI - https://github.com/intel/llvm/issues/5008.

**Review by romanovvlad — APPROVED** [review]

**Pull request merged**
