### PR TITLE
[SYCL-MLIR] Drop method definition registry

### PR DESCRIPTION
**Pull request by victor-eds**
Drop ability to store and load `SYCLMethodOp` definitions in the `sycl` dialect.

### CODE REVIEW

**Comment by victor-eds** [comment]
This is no longer used, as we will not lower these operations to function calls.

**Review by etiotto — APPROVED** [review]

**Review by whitneywhtsang — APPROVED** [review]

**Comment by whitneywhtsang** [comment]
Please look into the test failures.

**Comment by victor-eds** [comment]
`SYCL Pre Commit / Linux / OCL GEN9 LLVM Test Suite (pull_request_target` test failures seem unrelated to these changes.

**Comment by whitneywhtsang** [comment]
> `SYCL Pre Commit / Linux / OCL GEN9 LLVM Test Suite (pull_request_target` test failures seem unrelated to these changes.

It seems related, only showing up after this PR.
```
Timed Out Tests (1):
  SYCL :: SubGroup/scan_spirv13.cpp
```

**Comment by victor-eds** [comment]
> It seems related, only showing up after this PR, can you please look into it?

Test was failing right away before this change (error in registry). Now it times out. I'll make it fail early so we can look into it later with more detail

**Pull request merged**
