### PR TITLE
[SYCL-WEB] Update esimd tests due to opaque pointer

### PR DESCRIPTION
**Pull request by jsji**

### CODE REVIEW

**Comment by jsji** [comment]
This looks like a bug somewhere to me? But I am not sure, can someone from ESIMD team have a look and fix it? Thanks!

**Comment by sarnex** [comment]
@jsji Sorry, what do you mean by it looks like a bug? Is it because typed pointers has a vector but opaque has a ptr? If so I can take a look and confirm

**Comment by jsji** [comment]
> @jsji Sorry, what do you mean by it looks like a bug? Is it because typed pointers has a vector but opaque has a ptr? If so I can take a look and confirm

Yes, not sure why we changed a vector type into ptr here. Thanks!

**Comment by sarnex** [comment]
Will investigate!

**Comment by sarnex** [comment]
@jsji Good catch, it is a bug and I have a fix. How should we proceed? Should we merge this PR for now and I submit a PR to sycl-web/sycl later? Or should we drop this PR and I just make a PR for sycl-web? Thanks

**Comment by jsji** [comment]
> @jsji Good catch, it is a bug and I have a fix. How should we proceed? Should we merge this PR for now and I submit a PR to sycl-web/sycl later? Or should we drop this PR and I just make a PR for sycl-web? Thanks

Go ahead to make a PR for sycl-web, I will close this PR. Thanks!

**Pull request closed without merging**
