### PR TITLE
[SYCL][Bindless] 1D Image copy fix

### PR DESCRIPTION
**Pull request by cppchedy**
Fix copying problem for 1d images in both directions, from device to host and host to device.

### CODE REVIEW

**Comment by aarongreig** [comment]
@cppchedy https://github.com/oneapi-src/unified-runtime/pull/1240 has merged, please update

**Comment by cppchedy** [comment]
@aarongreig thanks, updated.

**Review by aarongreig — APPROVED** [review]
can you update the description as well

**Comment by aarongreig** [comment]
@intel/llvm-gatekeepers please merge

**Pull request merged**
