### PR TITLE
[SYCL][ESIMD] Miscellaneous cleanup for ESIMD Emulator

### PR DESCRIPTION
**Pull request by turinevgeny**
SYCL cmake cleanup;
remove emulator as supported device for e2e tests;
remove libdw1 dependency previously added for cm-cpu-emulation.

### CODE REVIEW

**Review by aelovikov-intel — APPROVED** [review]

**Comment by turinevgeny** [comment]
@intel/llvm-gatekeepers can this be merged? the problems seem to be unrelated to the patch.

```
Timed Out Tests (1):
  SYCL :: DeviceGlobal/device_global_unused_dis.cpp
```
```
#11 10.65 dpkg: error processing package intel-level-zero-gpu (--install):
#11 10.65  dependency problems - leaving unconfigured
#11 10.65 dpkg: dependency problems prevent configuration of intel-opencl-icd:
#11 10.65  intel-opencl-icd depends on intel-igc-opencl (= 1.0.14508.16); however:
#11 10.65   Version of intel-igc-opencl on system is 1.0.14828.8.
```

**Comment by aelovikov-intel** [comment]
I don't like failing CI Containers job...

**Comment by aelovikov-intel** [comment]
I'd suggest splitting out

> remove libdw1 dependency previously added for cm-cpu-emulation.

into a separate PR. Someone has to investigate what's going on with the containers job.

**Comment by turinevgeny** [comment]
> I'd suggest splitting out
> 
> > remove libdw1 dependency previously added for cm-cpu-emulation.
> 
> into a separate PR. Someone has to investigate what's going on with the containers job.

Ok, makes sense.

**Comment by turinevgeny** [comment]
@intel/llvm-gatekeepers, this PR should be ready to go.

**Pull request merged**
