### PR TITLE
[SYCL] Introduce external arbitrary fixed point functions

### PR DESCRIPTION
**Pull request by vmaksimo**
This change enables support of functions that operate on arbitrary precision
fixed point numbers. This datatype and its corresponding operations can be
useful on targets that can take advantage of narrower representation such as
FPGAs.

Arbitrary precision fixed point numbers are represented using arbitrary
precision integers (_ExtInt(N) wrapped in ap_int<N>). Additional parameters are:
* W - total width of the datatype. It's encoded in the width of the OpTypeInt.
* I - determines the position of the decimal point.
* S - determines if this is a signed or an unsigned number.

Usage example:
  ap_int<W> a;
  auto ap_fixed_Sqrt = __spirv_FixedSqrtINTEL<W,rW>(a, S, I, rI);
  // auto to be deducted to ap_int<rW>

### CODE REVIEW

**Comment by keryell** [comment]
That sounds like a good generic extension useful for others. :-)
Perhaps something to add as a KHR extension in SPIR-V?

**Comment by AlexeySachkov** [comment]
> That sounds like a good generic extension useful for others. :-)
> Perhaps something to add as a KHR extension in SPIR-V?

@keryell, here you go: https://github.com/intel/llvm/pull/1934. This is not a KHR one, but at least some starting point

**Comment by keryell** [comment]
Do you have a host device implementation for this too?

**Comment by MrSidims** [comment]
@keryell there will a wrapper headers around these SPIR-V builtins and this header will include host implementation.

**Pull request merged**
