### PR TITLE
[clang-offload-bundler] unification with the upstream LLVM [NFC]

### PR DESCRIPTION
**Pull request by sndmitriev**
Unify FileHandler interfaces with the upstream LLVM.

Signed-off-by: Sergey Dmitriev <serguei.n.dmitriev@intel.com>

### CODE REVIEW

**Comment by Fznamznon** [comment]
I believe we need a separate team of codeowners for clang-offload-wrapper and clang-offload-wrapper changes.

**Comment by kbobrovs** [comment]
> Unify FileHandler interfaces with the upstream LLVM.

@sndmitriev , could you please provide a link to the upstream with corresponding patch or provide some comments what this patch does?

**Comment by sndmitriev** [comment]
@kbobrovs, this is just a cleanup which does not change functionality. It makes FileHandler interface the same as in the llvm.org.

**Review by kbobrovs — APPROVED** [review]

**Comment by bader** [comment]
@sndmitriev, is there any reason to not contribute this patch to llorg? If not, I suggest committing to llorg instead. We regularly pull commits from llorg, so if patch lands there, it will appear eventually in `sycl` branch.

**Review by bader — APPROVED** [review]

**Comment by sndmitriev** [comment]
Do I need to do any additional changes to get this patch merged?

**Comment by bader** [comment]
> Do I need to do any additional changes to get this patch merged?

Could you answer the question below, please?

> @sndmitriev, is there any reason to not contribute this patch to llorg? If not, I suggest committing to llorg instead. We regularly pull commits from llorg, so if patch lands there, it will appear eventually in `sycl` branch.

**Comment by sndmitriev** [comment]
> > Do I need to do any additional changes to get this patch merged?
> 
> Could you answer the question below, please?
> 
> > @sndmitriev, is there any reason to not contribute this patch to llorg? If not, I suggest committing to llorg instead. We regularly pull commits from llorg, so if patch lands there, it will appear eventually in `sycl` branch.

Sure. This patch removes differences in FileHandler interface between llorg and sycl branch that were introduced to sycl branch long time ago. FileHandler interfaces that I am removing in this patch just do not exist in llorg, so it cannot be committed to llorg.

**Comment by bader** [comment]
> This patch removes differences in FileHandler interface between llorg and sycl branch that were introduced to sycl branch long time ago. FileHandler interfaces that I am removing in this patch just do not exist in llorg, so it cannot be committed to llorg.

I remember comparing llorg and sycl branches before posting my question, but it looks like I did something wrong, because I didn't that difference and I can see it. Sorry for the delay.

**Pull request merged**
