### PR TITLE
[E2E] Modify commands to address running on Windows.

### PR DESCRIPTION
**Pull request by mmoadeli**
Running the test on Windows failed due to missing support of `ls`. Replacing `ls` with `cat` made the test pass on Windows.

contributor @ldrumm

### CODE REVIEW

**Comment by mmoadeli** [comment]
@intel/llvm-reviewers-runtime, a friendly request to have this reviewed please.

**Comment by maarquitos14** [comment]
@mmoadeli Why are we dropping the last test where we run the test without the envvar and check that the dot files aren't there? Is this intended?

**Comment by mmoadeli** [comment]
> @mmoadeli Why are we dropping the last test where we run the test without the envvar and check that the dot files aren't there? Is this intended?

thank you @maarquitos14, that is put back.
@

**Review by maarquitos14 — APPROVED** [review]
LGTM.

**Pull request merged**
