### PR TITLE
[SYCL-MLIR] Enable raising host by default

### PR DESCRIPTION
**Pull request by Naghasan**
Make the host raising default when building for MLIR. The patch adds -fno-sycl-raise-host in order to opt out of raising.

### CODE REVIEW

**Review by victor-eds — APPROVED** [review]

**Comment by Naghasan** [comment]
@whitneywhtsang @etiotto I think we can merge this if you are ok with it

**Review by sommerlukas — APPROVED** [review]

**Comment by etiotto** [comment]
I am approving it because (1) functionality doesn't regresses and (2) there seems to be no performance impacts.

**Review by etiotto — APPROVED** [review]

**Comment by whitneywhtsang** [comment]
Do we need opaque pointer enabled before this? I remember I need to add `-Xclang -opaque-pointers` when I add `-fsycl-raise-host`.

**Comment by victor-eds** [comment]
> Do we need to fully support opaque pointer before this? I remember I need to add `-Xclang -opaque-pointers` when I add `-fsycl-raise-host`.

That's in the host. We don't need full support in the device

**Comment by Naghasan** [comment]
> Do we need to fully support opaque pointer before this? I remember I need to add -Xclang -opaque-pointers when I add -fsycl-raise-host.

That's for the host only, however that made me realize my rebase went very wrong and the patch didn't force that. The new patch is doing this.

**Comment by Naghasan** [comment]
@whitneywhtsang patch is good for you ?

**Comment by whitneywhtsang** [comment]
> @whitneywhtsang patch is good for you ?

Yes, good for me.

**Pull request merged**
