### PR TITLE
[SYCL] Remove a parsing error and make it a semantic error

### PR DESCRIPTION
**Pull request by AaronBallman**
The SYCL loop attributes can only be applied to a for, do, or while
statement. However, we would diagnose this as a parsing error rather
than a semantic error. Attribute appertainment of [[]] attributes is
handled as a semantic error to avoid potentially changing the parsing
paths in the presence of an [[]] attribute.

As part of this change, I also corrected the attribute definitions to
properly reflect that these are statement attributes and have a
specific subject list. However, Clang's automated diagnostics focus
primarily on declaration attributes, so this change is mostly for
code readability rather than correctness (for the moment).

### CODE REVIEW

**Comment by AaronBallman** [comment]
Question: why is the CI running clang-format on *test files*? (That seems like a really odd decision given that the community doesn't require formatting of their test files and frequently test files *can't* be formatted the way clang-format wants because of the nature of some tests (like lexing and preprocessing tests).

**Comment by bader** [comment]
> Question: why is the CI running clang-format on _test files_? (That seems like a really odd decision given that the community doesn't require formatting of their test files and frequently test files _can't_ be formatted the way clang-format wants because of the nature of some tests (like lexing and preprocessing tests).

When I added clang-format check, I took the logic from the community script. I haven't tracked what has changed since then. Could you open an issue to filter out clang/test directory, please?

**Comment by AaronBallman** [comment]
> > Question: why is the CI running clang-format on _test files_? (That seems like a really odd decision given that the community doesn't require formatting of their test files and frequently test files _can't_ be formatted the way clang-format wants because of the nature of some tests (like lexing and preprocessing tests).
> 
> When I added clang-format check, I took the logic from the community script. I haven't tracked what has changed since then. Could you open an issue to filter out clang/test directory, please?

I opened #3159, thanks for the suggestion. Perhaps I'm wrong on the community stuff, as I've not looked at their scripts in a long while, but in terms of community *review* process, we largely ignore formatting in test files unless the formatting is truly obnoxious for some reason.

**Comment by bader** [comment]
They seem to filter test directories indeed. https://github.com/google/llvm-premerge-checks/blob/main/scripts/clang-format.ignore

**Review by smanna12 — APPROVED** [review]
Thanks. LGTM!

**Review by elizabethandrews — APPROVED** [review]
I'm not very familiar with TableGen, so I'm not really sure what's going on there. But otherwise, the changes LGTM. Thanks!

**Comment by AaronBallman** [comment]
> I'm not very familiar with TableGen, so I'm not really sure what's going on there. But otherwise, the changes LGTM. Thanks!

The tablegen bits are so that we can have the actual subject lines in Attr.td without causing errors. My long-term plan is to start extending more of the table generated checking code that we have for declarations into also working for statements (I think I'll eventually need that for some planned OpenMP work as well).

An alternative would be for me to leave the tablegen bits out and comment out the `Subject` lines in Attr.td, if that's preferred.

**Comment by elizabethandrews** [comment]
> An alternative would be for me to leave the tablegen bits out and comment out the `Subject` lines in Attr.td, if that's preferred.

I like the increased readability, even if it lacks functionality at the moment. I don't see the harm keeping it in except for maybe confusing a developer who isn't familiar with the code base? I don't have a strong preference either way. So I leave it up to you and @premanandrao.

**Comment by AaronBallman** [comment]
> > An alternative would be for me to leave the tablegen bits out and comment out the `Subject` lines in Attr.td, if that's preferred.
> 
> I like the increased readability, even if it lacks functionality at the moment. I don't see the harm keeping it in except for maybe confusing a developer who isn't familiar with the code base? I don't have a strong preference either way. So I leave it up to you and @premanandrao.

Then I'd say let's leave it in for now.

**Pull request merged**
