### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW39)

### PR DESCRIPTION
**Pull request by dbudanov-cmplr**
LLVM: llvm/llvm-project@6b0b306
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@3938c74

### CODE REVIEW

**Comment by pvchupin** [comment]
Windows check-clang issue is was fixed in https://github.com/intel/llvm/pull/6938

@kbobrovs, @v-klochkov , can you take a look into
```
Timed Out Tests (1):
  SYCL :: ESIMD/dword_atomic_cmpxchg.cpp
```

**Comment by kbobrovs** [comment]
I took a look. The root cause is a test problem, patch is on the way.

**Comment by kbobrovs** [comment]
> I took a look. The root cause is a test problem, patch is on the way.

Fix: https://github.com/intel/llvm-test-suite/pull/1304

**Comment by pvchupin** [comment]
With the last test fix merged this looks clean now

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Tue 04 Oct 2022 04:03:15 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Tue 04 Oct 2022 04:06:58 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
