### PR TITLE
[SYCL][Matrix] fix the bug in element_wise_all_ops_tf32_impl.hpp

### PR DESCRIPTION
**Pull request by yubingex007-a11y**

### CODE REVIEW

**Comment by yubingex007-a11y** [comment]
previously, it can pass because TK=TN=16; now we change TK=8.
anyway sub_a should use TN instead of TK

**Comment by yubingex007-a11y** [comment]
@arnamoy10 @YuriPlyakhin ping?

**Comment by arnamoy10** [comment]
@yubingex007-a11y The JM dimension of Mat A type should be 8x8, not 8x16.  Changing the JM dimension to TMxTN to let the testcase to pass should not be the right approach.  Probably the CPU implementation of tf32 has to change?

Currently this test fails on GPU (`XFAIL` is given for that in the testcase already).  It fails on GPU because we do not have lowering support of round_to_tf32 yet in IGC.

**Comment by yubingex007-a11y** [comment]
> @yubingex007-a11y The JM dimension of Mat A type should be 8x8, not 8x16. Changing the JM dimension to TMxTN to let the testcase to pass should not be the right approach. Probably the CPU implementation of tf32 has to change?
> 
> Currently this test fails on GPU (`XFAIL` is given for that in the testcase already). It fails on GPU because we do not have lowering support of round_to_tf32 yet in IGC.

OK, if you feel it is ok, please approve the PR

**Review by arnamoy10 — APPROVED** [review]
LGTM

**Comment by yubingex007-a11y** [comment]
@intel/llvm-reviewers-runtime ping

**Comment by aelovikov-intel** [comment]
> @intel/llvm-reviewers-runtime ping

There is nothing for @intel/llvm-reviewers-runtime here, what you need is an approval from one of https://github.com/intel/llvm/blob/a63f07ccbda292cab2b260e22a1a7483e39f61d4/.github/CODEOWNERS#L106-L107

**Comment by yubingex007-a11y** [comment]
@YuriPlyakhin ping?

**Pull request closed without merging**
