### PR TITLE
[SYCL][E2E] Fix one of the compfails of TaskSequence tests

### PR DESCRIPTION
**Pull request by dm-vodopyanov**
This patch fixes errors like "call to 'XXX' is ambiguous" and also disables all TaskSequence tests on Windows because they fail in the same way as on Linux. Github issue was created against that and comment in tests was updated.

### CODE REVIEW

**Comment by dm-vodopyanov** [comment]
@cperkinsintel @intel/llvm-reviewers-runtime - gentle ping

**Review by KseniyaTikhomirova — APPROVED** [review]
LGTM

**Review by KseniyaTikhomirova — COMMENTED** [review]
sycl/test-e2e/TaskSequence/struct-array-args-and-return.cpp l116 - should we specify namespace for "abs" call too?

**Comment by dm-vodopyanov** [comment]
> sycl/test-e2e/TaskSequence/struct-array-args-and-return.cpp l116 - should we specify namespace for "abs" call too?

It does not affect the test compilation on Windows, but I will change it for consistency, thanks.

**Comment by dm-vodopyanov** [comment]
> > sycl/test-e2e/TaskSequence/struct-array-args-and-return.cpp l116 - should we specify namespace for "abs" call too?
> 
> It does not affect the test compilation on Windows, but I will change it for consistency, thanks.

Applied.

**Pull request merged**
