### PR TITLE
[BuildBot] Uplift GPU RT version for Linux CI Process

### PR DESCRIPTION
**Pull request by bb-sycl**
Uplift GPU RT version for Linux to 20.47.18513

### CODE REVIEW

**Review by bader — CHANGES_REQUESTED** [review]
Tests are failing.
We should either wait for a driver update fixing the regression or apply a workaround I suggested here: https://github.com/intel/llvm/pull/2807#issuecomment-735216459

**Comment by dm-vodopyanov** [comment]
Please check if PR #2851 fixes the uplifting after being merged.

**Comment by bader** [comment]
> Please check if PR #2851 fixes the uplifting after being merged.

Please, add your patch to this PR, CI system can validate the fix.

**Comment by bader** [comment]
It works. @dm-vodopyanov, I suggest closing #2851 and commit both patches from this PR if #2851 pre-commit pass. What do you think?

**Review by bader — APPROVED** [review]

**Comment by dm-vodopyanov** [comment]
@bader sounds good to me, closed #2851

**Comment by bader** [comment]
> Can it be run for this PR?

You can still use #2851 results for loader version update validation.
But it must be done for this PR for a different reason - we run these tests any driver update.

**Review by smaslov-intel — APPROVED** [review]

**Comment by yanfeng3721** [comment]
Regression detected by post commit CTS test, the mismatch information is as below:
--- math_builtin_float_double
SYCL_PI_TRACE[basic]: Plugin found and successfully loaded: libpi_opencl.so
SYCL_PI_TRACE[basic]: Plugin found and successfully loaded: libpi_level_zero.so
SYCL_PI_TRACE[all]: Selected device ->
SYCL_PI_TRACE[all]:   platform: Intel(R) Level-Zero
SYCL_PI_TRACE[all]:   device: Intel(R) Graphics Gen9 [0x3e98]
  . value: 0.8986363237370140755189140691072680056095123291015625 [3fecc1a0f6ae5732], reference: 0.89863632373701440858582145665423013269901275634765625 [3fecc1a0f6ae5735]
  . line: 152
  . tests case: 4600071. Correctness check failed.
  - fail

**Comment by yanfeng3721** [comment]
Hi @bader , the same test can pass with 20.46.18421, so could it possible to reopen https://github.com/intel/llvm/pull/2807 for uplift? 

> Regression detected by post commit CTS test, the mismatch information is as below:
> [2020-12-03T04:56:53.545Z] 48: --- math_builtin_float_double
> [2020-12-03T04:56:59.299Z] 48: . value: 0.8986363237370140755189140691072680056095123291015625 [3fecc1a0f6ae5732], reference: 0.89863632373701440858582145665423013269901275634765625 [3fecc1a0f6ae5735]
> [2020-12-03T04:56:59.299Z] 48: . line: 152
> [2020-12-03T04:56:59.299Z] 48: . tests case: 4600071. Correctness check failed.
> [2020-12-03T04:57:38.741Z] 48: - fail

**Comment by bader** [comment]
@yanfeng3721, it's quite possible a CTS bug, not DPC++.
I'm okay to merge https://github.com/intel/llvm/pull/2807, while this issue is being investigated.

**Review by bader — CHANGES_REQUESTED** [review]
To fix SYCL-CTS failures.

**Pull request closed without merging**
