### PR TITLE
[Driver][NFC] Fix typo in code comments

### PR DESCRIPTION
**Pull request by keryell**

### CODE REVIEW

**Review by bader — APPROVED** [review]
Thanks!

**Review by mdtoguchi — APPROVED** [review]

**Comment by keryell** [comment]
I have just tried the inline editor of GitHub...
I need to force-push the commit message with the right message suggested by @bader.

**Comment by bader** [comment]
> I have just tried the inline editor of GitHub...
> I need to force-push the commit message with the right message suggested by @bader.

I usually use PR title+description as squashed commit message, so you can edit PR title/description in web-browser.

**Comment by keryell** [comment]
OK, thanks.
At the end, I am not convinced by this funny on-line edit since I had already an LLVM fork but it created a new one...

**Pull request merged**
