### PR TITLE
[SYCL] Support stdlib function abs, labs, llabs in device library

### PR DESCRIPTION
**Pull request by haonanya**
Signed-off-by: haonanya <haonan.yang@intel.com>

### CODE REVIEW

**Comment by haonanya** [comment]
The lit test PR is: https://github.com/intel/llvm-test-suite/pull/184

**Review by vzakhari — APPROVED** [review]

**Review by jinge90 — APPROVED** [review]

**Comment by jinge90** [comment]
Hi, @kbobrovs , @AlexeySachkov , @intel/llvm-reviewers-runtime 
Could you help review this PR?
Thanks very much.

**Review by s-kanaev — APPROVED** [review]
RT part LGTM

**Review by kbobrovs — APPROVED** [review]

**Pull request merged**
