### PR TITLE
[SYCL][ESIMD] Remove redundant tests that emit IR

### PR DESCRIPTION
**Pull request by sarnex**
We already have the exact same tests in compile-only tests:

https://github.com/intel/llvm/blob/26e449331e0d60a80da9a0f572050f371214177f/sycl/test/esimd/vec_arg_call_conv_ext.cpp#L4 https://github.com/intel/llvm/blob/26e449331e0d60a80da9a0f572050f371214177f/sycl/test/esimd/vec_arg_call_conv_smoke.cpp#L4

### CODE REVIEW

**Comment by v-klochkov** [comment]
Those existing tests are compile-only tests.
It seems reasonable to keep the tests being deleted in this PR, but remove all the "CHECK" lines. It should verify that the tests run without SegFault or other JIT compile error caused by the transformation.

**Comment by sarnex** [comment]
@v-klochkov today the tests in sycl-e2e don't compile to a full executable or run on the GPU.

Test 1 commands: 
```
// RUN: %clangxx -fsycl -Xclang -opaque-pointers -fsycl-device-only -Xclang -emit-llvm -o %t.comp.ll %s
// RUN: sycl-post-link -ir-output-only -lower-esimd -S %t.comp.ll -o %t.out.ll
// RUN: FileCheck --input-file=%t.out.ll %s
```


Test 2 commands:
```
// RUN: %clangxx -fsycl -Xclang -opaque-pointers -fsycl-device-only -Xclang -emit-llvm -o %t.comp.ll %s
// RUN: sycl-post-link -ir-output-only -lower-esimd -S %t.comp.ll -o %t.out.ll
// RUN: FileCheck --input-file=%t.out.ll %s
```

The tests don't contain enough code to compile into a full executable either, there's no host code at all.

**Comment by v-klochkov** [comment]
> e time when compile-only tests went into llvm-test-suite and

Ok, Yes, I missed the fact that there was no host code in those tests. Let's remove these 2 tests then.
vadd_usm_opqptr.cpp should be a runnable test for the transformation. Also, we'll get way more tests when enable opaque pointers.

**Review by v-klochkov — APPROVED** [review]

**Comment by v-klochkov** [comment]
The test fail is unrelated to this PR (that only removes 2 other LIT tests):
  SYCL :: Basic/memory-consumption.cpp

**Pull request merged**
