### PR TITLE
LLVM and SPIRV-LLVM-Translator pulldown (WW11 2024)

### PR DESCRIPTION
**Pull request by sys-ce-bb**
LLVM: llvm/llvm-project@ccd16085f70105d457f052543d731dd51089945b
SPIRV-LLVM-Translator: KhronosGroup/SPIRV-LLVM-Translator@d54f77c5dd695ccd2a4acf657a0fae74c64413d2

### CODE REVIEW

**Comment by jsji** [comment]
This is ready for review.
- [ ] [Fix test after ClangOffloadBundler change](https://github.com/intel/llvm/pull/13025/commits/0fa4ec011b263843df5a7d6aea8d7818b66f49dc) @intel/dpcpp-tools-reviewers  @LU-JOHN

**Review by maksimsab — APPROVED** [review]
LGTM

**Comment by jsji** [comment]
Thanks @maksimsab .

@bader @intel/llvm-gatekeepers This is ready for merge. Thank you.

**Review by bb-sycl — APPROVED** [review]

**Comment by bb-sycl** [comment]
Mon 18 Mar 2024 05:05:14 PM UTC --- Start to merge the commit into sycl branch. It will take several minutes.

**Comment by bb-sycl** [comment]
Mon 18 Mar 2024 05:10:31 PM UTC --- Merge the branch in this PR to base automatically. Will close the PR later.

**Pull request merged**
