### PR TITLE
Change SYCL_PI_TESTS to SYCL_UR_TESTS in CI

### PR DESCRIPTION
**Pull request by omarahmed1111**
`SYCL_PI_TESTS` was deprecated and changed to `SYCL_UR_TESTS`.

### CODE REVIEW

**Review by kbenzie — APPROVED** [review]

**Review by RossBrunton — APPROVED** [review]

**Review by sarnex — APPROVED** [review]

**Comment by omarahmed1111** [comment]
@intel/llvm-gatekeepers please merge, Thanks!

**Comment by AlexeySachkov** [comment]
I think that the better change would  be to completely drop the option:

https://github.com/intel/llvm/blob/21018abfa8e86dc2f5e6b6cfa02fbfae2b807912/sycl/unittests/CMakeLists.txt#L28

This comment is totally outdated, because the only UR unit-test we have is:

https://github.com/intel/llvm/blob/21018abfa8e86dc2f5e6b6cfa02fbfae2b807912/sycl/unittests/ur/UrUtility.cpp#L18-L24

The option seems to be some kind of legacy and that single test we have should be enabled by default

**Comment by omarahmed1111** [comment]
> I think that a better change would be to completely drop the option:
> 
> https://github.com/intel/llvm/blob/21018abfa8e86dc2f5e6b6cfa02fbfae2b807912/sycl/unittests/CMakeLists.txt#L28
> 
> This comment is totally outdated, because the only UR unit-test we have is:
> 
> https://github.com/intel/llvm/blob/21018abfa8e86dc2f5e6b6cfa02fbfae2b807912/sycl/unittests/ur/UrUtility.cpp#L18-L24
> 
> The option seems to be some kind of legacy and that single test we have should be enabled by default

That make sense, removed the option.

**Review by AlexeySachkov — APPROVED** [review]

**Comment by omarahmed1111** [comment]
@intel/llvm-gatekeepers please merge, Thanks!

**Pull request merged**
