### PR TITLE
[SYCL][COMPAT] Add one helper function get_local_mem_size() to get local memory size

### PR DESCRIPTION
**Pull request by tomflinda**
Signed-off-by: chenwei.sun <chenwei.sun@intel.com>

### CODE REVIEW

**Review by zhimingwang36 — APPROVED** [review]

**Review by zhiweij1 — APPROVED** [review]

**Review by Alcpz — APPROVED** [review]

**Review by Alcpz — CHANGES_REQUESTED** [review]
Can you add the signature to the documentation?

**Comment by tomflinda** [comment]
> Can you add the signature to the documentation?

Okay

**Comment by tomflinda** [comment]
> Can you add the signature to the documentation?

okay, will do that。

**Review by Alcpz — APPROVED** [review]
Thanks for the changes

**Comment by tomflinda** [comment]
@intel/llvm-gatekeepers  This PR is ready for merging. Thanks!

**Pull request merged**
