### PR TITLE
[SYCL-E2E] Re-enable a bunch of working tests

### PR DESCRIPTION
**Pull request by RossBrunton**
Fixes [14795](https://github.com/intel/llvm/issues/14795), [14749](https://github.com/intel/llvm/issues/14749), [14804](https://github.com/intel/llvm/issues/14804), [14805](https://github.com/intel/llvm/issues/14805)

### CODE REVIEW

**Review by dkhaldi — COMMENTED** [review]
Since the issue has been resolved, please make sure you don't xfail the two other tests in SG32 for PVC as mentioned in https://github.com/intel/llvm/issues/14598#issuecomment-2259137281

**Comment by RossBrunton** [comment]
> Since the issue has been resolved, please make sure you don't xfail the two other tests in SG32 for PVC as mentioned in [#14598 (comment)](https://github.com/intel/llvm/issues/14598#issuecomment-2259137281)

None of the SG32 tests were marked as XFAIL as part of the PI->UR work as far as I can tell.

**Review by uditagarwal97 — APPROVED** [review]

**Comment by omarahmed1111** [comment]
@intel/llvm-gatekeepers Please merge when possible, Thanks!

**Comment by steffenlarsen** [comment]
@RossBrunton - It doesn't appear that Github is smart enough to auto-close the last 3 linked issues, like it was able to auto-close https://github.com/intel/llvm/issues/14795. Not a big deal, just an interesting note in case it becomes relevant in the future.

**Pull request merged**
